### ISSUE TITLE
backspace doesn't re-evaluate recipients - leaving compose in unusable state

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1001]
1) add recipient that has pgp
2) add second one that doesn't (gray email)
3) password box pops up
4) backspace-remove last recipient
5) password box does not go away

**Comment by tomholub** [comment]
The work here should be in `js/common/composer.ts`. It's a messy file to be working at if you are new to the codebase, but with a `console.log` here and a `debugger;` there, you should be able to find your way around it enough to fix this issue relatively elegantly.

**Comment by evanhellmuth** [comment]
Claiming this issue.
