### ISSUE TITLE
signed messages formatting in footer - broken

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1038]
Example - put this in footer, then send a signed message

```
________________________________________________________________________
* To send me encrypted email and attachments, go to https://FlowCrypt.com/me/TESting
________________________________________________________________________
```

**Comment by tomholub** [comment]
Repro: having the footer above seems to prevent us from verifying signatures, due to length of word too long combined with how Gmail rapes our messages and folds them

The solution is to apply rules to the text before signing (eg maybe hard-wrap words that are too long), then sign the changed version. That way Gmail won't mess up the msg in transit.

**Comment by tomholub** [comment]
@michael-volynets you can take a stab at this, but don't give it more than a day. It may be frustrating. After a day, if not resolved, please note down here what you tried and what didn't work, and what other things would you try.

**Comment by michael-volynets** [comment]
The footer should be outside the signed message? 
![image](https://user-images.githubusercontent.com/49104848/60188079-61074380-9837-11e9-92aa-e50f984d8e12.png)

Can you please clarify the issue because I can't understand exactly the point of the issue?
Thanks

**Comment by tomholub** [comment]
It should be inside, but it should pass verification. Try to load the
signing pubkey into contacts, then see if it verifies the signature in
green.

The issue was that it would fail signature verification, and show in red.

But that will only manifest with the pubkey first loaded for verification.
(Else shows gray as on the screenshot)

**Comment by michael-volynets** [comment]
I've fixed it according to the way you suggested (Hard-wrapping words) and it works now but when I was testing it I found one interesting thing.
The only change I made to fix it is to replace footer with this regex:
```TS
 $('.action_add_footer').click(Ui.event.prevent('double', async self => {
    const footer = `${String($('.input_email_footer').val())}`.replace(/([^\n]{1,80})\s/g, '$1\n');
```
Then I wanted to test how it will work with this footer:
```
________________________________________________________________________
* To send me encrypted email and attachments, go to https://FlowCrypt.com/me/testesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestest
________________________________________________________________________
```
And the result was unexcpected to me:
![image](https://user-images.githubusercontent.com/49104848/60262026-ec3f1280-98e5-11e9-991f-036e94141cec.png)

As you can see, the link takes the whole space but the signature was decrypted correctly but if I remove the regex the sign won't work.
Perhaps the issue isn't related to long lines? 
What do you think?

**Comment by tomholub** [comment]
I'm not sure. Fundamentally, the issue is that Gmail edits the messages in transit, but only sometimes. Maybe whatever the regex did somehow helped. 

Though I'm not sure what the regex does. I would have expected `/([^\n\s]{1,80})/g` or something like that.

**Comment by michael-volynets** [comment]
I've checked the plain message before the send and after I received it, and the 
`-----BEGIN PGP SIGNATURE-----` block is exactly the same. 
Also, I send the message (without regex replacement) but using this footer (there is a new line after `, go to`):
```
________________________________________________________________________
* To send me encrypted email and attachments, go to 
https://FlowCrypt.com/me/testesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestesttestest
________________________________________________________________________
```
And this was successfully verified

I think Gmail doesn't mess up the message in transit and the issue is somewhere in our code base.
I will try to investigate it.

**Comment by michael-volynets** [comment]
Do you know the way to debug `decrypt` function in the `pgp.ts` file? 
Because any `console.log`s and debuggers don't work there

**Comment by tomholub** [comment]
They are processed in the background. Go to chrome://extension, then click on the extension, and you'll see a _background_page.htm link, which will open the console

**Comment by tomholub** [comment]
Remember, for background script to reload, you have to manually reload the extension with the refresh button, else your code changes will not reflect.

**Comment by michael-volynets** [comment]
Ahah, I found the issue. You were right. Gmail wraps text at column 72 in plain/text mode. 
I tried to fix it by adding some headers to the email message but it didn't help. 
So the only way to fix it is to replace long lines before the message was sent.
I will change from `80`  characters to `72` in the RegExp
