### ISSUE TITLE
match the sizes of secure and standard compose buttons

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1054]
> Great app. Please change the Secure Compose button to be the same width as the standard compose button!!

> The text "secure compose" wouldn't fit in it. But we could extend the original compose button to match. 

> That would work great. Everything else is working incredibly well.

https://mail.google.com/mail/u/0/#inbox/16292f00a5b6abe0

**Comment by mondo989** [comment]
<img width="457" alt="screen shot 2018-04-18 at 8 46 09 pm" src="https://user-images.githubusercontent.com/3431871/38970547-fc675af6-434a-11e8-8cc3-1261292312d1.png">

This might be little difficult given we're using the same font size '11px' as the native Compose button...
Unless if we were to somehow give the native Compose button a little more padding? 

However, when I bring the 'secure compose' font size down to 10px, here's what happens...
<img width="196" alt="screen shot 2018-04-18 at 9 01 02 pm" src="https://user-images.githubusercontent.com/3431871/38970666-a50a9222-434b-11e8-8c57-dbaeb1579c7f.png">

10px doesn't look bad.

**Comment by tomholub** [comment]
I was thinking to give Compose a min-width to match the secure compose - that should do it

**Comment by tomholub** [comment]
You can do it in gmail.css

**Comment by mondo989** [comment]
I'd say we're all set here, considering the UI update for Gmail. 
(Reopen if it needs attention.)
