### ISSUE TITLE
When copying + pasting content, pasted content is appended to previous content. 

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#1060]
When Copying + Pasting some content,
'Select All' of the content,
Paste Again.

Expecting the Pasted content to override all previous content, instead pasted content is appended to previous content...

![apr-18-2018 20-45-02](https://user-images.githubusercontent.com/3431871/38970394-1eaaa7e0-434a-11e8-8df6-c8b1108eb57d.gif)

**Comment by tomholub** [comment]
Check this one out: #771 closing as duplicate :)
