### ISSUE TITLE
Clicking 'Proceed with Send Only' bug

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#1062]
To Replicate:
- Create new account.
- Click the signin with gmail button 
- Close modal, then Permissions Modal appears
- Click proceed with 'Send Only'

![bug](https://user-images.githubusercontent.com/3431871/39112349-11c2fc08-468d-11e8-9e52-b1aa33ced860.gif)

#Rapidfire

**Comment by tomholub** [comment]
Nice

**Comment by tomholub** [comment]
Seems to work now, maybe since fixed
