### ISSUE TITLE
Attestor / wrong public key recorded / Imported my own private key

### ISSUE THREAD

**Issue by fsantiago07044** [FlowCrypt/flowcrypt-browser#1063]
Hello. I signed up via your chrome extension. I chose to import my own existing private key. Now, when I click on attestor, it reports wrong public key recorded. I see the button request attestation, but it doesn't appear to do anything except land me back on the same message. How can I fix this? Thanks.

**Comment by tomholub** [comment]
Hello, after when you clicked the "request attestation" button, did you receive an email? If yes, opening the email will help. If not, please email me at human@flowcrypt.com with the link to this issue so that I know your email address.

**Comment by fsantiago07044** [comment]
On April 25, 2018 3:43:17 AM EDT, Tom J <notifications@github.com> wrote:
>Hello, after when you clicked the "request attestation" button, did you
>receive an email? If yes, opening the email will help. If not, please
>email me at human@flowcrypt.com with the link to this issue so that I
>know your email address.

Email sent. Thanks.
--

Fabian A. Santiago

OpenPGP:

0x643082042dc83e6d94b86c405e3daa18a1c22d8f (current key)
 0x3c3fa072accb7ac5db0f723455502b0eeb9070fc (to be retired / revoked)

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/FMfcgxmZVPZQlBVvZvLjWNBljPqRkCJH
public key is correctly reported so that it's not hight priority
But it shows a possible compatibility issue that may affect others too

**Comment by tomholub** [comment]
#1661
