### ISSUE TITLE
Contacts page seem to do nothing

### ISSUE THREAD

**Issue by chuacw** [FlowCrypt/flowcrypt-browser#1064]
The contacts page (in Firefox 59)  seem to do nothing. If it is loading contacts, it should show some visual progress.

See attached screenshot.

![contacts and their public keys - 2018-04-25 12_42_02-flowcrypt](https://user-images.githubusercontent.com/1757930/39226678-8579a822-4886-11e8-969b-15fa76aff875.png)

**Comment by tomholub** [comment]
Maybe there are no contacts yet. When you F12 then click "Console", does it show any errors after reloading the page?

**Comment by chuacw** [comment]
Hi,

I've already sent 2 encrypted email, so there's at least 2 contacts.
No errors in the console.

**Comment by tomholub** [comment]
Are you using Private Browsing Mode, Containers or a similar mechanism?

**Comment by chuacw** [comment]
I have containers and private browsing mode, but no, they're not activated for the issue I've reported.
Is there some way I can help you figure this out? Any logs I can help generate or something?

**Comment by tomholub** [comment]
I've also seen your email - just want to confirm - the contacts never end up loading, correct?

1) go to about:debugging
2) next to flowcrypt, click "debug"
3) it will show a scary looking prompt, but this is only for local debugging. Click ok
4) do you see any errors there?
5) try to open the contacts page again - any new errors show?
6) try to restart the browser completely - does it improve?

**Comment by chuacw** [comment]
I can't click on Debug, as there's an error there.

![flowcrypt - 2018-04-25 16_07_02-debugging with firefox developer tools](https://user-images.githubusercontent.com/1757930/39233391-c8471092-48a2-11e8-9bf7-2430f5c5437a.png)

I'll restart the browser and see if it works.

**Comment by chuacw** [comment]
Here's the errors:

[The operation failed for reasons unrelated to the database itself and not covered by any other error code.]
db_open@moz-extension://0e95628a-abda-4391-9037-1ffa94a0b766/js/common/storage.js:327:23
@moz-extension://0e95628a-abda-4391-9037-1ffa94a0b766/js/background_process/background_process.js:29:1

catcher.log: db corrupted, skipping: db_contact_search

Seems like the db is corrupted. Any way to delete the database, and re-import?

**Comment by chuacw** [comment]
Ok, I deleted storage.js (which appears to store all relevant data) under the firefox@cryptup.io directory, and recovered using my passphrase.

Contacts still do not show up. The storage.js doesn't appear to be corrupted. My pass phrase is stored in plaintext in storage.js as well, it appears.

**Comment by tomholub** [comment]
Interesting. Thanks for the detailed info

**Comment by tomholub** [comment]
todo:
 - test on firefox 59.0.2
 - make sure to surface errors on contacts page

**Comment by tomholub** [comment]
Sorry for the non-action, is this still giving you trouble @chuacw ?

**Comment by chuacw** [comment]
I don't use Firefox 59.0.2 already, @tomholub and I'm not using FlowCrypt at the moment, so no issues currently. :)

**Comment by tomholub** [comment]
Got it. I'll close it for now until someone encounters it again.
