### ISSUE TITLE
bcc and cc

### ISSUE THREAD

**Issue by chuacw** [FlowCrypt/flowcrypt-browser#1065]
Is there no BCC, and CC available when sending emails?

**Comment by tomholub** [comment]
Not yet. I have a list of users who are interested in this, I'll leave this open to track the progress. Thanks.

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#sent/FMfcgxwBTjvMwPmdNCmSVkvHtRwndRph

**Comment by tomholub** [comment]
This is a relatively UI-heavy change. The result should work very similarly to what our Android app does with cc/bcc.

**Comment by tomholub** [comment]
This should also support drag and drop between to:, cc: and bcc:, else it's hard to use.

**Comment by chuacw** [comment]
That's true. The program model and user model needs to match here.

**Comment by tomholub** [comment]
This is a relatively large change, and will need thorough tests added.

**Comment by michael-volynets** [comment]
@tomholub Can you please share the screenshot of Flowcrypt Android App where I can see BCC/CC?

**Comment by tomholub** [comment]
I recommend to download the app and test it out (do you have an android phone?) so that you can mimic the whole interaction. There is a down chevron on the right side next to recipient, which you can click to view cc and bcc options.

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/61883309-b479b980-aee9-11e9-983d-64a2505ed0ff.png)

Can otherwise follow Gmail

**Comment by michael-volynets** [comment]
In this issue, I will also refactor `composer-contacts.ts` to make it easier to understand code and to make the logic with `CC/BCC` similar to `to`, (perhaps I will have to delete `parserenderRecipients` and rewrite or split it)

**Comment by tomholub** [comment]
Of course. Is it possible to refactor it in a separate PR with no functionality change? I know it will be more work for you, but it will be much easier for me to review, and therefore less likely that a mistake will slip through.

**Comment by michael-volynets** [comment]
Yes, sure,

Okay, I will try to refactor it in separate PR

**Comment by tomholub** [comment]
Great. Let's do the refactor first, then you'll add new functionality after that.

**Comment by michael-volynets** [comment]
@tomholub, will we allow users to add the same email address to the to/cc/bcc if the email was already added in another input?
I checked how Gmail does it and they allow to do it but they even allow to add the same email addresses in one input.

In my opinion, it doesn't make sense to allow doing it but there maybe there are some situations that I don't know where it will be useful

**Comment by tomholub** [comment]
I'm not sure, doesn't make much sense to me either. I wonder if a total noob user would go bothering Google that "their recipient won't add" when they already added him/her 3 times. So maybe it's a UX thing. Hard to say, but for now I'd say don't add any special logic (things that add more code) to handle recipients duplicate in cc/bcc. It's not a big deal.

**Comment by michael-volynets** [comment]
CC is working now but I've got a problem with BCC.
We are using an old version of `emailjs-mime-builder` and to make it work I need to update it to the newer one.

I will create another PR for that

**Comment by tomholub** [comment]
We use a fork of emailjs, basically. I made some changes to it. So it may be a bit more difficult than that. What issues does the old one have bcc in particular?

**Comment by michael-volynets** [comment]
In the newer version, they accept this option `includeBccInHeader` (https://github.com/emailjs/emailjs-mime-builder/blob/master/dist/builder.js#L98) and we don't have this option because we use an older version so we always skip bcc here:
https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/lib/emailjs/emailjs-mime-builder.js#L399

Could you please give me access to the forked repository to make this change and update our `emailjs-mime-builder.js`

**Comment by michael-volynets** [comment]
I think we can even remove that `case`

**Comment by tomholub** [comment]
It's not exactly a forked repository, I simply edited the source files in place :blush:  ... I think, if you can, please ship this feature without BCC first. I think I will need to be involved in updating emailjs, which I planned to do for a long time anyway. But not right now, my life is a bit hectic atm

**Comment by michael-volynets** [comment]
Sure, okay I will change it in our file

**Comment by tomholub** [comment]
Finally merged the refactor. So again, please let's ship this as CC option only. Leave BCC for another day, after I upgrade emailjs.

**Comment by michael-volynets** [comment]
Why? I think if you have already edited emailjs, so I can edit it too, according to the current version, there are only about 5-6 lines of code I need to add to make BCC working

**Comment by tomholub** [comment]
Ok, if it is a very small change, we could do that.

**Comment by michael-volynets** [comment]
@tomholub, It's ready for review,

One thing I have done without asking you is I removed this arrow in the top-right corner:
![image](https://user-images.githubusercontent.com/49104848/64080989-671c1380-cd03-11e9-8bed-f127116c7e01.png)

because it brought me some problems with CSS and I didn't want to spend a lot of time on that.
Now it immediately opens emails aliases in the reply box (the same way like you open a compose window from the button in Gmail sidebar). If it isn't okay for you (if you want to leave that arrow) so I can somehow try to fix that.
