### ISSUE TITLE
Backup file prefix is CryptUp instead of FlowCrypt

### ISSUE THREAD

**Issue by chuacw** [FlowCrypt/flowcrypt-browser#1066]
When choosing to backup the key to a file, the file prefix is CryptUp, instead of FlowCrypt.
Steps as follows:

1. Go to settings
2. Select Backup
3. See More Backup options
4. Select Download
5. Click Backup as a file
6. Right click on the link, select link save as

The backup file name starts with CryptUp, instead of  FlowCrypt.

**Comment by tomholub** [comment]
Thanks for the report

**Comment by tomholub** [comment]
!! after changing, please confirm loading new AND OLD backups still works !!

please also confirm the same on Android

this is very important not to mess up
