### ISSUE TITLE
[firefox] Clicking settings doesn't work if gmail isn't opened first

### ISSUE THREAD

**Issue by chuacw** [FlowCrypt/flowcrypt-browser#1067]
Clicking settings doesn't work if a gmail tab isn't opened first in Firefox (both 59.0.2 (64-bit) and 60.0b15 (64-bit)).

To reproduce, do these steps.
1. If there is any Gmail tab opened, close it.
2. Close Firefox.
3. Start Firefox.
4. Click on FlowCrypt icon, and click the Gear/Settings icon, and select the account to open.

Nothing happens.

If you open a Gmail tab first, then repeat the above steps, after Step 4, the FlowCrypt settings page opens up.

**Comment by tomholub** [comment]
Will investigate

**Comment by tomholub** [comment]
Tried many times, cannot reproduce :( I could have been fixed since.
