### ISSUE TITLE
Email message containing prefix<randomtext>suffix becomes prefixsuffix instead

### ISSUE THREAD

**Issue by chuacw** [FlowCrypt/flowcrypt-browser#1073]
Hi,

I wrote an encrypted email, and the email contains the following sequence of characters:

` someprefix<randomtext>suffix`

When the email got sent, it became the following:

` someprefixsuffix`

**Comment by tomholub** [comment]
Looks like it omitted the middle, thinking it's a html tag. Instead, it should have escaped it. Thanks for the report!

**Comment by tomholub** [comment]
add a test
