### ISSUE TITLE
add automated test for create key manually -> download

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1074]
- [x] fix it (got fixed on recent versions)
- [ ] add test (on chrome)
- [ ] also test settings -> backup -> as file

**Comment by tomholub** [comment]
There will be no continue button after downloading backup in setup - tested on Firefox

**Comment by tomholub** [comment]
only broken on firefox, low-pri

**Comment by tomholub** [comment]
Didn't seem to be broken on recent FF versions, but having a test would still be good

**Comment by tomholub** [comment]
not really fixed: #2115

**Comment by michael-volynets** [comment]
To clarify, 
I need to write a test that's going to download the key and compare it with the original key, am I right?

**Comment by tomholub** [comment]
You don't actually need to compare the key, just test that you are able to proceed through setup by creating your own key, and then choosing the "download as file" backup method.

**Comment by michael-volynets** [comment]
Okay, got it
thanks

**Comment by tomholub** [comment]
Re-assigning to myself, to evaluate the PR when I get a chance
