### ISSUE TITLE
encrypt+sign support

### ISSUE THREAD

**Issue by matt812** [FlowCrypt/flowcrypt-browser#1080]
I would like to sign _and_ encrypt my emails, like k-9 mail does (and so it works seamlessly with k-9 mail).

https://k9mail.github.io/2017/01/30/OpenPGP-Considerations-Part-II.html

**Comment by tomholub** [comment]
Thanks for submitting the issue, we're planning it.

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/1633e5be04b3aacb

**Comment by tomholub** [comment]
fixed in #1963, will be released over the coming weeks
