### ISSUE TITLE
logo updates - browser action

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1083]

**Comment by tomholub** [comment]
folow up from https://github.com/FlowCrypt/flowcrypt-browser/pull/1082

We may need to hand-draw or otherwise pay more attention to the browser action logo:

![image](https://user-images.githubusercontent.com/6306961/39862098-4fd19a22-5475-11e8-8234-2b5e47d2bd52.png)

1) is there a way to make it appear bigger? Within the 19x19 allowance. Maybe cut of a pixel or two on both sides to make it a tad bit bigger?

2) it looks like it was scaled down from larger size, it should instead appear as if designed for that size

3) also they recommend a double 38x38 size: https://stackoverflow.com/questions/20424425/recommended-size-of-icon-for-google-chrome-extension (maybe for retina displays)

**Comment by tomholub** [comment]
Good job on the logo overall though!

**Comment by mondo989** [comment]
Cool, I'll look into fixing this today.

**Comment by mondo989** [comment]
@tomholub close this when you feel this is ready, or let me know any updates needed. 
Can't quite test it at the moment.
