### ISSUE TITLE
Browser extension blocking 'Secure Compose' email window on Updated Gmail Layout 

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#1102]
Might be somewhat related to a post on Twitter. 
https://twitter.com/FlowCrypt/status/1000049784101785601

<img width="499" alt="screen shot 2018-05-25 at 4 23 51 pm" src="https://user-images.githubusercontent.com/3431871/40564794-15aafef0-6038-11e8-8507-28baba139aa7.png">

Using quite a few extensions (possible troublemakers)
- HTTPS Everywhere
- Adblock 
- uBlock origin
- Privacy badger

**Comment by tomholub** [comment]
I think it's uBlock origin - try temp. disabling

**Comment by mondo989** [comment]
Yep it was uBlock origin
