### ISSUE TITLE
Firefox Mobile: responsive design - all settings pages

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1111]
@mondo989 We will one day allow offer users to download and use FlowCrypt as a Mobile Firefox extension. To test this:

1) download Firefox on your phone
2) open Firefox app
3) go to flowcrypt.com/download and choose the firefox extension
4) play around with it

That will give you an idea of how it looks and what needs to be done.

**Comment by mondo989** [comment]
@tomholub I'm getting a bit hung up with it loading on Firefox... 
Here's where it's getting hung up...
![jun-12-2018 20-26-16](https://user-images.githubusercontent.com/3431871/41323836-07783b68-6e7f-11e8-86b0-8ce56a06a2c7.gif)

**Comment by mondo989** [comment]
@tomholub understandably, we want this for FF... Although I'm wondering if it would make sense/possibly be easier to have all settings pages (basic and advanced) responsive, for modern browsers.

**Comment by tomholub** [comment]
Yes that's what I thought, just have everything responsive.

**Comment by tomholub** [comment]
It seems to work here. I'm using Firefox Beta and when clicking on the link, it doesn't download it - instead it offers to install the plugin.

Can you try Firefox Beta? Not sure if it makes a difference.

**Comment by mondo989** [comment]
Working on this this weekend...

**Comment by tomholub** [comment]
Perfect :)

**Comment by tomholub** [comment]
I saw you created separate issues #1193 and #1194 so I'm closing this, thanks!

**Comment by tomholub** [comment]
@mondo989 I'm deleting package-lock from the repo and ignoring it. If you want to use it locally, save it aside, then pull repo, then move it back - it should be ignored and not committed back to the repo anymore.

**Comment by mondo989** [comment]
@tomholub sure and no problem.  
Meant to remove it but it got added with all PR.
