### ISSUE TITLE
error rendering

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#115]
right now I render all errors with `alert()` for simplicity. Better way is to have a set space in each template where errors will go, if any.

Errors can happen:
- during setup and in settings
- when composing a message
- when replying to a message
- general errors in gmail window

For composing/replying messages in gmail window, we can keep them within the iframe, or outside the iframe as well. I like when errors show rather nearer to the action buttons that caused them, so within iframes would probably make more sense.

**Comment by mondo989** [comment]
I agree clicking an alert is a bit of a pain. 
Also that it's a good idea to keep the error message easily visible to the action button

In settings, what if we call in divs and populate the error message?

<img width="484" alt="screen shot 2016-04-10 at 4 21 31 am" src="https://cloud.githubusercontent.com/assets/3431871/14408873/e71b9a9e-fed3-11e5-898b-901ff4c95e26.png">
Maybe we can reuse it in different places?

I pushed some code that has the message and it's transition, right now on line 
61 #error_text_container is display: none;  If you display block it will appear like below.

<img width="1106" alt="screen shot 2016-04-10 at 4 36 51 am" src="https://cloud.githubusercontent.com/assets/3431871/14408954/871036c0-fed6-11e5-983c-a7cad29120ab.png">

**Comment by tomholub** [comment]
I like it, for settings, this will work nicely :)

**Comment by mondo989** [comment]
When composing a message:

<img width="544" alt="screen shot 2016-04-21 at 11 52 45 pm" src="https://cloud.githubusercontent.com/assets/3431871/14731211/42d48d40-081c-11e6-91f6-09ddb55a5e8d.png">

**Comment by mondo989** [comment]
Replying to a message
<img width="850" alt="screen shot 2016-04-22 at 12 04 24 am" src="https://cloud.githubusercontent.com/assets/3431871/14731369/e0f2b6e0-081d-11e6-812c-f772f205a131.png">

**Comment by mondo989** [comment]
Both messages use a little animation to fade up coming from the button. 
At the moment they are just active by default.

**Comment by tomholub** [comment]
General in window - maybe like "your cryptup key needs a backup" or something. But I might just emulate gmail notifications (the yellow ones) like I do now.

I'll hide the error messages until I can connect them. I'd also experiment with more colors, like maybe borderless and white background

**Comment by tomholub** [comment]
this is especially important for issues like #233

**Comment by mondo989** [comment]
@tomholub - on a previous project, we used SweetAlert, for error handling. 

Check it out and let me know if you have any thoughts on it.
https://t4t5.github.io/sweetalert/

<img width="1014" alt="screen shot 2017-02-12 at 1 45 51 pm" src="https://cloud.githubusercontent.com/assets/3431871/22865420/9acccf34-f129-11e6-926c-166ca6a234ef.png">

**Comment by tomholub** [comment]
Oh that's a great start. I'll replace all alerts asap!!! :)

--
Tom James Holub <http://holub.me/>

**Comment by mondo989** [comment]
Yeee! Awesome.

**Comment by tomholub** [comment]
There's a maintained version of it that I'll use
https://github.com/limonte/sweetalert2
Looks really nice.

**Comment by mondo989** [comment]
👍 👍 👍
