### ISSUE TITLE
'Send Encrypted Email' window's styling not consistent with Gmail's updated UI

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#1153]
A bit minor but could be a nice touch. 
- Border-radius around email window
- Border-radius on button
- Update 'Add Recipient' to 'To'
- Send button typeface

<img width="556" alt="screen shot 2018-06-29 at 8 57 27 pm" src="https://user-images.githubusercontent.com/3431871/42119863-1ab1891a-7bdf-11e8-896d-1f8b4060ab9c.png">
<img width="563" alt="screen shot 2018-06-29 at 8 57 19 pm" src="https://user-images.githubusercontent.com/3431871/42119864-1ad28f48-7bdf-11e8-9a50-2b717f5d476a.png">

**Comment by tomholub** [comment]
Agree, let's do it

**Comment by tomholub** [comment]
Closing this, relatively low priority
