### ISSUE TITLE
allow importing and using key without self-signature with a big warning

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1158]

**Comment by tomholub** [comment]
waiting for https://github.com/openpgpjs/openpgpjs/pull/879 to get merged

**Comment by tomholub** [comment]
part of enterprise requests #2125

**Comment by tomholub** [comment]
As for the warning banner design, you don't have to worry about it in this PR (unless you want to).

When importing such key, you could just do `Ui.modal.confirm` to ask the user if he really wants to (auto?)import such key (I leave the details to you, as long as the user is properly informed at least once in the process).

Then maybe render the recipient in orange, similar to what we do with expired keys:

![image](https://user-images.githubusercontent.com/6306961/77260582-d26a0a80-6c80-11ea-9fe5-906a63e8ffee.png)

To discuss design or styling, or request help integrating something ux/ui-wise, ask @limonte

**Comment by wiktor-k** [comment]
:thinking: the referenced OpenPGP.js PR was closed (not merged). I did grep for `openpgp.config.require_uid_self_cert` in the repo but the setting name is just mentioned in a commented-out fragment. So my question is: would fixing this issue require backporting your patch from the OpenPGP.js repo to `openpgp-custom.js` script or is there some other way to disable the selfsig check?

Thanks for help!

**Comment by tomholub** [comment]
That's right - we would have to maintain our own OpenPGP.js fork, which may turn out quite a bit of work over time.

However, your addition of S/MIME functionality may somewhat cover this issue - the main customer who needed this was using some sort of OpenPGP certs that were auto generated from s/mime certificates, and that's why they were missing self-sigs (no private key to sign with). Therefore, further improving S/MIME may be be a more worthwhile effort, given that we have some S/MIME functionality now.

So I'll go ahead and close this, until it turns out we have no other option.
