### ISSUE TITLE
compose: paste public key - option to load from file

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1168]
If I have the pubkey in a file, it's inconvenient to open it and paste

**Comment by schmorrison** [comment]
Ultimately this could be handled in a similar fashion as #1134 was fixed. Which means the code used in #1593 should be moved to an external file and made as an importable. Of course there were a number of changes to the HTML that would be required when using this new importable, which should be somehow documented perhaps in a comment.

What do you think?

**Comment by tomholub** [comment]
Yup, it is fundamentally the same issue, just in different context.

Agree with your thoughts, that would be I think the correct way to approach it.
