### ISSUE TITLE
Mobile Bug: When sending attachment to user without PGP

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#1193]
<img width="355" alt="screen shot 2018-08-04 at 1 12 36 pm" src="https://user-images.githubusercontent.com/3431871/43678820-2420a0ba-97e8-11e8-9b08-3937b5ec3716.png">

Quite a bit of overlapping

**Comment by tomholub** [comment]
deprecating FF mobile
