### ISSUE TITLE
Bug: table elements on mobile

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#1194]
<img width="264" alt="screen shot 2018-08-04 at 1 16 52 pm" src="https://user-images.githubusercontent.com/3431871/43678859-b32c5e5c-97e8-11e8-8107-064edfc3ddfe.png">
<img width="232" alt="screen shot 2018-08-04 at 1 16 29 pm" src="https://user-images.githubusercontent.com/3431871/43678861-b356b774-97e8-11e8-9c99-bee3b89cbd29.png">
<img width="260" alt="screen shot 2018-08-04 at 1 16 15 pm" src="https://user-images.githubusercontent.com/3431871/43678863-b381966a-97e8-11e8-9535-b6ace00e6c61.png">

**Comment by tomholub** [comment]
Deprecating FF mobile
