### ISSUE TITLE
BUG: Browser icon displays a low resolution logo

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#1202]
<img width="177" alt="screen shot 2018-08-05 at 8 16 37 pm" src="https://user-images.githubusercontent.com/3431871/43691582-a4d9f5d0-98ec-11e8-90e9-7757253a0652.png">

There may be another issue in another repo for this...

**Comment by tomholub** [comment]
I was wandering about this!
