### ISSUE TITLE
Rename the backup file name  from cryptup-email.key to flowcrypt-email.key

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-browser#1213]
Need to change the file name when the app is creating a backup (option `DOWNLOAD`)

What I have now (version 5.7.2 on July 13, 2018)

![image](https://user-images.githubusercontent.com/2863246/43776249-ea2b4c44-9a57-11e8-8539-a1703ad388e4.png)

**Comment by DenBond7** [comment]
option "EMAIL INBOX". The same situation

![image](https://user-images.githubusercontent.com/2863246/43776417-808e5f64-9a58-11e8-8e6f-3d03e0fc42c2.png)

**Comment by tomholub** [comment]
thanks for report, I have an issue for it: #1066 so I'll close it as a duplicate

for loading, you should search for both patterns
