### ISSUE TITLE
Update design of 'Contacts' view on mobile

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#1251]
Referenced:
https://github.com/FlowCrypt/flowcrypt-browser/pull/1247

<img width="456" alt="screen shot 2018-09-06 at 10 30 21 pm" src="https://user-images.githubusercontent.com/3431871/45195219-82555f80-b224-11e8-9fa8-54f5300bffa8.png">

**Comment by mondo989** [comment]
![sep-07-2018 02-47-29](https://user-images.githubusercontent.com/3431871/45202913-6ebbf000-b248-11e8-8d4c-fb056aab6631.gif)

I'm a fan of how Google is using the icon/photo in the button, I was thinking we can leverage/replicate some of this styling a bit.
<img width="361" alt="screen shot 2018-09-07 at 2 48 58 am" src="https://user-images.githubusercontent.com/3431871/45202986-aa56ba00-b248-11e8-8bfb-a8abc27d3121.png">

Here's what I'm thinking of pushing, for mobile, let me know any thoughts/feedback.
![sep-07-2018 02-47-29](https://user-images.githubusercontent.com/3431871/45203053-dd00b280-b248-11e8-812d-05322a19f3ed.gif)

**Comment by mondo989** [comment]
![sep-07-2018 02-52-43](https://user-images.githubusercontent.com/3431871/45203179-4d0f3880-b249-11e8-8552-eeedc5254fa5.gif)

**Comment by tomholub** [comment]
Ah I managed to not reply to this!

I would show only icons (on the same line) on mobile:

```
some@email.com      (o) (e) (x)
other@email.com     (o) (e) (x)
```

For the eye, we already have an eye icon that we use to show pass phrase - you can reuse that. For remove icon I would re-use the trash icon from compose window, and I would then pick an edit buton to fit the other two.

**Comment by tomholub** [comment]
I'm not a big fan of the Google styling for our purposes:

![image](https://user-images.githubusercontent.com/6306961/45467686-619f7500-b710-11e8-9def-bb77e0e99de9.png)

Since it's inconsistent with the rest of our styling, which I'm quite used to.

I usually like fewer borders, fewer frames, content only whenever possible, unless it's confusing - only then do I like to separate groups with additional styling.

**Comment by tomholub** [comment]
Re/posting earlier message to be clearer:

In addition to only using icons / no caption on mobile, I find that there are too many borders on the following:

![image](https://user-images.githubusercontent.com/6306961/45467777-d5da1880-b710-11e8-9c23-48a54177e914.png)

I usually like fewer borders, fewer frames, content only whenever possible, unless it's confusing - only then do I like to separate groups with additional styling.

In this specific case, if you put each email on a single line, you can remove the box/borders around each email+buttons, plus you can remove borders around the icons, plus you can remove borders around icon+captions. Less borders is more as far as I'm concerned! :)

**Comment by mondo989** [comment]
I agree the updated buttons with borders and icons are a bit too different, and introducing new borders (and the icons) are a bit much. 

I simplified the contact's actions/links as to one link per row. Also feel like icons aren't necessary as of now. (Stacking the actions/links seem to work well.)

I also agree with you on the excessive borders, and used used correctly they can add value on helping to quickly provide context in letting the user know what actions are related to which account. 

I think the single containing border works here to quickly differentiate which actions are associated with with account.

**Comment by mondo989** [comment]
![sep-20-2018 02-53-46](https://user-images.githubusercontent.com/3431871/45801002-98c9d500-bc80-11e8-84ff-99bc3d27246d.gif)

<img width="329" alt="screen shot 2018-09-20 at 2 55 53 am" src="https://user-images.githubusercontent.com/3431871/45801050-ba2ac100-bc80-11e8-82ed-5428f75ac0f4.png">

**Comment by tomholub** [comment]
I would still rather the show/change/remove buttons are all on single line with the email that belongs to them, but they won't fit without the icons on mobile. So I feel like the icons will be necessary if I want to make them fit on one line

**Comment by tomholub** [comment]
I would be quite ok to go with icons only also on the desktop version to keep it consistent if that helps

**Comment by mondo989** [comment]
![sep-25-2018 22-54-41](https://user-images.githubusercontent.com/3431871/46059959-3fe1bd00-c116-11e8-873a-ea0d728d3311.gif)

- added on one line and removed mobile borders

**Comment by tomholub** [comment]
What I meant was this:

![image](https://user-images.githubusercontent.com/6306961/46122667-819f6000-c209-11e8-944f-30f1e84fc9e7.png)

But looking at it now, the show button is redundant - we should make the email itself clickable to show:

![image](https://user-images.githubusercontent.com/6306961/46122693-bca19380-c209-11e8-9b09-f30a8164c2fe.png)

(ignore the email color, it should be blue)

Do you see any issue with doing it that way?

**Comment by mondo989** [comment]
I think there's value in having the show icon with the others, It keeps it consistent.
Also, it might not be easily known that clicking the email address will show the key. 

Some users may be used to an email client opening when clicking an email link. 
Clicking an eye icon is a little more explicit.

**Comment by tomholub** [comment]
Good point. Is the following ok?

![image](https://user-images.githubusercontent.com/6306961/46271749-9587f080-c580-11e8-97ee-27132a0d2fa3.png)

**Comment by tomholub** [comment]
We could still make the links clickable, doesn't hurt

**Comment by mondo989** [comment]
@tomholub  It's been a little tricky getting them to sit on one line, especially on mobile. 
At <500px there's a breakpoint to move the icons to the next line.  

![oct-12-2018 11-53-47](https://user-images.githubusercontent.com/3431871/46888644-eb2c8a80-ce15-11e8-9f4c-4c741d85b493.gif)


Not 100% sure how to make the email a link that references the public address. Let me know any thoughts/feedback on it.

**Comment by mondo989** [comment]
@tomholub There's like two PR's that are linked for mobile updates. 
It would be nice get them merged with the completion of 'Contacts View' updates.

https://github.com/FlowCrypt/flowcrypt-browser/pull/1247
https://github.com/FlowCrypt/flowcrypt-browser/pull/1252

**Comment by tomholub** [comment]
Ok that looks good. Putting them on next line makes sense for tiny screens, otherwise all ok

I would like to merge this soon, but I'm as busy as ever these days - it may need to stay open for a bit

**Comment by mondo989** [comment]
Temporarily going to close this issue
