### ISSUE TITLE
Chrome Updated browser bug

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#1256]
![sep-13-2018 01-46-57](https://user-images.githubusercontent.com/3431871/45469341-10cf5280-b6f7-11e8-9823-76883d33b501.gif)

**Comment by mondo989** [comment]
Chrome's browser is pretty sexy.

**Comment by tomholub** [comment]
What is the bug though? Is it the white background?

**Comment by mondo989** [comment]
It was the excessive size... 
After checking a few times, maybe there was something that didn't update with the browser ? 

Seems to be fixed now.

**Comment by tomholub** [comment]
I totally missed that in the screen shot! Also looks ok on my chrome.
