### ISSUE TITLE
sign-in permission loop

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1260]
happens on chrome, collected quite a few instances.

chrome68.0.3440.106 (64bit)
https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKbMfJlbRpqvfTHVGpCXXhjnK

Also a report for the vivaldi browser.

**Comment by tomholub** [comment]
Vivaldi seems consistently broken - possibly fixable.

**Comment by tomholub** [comment]
Please test on Vivaldi 2. If you cannot reproduce this, please close.

The issue is supposed to be: you click "Connect to Gmail", go through permissions, accept, and nothing happens. Then you try again, and nothing happens, so you're just stuck in a loop.

**Comment by michael-volynets** [comment]
Everything works well on Vivaldi 2 browser.:+1:
