### ISSUE TITLE
some attachments wrongly downloaded with .pgp extension

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1289]

**Comment by tomholub** [comment]
@DenBond7 It looks like this was caused by the Android app. However I cannot reproduce it, and when inspecting the code, it the Android app seems to be doing it correctly now (file name without the .pgp extension goes into the encrypt function).

Have you fixed this recently?

Eg this seems to be doing it correctly:

https://github.com/FlowCrypt/flowcrypt-android/blob/ff2dad8cc4c9d75a797455e4db7cd529c71d67ed/FlowCrypt/src/main/java/com/flowcrypt/email/service/PrepareOutgoingMessagesJobIntentService.java#L222

**Comment by DenBond7** [comment]
> Have you fixed this recently?

No, I've not fixed this. I've forwarded a new message via the Android app and I still have that problem.

![image](https://user-images.githubusercontent.com/2863246/47553745-83476b00-d910-11e8-939e-990116d8a4ae.png)

**Comment by DenBond7** [comment]
There are message sources from chrome and android. Maybe it'll help.

![image](https://user-images.githubusercontent.com/2863246/47554626-60b65180-d912-11e8-92b7-4c54bd714001.png)

**Comment by tomholub** [comment]
I'll investigate

**Comment by tomholub** [comment]
@DenBond7 I see. This only happens when forwarding attachments. Attachments that I added directly into a new message behave correctly.

The Android app is processing forwarded message attachments differently, and it needs to be fixed.

For example, when encrypting a file, the method lets you add a filename. That should be the original filename without `.pgp` (FlowCrypt Browser Extension will use this name after decrypting, so it needs to be original). This original name is encrypted inside the PGP encrypted data. After that, you add the `.pgp` message to the actual filename sent over SMTP.

When forwarding, somewhere we are adding `.pgp` into the encrypt function on Android, which is not correct.

**Comment by tomholub** [comment]
I think I found it. Let me fix it, at least I practice some Java :)

**Comment by DenBond7** [comment]
> Let me fix it, at least I practice some Java :)

No problems :) . Please notify me if need any help.
