### ISSUE TITLE
Support for key in cards

### ISSUE THREAD

**Issue by fzerorubigd** [FlowCrypt/flowcrypt-browser#1303]
There are some cards like yubikey that you can write your PGP secret key there and without having the master key, and also without using any private key on the computer (the private key stored in the key) you can sign/encrypt anything. 
Support for cards like yubikey as the source for PGP is very nice to have.

**Comment by tomholub** [comment]
absolutely, we're tracking it here: https://github.com/FlowCrypt/flowcrypt-browser/issues/964
