### ISSUE TITLE
apply to get whitelisted with Google Advanced Protection

### ISSUE THREAD

**Issue by meebey** [FlowCrypt/flowcrypt-browser#1325]
I want to evaluate FlowCrypt to secure my organization's email communication. Unfortunately I get an error message when I want to setup FlowCrypt:

"Google cannot give this app access to your account data because Advanced Protection is turned on for your Google Account."

My Google account is indeed protected with "advanced protection". This just means that single factor authentication (username+password) and even 2FA OTP is not allowed for authentication. A security key (U2F) is mandatory as my account is a common target for hackers.

![screenshot from 2018-11-06 11-14-06](https://user-images.githubusercontent.com/318066/48040850-a2b68180-e1b5-11e8-88c0-8bf4e95bd1d0.png)

**Comment by tomholub** [comment]
Sorry for the silence. Applying for getting whitelisted would indeed be good.

**Comment by seisvelas** [comment]
@tomholub Is there any way I can help with the whitelisting application process? Perhaps not, just let me know if there's anyway I can be useful for moving us towards this :)

**Comment by tomholub** [comment]
Could you please research what are the actual requirements today and if we fit them?

And what type of security review they require - do we have to use their chosen provider?

**Comment by seisvelas** [comment]
If I'm understanding the documentation correctly, it appears that it is fairly straightforward for Workspace super admins to explicitly whitelist trusted 3rd party apps:

<img width="726" alt="Screen Shot 2021-06-18 at 12 15 34 a m" src="https://user-images.githubusercontent.com/44826516/122515184-4ef5b100-cfca-11eb-90e7-a21745e63f2c.png">

source: https://support.google.com/a/answer/9378686?hl=en

This is probably a much easier way to support these users compared to trying to be accepted into the list of default trust apps (which only includes Google native apps, Apple Native iOS apps, Apple Mail on macOS, and Mozilla Thunderbird).

I can try setting up Advanced Protection myself on a test account, add FlowCrypt to the trusted apps, and see if it works. Then I'd add a note on installation or the download page saying for Advanced Protection users to click there, and it would take them to docs for how to add FlowCrypt as a trusted app.

What do you think?

**Comment by tomholub** [comment]
Ah, I didn't know that! Yes, with that, we should then create a section in docs, maybe the security page, pointing users (and their admins) in the right direction.

**Comment by ylemkimon** [comment]
For Workspace, changing the access of FlowCrypt Browser Extension to trusted in https://admin.google.com/ac/owl/list?tab=apps works:
![admin](https://user-images.githubusercontent.com/888148/149872117-6a081315-05ab-4125-b62b-8b7fe17f20ff.png)

**Comment by tomholub** [comment]
@ylemkimon Thank you for the hint!

@martgil please update our docs - I believe we mention lack of compatibility with GAP there somewhere. If the user is an organization that uses Google Workspace then they can allow the browser extension for their org as above.

**Comment by martgil** [comment]
Yes, sir @tomholub

Also to support Gmail account with individual GAP enabled, they would need to disable (unenroll) their GAP from their account temporarily to set up the FlowCrypt browser extension. 

Once the setup is done, they can enable the GAP again.

**Comment by tomholub** [comment]
> Also to support individual Gmail account with GAP enabled, they would need to disable (unenroll) their GAP from their account temporarily to set up the FlowCrypt browser extension.

> Once the setup is done, they can enable the GAP again.

Are you sure about that? I'd imagine the browser extension would stop working once GAP is re-enabled.

**Comment by martgil** [comment]
It is what the customer support shared with me when I ask about GAP in the app. I've ordered a Yubikey to test it out. I will convert the PR in the docs repo as a draft in the meantime. Apology for the delay.

**Comment by tomholub** [comment]
Ok. I'll also close this issue - we're not planning to apply for this anytime soon.
