### ISSUE TITLE
option to see original in flowcrypt inbox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1414]
This one could be done very easily and smoothly

**Comment by tomholub** [comment]
Came up when I wanted to copy signed message including armor

**Comment by tomholub** [comment]
deprecating

**Comment by tomholub** [comment]
not deprecating, this is about the inbox in flowcrypt settings

**Comment by tomholub** [comment]
Basically just sort of replicate what that "show original" button does in Gmail, but show it directly in the convo, not in new window, and only affect currently opened convo, and don't remember the choice

**Comment by tomholub** [comment]
In Settings -> Inbox

**Comment by schmorrison** [comment]
Hey Tom, I started working on this but I'm going to need a primer or explanation on what you want to see when you say

> Basically just sort of replicate what that "show original" button does in Gmail, but show it directly in the convo, not in new window, and only affect currently opened convo, and don't remember the choice

I found the stuff in `browser.ts` and the `gmail_element_replacer.ts`, and I know that in `js/content_scripts/webmail/*.ts` are the files in the webmail bundle which is loaded by the extension in a gmail inbox.

So I can see that clicking the `See Original` button just executes a click on the `In new Window` button in gmail, like so:
```
this.addfcConvoIcon(convoUpperIcons, this.factory.btnWithoutFc(), '.show_original_conversation', () => {
    convoUpperIcons.find('.gZ').click();
});
```

But if you could explain how you might like the layout to be organized, or some styling pointers for this. I started towards just replacing the decrpyted PGP UI blocks with the original PGP message block wrapped in a `pre` tag to handle the newlines, (maybe you have a helper for that already). Then providing a button that will replace the 'original messages' with the decrypted content. For my development of this I created some messages with the public key attached, the way it works on gmail is a PGP message block with a PGP Public Key in a file attachment. The change I made simply prints the PGP public key block directly after the PGP message block, but I can change it to do attachments alternatively if youd prefer

Best regards,

Sam Morrison

**Comment by tomholub** [comment]
Basically you should re-load and re-render the whole conversation, but don't do any decrypting any decrypting this time. (this is easier than trying to replace already rendered blocks)

So I would imagine in `renderMsg` you would find a way to skip `Ui.renderableMsgBlock` and instead treat and render each block as `text`. That would be a good start, from there, you would see what else needs work, if any.

**Comment by tomholub** [comment]
@schmorrison looks good. One thing to add is that when more than one or two css rules need to be added, the .css files are usually a better place than directly in the html file (see last commit). Thanks!
