### ISSUE TITLE
Refactor Api.err and Pgp.* methods into separate classes

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1438]
...

**Comment by tomholub** [comment]
Please don't do one gigantic PR, maybe make PRs file by file if possible. Then we can have several PRs related to one issue.

**Comment by michael-volynets** [comment]
Okay, will do,
There are more than 20 files, I think it's better to include 3-4 files in PR if files are small and make some few PRs with large files.

**Comment by tomholub** [comment]
We will follow your style here.

What I particularly want to refactor are two things:

#### property methods - example `settings.ts`

```js
// current
export class Settings {
  static fetchAcctAliasesFromGmail = async (acctEmail: string): Promise<...> => {
    // ...
  }
}
// refactored
export class Settings {
  static async fetchAcctAliasesFromGmail(acctEmail: string): Promise<...> {
    // ...
  }
}
```

#### object literals with methods on them - example `pgp.ts`

There are various properties with groups of methods, eg `Pgp.key`, `Pgp.armor` etc. These should become separate classes such as `PgpKey`, `PgpArmor`, `PgpHash`. These classes should then go to separate files eg `pgp-key.ts`, `pgp-armor.ts` all in the same folder, where now `pgp.ts` is.

```js
// current
export class Pgp {
  public static key = {
    create: async (...): Promise<...> => {
      // ...
    },
  };
}
// refactored
export class PgpKey {
  static async create(...): Promise<...> {
    // ...
  }
}
```

**Comment by tomholub** [comment]
Updated regexes to find these

`\n\s+(public|private)?\s*(static)?\s+[a-zA-Z0-9]+ = (async )?\([^)]*\)[^\n]+=> \{`
595 results

`\s+(static)?\s+[a-zA-Z0-9]+: (async )?\([^)]+\)[^\n]+=> \{`
98 results

**Comment by tomholub** [comment]
I'll try to get a stab at the bigger group with a regex-replace

**Comment by michael-volynets** [comment]
Got it, Thanks.
Will do

**Comment by tomholub** [comment]
Remaining to refactor:
- [ ] Api.err as ApiErr
- [ ] Pgp.armor as PgpArmor
- [ ] Pgp.hash as PgpHash
- [ ] Pgp.key as PgpKey
- [ ] Pgp.armor as PgpArmor
- [ ] Pgp.armor as PgpArmor
- [ ] Pgp.password as PgpPwd
- [ ] Pgp.internal will be carefuly put, method by method, into the classes that use them. If some methods are used in several, you could put them as `protected` into Pgp, then inherit all Pgp* classes from Pgp.

**Comment by tomholub** [comment]
For the above list, let's please do it one PR per checkbox, or it would be impossible for me to review. Thanks!

**Comment by tomholub** [comment]
correction, now it will be all fat arrows in the new classes:
```javascript
// current
export class Pgp {
  public static key = {
    create: async (...): Promise<...> => {
      // ...
    },
  };
}
// refactored
export class PgpKey {
  static async create = (...): Promise<...> => {
    // ...
  }
}
```

**Comment by michael-volynets** [comment]
I'm also thinking to move all these constants into a separate file:
![image](https://user-images.githubusercontent.com/49104848/70573631-07a78c80-1bab-11ea-82cb-a19c54b7138f.png)

**Comment by tomholub** [comment]
Don't make a separate class, rather, put each constant where it is used.

CRACK* goes into PgpPwd.

ARMOR goes into PgpArmor.

**Comment by michael-volynets** [comment]
I stuck a little, maybe you know why this happens.
I refactored Pgp.armor and I started seeing this kind of errors:
```
/ssd/Projects/flowcrypt-browser/test/source/platform/require.ts (8,10): Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.
/ssd/Projects/flowcrypt-browser/test/source/platform/util.ts (5,29): Cannot find module 'crypto'.
/ssd/Projects/flowcrypt-browser/test/source/platform/util.ts (12,10): Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i @types/node`.
/ssd/Projects/flowcrypt-browser/test/source/platform/util.ts (16,10): Cannot find name 'Buffer'. Do you need to install type definitions for node? Try `npm i @types/node`.
```
These errors are only present in the test files and I don't know their reason.
Do you know what could provoke these errors?

**Comment by michael-volynets** [comment]
I pushed the code so if you want you can take a look at the code.

**Comment by tomholub** [comment]
I'll wrap it up

**Comment by tomholub** [comment]
- refactor Pwd (no need q/a)
