### ISSUE TITLE
add user name into public keys when creating

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1489]

**Comment by tomholub** [comment]
(storage.full_name)

**Comment by schmorrison** [comment]
Can you provide a little clarification on this issue?

I believe we are looking to modify this function in `extension/chrome/settings/setup.ts`:

```
const createSaveKeyPair = async (options: SetupOptions) => {
    await Settings.forbidAndRefreshPageIfCannot('CREATE_KEYS', rules);
    const { full_name } = await Store.getAcct(acctEmail, ['full_name']);
    try {
      const key = await Pgp.key.create([{ name: full_name || '', email: acctEmail }], 4096, options.passphrase); // todo - add all addresses?
      options.is_newly_created_key = true;
      const { keys: [prv] } = await openpgp.key.readArmored(key.private);
      await saveKeys([prv], options);
    } catch (e) {
      Catch.handleErr(e);
      Xss.sanitizeRender('#step_2_easy_generating, #step_2a_manual_create', Lang.setup.fcDidntSetUpProperly);
    }
  };
```

But full_name already seems to be added, unless it doesn't exist. Am I misunderstanding something?

**Comment by tomholub** [comment]
Looks like I may have since fixed it. Can you please try to set it up on a
test account and check that the name makes it onto the key? Once checked,
you can close it.

**Comment by schmorrison** [comment]
OK, `Store.getAcct(acctEmail, ['full_name'])` returns `{full_name: "FC Test"}`.

For PGP Public key `key.getPrimaryUser().user.userId` returns an object with the following data:
```
{
  name: "FC Test",
  email: "fctest90@gmail.com",
  userid: "FC Test <fctest90@gmail.com>"
}
```
