### ISSUE TITLE
simplify compose reply

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1493]
- do not try to parse subject, from, to, etc from the DOM
- work exclusively with threadId and threadMsgId, then always fetch the remaining metadata later from API
- when cannot fetch, show retry button
- when cannot get threadId, render error showing that it failed to get threadId for a reply (users can write us)

**Comment by tomholub** [comment]
This one may mostly be done now, please take a look

**Comment by michael-volynets** [comment]
As I see now, we don't use 'threadMsgId' variable in `compose.ts`.
I think would be better to use this variable because maybe in the future we will have the ability to reply not only to the last message.
So I'll return this variable to the code. If there isn't `threadMsgId` and there is `threadId` then I'll set the last message-id of the thread as `threadMsgId` ;

**Comment by michael-volynets** [comment]
Also, do we need to get `isReplyBox` variable from the `URLParams`?
I think we don't, we could say that it's the reply box depending on whether we have threadMsgId or not.
What do you think?

**Comment by tomholub** [comment]
Please don't add threadMsgId back, because it's useless now. We'll add it back when it's actually useful.

At which point we will probably call it `replyToMsgId` for clarity.

**Comment by tomholub** [comment]
> Also, do we need to get `isReplyBox` variable from the `URLParams`?
> I think we don't, we could say that it's the reply box depending on whether we have threadMsgId or not.
> What do you think?

I guess you're right. You could remove it.

**Comment by michael-volynets** [comment]
I need to change these 2 tests:
![image](https://user-images.githubusercontent.com/49104848/64735847-0d310000-d4f2-11e9-8b1c-ab2c48c3cafa.png)

I will test here if the retry button is present in the tests, Is it okay? Or would it be better to change a little bit API mock so when I load the message the first time the mock returns me `NotFound` and when I try to get it the second time it will return me a normal message, what do you think?

**Comment by tomholub** [comment]
> I will test here if the retry button is present in the tests, Is it okay?

sounds ok

> Or would it be better to change a little bit API mock so when I load the message the first time the mock returns me NotFound and when I try to get it the second time it will return me a normal message, what do you think?

That sounds like too much magic
