### ISSUE TITLE
google chrome manifest v3 web extensions proposal [June 2024]

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1509]
https://docs.google.com/document/d/1nPu6Wy4LWR66EFLeYInl3NzzhHzc-qnk4w4PX-0XMw8/mobilebasic#h.z7s2dbchx38y

**Comment by tomholub** [comment]
First should do some prep work - move what we can from background script to content script

**Comment by tomholub** [comment]
https://developer.chrome.com/extensions/migrating_to_manifest_v3

**Comment by tomholub** [comment]
Available in Chrome Canary

**Comment by tomholub** [comment]
> Dear Developer,
> 
> Last year, we announced the availability of Manifest V3 - a more secure, performant, and privacy-preserving iteration of the extension platform. Since then, we have added new functionality to and improved the robustness of Manifest V3 with feedback from our developer community.
> 
> We recently published a timeline of our plans to move forward with the deprecation of Manifest V2 and shifting focus fully to the new iteration of the platform. This is a notice that beginning January 17, 2022, the Chrome Web Store will stop accepting any new Manifest V2 extensions with visibility set to “Public” or “Unlisted”. Existing Manifest V2 extensions that have previously been published publicly will not be affected by this change and updates to those already-published extensions will continue to be accepted.
> 
> Additionally, beginning in June of 2022, this restriction on new extensions will expand to include items set to “Private” visibility as well. For more details and dates relating to the phase-out of Manifest V2, please refer to the Manifest V2 Support Timeline page, which will be kept up to date as more exact dates and milestone details are available.
> 
> If you have not yet begun to do so, we recommend that you begin migrating your extensions to Manifest V3. If you have feedback around migration, please please post to the chromium-extensions Google Group.
> 
> Thank you for your cooperation and for your participation in the Chrome extension ecosystem!
> 
> - The Google Chrome Web Store team

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/214399995-fe235fab-3701-4bdd-90e6-51026d0160dc.png)

**Comment by rrrooommmaaa** [comment]
> First should do some prep work - move what we can from background script to content script

We can get rid of `pgpMsgDecrypt` message handling in the background page, send the request for a decrypted attachment to the content script (handled by MessageRenderer using the cache)

Do you approve this sub-task, @tomholub ?

**Comment by tomholub** [comment]
yup, that sounds good

**Comment by sosnovsky** [comment]
https://developer.chrome.com/blog/resuming-the-transition-to-mv3/

> We will begin disabling Manifest V2 extensions in [pre-stable versions of Chrome](https://developer.chrome.com/docs/web-platform/chrome-release-channels/) (Dev, Canary, and Beta) as early as June 2024, in Chrome 127 and later

**Comment by sosnovsky** [comment]
Submitted build 8.5.5 to Google Web Store review ✅

**Comment by sosnovsky** [comment]
✅ Review passed
⏳ Rollout 8.5.5 build to 1% users
