### ISSUE TITLE
do not show private key - either copy to clipboard or save to file

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1512]

**Comment by tomholub** [comment]
copy to clipboard:
```
[Node was not found]
removeFake@moz-extension://39553fca-76d4-4791-bf00-b4dfede6fd45/lib/clipboard.js:239:19
selectFake/this.fakeHandlerCallback@moz-extension://39553fca-76d4-4791-bf00-b4dfede6fd45/lib/clipboard.js:203:26
catch.js:78:2
FlowCrypt ERROR: Please report errors above to human@flowcrypt.com. We fix errors VERY promptly.
```

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/51802380-70ab3d80-2241-11e9-965f-72fb1aa50204.png)

**Comment by tomholub** [comment]
When saving to file the copy is weird, should not talk about decryption
```
File is ready.
Right-click the link and select Save Link As
DECRYPTED FILE
```

**Comment by michael-volynets** [comment]
Okay, will do,

I've got an idea for the future:
Maybe show public and private keys on one page?
It will look similar to this:

![image](https://user-images.githubusercontent.com/49104848/66094912-5975da00-e59e-11e9-966a-b81b84e347a1.png)

What do you think?

**Comment by tomholub** [comment]
Actually, that's a good idea. Less confusing, but I will re-arrange your design a bit, first.
