### ISSUE TITLE
flowcrypt blocked on forbidden links

### ISSUE THREAD

**Issue by ggomezse** [FlowCrypt/flowcrypt-browser#1518]
somebody sent me an encrypted message containing a link to a google drive spreadsheet and the flowcrypt extension get blocked at "Formatting..." step.

with chrome developers view i have found that the issue was that I have no access to the google drive link contained in the mail.

Thanks

**Comment by tomholub** [comment]
Could you please paste the error message as it shows? Does it show a HTTP status? Is that 401? That would be helpful.

**Comment by ggomezse** [comment]
I guess this is the relevant part of the log.

webmail_bundle.js:9506 Loading FlowCrypt 6.6.1 for XXXXX
thumb:1 GET https://drive.google.com/viewerng/thumb?ds=XXXXXXXXXXXXXX&ck=gmail&authuser=0&w=800&webp=true&p=card 400
Image (async)
......
/mail/u/0/#inbox/XXXXXXXXXXXXXXXUncaught (in promise) TypeError: Failed to fetch
Promise.then (async)
.....

Thanks
Gabriel

**Comment by tomholub** [comment]
perfect.

So this was a Google Drive file where the sender forgot to give you permission. Will it start working once you have permission? Thanks for the logs above.

**Comment by ggomezse** [comment]
i guess my partner should have shared the file with me before sending the encrypted mail.

but also I think the extension should not get blocked and need a disable/enable action to keep on working.

Thanks again
Gabriel

**Comment by tomholub** [comment]
I'm closing this as fairly rare, we don't really support google drive files that well.
