### ISSUE TITLE
improve play store copy

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1528]

**Comment by tomholub** [comment]
This is useful and related https://github.com/tomholub/flowcrypt-issues/issues/4

**Comment by tomholub** [comment]
>  “GPG” → “PGP”; etc. that are an easy fix.

Nope, GPG is there intentionally. GPG is a popular implementation of PGP and people search for it when looking for solution. In fact, it's intentional that it's mentioned several times.

**Comment by evanhellmuth** [comment]
https://docs.google.com/document/d/1fWMxwE2UlD-kd24M373fW9Na6wtcCFAOc0QxS6BTetI/edit?usp=sharing

@tomholub updates linked. For any change, I made sure to keep any SEO-relevant keywords in new version.

**Comment by tomholub** [comment]
@evanhellmuth I actually have to give you access to https://github.com/tomholub/flowcrypt-issues/issues/4 where you'll know which exact terms should be preserved. I was waiting for the NDA before I do that

**Comment by evanhellmuth** [comment]
@tomholub made some changes directly to https://github.com/tomholub/flowcrypt-issues/issues/4

See the diff here: https://github.com/tomholub/flowcrypt-issues/compare/ea672ea86ec032162093acf74087f4561fe09df5..9ca3028a81cbd0859e347c1b8d314d81b1f644b2

**Comment by tomholub** [comment]
Great, published it (takes about an hour to show). Thanks!
