### ISSUE TITLE
extensions can have settings btn in manifest - point to fc settings page

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1532]

**Comment by evanhellmuth** [comment]
@tomholub clarification: is this issue about the [options page](https://developer.chrome.com/extensions/options) accessible by right-clicking on the browser action and clicking options and by navigating to chrome://extensions, finding the extension, and clicking "Details?"

I.e. whenever a user clicks on Flowcrypt options via right-clicking the browser action or via the extensions page they should be directed to chrome-extension://<extension-id>/chrome/settings/index.htm ?

![screen shot 2019-02-12 at 9 30 50 am](https://user-images.githubusercontent.com/6273837/52618947-f289a080-2ea8-11e9-9236-32e9d942aee8.png)

**Comment by tomholub** [comment]
exactly
