### ISSUE TITLE
Allow up to 20 attachments per email

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1535]
when done notify https://mail.google.com/mail/u/1/#inbox/FMfcgxwBVgjLhKxvwSwrHRQfLNJbnkDt

**Comment by tomholub** [comment]
relies on #535  and possibly more design changes

**Comment by tomholub** [comment]
Please verify it will look reasonable on sending as well as receiving side

**Comment by michael-volynets** [comment]
@limonte Could you please take a look at the CSS issues?
Now when we add 20 attachments it can take a lot of space. Look at the screenshot below:
![image](https://user-images.githubusercontent.com/49104848/68865794-11e58080-06fc-11ea-8688-3b8dc34d05f1.png)

Maybe we could do something like Gmail does today:
![image](https://user-images.githubusercontent.com/49104848/68865943-4eb17780-06fc-11ea-8789-453e1ab9c725.png)

The work related to CSS always gives me some troubles so maybe you could do it faster.
You can continue working on the branch I've already created: ` issue-1535-allow-20-atts-per-email`
Thanks!

**Comment by tomholub** [comment]
He will probably be able to look into it at the end of the month, when we'll have another monthly work-week.

**Comment by tomholub** [comment]
nobody complained about this much, closing
