### ISSUE TITLE
team-wide small talk / chat space

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1544]
Hello everybody,

we don't really use slack or other chat space, which means there isn't an obvious place for everyone to get to know each other. Since we mostly collaborate on GitHub, might as well do it here :)

@tomholub that's me. FlowCrypt is 3 years old, and was my full time focus the whole time. Previously, I was involved with https://dilmil.co/ and https://bitoasis.net/ (as a technical co-founder) . These days I mostly do TypeScript, with some Python and SQL. When I have to, I can write some Java or Kotlin, some bits of Swift. All in all, I simply do whatever we don't have anyone else for yet.

@denbond7 works full time on our Android app at https://github.com/FlowCrypt/flowcrypt-android . We expect to have a release on the Play Store this year. Big current tasks underway are: migrating away from J2V8 to nodejs-mobile (at https://github.com/FlowCrypt/flowcrypt-android-node) and migrating the Android codebase from Java to Kotlin. Den has been working in Android development for 8+ years, and has been with FlowCrypt for 2 years.

@schmorrison just joined us part-time to work initially on our TypeScript codebase. Primarily a Go developer, Sam also does TypeScript and Swift. Once I stop feeling like we're drowning in TypeScript issues (hopefully in a few months?), Sam would revive our iOS prototype and start closing the gap between iOS and Android. I also have some bits in Go that need getting done, so the Go-TypeScript-Swift is quite a good combo for FlowCrypt.

@evanhellmuth also just joined us part-time. He authored https://fmnbot.com/ -  a chrome extension. I learned some new tricks when reviewing his codebase, which I hope to apply to FlowCrypt. Evan also has a good business, usability and product intuition, and aspires to start his own business / startup in the future, so I hope to lean on him somewhat to complement my own product / business judgement.

@mondo989 has been helping me with design on and off from the very beginning. The FlowCrypt settings and the website were mostly designed by Armando. He can do photoshop / html / css. To address a design issue that also involves TypeScript, someone else on this list will collaborate with Armando to get it done.

@vincentp has recently contributed to our codebase, may do more of that soon, and may join us in the future. 

So, anyway, feel free to say hello to everyone & use this issue for general chat.

**Comment by tomholub** [comment]
One thing I forgot to tell you individually is to name your branches `issue-1234-some-name` for consistency. Our CI tests also like this particular branch name format :)

**Comment by DenBond7** [comment]
Hello everybody. I'm glad to know the whole team :)

**Comment by schmorrison** [comment]
Hi everyone. Good to know you all, and Im happy to be able to contribute to this team however I can.
