### ISSUE TITLE
improve compatibility page behavior

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1547]
See comments:
https://github.com/FlowCrypt/flowcrypt-browser/issues/1257#issuecomment-462912446
https://github.com/FlowCrypt/flowcrypt-browser/issues/1257#issuecomment-462913216

**Comment by schmorrison** [comment]
Got it. Sorry my email has been blowing up with this subscription so its been hard to keep up.

Ill make those changes ASAP.
