### ISSUE TITLE
recommend a second device to prevent data loss

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1559]
Keybase did something smart here, we could do the same when both iOS and Android apps are ready:

![image](https://user-images.githubusercontent.com/6306961/53025093-3ad03200-3458-11e9-8037-98d4a1cf23af.png)

**Comment by tomholub** [comment]
Imitation is the best form of flattery.. Keybase has some good ideas.

![image](https://user-images.githubusercontent.com/6306961/65755617-01a12400-e103-11e9-86d1-8052a9c8d549.png)

**Comment by tomholub** [comment]
If you could create something similar, and add somewhere in the code a stub like:
```
if('user-does-not-have-flowcrypt-on-any-other-device' === 'user-does-not-have-flowcrypt-on-any-other-device') {
  // ... show the banner
}
```
Then I'll add the actual logic later.

Please design it so that there could be several such banners underneath one another.

Then, please change another such notification we use, to use this new mechanism too. This is the "you don't have read permission" banner. To cause it to show up:
1) Reset plugin
2) During setup, click CANCEL on the Google login last step
3) Click "Proceed with send only"
4) Approve

In settings, you will see:

![image](https://user-images.githubusercontent.com/6306961/65756412-935d6100-e104-11e9-8f07-407d344c930b.png)

## What to do

It would be better to have a consistent mechanism for this, so please make it closer to:

![image](https://user-images.githubusercontent.com/6306961/65758776-2d270d00-e109-11e9-85be-137c54ecd576.png)

(of course that's just a sketch - the fonts / looks should be consistent for each notification)
(also notice I shortened the copy of the permission notification)

**Comment by limonte** [comment]
> During setup, click CANCEL on the Google login last step

I guess I found the bug here. When I click the CANCEL on the Google login last step, I see the dialog with the "Proceed with send only" button as expected, but when I click the "Proceed with send only" instead of proceeding, the Google login widow is shown again.
