### ISSUE TITLE
Replying to a flowcrypt email with no-subject, the OP received subject 'undefined'

### ISSUE THREAD

**Issue by schmorrison** [FlowCrypt/flowcrypt-browser#1566]
I sent a no-content/no-subject message from my gmail to another user which I opened in FC inbox.

In FC inbox I see an email with the subject line ```(no subject)```. I replied to the email and the original sender received an email with the subject line ```Re: undefined```. This ```Re: undefined``` subject line is in both the FC inbox and Gmail of the original sender.

Gmail of original sender: 
![image](https://user-images.githubusercontent.com/17385251/53144499-1eb8b780-3562-11e9-8d64-1cfe2c649e27.png)

FC Inbox of original sender:
![image](https://user-images.githubusercontent.com/17385251/53144545-4871de80-3562-11e9-8993-e11fc4dedeb4.png)

Gmail of receiver:
![image](https://user-images.githubusercontent.com/17385251/53144520-309a5a80-3562-11e9-9b41-bc982c9938a7.png)

FC Inbox of receiver:
![image](https://user-images.githubusercontent.com/17385251/53144575-6b9c8e00-3562-11e9-8b56-9a9d1d024831.png)

**Comment by tomholub** [comment]
Interesting, the fix will be to put `|| ''` somewhere.
