### ISSUE TITLE
allow pasting public key straight into recipients box

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1575]
Sometimes, users are brilliant in their ignorance

> Given a public key - how do i send to the owner an ecrypted message?  Tried to copy the given key into the recipients bar, but it doesnt let me

This sounds like a great thing to allow, and it was smart of the user to even try.

We should have a way to detect when a public key was pasted into recipient field, parse it, figure out what is the primary email, save the pubkey into contacts and add the primary email as a recipient in the compose box.

**Comment by evanhellmuth** [comment]
@tomholub is it safe to assume that the '@' character will never appear in a public key?

**Comment by tomholub** [comment]
Good question! Mostly, but not really. You can have custom comments.
```
-----BEGIN ... -----
Comment: Yo my email is me@domain.com

Ufdtf/4Ty....
----END ... -----
```

It's however safe to assume that if a string has `-----BEGIN` in it, it _may_ be a pubkey.

If there's a way to detect that, and it turns out begin string is in there, then you could run the pasted content through `PgpMsg.stripPublicKeys`, and see if it yields any pubkeys. If it does, discard any non-pubkey content, grab primary email from each found pubkey and add them to recipients (save pubkeys to contacts, too - but only if the no pubkey recorded for that particular email. Do not update / replace pubkeys in storage when the user does this).

You could try to do this in `parseRenderRecipients` (sorry about all the log statements, trying to catch a nasty bug). You could evaluate `inputTo` before it gets lowercased. I don't know if this will give you newlines, I'm afraid not, so you may need to listen to clipboard paste events and process it there (with prevent default) before it ever gets to `parseRenderRecipients`.

It may be a bit tricky to implement. Last resort solution would be to change `input_to` to a multiline, with a single actual line.. that may give you the newlines without too much hassle. You'd need to play with css for a while to make it look and behave the same.

**Comment by evanhellmuth** [comment]
@tomholub started digging in and I can't figure out how to get an email from a pubkey. There are plenty of ways to go from email --> pubkey but not the reverse. 

Is there a FC API call I can make, or should I be searching the current user's contacts? I could forge ahead with the contacts approach, but want to get your input first in case that would be a waste of time. Let me know!

**Comment by tomholub** [comment]
That would be a waste of time. If it's a new key, user won't have it in contacts. Doing this on the backend is not needed because client can do it - you want to parse the string to get pubkey details, which includes the pubkey user, which contains the email. First though, I'd check the key is valid and usable (reusing this code from `add_pubkey`).

```js
const keyImportUi = new KeyImportUi({ checkEncryption: true });
const normalizedPub = await keyImportUi.checkPub(armored); // throws on bad key
```
parsing out the email
```js
const { keys: [key] } = await Pgp.key.parse(normalizedPub);
const keyUser = Str.parseEmail(key.users[0]);
```
saving to contacts
```js
await Store.dbContactSave(undefined, await Store.dbContactObj(keyUser.email, keyUser.name, 'pgp', normalizedPub, undefined, false, Date.now()));
```

Notes:
 - Some of this may throw, see how `add_pubkey` handles it, in code and in terms ux.
 - you should save the contact first, then add a recipient into the field, so that it turns green when you do
 - One day when you get a better feel for OpenPGP, you'll find a decent reference in the RFC, in this case https://tools.ietf.org/html/rfc4880#section-11.1 and https://tools.ietf.org/html/rfc4880#section-5.11 - but because reading the RFC without prior understanding won't give you much, maybe the OpenPGP.js api docs would be better in the beginning: https://github.com/openpgpjs/openpgpjs - most of that functionality is somehow mapped to methods in our own code, that uses this library. Notice how they add email when creating a key: `userIds: [{ name:'Jon Smith', email:'jon@example.com' }]` so that would give you a hint that maybe the email can be parsed out too.

Initially though, asking is better because the specs above are quite a rabit hole, and you don't want to go down that hole this early.

**Comment by evanhellmuth** [comment]
Okay, thanks for the resources! I didn't realize a user object was baked into an OpenPGP public key. I'll take a look at the docs or API reference in the future before resorting to asking you.

**Comment by tomholub** [comment]
I do encourage you to feel free to ask, too.

If you ask and then manage to find the answer before I respond, just note what answer you found. I may still want to add some notes to give you more context.

**Comment by tomholub** [comment]
This is mostly because security is at stake. You may find the correct answer when you go fishing for it on your own, and it doesn't hurt to do that, but you may still find it useful to have more context / feedback from me, like you did above.

**Comment by evanhellmuth** [comment]
Roger that.

**Comment by tomholub** [comment]
@michael-volynets you can take this over, evan dropped it.
