### ISSUE TITLE
there should be a way to test compatibillity during setup

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1578]
One way could be to add a footer to SweetAlert2 error modals on import setup page (and settings -> import page). The footer could say `Test your private key compatibility`, a link which should lead to chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/compatability.htm or ff alternative

should only apply to the types of errors that seem like a compatibility issue

**Comment by tomholub** [comment]
To test this, you will probably need some sort of broken key from me to test with.

**Comment by limonte** [comment]
@tomholub 

> To test this, you will probably need some sort of broken key from me to test with.

In order to learn, I'd like to create a broken key by myself if that's possible. @tomholub do you have any hints/steps on how to create a broken key for testing this feature?

**Comment by tomholub** [comment]
use gnupg, since it gives you enough flexibility to create keys that are not usable.

Create a key manually, but don't give it any users.
Or give it users that don't contain any email address.
Or create a key that's only set up for signing, but not encryption (eg DSA master key and no subkey).

I'm not 100% sure which one of these will produce a key that's not usable, but one of them should do it.

Alternatively, parse any working key with OpenPGP.js with `openpgp.readArmored`, then find the key object and remove subkeys (just set k.subkeys = []) and remove users (k.users = []). Then armor the key back using `armoredBrokenKey = k.armor()`. That ought to do it, but you have to examine the key object when you do this so that you overwrite the right properties. It could be `subKeys` instead of `subkeys`, etc - look at TS types or use debugger or console.log.

Once you export the armored key, it the armored result should be quite useless, enough to throw an error when trying to import it.

**Comment by limonte** [comment]
@tomholub I'm playing around with gnupg here, and facing this:

> (17) PK 0 > Sign/Verify test: [-] sign msg ok|verify failed: FlowCrypt had trouble verifying this message **(TypeError: msgOrVerResults.verify is not a function)**  

Is it a bug?

**Comment by tomholub** [comment]
Possibly wrong typings, unsure. Or bug in OpenPGP.js. 

Depends if it happens every single time (possibly wrong typings) or if it happens only with some keys (either bug or wrong/incomplete typings).

If it only fails sometimes, one would have to investigate OpenPGP.js docs, source code and also the msgOrVerResults object to figure out if this was done intentionally by OpenPGP.js devs or not.

**Comment by limonte** [comment]
> Possibly wrong typings

Yup, your first guess was right, #2488
