### ISSUE TITLE
visual cue to write pass phrase down on paper

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1579]
I like how keybase does this. We keep asking users to note their pass phrase down, but it would be really good to reinforce it with a graphic that looks like a paper with pass phrase written on it.

![image](https://user-images.githubusercontent.com/6306961/53330894-8e72cd80-38e7-11e9-9afe-82e6f940b482.png)

**Comment by tomholub** [comment]
You could take a look at this, during setup (key generation) - same place as #1586

You could probably implement this easily with a `Ui.modal.info` that shows a similar graphic and a similar text, then a checkbox and [done].

If checkboxes are not simple to add, then just "Yes I wrote it down" button.

**Comment by limonte** [comment]
@tomholub WDYT about this type of "paper" design:

![image](https://user-images.githubusercontent.com/6059356/66208219-4279d980-e6bd-11e9-9976-1ac4a0b11be8.png)

**Comment by tomholub** [comment]
I think that would work, if the corners are meant to be sticky tape, then maybe no shadow under the sticky tape / over the paper

And if it's meant to be like a post-it note, maybe it can have slightly larger height?

It depends how it's incorporated into the page

One particular cue to make it clear that it's a paper is the folded corner: 

![image](https://user-images.githubusercontent.com/6306961/66209459-e906b000-e6a6-11e9-8157-97e450a21884.png)

Not sure how easy that is in css.

**Comment by limonte** [comment]
@tomholub I'd like to clarify where exactly you want this modal to be shown? Did I understand correctly that the desired place is `setup.htm` after users successfully submits his/her pass phrase:

![image](https://user-images.githubusercontent.com/6059356/66270162-c4ead080-e858-11e9-96bd-432de6b2c4ee.png)

Do you want it as a modal on that page or just the "paper" alert between the "You're all set!" header and buttons?

**Comment by tomholub** [comment]
I actually want it to be added as a "step" after when the user has chosen pass phrase, but before they have reached the screen you posted.

So if I click "create and save" here:

![image](https://user-images.githubusercontent.com/6306961/66398745-d7d2e180-e9cd-11e9-9bb8-52f3192fbdc6.png)

I click green button. A modal would be presented, still on the same screen. The user has not yet finished setup until they have confirmed "Yes I wrote it down".

Once they affirmatively confirm this in the modal, only then would they find themselves at the screen below, at which point the setup is actually done:

![image](https://user-images.githubusercontent.com/6306961/66398823-02249f00-e9ce-11e9-90c4-1cb10b50e999.png)

The goal is to make them pause and think **before the setup is done**, giving them a chance to write it down, or change the pass phrase in case they already forgot it.

**Comment by tomholub** [comment]
re-opening to remember to test this more
