### ISSUE TITLE
recognize other less common iso-8859-2 equivalents 

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#159]
``` js
  if(url_params.message.match(/^Charset: iso-8859-2/m) !== null) {
    return window.iso88592.decode(text);
  }
```

``` js
            'csisolatin2',
            'iso-8859-2',
            'iso-ir-101',
            'iso8859-2',
            'iso88592',
            'iso_8859-2',
            'iso_8859-2:1987',
            'l2',
            'latin2'
```

**Comment by tomholub** [comment]
Please update the regex to match any of the known aliases.

**Comment by michael-volynets** [comment]
I didn't find this code in the project.
Can you please tell me if the issue is still actual?

**Comment by tomholub** [comment]
Ah - it has changed - look for `if (node.charset === 'iso-8859-2') {` at `mime.ts:312`. Actually you can use `Iso88592.labels` to get the list of aliases to compare with. No need to use a regex in this case.
