### ISSUE TITLE
FF: options_page param not supported?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1601]
When you click reload extension in Firefox, this shows:

**FF: Reading manifest: Error processing options_page: An unexpected property was found in the WebExtension manifest.**

Does FF lack this option? Is it called differently?

If no such option on FF, should remove it in `gulp.js` when building FF manifest.
If similar, rename in same step, or see if the renamed version works on Chrome also.

**Comment by michael-volynets** [comment]
What do you mean by reloading extension? Disable And Enable it?

**Comment by tomholub** [comment]
It was when disabling and enabling, but it doesn't do it anymore. Maybe older versions of FF did it. Closing
