### ISSUE TITLE
MIME is rendered as body on encrypted e-mails with attachments but no body

### ISSUE THREAD

**Issue by lkslawek** [FlowCrypt/flowcrypt-browser#1606]
When I'm viewing an e-mail that has no body but only attachment, FlowCrypt shows MIME as message body. The attachment is still available for download.

I've sent the test e-mail from Apple Mail 12.2 (3445.102.3) with GPGMail 3.0.1.

The decrypted `encrypted.asc` constructed by this client is:

```
Content-Type: multipart/mixed;
	boundary="Apple-Mail=_2E6442E0-11D3-4D77-B3C0-93356DA62015"


--Apple-Mail=_2E6442E0-11D3-4D77-B3C0-93356DA62015
Content-Disposition: attachment;
	filename=attachment.txt
Content-Type: text/plain;
	x-unix-mode=0644;
	name="attachment.txt"
Content-Transfer-Encoding: 7bit

An attachment.

--Apple-Mail=_2E6442E0-11D3-4D77-B3C0-93356DA62015--
```

And this above is exactly what gets displayed in Gmail:

<img width="429" alt="Screenshot 2019-03-26 at 16 31 39" src="https://user-images.githubusercontent.com/3786106/55010557-ad4aa980-4fe4-11e9-8e54-3f9317cfe1b8.png">

I've tried it also with Thunderbird + Enigmail pair, but it includes a body part, even if empty.

Also above is how Apple Mail is sending unencrypted e-mails with no character in body, that is, only with attachment part in MIME. I do not know whether the body part is required or not formally, so please decide yourselves if this is a bug for fixing or not.

Observed on Firefox 65.0.1 and FlowCrypt 6.7.0.

**Comment by tomholub** [comment]
Great bug (compatibility) report, thank you. 

Could you please have such email sent to flowcrypt.compatibility@gmail.com

Pubkey at FlowCrypt.com/lookup

Subject: Apple Mail attachment-only PGP/mime with empty body

File content: please add link to this GitHub issue

Thanks again!

**Comment by lkslawek** [comment]
Sure. Actually, I've sent there two e-mails, because accidentally I've discovered just know, that in the same case, when the e-mail is only signed and not encrypted, FlowCrypt shows error "Could not open this message with FlowCrypt" in place of the body. The attachment is available for download also in this case.

So one encrypted and not signed, and one signed and not encrypted.

**Comment by tomholub** [comment]
Awesome, that helps!

**Comment by tomholub** [comment]
The received test emails are at 

https://mail.google.com/mail/u/flowcrypt.commpatibility@gmail.com/#search/empty/WhctKJVJlwNwfQwtPVlxcLcSGJqcHWXcdBTNgjDCqDLXDsKGRmZrxvPzhwblLKcXJtjjSLb

https://mail.google.com/mail/u/flowcrypt.commpatibility@gmail.com/#search/empty/WhctKJVJlwNwfQwsjszLbbrNvxLKbwxtsRWMwkjbBbFknrswTklgdDrSgkpSMdCTxtmhGwb

Please address both cases and make tests for both.

**Comment by michael-volynets** [comment]
I found the reason why the emails aren't rendered correctly. But to fix it I have to remove ` && !Mime.getNodeFilename(node)` in `mime.ts` `decode` method.
```TS
           // mime.ts

            } else if (Mime.getNodeType(node) === 'text/html' && !Mime.getNodeFilename(node)) { // <-- Here
              // html content may be broken up into smaller pieces by attachments in between
              // AppleMail does this with inline attachments
              mimeContent.html = (mimeContent.html || '') + Mime.getNodeContentAsUtfStr(node);
            } else if (Mime.getNodeType(node) === 'text/plain' && !Mime.getNodeFilename(node)) { // <-- And Here
              mimeContent.text = Mime.getNodeContentAsUtfStr(node);
            } 
```

but I'm 100% sure that's a bad solution, could you please explain to me why you added these checkings? What they intended for?
