### ISSUE TITLE
showing reply info tag in sent reply pwd msg

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1646]
1) reply to someone who has not installed flowcrypt
2) use password protection
3) be on a paid plan
4) send and wait for the sent message to render:

![image](https://user-images.githubusercontent.com/6306961/56051054-059bde00-5d3d-11e9-9046-ec0ec9c2ba34.png)

It should not be included in the send success render

**Comment by michael-volynets** [comment]
Can you please explain to me what this function does?
What is the reply token and why it's used for?

```TypeScript
 private addReplyTokenToMsgBodyIfNeeded = async (recipients: string[], subject: string, plaintext: string, challenge: Pwd | undefined, subscription: Subscription): Promise<string> => {
    if (!challenge || !subscription.active) {
      return plaintext;
    }
....
```

**Comment by tomholub** [comment]
"challenge" is another word for message password (a challenge password). Used when emailing to users who don't have any public key. 

Recipient can open such messages online.

We have functionality that allows the recipient to reply. For this, the webpage needs a reply token (which is then passed to our server. This way only someone who can decrypt a message can then reply to it). 

This functionality is only available to paying users, thus the "subscription.active". 

The problem of this issue is that when this gets induced, sender ends up immediately seeing it in the sent reply, which is weird.

If you then reload the convo, I think it doesn't show anymore. So we have some functionality that strips it out, which you can use for rendering sent message too. 

Let me know if I should clarify further

**Comment by michael-volynets** [comment]
I got it,
Thanks for the explanation!
