### ISSUE TITLE
recognize prv backup and show details

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1648]
#1621

Similar to pubkey
allow user to test their pass phrase, say the pass phrase is needed, etc

**Comment by tomholub** [comment]
Michael,

I get many emails similar to:
> How do I open the backup? I tried to open it but don't know how.

To that I respond:

> Hello,
> you don't have to view or open the backup. Feel free to just archive it.
> To verify that your account is backed up properly, please go to FlowCrypt Settings -> Backup. It should say "your account is backed up correctly".
> It is however important to record your pass phrase properly. To verify that you remember it correctly, please go to FlowCrypt Settings -> Security -> Test my pass phrase.
> After that, please note your pass phrase down on a paper. It will be useful if your device ever stops working and you need to get set up on a new one.

-------------

Solution: let's start displaying details about backups, similar to how we recognize and render details about attached public keys.
The work will be somewhere around `replaceAtts`
`pgpNamePatterns` could maybe start returning one big `RegEx` instead of a list of strings. Then `filterAtts` could be simplified a lot.
Example, backups can be recognized with: `(cryptup|flowcrypt)-backup-[a-z]+\.key`
Once you recognize a backup file, you treat it similar to a pubkey. But instead of `pgp_pubkey.htm` frame you would insert `pgp_backup.htm` (a new iframe type).

--------------

The frame will look something like this:
```
This message includes a Public Key backup for some@email.com.

Private key is needed to open your encrypted messages.

Your pass phrase is needed if you ever need import this backup in the future (for example, when setting up FlowCrypt on another device, or when your main device stops working). 

Test that you remember your pass phrase correctly:
[ passphrase _______________  ][ø]   [ TEST PASSPHRASE]  // green btn

KeyWords: SOUP PADDLE MERGE INSIDE SKILL ATTACK // pull from the key
(Fingerprint: 5C42 AD03 B8AA 743A FB13 7C1B CFF3 DA2D BA9C A673) // pull from key

// bottom
```
Then, on the very bottom, it will either say 
```
This key is already imported.
```
or
```
This private key was not imported. We suggest to import all backups so that you can read all incoming encrypted emails.

[IMPORT MISSING PRIVATE KEY] // green btn
```
-------------------------

You can figure out if the key was already imported by extracting primary `longid` from the backup, and trying to find a key with the same `longid` in local private key storage:

```js
const backupKeyLongid = await Pgp.key.longid(backup);
const [matchingStoredKey] = await Store.keysGet(acctEmail, backupKeyLongid);
if(matchingStoredKey) { ... } else { ... }
```
The `IMPORT MISSING PRIVATE KEY` could simply lead to `settings/add_key.htm` page, which you can open by sending a message requesting it to open:
```js
BrowserMsg.send.bg.settings({ acctEmail, page: '/chrome/settings/modules/add_key.htm' })
```
Which should result in an acceptable user experience - you need to test it and let me know.

-------------------

Also remember to add `pgp_backup.htm` into web accessible resources in manifest, plus also test this in Setings -> Encrypted Inbox.

This issue is quite involved, so feel free to ask questions.

**Comment by tomholub** [comment]
There's something I didn't notice when merging it. The backup frame is replacing the whole message, which is not good. It's supposed to be added under the original message, like public key:

![image](https://user-images.githubusercontent.com/6306961/57573264-9cc78480-7414-11e9-8e9d-23feb98e9d8b.png)

Backup (message wrongly replaced)

![image](https://user-images.githubusercontent.com/6306961/57573272-b5d03580-7414-11e9-9b9a-4ba3f1000f25.png)

Backup (before replacing)

![image](https://user-images.githubusercontent.com/6306961/57573273-c1236100-7414-11e9-8b9c-87addb023e07.png)

Further, when you go to FlowCrypt Settings -> Encrypted Inbox, the backup doesn't show at all.

@michael-volynets please fix this before working on any other issue.

**Comment by michael-volynets** [comment]
Okay, I'm looking at it.

**Comment by tomholub** [comment]
@michael-volynets It seems there's a significant mistake that I overlooked earlier. It is testing primary public key from storage, which is not useful:
```js
  const [primaryKey] = await Store.keysGet(acctEmail, ['primary']);
  const { keys: [key] } = await openpgp.key.readArmored(primaryKey.private);
```
It's supposed to be testing and displaying information about the backup.

As implemented, it could never have reached this code:
```js
      $('.line .private_key_status')
        .text('This private key was not imported yet. We suggest to import all backups so that you can read all incoming encrypted emails.')
        .after('<div class="line"><div class="button green" id="action_import_key">Import Missing Private Key</div></div>');
      $("#action_import_key").click(Ui.event.handle(async target => {
        BrowserMsg.send.bg.settings({ acctEmail, page: '/chrome/settings/modules/add_key.htm' });
```
Because private key from your own storage would of course always be already loaded..

I'll go ahead and fix it since I'm already at it.

Hopefully in the future you will see a red flag when you encounter code like that, or when it seems like something doesn't make much sense to implement.

**Comment by tomholub** [comment]
A good way to prevent this situation in the future is to make sure to be confident in how to test all code paths while you're developing. For example, you could ask me:

> How can I test the scenario when a key is not yet imported?

Then I would explain how (log into `flowcrypt.compatibility` account, only import one key during setup, then skip importing of the second one). If you had tested this scenario, you would notice that something is off with your implementation, and you would probably ask me more questions - and this would have been prevented.

I thought of this when I encountered this line:

![image](https://user-images.githubusercontent.com/6306961/57586344-2d20ca80-74e4-11e9-9809-60c358b12e88.png)

The `else` part will never happen because `keysGet` will return an empty array, which is still truthy. All this would 100% be prevented by testing your code in various different scenarios. When not sure exactly how to get the app to the desired state to test something, ask me, I'm happy to help! :+1:

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/57586784-678d6600-74ea-11e9-9252-3b6653773edf.png)

Also without the key imported:

![image](https://user-images.githubusercontent.com/6306961/57586790-84299e00-74ea-11e9-9ccd-6d888fc05d1d.png)

**Comment by tomholub** [comment]
Inbox looks good, thanks for fixing it:

![image](https://user-images.githubusercontent.com/6306961/57586799-c18e2b80-74ea-11e9-8074-9a95cbad7e7c.png)

**Comment by michael-volynets** [comment]
Thanks for the explanation,
It's happened because a lot of code has been copied from recognizing pub key, some parts of the copied code I understood and some I didn't,
Next time I will ask you these things that I don't understand very good.
Thanks a lot again

**Comment by tomholub** [comment]
Better to ask and know.
