### ISSUE TITLE
Recipients Input Text isn't shown in Firefox

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1652]
![image](https://user-images.githubusercontent.com/49104848/56217719-617fa300-606c-11e9-9395-c80a050cf83d.png)

**Comment by tomholub** [comment]
Interesting, on my firefox (production verson) it shows:
![image](https://user-images.githubusercontent.com/6306961/56223522-70ab2480-605d-11e9-961f-552e7a9a4bd8.png)
