### ISSUE TITLE
minimize button utf character not showing

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1653]
@michael-volynets 

On your screen shot from another issue:
![image](https://user-images.githubusercontent.com/6306961/56223562-87517b80-605d-11e9-9c25-2d8199292961.png)

It seems to not render the minimize button properly.

Can you see if updating / fixing a meta tag or something similar will fix it on your device?

If so please add such tag to all pages.

It's supposed to look like this:
![image](https://user-images.githubusercontent.com/6306961/56223633-a6e8a400-605d-11e9-96f6-58465ca8fabf.png)

**Comment by tomholub** [comment]
I have seen a few devices with this issue (one was on Windows 7).

**Comment by michael-volynets** [comment]
I've fixed the icon by installing Unicode characters on my PC, maybe we need to replace this character (🗕) with .svg one?
because the issue can be on other devices as well

And text input is still empty, I'll investigate more.

**Comment by tomholub** [comment]
In that case we cannot rely on UTF icons, yes. Using svg would make more sense.
I didn't know devices can still have utf missing today.
