### ISSUE TITLE
fix test failures

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1657]
I'm seeing consistent failures but it looks like a false alarm. I'll investigate it.

**Comment by tomholub** [comment]
not related but also affects tests
```
ERROR: /home/runner/flowcrypt-browser/extension/chrome/elements/pgp_block.ts[504, 123]: trailing whitespace
ERROR: /home/runner/flowcrypt-browser/extension/chrome/settings/fatal.ts[26, 130]: trailing whitespace
ERROR: /home/runner/flowcrypt-browser/extension/js/common/api/api.ts[329, 22]: (Anonymous function) must clarify return type. Implicit any is dangerous
ERROR: /home/runner/flowcrypt-browser/extension/js/common/api/api.ts[330, 14]: Unsafe use of expression of type 'any'.
```

**Comment by tomholub** [comment]
@michael-volynets 
The following is dangerous:
```js
    isInPrivateMode: (e: any) => {
      return e.message.startsWith('BrowserMsg() (no status text): -1 when GET-ing blob:moz-extension://');
    }
```
You may get various errors:
```
TypeError: a is null
TypeError: a.message is undefined
```
When you use `any`, you have to write code to make sure that it could really be anything. In javascript thrown object can be anything, not just an Error. That's why we use any, we don't know what it is.

But you cannot go from using any (don't know what it is) to writing code as if it was an `Error`. You have to test it.

One way to test it is:
```js
    isInPrivateMode: (e: any) => {
      return e instanceof Error && e.message.startsWith('BrowserMsg() (no status text): -1 when GET-ing blob:moz-extension://');
    }
```
Now you fix the two errors mentioned above. You don't use `any` unsafely (first you checked it's an Error), and because TS now knows that `e is Error`, that means `e.message` is string, that means `e.message.startsWith` returns a `boolean`, so return type is now known.

**Comment by tomholub** [comment]
@michael-volynets Assigning to you so that you can fix it and learn the right habits :+1:

**Comment by tomholub** [comment]
Also, do you have `tslint` extension installed? It should alert you about at least some of these:

![image](https://user-images.githubusercontent.com/6306961/56375642-9ff49980-61f5-11e9-9934-6e688547bc5d.png)

**Comment by tomholub** [comment]
You can also run `npm run internal_tslint_dev_run` to get this checked locally.

**Comment by tomholub** [comment]
I'll do this because I need to do a release soon.

**Comment by tomholub** [comment]
It would be safer to use `unknown` instead of `any` everywhere, I'll make another issue.

**Comment by michael-volynets** [comment]
Yes, I have tslint installed but I think I need to check if it's working correctly because I didn't see those alerts.
Okay, thanks
