### ISSUE TITLE
Add reply btn and separator lines after multiple replies

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1678]
![image](https://user-images.githubusercontent.com/49104848/56850964-39b4f880-6912-11e9-8af8-e9a4822502b8.png)

**Comment by tomholub** [comment]
I will unassign you for now, it's relatively minor.

**Comment by tomholub** [comment]
I will close this - I don't worry too much about the separator, and we track reply buttons now here: #1735

**Comment by tomholub** [comment]
Reason being - the separator is only a relatively minor visual issue, only happening in very specific circumstance (several replies from me on the same page in the same moment). I would rather later spend effort integrating with Outlook or Yahoo.

**Comment by tomholub** [comment]
Of course, functional / behavior oddities are a different story. It's just I'm giving up on trying to match Gmail visual style 100%.
