### ISSUE TITLE
auth popup needed errors during backup / setup?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1685]
not 100% sure if this is auth popup error, but it looks like one. I'm not exactly sure how this could be reproduced, my best guess would be to:

- connect to gmail
- new key
- enter new pass phrases
- abandon the setup
- change password on google
- then come back and click "continue" which will create the backup

----------------
> i am trying to setup flowcrypt on my computer but i am being told that it failed to backup my key. below is a copy of the technical data relating to the error that i am facing.
```
Below are technical details about the error. This may be useful for debugging.

Error string: Error: Unauthorized: 401 when POST-ing https://www.googleapis.com/upload/gmail/v1/users/me/messages/send?uploadType=multipart string: not-a-json

Error stack:     at Function.GoogleAuth.apiGoogleCallRetryAuthErrorOneTime (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/google.js:600:42)
    at async Function.Google.gmailCall (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/google.js:52:10)
    at async doBackupOnEmailProvider (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/backup.js:219:13)
    at async setupCreateSimpleAutomaticInboxBackup (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/backup.js:353:5)
    at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/backup.js:395:6

url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/backup.htm?action=setup&acctEmail=seaneoin22%40gmail.com


provided ajax call stack:
    at Function.GoogleAuth.apiGoogleCallRetryAuthErrorOneTime (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/google.js:600:42)
    at async Function.Google.gmailCall (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/api/google.js:52:10)
    at async doBackupOnEmailProvider (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/backup.js:219:13)
    at async setupCreateSimpleAutomaticInboxBackup (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/backup.js:353:5)
    at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/backup.js:395:6

url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/settings/modules/backup.htm?action=setup&acctEmail=seaneoin22%40gmail.com

    at <async> ajax (/extension/js/common/api/api.ts:618:23)
    at <async> apiGoogleCallRetryAuthErrorOneTime (/extension/js/common/api/google.ts:557:53)
    at <async> gmailCall (/extension/js/common/api/google.ts:46:28)
    at <async> doBackupOnEmailProvider (/extension/chrome/settings/modules/backup.ts:218:34)
    at <async> setupCreateSimpleAutomaticInboxBackup (/extension/chrome/settings/modules/backup.ts:325:48)

Ajax response:
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "required",
    "message": "Login Required",
    "locationType": "header",
    "location": "Authorization"
   }
  ],
  "code": 401,
  "message": "Login Required"
 }
}

End of Ajax response
```

The soulution would probably be to handle the auth needed error similar to what `Encrypted Inbox` does, except that instead of showing a notification, we could show `Ui.modal.confirm` saying that FlowCrypt needs to reconnect. On "OK", it would show the oauth popup window, then recurse to retry if successful.

**Comment by michael-volynets** [comment]
How can I add a new key?

I mean these two steps:
![image](https://user-images.githubusercontent.com/49104848/58101356-254dde00-7be8-11e9-9960-6f2ebfbf71e5.png)

**Comment by michael-volynets** [comment]
When I entered the password after connection new Gmail Account it shows this page

![image](https://user-images.githubusercontent.com/49104848/58103430-9d69d300-7beb-11e9-8967-6fc3832dd157.png)

Do you mean show modal after clicking on 'RETRY' button?

**Comment by tomholub** [comment]
By `new key` I mean choose to create new key, which seems like you have done.

You keep clicking retry and it keeps doing the same thing, right?

I'm not sure about the best way to do the ux here. Somehow we will have to get the user to go through oauth popup again, and then retry the backup step and move on.

Maybe you can show the oauth window when user clicks retry. Or maybe before it ever gets to this screen (for `authPopupNeeded` error). Maybe you don't need to use a modal dialog for this, maybe you can.

I'll leave it up to you. See what's the cleanest way to handle this in the codebase, without worrying too much about UX (in this particular case) as the scenario is very rare. For things that are this rare, not polluting code with ugly hacks is more important than doing the best UX.

Try something and see how it goes. Ask me questions if unsure.

**Comment by michael-volynets** [comment]
Okay, I have almost done the variant when a user clicks on retry and gets a confirm modal.

Also, Is there a way to delete a flowcrypt account?

**Comment by tomholub** [comment]
You can try FlowCrypt Settings -> Additional Settings -> Experimental -> reset account. Let me know if this is what you were looking for.

**Comment by michael-volynets** [comment]
No, I'm looking for to delete the account fully with the pass phrase reset.
So after deleting, I can create the new account with the email I used before but passphrase will be new.

**Comment by michael-volynets** [comment]
Oh, yes, it was that I was looking for, Thanks!

It didn't log me out so I thought it didn't delete my account.

**Comment by tomholub** [comment]
Maybe other users could get confused the same way. What were you expecting? We could make it more obvious in another issue.
