### ISSUE TITLE
update openpgp.js version

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1687]
to v 4.5.1 where subkey-only keys are supported on master branch

**Comment by michael-volynets** [comment]
Here I have to change openpgp.js code to its newer version and correct openpgp.d.ts file, yes?

**Comment by tomholub** [comment]
This one is a very security-sensitive thing, which I'll have to be doing myself. Basically it's only updating the `.js`. The I look over the changes to see if it looks like it will break any functionality, and if any API was updated enough to warrant `openpgp.d.ts` file.

That `.d.ts` file is our own - I maintain my own definitions file, the others were not good enough.

**Comment by michael-volynets** [comment]
Oh, sorry :smile: 
I thought I should do it 

I just saw the "First Priority" and didn't check the Assignee :)

**Comment by tomholub** [comment]
No problem :)
