### ISSUE TITLE
support grabbing keys from a downloadable link

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1692]
Instead of inserting a public key, users could have an option to insert a link where the public key is located, such as:

http://www.shadowscape.eu/pgp/laur
https://www.kraken.com/kraken.asc

Then a simple get request would grab it.

**Comment by tomholub** [comment]
user:

> 
> Here's two examples. First, my public key:
> http://www.shadowscape.eu/pgp/laur
> 
> Perfectly acceptable way of sharing keys, btw, just dump them in a folder on your own website and point people to there.
> 
> Second one is what kraken is doing (was somewhere in your FAQ):
> https://www.kraken.com/features/security/pgp
> 
> You could scrap the page and you'll find it. Or you could expect the user to provide this instead:
> https://www.kraken.com/kraken.asc
> 
> Either way, it feels more user friendly.
> 
> Cheers,
> Laurențiu

**Comment by tomholub** [comment]
Could be allowed in a similar way we allow just pasting the key id, and fetch the key ourselves.

### In contacts

![image](https://user-images.githubusercontent.com/6306961/65754941-a458a300-e101-11e9-8ea2-7aaa51e1c4dc.png)

### When sending

![image](https://user-images.githubusercontent.com/6306961/65755004-bf2b1780-e101-11e9-983a-ec1b7fe9088d.png)

**Comment by tomholub** [comment]
Assigning, though it's still third priority

**Comment by michael-volynets** [comment]
What do you think about listening to `paste` event in those text areas and if the user pasted a link then try to grab pubkey and then render it in the text area?

**Comment by tomholub** [comment]
I was imagining parsing it after button was clicked, but I'm good with your solution too.

**Comment by michael-volynets** [comment]
Done, + 1h 30m
