### ISSUE TITLE
reply button icon larger lock

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1701]
Make the lock much bigger so that it's obvious. Maybe make both the arrow and the lock the same size and put them next to one another - we can try combinations of `[lock][arrow]` or `[arrow][lock]`, depending on what seems more obvious to the user.

![image](https://user-images.githubusercontent.com/6306961/57691799-ac251880-7634-11e9-9623-1b4efadb3b3d.png)

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/1530#issuecomment-492184955_

**Comment by tomholub** [comment]
Before making a PR, it may be better to just produce an edited screenshot of roughly what would the result look like (for the two combinations I mentioned, or another style if you can think of something). When we settle on the design, then you can make a PR. Thanks!

The goal is to make it more obvious to a first time user.

**Comment by michael-volynets** [comment]
I've tried a lot of variants of the icon but if arrow and lock are the same size it doesn't look really good because there isn't a lot of place
to make lock bigger I've done this thing, what do you think?
![image](https://user-images.githubusercontent.com/49104848/57775230-377dd700-7725-11e9-8443-2251ec072a40.png)

**Comment by michael-volynets** [comment]
I used two main colors of Flowcrypt logo

**Comment by tomholub** [comment]
I like the two colors!

That's definitely better, but maybe not quite there yet. I feel like the lock needs to be quite prominent, some people don't have the best sight, some use large res screens..

Something like:

![image](https://user-images.githubusercontent.com/6306961/57776053-11990800-770e-11e9-932c-3509c1076b41.png)

.
.
.

Or:

![image](https://user-images.githubusercontent.com/6306961/57776214-69d00a00-770e-11e9-9ca8-d4d64adae4cb.png)

Does that look ok to you?

I would actually prefer the lock even bigger..

![image](https://user-images.githubusercontent.com/6306961/57776368-c92e1a00-770e-11e9-8b98-691e855da8f5.png)

I don't mind if our icon is wider compared to other icons.

**Comment by tomholub** [comment]
On the screens above I actually squashed the "tail" of the reply icon horizontally, to have lower width, down to about 33% width.

**Comment by michael-volynets** [comment]
What do you think about this one?
![image](https://user-images.githubusercontent.com/49104848/57783289-8ed87300-7736-11e9-8650-a0ea5036cf43.png)

**Comment by tomholub** [comment]
I can live with it. At least it's somewhat bigger. Have you tried the arrow in gray and the circle in green?

**Comment by michael-volynets** [comment]
No, but I think it will be better, wait a minute

**Comment by michael-volynets** [comment]
Take a look, please
![image](https://user-images.githubusercontent.com/49104848/57784915-67cf7080-7739-11e9-84f1-614722fc4d09.png)

**Comment by michael-volynets** [comment]
Another variant when both are green:
![image](https://user-images.githubusercontent.com/49104848/57785250-0c51b280-773a-11e9-964e-4bb911d52c5a.png)

**Comment by tomholub** [comment]
I need to see it in context:

![image](https://user-images.githubusercontent.com/6306961/57788414-9db72980-7726-11e9-9fa4-c02ae713b96b.png)

Gray + green is definitely better, because the graynes implies that the arrow is the same arrow as the gray arrow next to it (meaning reply). It's a bit harder to figure out what the green-only button does, but the gray+green looks quite descriptive. Let's go with your version here:

![image](https://user-images.githubusercontent.com/6306961/57788532-c7705080-7726-11e9-83f1-1656369843d6.png)

What software do you use for this?

**Comment by michael-volynets** [comment]
Okay, Great

Firstly, I used a simple online editor for SVG but it didn't give me a lot of abilities to edit the icon.
Then I downloaded "GravitDesigner" app to work with the SVG icons.

**Comment by tomholub** [comment]
Thanks for looking into it, you saved my time because otherwise I would have to do it myself (I work with Gimp and produce a png, which is not always ideal - svg is definitely better)
