### ISSUE TITLE
"Getting file info..." gets stuck sometimes

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1703]
Tested on chrome:

![image](https://user-images.githubusercontent.com/6306961/57692681-e5f71e80-7636-11e9-9596-56c15c8e751d.png)

Sometimes files have ambiguous names. In these cases, the extension will download a small chunk of the file and try to analyze it to see if it's a PGP message, PGP public key or some other file. If it's some other file, it will leave it alone.

In this case on screenshot (on `flowcrypt.compatibility` email) the message never goes away. When it successfully figures our that the file is not pgp related, the message should go away.

**Comment by michael-volynets** [comment]
@tomholub I couldn't reproduce the issue, can you please tell me the steps how I can reproduce it?

**Comment by tomholub** [comment]
Do you have access to `flowcrypt.compatibility@gmail.com` account? You should find the password in the test-secrets.json file. In the same file, you will also find pass phrases to set it up with (it will ask you during setup).

Once logged in, just find the email from the screenshot. If it doesn't do the same thing, then maybe there is something else I have to look into.

**Comment by michael-volynets** [comment]
Got it, thanks!
