### ISSUE TITLE
tslint no longer highlights long lines

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1707]
At least on my device. Maybe a recent config update broke it

**Comment by tomholub** [comment]
@michael-volynets the tslint extension we use was deprecated, there is now a replacement by Microsoft:

![image](https://user-images.githubusercontent.com/6306961/57793443-dd830e80-7730-11e9-9320-cb415d5734fd.png)

Please remove the previous tslint extension and install this one instead. It should work better.

**Comment by michael-volynets** [comment]
Yes, I updated it and it highlights long lines.

For Note:
If you remember I had an issue with TSLint, it didn't work for me (There aren't any TSLint highlights in VSCode).

To fix it I opened flowcrypt-browser as a workspace.
![image](https://user-images.githubusercontent.com/49104848/58070223-e6e10080-7ba0-11e9-9ffa-b3f9c9e82f20.png)

**Comment by tomholub** [comment]
Ah, yes, I didn't think to tell you that. It should always be opened as a workspace, not just a folder.

I also recommend `PhilHindle.errorlens` extension (the one with more downloads). It will highlight errors very aggressively. Maybe too aggressively, but it helps me not miss them.

Here an extra comma in json file:

![image](https://user-images.githubusercontent.com/6306961/58073173-71b9ff00-7b91-11e9-8bbe-11de1862beef.png)

**Comment by michael-volynets** [comment]
Okay, I will install it, Thanks

**Comment by tomholub** [comment]
If you don't like the extreme verbosity, you don't have to use it (I haven't used it for very long yet, so I will see myself).
