### ISSUE TITLE
async pull list of email aliases from Gmail every time

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1717]
Currently, if user installs FlowCrypt and then adds an alias later, they will have to manually go to settings and have it refreshed for the alias to show in compose window.

It would be better if the extension did it automatically (in the background) each time I open secure compose window.

If it does find a new alias, or an alias was removed, it should save the new info to storage and a `modal.confirm` should show saying `Your email aliases on Gmail have refreshed since the last time you used FlowCrypt. Reload the compose window now?`.

I would not worry about preserving state or the draft, because in 99% of situations this will happen within 1 second of when the window opened, probably before the user has really done anything with it.

**Comment by tomholub** [comment]
Of course, after reloading, it should be able to show the new aliases from the storage right away.

**Comment by michael-volynets** [comment]
I don't exactly understand what is an alias and how I can test it? 
Could you please explain me a little more.
Thanks

**Comment by tomholub** [comment]
See Gmail Settings -> Accounts.

![image](https://user-images.githubusercontent.com/6306961/59882665-6598ab80-93a2-11e9-924d-32e5e6b615f3.png)

![image](https://user-images.githubusercontent.com/6306961/59882692-76492180-93a2-11e9-9b15-d6478d902c4d.png)

All of these are alternative send-from addresses. So I can have an account `acct@gmail.com` but send emails as `something@domain.com` for example.

The it lets me choose the sending address:

![image](https://user-images.githubusercontent.com/6306961/59882781-b1e3eb80-93a2-11e9-803a-641f4394b05e.png)

The issue is, if I just added a new email alias, and open secure compose, it will not notice and not show the new alias. You would have to go to FlowCrypt Settings -> Additional -> Experimental -> Refresh aliases, and after that open secure compose.

That's not a very good ux, so when someone adds or removes an alias, it would be better if the compose window noticed.

For this you should:
 - when secure compose is opened, async check aliases on gmail api
 - if a different set of aliases is found, save them to storage (`addresses`), then reload the window
 - if call fails, ignore it

**Comment by michael-volynets** [comment]
Got it.
Thanks! It will help me to work on this issue!
