### ISSUE TITLE
fix message compose when my own key expired

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1721]
currently it will say that recipient's email is expired.

It should instead say that my own key expired, and offer to renew it.

**Comment by tomholub** [comment]
Sometimes people import keys that may expire in the future.

Then they use the extension happily for a while, and then their key expires.

Then they start seeing "One of your recipient uses expired key" once they hit send. But it's actually their own key at fault. Because every outgoing message also encrypts for their own key, they'll see it for every recipient they try to send a message to.

To test this, we could allow importing of private keys that are expired. With a warning (modal):

> You are importing a key that is expired. You can still import it to read messages from the past, but you will not be able to send new messages using this key. You can add more keys in the settings later.
>
> Proceed with expired key?
>
> [OK] [Cancel]

Then add a test for the setup screen with an expired key.

Then fix the issue when sending out encrypted messages on such account (to make it clear it's the user's own key that's expired). It should say (error modal):

> This message could not be encrypted because your own Private Key is expired.
>
> You can extend expiration of this key in other OpenPGP software (such as gnupg), then re-import updated key in FlowCrypt Settings -> Additional Settings -> Public Key -> Show Private -> update key.
>
> [OK]

(the OK closes the modal, but will not send the message, so user will be looking at the Compose Window)

Then, add an automated test for doing that (updating the key in settinsg). Finally, the test should re-try sending a message, and it should go through after the retry.

**Comment by tomholub** [comment]
Please also check if there is a test for sending encrypted messages when RECIPIENT public keys are expired. If we are not testing it today, please add a test for that too.

**Comment by michael-volynets** [comment]
Just for a note:
I created a key for my Gmail Account that will expire tomorrow at `2021-08-12 ~15:00:00`

**Comment by tomholub** [comment]
Did you use gnupg?

**Comment by michael-volynets** [comment]
No, I used `gpg --gen-key` and then edited expiration date for the key in Linux console

**Comment by tomholub** [comment]
That is gnupg, also known as gpg :)

**Comment by michael-volynets** [comment]
Okay, thanks, I didn't know that :)
