### ISSUE TITLE
hitting escape should dismiss passphrase dialog in gmail

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1733]
![image](https://user-images.githubusercontent.com/6306961/58695255-75653700-8384-11e9-8a62-1190329eb482.png)

https://flowcrypt.com/docs/guide/common-tasks/require-pass-phrase.html

**Comment by michael-volynets** [comment]
Maybe would be better to use here featherlight-dialog? What do you think?

**Comment by tomholub** [comment]
You got me thinking. Why not. On the other hand, now I'm thinking to maybe stop using featherlight in the settings and start doing what we do in Gmail :laughing:  

I like featherlight. But I keep getting errors reports from it, and I don't feel like debugging it.

https://github.com/FlowCrypt/flowcrypt-browser/issues/1625
https://github.com/FlowCrypt/flowcrypt-browser/issues/432

Although it's not a big dependency, it's yeat another 650 lines of code, and all we really need is just an iframe in a box (already have), a close button on top right (easy to add) and an escape handler (a few lines). We could reuse some of the CSS from featherlight.

We have to review all of our code for security (including dependencies) - the fewer code to review, the better, so now I'm thinking to potentially remove featherlight in the future.

**Comment by michael-volynets** [comment]
If you want to remove featherlight at all I think we need to create our own dialogs structure.
So now, I'm going to add `ESC` handler for the passphrase dialog

**Comment by tomholub** [comment]
What do you mean with "our own dialogs structure"?
