### ISSUE TITLE
Change auto-generated text when we forward encrypted message

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1741]
Now we have this generated content if we want to forward someone a message:
```
Some text here.

Forwarded message:

> Some text there.
```

I think would be better if we give more information to the user about the message (From Who, Time, Subject, To), the same way as Gmail does.

```
Some text here.

---------- Forwarded message ---------
From: User Name <User Email>
Date: mm/dd/yyyy
Subject: Re: Subject Line here
To: <User Email>

> Some text there.
```

**Comment by tomholub** [comment]
Make it do whatever the reply does today. But maybe it's already fixed?
