### ISSUE TITLE
attachments in the reply box aren't shown correctly

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1751]
When you click on `Ask sender to update` the attachments in the reply box doesn't align correctly.

![image](https://user-images.githubusercontent.com/49104848/59505114-2acbda80-8ead-11e9-972e-53499596aa64.png)

It could have happened because of flex-box. A while ago we changed styles for showing attachments and it could have become a reason for this bug

**Comment by tomholub** [comment]
That looks bad, thanks for reporting! Please look into it.
