### ISSUE TITLE
Write quote loading tests for issue #873

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1794]
#873

**Comment by michael-volynets** [comment]
@tomholub before I start.
Can you please advice what basically should I test?

**Comment by tomholub** [comment]
Here

> You will want to craft a composer window URL that includes the thread of some other message in it, so that it attempts to reply to that message. Then you test behavior - three dots will load, once loaded, clicking three dots causes text to appear. Do this once for an encrypted message (standard), once for a pgp/mime message, and once for a plain message. That way you'll end up with three tests. This would fall under `compose.ts` tests.
> 
> Remember, do not use id= or class= selectors for tests. Each testable element has a special tag attribute for tests, eg `data-test="action-expand-quoted-text"`, so you'll need to add these into the markup.

**Comment by michael-volynets** [comment]
Okay, Got it, Thanks!

**Comment by tomholub** [comment]
Very roughly, it will look something like this:

```js
    ava.test('compose[global:compose] - standalone - quote - can load quote from plain text email', testWithNewBrowser(async (t, browser) => {
      const composePage = await ComposePageRecipe.openStandalone(t, browser, 'compose', { appendUrl: '&threadId=XXXXXXX', hasReplyPrompt: true });
      await composePage.waitAll(['@action-expand-quoted-text']);
      expect(awair composePage.read('@input-text')).to.not.include('some quoted text...');
      await composePage.waitAndClick('@action-expand-quoted-text');
      await composePage.waitTillGone(['@loader-expand-quoted-text', @action-expand-quoted-text']);
      expect(awair composePage.read('@input-text')).to.include('some quoted text...');
    }));
```
You can either copy-paste three such tests, or you can wrap the test definition (that is the whole ava.test thing) into a for loop with different variables for thread ID and expected snippet.

To run only one test, change `ava.test(` to `ava.test.only(`, then it will ignore other tests.

To debug these tests without running them (by actually doing the actions yourself, or gathering the compose window url, etc), you can run `flowcrypt-consumer-mock` version of the build. For this version to work, you have to run `npm run test_run_gmail_mock`.

**Comment by tomholub** [comment]
The mock gmail api uses email data from a few weeks ago. So don't expect to find new emails in there. Instead, once you run the mock version in one of your chrome profiles (make a new profile for it), just set it up then go to FlowCrypt Settings -> Encrypted Inbox, and there you will see which emails are available in the mock data.

**Comment by tomholub** [comment]
Any questions, let me know :+1:

**Comment by tomholub** [comment]
A note, the `@` idenitifers correspond to `data-test` tags. So `@action-expand-quoted-text` will match a html tag that has a `data-test="action-expand-quoted-text"` attribute.

**Comment by michael-volynets** [comment]
Test Slack

**Comment by tomholub** [comment]
For this to work, you also need to have the password on `test-secrets` that I shared earlier.

**Comment by michael-volynets** [comment]
> A note, the `@` idenitifers correspond to `data-test` tags. So `@action-expand-quoted-text` will match a html tag that has a `data-test="action-expand-quoted-text"` attribute.

Thanks for noticing that.

**Comment by tomholub** [comment]
exactly, you temporarily change it to
```js
    ava.test.only('compose[global:compatibility] - elements/pgp_pubkey renders', testWithSemaphoredGlobalBrowser('compatibility', async (t, browser) => {
      // tslint:disable-next-line:max-line-length
      const pub = `-----BEGIN%20PGP%20PUBLIC%20KEY%20BLOCK-----%0AVersion%3A%20CryptUp%204.3.6%20Gmail%20Encryption%20https%3A%2F%2Fcryptup.org%0AComment%3A%20Seamlessly%20send%2C%20receive%20and%20search%20encrypted%20email%0A%0Ax.....
    }));
```
... just don't push it upstream (remove .only before committing).

**Comment by michael-volynets** [comment]
Okay, Thanks

**Comment by tomholub** [comment]
Looks like there will be more tests to write:
 - Reply -> enter pass phrase dialog -> enter -> ok -> expand -> text present
 - Reply -> enter passphrase dialog -> cancel -> click loader to cancel -> text not present

But these are more complex because they involve several frames, so I propose to solve them in another issue. But once you do these, you will know about all there is to know about our automated tests, and should be able to write tests of any type.

Moving to a new issue.

**Comment by tomholub** [comment]
Make more tests for actual content
 - encrypted html
- plain html
 - encrypted text
