### ISSUE TITLE
Multi-frame (passphrase) tests for loading msg quote

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1797]
#873

Looks like there will be more tests to write:
 - Reply -> enter pass phrase dialog -> enter -> ok -> expand -> text present
 - Reply -> enter passphrase dialog -> cancel -> click loader to cancel -> text not present

But these are more complex because they involve several frames, so I propose to solve them in another issue. But once you do these, you will know about all there is to know about our automated tests, and should be able to write tests of any type.

Moving to a new issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/1794#issuecomment-508410544_

**Comment by michael-volynets** [comment]
Hi @tomholub 

I was trying to create the quoting test with the passphrase but I don't know why the passphrase modal wasn't shown in the test window. Seems like there is some error and in the console, I can see the `Not Found` error. Here is a screenshot of the issue:
![image](https://user-images.githubusercontent.com/49104848/60962298-a129f400-a316-11e9-86c9-98ba08db5d13.png)

And also here is the code of the test
```TS
    ava.test.only('compose[global:compatibility] - reply - pass phrase dialog - ok', testWithNewBrowser(async (t, browser) => {
      const appendUrl = 'isReplyBox=___cu_true___&threadId=16b584ed95837510&skipClickPrompt=___cu_false___&ignoreDraft=___cu_false___' +
        '&threadMsgId=16b584ed95837510&to=flowcrypt.compatibility%40gmail.com&from=flowcrypt.compatibility%40gmail.com' +
        '&subject=Re%3A%20testing%20quotes';
      const messageBeginingText =
        [
          'On 2019-06-14 at 23:24, flowcrypt.compatibility@gmail.com wrote:',
          '> This is some message',
          '>',
          '> and below is the quote',
          '>',
          '> > this is the quote',
          '> > still the quote',
          '> > third line',
          '> >> double quote',
          '> >> again double quote'
        ].join('\n');
      const pp = Config.key('flowcrypt.compatibility.1pp1').passphrase;
      await BrowserRecipe.setUpCommonAcct(t, browser, 'compatibility');
      const settingsPage = await browser.newPage(t, Url.extensionSettings());
      await SettingsPageRecipe.changePassphraseRequirement(settingsPage, pp, 'session');
      const composePage = await ComposePageRecipe.openStandalone(t, browser, 'compatibility', { appendUrl, hasReplyPrompt: true });
      await composePage.waitAndClick('@action-accept-reply-prompt', { delay: 1 });
      await composePage.waitAll(['@input-pass-phrase']);
    }));
```

So the passphrase modal windows wasn't shown at all. And I can't understand the exactly reason of that.
Can you please look at the code?  Maybe you'll notice some mistake or bug.

**Comment by michael-volynets** [comment]
I think I found the solution using inboxFrame but need to check

**Comment by michael-volynets** [comment]
Yes, It's working if I'm using `inboxPage`

**Comment by tomholub** [comment]
If you run the frame standalone, it cannot tell it's parent frame to create modal frames over the top of it, because there's no parent frame. 

To interact with passphrase dialogs, you need to run frames within the context of their parent page, in this case the whole inbox page.

**Comment by michael-volynets** [comment]
Thanks, got it
