### ISSUE TITLE
test that sent message includes previous quote

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1798]
When #1774 - mock email parsing - is done, the next step would be to make sure that messages sent eg by tests from #1794 indeed include the quoted part.

We can differentiate messages by the subject.

eg, very roughly, skipping many details:

```js
'/msg/send': async (req) => {
  const {text, subject, threadId} = await parseAsEmailReq(req);
  if(subject.includes('include quoted part')) {
    expect(await decrypted(body)).to.contain(data.getLastEmail(threadId).body);
  } else if (subject.includes('... other subject')) {
    // test some other thing
 } else {
    // default just pass
  }
}
```

**Comment by tomholub** [comment]
Maybe this is a little too aggressive in terms of testing, given the functionality. There's probably easier and more impactful tests we could do. If you haven't started on this, I'd move it to sometime later.

**Comment by michael-volynets** [comment]
No, I haven’t started it yet. You can move it
