### ISSUE TITLE
replies no longer reuse the same thread on the other end

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1817]
![image](https://user-images.githubusercontent.com/6306961/60980309-c113e480-a323-11e9-97c2-a3a9387f1ea4.png)

This was supposed to be a much longer conversation.

When testing, beware that just because it shows in the same thread on the sender's end does not mean it will show on the same thread on the recipient's end. You need to be looking at the recipient's end.

**Comment by tomholub** [comment]
Please look into this first thing tomorrow, it's a new regression, quite important one.

**Comment by tomholub** [comment]
The problem could either be due to my edit:

https://github.com/FlowCrypt/flowcrypt-browser/pull/1791/files#diff-71cc61c524dc2e78c03a5747baa55f1aR202

Or it could be due to the error handling:

https://github.com/FlowCrypt/flowcrypt-browser/pull/1791/files#diff-f549a749e46085d5ea6e7b9a01bb0270R1435

The error handling causes undefined to be returned even if we already have reply headers, which needs to be fixed either way. If we already have reply headers, they should not get lost of there is error getting the quote.

**Comment by tomholub** [comment]
Another issue, headers should be passed regardless if text is present

https://github.com/FlowCrypt/flowcrypt-browser/pull/1791/files#diff-f549a749e46085d5ea6e7b9a01bb0270R1914

**Comment by tomholub** [comment]
I probably found the actual issue, it's adding the headers when forwarding instead of when replying

```js
     if (method === 'forward') {
        this.additionalMsgHeaders['In-Reply-To'] = this.messageToReplyOrForward.headers.inReplyToHeaders;
        this.additionalMsgHeaders.References = this.messageToReplyOrForward.headers.references;
        this.urlParams.subject = 'Fwd: ' + this.urlParams.subject;
        this.S.cached('icon_show_prev_msg').remove();
        await this.appendForwardedMsg(this.messageToReplyOrForward.text);
      } else {
        if (!this.messageToReplyOrForward.headers.from || !this.messageToReplyOrForward.headers.date) {
          return;
        }
        const sentDate = new Date(String(this.messageToReplyOrForward.headers.date));
        this.msgExpandingHTMLPart = '<br><br>' + this.generateHTMLRepliedPart(this.messageToReplyOrForward.text, sentDate, this.messageToReplyOrForward.headers.from);
        this.setExpandingTextAfterClick(this.msgExpandingHTMLPart);
      }
    }
```
It's supposed to add when replying.

**Comment by michael-volynets** [comment]
Yes, you are correct, I've checked the commit when I changed that part of the code and I changed it incorrectly.

I will fix it in few minutes
