### ISSUE TITLE
test reply headers

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1818]
After #1817 and #1774 is done.

**Comment by michael-volynets** [comment]
Here I should check if `In-Reply-To` header contains in some message of the whole thread. 

I want to test reply headers in this way:

1. Get messages by `threadId`
2. Get `In-Reply-To` header Value and try to find the message from the thread that contains this header
3. If there is the message - then everything is okay - user is replying to existing msg. 

This header is formatted in `RFC2822` standard. Example of  `In-Reply-To` header value:
`<CAKbuLTpiB6g9kBSnBuKVQ6WLuJF=sNdPrrMWCLJhOaEcb4jNzA@mail.gmail.com>`
I don't know what have I to do with this string. I found some info about `RFC2822` format but there isn't any info about msgId.

Maybe you know what I can do with that string?

**Comment by tomholub** [comment]
That whole think is the message ID. If you want it very simple, I think you would just grab all raw mime messages by `threadId` from the mock data, then just check that at least one of the `In-Reply-To` values is contained somewhere in the MIME message.

You may need to remove the `<` and `>`, but whatever is inside of it, you should be able to find in the raw message.

See if that works. If it does, it would keep it simple.

**Comment by tomholub** [comment]
Correction, there can only be one `In-Reply-To` value (eg you can only reply to one specific message, I think).

But there are often many `References` (the whole thread, basically).

For now we will focus on `In-Reply-To` as it is somewhat simpler. For `References`, it's similar except there can be several space-separated values:
```
References: <id1> <id2> <id3>
```
Mime headers are subject to various encodings. Maybe my suggestion above (just searching raw mime string) is too crude. But you should not be manually parsing based on the RFC either. There are libraries for that. I saw that you used a library to parse MIME messages. That same library should be giving you parsed and decoded headers, which you can compare.
