### ISSUE TITLE
Command+Enter (mac) or CTRL + Enter (other) should send email 

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#183]
Similar to Gmail, it's a shortcut, and makes sending emails a little easier.

I wonder what keys are the shortcuts for Windows?

**Comment by tomholub** [comment]
yeah on linux not sure either.. I'll research this later, it's a good one

**Comment by tomholub** [comment]
https://mail.google.com/mail/u/0/#inbox/1601cfd1a34aa236

**Comment by tomholub** [comment]
for Radek

**Comment by tomholub** [comment]
note: this will involve editing `composer.ts`
