### ISSUE TITLE
pass phrase dialog - inbox - bg should span whole screen

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1839]
![image](https://user-images.githubusercontent.com/49104848/61212844-0e20fd80-a70c-11e9-8b29-19dac1f21034.png)

**Comment by tomholub** [comment]
What is the issue? That it's showing red right away, or the positioning of the dialog?

**Comment by michael-volynets** [comment]
the background of the dialog doesn't fit the whole window.
If you look at the bottom of the screenshot you can see a padding
I think the dialog box should always be in the center of the window

**Comment by tomholub** [comment]
Got it. Here is a related issue, visible on longer threads: #1796

**Comment by michael-volynets** [comment]
okay, thanks,
I think we can delete this issue because they are the same

**Comment by tomholub** [comment]
I saw it as two different issues, sort of, though they may have a common fix.
 - This issue is that the background is not covering the whole screen.
 - The other issue is that the dialog itself should be centered.
Of course you can track both problems here and close the other issue, I'll do that.

**Comment by tomholub** [comment]
If fixing the background fixes the position of the dialog too, then it's indeed the same issue.
