### ISSUE TITLE
integrate html editor into compose box

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1861]
continuation from #1630 and final part of #1621 

[##########] cannot do rich text emails or include inline images. (which depends on #1522 which depends on #1620 )

**Comment by tomholub** [comment]
now part of  #1621

**Comment by tomholub** [comment]
This just got unblocked! 

This issue is somewhat tricky. Currently we use our own contenteditable div for email body input. This does not offer any formatting options.

We want to integrate Quill instead. In particular, we have a prototype with our own image-paste-plugin that we want to use available at https://github.com/FlowCrypt/flowcrypt-browser/tree/experimental/issue-1630/Quill%20Editor - I want to use the particular settings as demoed in the prototype

But there are a few gotchas:

1. The default should remain that messages are a simple text (not rich text)
2. User can switch to `rich text` using a popover toggle, "Rich text" (see below)
3. When user switches to rich text, the contenteditable div content should be retrieved, the div removed? and Quill inserted instead? And then the content pasted into the Quill editor?
4. If user switches from rich text to simple text, the Quill content should be read? Then converted to text using `Xss.sanitizeStripAllTags`? Then contenteditable div should be inserted, and the textual representation of the previous Quill put in?

As you see it feels a bit more complex then it should be. One thing you could investigate is to see if it's possible to always use Quill, so that we don't have to switch back and forth, but have some way to enable/disable to Quill formatting functionality, so that it can sometimes behave as a rich text editor and sometimes as an unformatted text field (and make sure to remove formatting using the `Xss` method when switching to unformatted). That would be the easiest.

The toggle is curently only available on our testing account `flowcrypt.compatibility@gmail.com` because of this snippet:
```js
if (popoverOpt === 'richText' && !['flowcrypt.compatibility@gmail.com', 'tom@flowcrypt.com'].includes(this.urlParams.acctEmail)) {
  continue; // richText not supported yet. Only used for testing
}
```
You can either add your email in for debugging, or I can give you access to the compatibility email.

![image](https://user-images.githubusercontent.com/6306961/69285942-f4c41c80-0be9-11ea-8b16-d3b37d5967a1.png)

**Comment by limonte** [comment]
> We want to integrate Quill instead

I took a quick look at Quill repo and it doesn't seem good, the project seems to be stale. Year and a half ago they announced the upcoming major release which still didn't happen: https://github.com/quilljs/quill/commit/a5b203a7503d13e794dee58c9ccf52210674151b

There is a truckload of issues and nobody is fixing or even answering them.

All that means that if (when) we'll face an issue with an editor we most probably won't be able to get the fix even if we fix it by ourselves and submit a PR, the possibility of it being merged and released is low.

---

Alternative: https://github.com/basecamp/trix
 - releases are happening on a regular basis: https://github.com/basecamp/trix/releases
 - issues are answered and resolved when possible: https://github.com/basecamp/trix/issues
 - backed by a trusted company
 - TypeScript

---

@tomholub let me know you thoughts this

**Comment by tomholub** [comment]
Reviewing quill repo, it is true it didn't receive a whole lot of development this year. There's some, not much. More notably, even PRs are not getting merged, even simple ones like docs updates.

But I like how it works, in particular I like the air/bubble mode, when the formatting buttons only show when I highlight something.

Trix seems to be geared too much towards a wiki/document type of editing.

If we're going to search for yet another editor, have a look at https://github.com/neilj/Squire - it's similar to trix, but has been used specifically for email (handling of arbitrary html, blockquotes, etc). Actually Squire may be a really good choice for us. But no air mode.

Given there's no air mode, how would you incorporate the editor visually into the compose window?

**Comment by tomholub** [comment]
I also really like that using Quill we were able to choose size of images, like Gmail lets me, after pasting. But I'm ok to just ignore that feature (don't let perfect be enemy of good).

**Comment by tomholub** [comment]
[Squire](https://github.com/neilj/Squire) has also been designed to use with DOMPurify which we already use. Given it's designed for mail, it seems to be a good fit for us.

**Comment by tomholub** [comment]
To clarify my intention, and what I want to be able to do:

1) I want to be able to paste an image into text
2) I want to highlight some text and press "ctrl+b", "ctrl+u" or "ctrl+i"
3) I want pasted links to be clickable

I don't need any rich text UI for any of these actions. 

Therefore I propose we make the first version with no visible UI!

**Comment by limonte** [comment]
About **neilj/Squire**:
- The project seems to be stale as well, the latest release was 1.5 years ago, there are some recent commits, but the latest test was written a year ago which indicates the low quality.
- I was not able to paste image in their demo both with Firefox and Chrome on Linux.

I also checked https://github.com/summernote/summernote/ (found it in @michael-volynets pinned repos)
It has a Bootstrap dependency which doesn't seem like an option for us.

**Comment by tomholub** [comment]
We tested and demoed summernote, it was buggy as hell. Each minor version behaved differently, and always wrong.

Not able to paste images in Squire? I just Google "cat" and then right-click, copy image, then ctrl+v in the box:

![image](https://user-images.githubusercontent.com/6306961/69532845-94790600-0f6e-11ea-8daa-bf9c1f4fd4e5.png)

Both on FF and Chromium

**Comment by limonte** [comment]
> Not able to paste images in Squire? I just Google "cat" and then right-click, copy image, then ctrl+v in the box:

I'm using [Flameshot](https://github.com/lupoDharkael/flameshot) for taking screenshots. In Flameshot it's possible to select the area of the screen and hit `Ctrl+C` to put the screenshot to clipboard. After that I'm able to paste screenshot anywhere except Squire. 

> I just Google "cat" and then right-click, copy image, then ctrl+v in the box:

Strangely enough, this works for me as well. I don't know what the difference in copying with Flameshot and with the system context menu.

**Comment by tomholub** [comment]
:(

I just tried Gimp "Take Screenshot" utility and same result.

**Comment by tomholub** [comment]
I would go with Trix, but I'm afraid that it won't work well (or at all) for processing arbitrary quoted html and blockquotes.

But maybe it's not so bad. Better then not being able to paste images!

**Comment by tomholub** [comment]
https://github.com/neilj/Squire/issues/369#issuecomment-558380485 they say image paste works in Squire, and that their online demo is old.

I'd go with them if we can confirm this is the case.

**Comment by tomholub** [comment]
Inside encrypted email, embedded img like I mentioned in https://github.com/neilj/Squire/issues/369#issuecomment-564780443 will work well.

For non-encrypted email, it's more complicated, but we can look into that later, and for now just paste the images straight into regular attachments instead (on a non-encrypted message).

**Comment by tomholub** [comment]
For converting to base64 we use `Buf` class. If you can get uint8 from the blob, then `Buf.fromUint8(uint8).toBase64Str()`.

**Comment by tomholub** [comment]
Buf stands for Buffer, it's inspired by Node's Buffer, but more explicit in what you're converting from/to.

**Comment by limonte** [comment]
I was playing with Squire in my sandbox, here's the result: https://limonte.github.io/squire-sandbox/

> I want to be able to paste an image into text
This is clear now after getting some help from https://github.com/neilj/Squire/issues/369#issuecomment-564780443

> I want to highlight some text and press "ctrl+b", "ctrl+u" or "ctrl+i"
Shortcuts are working, it possible to disable them, that'll be needed when switching editot into the "plain text mode", you were suggesting it above:

> One thing you could investigate is to see if it's possible to always use Quill, so that we don't have to switch back and forth, but have some way to enable/disable to Quill formatting functionality, so that it can sometimes behave as a rich text editor and sometimes as an unformatted text field (and make sure to remove formatting using the Xss method when switching to unformatted).

> I want pasted links to be clickable
This is unlear for now, links aren't clickable in Fastmail and Protonmail. I guess you were thinking about something Gmail-like?

![image](https://user-images.githubusercontent.com/6059356/70750701-8e897000-1d37-11ea-8b6f-ff9773e3bf24.png)

**Comment by tomholub** [comment]
- I like the "remove formatting" button! That lets me highlight and clear a section.
 - pasting links works! - what I actually meant is just copy a link from url bar (plain) and paste into the text, it should get decorated with anchor (it does)

todo:
 - [ ] going to a new empty line, and clicking "CTRL+B" inserts `- [ ]` (**b**ullet) which I'd like to disable if easy enough (I was testing if maybe I can ctrl+b and then start typing in bold, but that is not really a requirement - but typing mid sentence, selecting nothing and hitting ctrl+b does do exactly what I'd expect). Interestingly, this happens even with shortcuts disabled - but ideally it would never happen.
 - [ ] rendered image should have style `max-width: 95%` ? or similar so that if it's wider than the view, it would fit in it

But as far as I can tell this is basically almost ready for integration. (Unless working with Squire made you distrustful of it enough to strongly recommend Trix instead?)

-------------------------

![image](https://user-images.githubusercontent.com/6306961/70791782-a856a180-1d8f-11ea-8b9e-f5c668e886cf.png)

**Comment by tomholub** [comment]
Not sure what I've done here, cannot reproduce:

![image](https://user-images.githubusercontent.com/6306961/70792151-7f82dc00-1d90-11ea-97de-518a2ce363be.png)

**Comment by tomholub** [comment]
So far very happy with it :)

**Comment by limonte** [comment]
> going to a new empty line, and clicking "CTRL+B" inserts - [ ] (bullet) which I'd like to disable if easy enough (I was testing if maybe I can ctrl+b and then start typing in bold, but that is not really a requirement - but typing mid sentence, selecting nothing and hitting ctrl+b does do exactly what I'd expect). Interestingly, this happens even with shortcuts disabled - but ideally it would never happen.

I can't reproducte this (both FF and Chrome), are you sure this isn't some smart extension in your browser / system snippet?

>  rendered image should have style max-width: 95% ? or similar so that if it's wider than the view, it would fit in it

Added `max-width: 100%`, anything less than 100% makes it look a bit ugly as we're not centering images.
The gap will be handled by `#input_text` paddings, the same way it is handled now:

![image](https://user-images.githubusercontent.com/6059356/70793682-8d425c80-1da4-11ea-8f7f-3aecd848833c.png)

> But as far as I can tell this is basically almost ready for integration. (Unless working with Squire made you distrustful of it enough to strongly recommend Trix instead?)

I'm quite happy as well. Except I didn't find types for Squire.

> Not sure what I've done here, cannot reproduce:

Handled :+1:

**Comment by tomholub** [comment]
> I can't reproducte this (both FF and Chrome), are you sure this isn't some smart extension in your browser / system snippet?

I can't reproduce it now either. I'll consider it solved until I can find a way to reproduce :+1:

**Comment by limonte** [comment]
Alright, moving from my sandbox to FlowCrypt then :)

**Comment by tomholub** [comment]
I think we're good, and can start integrating this.

> I'm quite happy as well. Except I didn't find types for Squire.

On your regular billable hours, feel free to author the types, and either submit them to DefinitelyTyped or directly to the repo (better), in a way that would have loaded the types if we installed the package through npm.

The types don't have to be complete at all, just a small subset of the functionality that we actually use. That way others can have something to extend later.

**Comment by tomholub** [comment]
First, initial PR should integrate Squire but leave all of its functionality disabled, with no way to enable.

The way it would be used when `rich text` was not enabled.

 - shortcuts do nothing
 - text is stripped of html as it is pasted
 - pasting images does nothing
 - pasting a plain url does nothing

**Comment by tomholub** [comment]
We'll merge that initial PR and release it, see if any issues come back, and only later start enabling the rich text functionality over time.

**Comment by limonte** [comment]
> We'll merge that initial PR and release it, see if any issues come back, and only later start enabling the rich text functionality over time.

Sounds reasonable :+1:

**Comment by tomholub** [comment]
Code that does initialization and assigning handlers to events could go in `composer-input.ts:initActions()`. Then individual event handlers as private methods of the `ComposerInput` class.

Actually I'll refactor it a tad bit before you start.

**Comment by limonte** [comment]
> First, initial PR should integrate Squire but leave all of its functionality disabled, with no way to enable.
> 
> The way it would be used when `rich text` was not enabled.
> 
>     * shortcuts do nothing
> 
>     * text is stripped of html as it is pasted
> 
>     * pasting images does nothing
> 
>     * pasting a plain url does nothing (I mean - leaves the url plain, not anchored)

This is done in my sandbox for now (the PR for `flowcrypt-browser` is almost ready as well): https://limonte.github.io/squire-sandbox/

In the UI there's only one checkbox "Rich Text" which simulates how it'll work in FlowCrypt. Please test out the plain text mode, everything from the list above should work.

One technical detail: I'm using and importing `html-to-text` dependency. It allows converting HTML to nice text before pasting. All line-breakes are preserved and some nice features are there, e.g. numbers for `<ol>`. ProtonMail is also using something like that:

![1](https://user-images.githubusercontent.com/6059356/70952332-97977b80-206e-11ea-85e4-493cf8de243e.gif)

The `import` statement isn't working in `flowcrypt-browser`:
![image](https://user-images.githubusercontent.com/6059356/70952137-0e804480-206e-11ea-8b82-1d58b5d3c19f.png)

How should I procees with converting HTML to text? @tomholub

**Comment by tomholub** [comment]
It looks good. In FlowCrypt we use `Xss.htmlSanitizeAndStripAllTags` (meaning just formatted text is left), combined with `Xss.htmlUnescape`. You can see it in `composer-input`:

```js
  public extract = (type: 'text' | 'html', elSel: 'input_text' | 'input_intro', flag?: 'SKIP-ADDONS') => {
    let html = this.composer.S.cached(elSel)[0].innerHTML;
    if (elSel === 'input_text' && this.composer.quote.expandingHTMLPart && flag !== 'SKIP-ADDONS') {
      html += `<br /><br />${this.composer.quote.expandingHTMLPart}`;
    }
    if (type === 'html') {
      return Xss.htmlSanitizeKeepBasicTags(html);
    }
    return Xss.htmlUnescape(Xss.htmlSanitizeAndStripAllTags(html, '\n')).trim();
  }
```
The rough opposite of that is `Xss.escapeTextAsRenderableHtml`.

If you're going to be inserting it back into the DOM (just remove formatting and place back), then you probably just want to do `Xss.htmlSanitizeAndStripAllTags(html, '<br>')` without the escapes / unescapes.
