### ISSUE TITLE
Find more consistent icons  for compose window

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1866]
I would like to change `Feedback of Help` icon. `Trash` icon, and make `maximize` and `minimize` icons a little bit thinner.

**Comment by tomholub** [comment]
Actually we could use icons from https://icons8.com/icons

MIT Licensed

They are very consistent, and they have very many of them so we don't have to worry about finding the right icon.

On iOS we use the iOS icons: https://icons8.com/icons/ios

On web we could reuse the iOS icons, maybe, or we could choose one of the Material styles they have.

**Comment by tomholub** [comment]
I'm closing this for now. While the current icons are inconsistent, they don't bother me too much. We'll probably look into it some other time.

**Comment by tomholub** [comment]
Probably the most noticeable are the header icons - different weights / thicknesses / styles.

![image](https://user-images.githubusercontent.com/6306961/70621410-66075600-1c11-11ea-8e35-548c09a8deeb.png)
