### ISSUE TITLE
sometimes pgp frames double up

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1870]
This is an intermittent error. Sometimes the content scripts will render two iframes instead of one.

For example, a message will show up twice (two pgp_block iframes) or it will show double the amount of attachments (10 instead of 5).

We replace everything once a second. I think this will happen when some stage of the replacing takes more than a second, before the DOM is updated to indicate that the content script is replacing it, but after a second has passed for another replace to take place.

![image](https://user-images.githubusercontent.com/6306961/62081238-bd4bf180-b241-11e9-928e-87341bca2d17.png)

Tests will also fail because they expect one block, but two show:

![image](https://user-images.githubusercontent.com/6306961/62081317-dd7bb080-b241-11e9-8fb8-642b58be1787.png)

![image](https://user-images.githubusercontent.com/6306961/62081301-d654a280-b241-11e9-828a-5b35fe2be05f.png)

You can probably catch this error easily when you temporarily lower replace interval down to 100 or 50 ms, then try to open a few messages. I think sooner or later you should encounter it. If not, try even faster interval.

**Comment by tomholub** [comment]
Unassigned until I see it happen in tests again

**Comment by tomholub** [comment]
Thanks for taking a look

**Comment by limonte** [comment]
from https://github.com/FlowCrypt/flowcrypt-browser/issues/2247#issuecomment-561821098

> Yes. Happens to attachments as well (eg 5 encrypted attachments become 10 encrypted attachments).
> 
> We replace contents of the browser once a second. I could imagine, if some steps takes longer than a second, and stars align just right, the next replace-run will not realize this message is already getting processed, and replace it as well. When both finish, original message is gone, but there are now two replacements.
> 
> There's a class that we add to the message that signifies that a message is being processed/replaced. Maybe we add the class too late in the replace process? Maybe Gmail will sometimes remove that class?
> 
> This is noticeable sometimes in CI.

You're most probably right, I noticed that whenever that happens, it takes a bit longer (more than one second) to load the email.

**Comment by tomholub** [comment]
Race condition somewhere.

**Comment by limonte** [comment]
This one is really tricky to catch, but IMO it should be caught asap because the UX might be bad in cases the Internet connection is slow:

![image](https://user-images.githubusercontent.com/6059356/70322718-84e1a300-1833-11ea-9b5a-c7fe9482dce1.png)

I'm on it now :male_detective: :beetle:

**Comment by tomholub** [comment]
Does slower internet connection contribute to is? That would be a good lead.

You can slow down your browser connection in the console. Thanks!

**Comment by limonte** [comment]
After rebasing to `master` I can't reproduce this issue anymore. To make sure, I reset the repo to https://github.com/FlowCrypt/flowcrypt-browser/commit/6a0341efdabe5d17781129f3be536bb307a5f699 and (after rebuilding of course) I was able to reproduce it. Then I switched back to `master`, rebuilt again, and unable to reproduce the issue. Tested manually something around 50 times with different throttling in dev tools.

For now, I'll close the issue, please reopen if you face it again.

**Comment by tomholub** [comment]
Interesting, I don't think we did anything special between https://github.com/FlowCrypt/flowcrypt-browser/commit/6a0341efdabe5d17781129f3be536bb307a5f699 and now. I'll re-open when I observe it again.

**Comment by limonte** [comment]
Reopening as I faced it again. Good news is that I figured out that in order to reproduce it more frequently (50/50) this nice feature of Chrome Dev Tools can be used: https://umaar.com/dev-tips/88-cpu-throttling/

![image](https://user-images.githubusercontent.com/6059356/70380395-a5008780-1943-11ea-9dd4-634b4d3cd3c4.png)

**Comment by tomholub** [comment]
That's an interesting feature for sure! :)

**Comment by limonte** [comment]
@tomholub I have to give up on this issue, at least for now. With CPU throttling I am able to reprocuce it frequently (in 50% cases), but I'm not familiar enough with the codebase to track the issue down.

**Comment by tomholub** [comment]
Thanks, it's already very valuable to be able to reproduce it. I'll see if I can reproduce & fix it.

**Comment by tomholub** [comment]
I can't reproduce it whatsoever :( even with 6x slowdown. 

![image](https://user-images.githubusercontent.com/6306961/70393909-5f959600-19e7-11ea-8bf6-0d896087a1f8.png)

If you can reproduce it relatively reliably, we could do a screenshare, and fix it together.

**Comment by tomholub** [comment]
Ok I can reproduce it now, message from ProtonMail

(my note) https://mail.google.com/mail/u/0/#label/tests%2Fencrypted/WhctKJVJkvgpnFCgwnbKSgVXRxLPdkMmMzqzKdNVNbZbFrGHMLVkGNdMhZVWzLcwKMgWPxV

**Comment by limonte** [comment]
This issue is happening to me again in both browsers:

![image](https://user-images.githubusercontent.com/6059356/76258538-7359ce00-625c-11ea-9a1d-f22cae53a280.png)

@tomholub can you reproduce it with your last message to me with two attached PDF files?

**Comment by tomholub** [comment]
> @tomholub can you reproduce it with your last message to me with two attached PDF files?

Nope, renders as one message here.

**Comment by limonte** [comment]
I added `console.trace()` to `XssSafeFactory.embeddedMsg()`

![image](https://user-images.githubusercontent.com/6059356/76618865-46463d80-6532-11ea-80d8-8852b788806d.png)

The unwanted `XssSafeFactory.embeddedMsg()` is getting called from `GmailElementReplacer.processAtts()`.

**Comment by tomholub** [comment]
That's what I would have thought, but not sure how to address it (without investigating and fixing it). Do you have any idea?

**Comment by limonte** [comment]
> That's what I would have thought, but not sure how to address it (without investigating and fixing it). Do you have any idea?

Debugging right now, will report my findings

**Comment by tomholub** [comment]
It will involve somehow making sure the same attachment does not get processed twice, some sort of a lock mechanism, possibly through adding some parameter to DOM.

Alternatively, best would be if you somehow knew that the attachements container is fully loaded, and only process it then, and only once.

**Comment by limonte** [comment]
@tomholub now I'm wondering how did you create the message which doubles pgp frames :)

When I'm sending a rich text message (e.g. to myself) it looks like this:

![image](https://user-images.githubusercontent.com/6059356/76642954-d4371e00-655c-11ea-9100-dfce72916008.png)

There are two files: `noname` and `encrypted.asc`, the message itself is empty.

On the other hand, your message is not empty and contains only `noname`:

![image](https://user-images.githubusercontent.com/6059356/76643048-034d8f80-655d-11ea-9cd8-a9312e2a07ea.png)

![image](https://user-images.githubusercontent.com/6059356/76643060-0b0d3400-655d-11ea-839f-4a89aeb0e8d1.png)

**Comment by limonte** [comment]
The message I'm asking about is the recent message with two attached PDF files.

**Comment by tomholub** [comment]
Please do `...` -> more -> Show Original -> Download original, and send me the raw mime text (attached) it downloads, with a link to this issue.

**Comment by limonte** [comment]
> Please do `...` -> more -> Show Original -> Download original, and send me the raw mime text (attached) it downloads, with a link to this issue.

Sent via email :+1:

**Comment by tomholub** [comment]
Interestingly, the email itself that you sent is doubling up. Maybe the fact that it contains a large attachment is affecting it.

**Comment by tomholub** [comment]
This is I think a different issue from before, but with a similar outcome.

The issue I was trying to chase (and thought I fixed?) earlier was a flaky one. This one keeps rendering double reliably, it's different. Either way, I should fix it.

**Comment by limonte** [comment]
> This is I think a different issue from before, but with a similar outcome.
> 
> The issue I was trying to chase (and thought I fixed?) earlier was a flaky one. This one keeps rendering double reliably, it's different. Either way, I should fix it.

Correct. The reason is different, I'll file a separated issue.

**Comment by tomholub** [comment]
I'll close this one for now, we can reopen it if we still encounter this sometime after the big-attachment cause is fixed.

**Comment by tomholub** [comment]
Then I'll address your newly opened issue.
