### ISSUE TITLE
Change Recipients list when you are replying to your own message

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1871]
When you are replying to your own message in a thread you can see that in the reply window in recipients list you are replying to yourself, here is a screenshot:
![image](https://user-images.githubusercontent.com/49104848/62298835-73028480-b47c-11e9-83f2-b6523cb6982a.png)

I think would be better if you are replying to the previous message AND previous message sender is you then take the emails from `to:` header and fill them in the recipients' list

**Comment by tomholub** [comment]
Is michael.flowcrypt2 an alias on michael.flowcrypt?

**Comment by michael-volynets** [comment]
No, it isn't an alias?

**Comment by michael-volynets** [comment]
It's another account

**Comment by tomholub** [comment]
If it's another account, I would not treat it any special way. Only for aliases (where it should behave as expected). So I would suggest to close this as wontfix

**Comment by michael-volynets** [comment]
Okay, Got it,
Thanks.
