### ISSUE TITLE
+ add intro button does not disappear when I click "Sign" icon

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1879]
1) add recipient (no pgp) and message
2) switch to sign
3) Green `+ intro` button is still visible. It should hide when I click sign.

**Comment by tomholub** [comment]
Please add a test for this one

**Comment by michael-volynets** [comment]
Can you please explain to me the logic?
I found the code that should hide `add_intro` button but I see this `if` expression:
```TS
    if (!$('.recipients span').length) {
      this.hideMsgPwdUi(); // <-- This call hides add_intro btn
      this.S.cached('send_btn').removeClass('gray').addClass('green');
    }...
```
If we follow the code it works as it's expected

**Comment by tomholub** [comment]
Here's what it means:
```
    if (!$('.recipients span').length) {
      this.hideMsgPwdUi(); // <-- This call hides add_intro btn
      this.S.cached('send_btn').removeClass('gray').addClass('green');
    }
```
If the user has just deleted the last recipient, there is no need to continue showing UI elements related to "password protected message", which includes the intro. 

Without this code, when I add askjdlkasjdklasjdaklj@gmail.com, then remove it, the compose window will be stuck in "add password" until I add another recipient, which is weird.

You can add a short comment to clarify the code.

Also, this may be an interesting thing to add a test for, as well.

**Comment by michael-volynets** [comment]
Got it, Thanks
