### ISSUE TITLE
do not submit key to alias @yahoo addresses

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1885]
I get email like this once a week from users:

> Trying to figure out if this will work for me. In testing, if I email myself at another gmail address, the received message decrypts fine. But if I send it to myself at a Yahoo email address, I just receive encrypted gibberish, but no instruction as to how to decrypt. So does it only work with gmail addresses?
> Thank You!
> *******
> FlowCrypt chrome 6.9.3

Typical answer:

> Hello,
> the issue is most likely that you have your yahoo address listed as one of your gmail aliases. FlowCrypt thought you have FlowCrypt installed on that address, too (it's your address, after all).
> Try to send it to another yahoo address, it should give you options that work.
> https://flowcrypt.com/docs/guide/send-and-receive/send-password-protected.html
> https://flowcrypt.com/docs/guide/send-and-receive/open-password-protected.html

-------------------

I suspect most users just uninstall when this happens.

During setup, when looking for other aliases to submit a pubkey for, please filter out any email aliases that contain the string `@yahoo` and also `@live` and also `@outlook`.

This will cause the pubkey to be not submitted for these addresses, resulting in a smoother experience when the user later wants to test sending emails to their own address.

**Comment by michael-volynets** [comment]
Okay, I got it, I'm going to start working on it and also I want to ask you a question:
Why should we filter only `@yahoo`, `@live` and `@outlook`? 
I mean why couldn't we allow only `@gmail` to submit pub key for?
