### ISSUE TITLE
Maximized Secure Compose Window is getting closed after closing aliases popup

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1900]
#### Step to reproduce:

1. Maximize the Secure Compose Window
2. Click "Settings"
![image](https://user-images.githubusercontent.com/6059356/62851372-8c15fb80-bcee-11e9-8132-501f81c4f0ba.png)
3. Close settings

#### Expected:

Settings popup is closed, Secure Compose Window is shown

#### Actual:

Settings popup is closed, Secure Compose Window is minimized

**Comment by tomholub** [comment]
Interesting, thanks

**Comment by tomholub** [comment]
Not at all on my device (ff/chrome). Could you try again? Possibly make a video?

**Comment by limonte** [comment]
My bad, I used incorrect wording, "maximize" is the wrong word. The correct steps to reproduce would be:

1. Make the Secure Compose Window full-screen
2. Click "Settings"
![image](https://user-images.githubusercontent.com/6059356/62851372-8c15fb80-bcee-11e9-8132-501f81c4f0ba.png)
3. Close settings

**Comment by tomholub** [comment]
Sorry! It's me who overlooked the "maximize" part, which is a correct word to use I think.

Yes! I reproduced this, totally a bug and a great discovery.
