### ISSUE TITLE
Top padding is missing for the mail body

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1902]
Spacing between the horizontal line and email body is missing:

![image](https://user-images.githubusercontent.com/6059356/62852310-b87f4700-bcf1-11e9-876b-c45c7dd62ee0.png)

This is a tiny detail, but my brain is reacting to it as "something is broken here" :smile:

**Comment by tomholub** [comment]
Very good. I think this is Firefox specific. I also cannot stand it. You could double check on Chrome

**Comment by limonte** [comment]
> Very good. I think this is Firefox specific. I also cannot stand it. You could double check on Chrome

Yup, Firefox only. All is well in Chrome.
