### ISSUE TITLE
The "Public key" icon looks off

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1904]
![image](https://user-images.githubusercontent.com/6059356/62853490-32fd9600-bcf5-11e9-9374-4e8b610f83f8.png)

This icon looks odd and interrupting the consistency of UI.

Something like the "key" icon would be expected here by me:

![image](https://user-images.githubusercontent.com/6059356/62853568-6c360600-bcf5-11e9-9037-1c98f249c97d.png)

**Comment by tomholub** [comment]
Yes. And no :laughing: 

Yes for the PK button totally out of place. I made that thing myself :blush: 

But I don't want to use a "key" icon either. To new users, key is something secure. But public key does not have that much to do with security from user stand point (unlike private key, or pass phrase for example). Other systems as S/MIME call it "certificate". I think if you could find appropriate certificate icon, that would be great. Then when they hover, maybe call it "Public Key Certificate" ? 

I would like to transition to using https://icons8.com/ , if you could find and propose a good "Certificate" icon, we could go with that. If we find most icons there, we could achieve more consistency.

They have some options but nothing I'm quite happy with:

![image](https://user-images.githubusercontent.com/6306961/62882494-87b70600-bd21-11e9-89d5-b725f2fdd0f4.png)

**Comment by limonte** [comment]
This one can fit the FlowCrypt styles: https://icons8.com/icon/11169/certificate

![image](https://user-images.githubusercontent.com/6059356/63084209-59207180-bf53-11e9-8a72-71f09cd3d36b.png)

![image](https://user-images.githubusercontent.com/6059356/63084853-d1d3fd80-bf54-11e9-8c62-867e4ddd5886.png)

@tomholub WDYT?

**Comment by tomholub** [comment]
Yup, perfect
