### ISSUE TITLE
Click on the header should toggle Secure Compose Window

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1905]
![image](https://user-images.githubusercontent.com/6059356/62855516-27ad6900-bcfb-11e9-81cb-f5e7a8886280.png)

When a user clicks on Secure Compose Window header, Secure Compose Window should:

- store the current state (normal or maximized) and minimize the popup when it's not minimized
- restore the visibility state (normal or maximized) when it's minimized

**Comment by tomholub** [comment]
Just to clarify, should it simply act as clicking minimize / maximize button based on context, or do you also propose change to how to minimize/maximize buttons behave?

**Comment by limonte** [comment]
> Just to clarify, should it simply act as clicking minimize / maximize button based on context, or do you also propose change to how to minimize/maximize buttons behave?

Simply act as clicking minimize / maximize button based on context

**Comment by limonte** [comment]
@tomholub @michael-volynets this is not working anymore, the `click` handler was removed in https://github.com/FlowCrypt/flowcrypt-browser/commit/6500219e7d8ca6e3691f0ca9452d8751bfb09087#diff-f549a749e46085d5ea6e7b9a01bb0270L982

Was it done on purspose or accidentaly?

**Comment by tomholub** [comment]
This must have been accidental, possibly a merging error.

**Comment by tomholub** [comment]
I've made another issue to add a test for it, that way we know the functionality won't break in the future.
