### ISSUE TITLE
Controls in Secure Compose Window should be tab-friendly and indicate the focused state

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1906]
Some people prefer not to touch their mouse/trackpad and use a keyboard for navigating fields, buttons and other controls:

![Peek 2019-08-12 12-19](https://user-images.githubusercontent.com/6059356/62855648-79ee8a00-bcfb-11e9-89da-9de86bd0e9bd.gif)

In Secure Compose Window I can't always see which element is currently focused, all these buttons aren't accessible with a keyboard:

![image](https://user-images.githubusercontent.com/6059356/62855857-fc774980-bcfb-11e9-8a30-faa10e128c54.png)

**Comment by tomholub** [comment]
Excellent
