### ISSUE TITLE
Secure Compose Window should trap the focus

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1907]
When inside Secure Compose Window, the focus should be "trapped" in the same way as native Gmail popup is doing. Here's the demo of "trapped" focus http://davidtheclark.github.io/focus-trap/demo/

This is important in order to make keyboard-ninjas and disabled people happy with FlowCrypt.

**Comment by tomholub** [comment]
Here again it would be super useful to know which one. Or did you mean the secure compose window? Screenshot would be best :+1:

**Comment by limonte** [comment]
Yup, sorry, the "main" popup :) Is there maybe a better name for it which I can use?

![image](https://user-images.githubusercontent.com/6059356/62858631-7959f180-bd03-11e9-90e6-d41c75a7ff3c.png)

**Comment by tomholub** [comment]
I'd call it secure compose window. We have too many other types of frames / popups / modals etc.

**Comment by limonte** [comment]
Alright, secure compose window it is, thank you. I will amend my reports and use this term in future reports.

**Comment by tomholub** [comment]
Awesome, thanks
