### ISSUE TITLE
Escape should perform save & close action

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1908]
Closing Secure Compose Window should be possible with a keyboard. The common practice for closing popups is to use `Esc`. Gmail, for example, is using that.

At the moment, nothing is happening with Secure Compose Window when pressing `Esc`.

**Comment by tomholub** [comment]
Which popup did you test this on - the browser action button popup? Or during oauth?

Some of our modals respond to esc, so it would be great to know which ones don't. Thanks!

**Comment by limonte** [comment]
Sorry for not being specific enough in my report. I meant this popup:

![image](https://user-images.githubusercontent.com/6059356/62858594-66dfb800-bd03-11e9-973e-e76d8d89658e.png)

**Comment by tomholub** [comment]
Ah! Never thought of that before. Very good.
