### ISSUE TITLE
The "Upgrade to FlowCrypt Advanced" popup doesn't feel 100% secure

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1909]
![image](https://user-images.githubusercontent.com/6059356/62859934-5a5d5e80-bd07-11e9-8f55-76ee1461ce3d.png)

The form doesn't feel safe to me:

1. Simple input fields with placeholders make an impression that the form is in WIP state
2. CVV field isn't visible unless the expiration date field is focused

What I'd expect there is something like https://github.com/jessepollak/card

---

There should also be some links leading to the information about the payment protection and security (e.g. https://stripe.com/docs/security/stripe)

**Comment by tomholub** [comment]
I agree that it looks wip. It kind of is.

To be honest, majority of our income comes from enterprise clients who don't use this form. Second largest is group subscriptions who use https://flowcrypt.com/billing#calculator ... which explains why the basic subscription form was left as a kind of afterthought. It has usability issues for sure, and thanks for pulling out your credit card to try it out! I did not though you'd do that, but now thinking about it - it makes total sense, payments is what keeps us in business.

For the appearing cvc, this re-uses stripe's SDK which does this for us. I don't find this particular part too bad.

I agree there should be a link to security, probably target=blank for people to check out, with a note that this is a page of our payment processor, not ourselves. Plus a note we don't store any credit card info ourselves, all is handled by Stripe.

For the thing you're proposing (card), wow, that looks fancy. If you'd want to integrate that, I'm down. However you will have to get access to flowcrypt-web repo (this is our website actually), plus you would probably need to be added as a developer on our Stripe account, plus you would probably need to adjust the sripe integration from just "initialize CC form and let me know when user is done" to "get the numbers from users ourselves through a library" + "here, Stripe, are the customers numbers". There's error handling to worry about that Stripe does automatically today, etc. So this is a bit of a project, I'm not sure you'll be able to get to it this week but if yes, that would be awesome.

As other issues are getting done, we'll see if it makes sense to include this.

**Comment by tomholub** [comment]
related  #1672

**Comment by tomholub** [comment]
will be deprecated by the issue above
