### ISSUE TITLE
Alias name is being ignored

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1911]
Let's say a user has the primary email address `john@gmail.com` and name `John Doe`.
When the email is sent, a recipient sees `John Doe <john@gmail.com>`.

Now, the same user can have an email alias `alice@gmail.com` and name for that alias `Alice Doe`.

By using Gmail, when the user is using the alias to send an email, a recipient will see `Alice Doe <alice@gmail.com>`.

But, if the user is using FlowCrypt and the same alias, a recipient will see `John Doe <alice@gmail.com>`.

The name of the original email address is used, not alias which might lead to confusions on the recipient side, as a recipient will see name unrelated to email address.

**Comment by tomholub** [comment]
Very good discovery

**Comment by tomholub** [comment]
I have not assigned you (yet) because this maybe digs a bit deeper into the internals of the plugin. We'll see if there's time for it later, or if we end up fixing this ourselves.

**Comment by tomholub** [comment]
@michael-volynets please change how alias addresses are saved, from a string array into a dictionary.

You can pull all of the information below from `sendAs`.

You can just forget/start ignoring the `addresses: string[]` field, and instead add `sendAs` field in `acctStorage`.

For example: 
```
sendAs: {
  "joe@gmail.com": { isPrimary: true, name: "Joe Doe", footer: "--\nJoe Doe" },
  "joe@your-local-baker.com": { isPrimary: false, name: "Joe Doe (baker)", footer: "--\nJoe Doe, your personal baker" },
}
```
Then when you need just a list of addresses, you would get it from storage and do `const addresses = Object.keys(storage.sendAs)`.

For now, please ignore the footer. That will be another issue.

**Comment by tomholub** [comment]
And of course, make sure the right name is used based on the alias.

Fallback on the account name on Gmail that we store today in case the alias name is empty.
