### ISSUE TITLE
Add possibility to subscribe with PayPal

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1913]
From my experience around 15-20% of users prefer to pay with PayPal because of different reasons, one of them is the additional layer of security and notifications from PayPal.

It would be great to provide the ability to subscribe with PayPal as well as with credit/debit card.

**Comment by tomholub** [comment]
I totally understand the appeal. Yet I was really hoping I can hide my head in the sand when it comes to implementing PayPal for as long as possible, ideally forever.

Thanks for noticing. I will discuss the reasons privately.

**Comment by tomholub** [comment]
Aaaaand.. closing. 

We are removing basically all restrictions for free users `@gmail` domains. That means there should be less need for them to subscribe, or worry about payment method.

Larger businesses pay over wire anyway.

While there may be value in offering paypal to SME, it's not clear the work involved will pay off. There is already so much work still to do for our Stripe integration (like allowing users to unsubscribe without emailing us).
