### ISSUE TITLE
unexpectedly seeing feedback screen after subscription?

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1914]
As a result of successful payment, this form was shown:

![image](https://user-images.githubusercontent.com/6059356/62866087-b2509100-bd18-11e9-8738-46d7715b622e.png)

I'm not sure why exactly the feedback form was shown to me after payment, I was expecting something like 'We received your payment, thank you' message.

**Comment by tomholub** [comment]
Very weird, that's not where you're supposed to end up after a successful payment, at all.

**Comment by tomholub** [comment]
@michael-volynets please could you take a minute sometime take a look at the code and see why would this happen? If you cannot find anything, I'll try to see if I can also reproduce it too, and if yes, try to investigate it myself.

**Comment by tomholub** [comment]
I will make another issue for the missing initial subscription email.

**Comment by michael-volynets** [comment]
Looking into it

**Comment by michael-volynets** [comment]
I've subscribed to Flowcrypt and I didn't get that form. The notification was sown and the modal dialog was closed.
I also checked the code and it's written correctly. Any code paths don't drive us to that form.

@limonte Had you been subscribed to the `trial` plan before you subscribed to  `Pro` plan?

**Comment by limonte** [comment]
> @limonte Had you been subscribed to the trial plan before you subscribed to Pro plan?

Yes.

**Comment by michael-volynets** [comment]
I just tried this way and I have the same result as before.
I don't really know what could provoke that behavior

**Comment by tomholub** [comment]
Thank you @michael-volynets for looking into it. Reading through the discussion, I have a guess.

@limonte went to the settings through a help icon here: 

![image](https://user-images.githubusercontent.com/6306961/62959917-180c4e00-bde9-11e9-8e90-1a6174ceec34.png)

Then he ended up on url: moz-extension://39553fca-76d4-4791-bf00-b4dfede6fd45/chrome/settings/index.htm?acctEmail=help.cryptup.org%40gmail.com&page=%2Fchrome%2Fsettings%2Fmodules%2Fhelp.htm

Which would show the help page, which he closed. But the url is left unchanged.

Then he subscribed right away, and at the end of the subscription process, there is probably a `window.reload()`. Guess which url it reloaded & guess which page will come up again?

If my guessing is correct, the solution would be to, when user closes a modal, make sure there is no `page=` url param on the host page. I think this can be done by adjusting url history through js, without reloading the page.

The result should be that if `window.reload()` is run anytime after that, it should end up at a screen that does not show the modal.

@limonte please take a look. Thanks!

**Comment by limonte** [comment]
> @limonte went to the settings through a help icon here:

Yes! That's the case! Apologies for not mentioning that in my issue report.

**Comment by tomholub** [comment]
You couldn't have known it's relevant.

Actually, once a few times a week I get a customer feedback that has nothing in it, like:

> no

or 

> thanks

or

> x

and so on. I though my users are completely crazy. Now I understand, they are trying to get rid of the box.
