### ISSUE TITLE
Add ability to cancel the subscription from FlowCrypt settings

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1915]
Users should be able to cancel their subscription in FlowCrypt settings by themselves, without contacting other humans :)

**Comment by tomholub** [comment]
Absolutely

**Comment by tomholub** [comment]
Marking as not actionable yet on the client because it's blocked on backend work (me)

**Comment by tomholub** [comment]
Yes, but on the web, so that we don't have to re-do this on every platform

**Comment by tomholub** [comment]
There will actually be a link to flowcrypt.com/account/ where all this will be possible.

The link will be added as part of #1672 or #1671
