### ISSUE TITLE
Payment Credit Card stores even the subscription payment was unsuccessful 

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1927]
I was trying to subscribe to FlowCrpyt Monthly subscription.

Firstly, I tried to subscribe with a card that doesn't have any funds on it and it threw me an error (`Your card has insufficient funds.`)

Then I tried to subscribe using another card that I have money on, but it tries to charge money from the card I entered the first time (I got a notification on my phone). 
Here is full error `Charge was declined: Request req_oHVwrbyLnKstZW: Your card has insufficient funds.`

I can guess, you saved the credit card I entered the first time in the Stripe Customer Account and then you don't charge money from the card I entered the second time.

![image](https://user-images.githubusercontent.com/49104848/62947889-ffe9fe00-bdeb-11e9-8351-3efcce8efb68.png)

**Comment by tomholub** [comment]
Good find. I had people complain about this, and I didn't believe them.

**Comment by tomholub** [comment]
will be obsoleted by #1672
