### ISSUE TITLE
Minimized state looks cut off

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1929]
The minimized state looks a bit odd because of the vertical alignment of its text:

![image](https://user-images.githubusercontent.com/6059356/62972709-56236500-be1d-11e9-85a0-24b911c4e0df.png)

The height of minimized popup is 36px

![image](https://user-images.githubusercontent.com/6059356/62972579-08a6f800-be1d-11e9-8e3b-5f10b8adf786.png)

When the height of header is 40px, so minimized is cut by 4px

I believe the height of minimized state should be equal to header's height and be 40px

**Comment by tomholub** [comment]
Yup, you sure have an eye for things like this. Finally I don't feel like the weird one anymore! Hahaha
