### ISSUE TITLE
When I press `ESC` button while I'm searching contacts the whole compose window closes

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1934]
When I press the `ESC` button if I'm searching for some contact I expect that the search box will close but not the whole compose window.

I checked how Gmail does it and they close search box firstly and on the second `ESC` press they close the whole window

**Comment by tomholub** [comment]
This is a regression from #1908 by @limonte so we'll let him fix it. Good find!

**Comment by tomholub** [comment]
I will meanwhile temporarily disable the esc handler because I really need to do a release soon (for other reasons).

**Comment by limonte** [comment]
This issue will be handled in scope of https://github.com/FlowCrypt/flowcrypt-browser/issues/1924
