### ISSUE TITLE
Contacts dropdown should be scrollable

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1936]
In case there are many (more than 12) contacts suggestions, the rest will be inaccessible and hidden below the viewport:

The dropdown should be scrollable in case there are more items in it than can fit without scrolling.

**Comment by tomholub** [comment]
I think I hard-cap amount of returned contacts. The way I'm looking at it, if more than 12 results came back, the search query was too generic. What do you think.

**Comment by tomholub** [comment]
I think I cap at 10? Unsure

**Comment by limonte** [comment]
> I think I cap at 10

Agree :+1: 

If we're going with that solution, no actions related to making dropdown scrollable is needed on UI side.

**Comment by limonte** [comment]
Closing this in favor of #1941
