### ISSUE TITLE
There should be 10 contacts suggestions at most in contacts dropdown

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1941]
As per discussion in https://github.com/FlowCrypt/flowcrypt-browser/issues/1936#issuecomment-521217553 in order to prevent overflowing the contacts dropdown, there should be 10 suggestions at most.

**Comment by tomholub** [comment]
I think we are already capping at 10. If not, please take a look

**Comment by limonte** [comment]
For me there was something around 30 suggestions and most of them were inaccessible because they were overflowing the viewport, I'll take a look :+1:

**Comment by tomholub** [comment]
aaah. Maybe we cap it with the iframe size :blush: ...

**Comment by tomholub** [comment]
The easiest place to cap it would probably be when rendering, else the logic may get a bit messy.

**Comment by limonte** [comment]
> aaah. Maybe we cap it with the iframe size ...

Yeah, in that case the keyboard navigation is confusing, becase user can navigate hidden behind the viewport items.
