### ISSUE TITLE
show such toast when clicking PK icon

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1957]
It would be great if we could show a simple toast after certain actions.

![image](https://user-images.githubusercontent.com/6306961/63193952-4ba3de00-c05e-11e9-908f-1c831478fea2.png)

This would be in particular useful in the secure compose window. Eg when I click (or tab-enter) the public key icon, it could say `Attaching your Public Key to the message` or `Removing your Public Key from the message`. Same for signing. This could be the first usecase, but there may be other usecases where this could be super useful.

Toast should disappear within 2 seconds.

**Comment by limonte** [comment]
How about 

```js
const Toast = Swal.mixin({
  toast: true,
  position: 'top-center'
  showConfirmButton: false,
  timer: 2000
})

Toast.fire({
  type: 'success',
  title: 'Signed in successfully'
})
```
Docs: https://sweetalert2.github.io/#mixin

**Comment by tomholub** [comment]
Ha, that thing can really support everything :) yes, just without the animation, ideally bottom-center, and maybe `.7` opacity?

**Comment by tomholub** [comment]
To implement this, I would add it as a method `Ui.toast(msg: string)`.
