### ISSUE TITLE
Question: should we switch to the minimal theme of SweetAlert2?

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1962]
Preview the minimal theme: https://sweetalert2.github.io/

![image](https://user-images.githubusercontent.com/6059356/63212069-28ce0400-c108-11e9-8d3f-c6609253f1dc.png)

I that case buttons won't have round corners and fit better in the FlowCrypt style. Also `animation: false` would be unnecessary: https://github.com/FlowCrypt/flowcrypt-browser/blob/948960e719dc48a81be49eb35964d487edfb9973/extension/js/common/browser.ts#L433

**Comment by tomholub** [comment]
Actually I kind of like the existing style :) I know the rounded corners are a bit of a mismatch, maybe, but I like it for whatever reason.

We could consider making the rounded corners a tad bit sharper (lower radius).

Does the minimal style have a lower footprint? We could consider the minimal + add rounded corners back :laughing: if that's the case.

**Comment by limonte** [comment]
> but I like it for whatever reason.

:smile: 

> We could consider making the rounded corners a tad bit sharper (lower radius).

:+1: 

> Does the minimal style have a lower footprint?

No, it's pretty much the same.

**Comment by limonte** [comment]
I guess the answer to the initial question is "no". Therefore I'm closing the issue.
