### ISSUE TITLE
rework compose button / sign / encrypt / plain with a chevron

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1963]
Instead of current situation with send btn and sign btn:
```
[ send encrypted message ]  [.!]
```
We should have an up or down chevron in the button to choose message type:
```
[ Send encrypted message |⌄]
```

When I click it, it will give me several lines that I can click and add tick to them, or click again and remove tick:
 - Encrypt message
 - Sign message

So I can send encrypted message, signed message, signed+encrypted message, or plain, depending which ones I choose.

That will also allow use cases like this:

> When I write someone I don't usually know beforehand whether they're going to have FlowCrypt set up or not. So when I start drafting an encrypted message and see that they don't, I usually don't want to go with a one-time password (since that expires and is just generally a bit of a hassle for the other person for ordinary day-to-day communication). So I would like an option where you just draft the email, if the other person has set up Flowcrypt the message is sent encrypted, and if they don't, you can send it unencrypted and add a little gentle message at the bottom about what FlowCrypt is and why they might want to use it.

**Comment by tomholub** [comment]
Very roughly (but not so ugly :) ):

![image](https://user-images.githubusercontent.com/6306961/64734723-b5d16680-d4d6-11e9-99a6-9ba7cd113ed7.png)

Possible button texts:
 - Sign and Send
 - Encrypt and Send
 - Encrypt, Sign and Send
 - Send plain (not encrypted)

You can use checkboxes from our docs: https://flowcrypt.com/docs/technical/openpgp-compatibility.html

Please make the pop-up options flexible enough that we could add a third or fourth option later (the other options would not change button text, but may change some other settings).

**Comment by michael-volynets** [comment]
Your variant looks nice, I like it :+1:

**Comment by michael-volynets** [comment]
I think we don't need to show a red cross icon, would be better to show just green tick icon next to the selected item, what do you think?

**Comment by tomholub** [comment]
You can try it with just the green ticks, and we'll see one I test it. Thanks
