### ISSUE TITLE
The "New Secure Message" should respect the Font size browser setting

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#1967]
There's a setting in Chrome:

![image](https://user-images.githubusercontent.com/6059356/63337789-45597e80-c34a-11e9-9118-e9c1e90aebf0.png)

People with visual impairments often use it to improve their UX.

When changing the setting to "Large" or "Very Large" the Gmail's "New Message" window respects that, but the "New Secure Message" doesn't:

![image](https://user-images.githubusercontent.com/6059356/63338138-ecd6b100-c34a-11e9-8f47-eb572a1ae7a7.png)

**Comment by tomholub** [comment]
Very good

**Comment by tomholub** [comment]
We just had a customer request this

> How to increase font size
> FlowCrypt chrome 6.9.3
