### ISSUE TITLE
don't render private keys in pubkey import

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1977]
Screenshot:
![image](https://user-images.githubusercontent.com/49104848/64116521-38517c00-cd9b-11e9-869c-65b179e26b22.png)

**Comment by tomholub** [comment]
We should not even be displaying this at all. In the public key import screen, when we encounter private keys, it should probably show text `Found Private Key ${longid}. To import Private Keys, see Additional Settings -> My Keys.`

You can do that by replacing the block with a "text" block that includes this sentence in `content` (I think).

**Comment by michael-volynets** [comment]
I just researched that we are able to put there everything we want :laughing: (except plain/text :))
I tried to put there PGP message and it decrypted it.

I will add validation for the PGP keys.
