### ISSUE TITLE
Error when importing not usable key as File through Settings.

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#1985]
When I click `Select File` and uploading my not usable key - it shows this invalid modal dialog:
![image](https://user-images.githubusercontent.com/49104848/64195840-1afbdb00-ce8b-11e9-8a76-354fa63dc1ec.png)

but if I paste pub key in the text input and then press show contents then it shows me that the key is not usable:
![image](https://user-images.githubusercontent.com/49104848/64195925-58606880-ce8b-11e9-986d-2ff2f6dd49f5.png)

**Comment by michael-volynets** [comment]
I think would be better to have the same result on both ways of adding pub key

**Comment by tomholub** [comment]
Thanks, I'm putting it as low-pri for now

**Comment by tomholub** [comment]
Closing, it would be nice to make it consistent, but there is just too much other stuff to do
