### ISSUE TITLE
collapsed recipients missing hover title

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#1998]
Hovering works when not compacted

![image](https://user-images.githubusercontent.com/6306961/64336963-beed9f80-cfcd-11e9-8b31-9f6d7c633d81.png)

Stopped working otherwise

![image](https://user-images.githubusercontent.com/6306961/64337041-fc522d00-cfcd-11e9-81c8-4498af03f269.png)

Unfortunately this is the kind of added complexity that comes as a cost of feature bloat

**Comment by michael-volynets** [comment]
Thanks, Adding
