### ISSUE TITLE
Got an error when asking sender to update a key

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2001]
![image](https://user-images.githubusercontent.com/49104848/64348884-a3e75380-cffe-11e9-9dc7-6c909831e58b.png)

**Comment by tomholub** [comment]
Please include a test for this one

**Comment by michael-volynets** [comment]
Ok

**Comment by michael-volynets** [comment]
Issue fixed, Writing a test
