### ISSUE TITLE
broken signed message styles

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2016]
Another side effect of the compacted recipients

![image](https://user-images.githubusercontent.com/6306961/64541986-49a60580-d312-11e9-879b-a79175021f72.png)

The recipients are all supposed to be gray, and the "Sign and Send" button is supposed to be gray.

**Comment by michael-volynets** [comment]
I've already fixed it but in #2015 
![image](https://user-images.githubusercontent.com/49104848/64542214-d5785b80-d32b-11e9-8c47-d577f0e77340.png)

**Comment by tomholub** [comment]
Ok good. That's better.

**Comment by tomholub** [comment]
Correction, the send button is indeed supposed to be green, as it is now - just the recipients needed fixing.
