### ISSUE TITLE
reply to all doesn't work

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2033]
tested on currently live Firefox version

Two people were recipients, yet when I click "reply all", it only replies to the sender.

If you can reproduce this, please add a test first.

If you can't, I'll have to investigate the particular message where I experienced this:

https://mail.google.com/mail/u/1/#inbox/FMfcgxwDrRRZBjjdPctQXXQjnSLwKDWQ

**Comment by michael-volynets** [comment]
Thanks, let me check

**Comment by michael-volynets** [comment]
Yes, I've got the same on the current/production version of firefox/chrome,
I'm going to fix this, thanks!
