### ISSUE TITLE
OrgRule to hide armor comment and version

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2035]
There would be an OrgRule flag called `HIDE_ARMOR_META`. Then you'd use `if(orgRules.shouldHideArmorMeta())` - when true, set `opgp.config.show_comment = false` and `opgp.config.show_version = false` - in the following  in the following situations:
 - [ ] rendering of `compose.htm` page. This should cause any sent message to not have any comment/version in armor
 - [ ] during setup in `setup.htm` - this should cause imported keys to get imported without armor

**Comment by rrrooommmaaa** [comment]
> * during setup in `setup.htm` - this should cause imported keys to get imported without armor

Do I understand correctly that the aim is that `public` and `private` fields of `KeyInfo` should be stored in `KeyStore` without the Version and Comment?
![image](https://user-images.githubusercontent.com/23335944/108105952-577ebf00-709e-11eb-9725-b103995271ba.png)

**Comment by tomholub** [comment]
Yes - if it's easily achievable. I do imagine we are already parsing and re-armoring imported keys?

**Comment by rrrooommmaaa** [comment]
Yes, we are
