### ISSUE TITLE
remove all footer settings, use sendAs 

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2039]
The tricky part will be: please add footer on top of the quoted part.

 - if this is a reply, it will be appended on top of the quote
 - if this is a new message, it will be the quote

In either case, it will be hidden under the `...`

In either case, our existing mechanisms (when storing drafts, loading drafts, etc) should pick it up so that the footer should not double up.

**Comment by tomholub** [comment]
Allow this for everybody, subscribed or not.

**Comment by michael-volynets** [comment]
```
if this is a reply, it will be appended on top of the quote
if this is a new message, it will be the quote
```
To clarify,
Now when we send a message we don't encrypt footer but if we have footer under `...` we will have to encrypt it in the whole message. Am I correct?

**Comment by tomholub** [comment]
Yes, you would encrypt the footer, too. Thanks for asking!
