### ISSUE TITLE
add test for clicking secure message header

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2047]
should minimize / maximize based on state

**Comment by tomholub** [comment]
Explanation https://github.com/FlowCrypt/flowcrypt-browser/issues/1905#issuecomment-536456683

**Comment by limonte** [comment]
Here's the PR which should be covered by this test: #2083

**Comment by tomholub** [comment]
I will re-assign it to @limonte because it could be a simple test to write (on next week-batch), to learn about our test mechanisms.
