### ISSUE TITLE
My FlowCrypt subscription has ended, but I didn't get any notification about that

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2059]
It would be nice to receive email notification about the fact that my subscription has ended. Something like:

> We were unable to process your payment. Please open FlowCrypt settings and click the "RENEW" button to update your payment details.

**Comment by tomholub** [comment]
Yes, definitely

**Comment by tomholub** [comment]
moving issue to backend https://github.com/FlowCrypt/flowcrypt-backend/issues/64
