### ISSUE TITLE
new message (not reply) - auto-focus recipients

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2062]

**Comment by tomholub** [comment]
related to #2057 and especially #2056

**Comment by limonte** [comment]
In this particular case I believe this line is directly related to the issue:

```js
this.S.cached('input_to').val(keyUser.email).blur().focus(); // Need (blur + focus) to run parseRender function
```

**Comment by tomholub** [comment]
Hmm. I have fixed the issue, but if the line above is causing trouble, we should just run the `parseRender` function directly in code?

**Comment by tomholub** [comment]
Good find, this could really be it
