### ISSUE TITLE
replying to signed message should produce signed message

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2076]
1) open a signed message
2) click reply
3) button will wrongly say "Encrypt and Send" (supposed to be Sign and Send)
4) I'm not able to change the button to sign and send. I CAN change it to `Encrypt, Sign and Send`, but not to `Sign and Send`

Please make a test for this first, and make sure the test is failing. Then produce a fix in another commit. That way we know this won't break in the future.

**Comment by michael-volynets** [comment]
I'll actually extend this one
```TS
ava.default.only('compose[global:compatibility] - reply - signed message'
```
instead of adding new

**Comment by tomholub** [comment]
Definitely
