### ISSUE TITLE
cc/bcc drag and drop no longer works

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2077]
tested on chrome. Please add automated tests for drag & drop.

**Comment by tomholub** [comment]
https://github.com/GoogleChrome/puppeteer/issues/1366

**Comment by michael-volynets** [comment]
What exactly doesn't work? 
I just tested it and everything works well

**Comment by tomholub** [comment]
I'll make a video

**Comment by tomholub** [comment]
Need to also add automated tests for this
