### ISSUE TITLE
automated tests for drag/drop

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2080]
_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/2077#issuecomment-538157091_

**Comment by michael-volynets** [comment]
I was trying to write the test but there is an issue when I'm doing drag & drop.
I found this issue on their GitHub at it's opened now

We need to wait when GoogleChrome/puppeteer#2085  is closed,
I'll create a Draft PR containing what I already did and will return to this when the issue is closed

**Comment by tomholub** [comment]
Un-assigning, this issue is blocked on puppeteer support https://github.com/puppeteer/puppeteer/issues/2085

**Comment by tomholub** [comment]
closing, we'd be waiting for puppeteer support forever
