### ISSUE TITLE
Can not "Proceed with send only"

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2090]
### Steps to reproduce:

- During setup, click CANCEL on the Google login last step
- Click "Proceed with send only"

### Expected behavior:

- Proceeding to 

![image](https://user-images.githubusercontent.com/6306961/65756412-935d6100-e104-11e9-8f07-407d344c930b.png)

### Actual behavior

- Google login window is shown again

**Comment by tomholub** [comment]
This is correct. We have to ask for authorization again, this time without the "read" permission.

How could we word it to make it less surprising that another permission window shows up?

**Comment by tomholub** [comment]
Closing for now, we can re-open it if a good idea comes up on how to improve it
