### ISSUE TITLE
mini-tutorial before create key spinner screen

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#210]
#1621

it's a good time to build trust/inform the user while it's loading
 - eg that you can send attachments
 - or that you can send to ppl who don't have cryptup
 - some people didn't notice there are drafts - mention it

**Comment by tomholub** [comment]
@mondo989 I would think of designing some sort of slideshow here, showing a few features why they're getting ready. Like animate something cool to educate them. Creating the first key takes about 30-60sec so we can definitely get creative with something.. now it's just a white screen with a loader

**Comment by mondo989** [comment]
Hey Tom, just got settled in Mexico.
I'll look into this, and start a google doc with the content/(draft) copy. 

Once we have content defined, I can develop some assets o create the on-boarding/slideshow.

**Comment by tomholub** [comment]
kk that sounds good

**Comment by tomholub** [comment]
Note from user
> When initially installing FlowCrypt, there should be a quick guided on-screen tutorial so that people know how to send/receive encrypted emails.
> I didn't see the secure compose and just sent a non-encrypted email.
> I now see it but it would've been great to have a 60-second overview.
> Then at the end of the tutorial there should be a brief snippet about how non-FlowCrypt emails see emails and how safe it really is to send to family and friends

At the very least, during setup, instead of the loading spinner screen, we should highlight that there will be a new secure compose button in Gmail (with a drawing / screen shot).
 - when user is looking at the tutorial screen, the user could click "next" which would take them:
    - either to next tutorial screen (if we add any)
    - or to the loading spinner (from where, if/when setting up is done, it would take them to "setup done") screen

**Comment by tomholub** [comment]
Closing this, it seems like less of a problem recently, after we did #1793
