### ISSUE TITLE
better recognize expired keys or show why unusable

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2109]
continuation of #214 

support emial https://mail.google.com/mail/u/1/#inbox/FMfcgxwDrlSTsTswGmZrwgPLpFCCtZMN or search for:

> If it's expired, I would have thought it could tell me when it's expired.
> 
> I won't have time to investigate it further for now. Feel free to create a new issue, ideally if you could also share the public key there. If you don't want to share our publicly, then you can send it to human@flowcrypt.com with link to my comment here. Thanks!

The key in FlowCrypt says "This OpenPGP key is not usable."

In gnupg and compatibility check, it shows:

https://github.com/FlowCrypt/flowcrypt-browser/issues/214#issuecomment-541106239

Should try to see if the key is usable with gnupg or not.

**Comment by tomholub** [comment]
closing without action

**Comment by karlwilbur** [comment]
I just encountered this when renewing my SSL certificate through Sectigo. Their email to me included the new certificate, as plain "ASCII armor" text, at the end of the body of the email.

In my case, the "This OpenPGP key is not usable" message was in regard to this text version of the SSL certificate which was contained within the email itself. Apparently FlowCrypt sees the included certificate string (`-----BEGIN CERTIFICATE----- ... -----END CERTIFICATE-----`) and misidentifies it as an OpenPGP key and thus warns that it is not usable.

For obvious reasons, I am not going to include the "not usable" "OpenPGP key".

@tomholub I don't know if this information is useful at all, but I want to provide it just in case.

**Comment by tomholub** [comment]
Thank you for reporting - this is helpful.
