### ISSUE TITLE
Problems with FlowCrypt loading in Gmail on FF 70 beta

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2110]
> I'm running Firefox 70.0b13 (64-bit) on MacOs and am rather frequently running into an annoying bug. I have the impression the flowcrypt plugin at some moments suddenly "quits" or crashes, making the flowcrypt button in the left menu bar in Gmail disappear. I need to go to the plugin itself with reduced functionality to initialize an encrypted message. Only then the button reappears. I hope this bug is being dealt with.

Personally I'm using FF 69 and don't see the problems there, but it's possible that it started misbehaving on version 70 and will stay that way once the new FF version is released publicly. Something similar has happened before.

The user reports that restarting the browser fixes it (button appears) but later it will start not appearing again.

This may be a bit hard to debug, but still wroth the try.

**Comment by tomholub** [comment]
user conversation support https://mail.google.com/mail/u/1/#inbox/FMfcgxwDrlSSnFrQhfDBckjrTZDJHzTr

**Comment by tomholub** [comment]
I assigned both of you, feel free to unassign the other person of you start looking into it.

**Comment by michael-volynets** [comment]
I will take a look

**Comment by tomholub** [comment]
I'm using FF 70 now and didn't experience any issues yet.

**Comment by tomholub** [comment]
I just encountered this, when:
1) I already had one tab open
2) I clicked a link to a Gmail thread that opened in second tat
3) FlowCrypt on second tab didn't load

I instinctively hit F5 and then it loaded on second one too.

It is a real issue, but it may not be easy to track down.

**Comment by tomholub** [comment]
I may have somewhat improved this, and will close it for now. We'll see.

Moving away from reliance on background script as required in #2158 may also help this.
