### ISSUE TITLE
show advanced options by default during setup

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2114]
**So that this:**

![image](https://user-images.githubusercontent.com/6306961/66957065-0f3c3080-f055-11e9-8295-768ccb514ebe.png)

**Will look more like this:**

![image](https://user-images.githubusercontent.com/6306961/66957146-2f6bef80-f055-11e9-9893-954689fc82e8.png)

**Comment by tomholub** [comment]
That way mindful users know what to expect during setup.

**Comment by limonte** [comment]
@tomholub would you also want me to replace those custom checkboxes which are keyboard-inaccessible and a bit ugly (IMO) with native checkboxes?

- accessibility for free
- users are getting their native-looking checkboxes they are familiar to
- less code

Native checkboxes are pretty much everywhere these two files:

![image](https://user-images.githubusercontent.com/6059356/66958613-2be66180-f071-11e9-8e69-7b9b144e1bb6.png)

**Comment by tomholub** [comment]
They look particularly ugly probably because I increased browser font size. Not sure, they used to look better.

The reason we use custom ones is because I was not able to make a default checkbox bigger without looking.. also ugly. Can I have big standard checkboxes? :)

**Comment by limonte** [comment]
> Can I have big standard checkboxes? :)

Yes, but as you said they will become lil ugly as well :) 

Why do you want bigger checkboxes in the first place? Their labels seem to have a very close to the default `font-size`, IMO regular native checkboxes will fit just fine there with all their cross-platform cross-browser benefits I listed in the previous comment.
