### ISSUE TITLE
Forward should show empty recipients + recipients in focus

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2118]
Another issue is that when I click `Forward`, the recipients field should be empty, and in focus. I'll make another issue for this.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/2116#issuecomment-543297500_

There is code somewhere that will make recipients in focus if it's a new message, so you could add an OR there to handle if this is a forwarded message.

This must be a relatively recent regression. Please add a test.

**Comment by michael-volynets** [comment]
`There is code somewhere that will make recipients in focus if it's a new message, so you could add an OR there to handle if this is a forwarded message.` I couldn't find this code so I added focus in `renderReplyMsgComposeTable` function
