### ISSUE TITLE
merge `reply_pubkey_mismatch.htm` with `compose.htm`

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2128]
I think that we need to totally remove `reply_pubkey_mismatch.htm` and use `compose.htm` instead of that. 
The reason is when I made some new features for `compose.htm` I also have to check if everything works well `reply_pubkey_mismatch.htm`.
Like in issue #2119.

**Comment by tomholub** [comment]
I'm fine with this, but will only merge the PR if it's obvious that it's an improvement to code clarity - as long as `composer.js` or `compose.htm` doesn't get too complicated as a result.

**Comment by tomholub** [comment]
I'm refactoring `compose.ts` in #2284 and will cover this too
