### ISSUE TITLE
improve signed message rendering consistency

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2147]
> Last question -- when receiving *signed* emails it shows "Person's Name - Matching Signature" in a stylized font in the upper-right.  We received a request from the COO here asking why for some people it shows their first & last name, where for other it shows just their email address instead, and whether they can edit / change how theirs is displayed there.  Again I can provide screenshots it's not immediately obvious.

-------------

Notes
1. rework to show consistent results based on primary email of the key that signed
2. if this is different from the email that the contact is saved as, highlight the difference (show in orange)
3. if this is different from the email sender, highlight the difference (show in orange)

**Comment by tomholub** [comment]
What to do: pls review code that decides which name gets displayed when we render a message signature. It's this code:
```ts
const signerEmail = signature.contact ? signature.contact.name || this.view.senderEmail : this.view.senderEmail;
$('#pgp_signature > .cursive > span').text(signerEmail || 'Unknown Signer');
```

Please see how is this code used in larger context (signature.contact is a local keystore public key of whoever signed the message, along with metadata like name). See how it behaves, compare it to what other software does, like Enigmail, and see if the behavior should update/improve to match your user expectations better.

**Comment by rrrooommmaaa** [comment]
@tomholub Possible sources of names are: 1) Address book (aka sent messages) -- this is actually what is saved to `contact.name`
2) User ID packet of the OpenPGP key -- looks like it (the name part) is ignored by Flowcrypt.
3) The `"From:"` header. Well, it is unsafe to use that as anyone can put "Mr President" there. And it is discarded right away in the `pgp_block` constructor: `    this.senderEmail = Str.parseEmail(senderEmail).email || '';`

As I see it, the Flowcrypt's concept is to show signer's names as they are in the "address book", so for example, if we have User ID = `Jack Jones <a@b.c>` and  `My Old Buddy <a@b.c>` in sent messages, the signed e-mail would look like `My Old Buddy -- Matching Signature`. If we have <a@b.c> in sent messages, The signed e-mail would appear as `a@b.c -- Matching Signature`. Well, we can display the name from User ID packet in different color in case the name is missing in the contact record.

I can also try and run all these setups on Enigmail to see how it handles them.

**Comment by rrrooommmaaa** [comment]
We can also check for new sent messages for existing contacts without `name`.

**Comment by tomholub** [comment]
Thanks! The current setup seems messy. Feel free to completely ignore what FlowCrypt did until now, and instead use some simpler, more sensible, and safer way to render signatures.

**Comment by rrrooommmaaa** [comment]
I tested Thunderbird with Enigmail plugin.
Enigmail displays UID from the key, Thinderbird displays name from address book in the "From" field.
Supplied name from "From" header is ignored, which is the right thing.
![image](https://user-images.githubusercontent.com/23335944/102212928-02c89780-3ee7-11eb-877e-98e3e4329828.png)
![image](https://user-images.githubusercontent.com/23335944/102213032-2ab7fb00-3ee7-11eb-87a1-7b209a95b6d7.png)
So we have 2 possible names to display: 1) from the address book -- currently implemented and 
2) from key's UID.
We can display both if they differ, and possible different color for Address books's.

**Comment by tomholub** [comment]
I don't entirely trust the names in the address book, the way we populate
it seems less direct compared to key IUD itself. Let's only show maybe
email from key uid?

**Comment by rrrooommmaaa** [comment]
Ok, so stripping off names entirely

**Comment by tomholub** [comment]
Yup. I think that will be best
