### ISSUE TITLE
plain response should not render as secure

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2149]
1) click "reply"
2) write message
3) select "Send plain"
4) send

Sent message will render in green box, even though it's sent plain.It should show without any secure frame.

**Comment by limonte** [comment]
@tomholub I can't reproduce the issue, in both browsers it works as expected for me:

![Peek 2020-07-01 14-22](https://user-images.githubusercontent.com/6059356/86238634-83e4da00-bba6-11ea-8156-2e9408ae082a.gif)

**Comment by tomholub** [comment]
While we don't communicate it well, the gray color is meant to mean "signed", so ideally when sending an unencrypted, unsigned message, there would not even be the gray frame.
