### ISSUE TITLE
re-working drafts without local storage + drafts don't work from other device

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2151]
#920

**Comment by michael-volynets** [comment]
There are some issues that we are going to face while working on this issue:

1) As @tomholub said that the storing draftIds in local storage wouldn't be so good because users can use FlowCrypt using multiple devices. So I started researching how we can solve the loading drafts issue.
First, I looked at Google API to get drafts (https://developers.google.com/gmail/api/v1/reference/users/drafts/list) but this API doesn't fit us because this API only gives us a draft by ID (which we don't know) or list of all drafts.
Then I started investigating Gmail Threads API (https://developers.google.com/gmail/api/v1/reference/users/threads/get) and I think we could work with this API. When a user opens some thread we asynchronously pull the thread and check if there is a draft. If yes then render it.
Working on this may affect storing drafts logic so we may need to change it as well.

2) I want to suggest when we render drafts do not render the reply box immediately because there may be more than 3 drafts in the thread (it's rare but it may be) and if we render all these drafts with reply box it may overload clients devices. So maybe we need to show some button under a message if the message contains a draft, and when the user clicks on the button we will render a reply box.

**Comment by tomholub** [comment]
We could show a button for all except the last draft, and render the last draft automatically. That would be a decent compromise.

**Comment by tomholub** [comment]
User has just bumped into this

> opening drafts doesn't seem to work.  is this a known issue?

> Not a known issue. Would you be able to share a screenshot or steps to reproduce it? Thank you!

> The issue seems to arise when a draft is started on one computer and then going to another PC and trying to open the draft.

This is indeed a problem today, because we store information about a draft (especially reply) locally on the device where it was created, so if you try to access it from another device, it doesn't work.

**Comment by tomholub** [comment]
Please do some cross-device testing - when you create a draft on one browser, can you open it from another browser?
 - [ ] new message draft
 - [ ] reply message draft - this may be the problematic one

**Comment by limonte** [comment]
> new message draft

Works as expected.

> reply message draft - this may be the problematic one

Doesn't work

**Comment by limonte** [comment]
This is weird. I just tested "reply message draft - this may be the problematic one" from chrome to firefox and vice versa and everything works well. Not sure what happened in my previous comment. Apologies for the confusion!

I guess, this issue can be closed.

**Comment by tomholub** [comment]
If that was true, we would not need any of the metadata we are saving to storage with each reply draft. I think we were storing thread id or draft id or both. Try a PR that removes that, see if anything breaks. Thanks!

**Comment by limonte** [comment]
> If that was true, we would not need any of the metadata we are saving to local storage with each reply draft. I think we were storing thread id or draft id or both. Try a PR that removes that, see if anything breaks. Thanks!

All seems to work fine after removing the code which saves drafts metadata to local storage: #3279

**Comment by limonte** [comment]
> This is weird. I just tested "reply message draft - this may be the problematic one" from chrome to firefox and vice versa and everything works well. Not sure what happened in my previous comment. Apologies for the confusion!
> 
> I guess, this issue can be closed.

This comment is incorrect, sorry. I was testing new message drafts yesterday 🤦‍♂️🤦‍♂️🤦‍♂️
