### ISSUE TITLE
Private key & passphrase stored in plain text in log files

### ISSUE THREAD

**Issue by dylanpyle** [FlowCrypt/flowcrypt-browser#2152]
Hey all-

I happened to discover today that my private key passphrase (and the key itself) is logged in plain text in a log file related to FlowCrypt:

The file in question is located at:
```
/Users/dylan/Library/Application Support/Google/Chrome/Profile 6/Local Extension Settings/bnjglocicdkmhmoohhfkfkbbkejdhdgc/000003.log
```

And around 0x000019c0 contains the info in the below screenshot. The redacted area is my passphrase in plain text. My private PGP key is located earlier in this same file.

This seems like a serious issue - I'm not clear if this is related to the vulnerability disclosed on Sept 5.

<img width="1212" alt="privatekey" src="https://user-images.githubusercontent.com/806257/67868839-e8750400-fb02-11e9-9b45-55ae89faf8d8.png">

**Comment by tomholub** [comment]
This is browser local storage file. The browser needs to store your private key somewhere, and it will store it on your hard drive.

The private key is encrypted with your pass phrase. You can choose to not have the browser remember the pass phrase (which will soon become the default - issue #1807) see https://flowcrypt.com/docs/guide/common-tasks/require-pass-phrase.html for details. That way the only thing stored will be your encrypted private key.

You can further (strongly recommended) allow full disk encryption on your device. See https://flowcrypt.com/docs/guide/common-tasks/improve-security.html#full-disk-encryption

I will close this for now (the most relevant is #1807 which will be addressed soon) but feel free to ask followup questions.
