### ISSUE TITLE
prep work for manifest V3 - move pgp functionality from background script to content script

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2158]
First should do some prep work - move what we can from background script to content script

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/1509#issuecomment-548742536_

**Comment by tomholub** [comment]
For example:
 - decrypting, and all OpenPGP.js operations

Following cannot be done yet:
 - network requests (have problems from content scripts)
 - storage related requests

**Comment by tomholub** [comment]
Background: 
https://developer.chrome.com/extensions/migrating_to_manifest_v3

There will be no more background pages. Our background page mostly responds to BrowserMsgs from content script frames.

To the extent we can, we'll try to start moving functionality from background page to content scripts. This means that content scripts should load `OpengPGP.js` library (if they don't already) and as a part of this issue, individual iframes (such as pgp_block) will be calling their parent frame (which is Gmail content script) and not the background page. Specifically these calls:

![image](https://user-images.githubusercontent.com/6306961/72736060-ee740180-3b94-11ea-9de0-1b8aef5be51d.png)

Will now be listeners in main email provider content script instead.

**Comment by limonte** [comment]
TODO:

- [ ] `pgpMsgType`
- [ ] `pgpMsgDiagnosePubkeys` (#2507)
- [ ] `pgpHashChallengeAnswer`
- [ ] `pgpMsgDecrypt`
- [ ] `pgpMsgVerifyDetached`
- [ ] `pgpKeyDetails`

**Comment by limonte** [comment]
@tomholub I guess this issue should be reopened since we didn't achieve the described in https://github.com/FlowCrypt/flowcrypt-browser/issues/2158#issuecomment-576310150
