### ISSUE TITLE
ecc keys by default

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2159]
This would mostly relieve the need for performance improvements like #1976 

Should come with an obvious way to choose another type of key

Options (first is default)
 - `curve25512` (shown to user as ECC `Curve25519`)
 - `rsa2048` (RSA 2048bit)
 - `rsa4096` (RSA 4096bit)

Then this string can be put into `Pgp.key.generate`

**Comment by tomholub** [comment]
This could be done after #2114 - the key type choice will simply become an option/select under the three checkboxes.

**Comment by limonte** [comment]
> curve25512 (shown to user as ECC Curve25519)

@tomholub was `curve25512` a typo? I'd assume it should be `curve25519`.

**Comment by tomholub** [comment]
> > curve25512 (shown to user as ECC Curve25519)
> 
> @tomholub was `curve25512` a typo? I'd assume it should be `curve25519`.

You're right, it's `curve25519`, to be shown as `ECC Curve25519`
