### ISSUE TITLE
Sometimes finish session btn isn't displayed in Gmail webmail

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2162]
I researched a little and found the issue.
The selector we are using to add button changes from time to time:
```TS
    composeBtnSel: {
      'gmail': 'div.aic',
      'outlook': 'div._fce_b',
      'settings': '#does_not_have',
    },
    finishSesionBtnSel: {
      gmail: 'div.gb_ue', // <-- this one
      outlook: '#does_not_have',
      settings: '#settings > div.header'
    }
```

The solution is to find out more general selector that won't be changed.

**Comment by tomholub** [comment]
Thanks for noticing this!

**Comment by tomholub** [comment]
Is it possible that sometimes it tries to find the selector too early while the page is loading? (just something to check)

**Comment by michael-volynets** [comment]
I don't think so, because I tried to find the selector manually using the developer console when the page was fully loaded, I couldn't find anything.

**Comment by tomholub** [comment]
Got it. Yes, this has happened to me before (with another selector).

**Comment by tomholub** [comment]
You can also add `Catch.report("Selector for locking session not found on Gmail webpage: .someSel")`. If this happens a lot, we'll get to know.

Don't do it for all selectors (yet?), just this one.

**Comment by tomholub** [comment]
closing, if issue re-surfaces, let's open another issue

**Comment by tomholub** [comment]
Still missing sometimes, we should look for both selectors?

![image](https://user-images.githubusercontent.com/6306961/69286510-5f298c80-0beb-11ea-989c-07458f97e29e.png)
