### ISSUE TITLE
notify about own mismatched pubkeys when composing or decrypt error

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2176]
If I'm composing a message, check on available public key servers that the email I'm sending from has correct record. If at least at one point a correct record is returned back, flag this in local storage and stop checking.

If no correct record was ever found for that email address, keep checking every time compose is open.

After each such check, if there is still mismatch, show a notification banner on the bottom of secure compose, under the row that has the send button, that public records are missing or mismatched, and how to correct them (link user to Attester screen in settings).

Remember to check proper iframe sizing on Firefox when you add the banner. When there is mismatch, banner should be visible both for new messages and replies.

-------------------------

Do the same check, except ignore previous successes, when there is a key_mismatch decrypt error. Tell the user that the error is likely because of the mismatch, and offer to open Attester screen to correct it.

**Comment by michael-volynets** [comment]
What do you think about adding an icon next to the send button and the text will be displayed in the popover when the user hovers it? it will look like this:
![image](https://user-images.githubusercontent.com/49104848/69779638-57e91c80-11b1-11ea-83fb-e0c8c5ef5b4f.png)
Or
![image](https://user-images.githubusercontent.com/49104848/69779490-dee9c500-11b0-11ea-8895-5af5fb697fb9.png)

I think it will be better than the banner.

**Comment by michael-volynets** [comment]
We can even color the icon in orange and show it before paperclip icon so users will pay attention to it
![image](https://user-images.githubusercontent.com/49104848/69779916-53713380-11b2-11ea-9ad7-a6957fe3fb62.png)

**Comment by tomholub** [comment]
I know you are trying to avoid having to add more complicated logic for the UI (a banner with some height will necessarily affect rendering logic, but an icon would not. Simplicity is a good thing.

But an icon would make it look like an action button, but it's actually a warning.

And I want it more prominent, so if it was placed in the lower row, it would be something like this:

![image](https://user-images.githubusercontent.com/6306961/69799700-b7ecbc80-11cb-11ea-8ed1-9227e0075851.png)

Other option, if you really want to avoid adding another table row, is to have it float top-right of the input box:

![image](https://user-images.githubusercontent.com/6306961/69799984-3cd7d600-11cc-11ea-923e-88cdc4ddc0d6.png)

Or in the header:

![image](https://user-images.githubusercontent.com/6306961/69800194-a35cf400-11cc-11ea-9687-a1d3906b9d68.png)

Original proposal was something like:

![image](https://user-images.githubusercontent.com/6306961/69800411-18c8c480-11cd-11ea-987f-9b137fb1a9a1.png)

Maybe @limonte has some idea.

**Comment by michael-volynets** [comment]
Your second option may conflict with the `add intro` button and with the text that user types.
The third one, I think won't be so good because of a green background. I tried it before and it looked ugly. But I only added the icon.

But I like your 1st and 4th options.
1st one is easier to implement I think.

**Comment by tomholub** [comment]
I was trying to work on a similar issue and wrote this snippet, but didn't end up needing it:

```js
  private async getAttesterKeyDetails(): Promise<Dict<KeyDetails | undefined>> {
    const storage = await Store.getAcct(this.urlParams.acctEmail, ['keys_attester', 'addresses']);
    const keysAttester = storage.keys_attester || {};
    const locallyStoredAttesterEmails = Object.keys(keysAttester);
    const attesterLookupPromises: Dict<Promise<PubkeySearchResult>> = {};
    for (const address of storage.addresses || []) {
      if (!locallyStoredAttesterEmails.includes(address)) {
        attesterLookupPromises[address] = Keyserver.lookupEmail(this.urlParams.acctEmail, address);
      }
    }
    if (!Object.keys(attesterLookupPromises).length) {
      return keysAttester; // already have all records in storage
    }
    for (const lookupEmail of Object.keys(attesterLookupPromises)) {
      try {
        const res = await attesterLookupPromises[lookupEmail];
        if (res.pubkey) {
          keysAttester[lookupEmail] = await Pgp.key.details(await Pgp.key.read(res.pubkey));
        }
      } catch (e) {
        if (Api.err.isSignificant(e)) {
          Catch.reportErr(e);
        }
      }
    }
    await Store.setAcct(this.urlParams.acctEmail, { keys_attester: keysAttester });
    return keysAttester;
  }
```
It would keep a cache of attester keys locally in storage. 

Let's wait with this issue until #2256 is done, I'll have some thoughts afterwards.

**Comment by tomholub** [comment]
I'll take this on, there are some difficult nuances that I'm not even sure about until I start implementing it.

**Comment by tomholub** [comment]
closing as not worth at the moment
