### ISSUE TITLE
`Show Advanced` icon and text aren't aligned properly

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2179]
![image](https://user-images.githubusercontent.com/49104848/68790745-8d89f380-0650-11ea-8658-b7112515d0c5.png)

It could have happened somewhere else.

**Comment by tomholub** [comment]
Thanks! I noticed it too. We'll be removing it soon, so I'll ignore it for now, until removed.

**Comment by tomholub** [comment]
here - #2114
