### ISSUE TITLE
Signature is adding itself to message each time draft is being closed and opened again

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2189]
### Steps to reproduce:

1. Click the "Secure Compose" button
2. Select a recipient
3. Wait for the "Saved" notification in the footer
4. Close the "New Secure Message" window
5. Go to Drafts, open the most recent draft message

### Actual result

The signature is doubled, the message contains it and the footer (three dots) contains it.

### Expected result

The message is empty, the signature is hidden in the footer (three dots)

---

Latest Firefox on Linux

**Comment by tomholub** [comment]
I believe the intention was that when loading message from a draft, footer would not be appended again. It's assumed it's already present in the draft.
