### ISSUE TITLE
#send_btn should be disabled when in the "Encrypting/Signing" state 

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2199]
Currently, the `#send_btn` is clickable when in the "Encrypting" state:

![image](https://user-images.githubusercontent.com/6059356/69424847-4b3c7280-0d32-11ea-88ff-2bc720a485f4.png)

I'd expect it to be disabled when in the "Encrypting" state. Also, three dots as the indicator of a pending process would be nice: "Encrypting...", "Signing...":

![image](https://user-images.githubusercontent.com/6059356/69429108-7d9e9d80-0d3b-11ea-8817-d670469e3270.png)

**Comment by tomholub** [comment]
I think this is a regression. I was observing it too. But it has been this way for a while.
