### ISSUE TITLE
disable declaration-block-trailing-semicolon in TypeScript

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2200]
![image](https://user-images.githubusercontent.com/6306961/69431047-d287e700-0d2e-11ea-8414-1db39bed2855.png)

**Comment by limonte** [comment]
Apologies, I forgot that `stylelint` will check all files by default. I don't think we need it in TS/JS, so I'll use the same config as in https://github.com/sweetalert2/stylelint-config/blob/master/index.js#L11-L14
