### ISSUE TITLE
The "Secure Reply" button doesn't seem to work

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2212]
When I click this one nothing happens, the console log is empty as well:

![image](https://user-images.githubusercontent.com/6059356/69532778-36085380-0f7f-11ea-88d2-38333c650dbd.png)

These are working as expected:

![image](https://user-images.githubusercontent.com/6059356/69532806-47e9f680-0f7f-11ea-881e-2dccfc8a9869.png)

Tested in both Firefox and Chrome on Linux

**Comment by tomholub** [comment]
We'll need a test for that, and this one will have to be of the Live Gmail type, unfortunately.

**Comment by tomholub** [comment]
There used to be, maybe still is, url param called "skipReplyPrompt", that is supposed to do what it says.

That button would I think change the iframe url of the reply box to one with `skipReplyPrompt=true`, which would re-render the iframe frame without the prompt.

**Comment by tomholub** [comment]
Note: if the problem is actually in the code of the iframe (more likely), then this could be tested using a mock:
1) load a standalone frame with url that includes `skipReplyPrompt`
2) test that you can send a message

**Comment by tomholub** [comment]
Currently works when replying to a plain message (secure reply box not yet rendered), but not when replying to secure message.
