### ISSUE TITLE
The saved draft isn't visible in the conversations list

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2223]
Steps to reproduce:

1. Open any encrypted conversation in the Inbox
2. Click Encrypted Reply
3. Write down any text and wait for the "Saved" notification in the footer
4. Go back to Inbox, there should be the saved draft:

![image](https://user-images.githubusercontent.com/6059356/69721563-c4b2d700-111d-11ea-957e-357f78d167ef.png)

### Expected result

![image](https://user-images.githubusercontent.com/6059356/69724566-d481e980-1124-11ea-9fd6-bdcd10ae87ee.png)

### Actual result

![image](https://user-images.githubusercontent.com/6059356/69726400-29276380-1129-11ea-93fc-2c84d36a38ac.png)

**Comment by tomholub** [comment]
This will probably be fixed once we resolve #2151. I'm marking it as "discussion" to keep it open until later, and make sure this indeed fixed after the other one lands.

**Comment by tomholub** [comment]
I've assigned you the reference issue - I'm also assigning this one - since they are related. Thanks!
