### ISSUE TITLE
remove account details view

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2230]
```
// todo - this this page should be removed, link from settings should point to flowcrypt.com/account once available

View.run(class AccountView extends View {
```

**Comment by tomholub** [comment]
Check to see if there is any functionality available on this AccountView that is missing in https://github.com/FlowCrypt/flowcrypt-account . If there is, please create issues there to address it. If nothing missing, can remove this page and link to https://flowcrypt.com/account

**Comment by yantakus** [comment]
@tomholub, I need an account with an active subscription in order to test this one.

**Comment by tomholub** [comment]
Either here or on the chat pls share any test email you'd like to use, I'll give it the subscription.

I think maybe it will be enough to subscribe to trial for now? It doesn't ask for a credit card, it's just a button to press.

**Comment by tomholub** [comment]
Actually, I think going forward it should link to the /account page regardless if signed up or not.
