### ISSUE TITLE
use a view-framework for simpler settings modules

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2231]
in `settings/modules/`:
 - add_key.ts
 - auth_denied.ts
 - compatibility.ts
 - contact_page.ts
 - debug_api.ts
 - my_key_update.ts
 - my_key_user_ids.ts
 - my_key.ts
 - security.ts
 - test_passphrase.ts

I've skipped the more complex ones which I'll have a look at, and maybe refactor further.

**Comment by michael-volynets** [comment]
I will create a PR with one refactored file.
If I've done everything correctly I will continue working on others. Okay?
Or I can even split every file to separate PR so it will be easier for review.
