### ISSUE TITLE
debug / fix searching recipients by name

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2234]
Assume I'm searching for a contact `Firstname Lastname <myemail@email.com>`.

I should be able to find the contact by searching any of the following strings:
 - `firstname`
 - `lastname`
 - `firstname lastname`
 - `myemail`

Searching by name should work properly, with any of the above search strings, when using any of the following sources of contacts:
 - sent emails
 - google contacts
 - local app Contacts

There is currently an issue where it doesn't search properly by names that are not contained in the email address. This has to be tested fixed for **all three contact search methods**, and we should create automated tests for these too.

**Comment by michael-volynets** [comment]
I have investigated how we are saving contacts to search and I have a few questions for you:

> There is currently an issue where it doesn't search properly by names that are not contained in the email address.

I don't exactly understand this part. Could you please clarify it a little bit more? It would be great if you describe the steps to reproduce the issue.

> This has to be tested fixed for all three contact search methods, and we should create automated tests for these too.
I assume that `local app Contacts` can be tested using mock data but for `sent emails` and `google contacts` we should only use `live Gmail`, am I right?

Thanks!

**Comment by tomholub** [comment]
Everything should be tested using mocks.

> >  There is currently an issue where it doesn't search properly by names that are not contained in the email address.
> 
>I don't exactly understand this part. Could you please clarify it a little bit more? It would be great if you describe the steps to reproduce the issue.

Try to find user `Firstname Lastname <myemail@email.com>` by searching `firstname` or `lastname`. It won't find the user.

**Comment by michael-volynets** [comment]
@tomholub, I think it's already been fixed so I have to write only tests,
As you see in the Gif I've attached, I'm searching by the last name and the email address doesn't contain any symbols from my last name, the results are correct.
![result2](https://user-images.githubusercontent.com/49104848/71670683-5a72ff00-2d79-11ea-94bb-5d147debebb5.gif)

**Comment by tomholub** [comment]
I'll take a look. It does not always work.

**Comment by tomholub** [comment]
There is indeed a problem. To reproduce:
1) delete internal contacts
2) don't connect to google contacts
3) try to search for `aaa` to find a contact `Aaa <bbb@ccc.de>`
4) Gmail api returns the contact but it will somehow not surface to user
