### ISSUE TITLE
use a view-framework for simpler frame elements 

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2239]
in `extension/chrome/elements`:
 - `add_pubkey.ts`
 - `backup.ts`
 - `passphrase.ts`
 - `pgp_pubkey.ts`
 - `subscribe.ts`

I've skipped the more complex ones which I'll have a look at, and maybe refactor further.

**Comment by michael-volynets** [comment]
I will be working on it the same way as I was working on #2231 (one file - one PR)

**Comment by michael-volynets** [comment]
Note: `Backup` file has been already refactored

**Comment by michael-volynets** [comment]
No, `Backup` element isn't updated, I was looking at `backup` module file
