### ISSUE TITLE
enable eslint - for now only rule require-await 

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2240]
In ESLint there's the https://eslint.org/docs/rules/require-await rule which can be helpful for such cases.

Offtopic: did you think about using ESLint for `flowcrypt-browser`? `tslint` has been deprecated in favor of ESLint + `@typescript-eslint`: https://medium.com/palantir/tslint-in-2019-1a144c2317a9

ESLint is truly amazing tool for keeping TS/JS in good and consistent shape and preventing silly human mistakes like this one with missing `await`.

Take a look on the config we're using for SweetAlert2: https://github.com/sweetalert2/eslint-config/blob/master/index.js

_Originally posted by @limonte in https://github.com/FlowCrypt/flowcrypt-browser/pull/2232_

**Comment by tomholub** [comment]
For now let's go with a single rule `require-await`, and then we can start working our way away from tslint and towards eslint if it all goes well.

**Comment by limonte** [comment]
I never used this plugin but seems like a good one to add https://www.npmjs.com/package/eslint-plugin-no-only-tests

WDYT?
