### ISSUE TITLE
Sometimes the encrypted message rendered twice

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2247]
This happened to me three times already in both browsers, but I still can't figure out steps to reproduce: 

![image](https://user-images.githubusercontent.com/6059356/70176863-e2fe7100-16e1-11ea-80e0-4c9cd5c30afa.png)

What I'm doing is just clicking with the mouse on the conversation in the conversation list and that's it. But it's not happening each time.

**Comment by limonte** [comment]
In case this info is somehow helpful, here's the original:

![image](https://user-images.githubusercontent.com/6059356/70177098-66b85d80-16e2-11ea-9fac-32c3e1554b57.png)

**Comment by tomholub** [comment]
Yes. Happens to attachments as well (eg 5 encrypted attachments become 10 encrypted attachments).

We replace contents of the browser once a second. I could imagine, if some steps takes longer than a second, and stars align just right, the next replace-run will not realize this message is already getting processed, and replace it as well. When both finish, original message is gone, but there are now two replacements.

There's a class that we add to the message that signifies that a message is being processed/replaced. Maybe we add the class too late in the replace process? Maybe Gmail will sometimes remove that class?

This is noticeable sometimes in CI: #187

**Comment by tomholub** [comment]
related / same issue: #1870

**Comment by tomholub** [comment]
I'll close this one and assign the other one to you. I have not given this a thorough look myself yet. Michael has but couldn't find anything.
