### ISSUE TITLE
Cannot read property 'replaceChild' of null"

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2271]
### Step to reproduce:

1. Open any encrypted message from Inbox
2. Click the remove Inbox label button:
![image](https://user-images.githubusercontent.com/6059356/70324512-57e3bf00-1838-11ea-9be0-850f290fac2c.png)
After clicking the remove label button, this error is in console: `Error in protected function: Cannot read property 'replaceChild' of null"`
3. Click the "Undo" button in the bottom toast notification:
![image](https://user-images.githubusercontent.com/6059356/70324528-65994480-1838-11ea-99e4-36f5ce0552dd.png)

### Expected behavior

Nothing happens

### Actual behavior

The encrypted message is being re-rendered:

![1](https://user-images.githubusercontent.com/6059356/70324645-b7da6580-1838-11ea-9173-2f11ec6a652b.gif)

**Comment by tomholub** [comment]
This may have something to do with how Gmail updates their Dom, I'm not sure if this is something we can change.

**Comment by tomholub** [comment]
I will close it for now but if there is any indication that this is reasonably fixable by us, we should consider re-opening.

**Comment by tomholub** [comment]
>  After clicking the remove label button, this error is in console: Error in protected function: Cannot read property 'replaceChild' of null"

We should handle the error though, reopening.

**Comment by limonte** [comment]
> After clicking the remove label button, this error is in console: Error in protected function: Cannot read property 'replaceChild' of null"

The same issue is happening on clicking "Archive" or "Move to Inbox" buttons

**Comment by limonte** [comment]
The exception is happening in the external Gmail's code, but it's happening only with FlowCrypt enabled.

**Comment by tomholub** [comment]
We must be doing something that is affecting Gmail code adversely. Try to see with trial and error if you can figure out what it is (you could try to disable replacing certain elements, and see if it helps).

Remember, after you change content scripts, you'll need to manually refresh plugin in `chrome://extensions` (and ideally reload the gmail page, too) to see the results.

**Comment by limonte** [comment]
this code is guilty of throwing an exception:

```js
e.parentNode.replaceChild(f,e);
```

It's easy to find it in Dev Tools by pressing Ctrl+Shift+F.

Now, the `parentNode` of `e` is `null` and `e` is `<div class="a3s aXjCH adM"></div>` which looks like something related to FlowCrypt: https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/content_scripts/webmail/gmail-element-replacer.ts#L50

**Comment by limonte** [comment]
Yup, `<div class="a3s aXjCH adM"></div>` is the `msgBody` and being replaced in https://github.com/FlowCrypt/flowcrypt-browser/blob/f129d01b3c798995405ea7deee0fa9020c37b6ee/extension/js/content_scripts/webmail/gmail-element-replacer.ts#L461
