### ISSUE TITLE
Show/Hide passphrase icon isn't aligned correctly in `backup` element

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2272]
Here you can see that there is a little free space below the button which is not good:
![image](https://user-images.githubusercontent.com/49104848/70324687-d7718e00-1838-11ea-90ac-ff7de72d0da0.png)

It might have happened somewhere else.

**Comment by tomholub** [comment]
Interesting that this is not a problem on other screens, maybe some other style specific to this screen is affecting it.

**Comment by tomholub** [comment]
Un-assigning as a low-pri

**Comment by michael-volynets** [comment]
I will take a look
