### ISSUE TITLE
The draft is created by itself after opening the same encrypted message twice

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2274]
This is happening in Chrome, I didn't notice this in Firefox:

![1](https://user-images.githubusercontent.com/6059356/70330160-ab103e80-1845-11ea-8ff7-6e78bc840cd1.gif)

### Steps to reproduce:

1. Open any encrypted message
2. Go back to inbox
3. Open the same encrypted message again

### Expected behavior

No drafts are created.

### Actual behavior

The empty draft with a signature is created automatically, even though as a user I didn't type anything,

**Comment by tomholub** [comment]
Actually I'll have a look

**Comment by tomholub** [comment]
- [ ] clicking `...` in new message compose (which puts footer into text) should not yet cause draft to be saved

**Comment by tomholub** [comment]
@limonte I cannot reproduce this. But I had one user mention it. Could you take a look?

**Comment by limonte** [comment]
This should be happening for all account with a signature (footer)

In [this line](https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/common/composer/composer-draft.ts#L90) will wrongly return `true` because `cached('input_text').text()` will contain a signature (e.g. `--/Vladimir`) and `lastDraftBody` is `''`.

**Comment by tomholub** [comment]
I thought the same, but I set signature on my account to test this earlier, and still could not reproduce :(

**Comment by tomholub** [comment]
Anyway, I don't have to reproduce it myself, if you know how to fix it, please do.
