### ISSUE TITLE
atts not replaced when opening the same message the second time

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2309]
Steps to reproduce:
1. Open a message containing Public Key as an attachment.
2. When you opened it the first time, pgp_pubkey is rendered.
3. Go to `Inbox` and open the same message again.
4. Pgp_pubkey element isn't rendered.

This happens repeatedly. I mean when you open a message the first time - element is rendered, the second time - it isn't, third time - rendered, 4th - not, etc.

Actually, I don't know what can provoke this behavior. So I have to debug it first.

Added a video reproducing of the bug:
https://drive.google.com/file/d/1Ues6t7YZT_6YOPCoYbR9T6Dy33s3u9Ig/view?usp=sharing

**Comment by tomholub** [comment]
I may have broken this recently. I'll take a look.

**Comment by michael-volynets** [comment]
For your information, there are no errors in the dev. console.

**Comment by tomholub** [comment]
@michael-volynets thanks for noticing this, indeed I broke it when trying to address https://github.com/FlowCrypt/flowcrypt-browser/issues/1870
