### ISSUE TITLE
eslint rules

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2358]
We could add `Prettier` (https://github.com/prettier/prettier-vscode) VSCode extension to make it easier to format our files.
But first, we should Agree with what style of code we should use.

As I see now, we are using this code style:
```TS
  // We use indent 2 spaces

  method() { // before every method/lambda expression should be new line
    // inside a method we don't use any new lines
    const a = 0;
    if (<condition>) { // when using 'if', 'for', 'while' operators we always use these brackets '{', '}'
      <code>
    }
  }
```

And also we should add everything that described in `tslint.yaml`

**Comment by tomholub** [comment]
Yes, with 1 empty line around methods

```
class Class {
// 1 empty line
  method = () =>  {
  }  
// 1 empty line
  method = () =>  {
  }  
// 1 empty line
}
```
enforce if/for/when brackets - yes
no blank lines in methods - yes
enforce semicolon

For the future:
alphabetic ordering of imports

**Comment by tomholub** [comment]
ordering of methods:
 - constructor should always be the first method
 - public methods should follow
 - then protected methods
 - private methods should only last

**Comment by michael-volynets** [comment]
Yes, and also I think we should have the same with properties:
1. static properties
2. private static properties.
3. public properties.
4. protected properties
5. private properties
6. constructor
7. and the methods as you described above

**Comment by michael-volynets** [comment]
I just noticed something about sorting using `Prettier`.
They can't do this because it sometimes can be unsafe. They described it in this issue: (https://github.com/prettier/prettier/issues/5412)

I think I could find another extension that does what we need. But we will have to fully test the extension to make sure it won't break anything.

**Comment by tomholub** [comment]
We don't need an auto-fix for this, just a linter. eslint can probably do it.

**Comment by michael-volynets** [comment]
Got it, yes, I hope it does

**Comment by tomholub** [comment]
For now un-assigning both of us

**Comment by tomholub** [comment]
Once it gets assigned to somebody, the goal will be to add a linter that covers at some (small part) of what was mentioned above, along with a refactor that makes the code conform to the new rule.

Best to do it one by one (1 new linter rule per pr) so that it's easier to review for bugs.

**Comment by tomholub** [comment]
@michael-volynets what did you use to autofix the import order and method order? When I auto-import, it always seems to put it in the wrong place, and since it doesn't get autofixed, it can get quite frustrating to adjust manually.

**Comment by tomholub** [comment]
> Yes, and also I think we should have the same with properties:
> 
>     1. static properties
> 
>     2. private static properties.
> 
>     3. public properties.
> 
>     4. protected properties
> 
>     5. private properties
> 
>     6. constructor
> 
>     7. and the methods as you described above

Right now it uses default order which is: private first. Initially you used a custom ordering, but in the final PR you left it default which is not ideal.

**Comment by michael-volynets** [comment]
> @michael-volynets what did you use to autofix the import order and method order? When I auto-import, it always seems to put it in the wrong place, and since it doesn't get autofixed, it can get quite frustrating to adjust manually.

Yes, I used this extension for VSCode: https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports

> Right now it uses default order which is: private first. Initially you used a custom ordering, but in the final PR you left it default which is not ideal.

My bad, I think I made a mistake in my comment because I got used to writing the classes the way I described in the PR. But if you want I could change that.

**Comment by michael-volynets** [comment]
I also think we could add that  VSCode extension to our workspace recommendations

**Comment by tomholub** [comment]
The intention is that public are always first, protected second, private last. Should apply to normal as well as static methods. All static stuff should be above normal methods.

**Comment by tomholub** [comment]
> I also think we could add that VSCode extension to our workspace recommendations

Yes, that will be better

**Comment by michael-volynets** [comment]
> The intention is that public are always first, protected second, private last. Should apply to normal as well as static methods. All static stuff should be above normal methods.

Okay, I will change that and add the extension to our Workspace recommendations.
So the structure will look like this, right?:
1. public/protected/private static props
2.public/protected/private props
3. constructors
4. public/protected/private static methods
5. public/protected/private methods.

**Comment by tomholub** [comment]
I would put constructors below static methods, else looks good:

1. public/protected/private **static** props
2. public/protected/private props
3. public/protected/private **static** methods
4. constructors
5. public/protected/private methods.

**Comment by michael-volynets** [comment]
Makes sense, will do that.

**Comment by tomholub** [comment]
> > @michael-volynets what did you use to autofix the import order and method order? When I auto-import, it always seems to put it in the wrong place, and since it doesn't get autofixed, it can get quite frustrating to adjust manually.
> 
> Yes, I used this extension for VSCode: https://marketplace.visualstudio.com/items?itemName=amatiasq.sort-imports

This works. Also, how do you run auto-fix for order of methods?

**Comment by michael-volynets** [comment]
I ran this command ` tslint --fix --project ./tsconfig.json -c ./conf/tslint.yaml` but it fixes **all** rules that it can.

I think we could add NPM script that we will run before committing/pushing changes to our repository.

**Comment by tomholub** [comment]
Best would be if it could run all fixes for a particular file when I edit it (when I save it), like it does with imports - if possible.

**Comment by limonte** [comment]
> Best would be if it could run all fixes for a particular file when I edit it (when I save it), like it does with imports - if possible.

+1 for this, I personally don't like linting scripts before committing/pushing because they are slowing down the default Git workflow and sometimes even cause losing the focus.

**Comment by michael-volynets** [comment]
> Best would be if it could run all fixes for a particular file when I edit it (when I save it), like it does with imports - if possible.

Yes, it should be possible, let me check
