### ISSUE TITLE
css: input and button don't allign together properly

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#237]
![2016-12-12-182653_1920x1080_scrot](https://cloud.githubusercontent.com/assets/6306961/21125200/a3a61ff0-c098-11e6-836c-5b97ebd77d4a.png)

**Comment by tomholub** [comment]
see if still an issue

**Comment by schmorrison** [comment]
Is it preferred that button is beside the input or below the input?

Currently it seems that it is below the input on a separate line, if I add it to the same line it seems to be vertically centred on the input.

![image](https://user-images.githubusercontent.com/17385251/52833307-cc7b2080-30a1-11e9-9d98-3e83c1bc2b0d.png)

**Comment by tomholub** [comment]
That looks ok enough, we can probably close this.

Generally speaking below is better, unless the page is getting very tall and may need scrolling - then in may be better to shorten the page by putting related fields / buttons on the same line (with space between them).
