### ISSUE TITLE
automatically detect full screen mode and lift up send button

### ISSUE THREAD

**Issue by exceptionwhisperer** [FlowCrypt/flowcrypt-browser#239]
When using the laptop asus 11.9 inch screen, windows OS, The task bar is kept hidden usually for my personal use. In this case It was not and the encrypt and send radio button is not accessible. Screen capture shows a small clip of the non hidden taskbar. The Gmail compose send dialog box is in a different location by default. Neither are able to be moved. 
![image](https://cloud.githubusercontent.com/assets/24501419/21128241/3b3b951a-c0c7-11e6-8f63-f18a8e316cc2.png)

**Comment by tomholub** [comment]
Interesting, can you screenshot your standard gmail compose window? With the taskbar up?

I thought the task bar will come up only when you move your mouse to the very bottom edge. The only other way I imagine is if the chrome window was stretched down and to the sides manually as opposed to maximizing it, which I couldn't do much about.

**Comment by exceptionwhisperer** [comment]
First screen shot is the two compose dialog boxes opened side by side.
Chrome is full screen and taskbar is set to not hide . The bottom of the
send dialog boxes are pushed up above by default.

[image: Inline image 1]

Second is the the two compose screens with task-bar set to auto hide
Note the bottom of both compose dialog boxes are covered. Chrome is full
screen.
Also to make this happen chrome is not in focus, which in this case I had
to place the mouse over the taskbar which by design is correct.

[image: Inline image 1]

Gmails compose but set to full screen which places it above the task-bars
location by default even when you hide the task-bar
Place mouse below the box and taskbar does show

[image: Inline image 2]

Conclusion. I use the gmail stock compose but with full screen compose box,
by default The OS taskbar is set to auto hide to allow more-space on the
screen.
When focus has been in the CryptUP compose screen then mouse is moved into
the overlapping send, which is behind the hidden taskbar, the taskbar will
stay up in the way so click on the dialog box. That's the issue the auto
hide stays up, and does not hide
almost a mouse game move the mouse to send before the autohide comes back.
As if the mouse was left in the taskbar still.
Will try and reproduce multiple times. Now its random but does happen. As
the taskbar autohide is working fine then starts this behavior.
Hard to reproduce based on autohide is mouse based.
Will see if this is an issue with other apps as this is new.

**Comment by tomholub** [comment]
Somehow the screens didn't show, not sure why?

--
Tom James Holub <http://holub.me/>

**Comment by tomholub** [comment]
Ok I see it now. Online I read up some that people tend to have problem with the taskbar in windows being buggy and hiding bottoms of websites. I don't think I can detect this from within a web page.

**Comment by exceptionwhisperer** [comment]
Is moving the dialog box up to the same location used when using the option
"default  to full screen" location used by gmail seem feasible?
This puts the bottom of the dialog box up above the standard size task-bars
location hidden or not.

**Comment by tomholub** [comment]
I can detect full screen mode and place the window a bit higher up in full screen mode. That sounds reasonable.

My notes
```js
if( window.innerHeight == screen.height) {
    // browser is fullscreen
}
```

**Comment by exceptionwhisperer** [comment]
The code displayed is that to pick up this option, just checking to see if
we are on the same page.
The "default to full screen" is a choice in the compose new message far
right drop down

[image: Inline image 1]

**Comment by exceptionwhisperer** [comment]
When the browser is in full screen moving the Secure Compose window above
the taskbar to avoid the mouse focus issue seems appropriate.

**Comment by tomholub** [comment]
Please see if you can reproduce

**Comment by exceptionwhisperer** [comment]
Fixed. Send button is always accessible now after fix was implemented.
