### ISSUE TITLE
The 'Send empty message?' confirm dialog isn't happening

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2395]
### Steps to reproduce

1. Open the "Secure Compose" window
2. Fill the recipient and the subject
3. Press the `Encrypt, Sign and Send` button

### Expected behavior

The 'Send empty message?' confirm dialog is shown.

### Actual behavior

The empty message is sent.

### Tech details

The `plainText` variable isn't taking footer into account:

`![image](https://user-images.githubusercontent.com/6059356/71133143-5d5ee300-2202-11ea-9435-fab116aef6e7.png)

**Comment by tomholub** [comment]
Good find, no wonder people have been sending me more empty messages than before.

We should add a test for this.
