### ISSUE TITLE
No way to disable public contact page

### ISSUE THREAD

**Issue by bewell** [FlowCrypt/flowcrypt-browser#2402]
After enabling the public contact page ([this](https://flowcrypt.com/docs/guide/send-and-receive/encrypted-contact-page.html)) there is no way to disable it.

Maybe I'm missing something?

Thanks

**Comment by tomholub** [comment]
Hello, please email human@flowcrypt.com

For future readers: by the time you read this, https://flowcrypt.com/account/ may be available where you can disable it yourself.
