### ISSUE TITLE
fix download att percentage on Chrome

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2405]
> @tomholub yes, I was right, on Firefox everything works perfectly so we can at least leave Firefox as is.
> But we have to do something with Chrome. You know, we can even simulate downloading, I mean it will change percentage but it will be stuck on about 75% until the file is fully downloaded. I don't think it's a good practice but we don't have any option. On Chrome, we can do either this or don't show the progress bar at all.

I don't really understand - why is the length available in Firefox, but not chrome? What is the difference?

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/2394#issuecomment-567604281_

**Comment by michael-volynets** [comment]
<b>Tech details:</b>
When downloading with slow internet (GPRS) this message `/#inbox/WhctKJVjQggqrLdjZWtLwgQzhPWrCcnlwtmpPXzZhlWlCVWbpgdKwrhTmxNwpZftDsrTFBl` (compatibility account):
I see this response headers:
```
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
cache-control: private, max-age=0, must-revalidate, no-transform
content-encoding: gzip
content-length: 15129
content-type: application/json; charset=UTF-8
date: Fri, 20 Dec 2019 15:26:47 GMT
expires: Fri, 20 Dec 2019 15:26:47 GMT
server: GSE
vary: Origin, X-Origin
x-content-type-options: nosniff
x-firefox-spdy: h2
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
```
and this JSON of the progress event:
```
{
bubbles: false
cancelBubble: false
cancelable: false
composed: false
currentTarget: XMLHttpRequest
defaultPrevented: false
eventPhase: 2
explicitOriginalTarget: XMLHttpRequest
isTrusted: true
lengthComputable: true
loaded: 2247
originalTarget: XMLHttpRequest
returnValue: true
srcElement: XMLHttpRequest
target: XMLHttpRequest
timeStamp: 25246
total: 15129
type: "progress"
}
```
and when Firefox finishes loading the `event.loaded = 15129` so it's the same as `event.total`

Results from Chrome:
```
alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
cache-control: private, max-age=0, must-revalidate, no-transform
content-encoding: gzip
content-length: 15129
content-type: application/json; charset=UTF-8
date: Fri, 20 Dec 2019 15:40:56 GMT
expires: Fri, 20 Dec 2019 15:40:56 GMT
server: GSE
status: 200
vary: Origin, X-Origin
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
```
and this JSON of the progress event:
```
isTrusted: true
lengthComputable: false
loaded: 19904
total: 0
type: "progress"
target: XMLHttpRequest {onreadystatechange: null, readyState: 3, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
currentTarget: XMLHttpRequest {onreadystatechange: null, readyState: 3, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
eventPhase: 2
bubbles: false
cancelable: false
defaultPrevented: false
composed: false
timeStamp: 49399.21499998309
srcElement: XMLHttpRequest {onreadystatechange: null, readyState: 3, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
returnValue: true
cancelBubble: false
path: []
```
As you can see, Chrome's `event.loaded` property is more than `content-length: 15129`.
I think Firefox shows `even.loaded` as compressed loaded data but Chrome shows decompressed.

But I have no idea why Firefox doesn't want to show `total` for this message: `#inbox/WhctKJVjQggqrLhfdpFmQwlSgvqwSVsGkPTshJNQPcrTfCCVxxdwWXMxksgnWgRVQkdCzbG` (compatibility account)

**Comment by tomholub** [comment]
That means the difference between browsers is just the amounts that they report.

`#inbox/WhctKJVjQggqrLhfdpFmQwlSgvqwSVsGkPTshJNQPcrTfCCVxxdwWXMxksgnWgRVQkdCzbG` does not work on both browsers then? Or just Firefox?

**Comment by michael-volynets** [comment]
Yes, neither Firefox nor Chrome
