### ISSUE TITLE
fix rich text message quoting

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2412]
Use rich text to reply to rich text, it seems the quoted content is not getting properly recognized and trimmed.

**Comment by tomholub** [comment]
Please have a look if you can reproduce this. When you have a conversation between two accounts with rich text enabled on both ends, it seems that we don't properly hide the quoted content when rendering message in `pgp_block.htm`.

**Comment by michael-volynets** [comment]
So far so good. I couldn't reproduce the bug yet but found another, 
For now, I only found an issue when `Encrypted Subject`s display differently in both users.
User 1:
![image](https://user-images.githubusercontent.com/49104848/71993525-e97f8b80-323f-11ea-8444-936ae3ad35cc.png)
User 2:
![image](https://user-images.githubusercontent.com/49104848/71993546-f308f380-323f-11ea-8667-2ad96dd423b3.png)

As you see, the first user (sender) can't see `Encrypted subject` header but the second one (receiver) can see it. The same thing is with the second message but sender & receiver have changed

I suppose they should not be shown at all, should they?

**Comment by michael-volynets** [comment]
I will continue testing, maybe I will find something else

**Comment by tomholub** [comment]
The encrypted subjects are interesting, but they don't bother me too much

**Comment by michael-volynets** [comment]
Okay, I've tested all possible variants of sending a Rich Text message. Quoted content rendered well in any of those messages. 

What I found that could be improved:
 - Currently, quoted content doesn't show any Rich text tags, it shows only plain text.
Look at a screenshot below:
![image](https://user-images.githubusercontent.com/49104848/71998382-2f405200-3248-11ea-9b9a-ed32422142a9.png)
We could render the quoted content with all HTML allowed tags.
- When we sent a new message with Rich Text and rendered it on the thread page, we showed it as plain text and without quoted contend. Screenshot attached:
![image](https://user-images.githubusercontent.com/49104848/71998723-d58c5780-3248-11ea-86c0-96a3f0c4388d.png)
It also may confuse some users that used Rich Text in their message. The solution for this issue would be to remove the `compose` element and render the `pgp_block` element.

Total Time Spent: 1h 30m

**Comment by tomholub** [comment]
> Currently, quoted content doesn't show any Rich text tags, it shows only plain text.

Thanks for noticing. I did this intentionally, I find it too messy to keep the html in quoted content.

> When we sent a new message with Rich Text and rendered it on the thread page, we showed it as plain text and without quoted contend. Screenshot attached:

We have issue for this here: https://github.com/FlowCrypt/flowcrypt-browser/issues/2439

Although in some ways, rendering pgp_block would be the cleanest solution, it is also not ideal because it will now have to decrypt the message we just sent, and that can be expensive.

Anyway, looks like all is well with quoting rich text, so I'm closing this.
