### ISSUE TITLE
"Send btn" is blocked when canceling PP modal

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2416]
Steps to reproduce:
1. Forget all Passphrases stored in a browser
2. Open & fill compose window
3. Click `Send` button.
4. You should see `Enter Passphrase` modal dialog, click `later` 
5. The `send` button gets blocked and you can't send the message anymore.

Screenshot:
![image](https://user-images.githubusercontent.com/49104848/71278264-c14aee00-235f-11ea-91f2-f981102136e6.png)

Expected Result:
Send button isn't blocked when clicking `later` button in the modal winow

**Comment by michael-volynets** [comment]
The same when you are trying to download an encrypted attachment.
When you click on the `Download` button after that you cancel modal dialog the `Download` button won't be clickable anymore.

**Comment by tomholub** [comment]
You could reset the send btn state after you send the `BrowserMsg` to open pp dialog. Then you could programmatically `.click()` it when pass phrase becomes available.

**Comment by michael-volynets** [comment]
Actually, the issue is somewhere deeper, because I found a listener for resetting the button in `composer-storage.ts` file.
```TS
  initActions = () => {
    BrowserMsg.addListener('passphrase_entry', async ({ entered }: Bm.PassphraseEntry) => {
      if (!entered) {
        clearInterval(this.passphraseInterval);
        this.composer.sendBtn.resetSendBtn();
      }
    });
  }
```

**Comment by tomholub** [comment]
I see

**Comment by michael-volynets** [comment]
Composer window is fixed. 
I started fixing AttachmentView.
I will also check other elements/pages where this modal dialog is used, I think this issue may occur in other places.
