### ISSUE TITLE
It's impossible to download the attachment using keyboard

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2418]
![image](https://user-images.githubusercontent.com/6059356/71289684-535df100-2376-11ea-8425-0fb7e9ae78bb.png)

1. `div#download`should be in the taborder. 
2. When focused, there should be an outline so users will be able to see the focused element
3. When focused, `Space` or `Enter` should trigger downloading
4. Once downloaded, the focus should be on `.file-download-right-click-link` so users will be able to press `Shift` + `F10` to trigger the context menu and proceed with `Save Link As...`

A small detail that can be included in this PR: add the ellipsis to match the item from the system context menu:

![image](https://user-images.githubusercontent.com/6059356/71289577-23aee900-2376-11ea-914c-cec79a944cf4.png)

as well as in

![image](https://user-images.githubusercontent.com/6059356/71290258-0f6beb80-2378-11ea-8bd2-1feeedf4e17f.png)

**Comment by tomholub** [comment]
Agree

The "Save link as..." bothers me quite a bit in general, but it's what I've done to work around browser restrictions (which only started popping up in browsers about 1 year ago). I hope to one day re-visit it and see if it can work without it., like before, by just clicking it, then waiting for the download.

At one point it stopped working in Gmail but still worked in flowcrypt inbox, suggesting it's a restrictions on frames inside host pages on different origin.
