### ISSUE TITLE
Compose window gets overflowed when pasting or typing lots of text, can't see borders

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2420]
Steps to reproduce:
1. Open Compose window
2. Paste several times a large amount of text or start typing only new lines
3. You will see that the top and bottom parts of the composer is getting hidden;

Expected result:
The text is shown between the borders. Composer should have original height.

![image](https://user-images.githubusercontent.com/49104848/71295706-cae74c80-2385-11ea-91e6-9cd642423527.png)

**Comment by limonte** [comment]
Oops, my bad. The issue is happening in Chrome only. I'll handle it.

**Comment by tomholub** [comment]
I have not released Squire to chrome yet, so it should not be affecting users. Thank you both for noticing & fixing
