### ISSUE TITLE
The footer (signature) is duplicated when replying

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2427]
This issue is happening in Chrome only:

![1](https://user-images.githubusercontent.com/6059356/71308343-f9a40800-2403-11ea-856c-5b616266f6d6.gif)

**Comment by michael-volynets** [comment]
Interesting, I think it could have happened because of my latest changes. Let me check.
Thanks!

**Comment by tomholub** [comment]
Let's have a test for this - footer should not be visibly present when new reply is rendered (unless there was a draft).

**Comment by michael-volynets** [comment]
Unfortunately, I couldn't reproduce that. When I click on the `reply` button the Reply Window is rendered without my footer. Could you please try to reply to other messages? Are you facing the same issue?

**Comment by michael-volynets** [comment]
Reproduced, fixing

**Comment by michael-volynets** [comment]
no, I was wrong, it happened only once and now I can't reproduce this again. Interesting...

**Comment by michael-volynets** [comment]
The issue happened when you changed your footer in the settings tab and then opened the reply window, then footer should double.
