### ISSUE TITLE
When replying with rich text, the reply is rendered as plain text

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2439]
Right after sending, the rich text message is rendered as plain text:

![1](https://user-images.githubusercontent.com/6059356/71443560-434a6680-2714-11ea-8aa8-65530b341985.gif)

If reopened, the reply will be rendered properly, as rich text.

**Comment by tomholub** [comment]
Thanks, I believe there are several bugs related to this, because we use different code to render sent replies vs rendering received messages, and they are always somehow out of sync. One day we should abstract that away.

**Comment by tomholub** [comment]
Marking as third priority so that we can focus on other things first.

**Comment by limonte** [comment]
I would be happy to resolve this because the issue might cost a lot of nerves when sending messages with attachments.

Attachments aren't being rendered and the first thought after seeing the sent message is "DAMN! DID I FORGET TO ATTACH A FILE?"

![Peek 2020-03-14 10-06](https://user-images.githubusercontent.com/6059356/76677864-ddb39b00-65db-11ea-812f-09d021075d57.gif)

**Comment by tomholub** [comment]
Yeah, that's fair. (should only happen when using the experimental rich text method, but still annoying)

**Comment by limonte** [comment]
> (should only happen when using the experimental rich text method, but still annoying)

Correct. Btw, I was wondering when were you planning to enable that feature in Chrome?

**Comment by tomholub** [comment]
There are compatibility issues with other software, to the extent that it appears the only way to get it compatible is for Google to fix their API. That may take a while. Given that, I'll have to rework it change the format a bit + only send such messages to FlowCrypt users, and that may take a while to get done.
