### ISSUE TITLE
The secure reply iframe isn't rendered after deleting a message from a thread

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2440]
### Steps to reproduce

1. Go to any encrypted thread with 2 or more messages
2. Delete the last message

### Expected behavior

Native "Reply" and "Forward" buttons are replaced by FlowCrypt's ones.

### Actual behavior

Native buttons aren't replaced.

![1](https://user-images.githubusercontent.com/6059356/71443644-d2577e80-2714-11ea-99cc-7d9db8a7a187.gif)

**Comment by tomholub** [comment]
Thanks! Marking as "not anytime soon" until we start catching up on other issues (I'm hoping this one is quite rare).
