### ISSUE TITLE
'Decrypting...' text doesn't fit inside the `triple dot` button

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2446]
I assume this text should not be present in the `triple dot` button at all. 
But if it should then we have to correct CSS.

![Decrypting text doesn't fit](https://user-images.githubusercontent.com/49104848/71576393-3bfed080-2af9-11ea-94bc-b1ae38a3241d.gif)

**Comment by tomholub** [comment]
I overlooked that, thanks
