### ISSUE TITLE
When editing a draft, pasting plain text is creating unwanted `<div>` container for pasted text

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2447]
This is a strange issue and I don't even know for now where to start looking for the reason: in the rich-text editor implementation or in the implementation of drafts.

### Steps to reproduce
1. create a new secure message e.g. "hello world", close the "new secure message" window
2. go to drafts, open secure draft
3. place cursor between "hello" and "world"
4. paste a plain text e.g. "beautiful"

### Expected result
hello beautiful world

### Actual result
hello 
beautiful
world

![1](https://user-images.githubusercontent.com/6059356/71582980-25667280-2b15-11ea-9bd9-93b3c6213416.gif)

Strangely enough, this is happening only when editing a draft. I also can't reproduce the issue in https://limonte.github.io/squire-sandbox/

Happening in both browsers (on Linux)

**Comment by tomholub** [comment]
If I'm not wrong, we use `<br />` as line breaks for saved drafts. Maybe that throws Squire off. Maybe it likes divs instead?

Not assigning anyone yet since it only happens when opening a draft.

**Comment by limonte** [comment]
This issue was fixed in https://github.com/FlowCrypt/flowcrypt-browser/commit/7ada1e2ed4dff0c31668e8530288e97faaad077d#diff-f59cdd2fcdf43ccf28e9643efeeeed2dR43

Squire didn't like setting `innerHTML` directly, which was happening in `Xss.sanitizeRender`. Squire prefers using its API method `.setHTML` instead.
