### ISSUE TITLE
standardize file names

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2450]
use `some-name.ts` rather than `some_name.ts` if class is named `SomeName`.

Does not yet apply to views, for example `pgp_block.ts` will stay as is, for now, to follow `pgp_block.htm`.

**Comment by michael-volynets** [comment]
Do I need to update `.htm` files?

**Comment by michael-volynets** [comment]
I will update them but in separate PR

**Comment by michael-volynets** [comment]
Nevermind, just noticed that you wrote not to update them,
