### ISSUE TITLE
Update all '.ts' files header comment

### ISSUE THREAD

**Issue by michael-volynets** [FlowCrypt/flowcrypt-browser#2452]
At the moment we have this comment:
`/* © 2016-2018 FlowCrypt Limited. Limitations apply. Contact human@flowcrypt.com */ ` 
but it should say:
 `/ ©️ 2016-2020 FlowCrypt a.s. Limitations apply. Contact human@flowcrypt.com /`.

Also, add ESlint rule to check if this comment is present at the beginning of all `.ts` files in `./extension/**` and `./tests/**` folders

**Comment by limonte** [comment]
You can use `present` instead of `2020` to avoid this chore every year :)

https://github.com/microsoft/vscode/blob/master/LICENSE.txt#L3

**Comment by tomholub** [comment]
> You can use `present` instead of `2020` to avoid this chore every year :)
> 
> https://github.com/microsoft/vscode/blob/master/LICENSE.txt#L3

I feel like an idiot. Let's do that.
