### ISSUE TITLE
Uncaught SyntaxError: Identifier 'EmailProviderApi' has already been declared

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2462]
Steps to reproduce:

1. clone the repo
2. run `npm run build`
3. load the unpacked extension in Chrome

The actual result:

```
Uncaught SyntaxError: Identifier 'EmailProviderApi' has already been declared
```

![image](https://user-images.githubusercontent.com/6059356/71731736-2cabba00-2e4e-11ea-8bc1-bcf9ba66d046.png)

On the other hand, there's no `email_provider_api.js` in `build` folder:

![image](https://user-images.githubusercontent.com/6059356/71731890-88764300-2e4e-11ea-90ab-03e20c386252.png)

@tomholub I'm probably missing some caching somewhere

**Comment by tomholub** [comment]
I renamed it recently from `email_provider_api.js` to `email-provider-api.js`. But where is it still getting the old name? Weird.

**Comment by limonte** [comment]
Weird indeed. I removed the `build` folder once again, ran `npm run build` and it works fine now.

I can confirm that the caching is disabled in both browsers so it shouldn't be the reason
![image](https://user-images.githubusercontent.com/6059356/71740845-009c3300-2e66-11ea-9c91-04bd83e6bb33.png)

Closing as I can't reproduce it anymore.

**Comment by tomholub** [comment]
I don't think it's browser cache, this must be build script quirk. For now, let's ignore it.
