### ISSUE TITLE
The recently added sort-imports extension hurts DX

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2465]
On every Ctrl+S `sort-imports` causes the editor to redraw the whole thing which is poor for performance and also produces annoying glitches:

![1](https://user-images.githubusercontent.com/6059356/71763654-fa01d000-2ee6-11ea-84da-39048f23b475.gif)

**Comment by limonte** [comment]
Is it just my editor or the same is happening for everybody?

**Comment by tomholub** [comment]
It's happening to me too. It is indeed mildly annoying. Please see if experimenting with other ordering extension fixes this. Worst case we'd abandon imports ordering, and maybe order them once in a few months in a PR.. until there's an extension that can do it seamlessly.

**Comment by tomholub** [comment]
closing since we stopped using it
