### ISSUE TITLE
Option to use GnuPG instead of OpenPGP.js

### ISSUE THREAD

**Issue by skumblex** [FlowCrypt/flowcrypt-browser#2466]
I would be really nice if there would be an option to use a native implementation of OpenPGP instead of OpenPGP.js, like GnuPG on GNU/Linux systems.

**Background**: I am using FlowCrypt for Gmail but Enigmail in Thunderbird for my work email address. Enigmail uses the GnuPG implementation that was shipped with my system. However, since FlowCrypt does not integrate with this native tool, I have to curate two separate key/contact lists. I know that Mailvelope is offering this option and since it is open-source, it might be possible to get some inspiration on how to do this from the respective source code.

Using this option, a user would only need to curate one list of keys for each machine.

**Comment by tomholub** [comment]
Hello, thank you for contributing an issue with your thoughts.

What you're describing will most likely end up being a side-effect of implementing #964 for which we'll most likely need to interact with gpg-agent. As a result, you should be able to keep your keys just in gpg when done.

I'll close this issue - although it's not a real duplicate - it should get solved by #964.
