### ISSUE TITLE
Settings: .action-toggle-accounts-menu should be accessible with keyboard

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2467]
Switching accounts should be possible with the keyboard:

![image](https://user-images.githubusercontent.com/6059356/71780642-d6fe1b80-2fcd-11ea-85b2-0de2801f4c81.png)

1. `.action-toggle-accounts-menu` should be focusable
2. Space or Enter should show the accounts menu (`#alt-accounts`)
3. Arrows should navigate the accounts menu
4. Enter should simulate clicking on the selected item in the accounts menu
5. Esc should close the accounts menu and bring the focus back to `.action-toggle-accounts-menu`

**Comment by tomholub** [comment]
Thanks, marking 3rd priority, for later
