### ISSUE TITLE
Are test/**/*.ts files subject to tslint?

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2470]
Currently, if I open any `test/**/*.ts` file, e.g. `test/source/browser/controllable.ts`, `tslint` is highlighting errors:

![image](https://user-images.githubusercontent.com/6059356/71892834-ae535e80-3152-11ea-804d-2188a5d21157.png)

Also, when I press `Ctrl+S`, the file will be changed automatically and those changes will be unrelated to other changes in the current branch/commit.

@tomholub @michael-volynets is this the case only for me? I wonder why my editor is reporting errors but `npm run test_tslint` reports success.

**Comment by tomholub** [comment]
Same here. It's an oversight, ideally they would also be tested.

Currently eslint/tslint uses `./tsconfig.json` which does not include tests. To cover tests, one would have to also target `./conf/tsconfig.tests.json` somehow.

**Comment by tomholub** [comment]
> Also, when I press Ctrl+S, the file will be changed automatically and those changes will be unrelated to other changes in the current branch/commit.

Not sure what this means, but we have not run any autofixes yet across the test files. Maybe that's what you're referring to, it's trying to fix it all up?

That means it's set up correctly, but we just haven't run autofix on the tests yet to fix them all.

**Comment by tomholub** [comment]
You could try to fix them up using 
```
tslint --fix --project ./conf/tsconfig.tests.json -c ./conf/tslint.yaml
```
Ideally in a separate PR.

**Comment by limonte** [comment]
> Maybe that's what you're referring to, it's trying to fix it all up?

Yup.

> You could try to fix them up using
> tslint --fix --project ./conf/tsconfig.tests.json -c ./conf/tslint.yaml
> Ideally in a separate PR.

Done: #2471
