### ISSUE TITLE
Settings: div.key_list isn't scrollable

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2489]
Currently, it's not possible to scroll the list of keys and it's needed when there are more than 3 keys:

![image](https://user-images.githubusercontent.com/6059356/72669863-a1cae200-3a3f-11ea-968a-c9738776e1b9.png)

**Comment by tomholub** [comment]
At one point I think there was a limit of 4 keys, would not let you import more. Then the max height was equal to 4 keys worth. I forgot if there's still such limit.

**Comment by tomholub** [comment]
I'll leave the solution up to you

**Comment by tomholub** [comment]
I did unrelated change that fixed this:

![image](https://user-images.githubusercontent.com/6306961/76152316-20dead00-60b6-11ea-86f9-5d412b08476c.png)
