### ISSUE TITLE
CORS failures - add api methods to permissions

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2502]
Today, I stumbled upon this issue in my dev environment:

![image](https://user-images.githubusercontent.com/6059356/73253131-95275600-41c4-11ea-959d-9525b5afa8fc.png)

which results into 

![image](https://user-images.githubusercontent.com/6059356/73253160-a3757200-41c4-11ea-8ee6-1fb776c4c0dd.png)

I removed the local entension and replaced it with the one published for all users and the error is not happening with published version.

All is well in Chrome.

Firefox version: 72.0.1 (64-bit)

**Comment by limonte** [comment]
As I understand the releasing table, the release of v72 was on Jan 7th

![image](https://user-images.githubusercontent.com/6059356/73253386-1a126f80-41c5-11ea-9bcb-c99abcc73d7c.png)

and I believe that I updated Firefox to v72 earlier which means the issue isn't related to some change in Firefox policies.

**Comment by limonte** [comment]
@tomholub I didn't notice, but did we maybe change something recently regarding calling googleapis API endpoints?

**Comment by limonte** [comment]
This is weird. Trying different things to resolve this, I switched off the Tracking Protection:

![image](https://user-images.githubusercontent.com/6059356/73253948-2945ed00-41c6-11ea-8820-29764d2f2f4a.png)

Which for some weird reason triggered FlowCrypt to ask me to set up my account again, which I did.

After that, the issue was gone.

Then I switched the Tracking Protection on to verify that the issue caused by it, but surprisingly, I wasn't able to reproduce it even with Tracking Protection on.

Weird issue, but since it's gone and I can't reproduce it anymore I'm closing it.

**Comment by tomholub** [comment]
I suspect this has to do with us recently changing permissions. It affects CORS. We had that issue on chrome-enterprise before, which was using restricted permissions for a while now.

I'll re-open it to see, in case I only mitigated it on chrome and should also allow the mitigation on Firefox. I'm unsure.

**Comment by limonte** [comment]
Argh... happening again for me with disabled Tracking Protection

![image](https://user-images.githubusercontent.com/6059356/73255812-88593100-41c9-11ea-833d-8edcc85ca893.png)

![image](https://user-images.githubusercontent.com/6059356/73255854-97d87a00-41c9-11ea-9e08-03216dc8db27.png)

**Comment by limonte** [comment]
> I suspect this has to do with us recently changing permissions. It affects CORS. We had that issue on chrome-enterprise before, which was using restricted permissions for a while now.
> 
> I'll re-open it to see, in case I only mitigated it on chrome and should also allow the mitigation on Firefox. I'm unsure.

I'll check if permission are affecting this :+1:

**Comment by tomholub** [comment]
The one published for all users was a previous version, does not yet have the permissions update.

**Comment by limonte** [comment]
It seems that we've missed 

![image](https://user-images.githubusercontent.com/6059356/73256808-4cbf6680-41cb-11ea-9a76-0e2ab5ae2b5e.png)

**Comment by limonte** [comment]
Without `https://www.googleapis.com`, it's not possible to set up FlowCrypt: 

![image](https://user-images.githubusercontent.com/6059356/73256917-7bd5d800-41cb-11ea-9738-f3845d3459bb.png)

I have no idea how this didn't happen to me during testing. Confusing.

**Comment by tomholub** [comment]
Having to list all domains that we'll do API calls to is problematic. I don't think we should be required to do that, and it seems it's only a problem on Firefox.

One solution would be to leave the permissions as they are on Firefox, and only lower them on Chrome.

Another solution would be to go ahead and list them one by one, and risk problems in the future when we need to reach one more api domain (like for Outlook mail).

**Comment by tomholub** [comment]
On my end though, I can run the extension on ff without problems, latest version, with reduced permissions.

Setup is not a problem:

![image](https://user-images.githubusercontent.com/6306961/73258117-efbcb400-41bc-11ea-84c6-ed41673a0b29.png)

Firefox 72.0.1 (64-bit) - same

**Comment by limonte** [comment]
> Having to list all domains that we'll do API calls to is problematic. I don't think we should be required to do that, and it seems it's only a problem on Firefox.

Yup, it seems that there's the difference in browser policies here, Chrome works well without `https://www.googleapis.com` listed in `permissions` field.

> One solution would be to leave the permissions as they are on Firefox, and only lower them on Chrome.

That would undo https://github.com/FlowCrypt/flowcrypt-browser/issues/1897 for Firefox.

> Another solution would be to go ahead and list them one by one, and risk problems in the future when we need to reach one more api domain (like for Outlook mail).

That risk would be eliminated by Manifest V3 (mid 2020) if I understood your comment form https://github.com/FlowCrypt/flowcrypt-browser/issues/1897#issuecomment-520510582 correctly.

**Comment by limonte** [comment]
> On my end though, I can run the extension on ff without problems, latest version, with reduced permissions.
> 
> Setup is not a problem:
> 
> ![image](https://user-images.githubusercontent.com/6306961/73258117-efbcb400-41bc-11ea-84c6-ed41673a0b29.png)
> 
> Firefox 72.0.1 (64-bit) - same

I'll try to reproduce the issue on clean Windows and Mac machines.

**Comment by tomholub** [comment]
I'm using Ubuntu here.



> >    Another solution would be to go ahead and list them one by one, and risk problems in the future when we need to reach one more api domain (like for Outlook mail).
>
>That risk would be eliminated by Manifest V3 (mid 2020) if I understood your comment from #1897 (comment) correctly.

I'm unsure. Manifest V3 was meant for operating on tabs of certain domains. When making API requests... I have no clue. I don't know if there will be an obvious way to prompt user to allow a domain that will only be used for api calls, as opposed to a tab that they open themselves. We may need to have them navigate to https://www.googleapis.com/ in url and ask them to allow there.. which would be extremely cumbersome.

Really hard to say.

**Comment by tomholub** [comment]
> >   One solution would be to leave the permissions as they are on Firefox, and only lower them on Chrome.
>
> That would undo #1897 for Firefox.

That's right. None of the solutions seem quite correct.

**Comment by tomholub** [comment]
I can reproduce it.

1) create a new firefox profile `firefox -ProfileManager`
2) set folder manually to something easy, in my case `~/.mozilla/firefox/flowcrypt-dev-2`
3) update `run_firefox` npm script temporarily to point there
4) `npm run-script run_firefox`

**Comment by tomholub** [comment]
You could skip a bunch of steps if you just wanted to load the extensions manually instead. As long as you do it on a fresh profile. This was on ubuntu.

**Comment by tomholub** [comment]
I suspect I may know what the solution could be - run all requests through background script.. like we do from content scripts. I'll give it a try.

**Comment by tomholub** [comment]
tried this
```js
  public static ajax = async (req: JQueryAjaxSettings, stack: string): Promise<any | JQuery.jqXHR<any>> => {
    if (Env.isContentScript() || (Catch.browser().name === 'firefox' && Env.isExtension() && !Env.isBackgroundPage())) {
      // content script CORS not allowed anymore, have to drag it through background page
      // https://www.chromestatus.com/feature/5629709824032768
      return await BrowserMsg.send.bg.await.ajax({ req, stack });
    }
```
Where I added `Catch.browser().name === 'firefox' && Env.isExtension() && !Env.isBackgroundPage()`.

Didn't work, now request fail just the same, except the errors show in background script.

**Comment by tomholub** [comment]
Alright, we'll just add them all. Let's make sure each one of these are included. On chrome too, in case the browser changes in the future. We will lose the flexibility to be adding more domains after we deploy this. Lucky I haven't yet.

```
https://graph.microsoft.com/*
https://login.microsoftonline.com/*
https://outlook.office.com/*
https://outlook.office365.com/*
https://www.googleapis.com/*
```
