### ISSUE TITLE
use standard browser methods to open settings window

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2504]
Either window.open or `<a href>` with a target. Need to test from:
 - browser popup
 - content script
 - settings page itself

------------------

We use `chrome.tabs` to find out if settings are already open and if yes, replace existing settings tab when opening new settings tab. This is not so crucial, can probably use some more standard way to do something similar, even `<a href target>` should do the job:

```js
  public static openExtensionTab = async (url: string) => {
    const openedTab = await BgUtils.getFcSettingsTabIdIfOpen();
    if (!openedTab) {
      chrome.tabs.create({ url });
    } else {
      chrome.tabs.update(openedTab, { url, active: true });
    }
  }

  public static getFcSettingsTabIdIfOpen = async (): Promise<number | undefined> => {
    return await new Promise(resolve => {
      chrome.tabs.query({ currentWindow: true }, tabs => {
        const extensionUrl = chrome.runtime.getURL('/');
        for (const tab of tabs) {
          if (tab.url && tab.url.includes(extensionUrl)) {
            resolve(tab.id);
            return;
          }
        }
        resolve(undefined);
      });
    });
  }
```

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/2497#issuecomment-579169967_

**Comment by tomholub** [comment]
Need to also test on Firefox, it tends to be restrictive with these things.

**Comment by limonte** [comment]
I am unable to resolve this with `window.open` as it doesn't seem to work from background scripts in Firefox. 

Related SO question: https://stackoverflow.com/questions/48982711/window-open-in-background-js-in-firefox-extension
Related (most probably) issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1296882

---

@tomholub I'm not sure about `<a href target>` though, could you please elaborate a bit on how it can be used to replace the logic with `chrome.tabs.create`?

**Comment by tomholub** [comment]
Let's say there is a button that causes settings page to be open, like the browser action button popup with the [cog] icon.

When user clicks, current approach is to send a BrowserMsg to background, and from background, use `chrome.tabs.create` to create a new tab, to open settings.

Two other possible approaches (either way, handled directly, not through background script):
1) handle a click and call window.open directly from the handler
2) make the cogs icon a link, such as `<a href="... settings window url ..." target="flowcrypt-settings"><img src="cogs icon"></a>`.

**Comment by tomholub** [comment]
Hopefully, we should never actually need to create popups from the background.

The one exception I can think of right now is the `initial.htm` page when the extension gets first installed.. we would have to find a solution for that too.

**Comment by limonte** [comment]
As per https://github.com/FlowCrypt/flowcrypt-browser/pull/2714#pullrequestreview-402416320 we were not able to achieve exactly what was desired.

@tomholub Let's move this issue from the `First priority` milestone somewhere else what'd be right for partly completed issues like this one.

**Comment by tomholub** [comment]
I'm moving it to third, and then we'll re-evaluate later.

**Comment by tomholub** [comment]
Thanks!

**Comment by tomholub** [comment]
Unassigning for now, to possibly look into even later

**Comment by tomholub** [comment]
closing, but accepting external contributions. The goal is to stop using `chrome.tabs` since we don't want to request that permission during add-on install if we can find a way to avoid it.
