### ISSUE TITLE
Can't start puppeteer with devtools: true

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2575]
Sometimes during writing tests it's handy to start puppeteer with `devtools: true` https://github.com/FlowCrypt/flowcrypt-browser/blob/ae45bd3684cb0a75fcf3d8f447c1400e454aaec5/test/source/browser/browser-pool.ts#L43

I was working before, but after upgrade to `v1.20.0` in #2564 it doesn't work anymore, browser just opens and closes immediately without any errors in log.

**Comment by limonte** [comment]
At least `v1.19.0` is needed for `waitForFileChooser`: https://pptr.dev/#?product=Puppeteer&version=v1.19.0&show=api-class-filechooser

**Comment by limonte** [comment]
Yup, `v1.19.0` works fine :+1:

**Comment by limonte** [comment]
> Yup, `v1.19.0` works fine +1

Nope https://github.com/FlowCrypt/flowcrypt-browser/pull/2576#issuecomment-590400488

--

I'll monitor new puppeteer releases and check if the issue will be fixed in next releases.

**Comment by limonte** [comment]
For now, if `devtools: true` is needed, just install `v1.19.0` locally without committing changes in `package.json`.

**Comment by tomholub** [comment]
Also you can try to press F12 to open debugger while a window is open, if that works

**Comment by limonte** [comment]
> Also you can try to press F12 to open debugger while a window is open, if that works

When debugging tests in VSCode, `devtools: true` allowing to debug the node.js context rather than browser context, so I can debug statements like this one `await page.evaluate(() => {debugger;});`, read more in the list item # 4 here: https://github.com/puppeteer/puppeteer#debugging-tips

**Comment by tomholub** [comment]
Didn't know this. Got it!
