### ISSUE TITLE
Uncaught SyntaxError: Identifier 'KEY_CACHE' has already been declared

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2585]
Steps to reproduce:

 -   clone the repo
 -   run npm run build
 -   load the unpacked extension in Chrome

The actual result:

![image](https://user-images.githubusercontent.com/6059356/75258918-df195100-57ef-11ea-9f23-92050dac9085.png)

![image](https://user-images.githubusercontent.com/6059356/75258894-d4f75280-57ef-11ea-8a66-565c1da97cfe.png)

@tomholub  Is it something on my side or you can reproduce the issue as well?

**Comment by tomholub** [comment]
I think this affects incremental builds, they were not designed to handle deleted files in some situations. Wiping the build folder should fix it.

**Comment by tomholub** [comment]
There should not be any `common/platform/store.js` file anymore because corresponding `store.ts` file was also removed.

**Comment by limonte** [comment]
> I think this affects incremental builds, they were not designed to handle deleted files in some situations. Wiping the build folder should fix it.

Right, removing the `build` folder resolved it. Thanks!
