### ISSUE TITLE
categorize: unknown err on firefox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2587]
Lately started seeing this on ff. If it affects chrome too, we should add a test

![image](https://user-images.githubusercontent.com/6306961/75272555-0ffc8480-57f6-11ea-9c25-4e182fa69f0a.png)

**Comment by limonte** [comment]
I faced this issue, it was happening when typing symbols in the recipients input, the error was saying something about `dbIndex` being undefined, I thought it's related to my environment and didn't report it :/

I can't reproduce it anymore.

**Comment by tomholub** [comment]
> typing

You can reproduce it by opening an email that has a public key attached to it as a file (in compatibility account, the `pubkey` label will get you some).

If you will have a time to look at it today, please do else I may look into it in a few hours.

**Comment by tomholub** [comment]
I'll fix this, browser is blocking communication between content scripts and background page.

![image](https://user-images.githubusercontent.com/6306961/75344347-5b647080-5892-11ea-9567-15051c6f1da1.png)

To avoid converting data to and from blobs, I'll send it as string instead of a typed array.
