### ISSUE TITLE
First lines of RTL messages are overlapping #pgp_signature 

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2599]
![image](https://user-images.githubusercontent.com/6059356/75441839-0c3c3f80-5967-11ea-8015-fa5191b4748f.png)

Not sure about the solution, something to think about, @tomholub suggestions are welcome!

**Comment by tomholub** [comment]
if any RTL line is present in body, we could give the signature a `position:relative` and just have it be above all text

**Comment by tomholub** [comment]
Above text, or below, either way

**Comment by limonte** [comment]
It's also the case for RTL as well:

![image](https://user-images.githubusercontent.com/6059356/75536964-d064b100-5a1e-11ea-8de6-346132d2361d.png)

@tomholub what do you think about making the signature floating:

![image](https://user-images.githubusercontent.com/6059356/75537113-1b7ec400-5a1f-11ea-8800-3f7a96fb176c.png)

![image](https://user-images.githubusercontent.com/6059356/75537279-639de680-5a1f-11ea-8828-bc0892237a2f.png)
