### ISSUE TITLE
The focused state on the Secure Reply button isn't working

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2615]
There are '.on()` handlers followed by `.off()`:

![image](https://user-images.githubusercontent.com/6059356/75765771-b392eb00-5d48-11ea-9fb1-df62a9a70d63.png)

in https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/content_scripts/webmail/gmail-element-replacer.ts#L159

It should be `.off('keydown')` I guess

**Comment by tomholub** [comment]
@limonte I think there should be just off first followed by on. To turn off all Gmail functionality (maybe it was trying to set something?), then set our own.
