### ISSUE TITLE
test offline gmail mode - decrypt

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2622]
here's a 1st priority issue for you! :)

Please test decrypting message in offline mode. It's supposed to be able to decrypt messages (at least the inline ones) without going online.

It's very important for a potential customer.

**Comment by limonte** [comment]
Decrypting message in offline mode seems to work, I'll add a test.

**Comment by tomholub** [comment]
> Decrypting message in offline mode seems to work, I'll add a test to verify that.

That would be awesome

**Comment by tomholub** [comment]
Does the whole FlowCrypt UI startup if you open gmail while offline? Is it even possible to open Gmail while you start out offline? (some offline plugin they have or whatnot)

**Comment by limonte** [comment]
> Is it even possible to open Gmail while you start out offline? (some offline plugin they have or whatnot)

Yes, thanks to Service Workers.

> Does the whole FlowCrypt UI startup if you open gmail while offline? 

Yes. The `https://flowcrypt.com/api/account/check` will fail, but other than that all resources are stored locally. On the other hand, Gmail's compose window won't open which makes FlowCrypt  better than Gmail in the offline UI :muscle:

**Comment by limonte** [comment]
> On the other hand, Gmail's compose window won't open which makes FlowCrypt better than Gmail in the offline UI muscle

This is actually a great advantage! IMO it should be advertised 

_ | FlowCrypt | Gmail
-|-|-
Ability to write emails while offline | :heavy_check_mark: | :stop_sign:

**Comment by tomholub** [comment]
You can write emails but you'll lose them if you close the tab :) because they don't get saved anywhere.

**Comment by limonte** [comment]
> You can write emails but you'll lose them if you close the tab :) because they don't get saved anywhere.

Well, to be precise, "writing emails offline" and "being able to save drafts offline" are two different features :) 

But do I understand correctly that saving draft offline should be doable using `localStorage`?

1. When offline and trying to save, store the message in `localStorage`
2. When online, check `localStorage` for any draft(s) and save them accordingly.

Am I missing something here and things are more complicated here?

**Comment by tomholub** [comment]
It could be done. Gmail could have done this too but didn't - I wonder if the reason is that people would often go looking for the draft on their phone when they get online.. and get disappointed. Or if it's just that the gmail window really needs a connection.

It would be relatively low-pri because drafts are already complicated as they are and I'm hoping to simplify them rather then make them more complicated. On the other hand, if this turns out important for the customer, that would be a different story.

**Comment by limonte** [comment]
> On the other hand, if this turns out important for the customer, that would be a different story.

Gotcha, that makes sence :+1: I've reported the feature-request in #2636 so it won't get lost when this issue is closed.
