### ISSUE TITLE
consider removing featherlight, use SweetAlert2

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2632]
With custom styling.

I don't like the following code in featherlight:

![image](https://user-images.githubusercontent.com/6306961/76166100-d0b62800-6153-11ea-8409-b70071ca033b.png)

I don't see any good reason why would they use eval like that, makes me wonder if they made other bad decisions.

Maybe try to replace one featherlight with a SweetAlert as a test, then we can take a look.

**Comment by tomholub** [comment]
Meanwhile I'll try to refactor it away.

**Comment by limonte** [comment]
> With custom styling.

Does this mean that the current styling should be preserved?

**Comment by limonte** [comment]
Switching to SweetAlert2 is totally possible, I was actually annoyed by inability to close featherlight with keyboard. Esc isn't working once a user started to tab through the popup, and the close button isn't focusable.

**Comment by limonte** [comment]
Considering that `eval` is removed, does this issue still have the first priority importance?

**Comment by tomholub** [comment]
> Considering that `eval` is now removed, does this issue still have the first priority importance?

Great question - not really, but if it sounds fun, feel free to prioritize it.

**Comment by limonte** [comment]
> > With custom styling.
> 
> Does this mean that the current styling should be preserved?

you probably missed this question ^

**Comment by tomholub** [comment]
What I meant is, maybe the "page" type of SweetAlert2 should look a little different than our "modal" type of SweetAlert2. 

Or maybe not?

I'll leave it up to you.
