### ISSUE TITLE
Add ability to save drafts in offline mode

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2636]
It is possible to use FlowCrypt for writing encrypted messages in offline mode. Once online, the message written offline can be sent the usual way.

The only missing thing which might be very inconvenient is that the message draft can not be saved in offline mode and if the user will close tab/browser, (s)he'll lose the data.

In order to fully support offline mode, it should be possible to store drafts in `localStorage` when offline and once the user gets back online, check `localStorage` for saved drafts and store them normally (`ComposeDraftModule.draftSave()`)

**Comment by tomholub** [comment]
The customer indeed showed interest in this. That means this was quite insightful of you to bring it up!

I'm moving this from `discussion` to `Second Priority`.
