### ISSUE TITLE
Long filenames of attachments are overflowing their containers

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2644]
Actual: 

![image](https://user-images.githubusercontent.com/6059356/76502253-626faf00-644c-11ea-949b-0ca40833e2af.png)

Expected

![image](https://user-images.githubusercontent.com/6059356/76502704-343e9f00-644d-11ea-9713-ddbf449cdc87.png)

**Comment by tomholub** [comment]
I would shorten with ellipsis (there is a `Str` method if you wanted to do it in js, or in css) with a `title=` that has the full filename.

**Comment by limonte** [comment]
> I would shorten with ellipsis (there is a `Str` method if you wanted to do it in js, or in css) with a `title=` that has the full filename.

Are you sure about that?

![image](https://user-images.githubusercontent.com/6059356/76504182-e0818500-644f-11ea-8062-4877918c88fe.png)

is more informative than 

![image](https://user-images.githubusercontent.com/6059356/76504225-f68f4580-644f-11ea-908e-be71fdcda5f5.png)

**Comment by tomholub** [comment]
That's true.. but what if the name is 5000 chars long? I feel there should still be some limit, like 100 chars or so. Maybe can combine the two approaches, so that I don't get an essay of a filename, which would be technically possible.

**Comment by limonte** [comment]
> essay of a filename,

Done :+1:
