### ISSUE TITLE
stop using urn:ietf:wg:oauth:2.0:oob:auto before Oct 3

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2649]
> Any reason why the OAuth to Google uses "Programmatic extraction urn:ietf:wg:oauth:2.0:oob:auto" ? The docs from Google says this option is deprecated and should only be used for embedded browsers/web views

> Google OAuth does provide a way to pass OAuth token via postMessage or other safer means

https://cure53.slack.com/archives/GSMB8RGFK/p1583983921015100

**Comment by tomholub** [comment]
We now have a feature freeze for about a month, but afterwards @seisvelas you may look into this since it's actually a security report.

**Comment by seisvelas** [comment]
I wonder if there is some limitation that prevents us from using [implicit grant flow](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow), since [programmatic extraction](https://developers.google.com/identity/protocols/oauth2/native-app#programmatic-extraction) is associated with native apps. Maybe since we're a browser extension, the means used by conventional JS web apps wouldn't work for us?

If we will switch to implicit grant flow, I think we might need to change some of our settings in the Google API Console, per the instructions in the above link.

**Comment by tomholub** [comment]
I think it was related to offline access, which is what was required so that the oauth popup would not come up every two hours or so.

Not entirely sure, murky memory..

**Comment by seisvelas** [comment]
Had we already attempted & found issue with the suggested approach in the Chrome app dev docs: https://developer.chrome.com/docs/extensions/mv3/tut_oauth/

?

I could try that route (tho I'd need you to do some stuff on the admin console), but wanted to see if maybe we already tried and there was a reason that route isn't valid for us.

**Comment by tomholub** [comment]
Same as before, don't really remember what the issue was, best guess is that token renewal or offline access didn't work as expected.

**Comment by tomholub** [comment]
some info about postmessage https://web.archive.org/web/20150317184124/https://developers.google.com/+/sign-in-faq

**Comment by seisvelas** [comment]
Just so we don't forget:

The problem is that alternative methods seem to mostly require a stable extension origin that can be entered into the Google Admin Console. But that isn't currently possible for us because Firefox extension URI's are generated uniquely per client. 

One option is to implement a more modern technique for Chrome clients, and continue to use programmatic extraction on Firefox. This would necessitate creating separate tests for Chrome vs Firefox (which is something we'll likely want to do eventually anyway, so not all bad, but still).

We tried looking into how other extensions similar to FlowCrypt do this and found out the extension we looked into also uses programmatic extraction, likely for the same reasons.

**Comment by seisvelas** [comment]
Another important note: why does this matter?

With programmatic extraction, the token is in the title of the tab, so any other extension with tab permissions will be able to steal that token.

**Comment by tomholub** [comment]
I guess, the first thing to look into is doing a few tests on Firefox. Not the whole test suite, just checking it's not completely broken. Puppeteer I think supports this - but don't know if it supports extensions too. Will make a separate issue.

**Comment by tomholub** [comment]
I guess I can copy it here

Hello Google OAuth Developer,

We're writing to remind you that the OAuth out-of-band (OOB) flow will be deprecated on October 3, 2022, to protect your users from phishing and app impersonation attacks.
What do I need to know?

As we notified you in the first week of May 2022, any affected authorization endpoint requests will be blocked with an invalid_request error after October 3, 2022. Apps using OOB in [testing](https://notifications.google.com/g/p/APNL1ThsWNo8BGNasVb0Z3jpuLg5F5xotZIhFM_vaB4a1aCGPxUHs-HZHF3oolmu0KlvkbLU2g-BM-a3AvZO2kzA6JTBZ7K15-Ya6F2A3--qtwoU7MX1ei92NQC43WgPtPHH3S2ZpTAYc0Aytklt2ndek7ZAJGYVNXPA_w) mode will not be affected. However, we strongly recommend migrating them to safer methods as these apps will be immediately blocked when switching to [in production](https://notifications.google.com/g/p/APNL1TjDiTpLYnVxFH7yM8KcRDhbIuY9VsGVaTqMGPFsEBJcUnGQyfA_mSaQ-GHQjX4WsN0x-ifWKO7wMdeuVF-nrw-xle0j2MPvRDViYdW1RMMOrRfqby-ZwvlWlm6e9sjzI1SRAbPKRp4U8TbHvtxomg3jv3LTP9Z8vO8qDQ) status.

Below are key dates for compliance:

- September 5, 2022: A [user-facing warning message](https://notifications.google.com/g/p/APNL1ThHgh1E6bYTfMirlIMfooONsPm5ImD2M8TACgm_R9jme4boInUPk03138HuM7Y0Y1a8KZfSXWon3mjiAVzcrWE7FMguhNzDIfyMYr75C9nUUWQO-gzHNuTndJhK7vDDZ-2OXOKCbYQWyJLOMxqrJqf3qtfSvXD_h-rRqIc) will be displayed to non-compliant OAuth requests.
- October 3, 2022: The OOB flow will be blocked for all clients and users will see the error page.

Please reference our previous email with the subject line containing: “Migrate your OAuth out-of-band flow to an alternative method before Oct. 3, 2022,” for more details.
What do I need to do?

- Please see the [Making Google OAuth interactions safer by using more secure OAuth flows blog post](https://notifications.google.com/g/p/APNL1ThwQ-XbdBzOOjkHawXXUN8_HqQTBmKx-PcI5QehjdSbQ54svSKQNubToZNojqHTl6OHEiZdZRbWceq7eV-s7MB-QIJwzDDsyLYUpRZs3g9oIhd3mjGaxNZ21FANbJJHIBk9ZYa8CMTBuoxVqQ) to learn about the deprecation
- Follow the [Out-of-band (OOB) Migration Guide](https://notifications.google.com/g/p/APNL1Tj_XiQ68pLOOsUCKPlMvAAV9cQlwT8QHXstAWMGYfFAuPVc2avpJEMJd4FpLXwLYg1VU1OdlRaDQgkagRbq-VjGVrQcogcmNJWIw_TEGCLXCXxBGKfDafrFz8l8t_w2rVum8fGp_QcXNK2h-ogH5HZ_8ZMP) to migrate your app to an alternative method.
- You may acknowledge the upcoming deadline and suppress a possible user-facing warning message by following instructions in our blog post. All non-compliant authorization requests will be blocked with an invalid_request error when loading Google's OAuth 2.0 authorization endpoint after October 3, 2022.
- If necessary, you may request a one-time [deprecation enforcement extension](https://notifications.google.com/g/p/APNL1TiS-zzyslV3MjR-HxUGKRlJVzUtvn7YYmCrLMG32SL6IraADtXxHSzbxGmg3wLmBFnmxZMteqdfLSSGn2CdzNfP2vLzvCfI5TfPkkHDXJFRGkjIucnZ3CyJlik2NLnq2691YB86uEc13c8cRBioratkwLFYDSf_LokLP9G_3t4Sgh2KSuDmNYSUgfAoExVnZhCBlSCQ5I3sqA4WAXO6znsL6k37GNmE5bcZCaNQcg) for each listed OAuth client ID until January 31, 2023. For clarity, the enforcement for the OOB flow deprecation will be enforced on February 1, 2023 with no exceptions or extensions.


Refer to the sample of OAuth clients below, which will be blocked.

Sample OAuth client list:
 - 717284730244-ostjo2fdtr3ka4q9td69tdr9acmmru2p.apps.googleusercontent.com

Thanks for choosing Google OAuth.

— The Google OAuth Developer Team

**Comment by tomholub** [comment]
I didn't see any warnings, but it does apply to our client, unfortunately.

**Comment by ioanmo226** [comment]
@tomholub Could you invite me to `Chrome Developer Dashboard`.
I need to get required info something like `Key`.
And need to check several things.

![image](https://user-images.githubusercontent.com/77344191/186921871-924ecb57-9167-48ad-8915-e744693e8774.png)

**Comment by tomholub** [comment]
Can you share documentation on what this "key" is and whether it is a secret?

**Comment by ioanmo226** [comment]
https://developer.chrome.com/docs/extensions/mv2/tut_oauth/

**Comment by ioanmo226** [comment]
It doesn't seem to be a secret as it's mentioned as pub key

**Comment by tomholub** [comment]
Well, the public key is as follows

```
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgB2GuIuszufxH4YgzDif
6HI/oTii28+qFAv3lU3n/k0rQShwC8D/a1ZV0NLLrqJNWrUNpowOtyKJKT5u33BI
X4GZI8R+805mtgY2tdbSCTjyl4tUxHmqSVnXUu801tVkmfAt7/catr8WWW+uGC3G
F5RoYgDu0jQREkCFL5wko7G3X84ldJqPY/FSWoUt0W01T0PttN8RYXyY4KeihvMt
c9d4u4L1HUp84WhNJ5gJFV/iFUyHU6rf0bW6RpRlm44A649U2B6KdRuR5JiXrCkR
nMlaPLUhQebKKs/Z7tZiOT4z2EPPsH5P+I0lwc8ZaSWyI/Rk0A8Y/gS+mHsCl78w
+wIDAQAB
-----END PUBLIC KEY-----
```

but I wasn't able to find the `key` yet. They say it does into the manifest, but I believe this part is done by google *after* I upload the package to web store. Google does the signing and uses the `key` internally. I don't think they expose it anymore, and belive this part of their docs is outdated.

The goal of what they describe with the `key` is to ensure a stable extension id. We do have that - it's `bnjglocicdkmhmoohhfkfkbbkejdhdgc` for consumer, and various different ids for internal customer deployments. I'd need to ask the customer what the ids are. For now you can just work on the consumer version that uses this id.

Btw it's not safe to assume it's public or not a secret, unless some documentation shows exactly what it is. I would assume it's private, but regardless, I think we shouldn't need it.

**Comment by tomholub** [comment]
We already have a registered app on google console, see:

![image](https://user-images.githubusercontent.com/6306961/186928532-8313de9d-fec3-4c7c-9246-469e34032c08.png)

So if you are trying to follow that guide, the next step would be:

https://developer.chrome.com/docs/extensions/mv2/tut_oauth/#oauth_registration

**Comment by tomholub** [comment]
I can now see that the application id is wrong on above screenshot. I won't edit it since it's production, I'll make a new client id for you.

**Comment by tomholub** [comment]
Ok here you go:

![image](https://user-images.githubusercontent.com/6306961/186929104-ddda43a0-907d-40fe-affa-02a352d128d5.png)


New client id: `717284730244-2m781alo57indm2e78tn7opakm4l7093.apps.googleusercontent.com`

**Comment by ioanmo226** [comment]
Ok
I already followed all guide but I get `chrome.identify` is not defined error.
Someone mentioned this might happen when there's no `key` in manifest.json.
Let me dig more

**Comment by tomholub** [comment]
I see. I think in our case, it's the chrome web store that adds the `key`, not us. I just upload a plain zip with the extension in it, and web store converts that to an actual extension,presumably with the `key` in it. I would also have to dig more to understand this. Could you link to where it says that it's due to missing `key`?

**Comment by ioanmo226** [comment]
https://stackoverflow.com/questions/26399699/chrome-identity-not-available-undefined

**Comment by tomholub** [comment]
Actually, here's a more robust solution: https://developer.chrome.com/docs/extensions/mv2/manifest/key/

![image](https://user-images.githubusercontent.com/6306961/186931516-a43af2c7-5b24-41f2-8aaa-ac22fb3984d4.png)

But instead of manually installing, just install the public extension. Then you should be able to extract the `key` from it from your local files as they describe. Then you enter that into manifest. That will cause dev builds to have the same, consistent id.

**Comment by tomholub** [comment]
And if you can extract the `key` that way, that would mean it's indeed not a secret. Else it wouldn't be so easily accessible to anyone who installs the extension.

**Comment by ioanmo226** [comment]
OK, got it.

**Comment by ioanmo226** [comment]
Just found out why `chrome.identify` is considered as undefined.
For some reason, `identity` permission (which I added in manifest.json) was not added to `build/chrome-enterprise` when I run build command.

After I manually added `identify` permission to chrome-enterprise, it works fine

**Comment by ioanmo226** [comment]
Just found that chrome-enterprise uses separate permissions during build process.

![image](https://user-images.githubusercontent.com/77344191/186947619-4a312857-98a1-426e-bb15-00dcd60ada9f.png)

**Comment by tomholub** [comment]
yes. you can add it there too

**Comment by ioanmo226** [comment]
@tomholub Did you set `redirect_uri` to `https://<extension-id>.chromiumapp.org/` in google dev console?
![image](https://user-images.githubusercontent.com/77344191/187361287-749ce8e3-7692-47a9-a0e4-0ca583603ee0.png)

**Comment by tomholub** [comment]
It didn't give me option to enter redirect url.

Presumably, for chrome apps, google dev console sets it automatically?

![image](https://user-images.githubusercontent.com/6306961/187420911-e57a1cd5-c2af-4732-8e4d-9ece59864ff0.png)

```json
{
    "installed":
    {
        "client_id": "717284730244-2m781alo57indm2e78tn7opakm4l7093.apps.googleusercontent.com",
        "project_id": "cu-nvimp",
        "auth_uri": "https://accounts.google.com/o/oauth2/auth",
        "token_uri": "https://oauth2.googleapis.com/token",
        "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs"
    }
}
```

**Comment by tomholub** [comment]
it does ask for it for web apps

![image](https://user-images.githubusercontent.com/6306961/187421429-a4214896-5770-4145-b741-829bae0f6408.png)

but not for chrome apps

![image](https://user-images.githubusercontent.com/6306961/187421493-20dbb759-c61d-4560-a4da-8a0a94e20354.png)

that leads me to believe it's auto-set

After all, the current `oob` redirect was not set in console either. Just in the app code.

**Comment by ioanmo226** [comment]
OK, got it

**Comment by ioanmo226** [comment]
@tomholub I believe we should create OAuth Client Id for web app (not for chrome app) and start using `launchWebAuthFlow` rather than (chrome.identify.getAuthToken).

Could you create new OAuth Client Id for web app and set authorized redirect uri to `https://<extension-id>.chromiumapp.org/`?

See below post screenshot.
https://stackoverflow.com/questions/40411493/can-chrome-identity-launchwebauthflow-be-used-to-authenticate-against-google-api#:~:text=I%27m%20writing%20a,to%20Chrome%20as.

![image](https://user-images.githubusercontent.com/77344191/187464553-22696d17-dd71-4589-86af-c42f5822aa5f.png)

**Comment by ioanmo226** [comment]
I tried on my local and it indeed is tied to logged in chrome user.

**Comment by ioanmo226** [comment]
However, I have found that there is a lack of documentation for chrome identity api.

**Comment by ioanmo226** [comment]
By the way, Here's another article mentioning about Google OAuth implementation with chrome identity.

https://anobjectisa.com/?p=34#:~:text=Set%20the%20%22Application%20type%22%20to%20%22Web%20application%22%2C%20not%20%22Chrome%20app%22.

**Comment by tomholub** [comment]
Ok. It sort of does make sense that they need a separate "identity" permission in manifest, it's a permission to the chrome-logged-in-identity. Otherwise it would not make sense to ask for a separate permission.

Ok, here. Are you able to use it without a client secret?

```json
{
	"web": {
		"client_id":"717284730244-5oejn54f10gnrektjdc4fv4rbic1bj1p.apps.googleusercontent.com",
		"project_id":"cu-nvimp",
		"auth_uri":"https://accounts.google.com/o/oauth2/auth",
		"token_uri":"https://oauth2.googleapis.com/token",
		"auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
		"redirect_uris":["https://bnjglocicdkmhmoohhfkfkbbkejdhdgc.chromiumapp.org/"],
		"javascript_origins":["https://bnjglocicdkmhmoohhfkfkbbkejdhdgc.chromiumapp.org"]
	}
}
```

**Comment by ioanmo226** [comment]
Yes

**Comment by ioanmo226** [comment]
@tomholub I get below error when trying to get `authorization_code`.
Please send me `client_secret` to my email. I think we need to set this in environment?
> error_description: "client_secret is missing."

**Comment by tomholub** [comment]
Per https://stackoverflow.com/questions/7274554/why-google-native-oauth2-flow-require-client-secret it's not considered a secret for client apps, since that's impossible. So you can add it to code.

`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`

**Comment by ioanmo226** [comment]
Ok, got it.

**Comment by ioanmo226** [comment]
@tomholub I'm getting this error when calling `keys/private` api.
Seems like you need to update google aud claim

> Error: Unauthorized: 401 when GET-ing https://ekm.flowcrypt.com/v1/keys/private (no body): -> authentication: Audience (aud) claim [717284730244-5oejn54f10gnrektjdc4fv4rbic1bj1p.apps.googleusercontent.com] doesn't contain an acceptable identifier. Expected one of [717284730244-ostjo2fdtr3ka4q9td69tdr9acmmru2p.apps.googleusercontent.com, 679326713487-5r16ir2f57bpmuh2d6dal1bcm9m1ffqc.apps.goog...

**Comment by tomholub** [comment]
thats a good sign. will do tomorrow

**Comment by ioanmo226** [comment]
Won't it affect live users if we change google aud claim?

**Comment by tomholub** [comment]
ill be adding another accepted client id. not replacing it. we already have several, for ios android etc. thanks for thinking about it

**Comment by ioanmo226** [comment]
Sounds good.
Please let me know when you add it.

**Comment by tomholub** [comment]
done

**Comment by ioanmo226** [comment]
@tomholub I think we can now unpin this issue?
