### ISSUE TITLE
The filesize of attached files isn't human-friendly enough

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2656]
I just sent the message with a file attached, the filesize was `1226843 bytes`

It was rendered as `1,199KB`, which was confusing to me at the first sight, my eyes interpreted that as `1.2KB`

Proposal 1: improve existing filesize calculation in https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/chrome/elements/pgp_block_modules/pgp-block-attachmens-module.ts#L28

Proposal 2: use existed well-tested solution like https://github.com/avoidwork/filesize.js 

![image](https://user-images.githubusercontent.com/6059356/76645750-42caaa80-6562-11ea-8b9d-2c9256a70a27.png)

**Comment by tomholub** [comment]
filesize looks good to me
