### ISSUE TITLE
refactor setup create key -> backup.htm -> action=finalize flow

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2663]
Currently there will be two redirects during keygen workflow:
1) redirect from `setup.htm` to `backup.htm`
```js
      // only finalize after backup is done. backup.htm will redirect back to this page with ?action=finalize
      window.location.href = Url.create('modules/backup.htm', { action, acctEmail: this.view.acctEmail, idToken: this.view.idToken });
```

2) redirect from `backup.htm` to `setup.htm?action=finalize`:
```js
    if (this.action === 'setup_automatic' || this.action === 'setup_manual') {
      window.location.href = Url.create('/chrome/settings/setup.htm', { acctEmail: this.acctEmail, action: 'finalize', idToken: this.idToken });
```

This is because `backup.htm` has UI and logic that is not the simplest, so it was left on a separate page so as to DRY. Better approach would be to abstract the `backup.htm` logic and UI into a class and a template file that both the `setup.ts` (for setup of extension) and `backup.ts` (for backing up key after setup) pages can use.

That way we don't have to redirect back and forth, everything will simplify, bugs less likely.

**Comment by ioanmo226** [comment]
We can abstract class but what do you mean abstract template file?
You mean abstract html file? Not sure how to do it though.
> Better approach would be to abstract the backup.htm logic and UI into a class and template file

**Comment by tomholub** [comment]
We don't have a good precedent for this, but you can do the following:
 - abstract the typescript logic into a class that can be reused in both places. Place the class in `js/common/ui/backup-ui.ts`
 - take html from `backup.html` and place it into `chrome/elements/shared/backup.template.html`
 - the new `BackupUi` class would have a `async initialize()` method that will load the backup template, as follows: `$('#backup-template-container').html(await (await fetch(htmlUrl)).text())`;

**Comment by ioanmo226** [comment]
Aha, got it.
Thank you for your explanation.
