### ISSUE TITLE
imported public keys should be live-reloaded in compose window

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2666]
1) receive a message with a public key
2) click reply which loads public key (presumably outdated/wrong one)
3) click "UPDATE CONTACT" which imports public key
4) hover over recipient green bubble in the reply form. Currently will show old fingerprint. Should be showing fingerprint of of the key that was just imported.

Should add a mock test.

**Comment by tomholub** [comment]
I keep bumping into this, updated priority

**Comment by limonte** [comment]
@tomholub I'm trying to reproduce the issue, but can't find the mentioned "UPDATE CONTACT" button in the codebase. Has something changed regarding to the steps since you reported the issue (15 Mar)?

**Comment by limonte** [comment]
@tomholub I'll need your technical advise on this one. To live-reload imported public key in the reply iframe it should get some sort of signal from the iframe with the UPDATE KEY button. What are your thoughts on how to achieve that signalling mechanism from one iframe to another? Does something similar already exist somewhere in the codebase?

**Comment by tomholub** [comment]
I think we used to have a broadcast BrowserMsg. Instead of specifying
recipient tab id (eg parent), you would put "broadcast" as the recipient.
Then it should be sent to all. But I don't think we are currently using it,
so you'd have to test if it still works.

**Comment by limonte** [comment]
Thanks! Will check it out.
