### ISSUE TITLE
reply box does not always get replaced (+ warning shows)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2683]
We somehow do this with message replies - when there's an error, a standard message replybox shows.

----------------

![image](https://user-images.githubusercontent.com/6306961/77245803-5092c680-6c19-11ea-874c-bd824300c925.png)

**Comment by tomholub** [comment]
Also, I'm not able to use the plain reply, keeps switching to encrypted. So maybe we didn't handle this yet at all.

**Comment by limonte** [comment]
Oops, apparently I missed something here. I'm on it :+1:

**Comment by limonte** [comment]
Hm, I can't reproduce the issue for example here https://mail.google.com/mail/u/1/#search/pgp%2Fmime+encrypted-asc-inline-encrypted-header+rich-text/WhctKJVjQgpKvxTvRjBcJDqfFvRNQjWRkqCXHqfpDNNCWNcZRQCFMcsMDdSQnHtcqJVWLnb

the secure reply is rendered:

![image](https://user-images.githubusercontent.com/6059356/77246826-9eb4c380-6c33-11ea-9ecd-aa3e4b2eb7d4.png)

Could you provide more details on how to reproduce the issue? Thanks!

**Comment by tomholub** [comment]
To be honest, I'm not exactly sure how to reproduce it myself - it doesn't always happen.

In the situation where it did happen, the conversation contained:
 - encrypted message (collapsed)
 - plain message (collapsed)
 - encrypted message (collapsed)
 - plain message, with some plain text and a quoted encrypted message from before, producing the error in the screenshot (opened)
 - plain reply box and a warning message, but I was not really able to use the plain reply box - once I click it, it would re-render as encrypted reply, clicking "plain reply button" would not help

Maybe we need to observe it longer, see if there is a pattern

**Comment by limonte** [comment]
Thank you for the input, I'll investigate further

**Comment by tomholub** [comment]
Here is another one, this time normal message.

![image](https://user-images.githubusercontent.com/6306961/77347963-8d051600-6d30-11ea-83a3-6d4d84bfe0fd.png)

If I reopen the same message, it works normally:

![image](https://user-images.githubusercontent.com/6306961/77348031-a60dc700-6d30-11ea-91f7-0ffe954b8e6e.png)

Could the new warning sign introduce a race condition causing this?

**Comment by tomholub** [comment]
Again. I'm observing that the warning shows before the encrypted reply box. It appears like it causes the reply box to not want to render if the warning was there first.

![image](https://user-images.githubusercontent.com/6306961/77363835-57215b00-6d4b-11ea-8e7a-a13ecfd6cb0b.png)

Are they being looked for / replaced at a different schedule, maybe?

**Comment by tomholub** [comment]
Schedule is not a problem, based on reviewing the PR again.

**Comment by limonte** [comment]
Was it happening for you in Chrome or in Firefox?

**Comment by tomholub** [comment]
This was on Firefox

**Comment by limonte** [comment]
alright, able to reproduce, here are the steps:

- open any secure message
- click plain reply
- click secure reply (nothing happens here!)
- click plain reply again
- go to inbox
- open the same message

**Comment by limonte** [comment]
The proper fix here would be to fix step 3

> click secure reply (nothing happens here!)

The click on secure reply button should switch the plain reply to secure one, the same as the "Switch to encrypted reply" link

**Comment by limonte** [comment]
Hm, my quick solution with the `keepNextStandardReplyBox` flag is not flexible enough here. The proper switching between plain and secure messages should be done, so users will be able to switch as much as needed.

**Comment by tomholub** [comment]
> Hm, my quick solution with the `keepNextStandardReplyBox` flag is not flexible enough here. The proper switching between plain and secure messages should be done, so users will be able to switch as much as needed.

That's true, and may not be easy to achieve.

I can sometimes reproduce it without switching back and forth, just open a brand new conversation. But fixing switching in general may have a positive effect on this bug too.

**Comment by tomholub** [comment]
Still, on firefox:

![image](https://user-images.githubusercontent.com/6306961/77842422-77a14900-7181-11ea-8f2c-cdf9680dae1e.png)

But clicking the "switch" button does work now - so that's an improvement.

Cannot reproduce, it's intermittent.

**Comment by limonte** [comment]
Roger, thanks!
