### ISSUE TITLE
Invalid CSP used by manifest.json

### ISSUE THREAD

**Issue by wiktor-k** [FlowCrypt/flowcrypt-browser#2693]
Hi,

The browser extension's manifest specifies invalid CSP expression (Chrome warns about it):

```json
  "content_security_policy": "'self'; object-src 'self'; frame-ancestors https://mail.google.com 'self';"
```

The problematic part is the leading `'self'`. Was it meant to be [`default-src 'self'`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src)? If so the `object-src 'self'` directive [would be redundant](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/object-src).

I'd propose a PR to change it but it may have a bigger effect than intended and maybe it should be carefully tested :)

**Comment by tomholub** [comment]
The goal of this CSP, overall, is to prevent click-jacking as discovered by Cure53 in the report.

If the CSP is defined invalid, please do fix it - and then have a look at the report and test the effect of the change on clickjacking as reported, vs having no CSP which was the situation until recently.

Good find!
