### ISSUE TITLE
Write a backend re-auth test (eg when user revokes session)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2703]
Write a backend re-auth test as follows:

1) set up acct
2) Additional settings -> experimental -> Set a new randomly generated FlowCrypt Account UUID
3) open settings, notice modal prompt to re-auth
4) re-auth
5) no more modal in settings

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/2702#issuecomment-605492242_

---------------------------

I'm not entirely sure if our mock backend actually looks at the uuids or ignores them. If it's ignoring them (more likely), we'd have to add functionality where the backend actually saves and remembers uuids.

**Comment by rrrooommmaaa** [comment]
Do I understand correctly that we need to "forget" google API access token to make this call fail?
```
    const storage = await AcctStore.get(acctEmail, ['google_token_access', 'google_token_expires', 'google_token_scopes', 'google_token_refresh']);
    if (!storage.google_token_access || !storage.google_token_refresh) {
      throw new GoogleAuthErr(`Account ${acctEmail} not connected to FlowCrypt Browser Extension`);
```

**Comment by tomholub** [comment]
Nope - the Google authentication stays as is. What you're trying to mess up for this test is the FlowCrypt backend session.

That one is held with email+uuid. By going to `Additional settings -> experimental -> Set a new randomly generated FlowCrypt Account UUID`, you will cause the app to have wrong backend credentials. Once you open settings, you should be prompted to re-authenticate (with google) because that's how the app can get a new OIDC token which it can use to validate a new set of email+uuid with the backend.
