### ISSUE TITLE
run utility to find (and potentially remove) unused methods

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2711]
While doing this, ignore the `core` folder because it includes methods potentially used on other platforms.

**Comment by tomholub** [comment]
reopening per review comment on the PR

**Comment by limonte** [comment]
Unfortunately, I wasn't able to find anything that would help with detecting unused public methods. I checked CLI tools as well as GitHub Actions. 

TypeScript itself doesn't handle that for reasons describe [here](https://github.com/microsoft/TypeScript/issues/16939#issuecomment-313048308) and [here](https://github.com/microsoft/TypeScript/issues/16939#issuecomment-324166134)

We could proceed with making our own tool, but that might take a lot of time and doesn't worth the produced results. I'd personally stop on the progress we've already done here: unused exports + unused variables. 

Let me know WDYT @tomholub

**Comment by tomholub** [comment]
Yup, agree. I may try to remove some code with trial and error. For now, you definitely managed to improve it.

**Comment by tomholub** [comment]
Actually, if there was going to be a too, that's how it could work - randomly removing methods / classes and see if tests still pass. That would take quite a bit of computation. Maybe easier would be to just test if it still builds.
