### ISSUE TITLE
don't show plain warning when replying to signed-only message

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2720]
> I don't like the red notification that says "The last message was encrypted, but you are composing a reply without encryption. Switch to encrypted reply". Not all communication has to be encrypted and I am well aware that I am not writing an encrypted message. Your interface is good enough (and intuitive enough) that such in-your-face messages are not necessary.

You are a bright and knowledgeable user.. not all of our users are.This is a result of us making encryption more accessible - a whole bunch of people who would otherwise not be able to use encryption can use it now, and they span a whole spectrum in terms of their technical abilities, to the extent of not knowing how to attach a file.But we still want even these people to stay secure.

> What makes matters worse is that the mail I am replying to is just signed, not even encrypted.

That's a great point. we'll fix it. There's no need to show the alert when replying to a signed message.

**Comment by limonte** [comment]
@tomholub could you please help me with this one. In the "Reply" button handler, how can I figure out if the correlated `.pgp_block` besides that Reply button is encrypted or not?

**Comment by tomholub** [comment]
Maybe there currently isn't any way. Sometimes the content script that created the iframe already knows that it's a signed message, so maybe it could add a class name to it from there, when it's getting created. It's not very obvious what's the best way to solve it, now that I think about it.
