### ISSUE TITLE
Facebook HTML email not rendering - sometimes

### ISSUE THREAD

**Issue by shawnahall71** [FlowCrypt/flowcrypt-browser#2728]
Hi,

I've noticed over the past several months that the Flowcrypt browser extension no longer renders HTML emails.  Instead after decrypting the email it simply shows me the raw HTML.  Maybe it's something specific to how Facebook sends PGP encrypted emails, but I've tried in both Chrome and Firefox and the HTML rendering functionality doesn't work for me.

**Comment by tomholub** [comment]
Hello,

facebook sometimes sends messages encoded wrongly.

We've debugged it before but Facebook is quite inconsistent with their formatting, so we were not able to have a "bad" sample arranged to be sent to us.

I'll keep this open until we have better tools to debug this.

**Comment by shawnahall71** [comment]
I have two encrypted Facebook messages I left in my Gmail inbox.  If there's a way I can extract those and package those up for inspection, I'd be happy to.

**Comment by tomholub** [comment]
Thanks! Exactly there currently isn't any such way.. we'll have to add something to allow this.

**Comment by shawnahall71** [comment]
For what it's worth, Facebook emails seem to be rendering again.  They're not pretty, but at least they're not raw HTML anymore.

**Comment by tomholub** [comment]
Good to hear. It's hard to say if that was Facebook or us improving something. The rendering being a bit "ugly" is expected - we intentionally don't support rich html, just basic html. Particularly images and remote styles are problematic, as they can be used to track the recipient.

**Comment by shawnahall71** [comment]
That makes sense.  I'll go ahead and close this issue then.
