### ISSUE TITLE
settle on a fingerprint format for s/mime

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2732]
eg in contacts currently:

![image](https://user-images.githubusercontent.com/6306961/79441547-e9bdbe80-7fc6-11ea-9d3a-101eddad5788.png)

Higher priority because it affects items in storage.. better settle it sooner than later.

**Comment by tomholub** [comment]
@wiktor-k I suspect this has been solved - when you get a chance, please document the outcome here, then close. Thanks!

**Comment by wiktor-k** [comment]
Yes, actually I looked at issues assigned to me and I think quite a few of them have been solved. Maybe I'll review them and then get back to the attester (I'm reading sources and doing some small experiments there).
