### ISSUE TITLE
check that cert is a real s/mime cert

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2733]
I tried to give it a HTTPS cert instead, and it happily encrypts for it :thinking: is this expected behavior? The lib doesn't care? In that case, sounds like this is something we should be checking ourselves? (eg in next PR)

```ts
    // todo - unexpectedly works
    // ava.default.only('send non-S/MIME cert - err', testWithBrowser('compose', async (t, browser) => {
    //   const inboxPage = await browser.newPage(t, TestUrls.extensionInbox('test.ci.compose@org.flowcrypt.com'));
    //   let composeFrame = await InboxPageRecipe.openAndGetComposeFrame(inboxPage);
    //   await ComposePageRecipe.fillMsg(composeFrame, { to: 'smime@recipient.com' }, t.title);
    //   const httpsCert = '-----BEGIN CERTIFICATE-----\nMIIFZTCCBE2gAwIBAgISA/LOLnFAcrNSDjMi+PvkSbX1MA0GCSqGSIb3DQEBCwUA\nMEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD\nExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0yMDAzMTQxNTQ0NTVaFw0y\nMDA2MTIxNTQ0NTVaMBgxFjAUBgNVBAMTDWZsb3djcnlwdC5jb20wggEiMA0GCSqG\nSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDBYeT+zyJK4VrAtpBoxnzNrgPMkeJ3WBw3\nlZrO7GXsPUUQL/2uL3NfMwQ4qWqsiJStShaTQ0UX1MQCBgdOY/Ajr5xgyCz4aE0+\nQeReGy+qFyoGE9okVdF+/uJhFTOkK8goA4rDRN3MrSuWsivc/5/8Htd/M01JFAcU\nEblrPkSBtJp8IAtr+QD8etmMd05N0oQFNFT/T7QNrEdItCKSS6jMpprR4phr792K\niQh9MzhZ3O+QEM+UKpsL0dM9C6PD9jNFjFz3EDch/VFPbBlcBfWGvYnjBlqKjhYA\nLPUVPgIF4CVQ60EoOHk1ewyoAyydYyFXppUz1eDvemUhLMWuBJ2tAgMBAAGjggJ1\nMIICcTAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF\nBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFMr4ERxBRtKNI67oIkJHN2QSBptE\nMB8GA1UdIwQYMBaAFKhKamMEfd265tE5t6ZFZe/zqOyhMG8GCCsGAQUFBwEBBGMw\nYTAuBggrBgEFBQcwAYYiaHR0cDovL29jc3AuaW50LXgzLmxldHNlbmNyeXB0Lm9y\nZzAvBggrBgEFBQcwAoYjaHR0cDovL2NlcnQuaW50LXgzLmxldHNlbmNyeXB0Lm9y\nZy8wKQYDVR0RBCIwIIIPKi5mbG93Y3J5cHQuY29tgg1mbG93Y3J5cHQuY29tMEwG\nA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEW\nGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBgYKKwYBBAHWeQIEAgSB9wSB\n9ADyAHcAb1N2rDHwMRnYmQCkURX/dxUcEdkCwQApBo2yCJo32RMAAAFw2e8sLwAA\nBAMASDBGAiEA7Omcf4+uFphcbEq19r4GoWi7E1qvsJTykvgH342x1d4CIQDSCJZK\n3zsVSw8I1GVfnIr/drVhgn4TJgacXx6+gBzfXQB3ALIeBcyLos2KIE6HZvkruYol\nIGdr2vpw57JJUy3vi5BeAAABcNnvK/kAAAQDAEgwRgIhAP7BbIkG/mNclZAVqgA0\nomAB/6xMwbu1ZUsHNBMkZG+QAiEAmZWCVdUfmFs3b+zDEaAF7eFDnz7qbDa5q6M0\n98r8In0wDQYJKoZIhvcNAQELBQADggEBAFaUhUkxGkHc3lxozCbozM7ffAOcK5De\nJGoTtsXw/XmMACBIIqn2Aan+zvQdK/cWV9+dYu5tA/PHZwVbfKAU2x+Fizs7uDgs\nslg16un1/DP7bmi4Ih3KDVyznzgTwWPq9CmPMIeCXBSGvGN4xdfyIf7mKPSmsEB3\ngkM8HyE27e2u8B4f/R4W+sbqx0h5Y/Kv6NFqgQlatEY2HdAQDYYL21xO1ZjaUozP\nyfHQSJwGHp3/1Xdq5mIkV7w9xxhOn64FXp4S0spVCxT3er1EEUurq+lXjyeX4Dog\n1gy3r417NPqQWuBJcA/InSaS/GUyGghp+kuGfIDqVYfQqU1297nThEA=\n-----END CERTIFICATE-----\n';
    //   await pastePublicKeyManually(composeFrame, inboxPage, 'smime@recipient.com', httpsCert);
    //   await composeFrame.waitAndClick('@action-send', { delay: 2 });
    //   await PageRecipe.waitForModalAndRespond(composeFrame, 'error', { contentToCheck: 'dunno', timeout: 40 });
    // }));
```

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/2712#issuecomment-614513053_

```ts
    if (PgpKey.getKeyType(armored) === 'x509') {
      return armored; // todo - check the key parameters, else it may throw later or cause other trouble
    }
```

**Comment by tomholub** [comment]
could also go ahead and:
 - verify the cert email address matches the email the user wants to use it for
 - verify the cert with the CA?

**Comment by wiktor-k** [comment]
>     verify the cert email address matches the email the user wants to use it for

Okay, this is straightforward. But as far as I can see there is no such check for OpenPGP keys? (I tried to add my key to another e-mail address and it didn't complain).

>     verify the cert with the CA?

That's probably easy to do on a low-level but we would have to think about where to get the CA key. Enterprises usually have just one trusted CA. On the other hand browsers have their own sets of trusted CAs but I'm not sure we could get the certs from there...

**Comment by tomholub** [comment]
> Okay, this is straightforward. But as far as I can see there is no such check for OpenPGP keys? (I tried to add my key to another e-mail address and it didn't complain).

Yes, and I kind of wish I did that earlier, hard to backtrack without breaking users.

When adding new tech, I want to do this from the beginning. Thanks for checking :)

**Comment by wiktor-k** [comment]
No problem, actually adding this check now will only prevent adding new contacts with non matching User IDs, old contacts would work fine.

I also think we need more detailed error messages, for example if key cannot be parsed, or doesn't have encryption subkey or something. I saw that the source has something like throwable error messages. I'll check if they can be reused ;)

**Comment by tomholub** [comment]
> No problem, actually adding this check now will only prevent adding new contacts with non matching User IDs, old contacts would work fine.

Attester also holds keys recorded for a certain email address that may actually not include the email in the key, so it's a wider change. Also, for OpenPGP, if we disallow this, I want to give the user very actionable options about what to do (eg import for one of the original emails, give the person instructions about how to fix it, or force-import anyway).

But yes, something like this could be done for now let's say just for the manual imports.

> I also think we need more detailed error messages, for example if key cannot be parsed, or doesn't have encryption subkey or something. I saw that the source has something like throwable error messages. I'll check if they can be reused ;)

Definitely. OpenPGP.js can be relatively specific in their errors, so if we are showing an error as a result of error thrown by the lib, we could include the original err msg in our err msg too.

**Comment by wiktor-k** [comment]
@tomholub could we close this issue? The original one - pasting non S/MIME certs has been resolved and some concerns raised here (using e-mail address from the cert or better error messages) have also been addressed in previous commits so I think we're OK with closing this one. If there are further adjustments needed we can create more specific issues then.

**Comment by tomholub** [comment]
Agree, closing
