### ISSUE TITLE
OrgRule FORBID_STORING_PASS_PHRASE

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2752]
Add OrgRule `FORBID_STORING_PASS_PHRASE` - option to forbid users from saving pass phrase (and instead keep it in session using existing mechanism)

 - [x] update OrgRules class to add org rule `FORBID_STORING_PASS_PHRASE`
 - [ ] use this new orgrule in
     - [x] setup screen: disable setting pass phrase to be stored locally in both manual and automatic flows, both in UX (checkbox `disabled=disabled`) and in the code
     - [ ] settings -> security: disable changing pass phrase settings to remember
     - [x] passphrase entry frame: disable remembering it for later
 - [x] add tests for new org rule for above mentioned scenarios

part of https://github.com/FlowCrypt/flowcrypt-browser/issues/2125

**Comment by rrrooommmaaa** [comment]
> * - [ ] settings -> security: disable changing pass phrase settings to remember

I can't see any "remember" options on security page, only to remove the ones already saved.

So, we're leaving `add_key.htm` unchanged, correct? There is also a `input_passphrase_save` setting on that page

**Comment by rrrooommmaaa** [comment]
> So, we're leaving `add_key.htm` unchanged, correct? There is also a `input_passphrase_save` setting on that page

ping @tomholub

**Comment by tomholub** [comment]
Anytime there is `input_passphrase_save` you'll want to handle it somehow when this rule is enabled.

While the `add_key.htm` file may not need to change, when this OrgRule is enabled, I would probably `.hide()` it's first-ancestor `.line` tag (in typescript probably `render` method) to make sure it doesn't show.

Further, in typescript, ensure we ignore that checkbox even if it was present and set.

**Comment by tomholub** [comment]
> I can't see any "remember" options on security page, only to remove the ones already saved.

You're right - that page doesn't have any way to switch to "remember", it's just the pass phrase entry form (and setup / key import forms) that have it.

**Comment by tomholub** [comment]
> when this OrgRule is enabled, I would probably .hide() it's first-ancestor .line tag (in typescript probably render method) to make sure it doesn't show.

This is not really needed, since I forgot to mention this in the original issue (and may need to tailor-hide different elements in each page). It would just be a bit neater. Could do sometime in the future, after other issues, too.
