### ISSUE TITLE
test for searching contacts when accessing Secure Compose from Gmail

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2787]
We need a test for searching contacts when accessing Secure Compose from Gmail. The IDBCursor does not like async to be mixed while a transaction is ongoing.

![image](https://user-images.githubusercontent.com/6306961/84515720-5cdc6c00-acbc-11ea-8e05-e31192fe8f6b.png)

Earlier this was passing all tests, meaning we are not testing this.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/2739#issuecomment-643314900_

**Comment by rrrooommmaaa** [comment]
@tomholub Do you want me to send 2 messages to background page, ContactStore 'search' and 'update' and see if they clash?

**Comment by tomholub** [comment]
Sorry for the bad issue description - you can simply pull up a Secure Compose (but in Gmail itself) and test searching for one contact. 

Eg you could copy test `compose - can load contact based on name` but make it run also as live Gmail test.

**Comment by tomholub** [comment]
Very sorry - I'll close this issue instead, as I'm not sure we can design a test that meaningfully addresses the difference (there are some puppeteer limitations - cannot directly interact with a Secure Compose frame inside page on a different domain).
