### ISSUE TITLE
Unable to recover an account in Firefox

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2804]
### Steps to reproduce:

1. Reset FlowCrypt account (Settings -> Additional -> Experimental -> Reset)
2. Recover FlowCrypt account

### Expected behavior

Ability to recover account in Firefox

### Actual behavior:

![image](https://user-images.githubusercontent.com/6059356/85932750-7c3be180-b8d7-11ea-8a5c-d6d8e7fa233a.png)

---

The issue is happening here: https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/common/platform/store/contact-store.ts#L131

`Contact.pubkey` is `Key` which can't be cloned by Firefox. 

> I think there are only two suspects to why [structured clone](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) fails: `checkPassPhrase` (it's a function) or symbols on the object. My casual skim over MDN suggests it's the former - and that's good because I wanted to move this function to a helper, static function anyway.

I tried removing checkPassPhrase and it doesn't seem to help, so the internal public key symbol is most probably the cause.

**Comment by tomholub** [comment]
This could possibly be outcome of #2731. I haven't dissected it yet but it's quite likely, I don't recall testing the PR on Firefox.

I'll wait with releasing 7.8.0 until this has also been addressed, so that it doesn't affect users.

**Comment by tomholub** [comment]
Here is limonte's fix that made it work: https://github.com/FlowCrypt/flowcrypt-browser/commit/8692e2dcc720e1a62e87c97146c8211202f13178

I did not end up merging it, will leave up to Wiktor to decide.

**Comment by tomholub** [comment]
(it's Sunday now, family time - notes here are of course "for later")

**Comment by wiktor-k** [comment]
> (it's Sunday now, family time - notes here are of course "for later")

Haha, great, thanks for your understanding :-D I see limonte did some debugging earlier so this will be easier, see you soon!

**Comment by tomholub** [comment]
Thank you both, I'll do a full release on Firefox (not so many users) and a 1% release on Chrome.
