### ISSUE TITLE
Russian letters are omitted in attachments

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2813]
Steps to reproduce:

1. Create a file with `привет_мир.txt` filename
2. Attach it to encrypted message:

![image](https://user-images.githubusercontent.com/6059356/86030546-4add2600-ba3d-11ea-830a-a26db5737696.png)

3. Send

### Expected result

![image](https://user-images.githubusercontent.com/6059356/86030608-5f212300-ba3d-11ea-92e9-e3cfa02e4bff.png)

### Actual result

![image](https://user-images.githubusercontent.com/6059356/86030625-647e6d80-ba3d-11ea-8d90-ab689429d04c.png)

@tomholub not sure if this is a dup of #2809 if so, feel free to mark as duplicate and close this one.

**Comment by tomholub** [comment]
It probably is a duplicate. The other one was specifically for password protected messages, but it looks like the issue happens on both types, so it will be good to test both types.
