### ISSUE TITLE
Get rid of "Save Link As..." (research) 

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2820]
The "Save link as..." bothers me quite a bit in general, but it's what I've done to work around browser restrictions (which only started popping up in browsers about 1 year ago). I hope to one day re-visit it and see if it can work without it., like before, by just clicking it, then waiting for the download.

At one point it stopped working in Gmail but still worked in flowcrypt inbox, suggesting it's a restrictions on frames inside host pages on different origin.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/2418#issuecomment-568164135_

**Comment by limonte** [comment]
Also from https://github.com/FlowCrypt/flowcrypt-browser/pull/2778#issuecomment-642105118

> ** NOTE : But the problem here is that we have a cumbersome "right click" instructions in place. Best would be if we could get rid of that. I think I did that to address restrictions either in Chrome or FF - forgot. I also recall that there may have been a workaround - on download, open a new tab, where auto-downloads are allowed unlike from an iframe. So when I click download (left-click), it could open frame - save the file - close the frame and I'd end up where I started. Architecting this may involve some futile efforts and blind streets, but it would be extremely nice to have this streamlined.

**Comment by tomholub** [comment]
Note - this is a slightly riskier endeavor, so I would not be merging it during the feature freeze. But research is welcome, and since we don't expect any major changes or refactors during feature freeze, you should not encounter merge conflicts later if we let the PR wait a bit.

**Comment by limonte** [comment]
> endeavor

Of course, I'm not anyway taking anything meduim/big that wasn't prioritized by you first.
