### ISSUE TITLE
Draft opens in regular plain text editor, instead of Secure Compose editor

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2822]
First, I create a message but don't send it, so it gets saved as a draft:

![Screenshot_2020-07-04_10-44-38](https://user-images.githubusercontent.com/44826516/86516139-ce06cf00-bde3-11ea-9dd1-9ca9440ab1e8.png)

I close the Secure Compose editor and click on the draft. But instead of opening in the Secure Compose editor, the ciphertext is opened in a plaintext Gmail editor:

![Screenshot_2020-07-04_10-45-30](https://user-images.githubusercontent.com/44826516/86516186-10c8a700-bde4-11ea-9e5a-fed7ed4471ec.png)

**Comment by limonte** [comment]
This is happening in Chrome only:

![s7nYWUYIXY](https://user-images.githubusercontent.com/6059356/88977516-ba596600-d2c6-11ea-976a-1c30eb5ac285.gif)

The draft for some reason doesn't have the expected `[cryptup:link:draft_compose:r-xxxxxxxxxxxxxxxxxxx]` fomat.

**Comment by tomholub** [comment]
@Aldekein you could actually send these drafts to yourself using the plain Gmail interface, which should allow you to then decrypt them.

**Comment by tomholub** [comment]
Meanwhile we will be releasing a fix for future messages soon.
