### ISSUE TITLE
option to generate another key

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2865]
could be added as an option here

![image](https://user-images.githubusercontent.com/6306961/88327453-97eba980-cd16-11ea-8da5-dcbcb80d6ce1.png)

Sometimes people actually need an RSA key, when the default is ECC. It's too complicated to guide them through other methods of making another key.

**Comment by tomholub** [comment]
This user would also find it useful

https://mail.google.com/mail/u/8/#inbox/FMfcgxwJWhtvcbVqzKLkJxrfjvKkTSfp

**Comment by sosnovsky** [comment]
fixed in https://github.com/FlowCrypt/flowcrypt-browser/pull/5823
