### ISSUE TITLE
Your platform is not supported: browser does not support extension windows

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2868]
Support email: https://mail.google.com/mail/u/5/#inbox/FMfcgxwJXBxClhPwpkBpKbtFhXPhcjnJ

According to the user:

> When I initiate a secure email from Gmail in FireFox I get the following two messages.  Any ideas?  The second screenshot occurs after hitting the "Go" green colored button.  I also notice that it self propagates my email address into the recipients list.
> Thanks!

![backend](https://user-images.githubusercontent.com/44826516/88360441-502b4900-cd3b-11ea-9d74-a682cbac2683.png)

![window](https://user-images.githubusercontent.com/44826516/88360462-61745580-cd3b-11ea-9394-3929098cecb7.png)

I'm unable to recreate the issue. 

I sent a response soliciting some more info which may help

**Comment by tomholub** [comment]
No clue whatsoever why would this happen. Plus we don't have any "Go" button I know of.

A good thing to try is for him to reinstall on a fresh browser, with clean settings and no other extension. Does it still fail? This is a good thing to try with any similarly weird behavior.
