### ISSUE TITLE
japanese encrypted email decoding issue (likely UTF issue)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2870]
the data to test with available at https://github.com/FlowCrypt/flowcrypt-issues/issues/14 (ask for access if you don't have)

customer: https://mail.google.com/mail/u/8/#inbox/FMfcgxwJWhrfdffKRSHtcdDpCzsFjgzr

**Comment by tomholub** [comment]
It would be good to use this data to create an automated test, and then see if it passes or needs fixing.

**Comment by yuakihiro** [comment]
in 7.8.8 decode is ok.
already fixed issue?

**Comment by yuakihiro** [comment]
but

> FlowCrypt ERROR: Please report errors above to human@flowcrypt.com. We fix errors VERY promptly. webmail_bundle.js:116:29

**Comment by tomholub** [comment]
> in 7.8.8 decode is ok.
> already fixed issue?

Possible - about a month ago, we have done some improvement to utf parsing - https://github.com/FlowCrypt/flowcrypt-browser/pull/2783 - this could have fixed it. I think it was related to Japanese.

> but
> 
> > FlowCrypt ERROR: Please report errors above to [human@flowcrypt.com](mailto:human@flowcrypt.com). We fix errors VERY promptly. webmail_bundle.js:116:29

Could you show us a screenshot of this? Any error in the browser error console?

**Comment by yuakihiro** [comment]
![image](https://user-images.githubusercontent.com/66588792/88436788-ff514880-ce3f-11ea-8ecb-3fc8ecd954c6.png)

**Comment by tomholub** [comment]
Thanks, created a separate issue for that.

**Comment by yuakihiro** [comment]
this (original) issue may be pgp-mime related i suppose.
because simular japanese message is ok
