### ISSUE TITLE
"To start using FlowCrypt click button in the corner" but button doesn't do anything on that page

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2874]
On the page that says "To start using FlowCrypt click button in the corner", if I click the button, nothing actually happens. 

![simplescreenrecorder-2020-07-24_18 41 10 (online-video-cutter com)](https://user-images.githubusercontent.com/44826516/88443422-e1eb9280-cddd-11ea-8c9b-7a074e15cf5f.gif)

To set up I have to browse to Gmail, at which point clicking it will say 'Setup FlowCrypt', and I can move forward.

Everything works fine, but I think it's confusing that on the page telling me to click the icon, clicking the icon does nothing.

**Comment by limonte** [comment]
Looks like the duplicate of https://github.com/FlowCrypt/flowcrypt-browser/issues/2854

Should be fixed in https://github.com/FlowCrypt/flowcrypt-browser/commit/a5d8d1efcdb1ccbea46d439bb4c080661cbc3639

**Comment by seisvelas** [comment]
Sorry, hadn't seen that. Thanks!
