### ISSUE TITLE
FlowCrypt incompatible with Google Advanced Protection

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2877]
I learned about this from uninstall feedback: https://mail.google.com/mail/u/5/#inbox/FMfcgxwJXCJQNzxKltWwrBhwVRCcWplV

Link to Google Advanced Protection: https://landing.google.com/advancedprotection/

> The Advanced Protection Program safeguards the personal Google Accounts of anyone at risk of targeted attacks – like journalists, activists, business leaders, and political campaign teams.

I can't immediately test this to verify the incompatibility or test for what supporting this would entail, because using this feature requires purchasing certain hardware. Specifically:

* Yubico FIDO U2F Security Key
* Feitian MultiPass FIDO Security Key

I'm happy to acquire these tools if this is something we're interested in supporting. It sounds cool, though I don't know how difficult it would be for FlowCrypt to support it.

**Comment by tomholub** [comment]
Here, a duplicate: https://github.com/FlowCrypt/flowcrypt-browser/issues/1325

The issue is that Google then starts blocking 3rd party apps, so we would have to apply for a special status.
