### ISSUE TITLE
"Key type is unknown, expecting OpenPGP or x509 S/MIME" when user tries to load key that used to work

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2880]
From support email: https://mail.google.com/mail/u/5/#inbox/FMfcgxwJXCFxBkWGRqtGkRHNfMXGbVzk

> Wrigglesworth Enterprises had our email encryption working through our GSuite account using the FlowCrypt add on and a key which we believe was issued by ORC. This setup worked flawlessly until around 7/20/2020, when the emails stopped decrypting as expected, and we now receive this error message:
> 
> "Could not open this message with FlowCrypt.
> 
> Normally, messages are encrypted for at least two people (sender and the receiver). It seems the sender encrypted this message manually for themselves, and forgot to add you as a receiver. This sometimes happens when the sender is using OpenPGP software other than FlowCrypt, because they have to configure encryption manually, and mistakes can happen.Please ask them to send a new message."
> 
> I have checked in the back end of the FedMall website, where part of our key is loaded, and nothing has changed from when the emails were being decrypted. This is the only source of encrypted emails we were using the key to decrypt.
> 
> Has anything changed in the FlowCrypt process that would have eliminated our key? We have tried loading the key back as we believe it was previously loaded, but we get this error:
> 
> "This does not appear to be a validly formatted key.
> 
> Key type is unknown, expecting OpenPGP or x509 S/MIME"
> 
> Our key and the email decryption was working earlier this month, and suddenly stopped without warning. Has anything changed. Can we fix this problem by upgrading our account? Please advise.

**Comment by seisvelas** [comment]
I don't know of any changes in the last month that would have caused this, but perhaps someone else has an idea?

**Comment by tomholub** [comment]
It's possible we broke it, if user says it used to work.

I see two issues here:
1) he's having trouble decrypting messages
2) he's having trouble importing his private key

The questions we should be asking are:
1) how did he produce his private key - it seems it is imported? Which software was it imported from? Could he create a similar private key for us for testing?
2) Is it possible to send us a test message from the system that is sending him encrypted emails? Based on info here https://flowcrypt.com/docs/help/compatibility.html#incoming-email-from-other-software

**Comment by gregameling** [comment]
End user here. I'm fairly certain that the type of key we were using was from ORC. We use this key to decrypt orders from FedMall, a DLA ordering platform. I actually don't see this key at all in the FlowCrypt account that decrypted the emails, so maybe it was removed for not being a FlowCrypt key(?)

We have access to the back end of the website where we can load in our public key and send test emails, so I know what public key we were using, but I'm not sure if we generated a private key from that public key, or if that's even how it works. But as mentioned previously, this setup was working until 7/20, so hopefully it can be made to work again

**Comment by tomholub** [comment]
> End user here. I'm fairly certain that the type of key we were using was from ORC. We use this key to decrypt orders from FedMall, a DLA ordering platform. 

Understood

> I actually don't see this key at all in the FlowCrypt account that decrypted the emails, so maybe it was removed for not being a FlowCrypt key(?)

This should not be happening. Imported and created keys are treated the same. But if there is indeed a compatibility issue with that particular key, an issue that only surfaced after 7/20, it could be possible that the particular problematic key stopped showing in the software.

> We have access to the back end of the website where we can load in our public key and send test emails, so I know what public key we were using

Understood

> but I'm not sure if we generated a private key from that public key, or if that's even how it works. 

Your software, in your case ORC, generates a keypair - both private and public. The private key goes to FlowCrypt extension, public key goes to FedMall. Typically, the public key can also be extracted from the private key, but not the other way around.

> But as mentioned previously, this setup was working until 7/20, so hopefully it can be made to work again

The most reliable way for us to diagnose this issue would be to try a similar private key, and test with it. Would you be able to generate one more for us, using ORC for testing, and share that with us?

**Comment by gregameling** [comment]
We were able to resolve the issue by switching to Mailvelope. We identified the right key, and attempted to install it into FlowCrypt, but it did not work. The Mailvelope add on did work, so we don't need to use FlowCrypt until Mailvelope breaks. Thank you for looking into this issue and for all your support.

**Comment by tomholub** [comment]
Understood. I'm happy you found a workable setup. Sorry for the trouble.

What exactly was the "ORC" software you mentioned? I tried to look it up but couldn't:

https://www.google.com/search?hl=en&ei=w2IyX6SaGKOBhbIP09OqkAI&q=ORC+openpgp&oq=ORC+openpgp&gs_lcp=CgZwc3ktYWIQAzoLCC4QxwEQrwEQkwI6AggAOgQIABAKOggIABAIEA0QHlDOygFYrM8BYP3YAWgDcAB4AoAB0gGIAdAKkgEFMC43LjKYAQCgAQGqAQdnd3Mtd2l6wAEB&sclient=psy-ab&ved=0ahUKEwjkh4ic6ZLrAhWjQEEAHdOpCiIQ4dUDCAs&uact=5

That way we can debug it further, for other future users.

If you were to try another attempt, this would be interesting: see if exporting the key from Mailvelope, and then importing into FlowCrypt, will make FlowCrypt accept the key.

**Comment by gregameling** [comment]
Hi Tom,

ORC is this company:

https://eca.orc.com/

I believe they created the certificate we're using, but I'm not positive.
They are a recommended certificate vendor for FedMall, which is why we
chose them. I believe the correct key is now loaded into our FlowCrypt
account, and I believe it's WendyWrigglesworthpk.asc, or at least it was
named that upon upload.

Thanks again for all your help, and the years of decryption.

Greg Ameling

Wrigglesworth Enterprises, Inc.

3516 S College Rd

Wilmington, NC 28412

Office: 910-395-1904 | Fax: 910-395-0026 | Email: greg@wesourceusa.com

GSA 51V: GS-21F-0015X | GSA 84: GS-07F-097GA | MRO: GS-23F-BA014 | JANSAN:
GS-07F-BA399 | DHS PPE: HSHQDC-15-A-00018 | DUNS: 612878772 | CAGE CODE:
4HQD0

**Comment by tomholub** [comment]
I'll close this for now, if we can ever get our hands on a sample to reproduce with, we'll take another look. Thanks for reporting!
