### ISSUE TITLE
warn during import when key unusable for signing or encryption (Missing private key parameters)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2887]
Currently we allow user to import a key if it can be used for at least something (encryption or signing).

We should update `KeyImportUI` to show a warning if a key is not usable for both of these, so that the user is aware.

Further, what happened to the user below may be a common problem. Normally private keys are structured as follows:

1) primary key for signing
2) subkey for encryption

When they use `--export-secret-subkeys`, it will only export the subkey and therefore FlowCrypt was missing a key to do signatures with. We should provide further guidance to the user when we detect this problem during import, with the suggestions I'm mentioning below.

------------------------------------

A few interesting parts in OpenPGP compatibility tests of the affected key:

```
(15) PK 0 > Encrypt/Decrypt test: Encryption with key was successful  
(16) PK 0 > Encrypt/Decrypt test: Decryption with key succeeded  
(17) PK 0 > Sign/Verify test: [-] Exception: Error: Missing private key parameters  
```

It was using the subkey for encryption and decryption, but it seems like it wanted to use the primary key for signing. But the primary key is not present because you used `--export-secret-subkeys`.

This is because your subkey is missing signing key flag:
```
(22) PK 0 > SK 0 > SIG 0 > Key flags: [-] 12  
```
If I'm reading this correctly, you have 0x04 and 0x08 flags (both for encryption) but not 0x02 (signing). This is standard, typically signing is done by the primary key.

So you have a choice of either exporting the full key:
```
gpg --output private-key.asc --armor --export-secret-key your@email.com
```

Or modifying your key to include the signing flag on the subkey, too, then exporting the same way as before.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/2743#issuecomment-674379035_

**Comment by rrrooommmaaa** [comment]
@tomholub 
So I suggest to first add following properties to `Key` interface
1) `missingPrivateKeyForSigning`
2) `missingPrivateKeyForDecryption`

also, if `missingPrivateKeyForSigning === true`, force `usableForSigning` to `false`
and based on these attributes, show a warning.

**Comment by tomholub** [comment]
Agree, that will work.
