### ISSUE TITLE
deprecate fine-uploader

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2889]
We use fine-uploader to add a file upload paperclip icon, and then render the list of uploaded files and retrieve their content.

Fine-uploader further has a bunch of other functionality like uploading to various cloud solution, but we don't use any of that.

As browser support for what fine-uploader does has improved, it's likely not needed anymore. Plus it's deprecated and has a known vulnerability.

Given how little we use of the library, we could either write our own, or create a mini-library with bits copied from fine-uploader, and release that under the same license as the original library.

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/90319453-dd6f5100-df27-11ea-9b12-e30199d86ce4.png)

**Comment by limonte** [comment]
@tomholub just to be clear on this issue: we want to stop using it and replace with another solution, not deprecate as stated in the title, right? 

From the [Wikipedia-article on Deprecation][1]:

> In the process of authoring computer software, its standards or documentation, deprecation is a status applied to software features to indicate that they should be avoided, typically because they have been superseded. Although deprecated features remain in the software, their use may raise warning messages recommending alternative practices, and deprecation may indicate that the feature will be removed in the future. Features are deprecated—rather than immediately removed—in order to provide backward compatibility, and give programmers who have used the feature time to bring their code into compliance with the new standard.


  [1]: http://en.wikipedia.org/wiki/Deprecation

**Comment by tomholub** [comment]
I'd like to get rid of it and stop using it, as you say.

It may be ok to package some parts of it into a smaller library that we continue using, if that's useful, as long as we mark the lib with appropriate license and credits.

**Comment by limonte** [comment]
Today I tried to use [uppy](https://github.com/transloadit/uppy), which seems to be the maintanable, well-tested, customizable solution for uploading files, but unfortunately I wasn't able to integrate it into flowcrypt's project structure which is using the old-school approach of including libraries with `<script>` tags.

I'll continue tommorow with the approach sugested in the description:

> create a mini-library with bits copied from fine-uploader, and release that under the same license as the original library.

**Comment by tomholub** [comment]
We could used that, especially if you can build it without the plugins that we wouldn't be using. Thanks!

I've also changed how we add deps: https://github.com/FlowCrypt/flowcrypt-browser/pull/2888 but it sounds like it would not apply to this one, since they don't have a prebuilt js for us in the npm repo?

**Comment by tomholub** [comment]
To clarify, this will probably mean you will have to include the built js in the lib folder, like we did until now.

Please also add a README.md in the lib folder with exact steps taken to produce the lib file, so that it's easy to upgrade in the future, and eventually we could make that into a script as well.

**Comment by limonte** [comment]
@tomholub refactoring fine-uploader into mini-library will probably take a lot of time. Replacing it with the another solution will be faster but there's a risk of breaking something. I checked https://github.com/pqina/filepond today, their docs are worse than uppy's. So uppy is the best option to replace fine-uploader, but we need to use https://www.npmjs.com/package/@uppy/file-input with it and that plugin doesn't provide the built js file and we won't be able to use it with `<script>` tag.

Here's the simplest possible solution which won't break anything and fix the vulnarability:

1. Fork https://github.com/FineUploader/fine-uploader to the `flowcrypt` org
2. I'll submit the vulnarability patch which is one-liner
3. We build and publish the fixed package to npm, proposed name: `@flocrypt/fine-uploader`

What do you think?

**Comment by tomholub** [comment]
I'm ok with that, if it's indeed easy to fix the vulnerability. I'll go
ahead and fork it

**Comment by tomholub** [comment]
Here https://github.com/FlowCrypt/fine-uploader/invitations
and https://github.com/FlowCrypt/fine-uploader/issues/1

It's indeed the cleanest way to fix this, I assumed it was a more difficult issue without investigating it in detail. Thanks!

**Comment by tomholub** [comment]
published as `@flowcrypt/fine-uploader` on npm :+1:
