### ISSUE TITLE
re-evaluate key wrap/unwrap patterns in OpenPGPKey

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2894]
Unfortunately the pattern of wrapping/unwrapping keys in OpenPGPKey still confuses me.

```
  public static isWithoutSelfCertifications = async (key: Key) => {
    const k = OpenPGPKey.unwrap(key);
    return await Catch.doesReject(k.verifyPrimaryKey(), ['No self-certifications']);
  }
```

```
  public static reformatKey = async (privateKey: Key, passphrase: string, userIds: { email: string | undefined; name: string }[], expireSeconds: number) => {
    const origPrv = OpenPGPKey.unwrap(privateKey);
    const keyPair = await opgp.reformatKey({ privateKey: origPrv, passphrase, userIds, keyExpirationTime: expireSeconds });
    return await OpenPGPKey.wrap(keyPair.key, {} as Key);
  }
```

I'd like to consider either to find a way to have fewer such places, or change the naming, or add some comments for easier understanding.

**Comment by tomholub** [comment]
Maybe wrap, unwrap -> externalLibraryFormatToKey, keyToExternalLibraryFormat.

Verbose, but maybe somewhat clearer

**Comment by tomholub** [comment]
Relatedly, why submit key externally like so: `await OpenPGPKey.wrap(prv, key);` when all attributes on the object will be rewritten anyway (using the Object.assign)? I'll try to refactor it as simply `await OpenPGPKey.wrap(prv);` and see if it causes any trouble.

**Comment by tomholub** [comment]
I now see it has to do with `decryptKey` which changes the actual object. I'll try to find some other pattern here.

**Comment by wiktor-k** [comment]
Yep, the issue is that a small subset of methods modify the underlying OpenPGP object (checking password decrypts key and changes the state).

I've been thinking about that and considered splitting immutable key info from functions that modify key data. Having them in one place is confusing IMHO.

**Comment by tomholub** [comment]
> Edit: one more thing: it would be ideal if we wouldn't have any wrap methods. Just retrieving data from the key and no need to keep the OpenPGP.js object around. Not sure how this could be achieved now but this is something that could be looked upon.

This may get real complex real fast, because ultimately the keys usually end up doing one of two things - encrypting something or decrypting something. For this we need the OpenPGP.js key.

I think it's an ok compromise for now. Thanks for writeup

**Comment by wiktor-k** [comment]
> This may get real complex real fast, because ultimately the keys usually end up doing one of two things - encrypting something or decrypting something. For this we need the OpenPGP.js key.

Yes, I was thinking rather on having something like `KeyInfo` objects that only have key descriptions and basic data (algos, fingerprints, etc.) and `Key` objects for encryption/decryption/signing/verifying. There is a lot of places where we just need key information (like list of keys etc.) and although en/decryption this is the core feature I think it's quite localized to just several places.

Still, what we have now should suffice for the time being :)
