### ISSUE TITLE
option to place signature (footer) at end of email, instead of before quoted text

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2901]
From https://mail.google.com/mail/u/5/#inbox/FMfcgxwJXVDZZfzMqGcLNGdMBkGjPsGf:

> It would be great if there was a preference option to place the signature at the end of the e-mail, rather than before the quoted text.
> 
> Or, just adhere to the gmail preference that is already selected?  They have an option checkbox "Insert signature before the quoted text in replies, and remove the '--' line that precedes it."
> 
> Otherwise, I have to jiggle e-mail replies around because many technical groups discourage "top post" e-mail replies.

**Comment by tomholub** [comment]
I understand the point, but we unfortunately have many similar requests. I'll leave it for later until a paying customer needs this.
