### ISSUE TITLE
test for session lock icon

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2912]
https://github.com/FlowCrypt/flowcrypt-browser/issues/2873

I have fixed the authentication in our live tests, this would be a good thing to test so that we know to fix it in case it breaks again.

**Comment by limonte** [comment]
@tomholub two questions:

1. do I understand correctly the it should be the live gmail test?
2. I can't figure out how to enable that setting to only keep pass phrase in session, could you help me with finding it?

**Comment by tomholub** [comment]
1) Yes I would test this on live, so that we know when Gmail changes and we need to fix it

-------------

2) you may have been trying on a @flowcrypt.com email where this functionality may be disabled. Try a flowcrypt.compatibility account as follows:

settings -> security - you should see the pass phrase section, and you may or may not see the "forget" link depending if browser currently remembers the pass phrase:

![image](https://user-images.githubusercontent.com/6306961/95311487-36e76280-087d-11eb-9040-77c45dea1155.png)

If you see it, then click it, make sure it forgets.

Then go let's say settings -> inbox, and open some encrypted message (enter pass phrase)

![image](https://user-images.githubusercontent.com/6306961/95311734-8d54a100-087d-11eb-93fa-2a74dfbe525d.png)

Now you should be seeing a lock in top right:

![image](https://user-images.githubusercontent.com/6306961/95311791-a0677100-087d-11eb-9e72-751792f9044d.png)

Now you would go to Gmail page to look for the lock there too:

![image](https://user-images.githubusercontent.com/6306961/95312151-19ff5f00-087e-11eb-847d-fa9b29e1ab8e.png)

But it's missing. Sure enough, it's broken. Can see the console:

![image](https://user-images.githubusercontent.com/6306961/95312243-369b9700-087e-11eb-892f-2bbc1812b9e1.png)

**Comment by tomholub** [comment]
This is a recurring problem. It seems the elements around the top right of the screen are too volatile.

We could try something else, like a slim `position: fixed` element on bottom middle of the screen.

**Comment by limonte** [comment]
Thanks a lot for your help here!

> We could try something else, like a slim `position: fixed` element on bottom middle of the screen.

This would be the robust approach and I'll probably go with it. But first I want to check what happened to the selector, because it was fixed quite recently: https://github.com/FlowCrypt/flowcrypt-browser/pull/2908

**Comment by limonte** [comment]
@wiktor-k did you start working on this issue? If not, I'll take care of it.

**Comment by wiktor-k** [comment]
Nope, I'm working on EKM PGP features now, not sure why Tom assigned me here :)

**Comment by limonte** [comment]
Roger, I'll go ahead with it then 👍

**Comment by tomholub** [comment]
I must have been monkey-clicking, definitely re-assigned it in error
