### ISSUE TITLE
The "Getting file info ..." status is applied only for even attachments (2nd, 4th, ...)

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2928]
Actual: 

![image](https://user-images.githubusercontent.com/6059356/91969108-49222e00-ed1e-11ea-9b5e-2cdd892638bf.png)

Expected: the "Getting file info ..." status is applied to all attachments so their alignment won't look broken.

**Comment by tomholub** [comment]
Very unusual, thank you for noticing

**Comment by limonte** [comment]
the spinner is also missing because of its width:

![image](https://user-images.githubusercontent.com/6059356/93392821-1ded2200-f87a-11ea-9fdf-727176a15b56.png)
