### ISSUE TITLE
FlowCrypt can receive encrypted attachments from gmx, but gmx can't receive them from FlowCrypt

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2938]
Ref: https://mail.google.com/mail/u/1/#inbox/FMfcgxwJXpJzPzljLtSSLwvwdxSwCwhV

> When someone send me an encrypted email using gmx with an attachment flowcrypt can decrypt and read that email and can separately download  attachment as decrypted attachment (as gmx encrypt the text and attachment in single asc file and flowcrypt can separate the attachment and text) but when I reply the email with text and attachment, it's received at gmx separate encrypted text and separate encrypted attached file. Gmx decrypt the text while file remain encrypted and unreadable. Is there any solution for that at flowcrypt end?

**Comment by tomholub** [comment]
Unfortunately, not really, at least not at the moment.

GMX seems to not support separately attached files. Unfortunately Gmail API does not support encoding the attachments inside the encrypted part.

So either Google or GMX would have to add compatibility for this to work.

**Comment by tomholub** [comment]
followup #3032
