### ISSUE TITLE
After clicking "Forward" the "Recipients" input field should be focused

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2941]
### Steps to reproduce

1. Open any encrypted message
2. Click "Forward"

### Actual behavior 

The focus is in `#input_text`

### Expected behavior 

The focus is in `#input_to`

**Comment by tomholub** [comment]
Agree, I thought we had this and I thought there was a test for it

**Comment by limonte** [comment]
@tomholub When clicking "Forward", here https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/chrome/elements/compose-modules/compose-render-module.ts#L249 `this.view.replyParams` is:

```
bcc: []
cc: []
from: "limon.monte@gmail.com"
subject: "Fwd: pdf"
to: ["limon.monte@gmail.com"]
```

Expected by me would be:

```
bcc: []
cc: []
from: "limon.monte@gmail.com"
subject: "Fwd: pdf"
to: []
```

Is my expectation correct? If so, I'll be investigating `GmailParser.determineReplyMeta()`

**Comment by tomholub** [comment]
The existing params are correct for replies, but look wrong for forwards. The second one is good for forwards.
