### ISSUE TITLE
Network error on Chrome for extension version 7.9.0

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#2942]
Ref:  https://mail.google.com/mail/u/1/#inbox/FMfcgxwJXLfpcSJQvTxMBvHZnhbhNvSL

> I have been using your FlowCrypt for awhile now without issue, but recently I have received the following message when using Chrome as my web browser for Gmail:
> 
![neterr](https://user-images.githubusercontent.com/44826516/93007365-02a6ad80-f52e-11ea-83e9-c3c4665c219f.png)
> 
> 
> I added the FlowCrypt extension to Firefox and the process works without any issues.  So, I don't believe there is anything wrong with my network.  Is there a solution to using Chrome again or am I just needing to switch to Firefox as my main browser?
>
>Below is the information from my system which you requested.  Also, the last time I tested FlowCrypt with Chrome it gave me the error message I provided you earlier but it also sent the email.  Not sure if that helps.

**Comment by seisvelas** [comment]
I created this issue here because I'm not sure how to move forward in diagnosing this. 

Very open to suggestions!

**Comment by tomholub** [comment]
Getting the contents of the error console will help. Alternatively, if nothing, also see the network tab.

This issue is very important to hunt down.

Finally could ask him to try on a fresh Chrome installation - sometimes other extensions or settings may be interfering.

**Comment by tomholub** [comment]
This was the problem. We should find a way to detect this situation and show the right help to the user.

chrome://extensions/?id=bnjglocicdkmhmoohhfkfkbbkejdhdgc

![image](https://user-images.githubusercontent.com/6306961/93106998-8b455b00-f6a0-11ea-9154-be085509c3e9.png)

**Comment by tomholub** [comment]
The actionable step here is to:
 - add a page to flowcrypt.com/docs that explains why and how these toggles should be left allowed.
 - append the following to the error message: `\n\nThis may also be caused by <a href>missing extension permissions</a>.`
