### ISSUE TITLE
chrome changed behavior after install, update confusing instructions

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2951]
(this is for after the PDF/attachments issue)

When we first install flowcrypt, it looks like this on recent versions of Chrome:

![image](https://user-images.githubusercontent.com/6306961/93709806-ea87ed00-fb30-11ea-922f-6ac9b2074536.png)

Notice there is no FlowCrypt action button.

I have to click the extension icon instead to see FlowCrypt:

![image](https://user-images.githubusercontent.com/6306961/93709826-12775080-fb31-11ea-836b-1c5bf17570d6.png)

Then I would have to click the "pin extension" button.

Please see if there's a way to force chrome to always show the action button without user interaction. If not, we should update the splash/initial screen instructions to reflect these steps better (I myself have struggled for minutes the first time I saw this, so I can't imagine what some users must be going through).

**Comment by limonte** [comment]
Starting from Chrom 76 it's impossible to automatically pin extensions anymore, here's the detailed answer on that decision https://groups.google.com/a/chromium.org/g/chromium-extensions/c/rOso__zU_sM/m/UTxbb5gnAgAJ

Proceeding with 

> If not, we should update the splash/initial screen instructions to reflect these steps better (I myself have struggled for minutes the first time I saw this, so I can't imagine what some users must be going through).
