### ISSUE TITLE
Upgrade puppeteer

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#2953]
In order to test against the `latest` (or at least `latest-1`) Chromium we should use the latest puppeteer.

This will prevent bugs like #2952 The download button was working when it was implemented but stopped working for Chrome v83. We would notice it much earlier if we'd be using the latest Pupeteer:

![image](https://user-images.githubusercontent.com/6059356/93720461-cd373b00-fb91-11ea-8ebf-fb8d9fbfac7a.png)

**Comment by tomholub** [comment]
I had problems many times with upgraded puppeteer due to Google login page. But now that we have switched the login to be delegated to Auth0, maybe we can finally upgrade puppeteer.
