### ISSUE TITLE
allow signing of outgoing s/mime emails

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2970]
dependent on https://github.com/FlowCrypt/flowcrypt-browser/issues/3530

**Comment by tomholub** [comment]
It would be great to do this one after https://github.com/FlowCrypt/flowcrypt-browser/issues/3530 

However if other things should be done first, I'll leave it up to you - with the goal to do this issue whenever all issues leading up to it were settled. Thanks!

**Comment by hotzen** [comment]
this issue is still listed as being relevant for missing/limited S/MIME signing support here: https://flowcrypt.com/docs/technical/feature-availability.html

Is S/MIME signing still an issue?
