### ISSUE TITLE
Search through encrypted mail using Gmail search bar

### ISSUE THREAD

**Issue by codekittie** [FlowCrypt/flowcrypt-browser#2976]
A customer brought up a really good point!

>When I use the search mail feature in Gmail searching for message contents, it doesn't return encrypted messages that contain the search term.  Is that because Gmail's search feature can't access the unencrypted text?  Is there a solution for this problem?  Is there a Flow Crypt application I can load on my computer that allows me to search contents of encrypted messages?  Thanks.

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwJXxvNzGNdSTdjtplnWLgZdcpn

**Comment by tomholub** [comment]
I would do this if an important customer brought this up. I agree it would be useful. But if we were to do it well, there would have to be a local index of this stuff.. which you'll need to encrypt.. it's all doable but it can get complex. So I'll make it "not anytime soon"
