### ISSUE TITLE
when replying to signed message, the reply box wording is mismatched

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2979]
Before activating compose box it says "Encrypted" 
![image](https://user-images.githubusercontent.com/6306961/94369029-e5014880-00d6-11eb-873d-807364d29ca5.png)

But once clicking, it is actually signed:
![image](https://user-images.githubusercontent.com/6306961/94369035-edf21a00-00d6-11eb-8108-0e27c110868c.png)

We should change the wording of the "Encrypted" maybe to simply "Secure"

**Comment by limonte** [comment]
@tomholub just to clarify. The "Secure" label should be shown only in cases of replying to signed messages, not always. Right?

**Comment by tomholub** [comment]
I just figured show "Secure" for both, which is the easiest change (no code is better then some code!)

**Comment by limonte** [comment]
> I just figured show "Secure" for both, which is the easiest change (no code is better then some code!)

"No code" is the easiest to maintain! :)
