### ISSUE TITLE
Firefox: unclear settings opening when already open in another tab

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#2998]
1) click browser extension icon -> settings (settings load)
2) click on another tab, leave settings in background tab
3) click browser extension icon -> settings (settings page reloads in background, but does not get switched to)

Ideally in step 3 it would change tabs so that the user finds themselves in the settings again

should also test on chrome

**Comment by tomholub** [comment]
Yan will have a look at this

**Comment by yantakus** [comment]
@tomholub, I can't reproduce this behavior in FF. Either the description is not correct or I'm doing something wrong. Please, record a video if it still can be reproduced from your side.

**Comment by tomholub** [comment]
I've sent a video. Since I cannot reproduce it on Chrome, which has 95% of our users, and you cannot reproduce it on Firefox, I'm ok to drop this issue.

**Comment by limonte** [comment]
For the record: the issue is reproducible in the latest Firefox on Windows.

**Comment by tomholub** [comment]
We could transfer the issue to @limonte since you are able to reproduce it on your setup.

Same applies - it's not a horribly important issue, but if it can be fixed without too much effort, we should fix it.

**Comment by yantakus** [comment]
I just wanted to record my screen to showcase how it works on Mac. This is really weird, but today it works the same as on your video - the background tab reloads, but doesn't get focused. Yesterday it was opening another tab. I can't explain this...

**Comment by tomholub** [comment]
Maybe a browser bug (unless your browser just updated)

**Comment by tomholub** [comment]
Since this issue wasn't started on yet, I'll un-assign it and later we can re-assign to whoever has the availability

**Comment by limonte** [comment]
For the record, the cog icon is working as expected, it's bringing the setting tab to the front

![image](https://user-images.githubusercontent.com/6059356/100607705-fdc6ee00-3313-11eb-9922-07f234b4e405.png)

It's when the user clicks the item in the dropdown menu, the setting tab is reloaded, but stays in the background:

![image](https://user-images.githubusercontent.com/6059356/100607944-59917700-3314-11eb-9186-e4f056fa6aaf.png)

**Comment by tomholub** [comment]
Great, that's an important distinction.
