### ISSUE TITLE
The "Replaced public key record" is being sent without public key record being actually updated

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3002]
I believe this email shouldn't be sent in case when old fingerprint === new fingerprint:

![image](https://user-images.githubusercontent.com/6059356/95618397-a58f1080-0a75-11eb-8fa3-13e666dbedea.png)

**Comment by tomholub** [comment]
Agree. There's an issue for it on Attester: https://github.com/FlowCrypt/flowcrypt-attester-ts/issues/35 so I'll close this one. Thanks!
