### ISSUE TITLE
Unable to run tests locally - remove cookies functionality

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3014]
Hey @tomholub 

I can see a lot of work you've done on tests recently. Did I miss something important because today I'm unable to run tests locally, each test gets stuck on this screen:

![image](https://user-images.githubusercontent.com/6059356/95752512-c8553b00-0ca8-11eb-9629-5b7ddb6127ee.png)

**Comment by tomholub** [comment]
I'm not sure what broke it, but it was probably me since I indeed did a bunch of work on the tests.

But it seems to be failing on functionality I wanted to remove anyway. I'll try to remove it, then we'll know for sure.

**Comment by tomholub** [comment]
In case you are using incremental builds, try to build it with a full build at least once. That may help.

**Comment by limonte** [comment]
> In case you are using incremental builds, try to build it with a full build at least once. That may help.

That helped indeed! Thank you, sorry for the false alarm!
