### ISSUE TITLE
Secure Compose button doubled

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3025]
Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKhqlZCqPtwQcPnBWTpXjnPflZ

> Hi all! I just have a question about the Secure Compose button. I have two of them on this account -- one above the regular compose button and another one just above the Inbox button in the sidebar. 
> 
> Also, the Secure Compose buttons (both of them) display the Google "plus" sign rather than the FlowCrypt symbol.
> 
> I also have FlowCrypt in my personal Gmail and it doesn't look the same. In that account the Secure Compose button displays the FlowCrypt symbol and there's only one of them above the standard Gmail compose button (although when I first added the extension there were two as well -- the one in the sidebar just kind of disappeared). 
> 
> That's a free account, this one is GSuite.

I requested a screenshot, which they provided, along with some additional info:

![newgsuite](https://user-images.githubusercontent.com/44826516/96039046-b224b780-0e2d-11eb-919a-9c295cdb7d8b.png)
 
> Here you go, Alex. It's pretty weird. At one point I cleared my cache and scrolled the sidebar up until it disappeared and reloaded the page and it went away, but now it's back again. 
> 
> I also got two buttons on my standard Gmail, but when I did the scroll up/reload trick it went away and hasn't come back. On that account I have the FlowScript logo in the Secure Compose button -- it was a Google plus sign at first until I did the reload.

**Comment by seisvelas** [comment]
Additional details from user:

> Great, thank you Alex! The functionality is there, just looks weird. If you'd like some extra info, here it is:
> 
>     My browser security includes the uBlock Origin and Privacy Badger extensions
>     Both extensions were enabled on the initial add-on
>     I've tried disabling them and reloading to no effect
>     The scroll/reload trick worked on my Chromebook Pixel laptop but not on my Windows 10 rig
>     On the Chromebook the Secure Compose button still has the plus sign, even though there's only one
>     The business email is a GSuite account, the personal email is standard free Gmail
>     I've checked all settings in both accounts and in the admin settings for GSuite and can't find an issue
> 
> 
> Other browser extensions include HTTPS Everywhere and Flashcontrol, both of which were enabled at the time I added FlowScript. 
> 
> As I've mentioned, the extension appears to be fully functional on both accounts, but I'll run another test to be sure. From what I can see it appears to be a cosmetic problem more than anything else. I'll reply in this thread if the test email reveals any problems.

**Comment by tomholub** [comment]
We had one more important customer with this problem.

So far all sessions seem to be on:
 - chrome
 - windows
 - business email

Chrome is the most common browser and windows is the most common platform, so it's hard to say if it matters.

Maybe Google is updating Gmail layout subtly.

**Comment by tomholub** [comment]
I'm only releasing to 1% of users because of other problems with latest version - #3046

Once approved by google it will be visible as version 7.9.5 at https://chrome.google.com/webstore/detail/flowcrypt-encrypt-gmail-w/bnjglocicdkmhmoohhfkfkbbkejdhdgc/

At that point, customers could delete their existing extension and reinstall, and they'll get the newest version. But it won't auto-update unless I increase rollout (which I'll do on 7.9.6 once the above mentioned issue is fixed).
