### ISSUE TITLE
clearly show usage flags in compatibility screen

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3027]
Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwJZJSxwPpgDZjjvpMDWzhVRBjw

> I have just received the following after passing my GPG private key:
> 
> This looks like a valid key but it cannot be used for encryption. Please write at human@flowcrypt.com to see why is that.
> 
> Could you kindly help me understand what's the problem?
> Private GPG copied with the following command: $ gpg --armor --export-secret-key [REF]
> GPG generated with the following command: $ gpg --default-new-key-algo rsa4096 --gen-key

I requested the user put the key in compatibility.htm and report the results, which they did:

> (1) Primary keys found: 1  
> (2) ----- Testing key 0 -----  
> (3) PK 0 > Key type: [-] openpgp  
> (4) PK 0 > Is Private?: [-] true  
> (5) PK 0 > User id 0: [-] [REDACED]
> (6) PK 0 > Primary User: [-] [REDACED]
> (7) PK 0 > Fingerprint: [-] [REDACED]
> (8) PK 0 > Subkeys: [-] 0  
> (9) PK 0 > Primary key algo: [-] rsa_encrypt_sign  
> (10) PK 0 > key decrypt: [-] true  
> (11) PK 0 > isFullyDecrypted: [-] false  
> (12) PK 0 > isFullyEncrypted: [-] true  
> (13) PK 0 > Primary key verify: [-] valid  
> (14) PK 0 > Primary key creation?: [-] 1601566359 or 2020-10-01T15:32:39.000Z  
> (15) PK 0 > Primary key expiration?: [-] 1664638359 or 2022-10-01T15:32:39.000Z  
> (16) PK 0 > Encrypt/Decrypt test: Got error performing encryption/decryption test: Error: Error encrypting message: Could not find valid encryption key packet in key 1f8d189539e41ae3:   
> (17) PK 0 > Sign/Verify test: [-] skiped, not fully decrypted  
> (18) PK 0 > expiration: [-] undefined  
> (19) PK 0 > internal dateBeforeExpiration: [-] undefined  
> (20) PK 0 > internal usableButExpired: [-] false  

The user is on Brave

**Comment by tomholub** [comment]
The key only has a primary key but no subkey. Typically, primary keys are for signing and verification, and subkeys are for encryption.

Somehow the key he created got exported without the subkey.

Actually, our compaitibility test should be improved to clearly show key "usage" flags, for both primary keys and subkeys. Ideally it would show it as follows:

```
(8) PK 0 > Usage flags: [encrypt_data, encrypt_communication, sign, certify]
```
Or similar, for a primary key and also
```
(8) PK 0 > SK 0 > Usage flags: [encrypt_data, encrypt_communication, sign, certify]
```
For subkey.

**Comment by tomholub** [comment]
I'll go ahead and hijack the issue to improve the compatibility screen.

**Comment by tomholub** [comment]
Unassigned - waiting for legal review
