### ISSUE TITLE
authenticate/ validate plugin?

### ISSUE THREAD

**Issue by xpseudonym** [FlowCrypt/flowcrypt-browser#3035]
how do I know the d/l plug-in is what it should be?
Is there any pgp signing or hashing of the plugins?
Thanks

**Comment by tomholub** [comment]
On Chrome, there is a signature on the plugin that is signed by Google (Chrome Web Store). Therefore, theoretically, Google could serve malicious extensions to chrome users.

On Firefox, Mozilla signs it but we distribute it from our servers, therefore if you worry about the scenario above, Firefox extension is preferred.

**Comment by xpseudonym** [comment]
Many thanks, I figured it would be straight forward - but, also figured I should check :-)
To complete the picture, I tracked down these articles at mozilla.org:
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox
https://wiki.mozilla.org/Add-ons/Extension_Signing
Morgan

**Comment by tomholub** [comment]
Thanks, let's leave it here for future reference.
