### ISSUE TITLE
pgp/mime?

### ISSUE THREAD

**Issue by xpseudonym** [FlowCrypt/flowcrypt-browser#3040]
I'm aware of Issue #3032 
I've just sent some signed only emails and they appear to be pgp inline.
Where do I find settings to implement pgp/mime?
Thank you
Morgan.

**Comment by tomholub** [comment]
Hello, in Firefox (not Chrome) next to the send button you will see a chevron that when you click on it, you'll see option "Rich text - experimental".

When using rich text, the message will be signed and sent as PGP/MIME.
Encrypted message also, but it will not be delivered as PGP/MIME as per the issue you referenced.

**Comment by xpseudonym** [comment]
Ah, thanks.  Got it.
