### ISSUE TITLE
missing pass phrase when opening attachment preview

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3046]
![image](https://user-images.githubusercontent.com/6306961/96416135-21f4c280-11df-11eb-90c5-d8592ce2407f.png)

**Comment by tomholub** [comment]
@limonte please add a test also, this is a good test case

**Comment by tomholub** [comment]
Can be tested by ending your pass phrase session, then previewing an attachment.

**Comment by limonte** [comment]
@tomholub what is the expected behavior?

**Comment by tomholub** [comment]
Similar to what happens when downloading the attachment (at least originally) the standard pass phrase dialog should show up asking for the pp.
