### ISSUE TITLE
text showing very dark in attachment preview

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3053]
![image](https://user-images.githubusercontent.com/6306961/96453541-24204680-120a-11eb-9d10-e292e16f676d.png)

notice the `-----BEGIN PGP MESSAGE-----` on the bottom which was actually the shared text this time.

The filename was something like `testfile.txt.pgp.pgp`

**Comment by limonte** [comment]
regression from my PR https://github.com/FlowCrypt/flowcrypt-browser/commit/fcf73dc42536c8d80abf82b7effea9120f787069 🤦‍♂️
