### ISSUE TITLE
When the "Enter your pass phrase to decrypt a file" closed by backdrop click, spinner stays forever

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3059]
I noticed this issue while working on https://github.com/FlowCrypt/flowcrypt-browser/pull/3057

When the "Enter your pass phrase to decrypt a file" is dismissed by the "Later" button, all is well:

![qj6Xu18Tpr](https://user-images.githubusercontent.com/6059356/96496938-99176e80-1252-11eb-8f41-96bb4aaf74cd.gif)

But when it's closed by the backdrop click, the loader stays forever because the `passphrase_entry` event handler doesn't fire:

![Da1XtfFngz](https://user-images.githubusercontent.com/6059356/96497448-61f58d00-1253-11eb-9d00-b73c134ba325.gif)

**Comment by tomholub** [comment]
Great, I love when you notice stuff like this :+1:
