### ISSUE TITLE
replace removing auth_denied.html|ts with a modal

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3071]
![image](https://user-images.githubusercontent.com/2179726/96745222-904ba780-13ce-11eb-8583-7a038f0239a9.png)
it is used all across the app, that's why I didn't want to duplicate the text.

_Originally posted by @yantakus in https://github.com/FlowCrypt/flowcrypt-browser/pull/3063#discussion_r509405148_

**Comment by tomholub** [comment]
You can address these one by one, giving you a chance to fix up the tests after each change (if needed). It can be one PR (if easy enough) or it can be several.

**Comment by yantakus** [comment]
@tomholub I can't reproduce any of these cases. Could you please help me with the reproduction steps (as [here](https://github.com/FlowCrypt/flowcrypt-browser/issues/2749) for example)?
1) https://github.com/FlowCrypt/flowcrypt-browser/blob/a74b43931075ea5063331197870459dd3777e1f9/extension/chrome/elements/compose-modules/compose-render-module.ts#L61
2) https://github.com/FlowCrypt/flowcrypt-browser/blob/74fc23465059661bcb65aafdfcf68b2c0dd4465e/extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts#L64
3) https://github.com/FlowCrypt/flowcrypt-browser/blob/2ffd45be40f12ea1a22f3df8c5745eccb054ff40/extension/chrome/settings/index.ts#L155
4) https://github.com/FlowCrypt/flowcrypt-browser/blob/9ea1217dcbf6edec4f11c3359f9370b8c5019d09/extension/chrome/settings/setup.ts#L145
5) https://github.com/FlowCrypt/flowcrypt-browser/blob/a74b43931075ea5063331197870459dd3777e1f9/extension/js/content_scripts/webmail/gmail-element-replacer.ts#L289

**Comment by tomholub** [comment]
I'm not aware of any problem with these - I just figured we could take the opportunity to refactor them all away. Since it's just text we're showing, it could be a modal instead of an actual page - less code overall.

Actually, maybe you are saying that you cannot get the extension to this code path.

I think that's a valid point too - a long time ago, we used to allow user to proceed to set up the extension without the `read` permission. They could only send (let's say it's a paranoid user, doesn't want to give read perm). Therefore we had to keep checking for this. The first link is a good example:

```ts
if(this.view.scopes.read || this.view.scopes.modify) {
  .. do the actual thing
} else {
  .. show warning and potentially end up calling auth_denied
}
```

Please help me find all examples where you see this pattern, and refactor it to become:

```ts
... do the actual thing
```

This **only** applies to when we are checking for reading, which is exactly this check you saw: read|modify (modify can also read).

The second example, same thing:
```ts
} else if(this.canReadEmails) {
```
Just assume user can read emails instead.

Finally the last one is the same:
```ts
          if (msgId) {
            if (this.canReadEmails) {
```
so do the same.

Since these three are related, you can do them in one PR if you want. Once merged, I'll have a look how to address the rest.

The goal these days is to try to simplify the codebase, it's getting complex. Thanks!

**Comment by tomholub** [comment]
For the remaining ones: 'action_go_auth_denied' looks to be also no longer needed - I would search for this and get rid of whatever code still uses this, including the html.

3) https://github.com/FlowCrypt/flowcrypt-browser/blob/2ffd45be40f12ea1a22f3df8c5745eccb054ff40/extension/chrome/settings/index.ts#L155

4) https://github.com/FlowCrypt/flowcrypt-browser/blob/9ea1217dcbf6edec4f11c3359f9370b8c5019d09/extension/chrome/settings/setup.ts#L145

**Comment by tomholub** [comment]
Which will allow you to actually remove that page :+1: and just store it as text somewhere.

**Comment by yantakus** [comment]
There's one more usage: https://github.com/FlowCrypt/flowcrypt-browser/blob/a74b43931075ea5063331197870459dd3777e1f9/extension/chrome/settings/modules/backup-status-module.ts#L20

Is it needed?

**Comment by tomholub** [comment]
I'd search for action_go_auth_denied everywhere and get rid of all of them, this one included, and in html too.
