### ISSUE TITLE
rich text messages drafts are broken

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3082]
1) create a new secure message **on Firefox**
2) switch to rich text (pgp/mime) - must be on firefox, then click the "chevron" icon next to send button, and choose `rich text (pgp/mime)`
3) start composing, a draft will get saved
4) close the window
5) open the draft

It's broken. The issue is on the opening side, not recognizing the draft. It's possible the sending side will still have to be improved, too - normally we add "draft tags" that make the content script recognize it's a draft when opening.

![image](https://user-images.githubusercontent.com/6306961/97070394-83de6f00-15c7-11eb-8f5d-5ba6cad15211.png)

**Comment by vnikolaou** [comment]
I am not sure what file to install on Firefox for dev mode (as in chrome). It seems that Firefox get xpi but we have only folder (build/firefox_consumer??) . How can i do that?

**Comment by tomholub** [comment]
On `about:addons` choose cog -> debug addons, then `Load temporary addon`. Point it either at the `firefox-consumer` folder or the manifest inside of it. Let me know if this works.

**Comment by tomholub** [comment]
> @tomholub , @limonte
> 
> tomholub >>:"..npm run-script run_firefox or by manually adding an unpacked extension into your firefox profile...."
> 
> Running pm run-script run_firefox throws an error locally:
> 
> ```
> Running web extension from /Users/vnik/Projects/FlowCrypt/flowcrypt-browser/build/firefox-consumer
> s: The request "/Users/vnik/.mozilla/firefox/flowcrypt-dev" profile name cannot be resolved to a profile path
> ```
> 
> Also for unpacked version.. I am not sure what file/folder to install on Firefox for dev mode (as in chrome). It seems that Firefox gets xpi but we have only folder (build/firefox_consumer??) which cannot be selected for import . How can i do that?

To load this way, you could try to create a new profile on firefox ui, but during creation make sure to choose profile folder manually and put it in that location. That could work.

**Comment by vnikolaou** [comment]
> On `about:addons` choose cog -> debug addons, then `Load temporary addon`. Point it either at the `firefox-consumer` folder or the manifest inside of it. Let me know if this works.

Yes, a bit different in my version till you find it, but practically the same..

**Comment by vnikolaou** [comment]
Okay, so following the description, i closed the secure message compose popup after typing a small message with subject, body and recipient.
Then i am trying to open the draft, and i am seeing:
<img width="600" alt="Screenshot 2020-11-11 at 14 56 52" src="https://user-images.githubusercontent.com/965534/98814309-2acb6380-242e-11eb-9d5f-1e8dc908a1e1.png">

**Comment by tomholub** [comment]
Need to make sure to have rich text enabled

![image](https://user-images.githubusercontent.com/6306961/98815218-b5a46200-241e-11eb-8884-1204f27efd02.png)

When I tested it now, it didn't show anything at all:

![image](https://user-images.githubusercontent.com/6306961/98815361-e71d2d80-241e-11eb-9433-84a9c9a78079.png)

When I tested it earlier, it showed encrypted pgp/mime attachments (which contain the actual message text - this is pgp/mime since you enabled rich text, as opposed to pgp/inline which is the simple text) without a way to view the draft content:

![image](https://user-images.githubusercontent.com/6306961/98815415-00be7500-241f-11eb-9ca7-dcbb8ac5bd3d.png)

**Comment by vnikolaou** [comment]
Okay. I duplicated..  it seems that i hadn't actually clicked on the 'Rict text' option,

**Comment by vnikolaou** [comment]
@tomholub , i have been trying to find out where it breaks but seems to be some callback that creates the issue. I have put debug statements in many places. Is there any clue where to search for? Maybe the person who did that?

**Comment by tomholub** [comment]
You can probably fix it by saving rich text drafts in simple text format, so that it's same as simple text drafts. It's not a perfect fix, because it will lose the rich text, but it's better than what we have now.

Other possibility is to continue saving the drafts in rich text, but find a way for the content script that looks for drafts to recognize that it's a draft. It seems the rich text version is missing the draft "tag" that the content script is looking for, and replaces it with the "open draft" button. Adding that in will get you closer to fixing it.

**Comment by vnikolaou** [comment]
@tomholub , regarding the last possibility, here is what i did:

The `webmail.ts` file contains the entry point for reaching the code that does the replacement inside `gmail_element_replacer::replaceFcTags()` method.
So i disabled the initial call into `webmail.ts` like:
```
  if (1 % 1 == 2) {
    console.log('before calling webmail-> await gmailWebmailStartup()');
    await gmailWebmailStartup();
  }
```
So actually this is never called and the replacement is not reached. Even other messages encrypted that didn't break dont get the 'Open draft' link, instead show the original content.

So after disabling, the error still persists. I think it doesn't come from the code necessarily, unless above the `webmail.ts` exists something else.

Your first option may be acceptable, it is a good idea anyway to rreview that in more detail. Probably saving somehow the text in rich format doesn't follow fully what is needed there. I mean maybe something is missing there (eg. the tag you are mentioning) and the problem is not the rich text itself. I'll come back a bit later

**Comment by tomholub** [comment]
> So after disabling, the error still persists. I think it doesn't come from the code necessarily, unless above the webmail.ts exists something else.

Of course! When you disable the code is supposed to replace draft tags with the link, then draft rendering functionality will stop working.

I'm not sure what this attempt was meant to achieve, but it wouldn't get you any closer to finding a way to fix this.

When investigating an issue like this, in face any issue in any codebase, you would want to:
1) reproduce the problem (which you did)
2) observe the situations when it works as intended (with simple text drafts, hopefully you did this)
3) find out what is the difference between working and non-working scenario (in this case one is rich text and one is simple text. Rich text is saving the draft in a format that content script doesn't recognize)
4) think about why is it that way (it appears that the drafts formatting scenario was not created with rich text in mind, and likewise for the content script)
5) find an appropriate place to fix this (do we convert rich text to simple text before saving a draft? Do we teach the code that saves drafts to save them in a format that can be understood by the content script? do we also then update the content script in case the format is substantially different from simple text drafts?)
6) write a test
7) fix it

I'm not sure where in the above sequence would disabling content scripts fit, or how could it help us understand it.

**Comment by tomholub** [comment]
Semi-related issue: https://github.com/FlowCrypt/flowcrypt-browser/issues/3259#issuecomment-747607268

**Comment by rrrooommmaaa** [comment]
@tomholub
The draft message doesn't look broken because it is displayed in Flowcrypt's own "Inbox" correctly.
![image](https://user-images.githubusercontent.com/23335944/102917081-9d9c1580-4495-11eb-8e19-4b8b3420449b.png)
Looks like it's not recognized by gmail-element-replacer.
Attachments may not appear because of special handling of `Content-Type: multipart/encrypted; protocol="application/pgp-encrypted"` by gmail. We should find a way for a replacer to hook it up. 
Can this be solved by adding a special flowcrypt tag into the subject as is done with some other messages?
![image](https://user-images.githubusercontent.com/23335944/102917982-2ff0e900-4497-11eb-8cd8-f1cf61899234.png)
Or try to find message-id of the draft to try to recognize it as `multipart/encrypted` or `multipart/signed'? Can you give me some more insight on this?

**Comment by tomholub** [comment]
Yup - the rich text message doesn't render the tag in drafts, causing browser extension to not recognize it.

In particular, this should be tested in drafts of a new conversation - when it pops up in Gmail as a new compose window draft - that's where it would be looking for the tag, and it's missing.

I don't like the tags much, but don't know of a better solution. You're free to either use that, or explore.

**Comment by rrrooommmaaa** [comment]
@tomholub As part of testing and research I implemented optional nesting of `multipart/encrypted` one level deeper, having `multipart/alternative` as the root content. This didn't help to solve this particular issue but may be useful in future.
Should I create a separate PR to review this update?
Also, it's not very convenient to have separate EncryptedMsgMailFormatter and SignedMsgMailFormatter, as it is EncryptedMsgMailFormatter that has most logic to switch between different message types, etc.
`SignedMsgMailFormatter` (and hence `createPgpMimeSigned`)  is only used in real message sending, never in drafts, so rich text  drafts are always save encrypted (when possible), even when encrypt option is ticked off.
So another question is: do we really have to save encrypted drafts? Can we just save signed or even plain message and encypt/sign during sending?

**Comment by tomholub** [comment]
> So another question is: do we really have to save encrypted drafts? Can we just save signed or even plain message and encypt/sign during sending?

We definitely have to - our customer's threat model includes protecting data from Google itself.

> As part of testing and research I implemented optional nesting of multipart/encrypted one level deeper, having multipart/alternative as the root content. This didn't help to solve this particular issue but may be useful in future. Should I create a separate PR to review this update?

Does this kind of structure follow https://tools.ietf.org/html/rfc3156 ? Does not matter too much for drafts, but it does matter for outgoing messages. Meaning, there is a possibility we may only be able to use this for the drafts.

> SignedMsgMailFormatter (and hence createPgpMimeSigned) is only used in real message sending, never in drafts, so rich text drafts are always save encrypted (when possible), even when encrypt option is ticked off.

From user perspective, this is not ideal. But nobody complained about this, 90% of users primarily care about encrypted messages (that are also signed) rather then plain signed messages.

I did it this way because I did not want to complicate parsing drafts to also account for separate structure for signed messages.

Would it make it easier overall to save signed drafts actually only signed?

> Also, it's not very convenient to have separate EncryptedMsgMailFormatter and SignedMsgMailFormatter, as it is EncryptedMsgMailFormatter that has most logic to switch between different message types, etc.

I'm open to structuring it differently if that results in an improvement in convenience. All of these used to be in one file but now that it's split it's definitely better then before. But maybe you have some other idea.

**Comment by rrrooommmaaa** [comment]
> Does this kind of structure follow https://tools.ietf.org/html/rfc3156 ? Does not matter too much for drafts, but it does matter for outgoing messages. Meaning, there is a possibility we may only be able to use this for the drafts.

I did browse through this particular specs file, the specs define content types `multipart/encrypted` and `multipart/signed`, but I didn't find any limitation on where this content should be placed inside an e-mail. There were also no mentions of such possible limitation on stackoverflow etc.
I also tried to find samples of such messages on github, there are only a few in this project:
https://github.com/RUB-NDS/Covert-Content-Attacks/blob/c396891fc9701cfd6ffc1b6a63dfbff6e8d961bb/01-enc/pgp_mime/01-reply-mix-alt.eml
https://github.com/RUB-NDS/Mitigation-of-Attacks-on-Email-E2E-Encryption/blob/0e6b4641cc4ba31ed6094f63a84986398f906117/implementation/attack-emails/A2%20DC%20MIME%20Modified.eml
The current version of Flowcrypt itself recognized messages constructed as `multipart/alternative' and renders them (though I saw some glitches with the pgp block sometimes disappearing in the process of rendering -- not sure if this was related to the format)

> Would it make it easier overall to save signed drafts actually only signed?
Well, when we save a draft, aren't we supposed to be able to resume editing or at least see what we're about to send? As we usually don't have our recipient's private key, we have to store the draft unencrypted, right? We can save it somewhere in Chrome local storage if this helps protecting the data from Google itself. So, the simplest solution for this issue would be to generate a placeholder draft message with no real text, but only a Flowcrypt tag (for messages we define as problematic -- causing quirky gmail behaviour) to make us able to extract the unencrypted message text from the storage and a warning/excuse message in case it gets sent accidentally.

> I'm open to structuring it differently if that results in an improvement in convenience. All of these used to be in one file but now that it's split it's definitely better then before. But maybe you have some other idea.

I currently can't see what issues this splitting was meant to solve. In `ComposeDraftModule.draftSave` method we call 
```
await new EncryptedMsgMailFormatter(this.view, true).sendableMsg ....
```
where `true` means `isDraft` flag, so we allow `EncryptedMsgMailFormatter` to decide on how to modify the message depending on whether we're sending a draft or not. If we want to not encrypt drafts -- how should we wire `SignedMsgMailFormatter` there? To me, it looks like `isDraft` logic is spread over several modules. It would be better to pass all the flags like `isDraft`, `sign` and `encrypt` to some `MsgMailFormatter` and have all the logic there in one place. That's my first impression.

**Comment by seisvelas** [comment]
>We definitely have to - our customer's threat model includes protecting data from Google itself.

Hmm. If I were Google attacking a FlowCrypt user, my strategy might be to add code to the target's Gmail web page to wait for FlowCrypt's Secure Compose button to be injected into the DOM by the extension and then cover it with another button that loads a fake, Google controlled Secure Compose. 

Alternatively, insert an invisble div above the Secure Compose popup to steal keystrokes, then when the user tries to send, say there was an error and they'll have to try again. Then delete the evil div and let them send their message for real.

These are just conjectures, maybe we account for all of this. Let me know - if this is an idea we'd like to explore in depth we can make a dedicated issue to Strategies for Defending Against Google or something similar to investigate feasibility and mitigation of such attacks. Honestly, acting within the Gmail web page already gives us the disadvantage in that fight. A customer truly concerned about defending Google might be much better off with a hypothetical FlowCrypt Enterprise addon for Thunderbird or Outlook or whatever non-webmail client. That way, everything is already totally encrypted by the time it even touches anything Google controlled, while still having easy integration with our on-prem solutions. 

Realistically, though, securing the extension as it is now is of more immediate concern than hypothetical new products, so let me know your thoughts and we can maybe do a lot of cool things to protect customers using the extension from Google :)

Sorry for inserting this big rant into an only tangentially related issue btw!

**Comment by tomholub** [comment]
> >  Would it make it easier overall to save signed drafts actually only signed?
> Well, when we save a draft, aren't we supposed to be able to resume editing or at least see what we're about to send?

That's how it works today (at least for non-rich-text which work properly, unlike rich-text, which is the subject of this issue).

You start writing a message, either for encrypting or signing. You change your mind and close it. It gets saved encrypted in Gmail API. Later you re-open it and continue editing.

> As we usually don't have our recipient's private key, we have to store the draft unencrypted, right?

We never have recipient's private key, that's for recipient to keep.

We store draft encrypted using our own public key.

> We can save it somewhere in Chrome local storage if this helps protecting the data from Google itself. So, the simplest solution for this issue would be to generate a placeholder draft message with no real text, but only a Flowcrypt tag (for messages we define as problematic -- causing quirky gmail behaviour) to make us able to extract the unencrypted message text from the storage and a warning/excuse message in case it gets sent accidentally.

This is strictly worse than storing it on Gmail encrypted. What is the downside to encrypting it and then storing it on Gmail?

**Comment by tomholub** [comment]
> > I'm open to structuring it differently if that results in an improvement in convenience. All of these used to be in one file but now that it's split it's definitely better then before. But maybe you have some other idea.
> 
> I currently can't see what issues this splitting was meant to solve. In `ComposeDraftModule.draftSave` method we call
> 
> ```
> await new EncryptedMsgMailFormatter(this.view, true).sendableMsg ....
> ```
> 
> where `true` means `isDraft` flag, so we allow `EncryptedMsgMailFormatter` to decide on how to modify the message depending on whether we're sending a draft or not. If we want to not encrypt drafts -- how should we wire `SignedMsgMailFormatter` there?

Saving the message draft encrypted, when it was in fact a signed message draft, is not ideal but not a big problem either. We could ignore this, at least for now. But if you want to fix it, then you'd probably add `isDraft` to `GeneralMailFormatter.processNewMsg`. Then pass that around into `SignedMsgMailFormatter` and so on inside that method.

Then in `draftSave` you'd call `GeneralMailFormatter.processNewMsg(...., true)` instead of `EncryptedMsgMailFormatter(this.view, true)`.

---------------------------

To talk about drafts in general. Of course, best would be if we did not have to modify the message in any way. If we could just save the message exactly the same way as we would if it was an outgoing message, without any added tag, and then we were able to somehow realize that it's an encrypted draft, that would be amazing (the content script draft parsing code would have to change).
