### ISSUE TITLE
Pubkeys in signed messages from thunderbird show doubled

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3106]
![image](https://user-images.githubusercontent.com/6306961/97630315-552d2200-1a27-11eb-9839-72f4cbb5f1f6.png)

This should be improved. Somehow the message is being wrongly interpreted, with the public key rendered twice - that's a bug. It may have something to do with `Att.treatAs`, or it may be something else. I'll also make a separate issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/3076#issuecomment-719010367_

**Comment by tomholub** [comment]
> inbox-active-thread-module.ts renders two message blocks: "signedHtml","publicKey".
> So, 2 pgp blocks are created:
> 1) message
> 2) pgp key
> 
> And later, in decideDecryptedContentFormattingAndRender, the public key is broadcast and received by the block 1 and it is appended to the message too.
> 
> So, we have the pgp key rendered twice -- in each block.
> 
> How should this be better organized?

To be honest I'm not sure what is the best way to address this. There are a few options:
1) the recipient of the broadcast could try to look at existing rendered pubkeys and don't render if duplicated
2) The sender of the broadcast could somehow sense this situation and not broadcast
3) The gmail rendering script could sense this situation and not render this public key

The problem is that there is a valid case for all of these situations: the gmail content script sometimes needs to render keys which are usually not picked up by the pgp_block. The pgp_block needs a way to render pubkeys (with the broadcast message) which are not picked up by content script because they are not in a separate file, but maybe included inside of the message for example, and only available after rendering.

I'm not sure why in this situation both pick it up. Is it attaching a public key both outside as a file as well as inside of the encrypted message? That would explain the duplication. In that case, it would be "sort of" expected behavior and maybe should be fixed in Thunderbird.

**Comment by rrrooommmaaa** [comment]
@tomholub The message is a bit strange. It consists of two parts (that's by the protocol):
mixed and `pgp-signature`
and the first mixed part contains another single "mixed" part.
and this internal "mixed" part contains two parts: text/html and key.
So maybe the problem is because of this double-wrapping? 
I'll try to see if we look though this "double mix" and whether this helps rendering.

**Comment by rrrooommmaaa** [comment]
The outer mix is to carry Subject and From and To fields

**Comment by tomholub** [comment]
You'll have to use your judgement here - I have no better ideas other than the ones above, but maybe as you evaluate this, you'll find some better way to fix it.

**Comment by rrrooommmaaa** [comment]
Gmail rendering script doesn't duplicate the public key, it's Flowcrypt's own inbox-active-thread-module issue.
We are testing unencrypted message (with public key inside) and detached signature

Gmail replacer does this:
1. creates 'pgp' block (for message contents)
2. appends public key inside this block (processAtts)
3. while processing signature, _overwrites_ the entire `pgp` block (processAtts), thus removing the public key from there.
4. if the public key is not found (in wkd, attester etc.), creates another frame with the one from the message

inbox-active-thread-module creates two frames: 'pgp' and 'pubkey'.
The 'pgp' frame renderer also adds pubkey to its frame after "decryption" via render_public_keys message.
 
Gmail rendering script simply doesn't listen to this message, while inbox-active-thread-module does 
(thus rendering it in 'pgp' block too).
I added additional condition `isEncrypted &&` (the simplest solution) to not send this message for signed-only messages, but not entirely sure whether it won't affect rendering of some other message constructs (old Thunderbird?)

Now, the next step is to check whether the `pubkey` frame gets hidden/erased in inbox-active-thread-module in case the pubkey can be retrieved from
storage, wkd, attester etc.

**Comment by tomholub** [comment]
You are definitely on the right track.

Careful with the wkd check. If the public key is found on wkd but the
attached key has a newer signature on it, then the attached key is still
useful to render.

But it really surprises me that there was this logic - to not render pubkey
if found on wkd or attester. Really? Very interesting. Could you point me
to where this happens? I'd like to review it to make sure it makes sense.

**Comment by rrrooommmaaa** [comment]
@tomholub 
>But it really surprises me that there was this logic - to not render pubkey
> if found on wkd or attester. Really? Very interesting. Could you point me
> to where this happens? I'd like to review it to make sure it makes sense.
Looks like I was mistaken on this one. Actually, gmail replacer does append a pubkey frame on message,
so `isEncrypted &&` solution isn't working -- the pubkey isn't rendered on gmail. I added gmail pubkey tests (failing yet)
and looking for another solution.
Also, do you think it's better to load the message from `exported-messages` json file in unit test `[unit][MsgUtil.verifyDetached]`?
Also, the pubkey has expiration set, this means that the tests will start to fail sometime. How should we go about it?

**Comment by tomholub** [comment]
>  Also, the pubkey has expiration set, this means that the tests will start to fail sometime. How should we go about it?

Ideally you would use a custom created pubkey with a custom message

>  Also, do you think it's better to load the message from exported-messages json file in unit test [unit [MsgUtil.verifyDetached]?

I think yes - you would use something like Gmail(emailAcct).getMessage(id) - just guessing the names here - like the extension normally would, which would make sure you are testing more than one component. We don't have any tests like that yet, I think they would be useful.

But it depends what exactly are you testing. If it's UI behavior of how messages are rendered, then unit test is not the right choice. If you're testing a more specific code behavior, then it probably is.

**Comment by rrrooommmaaa** [comment]
This unit test is to call MsgUtil.verifyDetached with sample data, it already exists.
We use this message json in UI tests too, so I thought we'd load it from there for both tests.

**Comment by tomholub** [comment]
Sure, you could

**Comment by rrrooommmaaa** [comment]
@tomholub Why would we want to append the public key to the message div, so it would be erased later.
We can think about replacing the original attachment div (see picture), or put it after the message div.
I'll also create signed & encrypted message in Thunderbird to test and see how the new changes are working out.
![image](https://user-images.githubusercontent.com/23335944/98449028-61a92d00-2141-11eb-8060-6e61ce327d92.png)

**Comment by tomholub** [comment]
> We can think about replacing the original attachment div (see picture)

The issue here is that it produces broken looking design even if you don't have more than one attachment. If this was a second attachment of three, it would be a real mess visually.

> put it after the message div

This sounds similar to appending, if it helps your issue, sure
