### ISSUE TITLE
update test to check that banners are not showing when not expected

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3113]
this one needs a test: no tests were testing that the banners are NOT showing

![image](https://user-images.githubusercontent.com/6306961/96828781-c5d0af00-1427-11eb-8ae8-4b62e67def39.png)

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/3069#issuecomment-714246506_

**Comment by limonte** [comment]
Oops, I missed this comment in #3069 sorry!

I can handle this one as well.

**Comment by tomholub** [comment]
Excellent, thanks!
