### ISSUE TITLE
Use of deprecated <font> tag

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3130]
We use this tag here:

https://github.com/FlowCrypt/flowcrypt-browser/blob/9d1b2e1528d13925a061544aae99c8146cd0f8d8/test/source/browser/controllable.ts#L579-L584

It's part of tests and not a big deal imo *but* strictly speaking this tag is deprecated as of HTML 4 (and is not even included in HTML 5), and it's generally recommended to style text without the font tag.

**Comment by tomholub** [comment]
Thanks for noticing!
