### ISSUE TITLE
rework reply options to be more obvious

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3149]
I received encrypted email that was

```
from: guy@other.com
to: me@domain.com,george@other.com
cc: andy@other.com,lily@other.com,wes@other.com
```

I click reply all, and I see in secure reply:

```
to: guy@other.com,george@other.com
```
We seem to be ignoring CC emails, which I think is a bug. It's different than what Gmail does.

**Comment by limonte** [comment]
![OxDQV7exdr](https://user-images.githubusercontent.com/6059356/99104795-2481e680-25ea-11eb-8a12-589e3fedeb0e.gif)

can't reproduce from the first try, let me check with the input data provided in the issue description...

**Comment by limonte** [comment]
Interesting opening the same email from another account which was in `cc` and it is reproducible.

**Comment by limonte** [comment]
> `this.view.replyParams` seems to be incorrect, both `from` and `cc` are incorrect:
> 
> ![image](https://user-images.githubusercontent.com/6059356/99109513-9e699e00-25f1-11eb-89e1-bf79f9badc5a.png)

Actually, the `replyParams` are correct in this screenshot, sorry for confusion.

**Comment by limonte** [comment]
@tomholub I am unable to reproduce the issue.

The secured email in `flowcrypt.compatibility@gmail.com`: https://mail.google.com/mail/u/3/#inbox/WhctKJWJDXwvNwfshclzTgRLDMkfmlrxqPqQBTxKgPDcQJmdccZBGZtvTCmtBNrSbGQDHNL

It has

```
from: limon.monte@gmail.com
to: flowcrypt.compatibility@gmail.com
cc: vladimir@flowcrypt.com
```

When I open it from `flowcrypt.compatibility@gmail.com` it shows this:

![image](https://user-images.githubusercontent.com/6059356/99905596-786f8800-2cda-11eb-8654-a43295d6d9fd.png)

When I open it from `vladimir@flocrypt.com` it shows this:

![image](https://user-images.githubusercontent.com/6059356/99905701-2da24000-2cdb-11eb-9f42-087d8e820ab9.png)

Both behaviors are correct. Are you still able to reproduce the issue?

**Comment by limonte** [comment]
I forgot to mention that the functionality is already covered by the `compose - reply all - TO/CC/BCC when replying all` test case.

**Comment by tomholub** [comment]
Mystery resolved - I'm clicking reply, not reply all.

Or more precisely, I'm clicking in the white space in reply box.

This is a bit tricky - every user may have different settings in Gmail on what to do as a default reply. 

Interestingly, for me it's neither?

![image](https://user-images.githubusercontent.com/6306961/99976505-6dc8f780-2d9b-11eb-87be-fb5153deed24.png)

And then when I want to reply with standard interface, it shows this:

![image](https://user-images.githubusercontent.com/6306961/99976670-a8329480-2d9b-11eb-8434-79b8888cbe3a.png)

No "general reply", so user always knows which one they clicked.

I think that's a reasonable design - we should probably make FlowCrypt behave similarly, so that there is less confusion. What do you think?

**Comment by limonte** [comment]
> Mystery resolved - I'm clicking reply, not reply all.

It was happening for me as well. This is why initially I thought that the issue is flaky but then realized that I was clicking the wrong thing.

> I think that's a reasonable design - we should probably make FlowCrypt behave similarly, so that there is less confusion. What do you think?

Agree 👍
