### ISSUE TITLE
Invalid behavior of contacts search/autocomplete 

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3150]
### Expected behavior

1. When I write my own email
2. I expect only one suggestion - my own email

Here's Gmail:

![image](https://user-images.githubusercontent.com/6059356/99078381-f9d26680-25c6-11eb-86db-f59daffc3e41.png)

### Actual behavior

In fact, I'm getting emails I was using before to test out things:

![SzOM0l0bb9](https://user-images.githubusercontent.com/6059356/99078213-b1b34400-25c6-11eb-9061-e6066f75f99c.gif)

In this case, if I hit `Enter` the totally valid email address I entered will be replaced by the first one from the suggestions list.

**Comment by tomholub** [comment]
Thanks for noticing :+1:

**Comment by limonte** [comment]
I have to fix contacts first before fixing #3149, the contacts search is playing with me, giving different results all the time 😫 

![image](https://user-images.githubusercontent.com/6059356/99117873-2ace8d80-25ff-11eb-9472-66ee881e0498.png)
