### ISSUE TITLE
[Compose] Ctrl + Enter doesn't seem to work in Chrome

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3151]
Strange issue, I remember this was working in Chrome, but not anymore. We have the test case `compose - keyboard - Ctrl+Enter sends message` which should cover this. Also, all is well in Firefox.

Can anyone confirm?

**Comment by tomholub** [comment]
Works for me on chromium - testing with textarea focused.

Version 86.0.4240.75 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Comment by limonte** [comment]
Chromium issue :/ https://bugs.chromium.org/p/chromium/issues/detail?id=79407

Not sure why it happened only now, the issue is quite old.
