### ISSUE TITLE
Previous contacts are missing in contacts search

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3152]
I'm working on #3149 and something weird is happening in the contacts search. Sometimes I don't see emails which I was using previously. To fix that I have to send emails to those addresses once again.

I'm unable to provide the steps to reproduce, just reporting the observations. I don't know for now what causes previously used emails not to be available in the contacts search results.

Example:

![image](https://user-images.githubusercontent.com/6059356/99116662-138ea080-25fd-11eb-9a2f-2d2a91956aa7.png)

Expected behavior:

![image](https://user-images.githubusercontent.com/6059356/99116825-5badc300-25fd-11eb-9aad-9ed696e024e8.png)

The same is happening with `vladimir@flowcrypt.com`:

![image](https://user-images.githubusercontent.com/6059356/99117491-79c7f300-25fe-11eb-88e3-9fcefbef42f7.png)

**Comment by limonte** [comment]
Possibly the same as #3150

**Comment by limonte** [comment]
For the record, 

I just typed "sw" and got the same "No result found" result as in the screenshot in the description.

Then I typed "sweetalert2@gmail.com" and then I got the expected suggestion:

![image](https://user-images.githubusercontent.com/6059356/100620092-aed68400-3326-11eb-879a-8a6581368e42.png)

Now, the expected suggestion is shown also when I type "sw". Strange. I'll wait till I can reproduce this again.

**Comment by tomholub** [comment]
In this case, "sw" does not find anything on Google. Nor locally. "sweetalert2" will allow the extension to find it on Google and save locally. Next time you type "sw", it finds it from local store - my guess.

**Comment by tomholub** [comment]
Does typing "sw" iin Gmail interface pull up the contact?

**Comment by limonte** [comment]
> "sweetalert2" will allow the extension to find it on Google

Do I understand correctly that the extension shouldn't be able to find anything on Google unless I give access to my contacts? Currently, I didn't give the access so I believe that it's not coming from Google.

![image](https://user-images.githubusercontent.com/6059356/100629295-c9622a80-3331-11eb-8313-a8bf4789b2b3.png)

**Comment by limonte** [comment]
> Does typing "sw" iin Gmail interface pull up the contact?

No.

![image](https://user-images.githubusercontent.com/6059356/100629389-e860bc80-3331-11eb-8fb9-72797064c3ac.png)

I was using sweetalert2@gmail.com only in FlowCrypt.

**Comment by tomholub** [comment]
> Do I understand correctly that the extension shouldn't be able to find anything on Google unless I give access to my contacts? Currently, I didn't give the access so I believe that it's not coming from Google.

When google contacts are turned off, the extension is guessing your contacts from sent email. If you've sent an email to someone in last 6 months, it's considered your contact. It's doesn't work perfectly, but it does find a bunch of emails that would normally be your contacts even if you don't give permission.

**Comment by limonte** [comment]
I'm not able to reproduce this issue anymore. Strange. I'll move it to `can't reproduce`. @tomholub feel free to close it, I'll reopen it in case I encounter it again.

**Comment by tomholub** [comment]
Ok, no prob. Some of these issues are finicky to reproduce. I'll close it, but feel free to reopen anytime, all improvements in the recipients field are welcome.
