### ISSUE TITLE
searching domain.com in contacts page does not find joe@domain.com

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3156]

**Comment by limonte** [comment]
This behavior is handy IMO, but might not be unexpected by users as Gmail doesn't behave this way.

**Comment by tomholub** [comment]
To clarify - the particular place where I noticed it was FlowCrypt Settings -> Additional Settings -> Contact, which only searches local database.

I was trying to find public keys that belong to our team to fix up our EKM https://flowcrypt.com/docs/technical/email-key-manager/latest/email-key-manager.html which would fix up WKD https://flowcrypt.com/docs/technical/email-key-manager/latest/wkd-server.html which would fix the failing tests.

I think there is some value in being able to find all emails of the same domain there - whether recipient or your own domain.

I know why it's failing too - IDBDatabase does not have full text search, so we're creating the index ourselves. And the full domain part is not part of the index. It could be.

**Comment by tomholub** [comment]
For regular contact search (when composing) I'm not aware of any value it would provide there, but that may get enabled as a side effect of fixing it on the contacts page.

**Comment by tomholub** [comment]
I will use this as an evaluation task for a new team member.

Screenshot of the issue:

![image](https://user-images.githubusercontent.com/6306961/100474704-24e5ab80-30d9-11eb-8c69-32ee91999c1f.png)

But when I search just `flowcrypt`, it finds a bunch of emails that it was also supposed to find when searching `flowcrypt.com`:
 - `tom@flowcrypt.com`
 - `ekm@ekm-org-rules-test.flowcrypt.com`
 - etc
