### ISSUE TITLE
Ability to remove any contact with keyboard

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3165]
### Given

There are 2 contacts in `#input_to`: `alice@domain.com`, `bob@domain.com`.

### The problem

Users can't delete `alice@domain.com` and keep `bob@domain.com` with the keyboard. The deletion only works with `Backspace` when the focus is in `#input_to` and not in any of the contacts. Users have to delete `bob@domain.com` first, then `alice@domain.com`. 

### Possible solution

The focused contact should remove itself when the user press ~~`Esc`~~ `Del` or `Backspace`.

**Comment by tomholub** [comment]
sounds good, that's what I'd expect if using keyboard

**Comment by limonte** [comment]
Sorry! I made a typo in the issue description!

In the "possible solution" section I meant `Del` or `Backspace`.
