### ISSUE TITLE
Unable to set up FlowCrypt after clearing the application storage in Chrome DevTools

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3177]
While debugging flaky #3149 I cleared the application storage here:

![image](https://user-images.githubusercontent.com/6059356/99904820-2298e100-2cd6-11eb-81dc-f921c0f326c7.png)

After clearing the storage I'm not able to set up FlowCrypt. After entering the correct password this error occurs:

![image](https://user-images.githubusercontent.com/6059356/99904863-61c73200-2cd6-11eb-8584-c849d6ee2b05.png)

`Error setting up FlowCrypt: FlowCrypt encountered an error with unknown cause. (Error: BrowserMsg(db) sendRawResponse::InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.`

**Comment by limonte** [comment]
Not sure why exactly, but restarting the browser helped.

**Comment by tomholub** [comment]
It may be interesting to see if, under this condition, it would work to try to close the database on the background page, and re-open a new one. But I have never had the time to look into it, and it's too rare to spend time on it right now. But I'm happy you documented it here, in case someone in the future does look into it.
