### ISSUE TITLE
sometimes a pgp block is not rendered at all from pgp/mime

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3180]
No error showing in console either. Observed myself on Firefox. It was my message that was missing. Refreshing the page fixed it. Messages above in the conversation were showing without issues.

![image](https://user-images.githubusercontent.com/6306961/99953890-d4d5b480-2d79-11eb-83d6-293cead9e325.png)

**Comment by tomholub** [comment]
This was a pgp/mime message - rendered from attachments. We used to have this bug and I thought we fixed it since, but it's manifesting again now on version 8.0.0, possibly due to a change in Gmail, or maybe we didn't fix it completely.

**Comment by tomholub** [comment]
This is happening to me more and more. Happens when the received message is the only message in conversation as well. Happens to flowcrypt-produced as well as other-software-produced messages. It's always PGP/MIME where it's interpreting it from attachments.

**Comment by tomholub** [comment]
This was interesting - now I opened a message and it was visible for about a second, and then it got hidden!

![image](https://user-images.githubusercontent.com/6306961/100610521-cbaf8f00-3307-11eb-95e7-08bddaa14b9c.png)

**Comment by tomholub** [comment]
@limonte could you please have a look? I know it's hard to hunt it down without a repro case. But it does seem like a race condition that we should be able to fix.

We replace contents once a second. Let's say there's a request it needs to make and it takes exactly a second.. then two replace cycles do their thing at the same time.. something like that.

**Comment by limonte** [comment]
Happens to me, but now I have steps to reproduce:

1. Send a rich text message to yourself
2. Right away click "Inbox"
3. Right away click the new message from yourself

![gF9WAoDLPm](https://user-images.githubusercontent.com/6059356/102487876-e60d9a80-4073-11eb-9c56-1767aa59c892.gif)

Important: the second time the same message will be rendered properly.

**Comment by tomholub** [comment]
Thanks! Is that a reliable reproduction? I'll be interested why does that happen.

**Comment by limonte** [comment]
> Thanks! Is that a reliable reproduction? I'll be interested why does that happen.

Yes, that's the reliable one. A new message is required for every reproduction.

**Comment by tomholub** [comment]
This could be accompanied with a live gmail test, actually.
