### ISSUE TITLE
refactor use of passphrase in Compatibility page

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#3188]
The value from `input_passphrase` should be passed to KeyUtil.diagnose to properly perform tests.

**Comment by rrrooommmaaa** [comment]
It turns out, the passphrase is read somewhere in depths of OpenPGPKey.diagnose but the decrypted key isn't used for further tests:
![image](https://user-images.githubusercontent.com/23335944/100137421-80c3f080-2e9d-11eb-9094-3afc78cb89ff.png)
So I suggest to 
1) pass `passphrase` as parameter and create a simple unit test
2) use the decrypted key for Sign/Veryfy and Encrypt/Decrypt tests

**Comment by tomholub** [comment]
agree, please pass it as a parameter

Further, instead of rendering directly, I suggest the method appends lines to an array, and returns the array of lines.

Other method will be responsible for rendering.

This way, the compatibility method can be unit tested for inputs/outputs.
