### ISSUE TITLE
Gmail's auto-replies are shown

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3201]
Can be reproduced here: https://mail.google.com/mail/u/1/#inbox/WhctKJWJFZGtpDRjKflnHxxznpmHNCsRmjPTMbQKPgJdxCCMLjPGdBvCJdcCWdfZgLXXDkL

![image](https://user-images.githubusercontent.com/6059356/100552328-412b4900-328f-11eb-9b59-bb588e766e25.png)

I guess we should hide them. WDYT @tomholub ?

**Comment by tomholub** [comment]
Definitely
