### ISSUE TITLE
Use separate types for storage

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#3220]
as discussed in #1640 
for example, `Key` shouldn't be stored with `usable`, `expired` etc.
`KeyInfo` shouldn't be stored with `passphrase`

**Comment by tomholub** [comment]
We do actually store pass phrase, however I think we store it in a separate place, not in KeyInfo. You'll need to have a closer look at the savePassphrase and loadPassphrase methods. They use either session (temporary) or extension (permanent) storage.

**Comment by tomholub** [comment]
I'll take this on as a part of the currently reviewed PR #3213

**Comment by rrrooommmaaa** [comment]
@tomholub We also wanted to replace `Key` in `Contact` with another type, so we calculate `usableForEncryptionButExpired` etc. at the moment of loading.
