### ISSUE TITLE
 FlowCrypt incompatible with PortableApps FireFox

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3222]
A user is attempting to use FlowCrypt with the [PortableApps Firefox](https://portableapps.com/apps/internet/firefox_portable) but has the following problem:

> 1.  I installed Firefox (non-portable).
> 2.  Installed the FlowCrypt extension.
> 3.  When I tried to recover the keys, I get this message.
> 
> This pass phrase was already used to recover some of your backups.
> The remaining backups use a different pass phrase.
> Please try another one.
> You can skip this step, but some of your encrypted email may not be readable.

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjdvMVRZMxCsSTczdvHZqvcpk

PortableApps offers versions of applications that can be loaded from a USB instead of installed on the system and improved privacy features.

Is this something we're interested in attaining compatibility with?

**Comment by seisvelas** [comment]
I should clarify - they don't get this when they try normal firefox, otherwise the error is self explanatory. But I need more info about whether they've created more keys with backups and haven't tried those passphrases among other things, so I'll close this for now and reopen if all else fails

**Comment by tomholub** [comment]
This doesn't look like a problem specific to the browser, the extension is behaving normally. They just have more than one backup. If they don't know the pass phrase to the remaining backups, they can skip them, see if the email they want to read is still readable.
