### ISSUE TITLE
The selected recipient inserted two times when clicked while contacts are still loading

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3242]
### Steps to reproduce

1. Copy any email to the clipboard
2. Paste it to the recipients field and wait for contacts to show

![image](https://user-images.githubusercontent.com/6059356/101772933-be0ebc00-3af4-11eb-82cf-e024fcefa978.png)

3. Right away, before the "loading..." goes away, mouse click the first suggestion 

### Expected result

![image](https://user-images.githubusercontent.com/6059356/101773128-075f0b80-3af5-11eb-9981-57965dc600e7.png)

### Actual result

![image](https://user-images.githubusercontent.com/6059356/101773116-01692a80-3af5-11eb-9377-1e0df4ace1ca.png)

**Comment by tomholub** [comment]
Yes, I kept running into this earlier! Very annoying.

**Comment by limonte** [comment]
It's actually more buggy than just doubling the contact:

![5N3OMfkMwF](https://user-images.githubusercontent.com/6059356/101775622-6bcf9a00-3af8-11eb-987d-42614d4a586a.gif)
