### ISSUE TITLE
Add a non-encrypted intro message to a secure email

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3245]
Is this something that we offer, or used to offer? I received this support email from a customer:

> I wanted to check that my subscription is still active for the pro level capability to add a non-encrypted intro message to a secure email. The functionality seems to have disappeared on my account. Great feature when sending secure emails.

But I can't find any references to this feature anywhere. Do we offer this?

**Comment by seisvelas** [comment]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjnXXsLhtHSdJgrcKDQqhvZTk

The user then followed up with this:

>Updated question -  I see that the intro functionality does work -- when the email address turns gray.  The question is - why don't all email addresses turn gray (this one does not, nor does the gmail address that caused me to write originally.

Maybe they are referring to password protected messages? I'll ask and get a better idea, but I wanted to ask here since I don't know about the feature they are originally asking about.

**Comment by seisvelas** [comment]
Okay, that's what I suspected was the case. Since we already have an issue open for this, what's your opinion of a feature to add plaintext intros to encrypted messages (like how we currently offer unencrypted footers for pro users)?

**Comment by tomholub** [comment]
>  what's your opinion of a feature to add plaintext intros to encrypted messages (like how we currently offer unencrypted footers for pro users)?

I imagine some users would like that, but I'm hesitant to add it for now. If a recipient has openpgp set up, there is no need for an intro. If they don't, then intro makes more sense (which is what we currently do). Additionally, adding intro to regular openpgp messages may throw off some email clients that would normally understand it as pgp message, but with intro they no longer would.

Therefore it would a be no-op on our side for now.
