### ISSUE TITLE
replace `Key` in `Contact` for better consistency

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3247]
@tomholub We also wanted to replace `Key` in `Contact` with another type, so we calculate `usableForEncryptionButExpired` etc. at the moment of loading.

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/issues/3220#issuecomment-743785530_

**Comment by rrrooommmaaa** [comment]
@tomholub There are some crafty `ContactStore` methods like `update` that saves `pubkey` as string,
while `obj`/`save`  pair save as `Key`, and `deserialize` allows both `string` and `Key` version of `pubkey` as input.
Can we always store `pubkey` as string and use `KeyCache` to map to `Key`?
Does saving `pubkey` as `Key` give any performance benefit?

**Comment by tomholub** [comment]
From the perspective of performance, the most important situation is when pulling many public keys - either when searching contacts in compose window, or even more when searching contacts in settings -> Contacts. It's important that we have all needed information without having to parse keys in those two places (when handling more than one key at a time). In particular, when rendering lists like this, it's good to know when the key expires and if or when it has been revoked (even if we don't have functionality to render it now, we eventually may).

From the perspective of functionality, right now we search by substring (index) and has_pgp. I don't see any search or index by expiration, although it's conceivable we may want to do that.

> There are some crafty ContactStore methods like update that saves pubkey as string, while obj/save pair save as Key, and deserialize allows both string and Key version of pubkey as input. Can we always store pubkey as string and use KeyCache to map to Key?

There was an effort to just always pass `Key` everywhere to keep things standard. But I'm not sure why this is there anymore:
```
const key = typeof update.pubkey === 'string' ? await KeyUtil.parse(update.pubkey) : update.pubkey;
```

It should just accept and expect a Key. Maybe this was a part of migration, where we still had a `string` stored in database? That's the only thing that would make sense, but I'd have to review it closer to see if such string could actually make it from the database all the way back to the update method "unnoticed" until this step. It seems it wouldn't, so this could likely be refactored.

> deserialize allows both string and Key version of pubkey as input.

This is definitely a result of a database schema change without a migration. `pubkey` used to be a string in database. We changed it to `Key` to get more flexibility. It may still come back from the database as `string` and it's getting deserialized into a `Key`. 

Actually, this would explain the performance issues I've been having. Plus it leads to sometimes having outdated `Key` object and sometimes one that's up to date.

-----------------------------

I agree all of this should be streamlined somehow. If we change it all to `string`, then it will be the same as before :laughing: so we may find ourselves running in circles.

If you wan to get out of this mess, I would consider making a whole new database table. In the migration, we would have to go batch by batch - grab 20 public keys, parse them if needed (cca 200 ms worst case, although most should not need parsing), insert into new table, delete them from old table. Wait 200ms and continue until all done, then finally delete old table.

This means if someone updates, and they have 1000 keys, it will take 20 seconds to migrate. During that time, they will not see all public keys while they are getting moved. That's not too bad, as long as there are delays between batches so that their device doesn't become toast if they have 5k keys like me.

Sounds to me like this kind of operation would need a migration test..

The other option is some less aggressive approach, where we try to clean it up without migrating everything.

There's also an option of cleaning up the existing table, in a similar manner, without moving it. That may be better?

**Comment by rrrooommmaaa** [comment]
> 
> There was an effort to just always pass `Key` everywhere to keep things standard. But I'm not sure why this is there anymore:
> 
> ```
> const key = typeof update.pubkey === 'string' ? await KeyUtil.parse(update.pubkey) : update.pubkey;
> ```
> 

More interesting is the part below:
```
update.pubkey = KeyUtil.armor(key) as unknown as Key; // serialising for storage
```
So it actually saves as a string.

**Comment by tomholub** [comment]
Got it. So that's not so bad. Does that mean we actually don't have a problem with stale `Key` stored in database?

**Comment by rrrooommmaaa** [comment]
We have in case it was saved with `obj`/`save`. In this case it is saved as a `Key`.

**Comment by tomholub** [comment]
I see. We can start out by ensuring we always save it as a string.

After that, we may find that we don't need to do anything else - except maybe a migration to make sure to go through all keys in db, check if there is object saved, and replace it with a string. That should be an easy migration, because it does not actually parse any key.

Does that sound ok or do you see more things that we should be fixing?

This way, the `Contact` will still continue having a `Key`. But never in actual storage.

In a separate PR, we'll change result of `search` from `Promise<Contact[]>` to `Promise<ContactPreview[]>` which will NOT be actually parsing anything, just returning `{email: string, name?: string, has_pgp: boolean, ...}`. That should speed up the performance issues I had.
