### ISSUE TITLE
Refactoring: perform /Att[A-Z']/ -> Attachment$1 renaming

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3257]
Another question: I noticed there was `Att -> Attachment` renaming recently. 

There are still some `/Att[A-Z']/` occurrences and I'm using `Mime.createAttNode()`

![image](https://user-images.githubusercontent.com/6059356/102474592-7f7f8100-4061-11eb-90a5-9d1bba245de1.png)

I guess we should also do `/Att[A-Z']/ -> Attachment$1`, if so I'd prefer it to be done in separate PR not to mix the fix and the refactoring in one PR.

_Originally posted by @limonte in https://github.com/FlowCrypt/flowcrypt-browser/issues/3256#issuecomment-747343528_

**Comment by tomholub** [comment]
Assignign to @bilalashraf123 to gain some familiarity with the chrome extension.
