### ISSUE TITLE
FlowCrypt signature

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3266]
@tomholub what do you think about promoting FlowCrypt by adding its signature to the user's signature?

> Sent with FlowCrypt Secure Email.

Something similar to what ProtonMail is doing:

![image](https://user-images.githubusercontent.com/6059356/102795047-e9c35900-43b4-11eb-8f72-00f55ae42545.png)

I personally think that it is polite and at the same time efficient way to promote the product. Users with the subscription will be able to disable inserting that signature to their emails (+1 subscriber-only feature to promote)

**Comment by tomholub** [comment]
I thought about this many times, and decided against (because it annoys me a tiny bit when I see it on PM). It's really hard to say if it's a better idea to leave it out or add it in, but I'll skip this time. Thank you for the good suggestion!
