### ISSUE TITLE
[Rich-Text] Inserting wide (> 600px) images

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3267]
Currently, we don't have controls for changing the size of inline images:

![image](https://user-images.githubusercontent.com/6059356/102796763-6bb48180-43b7-11eb-85c6-8e0d05a3327e.png)

---

When pasting wide (> 600px) images, they are cropped:

![image](https://user-images.githubusercontent.com/6059356/102797028-c3eb8380-43b7-11eb-9ee4-12a3ad1e4160.png)

This can be fixed in 2 ways:

1. Add `max-width: 100%` to inline images (this is Gmail's default behavior)
2. Allow horizontal scrolling by removing `overflow-x: hidden` from  `#new_message table#compose td.text div#input_text`

As a user, I'd prefer the first option. Let me know your opinion @tomholub

**Comment by tomholub** [comment]
Agree. I thought we already did that. Maybe only when rendering received
message
