### ISSUE TITLE
use font-weight normal for reply buttons

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3290]
I find these slightly too loud:

![image](https://user-images.githubusercontent.com/6306961/103527706-a9ff7580-4e7a-11eb-95ed-8112f23ae68c.png)

and these more pleasant

![image](https://user-images.githubusercontent.com/6306961/103527735-b552a100-4e7a-11eb-9c41-f20faa203642.png)

Else they look great.

**Comment by limonte** [comment]
FYI In Windows it looks different because of the system fonts:

![image](https://user-images.githubusercontent.com/6059356/103595239-9b10d580-4f03-11eb-98d9-63671224d4e9.png)

![image](https://user-images.githubusercontent.com/6059356/103595247-a401a700-4f03-11eb-855b-e94a3f6de26d.png)
