### ISSUE TITLE
Wrongly claims that the signature is expired

### ISSUE THREAD

**Issue by patrakov** [FlowCrypt/flowcrypt-browser#3299]
I have received a message that FlowCrypt identifies as a message with an expired signature. It is attached to this ticket. However, if I download the message locally, then use `gpg --receive-keys 4644409808C171E05531DDEE054CB8F31343CF44` to receive the key, and then check it with `gpg --verify`, it doesn't complain about dates. Could you please investigate why FlowCrypt complains?
[example.zip](https://github.com/FlowCrypt/flowcrypt-browser/files/5773644/example.zip)

**Comment by tomholub** [comment]
Thank you for this report including the samples! We'll have a look.

If you have the time, could you please try in Mailvelope and see if it shows a different result? (they use similar tech to us)

**Comment by patrakov** [comment]
I have time but do not fully understand how to test Mailvelope safely given that I already have FlowCrypt. Namely, should I use a separate VM, install Chromium there, install Mailvelope, and then log into my gmail account? Won't that result in the automatic sync of the FlowCrypt extension and a conflict? (I did not actually try)

**Comment by tomholub** [comment]
You can temporarily disable FlowCrypt in the browser. Assuming chrome, open `chrome://extensions` and temporarily disable it there. There's a similar mechanism on Firefox. Then you can try to install Mailvelope next to it, too.

Otherwise you could just install it on another browser (Chrome vs Firefox) or another browser profile. Any of those mechanisms will keep things separated.

**Comment by patrakov** [comment]
It says "Incorrect signature".

**Comment by patrakov** [comment]
In fact it says "Incorrect signature" for everything in the debian-security mailing list.

**Comment by tomholub** [comment]
Thank you for checking. Seems like we get bit further in verifying it, but bump into the supposedly expired signature. We'll be taking a look.

**Comment by tomholub** [comment]
@bilalashraf123 if you can reproduce this issue, please create a minimal repro script with only openpgp.js and the public key / signed data that you can submit to openpgp.js maintainers.

**Comment by patrakov** [comment]
1. I can't, as I don't know javascript.
2. Today the email from debian-security verifies successfully. So something either on your side or on the keyserver (or just switching to Mailvelope and back) fixes the issue.

**Comment by tomholub** [comment]
Is it the same email, now working?

That sounds like maybe it was signed with a signature with a "future" date, or one of it's keys only became available at a future date.

**Comment by patrakov** [comment]
Nope, the same email is still marked as having an expired signature. The same applies to other emails written by Salvatore Bonaccorso <carnil@debian.org> and sent via debian-security-announce. But there are emails on that list (sent by Moritz Muehlenhoff <jmm@debian.org>) which verify successfully. So:

1. I need more sleep.
2. I need even more sleep.
3. The problem that _everything_ on debian-security fails to validate is specific to Mailvelope. Flowcrypt so far only fails to validate messages from a specific person.

**Comment by patrakov** [comment]
OK, I think the problem is with the key itself.

Here is what Flowcrypt thinks about the key:

```
Type: openpgp
Fingerprint: 04A4 407C B914 2C23 030C 17AE 789D 6F05 7FD8 63FE
Users: carnil@cpan.org, carnil@debian.org, bonaccos@ee.ethz.ch, carnil.debian@gmx.net, salvatore.bonaccorso@gmx.net, salvatore.bonaccorso@gmail.com, salvatore.bonaccorso@livenet.ch
Created on: Mon May 11 2009 10:11:42 GMT+0600 (Екатеринбург, летнее время)
Expiration: Thu May 09 2019 09:11:42 GMT+0500 (Екатеринбург, стандартное время)
Last signature: Mon May 23 2016 00:42:42 GMT+0500 (Екатеринбург, стандартное время)
Expired: yes
Usable for encryption: false
Usable for signing: false
```

The key itself is attached, in two versions: as seen by flowcrypt and as seen by gpg.

[key-as-seen-by-flowcrypt.txt](https://github.com/FlowCrypt/flowcrypt-browser/files/5801061/key-as-seen-by-flowcrypt.txt)
[key-as-seen-by-gpg.txt](https://github.com/FlowCrypt/flowcrypt-browser/files/5801062/key-as-seen-by-gpg.txt)

**Comment by patrakov** [comment]
If I import the key as seen by gpg into flowcrypt, then the signature verified successfully.

**Comment by tomholub** [comment]
Got it - FlowCrypt just had an old version of the key. This is something we are working to resolve - keep things fresh over time automatically. Thank you for looking into this! I'll close this, as the fix will be in a different repository.

**Comment by tomholub** [comment]
For our internal needs, the relevant issue is tracked at https://github.com/FlowCrypt/flowcrypt-attester-ts/issues/59
