### ISSUE TITLE
check security of cid replacements PR

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3301]
@tomholub the PR is ready for review 🚀 

@seisvelas please evaluate the security of the `extractInlineImagesToAttachments()` method

Thanks!

_Originally posted by @limonte in https://github.com/FlowCrypt/flowcrypt-browser/issues/3256#issuecomment-750590830_

**Comment by seisvelas** [comment]
Everything looks perfectly tidy and sanitized just fine to me, I don't see any way this could be used to attack the recipient.

I do have one question about this though, specifically this method:

https://github.com/FlowCrypt/flowcrypt-browser/blob/5008408cad94e84be29f86f10582a4378c3cbafe/extension/chrome/elements/compose-modules/compose-send-btn-module.ts#L183-L192

It seems we assume that the the image src is a data uri. What if there is an image in a PGP/MIME email with src set to an external URL (ala some.site/image.png)? Will this just break?

**Comment by limonte** [comment]
> some.site/image.png

Hey @seisvelas and sorry that it took so long for me to answer your question here. The answer is: yes, it'll just fail with unexpected `src` values of inline images. That's of course not how it should be, thanks for noticing!

The PR is coming.
