### ISSUE TITLE
accumulating drafts cause live gmail tests to fail

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3315]
Example failure: https://flowcrypt.semaphoreci.com/jobs/3a01ea85-c237-4140-b189-34108f5d5b08

The solution could be to call an API that deletes all drafts on Gmail before start of the test. However, the test code that runs on nodejs does not have the right permission, only the browser extension does (after the login step). There are three options how to solve it that come to mind:

a) somehow extract the necessary access token from the browser extension after login step, and then make a call from NodeJS to delete all drafts.
b) create a separate miniapp for tests where the nodejs app will use puppeteer to log in and authenticate. The resulting code will be scraped from the window after authentication, then nodejs requests access token manually, and then uses it to delete the drafts.
c) find out why are we leaving drafts behind in some other test, and adjust the test to always make sure to delete the draft using Gmail UI at the end of a test

![image](https://user-images.githubusercontent.com/6306961/104477957-a3c77280-55b9-11eb-999b-eaba715387a7.png)

**Comment by tomholub** [comment]
This seems to be consistently affecting tests. @rrrooommmaaa please have a look later. Some test is leaving behind drafts on Gmail. It seems to be relatively recent.

**Comment by rrrooommmaaa** [comment]
> c) find out why are we leaving drafts behind in some other test, and adjust the test to always make sure to delete the draft using Gmail UI at the end of a test

I assume this can happen as a result of a test crash.

**Comment by tomholub** [comment]
That was my assumption too. But sometimes I feel even successful tests cause this, given the rate at which we are getting these.

If you need to log into that account to see, you can grab the credentials from test secrets.
