### ISSUE TITLE
switch browser extension to OpenPGP v5

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3324]
Not ready yet, but hopefully in a few months it will be

**Comment by tomholub** [comment]
This will be a massive effort, I think. We may wait until later in the year to do this.

**Comment by tomholub** [comment]
Maybe late October.

**Comment by IvanPizhenko** [comment]
@tomholub  There's PR #3955 initiated by dependabot

**Comment by limonte** [comment]
@IvanPizhenko I guess our `openpgpjs-custom.ts` middleware is not compatible out of the box with the proposed OpenPGP.js upgrade
```
Cannot read property 'Key' of undefined
  › Object.<anonymous> (test/source/core/crypto/pgp/openpgpjs-custom.ts:36:12)
  ```

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/issues/3955#issuecomment-913197886_

**Comment by limonte** [comment]
There are loads of incompatible changes in OpenPGP.js v5 - the API all changed, has been modularized - individual methods can now be imported separately. Global config mechanism was changed or replaced/removed. Many internals were refactored.

On the other hand, some of the functionality we implemented manually (forbidding rsa1024) now has mechanisms for it in the library.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/3955#issuecomment-913806111_

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa @tomholub I can now start working on this one, but we will face here the same issue as in the FES, because library is added here in the same way as in FES (or to say more correctly, it is in the FES the same way as here).

**Comment by tomholub** [comment]
There will be additional issues we will run into here:
 - `pgp_block.htm` frames intentionally don't have OpenPGP.js imported, and instead do operations by calling a background page that does have it imported. This was an optimization - loading openpgp.js took nearly 500ms depending on device, per iframe. If you had a conversation with 40 messages (40 iframes each with own openpgp.js), that would be 20 seconds just loading the pages before any of the actual page functionality (like decrypting / rendering each message) can begin. This calling to background page introduced some friction.
 - OpenPGP.js v4 had built-in mechanism for worker threads, which were initiated on background page. OpenPGP.js v5 has no such functionality and we'd have to write our own worker mechanism. This is so that more messages can be decrypted in parallel if the CPU is multi-threaded. This is again important when decrypting whole conversation.
 - we did quite a few modifications of OpenPGP.js v4 behavior - to mind comes ignoring weak ciphers like rsa1024. This functionality is supported by OpenPGP.js v5, and so we should remove our custom code (which is quite complicated) and use v5 functionality instead.
 - we use library internals when doing signature verification, and it may not be trivial after we switch to v5 if the internals changed or are no longer exposed. Hopefully this will mean we can simplify our code and use more friendly interfaces. Whether that will be difficult or not, I'm not sure.

@IvanPizhenko this will be quite a project to do this on flowcrypt-browser. Let's do another simpler one. We also use OpenPGP.js v4 on encrypted contact page https://flowcrypt.com/docs/guide/send-and-receive/encrypted-contact-page.html which is this repo: https://github.com/FlowCrypt/flowcrypt-web/invitations and this issue: https://github.com/FlowCrypt/flowcrypt-web/issues/486 . The repo covers two functionalities: the ECP mentioned and also password-protected messages for consumers, which is very similar to what you've just done on the FES. Let's do this one first.

**Comment by tomholub** [comment]
Un-assigning for now, while I need Ivan's work server-side.
