### ISSUE TITLE
can the extension be convinced to encrypt with TripleDES?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3326]
OpenPGP has a notion of preferred algorithms, see https://tools.ietf.org/html/rfc4880#section-13.2. These are enumerated in the public key. Depending on the version of the protocol, there will be a particular "implicit" algorithm that is assumed to be supported regardless of what is listed - in the version above, which is the most commonly used right now, TripleDES is the implicit one.

Per spec at https://tools.ietf.org/html/rfc4880#section-9.2 TripleDES is a must-implement algorithm.

Contrary to that, the OpenPGP.js library says at https://github.com/openpgpjs/openpgpjs#encrypt-and-decrypt-uint8array-data-with-a-password that _"Encryption will use the algorithm specified in config.encryption_cipher (defaults to aes256), and decryption will use the algorithm used for encryption."_. That sounds to me like when encrypting, AES256 is ALWAYS used unless we set something else in the config.

Please construct a public key (with GnuPG or OpenPGP.js or otherwise) that only ever wants to use TripleDES and no other symmetric algorithm. Please post it here, then try to encrypt a message for it using the extension. What happens?

**Comment by seisvelas** [comment]
FlowCrypt will indeed respect the algorithm preference specified in the public key, per the RFC. I want to tell you that up front, but since you probably want to know how I came to that conclusion, I describe the process below -

---

I've made a key and set 3DES as the sole algo in the preferred symmetric algorithms list, and verified like so:

```
alex@home:~$ gpg --export -a 3D307AA7242782A0F23F10F3744AEB778AFC9B2B | gpg --list-packets | grep pref-sym-algos
	hashed subpkt 11 len 1 (pref-sym-algos: 2)
```

So the only preferred algo is number 2. If we look that up in the GPG source code, we see that 2 does indeed refer to 3DES:

```C
typedef enum
  {
    CIPHER_ALGO_NONE	    =  0,
    CIPHER_ALGO_IDEA	    =  1,
    CIPHER_ALGO_3DES	    =  2,
    CIPHER_ALGO_CAST5	    =  3,
    CIPHER_ALGO_BLOWFISH    =  4, /* 128 bit */
    /* 5 & 6 are reserved */
    CIPHER_ALGO_AES         =  7,
    ...
}
```

Source: https://github.com/gpg/gnupg/blob/865d485180240369a20d3be14d0c6499783df2b5/common/openpgpdefs.h#L134

We can also confirm this using the showpref command in GPG itself:

```
gpg> showpref
[ultimate] (1). test mctesty (test)
     Cypher: 3DES
     Digest: SHA1
     Compression: ZIP, Uncompressed
     Features: MDC, Keyserver no-modify
```

Okay, so we've got a public key that explicitly and exclusively prefers 3DES. Here is the full public key:

```
alex@home:~$ gpg --export -a 3D307AA7242782A0F23F10F3744AEB778AFC9B2B 
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBGAGCokBDACyKhqiJ6Qd6AvqitY7p9KeQYimxvmJLtRDh1fFYIzIu92ASwqL
/Jivl32nrrhST+iZ+oMRmQbJrgXP8sizdZSKVXAclMLRMAViK9GTBvPIrg6Sb2l5
90hrHJCQrIUaTGiBX2UxGO72MJXsDkogCLwmakK1wH9/m72XeZhVSwiujrc/detH
uIGDWfBOiti5tXFfP3M2p/DI1/awHEC1m8TM09NPE+aWmEWMDrmzs/4+AIJhlBLu
ov337MCL/0tCBsU/xV0rYeBfPD8rLbWRvE23uqgJjpmX7dDQhTSsu/MM3itA/xKR
B7+dvd+C0x6g+rP1RobiIRMg+1XylVU1a6Ol8Agjbq9tx5iGSfQ+TnAcfRB848bF
v0gBBMyNP4NbD+r19Tt2QbSqcVdjjdqtt+R2n9pYlv8mgrwYZMtzZO7xmxrjLKHT
1RTUaveyaFluu4BBeyPlUeOf316UEDnCPwZ3mJpySAGUuGAOuW2UzaTm3PMqkx2A
hCnXZfPzFRZ6w0sAEQEAAbQvdGVzdCBtY3Rlc3R5ICh0ZXN0KSA8a2hldHlhdmls
ZXMxNjEyQGdtYWlsLmNvbT6JAb8EEwEKACkWIQQ9MHqnJCeCoPI/EPN0Sut3ivyb
KwUCYAYKiQIbAwILAgIeAQIXgAAKCRB0Sut3ivybK0XqDACTpM/I8x8WOw0xMxUK
Q8+sKODPaiNB85BZGzmn8xuXGc0O+h+BBu8iUzzOp2TLmRCyL3vJHG7IsTN2qjk2
A6Ed47K8MySG1vEn6D2lqMFDJ1kh6/B9Ec0Y8qkU7zsJm5uD/KV/xj2XSaFsKMPZ
qfgjYL/G9LlA6W0a4DJ0ZnYfdvPfbaFq3TnubyhxOxasHPOpYN4uGIWmhacLDHaU
TDbUM5/szNm62KFyUSB3lA2QtU8qPcxyCark9FFzEhY8NYgdjSpEIHyv3esg/U4N
J4Hfdg8PlpHsEzfnWK1qBn2WlVGlVDvhK/mGR9Ey6+ga1UPsBzWtw04CpGESIyDx
cJqexsZej/giREadOTH5ypnnUv3VjTIDSVhtcyC1Oy6kJIJ6YXm4wgTlLOmg6vzD
1dzU6Qj+6qOUvjC6WiYZmDGEzVte/LxfVqVBMfSErEl/osQsQhERb/ocviKkk6kI
u1UXMZNcwng/YmjkHe+FTEmiZY8AYvymNjCYWD5yIiuFB+m5AY0EYAYKiQEMALYT
7Tzq8u8E92q25YMjovHhrh2+4WQ8WqzINXL9iC/DvUCg8f1vV/NDpJbA7o+NRJl0
G5EVMf0Wtq2V6EjJqcpfro7w3I4bX7ZV33RVWqjFBvhUACLuX6uLezokTnxkfxdp
qt68ojJeLbuZWxTc5+IhLJ0p80imLvIqneJOCJ6GgzXl0C9fPCaU9jDR3Mp8sc2k
UymEKEZVlysyTXUVi/IYZiKqB7vCL2EtSeGB3pAwjHghxX2jK4HNs5ofHG+r9jeH
QKCorHVRe3GcU1ugUkNmNcSkaMKGRD2xkwULG7+DrAwbMFpDZp+Y+FyZOg36/J5w
Sp3lsJ7xKBRLH8qPC4n/Hc6q9O5wf/AE/xI5a2KIicu77WAoUL1Zod41yRwQ+L0X
hGMxR0aGBpki5LfcqfsqLdUb9ibTo2tMLamtSOrIUqMUQ14B3WXx9dCChyisovSE
/cIPDyfp+jWCPgMj0QvNUYnwV+WjMWr7GbAraojAMvlqadZUEvTwhq6Cs0ubbQAR
AQABiQG2BBgBCgAgFiEEPTB6pyQngqDyPxDzdErrd4r8mysFAmAGCokCGwwACgkQ
dErrd4r8myu3zgv/Zmqd7q4jYEBRYppfhDSPPGQc1cSlFiR+0FX6DO7oSWLxZXhX
9NqnVfqxJ/L99VLjpqNktncgWSo3E7eTnkc8EAsecQLOcx4r3fLsagzzy6ZP+UsG
Se4dzPJhw/MJzgRdg8XE0zx/ZJZZ2Q6jSpDg9BIzztMyobeDfmDfM2+1k2IEPWEq
SHZHyMXMaLdz+2PA6CPV52FgaYHV/ivUzz5SpV9tOMtNYjQ4tKkfDhkGwv14zEOi
39EqKpKpfZ0z+A1UiRnJoG2F1/08Q+LLLQvvHenErTgrxsgG1g5qBpIzn5/TUQle
V5BT3YprOvQVY3Y6VQrw3fiQZTwnCN9l2EtDAzOYpGls2rvZ7H6OIEwJQlgk/xLx
utRVxKoHB0dvMUz0yzsDVQJOCpXtwQsIfCsUW/Z15w40YOtuDHJrM7ZMYBZQhJYP
HiPpubrZO3yaHWzMa5/WT5fCz/xhFcRUgz0arxBuDDCkYWRVyDNJs1BObehNYKTE
YN159LSzV3cH1CMQ
=HOuM
-----END PGP PUBLIC KEY BLOCK-----
```

I imported this key to FlowCrypt for a contact (also me) and sent myself a message to that address using FlowCrypt's Secure Compose. Then I received the message and examined it with GPG. Here's what I saw when I examined the message with GPG to see what kind of symmetric encryption was used for the session:

```
alex@home:~/Downloads$ gpg -vv --show-session-key --list-packets 0xADAC279C95093207.asc 2>&1 | grep -B 3 3DES
gpg: using subkey 0C7CEB76846D3945 instead of primary key 744AEB778AFC9B2B
gpg: encrypted with 3072-bit RSA key, ID 0C7CEB76846D3945, created 2021-01-18
      "test mctesty (test)"
gpg: 3DES encrypted data
```

Taking note of the line saying '3DES encrypted data', we can conclude that FlowCrypt does indeed respect the preferred symmetric algorithms list in the public key, per the RFC.

**Comment by tomholub** [comment]
Thank you for looking into this - this highlights the difference: `config.encryption_cipher` is used for symmetric encryption that is password-based. Anytime it's using public-key encryption, it will follow the public key preferences. Thanks!

**Comment by seisvelas** [comment]
No problem!
