### ISSUE TITLE
Manual testing on Edge

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3327]
I faintly recall you may have already done manual testing on Edge?

Please give it one more spin to confirm the extension works well to set up, encrypt, decrypt, sign, verify messages and attachments. If it looks good, I'll submit it to the edge web store.

If the testing is positive, please assign the issue to me. Thanks!

**Comment by limonte** [comment]
Tested, all is well.

- [x] set up
- [x] encrypt 
- [x] decrypt
- [x] sign
- [x] verify messages and attachments

There is a tiny issue with styles:

![image](https://user-images.githubusercontent.com/6059356/105099089-c70b8980-5ab3-11eb-8a98-41427c670458.png)

**Comment by tomholub** [comment]
Excellent, thank you!
