### ISSUE TITLE
ability to store more than one public key per recipient

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3332]
Right now the extension will store only one public key per recipient email address.

For a smooth user experience with key rotations we need to add the ability to store more than one public key per recipient in the extension. That, combined with the WKD improvements in #3017 and #3018 will allow for a smooth experience during key rotation.

I haven't investigated exactly how the email-to-pubkey relationship is handled on the storage level, it could be a unique index on IDBDatabase. Maybe the index could be simiply dropped without migration. And then the following will need to be updated:
 - [ ] Store method used to retrieve one public key for one recipient should start to return an array of public keys
 - [ ] all code that uses that method downstream should start expecting that too
 - [ ] when the called from compose window, additional code needs to be added to decide which of the retrieved keys to use (some may be expired, some may be revoked - I'd recommend to use whichever valid key that has the most recent signature on it)
 - [ ] when called from pgp decrypt window to verify a signed message, key should be chosen by key id (therefore presumably no change there)

**Comment by tomholub** [comment]
@rrrooommmaaa please have a look to see how involved this change may be - particularly the database / unique index part.

**Comment by rrrooommmaaa** [comment]
@tomholub First refactoring thought: 
In `Contact` structure we have fields `longid` and `longids` and corresponding indexes: `index_longid` and `index_longids`.
`longid` is used to search for primary key and `longids` is used to search among primary and subkeys.
As we're going to have multiple pubkeys in contact, I suggest to drop `longid` field and `index_longid` index and use `longids` field to search.

**Comment by tomholub** [comment]
Instead of having multiple public keys in one contact, can we have one
contact per public key?

**Comment by rrrooommmaaa** [comment]
Currently, `email` is the key field for the Contact's object store. So we'll need to refactor this store to have a different key. I'm not an expert, but it may slow down the search by e-mail. The positive effect would be that there will be less refactoring in other portions of code.

**Comment by rrrooommmaaa** [comment]
> Maybe we could still make it the key (index), but not an unique one (if IDBDatabase supports that)

The key itself should be unique as the IndexedDB is a "key-value" type of the database, if I'm reading the right specs:
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Concepts_Behind_IndexedDB#concepts
```
Each record in an object store must have a key that is unique within the same store, so you cannot have multiple records with the same key in a given object store.
```

I think we may extend the key with pubkey fingerprint to make it unique (store it out-of-line, perhaps: https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Basic_Concepts_Behind_IndexedDB#gloss_outofline_key) and search the a key range to retrieve all records matching this email, like in this example
https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#specifying_the_range_and_direction_of_cursors

**Comment by tomholub** [comment]
Thinking about this, the ideal store structure (that I should have done from the beginning) would look like this:
1) a table with public keys where full key `fingerprint` is the index. There is never a reason to keep more than one public key stored if they have the same primary fingerprint, so we should de-duplicate on that.
2) an index table with email-fingerprint pairs. Here, the table key could be anything (like a random value, increement, or even a ligerally `$email-$fingerprint` value. The table will be used to look up fingerprints by email address you want to send an email to. Maybe also the reverse (look up emails that a public key is associated with - in settings).

This would also be a chance to fix up our messy database and code structure.

**Comment by rrrooommmaaa** [comment]
> a `search_index` with values like `[t, to, tom, f, fl, flo, flow, flowc, flowcr, flowcry, flowcryp, flowcrypt]` for `tom@flowcrypt.com`. We already do this, it would just get separated into its own table?

I see, this is `searchable` field of `Contact`, populated by `dbCreateSearchIndexList`.
So, if we have two tables: `Email` and `Pubkey`, do you suggest to have `searchable` field in `email` table?
So, in `Email` table (object store) will mainly have fields we currently have in `ContactPreview`: 
```
email
name
has_pgp
last_use (?)
searchable
fingerprints
```
?

**Comment by tomholub** [comment]
I don't know exactly what I want, but you are pretty close to it.

I have to take a second look. It's important to design it to minimize
chances that the two tables get out of sync. So the boundary needs to be
something that ensures the data remains meaningful without having to do
atomic updates on both (ideally).

**Comment by tomholub** [comment]
`email` table:
 - email (table key)
 - name
 - hasPgp (but only if we cannot search by `fingerprint.count > 0` - if that is possible and fast, then it would be preferable. IDBDatabase seems to also index arrays, so empty array should be searchable?)
 - lastUse
 - searchable
 - fingerprints (this refers to a list of primary fingerprints of keys associated with this email address)
 - pendingLookup

`pubkey` table:
 - armoredKey
 - parsedKey (??? or not? Something like this was there to speed things up but maybe it won't be needed once we split it into two tables? since it can contain outdated information)
 - fingerprint
 - longids
 - lastSig
 - lastCheck
 - expiresOn

Since we are changing things, I would propose `camelCase`. Anything is fine as long as the casing is consistent.

That means we may drop the `client` field. We'll see where is it used, if anywhere, and if that functionality can be dropped.

**Comment by rrrooommmaaa** [comment]
`pubkey` table:
`fingerprint` is the key, right?
`parsedKey` -- we don't currently store it as `Key`. There is a lot of headache converting it back and forth on load/save to ContactStore.
saved `parseKey` isn't usable anyway as it doesn't have functions, so parsing still happens from its hidden `raw` field.
The only benefit of `parsedKey` is to expose some string properties of it, so I'd suggest to add those properties to the table explicitly.
On loading a `pubkey` record, we're going to convert it (together with parent `email` record) to `Contact` (with parsing as we do now), but in a more explicit manner, so `Contact` structure will remain unchanged. For callers requesting `ContactPreview` parsing will be skipped.
Agree?

**Comment by tomholub** [comment]
>  fingerprint is the key, right?

Yes! Sorry, I forgot to update that - updated.

>  parsedKey -- we don't currently store it as Key. There is a lot of headache converting it back and forth on load/save to ContactStore. saved parseKey isn't usable anyway as it doesn't have functions, so parsing still happens from its hidden raw field.
The only benefit of parsedKey is to expose some string properties of it, so I'd suggest to add those properties to the table explicitly.

Perfect - less mess

>  On loading a pubkey record, we're going to convert it (together with parent email record) to Contact (with parsing as we do now), but in a more explicit manner, so Contact structure will remain unchanged. For callers requesting ContactPreview parsing will be skipped.

This sounds good.

**Comment by rrrooommmaaa** [comment]
@tomholub We omitted the field `client`. As I understood, it's need to display Flowcrypt logo for some keys? Do we still need this functionality?

**Comment by tomholub** [comment]
Can drop functionality that uses the client field, if any

**Comment by rrrooommmaaa** [comment]
It's mainly used in `reevaluateShouldAttachOrNot`

**Comment by tomholub** [comment]
I'll have to look deeper into this, I forgot we use it that way. I would prefer to not always attach the public key, especially if it's a FlowCrypt recipient where this is not needed.

**Comment by tomholub** [comment]
Still need to look into this

**Comment by tomholub** [comment]
answer here https://github.com/FlowCrypt/flowcrypt-browser/pull/3445#issuecomment-791414059
