### ISSUE TITLE
"Are you sure you want to send this email unencrypted?" alert

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3358]
When the user clicks the normal Gmail Compose button and tries to send an email, they get a warning alert saying "Are you sure you want to send this email unencrypted?"

Is this normal behavior of the extension? It doesn't happen for me at all. The user is on FlowCrypt chrome 8.0.0. 

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKkbqHRTkzLPsLnBLJqLSWQVkB

**Comment by tomholub** [comment]
Most likely they also have some other extension installed that does this.

**Comment by seisvelas** [comment]
I've asked them whether they do, will update this issue when I receive a response

**Comment by seisvelas** [comment]
Yep, it was another extension. Thanks, Tom!
