### ISSUE TITLE
tests: Could not find browser revision

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3359]
From @bilalashraf123 

> I am getting the following error when running "npm: test_local_chrome_consumer_mock" from VS Code
> 
> Error {
>     message: 'Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.',
>   }
>
> I ran the command in the above error message which went well, but I am still getting the same error

To me this looks like you are using a different version of npm. Here I'm on `6.14.6`. Please try to remove `node_modules`, update your npm (or try my version) then do `npm install` and then try the tests again.

**Comment by bilalashraf123** [comment]
Updated to: 

`node version to - v15.7.0.`
`npm version to - 7.4.3`

and then:

`npm install`

It worked fine.

**Comment by tomholub** [comment]
Great - it really was npm version.
