### ISSUE TITLE
could not get information from backend / platform not supported

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3368]
This is on MacOS / Firefox but more likely it's not platform specific. Sounds like something messed up on my account.

![image](https://user-images.githubusercontent.com/6306961/106491428-d34f0800-64f1-11eb-8948-df5dfc3f47fd.png)

Here's what likely caused that - which itself is not a problem - normally I can click ok and re-do auth.

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/6306961/106491906-4fe1e680-64f2-11eb-910e-d3d25def32be.png">

If I scroll down in there and click ok:

![image](https://user-images.githubusercontent.com/6306961/106491535-ed88e600-64f1-11eb-9f67-ffd1dda50fe4.png)

That seems like a bug on our end. It would be good to know where that error is coming from.

**Comment by tomholub** [comment]
To triage this, you can try the following:
 - set up an extension
 - go to settings -> Additiomal Settings -> Experimental -> Set a new randomly generated FlowCrypt Account UUID
 - now in settings, you should see "Please log in with FlowCrypt to continue." - ignore that
 - go to any encrypted conversation and find encrypted reply buttons (as per screenshot above)
 - Reply using one of the buttons
 - A new set of buttons re-render, and you should see the "Could not get information from backend" message - that is expected
 - after attempting to scroll down and clicking ok on that modal message, normally, it should allow you to re-authenticate. In my case, it showed me the "platform" error instead. Are you able to reproduce that error too?

In a separate issue, we should also fix the CSS on that message so that the modal is readable / clickable.

**Comment by limonte** [comment]
> after attempting to scroll down and clicking ok on that modal message, normally, it should allow you to re-authenticate. In my case, it showed me the "platform" error instead. Are you able to reproduce that error too?

For the record, I am able to reproduce the "platform" error in Firefox on macOS.

![image](https://user-images.githubusercontent.com/6059356/106747028-085f7580-662c-11eb-90ec-ad3c3441b05a.png)

In Chrome the error isn't happening, re-authentication works as expected after clicking the OK button in the "Could not get account information from backend." modal.

**Comment by tomholub** [comment]
I'm not sure if Bilal has a Mac handy. If this really is platform specific, maybe @limonte could have a look later

**Comment by bilalashraf123** [comment]
I have Windows and Ubuntu based machine.
