### ISSUE TITLE
fix modal rendering in iframes with low height

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3369]
To triage this, you can try the following:
 - set up an extension
 - go to settings -> Additiomal Settings -> Experimental -> Set a new randomly generated FlowCrypt Account UUID
 - now in settings, you should see "Please log in with FlowCrypt to continue." - ignore that
 - go to any encrypted conversation and find encrypted reply buttons (as per screenshot above)
 - Reply using one of the buttons
 - A new set of buttons re-render, and you should see the "Could not get information from backend" message - that is expected
 - after attempting to scroll down and clicking ok on that modal message, normally, it should allow you to re-authenticate. In my case, it showed me the "platform" error instead. Are you able to reproduce that error too?

In a separate issue, we should also fix the CSS on that message so that the modal is readable / clickable.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/3368#issuecomment-771012100_

@limonte please see if we can make this modal visually fixed / usable. The host frame has a low height so we just barely see the first line of the modal. We did some fix in attachment window. Maybe could do a css media query to do something similar when the frame height is small?

This is purely a request for a css fix, the functionality will be fixed in the originally referenced issue.

**Comment by limonte** [comment]
> after attempting to scroll down and clicking ok on that modal message, normally, it should allow you to re-authenticate. In my case, it showed me the "platform" error instead. Are you able to reproduce that error too?

For the record, I am able to reproduce the "platform" error in Firefox on macOS.
