### ISSUE TITLE
Compatibility with Horde IMP

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3376]
Horde IMP is a webmail program with builtin support for PGP. According to the user:

>I can send PGP encrypted mail to other addresses I have public keys for through Horde successfully, but not to my Gmail account using my FlowCrypt public key. 

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLsJxdPlnPQQJzBZQJzLzfzLCN

The best way to test this is to set up Horde IMP locally and figure out what's going wrong, so that's my plan.

**Comment by seisvelas** [comment]
Update: FlowCrypt *does* appear to be compatible with Horde. I was able to send encrypted email to my Gmail account and open it with FlowCrypt. This was from the same Horde server the user having this issue is sending from. 

So I do not think the problem is one of general incompatibility - maybe there is something wrong with the specific key the user is trying to encrypt with, or some other issue. 

I'll keep trying to figure out what's going wrong for this user, but I'm closing this issue because we *are* apparently compatible with Horde

**Comment by tomholub** [comment]
Thanks!

**Comment by seisvelas** [comment]
Weird, so I can encrypt mail to them just fine using FlowCrypt. But when I open their encrypted response that has their key attached to it, I see this below the decrypted message:

<img width="1170" alt="Screen Shot 2021-04-27 at 7 24 02 p m" src="https://user-images.githubusercontent.com/44826516/116332017-2dc4d100-a78e-11eb-8243-dc2129d901be.png">

```
This OpenPGP key is not usable.
-----BEGIN PGP PUBLIC KEY BLOCK-----Version: FlowCrypt Email Encryption 8.0.4Comment: Seamlessly send and receive encryptedemailxjMEYGXq+hYJKwYBBAHaRw8BAQdA33s2V9hZWmKYryg8vA1ClHTQpdoRFPvz8SHN8pHM/63NJUphcmVkIENvbGxpZSA8amFyZWQuY29sbGllQGdtYWlsLmNvbT7CjwQQFgoAIAUCYGXq+gYLCQcIAwIEFQgKAgQWAgEAAhkBAhsDAh4BACEJEB3aisS9VdNQFiEEgQqfjVt7ZdClLz3NHdqKxL1V01DbfAD9HVpCzpMXZO+00T1ZGGl/r4ToRyzvzM9ZqeV/+H1DTHwBAJMeIWvX+I+i8D3LaZpOv2ohxjlqSniI8tUlvTgylo4HzjgEYGXq+hIKKwYBBAGXVQEFAQEHQFkZhJhUJ+GJwIxCpesYUyH/SmN3nOQwpz4MXIpm5wFyAwEIB8J4BBgWCAAJBQJgZer6AhsMACEJEB3aisS9VdNQFiEEgQqfjVt7ZdClLz3NHdqKxL1V01D5twEAlpEi8I5GtEXP4p8H+V/LgAA3NV9C90O6lvAG/kLUD94A/1QW1nMGC16M0iWRWJDVG9wCqeaa/4svSR8JdcFSzWsJ=Y/Yv-----END PGP PUBLIC KEY BLOCK-----
```

The whole key appears on one line like that, although it's formatted properly (at least I think so) on the attester and in my contacts.

No idea what is wrong with the key, I'm stuck.

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLtkSCvTjzzjkxcHGxSmMtgFMT

**Comment by tomholub** [comment]
The key is missing newlines. Maybe an error when encoding, or when parsing, or somewhere in between.

Could you have one such email moved or sent to flowcrypt.compatibility inbox?

**Comment by seisvelas** [comment]
>The key is missing newlines. Maybe an error when encoding, or when parsing, or somewhere in between.

Indeed, I see that in the error message, but in my contacts the key does indeed have the appropriate newlines:

<img width="629" alt="Screen Shot 2021-04-28 at 12 30 55 p m" src="https://user-images.githubusercontent.com/44826516/116454822-9e66fe80-a81d-11eb-90c4-1c5689e4e959.png">

And I pasted the key into Horde from my contacts, and still got this error. So maybe it's some other formatting issue, or the rendering for that error just doesn't convert newlines into `<br>`'s or something similar?

Here's the email in flowcrypt.compatibility: https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/WhctKJWQntDZPPpkFwTBzdVlXdtrflDkCZFHzNnFqFfdHmmFJzHhFMDHtsJNTqmZKHMRDTG

I can't decrypt it due to 2fa issues (;_;) but it *should* have the same problem found in the support email linked in my previous comment.

**Comment by seisvelas** [comment]
Darn. So, when I decrypt the email in flowcrypt.compatibility, the "This OpenPGP key is not usable." message doesn't even appear. Rather, when the user attached their key and sent this email, it loaded just fine.
