### ISSUE TITLE
SweetAlert2 method onClose is deprecated, replace with willClose

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3393]

**Comment by limonte** [comment]
I missed this one in https://github.com/FlowCrypt/flowcrypt-browser/commit/334a4c9135e5c089524d8a054860b1d9b9ec68da

**Comment by seisvelas** [comment]
@limonte I happened to notice the warning while installing the Chrome extension, glad I could be useful in some small way
