### ISSUE TITLE
The cursor isn't staying in the viewport when inserting new lines in reply box

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3403]
### Actual behavior

https://user-images.githubusercontent.com/6059356/107156286-27d90400-6986-11eb-9956-d2037dd57a7e.mp4

Cursor is below the viewport, it'll be visible again once user types any character, but `Enter/Return` for some reason doesn't keep the cursor in the viewport. 

### Expected behavior

The cursor is always in the viewport.

**Comment by tomholub** [comment]
Well noticed, thanks!

**Comment by limonte** [comment]
Reported to the squire repo https://github.com/neilj/Squire/issues/402

Let's see if it'll be fixed there, if not then I'll start investigating.

**Comment by limonte** [comment]
Hold on, this was already reported and supposedly fixed: https://github.com/FlowCrypt/flowcrypt-browser/pull/2401/files

Let me investigate that.

**Comment by limonte** [comment]
The memory isn't the best feature of my brain, that's why it's good to write down all the tracks for the future self 😆

**Comment by limonte** [comment]
Right, #2400 is fixed indeed, it was about the new secure message window. This issue is about the reply box.
