### ISSUE TITLE
Properly test `KeyUtil.dearmor` and possibly move to a different class

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#3407]
Following conversation in #3404 
we need to test how this method behaves on incorrect and/or large input.
As it can be used not only for keys, we need to think of a proper name/class for it.

**Comment by tomholub** [comment]
Excellent, I very much like that you think about and notice things like this. It's a subtle concern (a method that is not that well tested that is exposed in public API, kind of looking like a stable method that someone else may end up using and potentially cause trouble).

It shows a real maturity as a developer to think about this, and makes me want to maybe involve you in helping me with code reviews. I know you did code reviews this in another project. What is your preference? Do you prefer to just code, or do you prefer to do code reviews over coding, or both/doesn't matter either way?

**Comment by rrrooommmaaa** [comment]
@tomholub Thanks for appreciation, Tom. Reviewing code is simpler for me, since I only have to criticize, whereas during coding, I have to code AND criticize myself, he-he) On the other hand, a bit of coding now and again breathes life into me, so it’s cool to do it too. Generally, I can do both so I’d rather let you decide what proportion of code/review would be most beneficial for the projects you mentioned.

**Comment by tomholub** [comment]
Sounds good. I think I will be making it a requirement to get two reviews per PR. That way, initially it would be typically me + one more person (often you). Then over time, it could be typically two people who are not me - then I can lower my workload.
