### ISSUE TITLE
Set key expiry?

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3412]
Is there a way to set when the key expires using the browser extension? And if not, do we have any interest in eventually adding such functionality?

https://mail.google.com/mail/u/human@flowcrypt.com/#search/GPG/FMfcgxwLsSWMbTlTNmZkQDnGmmgFXWQg

**Comment by tomholub** [comment]
We currently only have this option when using FlowCrypt for Enterprise when the expiration is set on a domain-wide level for all users. 

Eventually we'll also add this option for individual / free users to set manually, but probably not this year.

**Comment by tomholub** [comment]
You should let the user know, just in case they are looking into this on behalf of a company.

**Comment by seisvelas** [comment]
I've informed the user, thanks for letting me know!
