### ISSUE TITLE
removing testdata.json

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3422]
from @bilalashraf123 

> There are now two test JSON files i.e. "testdata.json" and "test-secrets.json". It is not clear which files covers which area of tests.

--------------------------------

testdata.json is checked into the repository, test-secrets.json is not.
Therefore when the item is sensitive (customer information or live credentials), it goes into `test-secrets.json`. Else it goes into `testdata.json`. 

Actually, I may want to remove `testdata.json` completely and have non-sensitive fields declared in code.

**Comment by martgil** [comment]
Got it Tom! Working on it asap, Thanks!
