### ISSUE TITLE
pgp/mime message disappears on first loading

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3423]
Unfortunately the issue still resurfaced. I'm on Firefox with version 8.0.2

**Comment by limonte** [comment]
I guess it's the same as #3180 ?

**Comment by tomholub** [comment]
Yes, it's the same.

In my observations, it seems to take a bit longer to disappear sometimes. There seems to be a distinct "all rendered now", then a 2-3 seconds pause - maybe, and then "poof".

**Comment by limonte** [comment]
I'll switch to Firefox as my primary browser to be able to catch this issue (not happening on Chrome)

**Comment by tomholub** [comment]
Thanks for having a look! It was bothering me for a while.

**Comment by tomholub** [comment]
Glad to hear it wasn't happening on Chrome.

**Comment by tomholub** [comment]
Me neither at the moment.
