### ISSUE TITLE
more robust message delete during tests

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3428]
This deletes a message in a not very robust way - and not clear which message.

@rrrooommmaaa had a piece of code that deleted messages - I'll merge this and then make another issue about using that instead (it calls the Gmail API - more robust).

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/3426#discussion_r576607394_

**Comment by tomholub** [comment]
@limonte thank you for the fix - which particular message was it trying to delete?

**Comment by limonte** [comment]
> @limonte thank you for the fix - which particular message was it trying to delete?

In that test I'm opening a secure message and sending a secure reply. After sending the reply, I want to delete it in order for that thread not to grow big.
