### ISSUE TITLE
Contacts suggestions dropdown isn't fitting vertically into the reply box

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3436]
### Actual behavior

![image](https://user-images.githubusercontent.com/6059356/108208521-cfe29000-7131-11eb-9ebc-9eac328bd548.png)

### Expected behavior

The dropdown should have 

```css
max-height: calc(100% - 45px);
overflow-y: auto;
```

![image](https://user-images.githubusercontent.com/6059356/108208944-59925d80-7132-11eb-8fd8-cd069f86f17a.png)

**Comment by tomholub** [comment]
Thanks!
