### ISSUE TITLE
not encrypting with weak keys - using preference settings

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3444]
Once we move to OpenPGP.js v5, I wonder if this PR would address the need we had in #2715 ?

It would be cleaner that way: https://github.com/openpgpjs/openpgpjs/pull/1238

I haven't investigated it in detail.

**Comment by alichry** [comment]
Hey @tomholub ✌️

I would be interested in this as I wrote similar helper functions when it comes to dealing with keys, one of those is `canEncrypt` which is similar for `usableForEncryption`. it does not check the validity of the public key, just the underlying algorithm info. I would be happy to submit a PR that adds a `usabeForEncryption` method to `Subkey`

Something like that and we check the RSA bits? (definitely rewritten in the context of `Subkey`)

```ts
/**
 * checks whether the underlying algorithm is suitable for encryption
 * regardless of the validity of the signature
 * @param key 
 */
export const canEncrypt = (key: OpenpgpKey) => {
    const keyPacket = getKeyPacket(key);
    if (! keyPacket) {
        return false;
    }
    const r: any = enums.read;
    if (! keyPacket.algorithm) {
        return false;
    }
    return keyPacket.algorithm !== r(enums.publicKey, enums.publicKey.rsa_encrypt) &&
        keyPacket.algorithm !== r(enums.publicKey, enums.publicKey.elgamal) &&
        keyPacket.algorithm !== r(enums.publicKey, enums.publicKey.ecdh);
}
```

**Comment by tomholub** [comment]
Hello, thanks for reaching out!

@rrrooommmaaa may be a better fit for answering.

**Comment by alichry** [comment]
Whoops, sorry for that. I thought it's the openpgpjs/openpgpjs repository

**Comment by tomholub** [comment]
No wonder :) Feel free to create a sister issue there, and link this too. My usecase is that I don't want to use certain algorithms, like RSA less then 2048 bits, or SHA1, or 3DES, ever. We did make this work with v4 openpgpjs library but it feels like a workaround the way we did it, it would be nicer to have that option straight in the library :+1: for which your PR may have helped.

**Comment by tomholub** [comment]
Here's another conversation that may simplify this for us: 

https://github.com/openpgpjs/openpgpjs/issues/1243

**Comment by tomholub** [comment]
on our end we've already done this

**Comment by tomholub** [comment]
on our end we've already done this
