### ISSUE TITLE
Popup message improvement when sending password protected email

### ISSUE THREAD

**Issue by bilalashraf123** [FlowCrypt/flowcrypt-browser#3449]
![image](https://user-images.githubusercontent.com/24797522/108603618-cfb0f180-73ca-11eb-8949-8ccf1992078d.png)

I believe the second message also talks about message expiry limit. 

May be we could improve this message to something like this:

**Messages sent to FlowCrypt users have no limit for message expiry and don't need password exchange**

Thoughts?

**Comment by tomholub** [comment]
Definitely

**Comment by tomholub** [comment]
I imagine this kind of thing you'd be able to change :smiley:
