### ISSUE TITLE
Add option to generate password when sending emails to non FlowCrypt users

### ISSUE THREAD

**Issue by bilalashraf123** [FlowCrypt/flowcrypt-browser#3450]
There could be following options:

- Provide both options and let the user to either enter the password manually or generate it by clicking on generate password button.
- Provide generate password option only.
- Control this behavour using Org rules.

Also provide note in any case that FlowCrypt never stores this password. May be in the popup message.

There are few advantages of generating the password:
- It generates the password with sufficient randomness and security level.
- Assume a case where `user1@gmail.com` sends a message to `user2@gmail.com` and choose some password. Later the same user sends an email to different user and choose the same password (most users are habitual of doing this). If we let the system to generate the password, then some level of security gain could be achieved.

Thoughts?

**Comment by tomholub** [comment]
Agree. I will set it as a lower priority for now but I think this would be a good improvement.

**Comment by tomholub** [comment]
worthwhile eventually but for now closing
