### ISSUE TITLE
more properly display errors when decrypting attachments

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3464]
According to a user:

> i have problems with viewing / downloading encrypted attachments.
> then i get the error message:
> "Error downloading file - Error: Session key decryption failed.."
> Please fix this problem.
> If you need further information do not hesitate to contact me

They followed up with more details about the message:

> the mail is from an automated process i have no control over.
> it is readable but not encrypted. only the attachment is encrypted.
> What software this process uses i am not sure of.

I can send them an attachment just fine, so it's only a problem with this correspondent. Here is the full console output when this occurs:

```js
2DevTools failed to load SourceMap: Could not load content for chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/purify.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/lib/pdf.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
catch.js:55 Error: Session key decryption failed.
    at AttachmentPreviewView.decrypt (VM299 attachment_preview.js:100)
    at async AttachmentPreviewView.render (VM299 attachment_preview.js:24)
    at chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/async chrome-extension:/bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/view.js:27
    at <async> decrypt (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/extension/chrome/elements/attachment_preview.ts:84)
Catch.onErrorInternalHandler @ VM308 catch.js:55
Catch.reportErr @ VM308 catch.js:78
AttachmentDownloadView.renderErr @ VM305 attachment.js:123
AttachmentPreviewView.render @ VM299 attachment_preview.js:66
async function (async)
AttachmentPreviewView.render @ VM299 attachment_preview.js:23
(anonymous) @ VM311 view.js:27
run @ VM311 view.js:34
(anonymous) @ VM299 attachment_preview.js:14
catch.js:59 [Session key decryption failed.]Error: Session key decryption failed. at AttachmentPreviewView.decrypt (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/attachment_preview.js:100:23) at async AttachmentPreviewView.render (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/attachment_preview.js:24:55) at async chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/view.js:27:21 at <async> decrypt (/extension/chrome/elements/attachment_preview.ts:84:20)
catch.js:274 FlowCrypt ERROR: Please report errors above to human@flowcrypt.com. We fix errors VERY promptly.
```

I'm unsure how to move forward in debugging this, any assistance is appreciated :)

**Comment by seisvelas** [comment]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjdxgpLVXKBXbSxkSHXQLZJvb

**Comment by tomholub** [comment]
Session key decryption failed is a cryptic way to say that the attachment is encrypted for a wrong public key. That's why they can't open it.

**Comment by seisvelas** [comment]
User never got back to me. Closing.

>Session key decryption failed is a cryptic way to say that the attachment is encrypted for a wrong public key. That's why they can't open it.

Thanks for explaining! Perhaps I should change the error message to explain that this is a likely cause?

**Comment by tomholub** [comment]
You could render the contents of `result.error.type` and `result.error.message`, which should together hopefully render something more meaningful. You can see the key mismatch label on `flowcrypt.compatibility` account to find a message that you can test this on.

**Comment by tomholub** [comment]
Nothing wrong with a subkey used for encryption - we support that usecase regularly.

**Comment by ioanmo226** [comment]
Is this issue still active, @tomholub?

**Comment by tomholub** [comment]
i believe so. you may triage to confirm. go through decrypt error and attachment label on compatibility account, there should be one badly encrypted attachment to test

**Comment by ioanmo226** [comment]
ok
@martgil Please forward this to my email
> ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjdxgpLVXKBXbSxkSHXQLZJvb

**Comment by ioanmo226** [comment]
@tomholub error message and type is same as current image.
I think there's not much more we can do?

![image](https://user-images.githubusercontent.com/77344191/208059504-a728e7d5-cfe9-4a7c-a0d6-9a685b91de0f.png)

![image](https://user-images.githubusercontent.com/77344191/208060319-046f3b0d-1f60-48fe-ac36-9fa472a5910a.png)


> You could render the contents of result.error.type and result.error.message, which should together hopefully render something more meaningful. You can see the key mismatch label on flowcrypt.compatibility account to find a message that you can test this on.

**Comment by martgil** [comment]
> Please forward this to my email

yes, sir. Just forwarded the email. thanks!

**Comment by tomholub** [comment]
> @tomholub, the error message and type are the same as the current image.
> I think there's not much more we can do?

I can see screesnhot of what it looks like for the user? That's what matters.

**Comment by tomholub** [comment]
that's an error in the console, nobody will look at it. the error should be rendered inside the attachment icon for example

**Comment by ioanmo226** [comment]
You mean render `Session key decryption failed` instead of `Failed to decrypt` error message?
![image](https://user-images.githubusercontent.com/77344191/208630956-b7687d3a-c591-4c7a-a0d2-a5af08cf8d1a.png)

**Comment by tomholub** [comment]
Ok, now I see that is not console, but an actual html view, that user can see.

I got confused earlier, this issue is already fixed.
