### ISSUE TITLE
Flaky test: "settings - feedback form"

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3468]
Happened several times already and causing dependabot PRs to fail, e.g. https://github.com/FlowCrypt/flowcrypt-browser/pull/3467

https://flowcrypt.semaphoreci.com/jobs/fa53d1c4-b6a7-45d4-9843-54b8ea519b4e

**Comment by limonte** [comment]
I am able to reproduce the issue sometimes. It looks like this:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/6059356/109798993-1ea92300-7c24-11eb-8c86-de1224bfcb04.png">

<img width="418" alt="image" src="https://user-images.githubusercontent.com/6059356/109799029-2c5ea880-7c24-11eb-913e-62bc00c3ead4.png">

**Comment by limonte** [comment]
And sometimes the form works as expected:

<img width="530" alt="image" src="https://user-images.githubusercontent.com/6059356/109799481-c7578280-7c24-11eb-885a-3e40fc1ee368.png">

So I believe there's a bug in the `/api/help/feedback` endpoint.

**Comment by tomholub** [comment]
This is correctly blocking security issues:

![image](https://user-images.githubusercontent.com/6306961/109800826-96bc1c80-7c15-11eb-91b8-f2292b070b54.png)

But we're not doing a good job at showing that to the user. But it won't be doing that randomly - it's always supposed to block users from flowcrypt.com domain.

**Comment by tomholub** [comment]
Hahaha it may be a bit of an edge case - `flowcrypt.compatibility` contains `flowcrypt.com` ...

**Comment by limonte** [comment]
> Hahaha it may be a bit of an edge case - `flowcrypt.compatibility` contains `flowcrypt.com` ...

But I still don't understand why the behavior is flaky, sometimes it matches, sometimes it's not.

**Comment by tomholub** [comment]
Sounds like one server was not properly upgraded, which would be a real problem.

**Comment by tomholub** [comment]
When you say sometimes - do you submit the same form 20 times and one time it fails? Or how exactly?

**Comment by tomholub** [comment]
Given that this is supposed to never work (which I'll cross check on backend), we may want to add this to mocked backend endpoints instead of forwarding this. That will fix the issue on browser.

Because once we fix it on backend, the result will be that all test runs here will fail.

**Comment by limonte** [comment]
> When you say sometimes - do you submit the same form 20 times and one time it fails? Or how exactly?

Roughly 50/50

**Comment by tomholub** [comment]
fixed in #3492
