### ISSUE TITLE
users being redirected back to setup / login when setting up FlowCrypt

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3478]
I've received a few support emails about this:

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLsmmxflHNqqlhGfDQtXQFfdnG
ref: https://mail.google.com/mail/u/2/#search/uninstall/FMfcgxwLsmgDjRwlkvMPMCQgpNwffrJM
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#search/login/FMfcgxwLsmhNzVxFGrHRgWvhptXbDBCT

I am sure there was another user who had this same problem as well, but I couldn't find them. The problem is basically this: they go through the setup process, and at some point are just sent back authenticate with Gmail and start all over, ad infinitum

Maybe some security setting or extension or something causes this. I'll be emptying support tomorrow so I'll ask the best questions I can to get to the bottom of this.

I'll update this issue if I get any responses from users.

**Comment by tomholub** [comment]
Try setting up on a blank browser profile. If they use Firefox, do a test to set up on Chrome and vice versa.

**Comment by seisvelas** [comment]
ref: https://mail.google.com/mail/u/2/#inbox/FMfcgxwLswJQPTDnwzhmcLXWHcmKQfMR

**Comment by seisvelas** [comment]
The last user who reported this turned out to be using advanced protection, and the others never got back to me. No one has reported this since. I'm closing, will reopen if the problem reoccurs.
