### ISSUE TITLE
Flaky test - secure reply btn, reply draft

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3481]
Okay, I reran the tests for the last commit to master (which passed when the commit was merged) and they are now failing: https://flowcrypt.semaphoreci.com/workflows/9ba160ab-2172-4a99-85ca-234edf401adc?pipeline_id=320a823f-bbcf-41db-8052-d2f11c0bbe7f

So I don't believe this is related to this PR specifically.

_Originally posted by @seisvelas in https://github.com/FlowCrypt/flowcrypt-browser/issues/3480#issuecomment-796663205_

**Comment by limonte** [comment]
This one is the reason for failures in "standard test group": https://github.com/FlowCrypt/flowcrypt-browser/issues/3468

**Comment by limonte** [comment]
I'll handle the flaky live test in scope of this issue

```
  mail.google.com - secure reply btn, reply draft
    ℹ (attempt 1 of 3) Retrying: Error: waiting failed: Elements did not appear: [data-test="input-body"]
    ℹ (attempt 2 of 3) Retrying: Error: waiting failed: Elements did not appear: [data-test="input-body"]
    ℹ (attempt 3 of 3) Failed:   Error: waiting failed: Elements did not appear: [data-test="input-body"]
```

**Comment by limonte** [comment]
Argh, this test failed again https://flowcrypt.semaphoreci.com/jobs/addb1263-4aa9-4de3-aa17-1986df328386

**Comment by limonte** [comment]
😭 failed again https://flowcrypt.semaphoreci.com/jobs/4b202b58-7673-479d-b54a-607762821704
