### ISSUE TITLE
how to extract unit test cases for MsgBlockParser.detectBlocks from integration tests?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3482]
In this repo we run many integration tests, that tend to also use the detectBlocks method.

Now we're trying to port this functionality to Kotlin at https://github.com/FlowCrypt/flowcrypt-android/issues/1052#issue-821114723 but we only have three unit tests for this method, most of the testing is done through integration tests.

@rrrooommmaaa how could we extract the data inputs/outputs for that method for a whole test run, deduplicate them and export them? This would be very valuable when porting similar functionality. We will be doing more porting in a similar way upcoming weeks/months, so it would be great to have a way to do this, even if we don't necessarily check any tooling in (depending on what you think).

**Comment by rrrooommmaaa** [comment]
1) we can standardize the tests and pass input/output in a strictly defined structure, in a way we do `BrowserRecipe.pgpBlockVerifyDecryptedContent` passing a `TestMessage` structure as input.
2) we can possibly build (borrow from somewhere?) a transpiler from TypeScript to Kotlin, using Peg.js or ANTLR. Of course, more costly (at start) but more flexible afterwards. I googled an existing one here https://github.com/Kotlin/dukat

**Comment by tomholub** [comment]
Option one would be nice for other reasons - test clarity, and easier to write tests. Bilal had trouble contributing initially #3419 for a related reason, and this would have helped. But it doesn't directly address this issue - since these are integration tests - the inputs into the tests don't necessarily give us the expected inputs and outputs of one particular method we'd like to test.

There's not that much code to consider a transpiler, and the code we do have relies on OpenPGP.js (which is not realistic or meaningful to transpile).

I'm just trying to extract some test cases from the integration tests from one method. I was thinking we could wrap the method somehow to output inputs and outputs and then run one test suite. The node script that runs these tests would somehow collect the inputs and outputs and dump them into stdout for example. Then we could manually parse it to create test cases from it on Kotlin (and then later we can port these test cases back to TypeScript as unit tests).

That's just a rough idea - maybe you'll have some other thoughts?

**Comment by rrrooommmaaa** [comment]
> I'm just trying to extract some test cases from the integration tests from one method. I was thinking we could wrap the method somehow to output inputs and outputs and then run one test suite.

If you're talking about `unit-node.ts`, only mock storages are used there `test/source/platform/store`.
When using browser tests, we still can read/write to both IndexedDB and LocalStorage (remember getFromLocalStorage?)
So, are you willing to dump contents of storage before and after the test?
BTW, `MsgBlockParser.detectBlocks` doesn't use a storage.
I added a couple of tests in `unit-ContactStore.js` in my PR#3445 that successfully handle IndexedDB on a low-level (thanks to your `unit-browser` framework)

**Comment by tomholub** [comment]
> When using browser tests, we still can read/write to both IndexedDB and LocalStorage (remember getFromLocalStorage?)
> So, are you willing to dump contents of storage before and after the test?
>  BTW, MsgBlockParser.detectBlocks doesn't use a storage.

Something like this is what I'm after. We could make a draft PR where `MsgBlockParser.detectBlocks` is wrapped to dump input and output into storage every time it runs. Then we collect that information at the end of each full browser test and console.log it in node. Then we collect all those inputs/outputs, and throw out the temporary code.

**Comment by rrrooommmaaa** [comment]
what is "input" and "output"?
can you please be more specific?

**Comment by tomholub** [comment]
Whatever comes in/out of detectBlocks:

```
input: string
output: {blocks: MsgBlock[], normalized: string}
```

Here's one example that I took from a unit test, but I would like to know all combinations of input/output that the method produces throughout the whole (browser puppeteer) test suite, not just the three unit tests we already have.

```
input:
This text breaks email and Gmail web app.\n\n-----BEGIN FOO-----\n\nEven though it's not a vaild PGP m\n\nMuhahah

output:
{
    "blocks": [
        {type: "plainText", content: "This text breaks email and Gmail web app.\n\n-----BEGIN FOO-----\n\nEven though it's not a vaild PGP m\n\nMuhahah", complete: true}
    ],
    "normalized": "This text breaks email and Gmail web app.\n\n-----BEGIN FOO-----\n\nEven though it's not a vaild PGP m\n\nMuhahah"
}
```

**Comment by rrrooommmaaa** [comment]
If I understand correctly, this function isn't using any storage, so how is it related to #3419?

**Comment by tomholub** [comment]
Nearly not at all. I made a reference to #3419 based on your comment _"we can standardize the tests and pass input/output in a strictly defined structure, in a way we do BrowserRecipe.pgpBlockVerifyDecryptedContent passing a TestMessage structure as input."_ - this is true but indeed not very related to this conversation here.

**Comment by rrrooommmaaa** [comment]
> We could make a draft PR where `MsgBlockParser.detectBlocks` is wrapped to dump input and output into storage every time it runs.

Sure, we can, but first we should create a PR to create an IndexedDB in the beginning of `testWithBrowser` and dumping its contents after the `cb` call, if they are not empty. I suggest to go with an IndexedDB, as we can have a look at it in Chrome if needed.

**Comment by tomholub** [comment]
Got it, that makes sense. Let's wait a bit until the current contacts PR gets merged and then revisit this. Thanks!
