### ISSUE TITLE
What should happen when you import an external private key with subkeys?

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3483]
Ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwKjdxgpLVXKBXbSxkSHXQLZJvb

> i've had a second look at the decryption process:
> 
> % LC_ALL=C gpg -v e819c2e9-0c5d-4e8a-b791-0b0c48f88981
> gpg: WARNING: no command supplied. Trying to guess what you mean ...
> gpg: armor header: Version: Cryptix OpenPGP 0.20050418
> gpg: public key is 01830E35BF4BDFB8
> gpg: using subkey 01830E35BF4BDFB8 instead of primary key 8ECDF9ADC2EA66F4
> gpg: using subkey 01830E35BF4BDFB8 instead of primary key 8ECDF9ADC2EA66F4
> gpg: encrypted with 4096-bit RSA key, ID 01830E35BF4BDFB8, created 2007-03-02
>       "Michael Mohn <michael.mohn@ueberleet.de>"
> gpg: 3DES encrypted data
> gpg: original file name='Rechnung_12.03.2021.zip'
> gpg: e819c2e9-0c5d-4e8a-b791-0b0c48f88981: unknown suffix
> 
> so indeed it uses a secondary/subkey.
> how do i import that into flowcrypt? i thought i had exported/imported my whole key..

So it imports the subkey instead of the primary key. Mail encrypted and sent to him can't be opened in FlowCrypt because it's not encrypted with this subkey's public key.

At least, I think that's what's going on. What should we advise to the user in this situation?

**Comment by tomholub** [comment]
> What should happen when you import an external private key with subkeys?

Then both the primary key and all the subkeys should get imported.

He could run the key he has through our compatibility test, see what it prints out.

**Comment by seisvelas** [comment]
As the user has not responded, I'm closing this for now. If they get back to me, I'll reopen and update this issue
