### ISSUE TITLE
Allow users to customize comment line?

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3489]
User requested this, ref: https://mail.google.com/mail/u/2/#inbox/FMfcgxwLswDnWGBxwFKwbggCkFpgJSNv

Technically, we don't totally disallow this. When pulling a key via SKS we *keep* the comment line as pulled from the other server. So a user with a lot of free time on their hands could just set up an SKS server, finagle their way into the larger SKS pool, and we'd eventually get it that way.

But whether this is worth facilitating via the UI is another question entirely.

**Comment by tomholub** [comment]
It's a good suggestion. Right now we don't and we don't have plans to, but eventually we could. I'll mark it as "Not anytime soon" and later we can revisit it.
