### ISSUE TITLE
iso-2022-jp signed message garbled

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3520]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLtGlbzXGTcSBkfbffLLgFwttB

It appears we assume UTF-8,  most explicitly in the `fromUtfStr ` method here:

https://github.com/FlowCrypt/flowcrypt-browser/blob/53ce61e2228a55bc624a09d2f354e6f0be90aaea/extension/chrome/elements/pgp_block.ts#L58

But perhaps in other ways as well. 

This may not seem particularly important given the dominance of Unicode, even in Japanese writing. But email is an exception:

> ISO-2022-JP is the 7-bit JIS encoding, that e-mails are usually sent in. It is rarely used in other contexts.

Source: https://www.sljfaq.org/afaq/encodings.html#encodings-Overview-of-the-encoding-schemes

So by not being compatible with ISO-2022-JP, FlowCrypt is incompatible with the dominant form of encoding used for email in Japan!

**Comment by tomholub** [comment]
This will only be problem for a signed-only ISO-2022-JP message. We already handle them properly for encrypted messages.

**Comment by tomholub** [comment]
Could they send us a signed message to flowcrypt.compatibility@gmail.com?

**Comment by seisvelas** [comment]
>Could they send us a signed message to flowcrypt.compatibility@gmail.com?

As it so happens, they actually provided the raw email including headers of the signed message in which they observed this behavior. You can acquire the real thing via the link in my original comment to the support thread. Would that be sufficient, or would you still prefer I request that they send a signed message to flowcrypt.compatibility@gmail.com?

>This will only be problem for a signed-only ISO-2022-JP message. We already handle them properly for encrypted messages.

I didn't realize this before, but when I search the code for ISO-2022-JP I see that we do indeed have a few segments of code specifically to handle this. Out of curiosity, is there any reason this would be harder to implement on signed-only messages compared to encrypted?

**Comment by tomholub** [comment]
It's not any harder - it's an oversight (nobody reported the issue on signed msg before).

I've removed sensitive info from the message and pasted it here for someone to use as a test case later.

[jp-signed.zip](https://github.com/FlowCrypt/flowcrypt-browser/files/6215409/jp-signed.zip)

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa Any ideas how to fix this? Email message contains following part:
```
----Security_Multipart(Fri_Mar_26_22_08_51_2021_147)--
Content-Type: Text/Plain; charset=iso-2022-jp
Content-Transfer-Encoding: 7bit

$B%F%9%H$G$9(B
$B%F%9%H(B

----Security_Multipart(Fri_Mar_26_22_08_51_2021_147)--
```

How can we take into account information about encoding?

**Comment by IvanPizhenko** [comment]
@tomholub @rrrooommmaaa 
Also I have no idea how to write test for this:
- where to put the test?
- what scenario the test should perform? (I assume load message from file - is it ever possible?)
- what is correct test result? Do we have expected Japanese text encoded as UTF-8? Or maybe take text from message, convert to UTF-8, compare in the test?

**Comment by rrrooommmaaa** [comment]
I suppose, if `Content-Transfer-Encoding: 7bit`, it can't be UTF-8

**Comment by rrrooommmaaa** [comment]
> * where to put the test?

A message with such encoding should be places in `exported-messages` folder.


> * what scenario the test should perform? (I assume load message from file - is it ever possible?, then compare actual text from somewhere with expected UTF-8 - where from to take text to compare?)

To load message from file, simply load the message by msgId -- there are a number of tests that use `BrowserRecipe.pgpBlockVerifyDecryptedContent`, one of the params is `msgId=....`. The msgId should match the `id` inside the file -- NOT the file title! All messages from `exported-messages` folder are parsed and indexed according to these ids prior to running the tests.

**Comment by rrrooommmaaa** [comment]
To translate the message from `.eml` format -- the attached file by Tom, you can first drop it into a mailbox with a Thunderbird, then "export" it with the flowcrypt-browser extension -- this will give you the `.json` file to be put to `exported-messages`. Do you know how to do that, @IvanPizhenko ?

**Comment by rrrooommmaaa** [comment]
> But what is contained in the 'message'? Whole message part with headers? Only text?

If the test with `msgId` passes (when the message is extracted by the `pgp_block` frame itself), we really need to test how the message travels all the way from the inbox thread (it may indeed pass the `message` in an incorrect way). For this, we also have a recipe `InboxPageRecipe.checkDecryptMsg`. You can have a look at the tests we have that use this recipe.

**Comment by tomholub** [comment]
Here is some info about tests in general https://github.com/FlowCrypt/flowcrypt-browser/wiki/Writing-and-running-tests

For this particular situation, see this comment:

```ts
  /**
   * This is the proper way to add messages to mock api for testing:
   *   1) log into flowcrypt.compatibility@gmail.com
   *   2) go to Settings -> Inbox and find your message
   *   3) click "download api export"
   *   4) save the json file to exported-messages folder
   */
  private static exportedMsgsPath = './test/source/mock/google/exported-messages/';
```

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa I've added message in the Thunderbird, but when I try to open it in the FlowCrypt browser extension, I get following error:
```
Failed to load thread due to the following error:

Google.gmailCall@moz-extension://8cac2d06-1d82-4819-9ffe-23fe6c276ff9/js/common/api/email-provider/gmail/google.js:36:33


url: moz-extension://8cac2d06-1d82-4819-9ffe-23fe6c276ff9/chrome/settings/inbox/inbox.htm?acctEmail=flowcrypt.compatibility%40gmail.com&threadId=18024d53a24b19ff


provided ajax call stack:
Google.gmailCall@moz-extension://8cac2d06-1d82-4819-9ffe-23fe6c276ff9/js/common/api/email-provider/gmail/google.js:36:33


url: moz-extension://8cac2d06-1d82-4819-9ffe-23fe6c276ff9/chrome/settings/inbox/inbox.htm?acctEmail=flowcrypt.compatibility%40gmail.com&threadId=18024d53a24b19ff


responseText(0, 1000):
{
  "error": {
    "code": 403,
    "message": "Request had insufficient authentication scopes.",
    "errors": [
      {
        "message": "Insufficient Permission",
        "domain": "global",
        "reason": "insufficientPermissions"
      }
    ],
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
        "domain": "googleapis.com",
        "metadata": {
          "method": "caribou.api.proto.MailboxService.ModifyThread",
          "service": "gmail.googleapis.com"
        }
      }
    ]
  }
}


payload(0, 1000):
[typeof:string] {"removeLabelIds":["UNREAD"],"addLabelIds":[]}
    at <async> ajax (/extension/js/common/api/shared/api.ts:64:23)
    at <async> apiGoogleCallRetryAuthErrorOneTime (/extension/js/common/api/email-provider/gmail/google-auth.ts:102:53)
    at <async> gmailCall (/extension/js/common/api/email-provider/gmail/google.ts:21:28)
    at <async> threadModify (/extension/js/common/api/email-provider/gmail/gmail.ts:56:24)

### Catch.reportErr calling stack ###
# Catch.onErrorInternalHandler@moz-extension://8cac2d06-1d82-4819-9ffe-23fe6c276ff9/js/common/platform/catch.js:76:29
# Catch.reportErr@moz-extension://8cac2d06-1d82-4819-9ffe-23fe6c276ff9/js/common/platform/catch.js:92:18
# InboxActiveThreadModule/this.render@moz-extension://8cac2d06-1d82-4819-9ffe-23fe6c276ff9/chrome/settings/inbox/inbox-modules/inbox-active-thread-module.js:63:31
# 
# 
# url: moz-extension://8cac2d06-1d82-4819-9ffe-23fe6c276ff9/chrome/settings/inbox/inbox.htm?acctEmail=flowcrypt.compatibility%40gmail.com&threadId=18024d53a24b19ff
# 
######################

```

**Comment by tomholub** [comment]
Try resetting the account (flowcrypt settings -> additional -> experimental -> reset account), then going through setup and auth again.

**Comment by IvanPizhenko** [comment]
> Try resetting the account (flowcrypt settings -> additional -> experimental -> reset account), then going through setup and auth again.

Thanks, this has helped.

**Comment by IvanPizhenko** [comment]
I'm getting this error in the test:
```
Could not open this message with FlowCrypt.

Message is either badly formatted or not compatible with FlowCrypt. Please write us at human@flowcrypt.com to submit a bug report, and mention what software was used to send this message to you. 
show original message
```

**Comment by IvanPizhenko** [comment]
Sorry, but I have no idea how to debug this.

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa 
Error comes from somewhere here (`PgpBlockViewDecryptModule.initialize()`):
```typescript
          this.view.renderModule.renderText('Retrieving message...');
          const format: GmailResponseFormat = (!this.msgFetchedFromApi) ? 'full' : 'raw';
          const { armored, plaintext, subject, isPwdMsg } = await this.view.gmail.extractArmoredBlock(this.view.msgId, format, (progress) => {
            this.view.renderModule.renderText(`Retrieving message... ${progress}%`);
          });
          this.isPwdMsgBasedOnMsgSnippet = isPwdMsg;
          this.view.renderModule.renderText('Decrypting...');
          this.msgFetchedFromApi = format;
          if (plaintext) {
            await this.view.renderModule.renderAsRegularContent(plaintext);
          } else {
            await this.decryptAndRender(Buf.fromUtfStr(armored), verificationPubs, subject);
          }
```

**Comment by rrrooommmaaa** [comment]
> ```ts
>         params: "?frameId=none&message=&msgId=18024d53a24b19ff&senderEmail=&isOutgoing=___cu_false___&acctEmail=flowcrypt.compatibility%40gmail.com"
> ```

Looks like this param set doesn't fit for signed-only messages with detached signatures.
If I remember correctly, messages with detached signatures are called with `signature=___cu_true___`.
You can find a number of such calls, for example, tests that use msgId=17dad75e63e47f97 (one of them is using `BrowserRecipe.pgpBlockVerifyDecryptedContent`).
Or you can debug from the upper level -- inbox page.

**Comment by IvanPizhenko** [comment]
Thanks, `signature=___cu_true___` seems to work.

**Comment by IvanPizhenko** [comment]
Investigation progress
There is function `PgpBlockViewRenderModule.decideDecryptedContentFormattingAndRender()` which calls `PgpBlockViewQuoteModule.separateQuotedContentAndRenderText()`.

**Comment by IvanPizhenko** [comment]
There is following fragment in the `Mime.decode()` which extracts text:
```typescript
else if (nodeType === 'text/plain' && (!Mime.getNodeFilename(node) || Mime.isNodeInline(node))) {
                mimeContent.text = (mimeContent.text ? `${mimeContent.text}\n\n` : '') + Mime.getNodeContentAsUtfStr(node, true);
                alert(`text/plain\nAFTER: [${mimeContent.text}]`);
              }
```
In the `Mime.getNodeContentAsUtfStr(node, true)`:
```typescript
  private static getNodeContentAsUtfStr = (node: MimeParserNode, debug: boolean = false): string => {
    if (debug) alert(`getNodeContentAsUtfStr: ${node.charset}`);
    ....
```
This alert shows "utf-8". So encoding is parsed incorrectly.

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa Please look at my previous comments. Should we fix `'emailjs-mime-parser'`?

**Comment by IvanPizhenko** [comment]
@tomholub I can see that in the emailjs MIME parser there is following line of code which forces encoding to UTF-8:
```js
            // override charset for text nodes
            this.charset = this.contentType.params.charset = 'utf-8';

```
it was added when fixing issue #71.
So what should I do now? Remove it?

**Comment by tomholub** [comment]
You can see if removing the override will still pass all of our other tests.

**Comment by IvanPizhenko** [comment]
ok

**Comment by IvanPizhenko** [comment]
@tomholub It did broke some tests, so I've ended up with following:
```typescript
            if (this.charset?.toUpperCase() !== 'ISO-2022-JP') {
                this.charset = this.contentType.params.charset = 'utf-8';
            }
```
This way all tests are passing.
