### ISSUE TITLE
test importing binary private key from file

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3528]
The file import functionality during setup does not seem to be tested.

I have added some file loading functionality in `SetupPageRecipe.manualEnter` with `key.filePath` but that assumes puppeteer can directly input file into the `<input type=file>` but what actually happens during import is that the OS file picker gets automatically triggered - I don't think puppeteer has any way to handle this.

The solution may be to at least render the file input in advance, even if hidden. Then puppeteer can set it with the input file without clicking on the "import from file" label which causes the file picker.

**Comment by tomholub** [comment]
To be fair, the file doesn't have to necessarily be binary - armored would do too. Or both.

**Comment by rrrooommmaaa** [comment]
Puppeteer does have a way to intercept OS file chooser interception.
Do you wish me to PR this code without a test, or with OpenPGP file, or with S/MIME #3530 ?

**Comment by tomholub** [comment]
Puppeteer does have a way to load a particular file into file picker (we do that when testing adding attachments in compose frame). Maybe the import screen would have to be updated for this to work. Do you think it's feasible? I'd be willing to redesign how the import screen behaves, if it means we can test it better.

**Comment by tomholub** [comment]
> Puppeteer does have a way to load a particular file into file picker

For clarity - puppeteer allows an `<input type=file>` to be filled by a file chosen by us.

**Comment by rrrooommmaaa** [comment]
> Maybe the import screen would have to be updated for this to work.

Nope, the test works as it is. I just wanted to know, do we need an OpenPGP file for this test or S/MIME. as you outlined?

**Comment by rrrooommmaaa** [comment]
> Maybe the import screen would have to be updated for this to work.

Nope, the test works as it is. I just wanted to know, do we need an OpenPGP file for this test or S/MIME. as you outlined?

**Comment by rrrooommmaaa** [comment]
This sorcery is tested to work fine. I'm just thinking what branch to put it to.
```
      const [fileChooser] = await Promise.all([
        settingsPage.page.waitForFileChooser(),
        settingsPage.waitAndClick('@input-step2bmanualenter-file', { retryErrs: true })]);
      await fileChooser.accept([key.filePath]);
```

**Comment by tomholub** [comment]
Ah. It could be an OpenPGP file, that's the common usecase. Especially a non-armored one would be good to test.

Testing with S/MIME files can be done later, in S/MIME specific tests.

**Comment by tomholub** [comment]
> Puppeteer does have a way to intercept OS file chooser.

I somehow read this as `does not`, not sure why. Sorry for this confusion.
