### ISSUE TITLE
import decrypted pkcs12 private key

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3530]
after #3528 and #3529 we should enable this test (and see if there is something left to implement, this is untested functionality)

```
    // ava.default.only(
    //   'setup - s/mime private key',
    //   testWithBrowser(undefined, async (t, browser) => {
    //     const settingsPage = await BrowserRecipe.openSettingsLoginApprove(t, browser, 'flowcrypt.test.key.imported@gmail.com');
    //     const key = {
    //       title: 's/mime pkcs12 encrypted key',
    //       filePath: 'test/samples/smime/human-unprotected-PKCS12.p12',
    //       armored: null,
    //       passphrase: 'test pp to encrypt unprotected key',
    //       longid: null
    //     };
    //     await SetupPageRecipe.manualEnter(settingsPage, key.title, { submitPubkey: false, usedPgpBefore: false, key });
    //   })
    // );
```

**Comment by rrrooommmaaa** [comment]
This test has remarks
```
    // todo - change to an "add key" instead of initial import test
    // todo - disable initial import of s/mime key
```
Are you sure we're ready to support S/MIME key as the primary user key?

**Comment by tomholub** [comment]
> This test has remarks
> 
> ```
>     // todo - change to an "add key" instead of initial import test
>     // todo - disable initial import of s/mime key
> ```
> 
> Are you sure we're ready to support S/MIME key as the primary user key?

I think very likely we're not ready to support S/MIME as the only user key. Just as a secondary to an already existing OpenPGP key that the user has.
