### ISSUE TITLE
Implement img-src CSP directive

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3534]
The `img-src` directive dictates what sources are allowed to be used in `<img>` tags. This is useful because an attacker might devise a way to insert a malicious source into an existing img tag, or inject html that includes a malicious img tag. With this policy in place, 

To implement this:

- [x] Allow `data:` scheme source so image attachment previews continue to work
- [x] Review every img tag in the code base for other instances that might need special consideration
- [x] Allow `*googleusercontent.com`
- [x] *Extensive* manual testing

I mention allowing `*googleusercontent.com` because we could do that and it would work, but it would cripple the strength of our CSP since anyone can get an image on that domain by making it the profile picture of a Google account they control, and then load it into FlowCrypt that way. So not much better than just allowing arbitrary sources like we do now.

I'll have a PR up shortly.

**Comment by seisvelas** [comment]
Actually, the weakening of our CSP by allowing `*googleusercontent.com` already occurs by allowing `data:`, which we need for attachment previews.  So it doesn't matter.

In that case, I'll allow both `*googleusercontent.com` and `data:`, even though it makes this directive weak, just to get it up and working. Later we'll hopefully think of ways to strengthen it.

**Comment by tomholub** [comment]
googleusercontent.com is for images? We could load the user picture from local storage as you say. Or just stop showing it
