### ISSUE TITLE
unify ContactStore save and update

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3536]
This PR makes no difference between `save` and `update` operations. I left them untouched so we won't need to update a lot of client code in this massive PR.

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/pull/3445#discussion_r605383023_

**Comment by rrrooommmaaa** [comment]
The only useful feature of `save` is that we can save multiple contacts in one call,
whereas `update` allows to apply the same update request to a bunch of contacts.

**Comment by tomholub** [comment]
I see - that means there is some difference. We should maybe just update the comments of both methods, to say that the purpose of `save` is meant to add new contacts, however it will also update existing contacts.

And the purpose of `update` is to update one or more contacts at once, but it would also create a new contact if it was missing :shrug: 

At least if the oddity is documented, it becomes less odd.
