### ISSUE TITLE
browser compose button looks broken after Gmail UI update

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3558]
![image](https://user-images.githubusercontent.com/6306961/114610956-03ecb400-9c90-11eb-9c1a-ef7143c830e4.png)

**Comment by tomholub** [comment]
Observed on firefox

**Comment by tomholub** [comment]
This seems to have fixed itself with another Gmail update.

**Comment by tomholub** [comment]
can reproduce when I pin (expand) side menu on the left, on my company account

**Comment by limonte** [comment]
I'm experiencing this issue, I'll handle it.

**Comment by limonte** [comment]
There are 3 different cases:

### 1. New UI, Gmail with Meet enabled (Meet is enabled by default AFAIK)

<img width="249" alt="image" src="https://user-images.githubusercontent.com/6059356/116209715-da7d5f00-a74a-11eb-9f87-290d7e003955.png">

### 2. New UI, Gmail with Meet disabled in settings

<img width="250" alt="image" src="https://user-images.githubusercontent.com/6059356/116209831-f8e35a80-a74a-11eb-91af-5665c79d905a.png">

### 3. Old UI, same with Meet enabled and disabled

<img width="247" alt="image" src="https://user-images.githubusercontent.com/6059356/116210189-4eb80280-a74b-11eb-8551-ec4e6ed742f4.png">

**Comment by limonte** [comment]
@tomholub my proposal is to make the FlowCrypt "Secure Compose" button independent from Gmail's classes and place it always under the Gmail's logo, regardless of the layout:

<img width="250" alt="image" src="https://user-images.githubusercontent.com/6059356/116210944-064d1480-a74c-11eb-92a5-46483ab8f555.png">

WDYT?

**Comment by tomholub** [comment]
This all looks good. Just need to check it works both for collapsed and expanded menu (with the toggle on the left, not only hovering).

**Comment by limonte** [comment]
> This all looks good. Just need to check it works both for collapsed and expanded menu (with the toggle on the left, not only hovering).


https://user-images.githubusercontent.com/6059356/116245414-9cdffc80-a771-11eb-8de3-58a076a3cd26.mp4

**Comment by tomholub** [comment]
:+1:
