### ISSUE TITLE
Make sure the key remains revoked when trying to update with older version of it

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#3579]
I'll let you choose an approach that you deem appropriate. I'd be ok to prevent updating revoked keys in a followup PR - the situation now is already better then before (it used to not be even able to import revoked keys, I think).

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/3561#r616961032_

**Comment by rrrooommmaaa** [comment]
I suggest to create an object store containing revoked keys fingerprints (without possible "-X509" postfix).
Benefits:
1) It will help us to process CRLs for X.509 certificates later.
2) if an RSA key is compromised, it makes sense to revoke it for both systems, OpenPGP and X.509
3) Preventing to replace revoked key at ContactStore level will require complex logic without storing `revoked` flag, because of asynchronous parsing operation, IDBTransaction would need to be re-opened.

**Comment by tomholub** [comment]
Seems ok to me. Should we also store the revocation signature (or revoked public key) somewhere? To be fair, I'm not sure we actually need to have it - maybe it's not needed. Just thinking aloud.

**Comment by rrrooommmaaa** [comment]
@tomholub  We have to think about how revocations affect contact search. If a contact has all its keys revoked, should it appear in `has_pgp=true` or `has_pgp=false` results or none of them?
Also, should we export revoked keys in "Export All Keys"?

**Comment by tomholub** [comment]
What would be the easiest method for you to implement? UX here is less important - for now.

**Comment by rrrooommmaaa** [comment]
The easiest is to leave it all as it is. Revocation isn't indexed and it's hard to index given the currently suggested implementation, so `has_pgp=true` means that the contact has at least one key, possibly revoked.

**Comment by tomholub** [comment]
That seems ok to me. Then when user attempts to email to the revoked key, we should ensure the recipient field shows orange color (like when the key is expired) and when user hovers over it, it should show the available they was revoked.

**Comment by tomholub** [comment]
Otherwise seems perfect to me. Ok to export revoked keys, too.

**Comment by rrrooommmaaa** [comment]
As I understood, the revoked key is currently not allowed to be imported with the message "key is not valid"?
I think we should save it to `revocations` store, to not allow importing older version.

**Comment by tomholub** [comment]
Agree. We should also show a clear UI to say "This key is revoked, meaning it should not be used. Importing this key will ensure that other versions of this key won't be used either." Let's do a separate PR for that.
