### ISSUE TITLE
Bulk public key import freezes

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3586]
If you try to import a ton of PGP public keys (~150), the extension just freezes and never finishes. Or it throws errors about key validity, even though the keys work when imported individually or in smaller chunks

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLtbBGHZsWcmTfkPxcmWgkdChN

I haven't tried to reproduce this, I'm making this issue so I remember to do so. The user who sent the feedback was able to import the keys individually so this no longer impacts them, but it needs to be addressed so other users aren't inconvenienced.

I'll try this later and update this issue with results

**Comment by seisvelas** [comment]
I've tried recreating this but am unable to do so - it works for me even importing more keys than the original user. Closing since I can't reproduce.

**Comment by tomholub** [comment]
We reworked these things since April - maybe it really works now
