### ISSUE TITLE
Using subkey's private key

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3587]
A user is reporting a problem when trying to use a subkey's private key as their key on FlowCrypt. Here are the details:

1) Generated a master RSA 4096 bit key that can only Certify (used `gpg --expert --full-gen-key`) - I used exactly the same passphrase as the one that was generated during sign up.

2) Generated an RSA 4096 bit subkey that can Encrypt and Sign (used `gpg --expert --edit-key KEYID`)

3) Create backups of the master private key, the subkey's private key  and the public key.

3) Removed all private keys (used `gpg --delete-secret-key KEYID`)

4) Imported the subkey's private key only (used `gpg --import private_key.subkey.asc`)

5) Uploaded subkey's private to FlowCrypt's web version - that was added without problem

6) Getting the following error when receiving a message that used the associated public key:

Could not open this message with FlowCrypt.
Message is either badly formatted or not compatible with FlowCrypt. Please email us at human@flowcrypt.com to submit a bug report, and mention what software was used to send this message to you. We usually fix similar incompatibilities within one week.

If they try to import this key to mobile they get:

``One of the provided Private Keys is a partially encrypted private key (some packets are encrypted, some not).
Such keys are not supported. Please only import fully encrypted keys, with the same pass phrase for all secret packets.``

I'm making this issue to see if the problem was obvious to anyone else, since it's not at all obvious to me.

**Comment by seisvelas** [comment]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLtQNnWKbWSxftNdDqtmXtLKsr

**Comment by tomholub** [comment]
> Uploaded subkey's private to FlowCrypt's web version - that was added without problem

Presumably he means the browser extension?

**Comment by tomholub** [comment]
Also we should remove this - it's untrue:

> We usually fix similar incompatibilities within one week.

**Comment by tomholub** [comment]
We'd look into this - it would be really helpful if the user could prepare one such subkey-only key for us to test with.

**Comment by seisvelas** [comment]
I've asked the user if they'd provide us with such a key, in the meantime closing (will reopen if/when I receive response)
