### ISSUE TITLE
Secure Compose button is messed up for Chrome user

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3597]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLtkPlBkjqCmbDxrSGlSqTvGbX

Here is how it is being rendered for them:

![image (1)](https://user-images.githubusercontent.com/44826516/116506403-6cd05080-a87a-11eb-8986-21c830e45116.png)

According to the user they do not have any other extensions or customizations in Gmail that could affect this.

Not sure how best to proceed, please advise.

**Comment by tomholub** [comment]
We recently fixed this but I didn't make a release yet for consumers: #3558

**Comment by tomholub** [comment]
it's fixed now and released

**Comment by seisvelas** [comment]
User contacted us saying the latest released fixed the issue :)
