### ISSUE TITLE
Signing into Gmail through delegated authority?

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3608]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgxwLtkVVvSbcHWXjJhSHJghFNpDv

> I have the flowcrypt option in my email but when I click to open an encrypted email this error message comes up ' Please reconnect FlowCrypt to your Gmail Account. This is typically needed after a long time of no use, a password change, or similar account changes'. 
> When I then click the 'reconnect' link I get this message ' Forbidden
> You don't have permission to access this resource.'
> 
> Any suggestions would be appreciated.

I followed up, inquiring whether there could be anything interfering with FlowCrypt (extensions, Gmail settings, etc)

>I am not very tech savvy.  I sign into my work gmail through delegated authority if that helps!?

Would we expect that to be an issue? Just checking to see if anyone else has knowledge on this already, otherwise I'll continue troubleshooting this.

**Comment by tomholub** [comment]
It would be good to know how FlowCrypt behaves in this situation - I haven't tested.

**Comment by seisvelas** [comment]
Okay, great! I can test it , then. If it goes wrong we can use this issue to perhaps fix it (or at least understand the source of the incompatibility), and if not we know the issue is somewhere else.

**Comment by seisvelas** [comment]
To update this: it worked fine for me, then randomly started working fine for the user. 

I'm closing this for now since neither we nor the user can reproduce the problem, but will reopen if it crops back up.
