### ISSUE TITLE
how to handle apparent duplicates in contact list

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3633]
Also experiencing issues with rendering the contacts list, there are duplicates:

![image](https://user-images.githubusercontent.com/6059356/117874882-3ba84500-b2aa-11eb-8716-193fa85388a8.png)

_Originally posted by @limonte in https://github.com/FlowCrypt/flowcrypt-browser/issues/3632#issuecomment-839067108_

**Comment by tomholub** [comment]
Ever since we did #3332 (likely) we started to see duplicates in contact list.

This is because there may be more than one public key for a particular recipient now.

This would be worth to re-organize - maybe pull by unique email, and then show all of that person's public keys on the contact detail page?

**Comment by limonte** [comment]
Interesting detail, when filtering by email there's no dups. So I'd assume there's already some kind of filtering functionality which can be used as well when the filter isn't set?

**Comment by tomholub** [comment]
Interesting indeed - we have to come up with some deliberate approach here, what we have now is incidental.

**Comment by tomholub** [comment]
@rrrooommmaaa I'll let you approach this in a way that makes sense to you. What would you do?

**Comment by rrrooommmaaa** [comment]
> This would be worth to re-organize - maybe pull by unique email, and then show all of that person's public keys on the contact detail page?

Sure, we already have a method for retrieving all pubkeys per email -- `ContactStore.getOneWithAllPubkeys`. As the refactored `ContactStore` tries to mimick the original one returning "one key per on e-mail" suiting most of encryption tasks etc., we of course should make use of full functionality where it is appropriate

**Comment by rrrooommmaaa** [comment]
> This would be worth to re-organize - maybe pull by unique email, and then show all of that person's public keys on the contact detail page?

Right, currently each entry on the list (as well as `ContactPreview` structure) is supposed to be identified by `email`, so pressing "view" should load the list of all keys (and "delete" button should be available for each of the loaded keys), thus "delete" button should be removed from the "contact list" (unless we're meaning to delete all contact's keys at once). This discussion should be resolved prior to #3632

**Comment by tomholub** [comment]
Let's do that than - list of emails in contacts, then list of their associated public keys when I click.

**Comment by tomholub** [comment]
Thanks!

**Comment by rrrooommmaaa** [comment]
Should I wait for "actionable" tag or start right away?

**Comment by tomholub** [comment]
Sorry - I forgot to add it.

**Comment by tomholub** [comment]
@rrrooommmaaa I have a simplification here.

Instead of rendering the list like this:
```
user@corp.co     [btn] [btn]
user2@corp.co    [btn] [btn]
```

And then after clicking seeing several keys, you can render like this:

```
user@corp.co
   openpgp - active - 2020 AAFA ....   [btn] [btn]
   openpgp - expired - AAAA BBBB ....  [btn] [btn]
user2@corp.co
   openpgp - active - CCCC 2222 ....   [btn] [btn]
```

Then when I click a button, I will still see just one key. That means you don't have to rework the key view part, which is I think more complicated then reworking just the list.
