### ISSUE TITLE
Instead of waiting for the user to enter the wrong passphrase to skip backup, just give them the option to begin with

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3634]
Currently, when a user has a backup, they are asked for the passphrase. If they enter an incorrect passphrase, they are given the option to skip this step.

But how is a user supposed to know that's how they skip? A user who hasn't done this before will just have to guess or assume that would work, or have tried the incorrect passphrase. But if they know they forgot their passphrase, they aren't likely to attempt that. 

It just seems easier to give them the option right away, instead of only after they have incorrectly guessed. If that's what they want, then why not?

**Comment by tomholub** [comment]
Agree. Skipping used to be more desctructive (still old public keys would remain on attester) and therefore more discouraged, but these days we can offer it more clearly.
