### ISSUE TITLE
Gmail's attachment element isn't being removed

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3642]
There are 4 attachments in this message, 3 default elements are removed and the 4th one isn't:

![image](https://user-images.githubusercontent.com/6059356/118466225-51cf5e80-b70b-11eb-95db-2112b803a5ce.png)

**Comment by limonte** [comment]
The issue is happening for all attachments with double space in the filename, e.g. `a  b.png`

**Comment by tomholub** [comment]
Interesting. Then the name is different then received over API, causing the extension to not be able to match the file from api to the file in UI?

It would be great if we could somehow reference by id instead, but I think the DOM doesn't surface that info.

**Comment by limonte** [comment]
> Interesting. Then the name is different then received over API, causing the extension to not be able to match the file from api to the file in UI?

Correct.

> It would be great if we could somehow reference by id instead, but I think the DOM doesn't surface that info.

Agree, I'll check that.
