### ISSUE TITLE
Setting to open compose modal full screen

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3644]
Gmail allows this, like so:

<img width="1287" alt="Screen Shot 2021-05-15 at 3 01 50 PM" src="https://user-images.githubusercontent.com/44826516/118587025-08a5fb80-b759-11eb-95e2-53bb9ccc7893.png">

Perhaps we could have a little panel in FlowCrypt settings just for UI stuff (in case there are other things we want to be customizable like this)

**Comment by tomholub** [comment]
Setting it for later in the future - when we've handled more crucial stuff. I can imagine it can be convenient for someone who is used to it.
