### ISSUE TITLE
The "Send Options" button should be disabled when the "Send" button is disabled

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3650]
Because otherwise it creates unexpected behaviors:

https://user-images.githubusercontent.com/6059356/118666890-31cb9800-b7fc-11eb-9f94-f02cc2541697.mp4

While fixing this also make sure that `<button disabled>` doesn't have `cursor: pointer`

**Comment by tomholub** [comment]
Thank you, agree! @rrrooommmaaa mentioned something similar recently
