### ISSUE TITLE
The number of attachments shouldn't be removed

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3654]
Gmail:

<img width="468" alt="CleanShot 2021-05-19 at 16 20 53@2x" src="https://user-images.githubusercontent.com/6059356/118819849-6869e700-b8be-11eb-808d-86fa4c1e6bea.png">

FlowCrypt:

<img width="452" alt="CleanShot 2021-05-19 at 16 21 34@2x" src="https://user-images.githubusercontent.com/6059356/118819871-6ef85e80-b8be-11eb-858b-235fcca2ee35.png">

Something in out codebase removes that useful "4 attachments" block.

**Comment by tomholub** [comment]
I think I did it on purpose, because sometimes two attachments combine into one (sig + content), sometimes they combine into none (actually contain encrypted data), etc. I didn't want to do all of that accounting, so I removed it hoping nobody would ever notice :-)

**Comment by limonte** [comment]
> I think I did it on purpose, because sometimes two attachments combine into one (sig + content), sometimes they combine into none (actually contain encrypted data), etc. I didn't want to do all of that accounting, so I removed it hoping nobody would ever notice :-)

Right, but I think it should be possible to calculate the total number of decrypted attachments after rendering them and then use that number for the label?

**Comment by tomholub** [comment]
We could do that, and that's pretty simple. Good idea.

**Comment by tomholub** [comment]
Should also count the plain attachments, in messages with mixed attachments.
