### ISSUE TITLE
"Download all attachments" button should download decrypted files

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3655]
![image](https://user-images.githubusercontent.com/6059356/118820499-fd6ce000-b8be-11eb-9132-36afa6f79d4a.png)

This button should:

1. decrypt all attachments
2. pack them into zip (use JSZip or similar)
3. download zip

**Comment by tomholub** [comment]
Nice catch. This would sure surprise some users.

**Comment by tomholub** [comment]
I'm putting to Third because it's not exactly an easy task :-)

Also, I would prefer not to hijack the original button's functionality. Maybe we would hide it and present our own in green color or something?

**Comment by limonte** [comment]
> Also, I would prefer not to hijack the original button's functionality. Maybe we would hide it and present our own in green color or something?

Agree. It's better to hide Gmail's one and replace it with the same-looking, but `rgb(49, 162, 23)` button.

**Comment by tomholub** [comment]
postponing, may eventually reopen if someone complains
