### ISSUE TITLE
Export all contacts feature broken

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3659]
ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkXSTdrbjTDpCcDmDRkPpnBsfh

>I found one bug about the export contact. I click export all contact but seem like file size is 0 byte.

I tried this myself and the same happens. I click `FlowCrypt Settings -> Additional Settings -> Contacts -> export all`, it downloads a file, I open it, aannnd, empty!

When we patch this, we should also add a test to prevent this from popping up again in the future.

If anyone knows something obvious that's causing this let me know, otherwise just feel free to assign this to me and I'll start debugging it.

**Comment by tomholub** [comment]
Agree with added test

**Comment by tomholub** [comment]
reopening for:

> Good for this particular PR, but it would be good to test this with UI tests (click the export all button, and expect pubkeys to come out).

**Comment by tomholub** [comment]
closing, test issue filed separately
