### ISSUE TITLE
"Cannot find primary key. Is FlowCrypt not set up yet? retry" error handling looks broken

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3669]
Steps to reproduce:

1. Settings -> Experimental -> Reset account
2. Try to compose secure email

https://user-images.githubusercontent.com/6059356/119254204-b3854200-bbbd-11eb-830b-05ee9c067368.mp4

**Comment by tomholub** [comment]
This is expected behavior - resetting account removes your private keys, going back to "not set up" mode, and the compose window will stop working when that happens.

Was the window already open at the time you reset the account, or did you manage to still open it after?

**Comment by limonte** [comment]
> Was the window already open at the time you reset the account, or did you manage to still open it after?

I'm able to open the compose window after resetting account.

Only after reloading Gmail's page, the "Secure Compose" button is gone. Before reloading Gmail the "Secure Compose" button is opening the compose window.

**Comment by tomholub** [comment]
The fact that the button (and other UI) remains available to click in Gmail is an oversight, and could be fixed.

There is a way to tell the content scripts to "clean themselves up" which is used during extension update (new extension is loaded, and it tells the old extension to clean up it's own UI side effects in Gmail UI). But I haven't looked into this in a while. If this could be triggered during account reset, then the UI elements should go away.

**Comment by tomholub** [comment]
However, if your primary worry is that the style of the error message looks broken, than that could be fixed easier :-)

**Comment by limonte** [comment]
> However, if your primary worry is that the style of the error message looks broken, than that could be fixed easier :-)

Yup 👍 I'll handle that
