### ISSUE TITLE
#cryptup_dialog should close itself by Esc

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3677]
Currently `#cryptup_dialog` doesn't close itself when user press `Esc`. Instead it allows `Esc` to propagate, which create the unexpected behavior, e.g. closing the "Secure Compose" window while `#cryptup_dialog` stays opened.

### Steps to reproduce

1. Start wiring the password-protected message
2. Click the "Add their public key" link
3. Press `Esc`

### Actual behavior

`#cryptup_dialog` stays opened while the "Secure Compose" window is getting closed.

### Expected behavior

`#cryptup_dialog` is getting closed while the "Secure Compose" window stays opened (stop event propagation).

**Comment by tomholub** [comment]
well noticed!
