### ISSUE TITLE
The "success notif after setup, click hides it, does not re-appear + offers to reauth" Gmail test is failing

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3678]
In `master` branch: https://flowcrypt.semaphoreci.com/jobs/c341c1de-1327-482f-9b41-7a9b24e25472

And dependabot's PRs are red because of this.

**Comment by tomholub** [comment]
That would be for me to take a look.

**Comment by tomholub** [comment]
@limonte would you be able to debug it? I may not be able to do it until next week

**Comment by limonte** [comment]
> @limonte would you be able to debug it? I may not be able to do it until next week

Will do tomorrow 👍
