### ISSUE TITLE
Saving draft is going into infinite loop after clicking on "Add their Public Key" link

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3688]
While working on #3680 I noticed the infinite changing "Saved"/"Saving..." labels after opening the dialog for adding a pubkey:

https://user-images.githubusercontent.com/6059356/119659274-ad4dca80-be36-11eb-8541-c513c14f5d8c.mp4

**Comment by tomholub** [comment]
Very interesting :-) thanks for reporting!
