### ISSUE TITLE
Editing and deleting contacts doesn't work

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-browser#3690]
If you try to delete a contact, nothing happens. If you edit a contact and put in a new key, the key is not updated. This is on both Chrome and Firefox. No error appears on the console, just nothing at all.

ref: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkXSSSbRFRkskTbVvjlqGgpXWS

**Comment by rrrooommmaaa** [comment]
working on it in #3633 and #3632

**Comment by seisvelas** [comment]
Sorry, hadn't seen that!
