### ISSUE TITLE
Contacts suggestions popup should be closed when user press Enter (submit the recipient)

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3698]
### Steps to reproduce

1. type any email that is not in the contacts list e.g. `aaaaaaaaaa@ss.dd` in the recipients input

<img src="https://user-images.githubusercontent.com/6059356/120040485-4e8f7900-c00f-11eb-81fc-cba502a5a959.png" width="400">

2. hit `Enter`

### Actual result

<img src="https://user-images.githubusercontent.com/6059356/120040513-5d762b80-c00f-11eb-9513-8651af21339a.png" width="400">

### Expected result

<img src="https://user-images.githubusercontent.com/6059356/120040531-6666fd00-c00f-11eb-819e-ef5cacec21d8.png" width="400">

**Comment by tomholub** [comment]
well noticed
