### ISSUE TITLE
[Attachment preview] Images aren't rendered in Firefox because of CSP

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3703]
Firefox throws this when previewing any image:

```
Content Security Policy: The page's settings blocked the loading of a resource at blob:moz-extension://... ("img-src")
```

I tried this so far, no luck:

```diff
-<meta http-equiv="Content-Security-Policy" content="script-src 'self'">
+<meta http-equiv="Content-Security-Policy" content="script-src 'self'; img-src 'self' blob: data:;">

**Comment by seisvelas** [comment]
I think that when there is a conflict between the HTTP header CSP policy, and the meta tag, the header gets priority. So it's possible that meta tag isn't doing anything. Rather, I think you'd need to change this:

https://github.com/FlowCrypt/flowcrypt-browser/blob/81145328da8c26a908d5141287954c38a023f660/extension/manifest.json#L94

Specifically, in img-src, you'd have to add `blob:`.

I could be totally wrong, I'll try this out in a bit and get back to you.
