### ISSUE TITLE
We should probably not bother users with "loading..." state of contacts suggestions popup

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3711]
While I do agree that it's helpful in most cases to indicate the background activity to users, this particular case seems to be unnecessary, flickering "loading..." popup is kinda annoying:

https://user-images.githubusercontent.com/6059356/120302739-da86f680-c2d6-11eb-9696-f594126f237a.mp4

IMO Here, we can hide the `loading` state from users and render contacts suggestions 

- when we have them
- no results found, but Google isn't connected (suggestion to connect it)
- error occured

**Comment by tomholub** [comment]
I'll let you update it to your taste. Thanks for noticing!
