### ISSUE TITLE
The "Recipient will have access to this message" block is mispositioned in secure reply

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3716]
![image](https://user-images.githubusercontent.com/6059356/120538900-b408ae80-c3ef-11eb-8ba7-6bb48a20cab5.png)

---

Also, while fixing this, fix also this: split this line into two lines or insert comma here:

![image](https://user-images.githubusercontent.com/6059356/120538996-d1d61380-c3ef-11eb-80d7-516fe40e4cf3.png)

**Comment by limonte** [comment]
@tomholub `<offtopic>` I'm sometimes making small fixes in one issue/PR for the sake of saving time. Let me know if you're ok with that or you'd prefer issue per each small defailt. Thanks.`</offtopic>`

**Comment by tomholub** [comment]
No problem about fixing tiny things in another issue, if it's minor I'll often do the same.
