### ISSUE TITLE
Apply FORBID_STORING_PASS_PHRASE OrgRule to `add_key.htm` frame

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#3756]
> when this OrgRule is enabled, I would probably .hide() it's first-ancestor .line tag (in typescript probably render method) to make sure it doesn't show.

This is not really needed, since I forgot to mention this in the original issue (and may need to tailor-hide different elements in each page). It would just be a bit neater. Could do sometime in the future, after other issues, too.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/2752#issuecomment-853819137_

**Comment by tomholub** [comment]
I think the way you did it is good. I don't see a strong need to refactor it further - it was just a general thought.

**Comment by rrrooommmaaa** [comment]
Still, "add_key.htm" has its own "Remember Pass Phrase after closing browser." checkbox that wasn't affected by PR #3707

**Comment by tomholub** [comment]
Understood - this was left unimplemented for now. Got it :+1:
