### ISSUE TITLE
Replace "Forgot pass phrase?" on pass phrase dialog when key_manager_url OrgRule is set

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3781]
Instead of the "Forgot pass phrase?" link, there should be text that says "Ask your IT staff for help if you lost your pass phrase."

![image](https://user-images.githubusercontent.com/6306961/123862105-76784200-d917-11eb-9e98-d66cdec0d13c.png)

**Comment by martgil** [comment]
I think I have managed to fix this issue by adding a check using `this.orgRules.usesKeyManager()` in `passphrase.ts`
![fix forget password on when keymanager enabled](https://user-images.githubusercontent.com/46025304/125911882-2ac0b068-ed58-4981-aa27-259a12e19daf.png)

**Comment by tomholub** [comment]
That looks good but is that still a link? It looks like the user could click it and go somewhere we don't want them to go.

**Comment by martgil** [comment]
When the link was clicked, the pop-up help for "Non-FES" user is shown. 
![image](https://user-images.githubusercontent.com/46025304/125913164-b0f5097b-13d2-4565-8623-24faf5b0a3e2.png)

Maybe we can update or add the description for "FES" user. Or maybe we could just disable the link?

**Comment by tomholub** [comment]
Let's disable the link when the user uses EKM as you say

**Comment by tomholub** [comment]
There's a test that uses EKM and also FORBID_STORING_PASS_PHRASE org rule. That test will be using the pass phrase dialog, I think. You can add a line to that test to verify the content has changed and is not clickable. Thanks!

**Comment by martgil** [comment]
Correct me if I'm wrong. it the `settings.ts` contains the test. Maybe I should just read the Document Object Model to check if the link is not clickable when the pass phrase dialog was invoked. I am a not yet comfortable with unit testing but I am trying to keep up as fast as I can. Thanks for understand.

**Comment by martgil** [comment]
I have tried to understand how ava testing was implemented in the flowcrypt-browser but I can't able to absorb what's happening inside the code. Can I help somebody once I get it, I'm going to add the test for the changes that I have made hopefully. Pardon me for any inconvenience.

**Comment by tomholub** [comment]
@martgil see if "Running tests locally" in https://github.com/FlowCrypt/flowcrypt-browser/wiki will help you. After that, please ask a more specific question and we'll be able to help or demonstrate. Thanks!

**Comment by martgil** [comment]
Hi @tomholub. Thanks for that. I think I have found it. There is currently a test that involves the `passphrase.htm` but the test is not specifically dedicated to user who has a FES account. Would you like me to add a specific test instead? The test will check if the user does have FORBID_STORING_PASS_PHRASE org rule and then if the DOM has indeed change the text and removed the `href`. I will try to do this and hopefully finished the test on moved on to the other tasks.

**Comment by martgil** [comment]
I wish to get the dom tree of `passphrase.htm` in this code `const passphraseDialog = await inboxPage.getFrame(['passphrase.htm'])` found in compose.ts but still not working. I tried `passphraseDialog.page.$eval()` and the ` passphraseDialog.$eval()`

**Comment by tomholub** [comment]
Could you point me to the test you found?

**Comment by martgil** [comment]
I found this test located in 'test/source/tests/compose.ts' and the exact test im referring is the 'compose - signed with entered pass phrase + will remember pass phrase in session' from this ava test. Because it has the passphraseDiaglog which I need to fetch the DOM tree from.

**Comment by tomholub** [comment]
Here's how to find the ideal test to modify (or how to write a new test) when testing OrgRules.

1) make a decision if you will only be adding/editting test for the behavior of the org rule, or also add/edit a test for "default" behavior. If default behavior is already tested well, then you only address the specific OrgRule behavior.

Here, it's not quite clear - but since this will be just a small change, it doesn't hurt to address both sides. Let's start with the specific OrgRule test as an example.

2) search for the org rule you want to test eg `FORBID_STORING_PASS_PHRASE`, and see where it's used in the tests: (this example is `test/source/mock/backend-data.ts`

![image](https://user-images.githubusercontent.com/6306961/126290415-f1c209c0-4085-4677-bbec-e1e2f9718b3f.png)

3) notice the test domain that it's definining: `forbid-storing-passphrase-org-rule.flowcrypt.test` and search for it

here's one: 

![image](https://user-images.githubusercontent.com/6306961/126290804-98775e9f-16c7-486c-9e08-439b610cd307.png)

another one:

![image](https://user-images.githubusercontent.com/6306961/126290886-cbe373d1-a311-45fd-8f79-72a1b49c3165.png)

4) find the most generic test that has the org rules setup you want (or create one)

In our case, it seems to be this one:

```ts
    ava.default('user@forbid-storing-passphrase-org-rule.flowcrypt.test - do not store passphrase', testWithBrowser(undefined, async (t, browser) => {
      const acctEmail = 'user@forbid-storing-passphrase-org-rule.flowcrypt.test';
      const settingsPage = await BrowserRecipe.openSettingsLoginApprove(t, browser, acctEmail);
      await Util.sleep(5);
      const passphrase = 'long enough to suit requirements';
      await SetupPageRecipe.createKey(settingsPage, 'unused', 'none', { key: { passphrase }, usedPgpBefore: false },
        { isSavePassphraseDisabled: true, isSavePassphraseChecked: false });
      await settingsPage.notPresent('.swal2-container');
      const inboxPage = await browser.newPage(t, TestUrls.extensionInbox(acctEmail));
      await InboxPageRecipe.finishSessionOnInboxPage(inboxPage);
      const composeFrame = await InboxPageRecipe.openAndGetComposeFrame(inboxPage);
      await ComposePageRecipe.fillMsg(composeFrame, { to: 'human@flowcrypt.com' }, 'should not send as pass phrase is not known', { encrypt: false });
      await composeFrame.waitAndClick('@action-send');
      await inboxPage.waitAll('@dialog-passphrase');
      const passphraseDialog = await inboxPage.getFrame(['passphrase.htm']);
      const forgetPassPhraseElement = await passphraseDialog.waitAny('@forget-pass-phrase');
      expect(await InboxPageRecipe.isElementDisabled(forgetPassPhraseElement)).to.equal(true);
      expect(await InboxPageRecipe.isElementChecked(forgetPassPhraseElement)).to.equal(true);
      await inboxPage.close();
      await settingsPage.close();
    }));
```

If you notice, it already uses `passphrase.htm`. Plus this is a test domain that uses `FORBID_STORING_PASS_PHRASE`. That's what we wanted. In this issue, we are looking for specific text in specific element. Therefore you can use `waitForContent` just under the line `const passphraseDialog = await inboxPage.getFrame(['passphrase.htm']);` to test the behavior.

You can run the test per wiki (with .only) to make sure it runs properly.

5) find and edit an appropriate test that does not have OrgRules set. You've already found one: `compose - signed with entered pass phrase + will remember pass phrase in session`

```ts
    ava.default('compose - signed with entered pass phrase + will remember pass phrase in session', testWithBrowser('ci.tests.gmail', async (t, browser) => {
      const k = Config.key('ci.tests.gmail');
      const settingsPage = await browser.newPage(t, TestUrls.extensionSettings('ci.tests.gmail@flowcrypt.test'));
      await SettingsPageRecipe.forgetAllPassPhrasesInStorage(settingsPage, k.passphrase);
      const inboxPage = await browser.newPage(t, TestUrls.extensionInbox('ci.tests.gmail@flowcrypt.test'));
      const composeFrame = await InboxPageRecipe.openAndGetComposeFrame(inboxPage);
      await ComposePageRecipe.fillMsg(composeFrame, { to: 'human@flowcrypt.com' }, 'sign with entered pass phrase', { encrypt: false });
      await composeFrame.waitAndClick('@action-send');
      await inboxPage.waitAll('@dialog-passphrase');
      const passphraseDialog = await inboxPage.getFrame(['passphrase.htm']);
      await passphraseDialog.waitAndType('@input-pass-phrase', k.passphrase);
      await passphraseDialog.waitAndClick('@action-confirm-pass-phrase-entry');
      await inboxPage.waitTillGone('@dialog-passphrase');
      await inboxPage.waitTillGone('@container-new-message'); // confirming pass phrase will auto-send the message
      // signed - done, now try to see if it remembered pp in session
      const composePage = await ComposePageRecipe.openStandalone(t, browser, 'compose');
      await ComposePageRecipe.fillMsg(composePage, { to: 'human@flowcrypt.com' }, 'signed message pp in session', { encrypt: false });
      await ComposePageRecipe.sendAndClose(composePage);
      await settingsPage.close();
      await inboxPage.close();
    }));
```

Notice that it has a generic domain: `ci.tests.gmail@flowcrypt.test`. This should mean that it doesn't have any OrgRules set up  (unlike for example `user@forbid-storing-passphrase-org-rule.flowcrypt.test` which does).

Here you can similarly edit the test, but this time to test for the opposite behavior.

**Comment by martgil** [comment]
Hi @tomholub. Thanks for the reference, It helps me to understand it better now. I have tried what exactly we need to do but I am having an error on compose.ts for some reason:
![image](https://user-images.githubusercontent.com/46025304/126434621-3f5f1f56-8737-433e-ad2e-0e0343887d3f.png)

As we can see even though I haven't used any of the `.passphrase` property it still insists `TypeError: Cannot read property 'passphrase' of undefined
          at Function.SetupPageRecipe.recover (/home/mart/project/flowcrypt-browser/test/source/tests/page-recipe/setup-page-recipe.ts:208:69)`.
          
The npm command I used for testing is the `npm run test_local_chrome_consumer_mock;` So that the `if (testVariant !== 'CONSUMER-LIVE-GMAIL')` will pass since I'm running the local test for consumer and not a consumer-live variant of testing. I believed that the `flowcrypt-browser/test/source/tests/page-recipe/setup-page-recipe.ts` has nothing to do with the error. The error for `.passphrase property is undefined` keeps appearing even on the untouched version of the code from `compose.ts` so It's really strange.

**Comment by tomholub** [comment]
Please submit it to the Draft PR, then we'll be able to try it and help more specifically.

**Comment by martgil** [comment]
Thank @tomholub. I will try to send a draft PR when I had a chance to get a more specific question to ask since I don't have any idea yet what to ask in my case here despite I have a pretty clear idea on how to have a proper fix. Although I've already push a PR to fix this issue itself but without a test for it yet.

**Comment by martgil** [comment]
Understood @tomholub. I have converted the original PR into a draft PR for this issue.
