### ISSUE TITLE
Check if email falls under `disallow_attester_search` when fetching by fingerprint/longid

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#3804]
When fetching by fingerprint, e-mail might not be known (or not supplied to `lookupFingerprint` method).

https://github.com/FlowCrypt/flowcrypt-browser/pull/3803#issue-940919605

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/125175380-35a3e700-e1bb-11eb-8bb9-e4a8fdd4ecd9.png)

**Comment by tomholub** [comment]
We don't search attester by Fingerprint anymore.
