### ISSUE TITLE
retire pulling public keys keys from EKM

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3841]
Since we already pull public keys from WKD which is synced with EKM, no need to have a separate endpoint for this.

That means this would simply get removed:

```ts
    if (this.keyManager) {
      const res = await this.keyManager.lookupPublicKey(email);
      if (res.publicKeys.length) {
        return { pubkeys: res.publicKeys.map(x => x.publicKey) };
      }
    }
```

Similarly remove `getKeyManagerUrlForPublicKeys` and everything related to `NO_KEY_MANAGER_PUB_LOOKUP` and adjust tests.

This way, the extension will be more consistent with what mobile apps do, also.

**Comment by tomholub** [comment]
Also this to remove from `KeyManager`:

```ts
  public lookupPublicKey = async (emailOrFingerprint: string): Promise<LoadPubRes> => {
    return await this.request('GET', `/keys/public/${emailOrFingerprint}`);
  }
```

**Comment by martgil** [comment]
Hello @tomholub. I just initially removed all of the code you've mentioned but I haven't done adjusting the tests. Would there be any specified things to adjust on the test or just removing the `user@key-manager-no-pub-lookup.flowcrypt.test - do not search pubkeys on EKM: NO_KEY_MANAGER_PUB_LOOKUP` out from the test in setup.ts

**Comment by tomholub** [comment]
Hard to say - you will see based on which tests start failing after the change.
