### ISSUE TITLE
update reset account procedure for EKM users

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3856]
when EKM is used, going to `flowcrypt settings -> Additional settings -> experimental -> reset account`:

- [x] it should not produce such a stern warning. Instead it should only say `You may lose local settings by resetting this extension. Continue?` and no second confirmation
- [x] debug file that contains the private key should not be saved - this step should be skipped

**Comment by martgil** [comment]
Working on this at the moment.
