### ISSUE TITLE
Clicking the "Secure Compose" button should maximize the minimized secure compose window

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3858]
### Given

- The secure compose window is already opened and minimized
- User clicks the "Secure Compose" button

### Current behavior

Nothing happens.

### Expected behavior

The minimized secure compose window is maximized. This would be aligned with Gmail.

**Comment by tomholub** [comment]
Eventually (soon) we should add support for several compose windows. This feature you propose makes sense as things are now but would not once this is implemented: #3125 

Thank you for filing - I'll close.

**Comment by tomholub** [comment]
Unless you think it would still make sense? Maybe it would?

**Comment by limonte** [comment]
> Unless you think it would still make sense? Maybe it would?

I think you're right, with multiple compose windows this request would not make sense. Closing.
