### ISSUE TITLE
Disabled checkbox during setup process

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3866]
I was setting up my `vladimir@flowcrypt.com` account and faced this disabled checkbox:

![CleanShot 2021-07-29 at 02 18 03@2x](https://user-images.githubusercontent.com/6059356/127465327-31979b31-9aa4-44d0-8446-449b2a13e786.png)

It should either be hidden or enabled for users.

**Comment by limonte** [comment]
Another disabled checkbox (I'm not sure if these two checkboxes are connected)

![CleanShot 2021-07-29 at 12 13 58@2x](https://user-images.githubusercontent.com/6059356/127465744-a1b463b1-befc-47a2-973c-5843c8971d05.png)

**Comment by tomholub** [comment]
To be fair, I also struggled with the disabled check boxes - I keep wanting to click them. 

This is the PR that is doing it: https://github.com/FlowCrypt/flowcrypt-browser/pull/3707

There are various org rules (client configuration) that are modifying the behavior of the extension - applied per domain. Some customers may want their users to not be able to do X or enforce to do Y and so on. I've applied several of them to our own domain `flowcrypt.com`. The OrgRule causing this behavior is `FORBID_STORING_PASS_PHRASE`.

It's doing it's job but not in a user-friendly way. Hiding the checkbox and its label is preferable over just disabling it.

**Comment by limonte** [comment]
Note to myself: while fixing this, also fix the centering:

Current | Expected
-|-
<img width="732" alt="CleanShot 2021-07-29 at 02 16 14@2x" src="https://user-images.githubusercontent.com/6059356/127466899-82aa6860-24de-4b62-bc2c-88b7e2b046b1.png"> | <img width="716" alt="CleanShot 2021-07-29 at 02 17 08@2x" src="https://user-images.githubusercontent.com/6059356/127466910-fd06db53-98eb-4c96-b792-efda64cd3c9d.png">

**Comment by tomholub** [comment]
To be fair, when the Email Key Manager is used and you end up seeing this setup screen, it could be highlighted.

Something like `Your keys are managed with your organization's Email Key Manager.`

I'll file an issue.
