### ISSUE TITLE
refactor to use ContactStore.getOneWithAllPubkeys instead of .get

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3905]
as a part of #3897, discussed in https://github.com/FlowCrypt/flowcrypt-browser/pull/3898:

`Promise<Contact>` is actually used for subsequent rendering in `renderPubkeyResult`. If we want to move the "diagnostics" logic to compose-recipients module `evaluateRecipients` method, that's ok, but we don't have to present the results as a list of `Contact`, as this is a bit misleading (`email` field will be copied all over the entries), so the perfect solution would be a special type with `email` field and a list of keys.
Currently, the diagnostics (figuring out the properties of the most appropriate key) is done by the line below.
```
const [preferred] = await ContactStore.get(undefined, [email]);
```
We can, of cause, get rid of the compatibility method `ContactStore.get` and move the key-picking logic to some other place, but we need to find all places where it used.
I see it is used in `GmailElementReplacer.evaluateStandardComposeRecipients()` too

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/pull/3898#discussion_r686244628_

> so the perfect solution would be a special type with email field and a list of keys

That sounds good to me

> We can, of cause, get rid of the compatibility method ContactStore.get and move the key-picking logic to some other place, but we need to find all places where it used.
I see it is used in GmailElementReplacer.evaluateStandardComposeRecipients() too

Got it. Here's the code:

```ts
      // pick first usableForEncryption
      let selected = contactWithAllPubkeys.sortedPubkeys.find(entry => !entry.revoked && entry.pubkey.usableForEncryption);
      if (!selected) {
        selected = contactWithAllPubkeys.sortedPubkeys.find(entry => !entry.revoked && entry.pubkey.usableForEncryptionButExpired);
      }
      if (!selected) {
        selected = contactWithAllPubkeys.sortedPubkeys[0];
      }
```

`GmailElementReplacer.evaluateStandardComposeRecipients()` only needs to know if there is any usable key or not. So it could be as simple as:

```diff
-const [contact] = await ContactStore.get(undefined, [email]);
+const pubkeys = await ContactStore.getOneWithAllPubkeys(undefined, [email]);
-if (contact && contact.pubkey) {
+if (pubkeys.filter(p => p.usableForEncryption).length) {
```

Therefore, the actual nuanced logic that relates to choosing public keys for encryption can be actually in the compose modules somewhere. Then we can always use `.getOneWithAllPubkeys`, and never `.get`, which should produce fewer quirks in code and in behavior, I think.

-----------------

We'll probably want to rename `.get` to `.getByFingerprint` and then forbid using emails in the method, only fingerprints.

Most usages are by email. Some of these are just trying to understand if the recipient has encryption or not. Some actually need the key. We'd have to evaluate them individually.

![image](https://user-images.githubusercontent.com/6306961/128932392-9b9a287a-b46c-4a02-9611-e5ab39e6ad6a.png)

Maybe another method would be useful, like `ContactStore.doesUsableKeyExistFor(email)` that could be used in `GmailElementReplacer.evaluateStandardComposeRecipients()` and also other places. Like this one:

```ts
      const [contact] = await ContactStore.get(undefined, [String($('.input_email').val())]);
      $('.action_add_contact')
        .text(contact?.hasPgp ? 'update key' : `import ${this.isExpired ? 'expired ' : ''}key`)
        .css('background-color', this.isExpired ? '#989898' : '');
    }
```

---------------------

> `Contact.hasPgp` just shows that a key exists, it may be revoked or expired, but generally I don't mind against moving key-selection logic out of ContactStore. It was implemented to mimick the original ContactStore with the intent of not making too much changes at once. Now that the code is looking stable, we can move on with further refactoring.

**Comment by tomholub** [comment]
@IvanPizhenko this is a larger issue. You could pick just one usage and make a draft PR replacing it as above, where we can discuss to see if you are on the right track.

**Comment by IvanPizhenko** [comment]
I'm trying to understand what this all about and I think I don't get it. I've looked into code and found that 2 out of 4 calls to `renderPubkeyResult()` already accompanied with call to `getOneWithAllPubkeys()`:
```typescript
  public reRenderRecipientFor = async (email: string): Promise<void> => {
    if (!this.addedRecipients.some(r => r.email === email)) {
      return;
    }
    const emailAndPubkeys = await ContactStore.getOneWithAllPubkeys(undefined, email);
    for (const recipient of this.addedRecipients.filter(r => r.email === email)) {
      this.view.errModule.debug(`re-rendering recipient: ${email}`);
      await this.renderPubkeyResult(recipient, emailAndPubkeys ? emailAndPubkeys.sortedPubkeys : []);
      this.view.recipientsModule.showHideCcAndBccInputsIfNeeded();
      await this.view.recipientsModule.setEmailsPreview(this.getRecipients());
    }
  };

  private checkReciepientsKeys = async () => {
    for (const recipientEl of this.addedRecipients.filter(
      r => r.element.className.includes('no_pgp'))) {
      const email = $(recipientEl).text().trim();
      const dbContacts = await ContactStore.getOneWithAllPubkeys(undefined, email);
      if (dbContacts && dbContacts.sortedPubkeys && dbContacts.sortedPubkeys.length) {
        recipientEl.element.classList.remove('no_pgp');
        await this.renderPubkeyResult(recipientEl, dbContacts.sortedPubkeys);
      }
    }
  };

```
The rest 2 are in the `evaluateRecipients()`:
```
    for (const recipientEl of recipientEls) {
        ...
        if (recipientEl.status === RecipientStatus.WRONG) {
          this.view.errModule.debug(`evaluateRecipients.evaluating: exiting because WRONG`);
          await this.renderPubkeyResult(recipientEl, 'wrong');
        } else {
          this.view.errModule.debug(`evaluateRecipients.evaluating: calling getUpToDatePubkeys`);
          const pubkeys = await this.view.storageModule.getUpToDatePubkeys(recipientEl.email);
          await this.renderPubkeyResult(recipientEl, pubkeys);
        }
        ...
    }
```
`renderPubkeyResult()` itself already doesn't take list of `Contact`:
```typescript
  private renderPubkeyResult = async (
    recipient: RecipientElement, sortedPubkeyInfos: PubkeyInfo[] | 'fail' | 'wrong'
  ) => {
      ...
  }
```
So what exactly should we refactor here? Maybe it is already more-less done?

**Comment by tomholub** [comment]
Look for places that still use `ContactStore.get` and replace with `ContactStore.getOneWithAllPubkeys`. See:

<img width="788" alt="image" src="https://user-images.githubusercontent.com/6306961/149665157-a2281cef-4d68-4d3f-89ca-61053c1de45a.png">

**Comment by rrrooommmaaa** [comment]
in unit tests simply delete all the checks -- they will be no longer relevant

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa @tomholub 
I've digged code a bit, and what I can see, is that only following properties are used from returned `Contact`:
- contact.hasPgp - 1 time
- contact.pubKey - 2 times
- contact.email -  1 time
- contact.name - 2 times

But to get `hasPgp` and `pubKey` it does some more:
```typescript
      // pick first usableForEncryption
      let selected = contactWithAllPubkeys.sortedPubkeys.find(entry => !entry.revoked && entry.pubkey.usableForEncryption);
      if (!selected) {
        selected = contactWithAllPubkeys.sortedPubkeys.find(entry => !entry.revoked && entry.pubkey.usableForEncryptionButExpired);
      }
      if (!selected) {
        selected = contactWithAllPubkeys.sortedPubkeys[0];
      }
      return ContactStore.toContactFromKey(contactWithAllPubkeys.info, selected?.pubkey, selected?.lastCheck, Boolean(selected?.revoked));
```
i.e. it calls `getOneWithAllPubkeys()` and then finds first suitable key. So I don't think we can call just `getOneWithAllPubkeys()` in all cases, because it will need to put above logic in multiple places, which is code duplication. Instead we likely need new function called like `getOneWithSuitableKey()`. What do you think?

**Comment by rrrooommmaaa** [comment]
Is `Contact.pubKey` only used in `AddPubkeyView`.`copyFromEmailHandler()`?
It is only for display, we're planning to copy all the keys anyway.
Makes sense to complete #4112 first

**Comment by rrrooommmaaa** [comment]
as for `Contact.hasPgp` -- is it used in two places only?
In compose-recipient-module, I guess `ContactStore.getEncryptionKeys()` is good enough. If the returned array is non-empty, then `hasPgp` is considered `true`.
in `PgpPubkeyView`.`setBtnText()`, I guess if `ContactStore.getOneWithAllPubkeys()` returns non-empty, we can consider `hasPgp` = `true` for this purpose, that is the button should read "update key'.
Are there any other places where these values may be used?

**Comment by IvanPizhenko** [comment]
> Is `Contact.pubKey` only used in `AddPubkeyView`.`copyFromEmailHandler()`? It is only for display, we're planning to copy all the keys anyway. Makes sense to complete #4112 first

@rrrooommmaaa ok, then will wait for #4112
