### ISSUE TITLE
copying tab-indented text into rich text compose strips tabs

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3925]
If I copy some text (eg from Geany) to secure compose, it loses leading tabs.

```
line
\tanother
```

(where \t is an actual tab copied over) will become

```
line
another
```

But works with spaces.

**Comment by limonte** [comment]
Some investigation details so far:

Given this text is in clipboard:

<img width="197" alt="CleanShot 2021-09-02 at 14 50 31@2x" src="https://user-images.githubusercontent.com/6059356/131838742-cd902068-ebf0-40f3-b9f9-0c27be49d1e0.png">

---

First, let's paste it to Gmail:

<img width="111" alt="CleanShot 2021-09-02 at 14 52 23@2x" src="https://user-images.githubusercontent.com/6059356/131838890-605cca50-5c28-433b-a896-ceb1622eed9d.png">

Tabs from the first line are converted to spaces, other tabs are ignored.

---

Then, let's go back to Squire editor. In the [`willPaste` event handler](https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/chrome/elements/compose-modules/compose-input-module.ts#L80) we do not have the raw text from the clipboard, but the [document fragment](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment):

<img width="261" alt="CleanShot 2021-09-02 at 14 57 02@2x" src="https://user-images.githubusercontent.com/6059356/131839611-a822d3e1-9b75-4f92-8e2f-cbcb64e191c6.png">

As per the screenshot, there are no leading tabs in the document fragment.

For the comparison, here's what we have when there are leading spaces:

<img width="222" alt="CleanShot 2021-09-02 at 15 00 26@2x" src="https://user-images.githubusercontent.com/6059356/131839975-c5354cd2-8d5f-4b26-97d9-0778725189c4.png">

---

Squire editor should be investigated for the possibility of interception the `willPaste` event.
