### ISSUE TITLE
messages on live test gmail account missing

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3929]
This may possibly be caused by one of the updates that deletes last message in conversation - or similar - possibly it could have gradually deleted all messages by mistake?

![image](https://user-images.githubusercontent.com/6306961/130644138-c8bcab5b-18b7-4231-a838-78226a2eae73.png)

In this issue, let's try to identify the offending code and remove it.

Then in a follow up PR me or someone will re-populate the inbox and do a backup of it somehow before we run more tests.

Or maybe we ensure the emails are present (or upload them) before each test.

**Comment by tomholub** [comment]
To be fair, when debugging other brokenness, on my first test it seemed to log in ok (with a backup loaded from inbox). On my second test, the backup was missing. Unsure if this is coincidence, that the backup was the last email to be destroyed just as I was testing it, or if I helped it somehow.

**Comment by tomholub** [comment]
I may like the idea that we would have a method to ensure message is present, or upload it, on start of the gmail test. Something like this:

```diff
    // broken - https://github.com/FlowCrypt/flowcrypt-browser/issues/3929
    ava.default.skip('mail.google.com - decrypt message in offline mode', testWithBrowser('ci.tests.gmail', async (t, browser) => {
      const gmailPage = await BrowserRecipe.openGmailPage(t, browser);
+     await ensureMessagePresent('message-export-15f84afa553d8a83.json');
      await gmailPage.type('[aria-label="Search mail"]', 'encrypted email for offline decrypt');
      await gmailPage.press('Enter'); // submit search
      await Util.sleep(2); // wait for search results
      await gmailPage.page.setOfflineMode(true); // go offline mode
      await gmailPage.press('Enter'); // open the message
```

This `ensureMessagePresent` method would check for presence of message with Gmail API, by subject. If the message is missing, parse the raw mime out of the supplied file (`message-export-15f84afa553d8a83.json`) and store upload it to the mail server, then verify presence again.

We already use Gmail API in tests to clear out drafts, so it's not a big stretch to do this, and would hopefully therefore be robust to unwanted state changes on the email account.

**Comment by limonte** [comment]
Oops, this sucks. This is indeed most probably caused by my changes 😭

The deletion of messages from inbox has happened here: 

```js
  public static emptyDrafts = async (gmailPage: ControllablePage) => {
    await Util.sleep(1);
    await gmailPage.waitAndClick('[data-tooltip="Drafts"]');
    await Util.sleep(1); // <- instead of 1s sleep, there should be more robust line ensuring that we're actually in drafts
    await gmailPage.page.keyboard.press('*');
    await gmailPage.page.keyboard.press('a'); // Select all
    await Util.sleep(.5);
    await gmailPage.page.keyboard.press('#'); // Delete
  }
```

And then deleted messages were erased by the `emptyTrash` helper. 

---

Actions: 
- remove the `emptyTrash` helper, I implemented it because I suspected the wrong reason for flaky test failure.
- change the `emptyDrafts` helper to either ensure that we're in the Drafts section before deleting messages or use Gmail API.

**Comment by limonte** [comment]
@tomholub I need your help here:

https://user-images.githubusercontent.com/6059356/130669890-6f87571f-fbbd-48f3-8d74-4829aff45150.mp4

FlowCrypt is asking me to create a new key for `ci.tests.gmail@flowcrypt.dev` instead of asking for a password for an existing key. What might be the reason for that?

**Comment by limonte** [comment]
Now I feel even more stupid 🤦🤦🤦 There's already implemented `deleteAllDraftsInGmailAccount` method which uses Gmail API.

Note to myself: track the PRs by other people more carefully.

**Comment by limonte** [comment]
> Do you have access to flowcrypt.compatibility email? 

I had it at some point, but I can't recall now where to find the credentials. I thought they are in the secrets file, but it's not the case. Please email me instructions how to access it, thank you!

**Comment by limonte** [comment]
Done in #3941 (forgot to use `close #3929` there)
