### ISSUE TITLE
Why the limit of attachments is 10?

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3940]
While reporting #3939 I faced the limit of attachments is 10. I wonder why we do that limit? For testing purposes, I increased the limit locally and sent an encrypted email with 36 attachments without any issues.

I assume that for some users 10 attachments would not be enough. Should we increase the limit to, let's say, 100?

**Comment by tomholub** [comment]
There was some UI problem when attaching many attachments in the composer, at least in the past. An overflow of some sort, getting cut off screen. If you don't find any UI issue anymore, then the limit could be increased. 100 sounds like a lot especially if we don't have a "download all" button, but 30 sounds reasonable?

**Comment by tomholub** [comment]
(I'm no longer subscribed the repository's all issues - generally I'll only notice when you @tomholub me)

**Comment by limonte** [comment]
> There was some UI problem when attaching many attachments in the composer, at least in the past. An overflow of some sort, getting cut off screen. If you don't find any UI issue anymore, then the limit could be increased. 

All is well nowadays.

**Composer:**

https://user-images.githubusercontent.com/6059356/132199563-4b1a6b00-713d-4271-8d98-67a382defc8f.mp4 

**Reply box:**

<img width="1015" alt="CleanShot 2021-09-06 at 12 58 06@2x" src="https://user-images.githubusercontent.com/6059356/132199147-5dec74d6-c997-4558-bfb6-96490d8f6c81.png">

> but 30 sounds reasonable?

In one of gmail live tests, I created a message with 36 attachments just to have all the most common file extensions in one place to easily preview them. The were no issues in UI or rendering performance. 30 is reasonable, but I'd personally raise that limit to 50 because as I mention there are no strong reasons not to do that (UI is fine, rendering performance is fine).

> (I'm no longer subscribed the repository's all issues - generally I'll only notice when you @tomholub me)

Roger 👍 Is there a person who will quickly check out all newly reported issues and decide what to do with them? (e.g. mark them as actionable, move to the discussion, or mention @tomholub if unsure)

**Comment by tomholub** [comment]
Not right now. I'll be checking new issues roughly every other week to sort them out - if you run out of issues before then, please tag me. Thanks!

**Comment by limonte** [comment]
Got you, thanks! So, 30 or 50? Let me know what's your last word because I don't have a strong opinion, but 50 will satisfy the needs of more users (e.g. me in CI tests 😄)

**Comment by tomholub** [comment]
Let you decide, don't have a strong opinion either

**Comment by limonte** [comment]
> Let you decide, don't have a strong opinion either

I'll go with 50 and do additional testing on Windows machine with 50 attachments 25 MB in total. Just to double-check that the rendering performance is also ok there.
