### ISSUE TITLE
[user concerns][compatibility issue] users cannot login to flowcrypt browser extension after they change their passphrase through flowcrypt for android

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#3945]
Hello Team,

This issue is based on our user's report after experiencing a compatibility issue between the flowcrypt for android and the flowcrypt browser extension. 

Description:

Users who initially used FlowCrypt for android cannot be logged into their account through the FlowCrypt browser extension after they decided to change their passphrase in their FlowCrypt for android.

Problem: 

Users will not able to use their account through the FlowCrypt extension because the said application throws an error that says: `Error: Encrypted private key is authenticated using an insecure two-byte hash.` Which likely came after changing their passphrase on FlowCrypt for android.

I was able to reproduce it in both Firefox and Chrome browsers:

Error in chrome browser:
![insecure-hash for chrome error](https://user-images.githubusercontent.com/46025304/131442814-82089c03-e4da-446a-95ca-64681fdfa28e.png)
Error in Firefox browser
![error insecure two-byte hash](https://user-images.githubusercontent.com/46025304/131442831-0645273e-f1ba-4fd4-b37f-9a681f48743d.png)

Steps to reproduce:
1. log in to Flowcrypt for android with a fresh Google account.
2. Continue to create a new key and finish setting up your passphrase.
3. Change your passphrase using FlowCrypt for android.
4. Open your browser ( firefox/chrome) and login to the FlowCrypt browser extension and authenticate.
5. On the "recover your passphrase" phase, input the new passphrase you just set on step 3.
6. The browser will throw an error saying `Error: Encrypted private key is authenticated using an insecure two-byte hash.` and you will not able to pass through that error making your FlowCrypt account unusable.

Reference: 
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkbDThpqzzjHPsRcXdzPgXPRpq
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGkZsxHpxLBfQZHkkhjtRJqFPMM

Kind Regards,
Mart Gil

**Comment by martgil** [comment]
Hi Team,

Just a piece of additional information. After this issue occurs, the users will unable to use any other backup they own. Even after they choose to skip entering any of the passphrases they remember and generate a new one. Once they reset it, the previously generated key will in fact also become unusable.

**Comment by martgil** [comment]
Hi @tomholub,

I am a bit worried that some of the FlowCrypt users are experiencing this bad issue. It is way impactful enough for the FlowCrypt browser extension itself to deny account access to the account owners (somewhat like permanently and I personally experience it too with my own account).

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGljljprLGFxZrPXRqxmWDtsqjz

Kind Regards,
Mart Gil

**Comment by tomholub** [comment]
@DenBond7 please see if you can reproduce this

**Comment by tomholub** [comment]
If yes, please give appropriate info to Paul to investigate.

**Comment by DenBond7** [comment]
@martgil Thank you for the report. I'm still doing investigation.

I can confirm this bug. Could you ask a user check maybe he has old backups? We don't delete existing backups after the passphrase change. If he will delete a new backup he will be able to login with the old backups. I've checked that.

@tomholub By the way, it seems FlowCrypt for browser(Chrome) doesn't allow to continue if one of the key was affected. Even if we have good backups.

**Comment by tomholub** [comment]
The user could download the bad backup to their computer, then move it to Trash on Gmail. Then it will be ignored by the browser extension.

**Comment by martgil** [comment]
>I can confirm this bug. Could you ask a user check maybe he has old backups? We don't delete existing backups after the passphrase change. If he will delete a new backup he will be able to login with the old backups. I've checked that.

Hi @DenBond7, You're welcome! I have sent them some updates at this moment. Btw, you are correct here. I tried to follow your instructions and, I was able to use my previous backup after deleting the faulty backup out from my account. I just wonder how about those who haven't had any other backup aside from the faulty one. Does it mean they have no other choice but to generate a new key instead after they deleted the faulty one?

> The user could download the bad backup to their computer, then move it to Trash on Gmail. Then it will be ignored by the browser extension.

@tomholub, just a clarification. I tried moving them directly to trash alone and doesn't work at least for me. It happens that, I need to completely delete it away from my Gmail before it starts detecting that the backup is fully removed and those previous backups left are started to be recognized again by the FlowCrypt browser extension.

**Comment by DenBond7** [comment]
@martgil 
>  I just wonder how about those who haven't had any other backup aside from the faulty one. Does it mean they have no other 
choice but to generate a new key instead after they deleted the faulty one?

We've found a reason of the issue. Please let me work on that. I will add more details soon.

**Comment by martgil** [comment]
Understood, sir! Thank you!

**Comment by DenBond7** [comment]
@martgil 
>I just wonder how about those who haven't had any other backup aside from the faulty one. Does it mean they have no other choice but to generate a new key instead after they deleted the faulty one?

We've made a new release. Need to wait some time while the new version will be available for download. To fix an issue a user can follow these steps:

1. Update the app to 1.2.1
2. Go to `Settings `-> `Security and Privacy` -> `Change pass phrase`
3. Change the pass phrase
4. Go to Gmail for web
5. Check if a new backup was created(if not, go to `Settings `-> `Backups` -> `Backup as Email`)
6. Find old backups and save them locally(just in case)
7. Delete old backups(#3968). Maybe need to delete them from `Trash`
8. Try to set up FlowCrypt for Web with a new backup(the last one that we created at `3.` or `5.`)

**Comment by martgil** [comment]
Hi @DenBond7, Thank you! I can now confirm the new release is now available for download by checking the change logs from playstore. 

```
- WHAT’S NEW
- fixed pass phrase incompatibility with browser extension
```

I also provide some updates to the respondents as well.

Thank you!

**Comment by tomholub** [comment]
closing as fixed on Android - thanks everyone!
