### ISSUE TITLE
Update check-for-email github action

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-browser#3956]
Please point it to the `FlowCrypt/comment-email-address-alerts@v19`.
I tried to do it myself, but I seem to don't have push access for this repo.

Original issue: https://github.com/FlowCrypt/flowcrypt-ios/issues/480

**Comment by IvanPizhenko** [comment]
Alternatively, @DenBond7 can you please grant me push access to this repo? Then I will post PR myself.

**Comment by DenBond7** [comment]
@IvanPizhenko I've sent an invite. Please try.

**Comment by IvanPizhenko** [comment]
> @IvanPizhenko I've sent an invite. Please try.

@DenBond7 thank you! I have accepted invite.

**Comment by IvanPizhenko** [comment]
@DenBond7 But still no push access. I've cloned repo, created branch, made changes, committed, tried to push branch.
```shell
$ git push --set-upstream origin ip-3956-update-check-for-emails
ERROR: Permission to FlowCrypt/flowcrypt-browser.git denied to IvanPizhenko.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by DenBond7** [comment]
@IvanPizhenko I've added new changes. Please retry.

**Comment by IvanPizhenko** [comment]
> @IvanPizhenko I've added new changes. Please retry.

@DenBond7 Thank you! After this I was able to push my changes.
