### ISSUE TITLE
Access to Semaphore for this repo

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-browser#3958]
I wanted to look at CI test results in the PR #3955 (because we need to do the same upgrade of the openpgp.js version in the FES web portal) and Semaphore returned page "404" . Please grant me access to view Semaphore test results in this repo.

**Comment by DenBond7** [comment]
@tomholub Could you check that? It seems I don't have access too.(404)

**Comment by tomholub** [comment]
@DenBond7 I've promoted you admin on semaphore. Once Ivan has write privileges on this repo, you can go to project settings on semaphore and refresh the members list, he should show up there at that point.

**Comment by DenBond7** [comment]
@tomholub Thank you, now I have access.
@IvanPizhenko Please try again

**Comment by IvanPizhenko** [comment]
@DenBond7 Thank you, now I have the access.
