### ISSUE TITLE
Local draft should override the cloud draft once user get back online

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3971]
While working on #3126 and #3337 I faced this issue which might cause lost reply drafts in use-cases described below:

### Steps to reproduce

1. Open any secure email
2. Type "123" into the secure reply, ensure the cloud draft is saved normally (`Saved`)
3. Go offline
4. Type "456" into the same reply box, so the whole reply is now "123456", ensure the draft is saved locally (`Draft saved locally (offline)`)
5. Go to inbox
6. Go back online
7. Open the same secure email

### Expected behavior

The user sees the "123456" draft (local draft, if exists in the same thread, should override the cloud draft)

### Actual behavior

The user sees the "123" draft, the local draft is lost.

**Comment by limonte** [comment]
@tomholub what is the proper terminology for "normal" (not local) drafts? I believe calling them "normal" isn't right, but I can't come up with the better wording.

**Comment by tomholub** [comment]
Could be email provider draft maybe? Or cloud draft?

**Comment by limonte** [comment]
> Could be email provider draft maybe? Or cloud draft?

Cloud draft sounds good, thanks 👍
