### ISSUE TITLE
show all fingerprints when hovering over recipient

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3985]
In the past, we used to only have one public key possible per recipient. After that, we refactored some code to allow more than one public key. So now, if I email `joe@example.com`, I may have 3 public keys recorded for them locally, and encrypt the message for all three public keys.

However, when I hover over the recipient in compose box, it will only show one of the public key fingerprints. This is because we didn't refactor all of the code, and somewhere we pull just one public key instead of pulling all as we should to display this.

Instead, it should be showing the primary fingerprint of each public key we have recorded for that person.

Feel free to ask rrrooommmaaa where you need questions asked about the codebase.

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa Here's what I've found in the code (`extension/chrome/elements/compose-modules/compose-recipients-module.ts`):
```typescript
      $(el).attr('title', 'Does use encryption' + this.recipientKeyIdText(contact));
```
and then 
```typescript
  private recipientKeyIdText = (contact: Contact) => {
    if (contact.fingerprint) {
      return `\n\nRecipient public key fingerprint:\n${Str.spaced(contact.fingerprint)}`;
    } else {
      return '';
    }
  }
```
And then (`extension/js/common/core/crypto/key.ts`)
```typescript
export type Contact = {
  email: string;
  name: string | null;
  pubkey: Key | undefined;
  hasPgp: 0 | 1;
  fingerprint: string | null;
  lastUse: number | null;
  pubkeyLastCheck: number | null;
  expiresOn: number | null;
  revoked: boolean;
};
```
So finally `Contact` has only one key and fingerprint, and I assume we need to bring there multiple ones.

**Comment by IvanPizhenko** [comment]
> So now, if I email joe@example.com, I may have 3 public keys recorded for them locally, and encrypt the message for all three public keys.

@rrrooommmaaa where does encryption with all keys happens in the code?

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa any ideas how should we proceed with this one? Seems like changing `Contact` will make it incompatible with existing contact database, which should be somehow migrated then.

**Comment by tomholub** [comment]
Instead of changing `Contact` (not desired), you would be passing around an array of `Contact[]`. Then, wherever it currently uses some `ContactStore` method that only pulls a single `Contact`, you would instead use another existing `ContactStore` method that returns `Contact[]` and pass the array around to display here.

For encryption, public keys are currently pulled at `general-mail-formatter.ts`, this line:

```ts
const { pubkeys, emailsWithoutPubkeys } = await view.storageModule.collectAllAvailablePublicKeys(newMsgData.from, senderKi, recipientsEmails);
```

**Comment by IvanPizhenko** [comment]
@tomholub ok, but then there is another question - how do we display expired/revoked/"no pgp" statuses in this case? Currently the code checks some fields of the `contact` and displays statuses based on that:
```typescript
if (contact.pubkey && ((contact.expiresOn || Infinity) <= Date.now() || contact.pubkey.usableForEncryptionButExpired)) {
      recipient.status = RecipientStatus.EXPIRED;
    ....
} else if (contact.revoked) {
      recipient.status = RecipientStatus.REVOKED;
    ....
else if (contact.pubkey) {
      recipient.status = RecipientStatus.HAS_PGP;
   ....
else {
      recipient.status = RecipientStatus.NO_PGP;
    ....
}
```
Now look at the above code and assume `contact` will be array of `Contact`. How to display statuses in this case? Is it reliable to just take first element and display based on it? Or should there be some more sophisticated logic?

**Comment by tomholub** [comment]
The logic would be:
 - if there is at least one valid (non-expired, non-revoked) public key, then it's HAS_PGP
 - else if there is at least one expired public key, then it's EXPIRED
 - else if there is at least one revoked key, then REVOKED
 - else it's NO_PGP

If you will be always rendering from there, with all of this information, then you could list all fingerprints in the black tooltip, for example as follows:
```
Valid public key fingerprints:
aaaa (openpgp)
bbbb (openpgp)

Expired public key fingerprints:
cccc (openpgp)

Revoked public key fingerprints:
ddd (openpgp)
```

So if there are no valid, you would render:
```
Expired public key fingerprints:
cccc (openpgp)

Revoked public key fingerprints:
ddd (openpgp)
```

If there are only valid, then:
```
Valid public key fingerprints:
aaaa (openpgp)
bbbb (openpgp)
```

If it's actually an S/MIME key that you came across:
```
Valid public key fingerprints:
aaaa (s/mime)
```

That will be easier for debugging. Thanks!

**Comment by IvanPizhenko** [comment]
`lookupPubkeyFromKeyserversThenOptionallyFetchExpiredByFingerprintAndUpsertDb` rocks!
The longest human-invented method name in the real project I've ever seen.

**Comment by tomholub** [comment]
:-) I don't know if I should be proud or ashamed.

Really, the method should probably be broken up somehow. The long name already correctly highlights the ridiculousness of how much happens in that method.

**Comment by tomholub** [comment]
@rrrooommmaaa to be clear - the above logic only applies to choosing how to color the recipient field. Would the `.sortKeys` method be actually helpful for that? It seems to me you'd still have to follow a similar decision tree after that, to decide how to color the recipient.

**Comment by rrrooommmaaa** [comment]
@tomholub To color the recipient field (that is a single value from possibly several keys, right?) we can take the color of the best key, and the best key always comes first in the sorted list. First there are valid keys (if any) (sorted by descending expiration dates), then expired (if any), then revoked (if any). And within revoked they should be sorted by descending expiration date.

> Is it reliable to just take first element and display based on it? Or should there be some more sophisticated logic?

Should be. If the first key is valid, then the overall status is valid.
If the list is empty, then `NO_PGP`.
If the first key is expired, then expired is the best option.
The worst scenario is when the first key is revoked.

**Comment by rrrooommmaaa** [comment]
@IvanPizhenko The real contact store can be tested directly with a browser unit test, located in `unit-ContactStore.js`. I see there are currently no tests for calling getOneWithAllPubkeys directly, the closest one that tests sorting is `ContactStore gets a valid pubkey by e-mail, or exact pubkey by longid`.
We can add more tests for edge cases to test sorting (and grouping), if in doubt.

**Comment by tomholub** [comment]
> @tomholub To color the recipient field (that is a single value from possibly several keys, right?) we can take the color of the best key, and the best key always comes first in the sorted list. First there are valid keys (if any) (sorted by descending expiration dates), then expired (if any), then revoked (if any). And within revoked they should be sorted by descending expiration date.
> 
> > Is it reliable to just take first element and display based on it? Or should there be some more sophisticated logic?
> 
> @IvanPizhenko Should be. If the first key is valid, then the overall status is valid.
> If the list is empty, then `NO_PGP`.
> If the first key is expired, then expired is the best option.
> The worst-case scenario is when the first key is revoked.

Yes, single value color for all of the keys.

I see. Therefore you recommend to use `.sortKeys` on the key array, and then using the first result from that, and basically re-introducing back the color choosing logic that was based on one key.

Sounds good, I didn't realize that.

(the above is for color choosing, while we'll still be showing all fingerprints in the tooltip as was already done)

**Comment by rrrooommmaaa** [comment]
> Therefore you recommend to use .sortKeys on the key array

Actually, `getOneWithAllPubkeys` already returns `sortedKeys`, so no need for additonal call.

> while we'll still be showing all fingerprints in the tooltip as was already done

If you're referring to PR #4003 , storing result of `ContactStore.get` into `Contact[]` doesn't get us an array of more than one contact/pubkey per email. We need to call a different method instead --  `getOneWithAllPubkeys`

**Comment by rrrooommmaaa** [comment]
> @rrrooommmaaa where does encryption with all keys happens in the code?

This is really in `collectAllAvailablePublicKeys` which calls `ContactStore.getEncryptionKeys` which in turn uses `getOneWithAllPubkeys` per each recipient.
There is also additional logic: if a recipient has a valid non-expired key (displayed as HAS_PGP), then expired keys of that recipient are not included. If the recipient has only expired keys, then all his expired keys are included (the page shows an appropriate warning in this case).

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa I think I have one problem with all this - I quite don't get how should I rewrite that method
`lookupPubkeyFromKeyserversThenOptionallyFetchExpiredByFingerprintAndUpsertDb()` in regard of using `getOneWithAllPubkeys()`. Please advise.

**Comment by tomholub** [comment]
I think instead of `ContactStore.get` you'd write `ContactStore.getOneWithAllPubkeys`. The rest of that method will stay as you already updated it, it seems.

**Comment by IvanPizhenko** [comment]
They return different types. And then `checkKeyserverForNewerVersionOfKnownPubkeyIfNeeded` requires `Contact`, but  `getOneWithAllPubkeys` returned something different and I'm not sure how to **correctly** convert that to `Contact`. So I'd wait for some more explanations from @rrrooommmaaa how does he imagine this.

**Comment by IvanPizhenko** [comment]
Trying to do something with it... Will tag Roman when done.

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa I did it to some extent, please review the current state, but I'm stuck at this point.
```typescript
  public lookupPubkeyFromKeyserversThenOptionallyFetchExpiredByFingerprintAndUpsertDb = async (
    email: string, name: string | undefined
  ): Promise<EmailWithSortedPubKeys[] | "fail"> => {
    // note by Tom 2021-08-10: We are only getting one public key from storage, but should
    //    work with arrays instead, like with `ContactStore.getOneWithAllPubkeys`.
    //    However, this whole fingerprint-base section seems unnecessary, we could likely
    //    remove it and the keys will be updated below using
    //    `lookupPubkeyFromKeyserversAndUpsertDb` anyway.
    //    discussion: https://github.com/FlowCrypt/flowcrypt-browser/pull/3898#discussion_r686229818
    const storedContact = await ContactStore.getOneWithAllPubkeys(undefined, email);
    if (storedContact && storedContact.sortedPubkeys.length) {
      const results: PubKeyInfo[] = [];
      for (const pubkey of storedContact.sortedPubkeys) {
        if (!pubkey.revoked) {
          // checks if pubkey was updated, asynchronously. By the time user finishes composing,
          //    newer version would have been updated in db.
          // This implementation is imperfect in that, if sender didn't pull a particular pubkey
          //    for a long time and the local pubkey has since expired, and there actually is a
          //    newer version available on external key server, this may unnecessarily show "bad pubkey",
          //    until next time user tries to enter recipient in the field again, which will at that point
          //    get the updated key from db. This could be fixed by:
          //      - either life fixing the UI after this call finishes, or
          //      - making this call below synchronous and using the result directly
          this.checkKeyserverForNewerVersionOfKnownPubkeyIfNeeded(storedContact.info.email, pubkey)
            .catch(Catch.reportErr);
          results.push(pubkey);
        } else {
          const res = await this.lookupPubkeyFromKeyserversAndUpsertDb(email, name, pubkey);
          if (res === 'fail') return res;
          results.push(res);
        }
      }
      // TODO: Do something with result.
    }
    return 'fail';
  }
```
I need to return array `EmailWithSortedPubKeys` from this method, but when I have array of PubKeyInfo, it does not have all information needed to construct `EmailWithSortedPubKeys` or I don't know how to do it. In particular I need to fill `info: Email` in the `EmailWithSortedPubKeys` which is:
```typescript
export type Email = {
  email: string;
  name: string | null;
  searchable: string[];
  fingerprints: string[];
  lastUse: number | null;
};
```
I don't know how to fill these fields (maybe expect email and name). Please advise.

**Comment by tomholub** [comment]
> They return different types. And then `checkKeyserverForNewerVersionOfKnownPubkeyIfNeeded` requires `Contact`, but `getOneWithAllPubkeys` returned something different and I'm not sure how to **correctly** convert that to `Contact`. So I'd wait for some more explanations from @rrrooommmaaa how does he imagine this.

I imagine you could refactor everything downstream to use `EmailWithSortedPubKeys` instead of `Contact[]`. I'm thinking that based on this comment from him:

> We will most likely get rid of Contact type and ContactStore.get method when no consumers are left. Still, let's keep key selection in one place.

Which makes sense to me now.

**Comment by rrrooommmaaa** [comment]
Yes, `Contact` is like a leftover form `one email - one or zero pubkeys` architecture. Most methods require either a single pubkey, or an email with all the pubkeys. I'll have a look at these methods to see how they fit into the new architecture.

**Comment by IvanPizhenko** [comment]
@tomholub In fact, I'm trying to refactor to the some extent, but I am facing some difficulties and not enough understanding of the involved data structures and code logic. So I may be asking lot of questions like above one.

**Comment by rrrooommmaaa** [comment]
> I don't know how to fill these fields (maybe expect email and name). Please advise how to do it.

As I can see, `renderPubkeyResult` and `publicKeysToRenderedText` only use pubkeys data or am I missing something? Isn't it enugh to pass `PubKeyInfo[]`?

> Also I need to sort keys again, because some might have been newly received from keyserver, but sortKeys method signature is far from what I have here.

Good catch, I refactored ContactStore in your branch to be more flexible, first converting to PubkeyInfo, then sorting. Or even, I think we can use `max` with sorting function if we only need to find the best key. Please pull.
Please rename to `PubkeyInfo` (small letter `k`) as we have `Pubkey` anywhere.
And we're mostly using `undefined` instead of `null` as linter suggests. The only exception is when loading data from storage or some external source, I guess.

**Comment by IvanPizhenko** [comment]
Thank you @rrrooommmaaa for help with this. So I'll continue to work on this and may ask more questions.

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa 
So here is the next question:
 I have refactored function `reRenderRecipientFor()` to use newly introduced `PubKeyInfo` instead of `Contact`. It has 2 uses over code entire code. I've refacored one of them, but I absolutely don't get how to refactor the remaining one. It is used in a sort of hook:
```typescript
// in extension/chrome/elements/compose-modules/compose-recipients-module.ts
    BrowserMsg.addListener('reRenderRecipient', async ({ contact }: Bm.ReRenderRecipient) => await this.reRenderRecipientFor(contact));
```
So how to refactor this one? Or maybe you can do it?

**Comment by tomholub** [comment]
You could change type of `Bm.ReRenderRecipient` to accept a non-contact value if that's what you want. Currently it's probably `{contact: Contact}` but you can make it eg `{ pubkeyInfo: PubkeyInfo }` instead, or whatever you needed.

**Comment by tomholub** [comment]
Then search for `BrowserMsg.send.reRenderRecipient` to update usage as well.

**Comment by IvanPizhenko** [comment]
@tomholub Thank you, but I don't think I have so good understanding of the code so I will know where else I will have to change things after "changing type of Bm.ReRenderRecipient to accept a non-contact value". So I'd prefer to stick now to the smaller change right at the moment. Later on someone can refactor this. Also let's wait for what @rrrooommmaaa would say, maybe he will reveal more details on how to do this correctly.

**Comment by IvanPizhenko** [comment]
> Then search for `BrowserMsg.send.reRenderRecipient` to update usage as well.

@tomholub I've checked for this, there are two occurrences, and it seems like for now I've done the correct thing - because otherwise I would put similar code twice in the both places where it is called.

**Comment by rrrooommmaaa** [comment]
@IvanPizhenko Yes, `reRenderRecipient` can be refactored to accept only `email` without Contact.
`addContactHandler` can be simplified and refactored (it still assumes it is interacting with old-style ContactStore)
I added an issue #4025 for that

**Comment by IvanPizhenko** [comment]
ok

**Comment by IvanPizhenko** [comment]
Finally I've fixed this test. I had to restore:
```typescript
    const res = await this.lookupPubkeyFromKeyserversAndUpsertDb(email, name, undefined);
    if (res === 'fail') return res;
    return [res];
```
in the end of method `lookupPubkeyFromKeyserversThenOptionallyFetchExpiredByFingerprintAndUpsertDb()`.

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa Now to solve next failing test I need to fix method `lookupPubkeyFromKeyserversAndUpsertDb()`, and in order to fix it, I need to convert `Contact` into `PubKeyInfo`. How to do it correctly? Can you explain in details and/or please provide/point me to ready conversion function?

**Comment by IvanPizhenko** [comment]
I think I understand how to convert `Contact` to `PubKeyInfo`.
