### ISSUE TITLE
`pgp_block` should be removed after clicking the "End Pass Phrase session"

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#3993]
Because `pgp_block` isn't currently being removed, it duplicates itself as many times as the "End Pass Phrase session" button was clicked: 

https://user-images.githubusercontent.com/6059356/134169031-88bf274d-f048-4f9a-b508-bff4edb78f00.mp4

**Comment by tomholub** [comment]
It is a bug no doubt, but maybe not worth fixing :-) as I worry, removing the frames could cause bugs worse than this in other situations. I'll close this as a rare situation.
