### ISSUE TITLE
recipients field does not recognize company contacts

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#3998]
for example, if there is some `user` `@flowcrypt.com` which I've never looked up or written to before, searching the first name `user` will produce the person in regular gmail compose (if I'm also on a `flowcrypt.com` gmail domain) but doing the same in secure compose will not find that person.

**Comment by tomholub** [comment]
We seem to have many similar issues - please triage this one too

**Comment by ioanmo226** [comment]
I couldn't reproduce this issue.
Could you check if this issue is up-to date?

**Comment by tomholub** [comment]
not at the moment, or unsure exactly how to reproduce. I'll close it, thank you.
