### ISSUE TITLE
Double auto approve for dependabot PRs

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-browser#4004]
Do similar thing as we did in another repo - auto-approve dependabot PRs by two "Robot" users.
See https://github.com/FlowCrypt/flowcrypt-enterprise-on-prem/issues/1463 for reference.

**Comment by limonte** [comment]
Could you please link to the issue/PR from another repo because the issue description doesn't tell anything about the reasons for double approve.

**Comment by IvanPizhenko** [comment]
@limonte Updated description with original issue.

**Comment by limonte** [comment]
@IvanPizhenko FYI https://github.com/FlowCrypt/flowcrypt-browser/pull/3996 is failing not because of approvals

**Comment by IvanPizhenko** [comment]
Looks like only single approval is needed on this repo, so closing this issue.
