### ISSUE TITLE
Rename type Contact

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-browser#4005]
This code makes me think we should start calling `Contact` something else. Probably `DbPubkey`, as the meaning of the structure has changed over time. That would be for another issue, of course.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/4003#discussion_r716183350_

**Comment by tomholub** [comment]
closing - the goal will eventually be to get rid of the `Contact` type by refactoring places that use it.
