### ISSUE TITLE
Sluggish encryption progress with csv attachment files 

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4032]
This issue was mainly coming from a FlowCrypt user.

Description:
Sending an encrypted message takes a long time when a having 5-6 CSV attachment files.

Steps to reproduce:
1. Download and prepare CSV test files.
2. Compose a simple message.
3. Try to add an attachment having 5-6 same category of CSV test files.
4. Hit "send" and the process will take quite some time to Encrypt and Send.

Sample attachments: 
[50000 Sales Records.csv](https://github.com/FlowCrypt/flowcrypt-browser/files/7275284/50000.Sales.Records.csv)
[10000 Sales Records.csv](https://github.com/FlowCrypt/flowcrypt-browser/files/7275276/10000.Sales.Records.csv)

Reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkFsqnVfJJlmfCgpnQqnBcktC

**Comment by martgil** [comment]
Thanks, @limonte! I agree with you. Maybe it may also depend on the user's machine capability. I test this out with 4 of those 50000 Sales Records CSV files with 6.2MB each and, it gives me about 9 minutes of waiting before it sends out. But yeah, encryption is not an instant process.

Thank you for sharing your insight with this, sir!

**Comment by martgil** [comment]
Just temporarily closing this one. The user is now able to send encrypted messages with attachments without any problem. Thank you!

**Comment by limonte** [comment]
> I test this out with 4 of those 50000 Sales Records CSV files with 6.2MB each and, it gives me about 9 minutes of waiting before it sends out. But yeah, encryption is not an instant process.

I believe you have a slow Internet connection. For me it takes less than 25s to encrypt and send those 4 big CSV files:


https://user-images.githubusercontent.com/6059356/135977066-8ceca931-d644-45d1-bc5d-5f580282c03a.mp4

**Comment by martgil** [comment]
Yes, maybe the internet connection is the problem in my case. Thank you, sir!
