### ISSUE TITLE
Unable to use my @flowcrypt.com account

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#4034]
I am currently getting this error in my `vladimir@flowcrypt.com` account:

<img width="529" alt="CleanShot 2021-10-04 at 14 11 18@2x" src="https://user-images.githubusercontent.com/6059356/135841627-9fca6203-5969-4695-8028-a4400c065caa.png">

```
This message could not be encrypted because your own Private Key is expired. 
You can extend expiration of this key in other OpenPGP software (such as gnupg), then re-import updated key _here_.
```

**Comment by limonte** [comment]
When I click the "here" link, this page is shown:

<img width="857" alt="CleanShot 2021-10-04 at 14 13 37@2x" src="https://user-images.githubusercontent.com/6059356/135841878-c5bd9e38-bb29-4cec-b242-e3517ea01048.png">

**Comment by limonte** [comment]
@limonte small details to fix somewhere:

1. horizontal alignment from the screenshot above
2. <img width="378" alt="CleanShot 2021-10-04 at 14 18 30@2x" src="https://user-images.githubusercontent.com/6059356/135842483-ea3298b6-04a5-4d59-8cfd-814c8bd34b1a.png">
3. <img width="231" alt="CleanShot 2021-10-04 at 14 18 56@2x" src="https://user-images.githubusercontent.com/6059356/135842537-4d85246f-f848-49e1-8c7c-134868909a7c.png">
4. <img width="273" alt="CleanShot 2021-10-04 at 14 19 21@2x" src="https://user-images.githubusercontent.com/6059356/135842592-e66588c0-6efd-4643-81b7-66f4e102662e.png">

**Comment by limonte** [comment]
@tomholub I believe your attention would be needed here

**Comment by tomholub** [comment]
@limonte this is due to unimplemented https://github.com/FlowCrypt/flowcrypt-browser/issues/2602 - for now, to grab your latest keys from EKM (which should not be expired), you would have to reset/reinstall the extension and go through setup again.

**Comment by limonte** [comment]
> @limonte this is due to unimplemented #2602 - for now, to grab your latest keys from EKM (which should not be expired), you would have to reset/reinstall the extension and go through setup again.

This helped, thanks!
