### ISSUE TITLE
Email check: ignore "Flowcrypt Compatibility"

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-browser#4037]
"Flowcrypt Compatibility" should be ignored

**Comment by limonte** [comment]
it's better to transfer this issue to https://github.com/FlowCrypt/comment-email-address-alerts

![CleanShot 2021-10-04 at 22 25 11@2x](https://user-images.githubusercontent.com/6059356/135911986-690ed76a-ed03-4545-a2f2-a946ca4266d1.png)

**Comment by IvanPizhenko** [comment]
@limonte No, action itself is kept "generic", any ignores are tuned right in the repo where it is applied.
See https://github.com/FlowCrypt/flowcrypt-browser/blob/master/.github/workflows/check-for-emails.yml for details.
