### ISSUE TITLE
Firefox draft UI issue when using mail.google.com as email client

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4039]
Description:
The draft UI produces likely a broken webpage when accessing a draft via mail.google.com using a Firefox Browser.

Steps to reproduce:

FlowCrypt extension version: 8.1.4
Firefox browser version: 92.0 (64-bit)

1. compose a draft message (mail.google.com as email client)
2. access the draft message through Google's native draft section
3. click on the draft message and click the "open draft" link.
4. the draft UI will not be rendered properly (you also barely see that passphrase is required to open the draft but then is barely visible especially at first glance).

Nonetheless, the draft UI looks good in the FlowCrypt extension email client.

**Comment by limonte** [comment]
I'm unable to reproduce the issue. What does "mail.google.com as web client" mean? Can you attach the video demonstrating the issue?

**Comment by martgil** [comment]
Sorry for the confusion. I'm referring to mail.google.com itself. Simply compose a draft message while using Gmail > view the draft > click the "open draft" link. At this point, the compose message box will become transparent.

Reference:
https://mail.google.com/mail/u/2/#archive/FMfcgzGlkFsqdrRbgDKMlKbzxmshKrJD

**Comment by limonte** [comment]
I am unable to reproduce. Can you attach the video demonstrating the issue?

**Comment by martgil** [comment]
Here it is:

https://user-images.githubusercontent.com/46025304/135981620-31a3229b-656b-45a0-83e4-19a14b875d87.mp4

This confuses the user after they click the open draft. The compose message box by Gmail will disappear and the secure message box from FlowCrypt will show up with a transparent window.

**Comment by limonte** [comment]
Thank you @martgil now the issue is clear.

**Comment by martgil** [comment]
You're welcome, sir! 🙇
