### ISSUE TITLE
Add info alert below the attachments when attachments are large

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#4040]
I believe what the user means by "Sluggish" is that encrypting takes some time before sending. For my machine, it took around 10s to encrypt two attached in the issue description files.

Encrypting is not an instant process and I believe we can't do anything here to speed up the process.

What we can do is to indicate to users beforehand that attachments are big and it will take time to send them. For example, this is what Thunderbird is doing:

<img width="403" alt="CleanShot 2021-10-04 at 14 40 29@2x" src="https://user-images.githubusercontent.com/6059356/135845449-1393b26b-ee19-46b2-89bf-762cceb9fe2a.png">

_Originally posted by @limonte in https://github.com/FlowCrypt/flowcrypt-browser/issues/4032#issuecomment-933401184_

**Comment by limonte** [comment]
The threshold could be 1 MB.

The wording could be "<icon_info> Attachments are large, it might take some time to encrypt and send them."

**Comment by tomholub** [comment]
As long as the UI remains responsive and there is some sort of progress showing, I don't necessarily see the need to add that warning. However, we should sometime investigate how to speed up encryption - there is always some space for optimization. As for this particular issue, I'll close it. Thanks for the suggestion!
