### ISSUE TITLE
Implement sending signed and encrypted S/MIME message

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#4048]
>  signed and encrypted?

This is the most important. Could also be tackled separately.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/3979#issuecomment-929327714_

**Comment by rrrooommmaaa** [comment]
Oh it turns out we don't have to nest PKCS#7 data, we should nest S/MIME messages instead.
That is, build a complete S/MIME signed message and then use it as input to build an encrypted S/MIME message.
I have tested it and Thunderbird recognizes signed and encrypted messages built this way.

**Comment by tomholub** [comment]
excellent
