### ISSUE TITLE
[Feature suggestion] default action on the secure reply/forward, like sign only, sign+encrypt, encrypt-only

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4049]
Hi team,

Good Day! We have a feature request coming from a user. A FlowCrypt user suggests a feature to have an option to make default action for the sign only, sign+encrypt, encrypt-only in every secure compose/reply/forward. Although we have an option to choose from sign only, sign+encrypt, encrypt-only,  it can't be set by default (globally).

Reference:
https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkFwJrVLdpTSRWsRFMpJFrqrP

Let me know your thoughts about it.

Best Regards,
Mart Gil

**Comment by limonte** [comment]
Agree, this could an option in settings. It doesn't really fit into any of existed categories, so maybe we can add a new category which would be named "General" and place there these settings:

- When composing
  - [x] Encrypt message
  - [x] Sign message
- When replying
  - [x] Encrypt message
  - [x] Sign message
- When forwarding
  - [x] Encrypt message
  - [x] Sign message

**Comment by tomholub** [comment]
As for the original issue - setting a default - it would be nice but it would end up used by less than 1% of users. Marking for much later.

**Comment by Braveheart53** [comment]
@tomholub not to be obtuse, but when stating "less than 1%", where are getting data to support this figure? It sounds like it was completely made up. I would suggest creating a feedback form on install asking questions like this to get the real data.

**Comment by tomholub** [comment]
hello, it is indeed completely made up. with limited resources, which is what we have, we have to rely on intuition and experience communicating with our users to understand what they want. of course we may be wrong at times.
