### ISSUE TITLE
Test and fix automatic backup and recovery when the first key is `x509`

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#4053]

**Comment by tomholub** [comment]
How did it happen, the x509 was imported, and then user went to backup?

(currently the only customer who wants x509 has the NO_PRV_BACKUP client configuration so backup is disabled for them anyway)

**Comment by rrrooommmaaa** [comment]
> How did it happen, the x509 was imported, and then user went to backup?

Sorry, perhaps I saw an attempt to submit a `x509` key to attester instead....

**Comment by tomholub** [comment]
That's possible - that would error for sure.
