### ISSUE TITLE
Compose message box UI bug when cancelling passphrase prompt

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4072]
Description:
A user encounters a minor UI issue when canceling the passphrase prompt triggered when sending a compose message.

Steps to reproduce:
1. Compose a message with a recipient, subject, message.
2. Click on encrypt, sign and, send button.
3. Passphrase prompt will pop-up (no passphrase session yet).
4. Close the passphrase prompt
5. The compose box will stuck at loading phase.

<img width="539" alt="Screen Shot 2021-10-27 at 4 42 37 PM" src="https://user-images.githubusercontent.com/46025304/139031644-e0921b5a-7778-4e61-80e0-04d25c1ab526.png">

Reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkZChlnWzzmqHDCVRfXbSdsGV

**Comment by tomholub** [comment]
This bug is quite annoying - just ran into it. Thank you for reporting it earlier - this will need a ui test.

**Comment by limonte** [comment]
This issue is happening in Firefox only, the underlying reason is described in #4140

**Comment by rrrooommmaaa** [comment]
It's important to specify -- are we invoking composer from gmail page? The it may be really content script messaging issue

**Comment by limonte** [comment]
> It's important to specify -- are we invoking composer from gmail page? The it may be really content script messaging issue

Yes
