### ISSUE TITLE
confusing text tooltip when including public key to the message

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4073]
Description:
A FlowCrypt user shared with us that the tooltip text description is confusing them. 

The tooltip will remain the same description after the public key is already included/attached:
```
Your Public Key will be included with this message. This allows people using non-FlowCrypt encryption to reply to you.
```

<img width="535" alt="Screen Shot 2021-10-27 at 4 53 17 PM" src="https://user-images.githubusercontent.com/46025304/139033586-4b7ac44b-b2de-453c-a29a-d9c4dd53ef84.png">

Though, the change in color and emboss effect is already noticeable.

Reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkZChlnWzzmqHDCVRfXbSdsGV

**Comment by rrrooommmaaa** [comment]
We should also consider wording "Your Certificate" instead of "Your Public Key" when we're sending S/MIME message.

**Comment by tomholub** [comment]
That would be sometime far in the future - don't need that level of S/MIME support yet.

**Comment by limonte** [comment]
Sorry for the delayed reply on this issue! WDYT about adding `If enabled,` to the beginning so it'll be:

```
If enabled, your Public Key will be included with this message. 
This allows people using non-FlowCrypt encryption to reply to you.
```

**Comment by tomholub** [comment]
That works for me.
