### ISSUE TITLE
Create a new key issue. Checking if a pass phrase is strong doesn't work automatically after "paste" action.

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-browser#4076]
Checking if a pass phrase is strong doesn't work automatically after "paste" action. Please look at the attached video

https://user-images.githubusercontent.com/2863246/139660079-9738b6c7-7dfd-4b9e-8109-2f290992f4e1.mp4

**Comment by tomholub** [comment]
Looks like it just needs to handle one more type of events? @limonte could this be a 5-minute fix?

**Comment by limonte** [comment]
> Looks like it just needs to handle one more type of events? @limonte could this be a 5-minute fix?

It took me a bit longer because I looked for similar issues across the codebase, there were a couple of them: #4100

**Comment by tomholub** [comment]
Very good - systematic fixes are always better. Thanks!
