### ISSUE TITLE
The "reply" button should only reply to the sender, it currently works the same way as "reply all" button

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4077]
Request by enterprise customer

<img width="386" alt="image" src="https://user-images.githubusercontent.com/6306961/139930629-1ee9e464-c3df-46aa-8108-2f7fdff0b085.png">

Currently we have reply icon with reply-all functionality which is confusing.

---

Upd: The secure reply icon button triggers the right button, it's the "Reply" button that is broken and works like "Reply all" button.

**Comment by limonte** [comment]
The secure reply icon button triggers the right button, it's the "Reply" that is broken and works like "Reply all".

**Comment by limonte** [comment]
Actually, the icon button is broken as well. We already clicking it in live tests, so I'll figure out how to cover this with the live test as well without creating a new test case.
