### ISSUE TITLE
Sketchy way for importing a private key when backup key is present 

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4079]
Description:
Importing a private key is sketchy for users who have a previous backup key in their email.

The possible way for them to import their private key is by skipping the recovery which might not be the best approach.

Problem:
Most user may confuse them as the flow suggest it is only meant for generating a new key and not for importing an existing key.

Current behavior:
Given scenario -- a user has a private key but also has a backup key in their email.

1. Log in to Flowcrypt extension via google > backup recovery page appear > lost passphrase > skip recovery and create a new key > the new encryption & import a private key file page appear > import private key.

Expected behavior:
1. Log in to Flowcrypt extension via google > there should be a separate button that will redirect them to the private key import page instead of following the flow for generating a new key right before they can have the option to import private key file.

Reference: https://mail.google.com/mail/u/2/#archive/FMfcgzGlkjZJXGkkzjdfkBZGmNwxMdvf

**Comment by tomholub** [comment]
Thank you for reporting this.

I'll close this as a rare situation. If someone has a key to manually import, then they know what they are doing and will find what they're looking for.

But 99% of users don't know what they are doing, and guiding them to make a new key is the correct thing.

**Comment by martgil** [comment]
You're welcome, sir! Thank you for sharing your insight here. I'll take note of that.

**Comment by tomholub** [comment]
However, please still report similar issues as you come across them. For some of them, we may decide to take action anyway, or we may think of something else to do.

**Comment by martgil** [comment]
Yes, sir! I understand completely. I'll file an issue as soon as possible.
