### ISSUE TITLE
"can lookup public key from WKD directly" test is failing because of expired key

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#4085]
The `master` branch is currently green, but the PR I'm working on now is failing:

```
  can lookup public key from WKD directly
    ℹ (attempt 1 of 3) Retrying: Error: waiting failed: Elements did not appear: .email_address.has_pgp
    ℹ (attempt 2 of 3) Retrying: Error: waiting failed: Elements did not appear: .email_address.has_pgp
    ℹ (attempt 3 of 3) Failed:   Error: waiting failed: Elements did not appear: .email_address.has_pgp
```

I took a quick look and here's the reason:

<img width="479" alt="CleanShot 2021-11-03 at 18 53 05@2x" src="https://user-images.githubusercontent.com/6059356/140110002-9f79b8a5-b761-4440-b0f2-9126fcc6ddc7.png">

**Comment by tomholub** [comment]
Can use `demo@flowcrypt.com` instead for this test
