### ISSUE TITLE
Unreadable encrypted message with attachment sent using Microsoft outlook

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4086]
Description:
Encrypted messages with an attachment that is sent using Microsoft Outlook failed to be recognized by the FlowCrypt extension.

The message from Microsoft outlook was separated and turned into two files named `ATT00001` and `ATT00002` without any file extension. But the `ATT00002` has the PGP message. I also tried to tweak some settings to my outlook, installing the latest version of the GpgOL (gpg4win) outlook plugin, but still getting the decrypted message without any problem.

The FlowCrypt extension, however,  has no problem when decrypting a message without an attachment (in my testing case) where these messages were named `openpgp-encrypted-message.asc` instead of the more random one. 

I have searched for the same problem on google, and, some other says this was an issue from the Microsoft outlook where the email with the attachment was turned into `ATT00001` (https://www.google.com/search?q=att00001)

I have replicated it once but never happened it again as it was really tricky.

I was able to decrypt it with my key and have the decrypted mime message. I'm not knowledgeable yet on how to proceed but the mime message looks like it can be rendered and be fully decrypted.

I highly suspect that it could be because the attachment doesn't have a `.asc` extension so the FlowCrypt browser ignored to render it?

Thank you for taking a look. Any ideas are welcomed!

Files:
decrypted mime message => [decrypted.txt](https://github.com/FlowCrypt/flowcrypt-browser/files/7473511/decrypted.txt)
original attachment => [ATT00002 (2).txt](https://github.com/FlowCrypt/flowcrypt-browser/files/7473517/ATT00002.2.txt)

Reference:
https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkXsdKtBnmmkzrqnJcSrPFFTl

**Comment by tomholub** [comment]
Please have the user send us a sample email with subject `Microsoft outlook OpenPGP email not recognized` to our compatibility email. Instructions here https://flowcrypt.com/docs/help/compatibility.html

**Comment by martgil** [comment]
Thanks for your response. I have requested the user to send us a sample email. Thank you!

**Comment by martgil** [comment]
We have successfully received a sample email from the user with the subject `Microsoft outlook OpenPGP email not recognized` in the flowcrypt compatibility account.

**Comment by tomholub** [comment]
Thank you - this is helpful. As a workaround, until we add compatibility, then can view it here in flowcrypt icon -> encrypted inbox:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/6306961/146398284-325b6d06-ef2b-44a4-9b69-428c64c7d30d.png">

**Comment by tomholub** [comment]
Calling Google API for every message user opens would fix all of similar problems, but seems too excessive.

The easier fix here is to only add the file name pattern to `Attachment.treatAs` which should evaluate them.

**Comment by martgil** [comment]
@tomholub, sir. The ATT00001 file is created by Microsoft outlook is an encrypted PGP message which I just copy resend as a raw email body that is why it worked there in my test email. I guess opening it through the FlowCrypt extension directly will not work?

Actually this is what the problematic email looks like: 
<img width="1173" alt="Screen Shot 2021-12-17 at 12 52 12 PM" src="https://user-images.githubusercontent.com/46025304/146490975-356c261f-e7a6-4e6f-9f32-1e8e4342da2c.png">

Perhaps he can do the same steps that I did just to read the email? - The email will turn into that weird-looking attachment only if the outgoing message has an attachment.
