### ISSUE TITLE
ability to remove any private key when > 1 used

### ISSUE THREAD

**Issue by combs** [FlowCrypt/flowcrypt-browser#409]
I walked through the wizard, let it create a key, now can't remove it to add my real key—the `(primary)` shows up instead of `(remove)`

---------------

// edited by tom: see details for implementing this in https://github.com/FlowCrypt/flowcrypt-browser/issues/409#issuecomment-662899507

**Comment by tomholub** [comment]
Similar to #268. Replacing of primary keys (done properly) is a bit of a tedious task, so I have not implemented it yet.

Right now, you would need to remove CryptUP and re-add the extension, then set up the account again.

Thanks for getting involved & reporting this.

**Comment by tomholub** [comment]
For users who found this issue looking for a solution, here is the current steps to replace primary key:

1) Please test your current, temporary passphrase in FlowCrypt Settings -> Security -> test my pass phrase.

2) Go to FlowCrypt Settings -> Additional Settings -> Experimental -> reset account.

3) After that, during setup, it will ask for your pass phrase. You can give it a wrong one, then you will see a link to skip the step. Follow the link. 

4) In the following steps, set up FlowCrypt again with intended key.

5) Finally, in FlowCrypt Settings -> Additional Settings -> Attester, use your temporarily created (current) key + pass phrase that you tested above to fix public records.

**Comment by franciscojasousa** [comment]
Dear Tom,
does the below means that I will be unable to solve public key check for my email for good?
Key does not match. Looking for key with KeyWords SEEK PUBLIC CANOE CUBE TYPICAL FIRST SLOGAN JOKE VAPOR STABLE CROP VENUE HUB FIRE ALREADY (C315A0861ABEBEAEF2FBC2F17A78CFF936E8AE79)
Kind regards

**Comment by tomholub** [comment]
@franciscojasousa that looks like a bug, we'll be looking into it

**Comment by tomholub** [comment]
@franciscojasousa we will be addressing this in #1328

**Comment by franciscojasousa** [comment]
Thank you Tom!
Great extension.
Rest of a good week

**Comment by ewa** [comment]
I just want to bump this.  It's important and very non-intuitive what to do (except when you've found this page).

**Comment by tomholub** [comment]
I agree

**Comment by georgjaehnig** [comment]
Hi, I need to update my primary key because my current one is expiring. Added my new key but cannot make it primary

Saw the workaround [https://github.com/FlowCrypt/flowcrypt-browser/issues/409#issuecomment-431900787 here] but cannot find the "reset account" option anymore.

What can I do to update my primary key?

**Comment by tomholub** [comment]
Is it the same key with extended validity, or a brand new generated key?

## Same key

FlowCrypt Settings -> Additional Settings -> My Keys -> click on your key -> scroll down -> update

![image](https://user-images.githubusercontent.com/6306961/77827483-abdb2200-710d-11ea-9698-155a83a059bd.png)

## Different / newly generated key

FlowCrypt Settings -> Additional Settings -> Experimental -> reset account

**Comment by georgjaehnig** [comment]
Thanks for the quick response!

It is a different key.

I do not see the "reset account" option at "Experimental". I'm on version 7.7.4.

**Comment by tomholub** [comment]
You should see a scrollbar - if you scroll all the way down, you'll find it:

![image](https://user-images.githubusercontent.com/6306961/77827665-e6918a00-710e-11ea-875a-fc182536092e.png)

**Comment by georgjaehnig** [comment]
Oh. There was no scrollbar. Now I've found it.

Proceeded with resetting. Now I keep getting:

> Failed to connect to Gmail(new). If this happens repeatedly, please write us at human@flowcrypt.com to fix it.
> 
> [Error] Grant successful but error accessing fc account: Error: error: -1 when POST-ing https://flowcrypt.com/api/account/login string: account,uuid,token -> undefined

**Comment by tomholub** [comment]
That sounds like something I have to look into, sorry for the trouble.

**Comment by tomholub** [comment]
Actually, this looks like a firewall issue, potentially. Are you behind a firewall?

**Comment by georgjaehnig** [comment]
Just behind a VPN. Switched it off. Same problem.

**Comment by tomholub** [comment]
Which browser is this, Firefox? If yes, are you using Firefox containers, or private browsing mode?

**Comment by georgjaehnig** [comment]
Reinstalled the Flowcrypt extension, now it worked.

Chrome on Mac, Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by tomholub** [comment]
Sorry, not sure what happened there. Good to know it's working now.

**Comment by georgjaehnig** [comment]
Yup, thanks for your help.

**Comment by tomholub** [comment]
This should now be relatively easy to implement:

1) update primary key in storage
2) offer to submit new pubkey to Attester (unless OrgRules forbid it)

No need to worry about backup because the kind of user to care about switching which key is primary is the kind of user who does their own backups manually.

**Comment by tomholub** [comment]
I've updated the comment above with a different approach.

**Comment by tomholub** [comment]
If you need test secrets to run tests locally (in case you still don't have them), I'll be sharing them.
