### ISSUE TITLE
[Feature suggestion] upload to pub attester without importing prv to extension

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4094]
Description:
A user having a Yubikey has wishes to be added in the attester and then use a private key without importing it. 

On such occasions, is it reasonable or likely for us to include this feature in the future? 

Thank you!

Reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGlkjdkLCWFpCVHsmrQdMXlRnWP

**Comment by tomholub** [comment]
They can manually upload their public key to attester here: https://flowcrypt.com/attester/update-public-keys

No need to use the extension.

**Comment by martgil** [comment]
Thank you for your response.

That makes sense! I have sent the user a follow-up email. Thank you!
