### ISSUE TITLE
secure compose button logo not appearing for some users

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4098]

**Comment by limonte** [comment]
Any additional details or screenshots would be useful in order to fix this issue.

**Comment by tomholub** [comment]
Will do

**Comment by limonte** [comment]
Gotcha! The customer have https://chrome.google.com/webstore/detail/virtru-email-protection/nemmanchfojaehgkbgcfmdiidbopakpp/related?hl=en installed, which conflicts with FlowCrypt. Investigating further if we can make FlowCrypt to play well along with Virtru Email Protection.

**Comment by tomholub** [comment]
Got it, let me followup since I have something to add.

**Comment by tomholub** [comment]
Actually, if you can reproduce this locally to confirm the conflict with Virtru causes this, please tell them that. They may have some input as well.
