### ISSUE TITLE
"Copy from Contact" option in `add_pubkey.htm` shows list with duplicate emails

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#4112]
This is how it looks when invoked in `'compose - settings - manually copied pubkey'` test

![image](https://user-images.githubusercontent.com/23335944/141286911-0e8821e0-9465-4d3e-b1d0-1f9d084fdfb8.png)

Should there be fingerprints?

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/issues/4110#issuecomment-966205474_

**Comment by tomholub** [comment]
Hm. There should still be emails ("recipients"), but they should be de-duplicated. Then all public keys of that recipient should be copied over for the other recipient.

**Comment by IvanPizhenko** [comment]
@rrrooommmaaa How do I get to this page? I can't find where is mentioned in description `compose - settings - manually copied pubkey`.

**Comment by rrrooommmaaa** [comment]
This frame is opened with "Add their Public Key" anchor
![image](https://user-images.githubusercontent.com/23335944/153751097-7f0c7c55-75f5-4367-9938-7707ac019db1.png)
after you entered a "gray" recipient
![image](https://user-images.githubusercontent.com/23335944/153751189-892188c5-0a03-452c-bc13-e4fd3ffb7723.png)
