### ISSUE TITLE
Additional tests for pass phrase dialog for drafts

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#4120]
I tested this manually but would also like to create unit tests for these scenarios (in another issue)
[  ] - pressing 'close' button when trying to decrypt a draft
[  ] - pressing 'Later' when entering a pass phrase for draft decryption (as opposed to `'compose - loading drafts - PKCS#7 encrypted draft with forgotten non-primary pass phrase` test) and the re-invoking the pass phrase dialog with pressing 'Pass phrase' button again

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/pull/4109#issuecomment-970053531_

**Comment by tomholub** [comment]
ok with it as is
