### ISSUE TITLE
BrowserMsg listeners aren't working in Firefox

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#4140]
### Steps to reproduce

1. In `compose.ts` add this line:

```diff
public setHandlers = () => {
  BrowserMsg.addListener('focus_previous_active_window', async ({ frameId }: Bm.ComposeWindow) => {
+   console.log('focus_previous_active_window');
    if (this.frameId === frameId) {
      this.S.cached('input_to').focus();
    }
  });
```

2. Open 2 new secure compose windows
3. Close the second one

### Expected behavior

`focus_previous_active_window` in console, the first secure compose window is active

### Actual behavior

Nothing in console, the first secure compose window is inactive

<img width="683" alt="CleanShot 2021-11-21 at 18 42 01@2x" src="https://user-images.githubusercontent.com/6059356/142770952-ad510160-acce-4214-a001-583aa6fb75c5.png">

**Comment by limonte** [comment]
@tomholub I'm not sure what's the reason (changes in our codebase or changes in Firefox) and when it started, but ATM listeners aren't working in Firefox and Firefox users might experience many issues, e.g. #4072 is happening because of this. 

I spent quite a while trying to understand what's wrong with `BrowserMsg`, but unfortunately without any results for now. Maybe @rrrooommmaaa would be able to help here.

Possibly related to #3789

**Comment by tomholub** [comment]
don't seem to be experiencing any Firefox-specific issues anymore, closing
