### ISSUE TITLE
attachments inner info should include proper file name

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#415]
> Hi Tom,
> I can decrypt your mail successfully, but  the attachments contain the wrong name “msg.txt” in them.
> Therefor gpg4o shows both attachments as “msg.txt”
> In nearly all other PGP implementations we have encountered in the last three years, the inside-filename is the right one. The attachment's filename (e.g. image.jpg.pgp) is in many implementations wrong or meaningless (e.g. Attachment1.pgp)
> Therefor gpg4o prefers the name inside the packet. If would change this behavior, we would solve your problem but would annoy all other customers.
> So you should replace “msg.txt” by the filename’s real name.
> Best regards
> Tobias

![image](https://cloud.githubusercontent.com/assets/6306961/22372242/676149ee-e450-11e6-8e21-8f599e0a4296.png)

**Comment by tomholub** [comment]
We can buy a gpg4o license for testing, or maybe I can talk to them to give us a free licence to test with

**Comment by tomholub** [comment]
This issue is about including the filename property inside the pgp encrypted part, for files. See OpenPGP API for encrypting files. I will get a gpg4o license for testing, send an attachment from FlowCrypt to gpg4o and see if the name is displayed correctly. If yes, you can close this issue.

**Comment by tomholub** [comment]
I will send you GPG4o license to email

**Comment by tomholub** [comment]
license is here https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/WhctKJVRDxWCmPQxbDTkVdFfLZvCnJmkpNvcPbKZWTDZBsczMNTszPHlVdhpFmLxGFCShFQ

Most likely we are forgetting to add the `filename` param when creating encrypted attachments 
https://github.com/FlowCrypt/types/blob/master/openpgp.d.ts#L974

**Comment by tomholub** [comment]
@michael-volynets have you taken a look at this? You should be able to install a test version of GPG4o without a license, but if you need a license, then you'll find it in the email link above.

The issue is with attachment names sent by FlowCrypt and opened in GPG4o.

**Comment by tomholub** [comment]
@michael-volynets sorry, I just noticed your chat from earlier today. 

Can you please tackle this issue while I review the others?

After this one, you can look at #1763 since the other issues are now waiting for my input. Thanks!

**Comment by michael-volynets** [comment]
yes, I'm looking into this one,

Thanks!

**Comment by michael-volynets** [comment]
Looks like this works correctly, I have tested it and the here is the results:
When I sent a message from Flowcrypt Gmail Account to my Outlook account with GPG4o, with an attachment in the message, GPG4o decodes filename correctly:
![image](https://user-images.githubusercontent.com/49104848/62296303-79dac880-b477-11e9-858e-034f05267bba.png)
Here is how the message looks in Gmail:
![image](https://user-images.githubusercontent.com/49104848/62296359-9414a680-b477-11e9-860a-a7322caa47a5.png)

Did I test it correctly or the issue is obsolete?

**Comment by tomholub** [comment]
You have tested it properly. This means it was since fixed. Thank you for testing it!
