### ISSUE TITLE
encrypted forward or reply functionality on plain email?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4160]
There used to be a way to reply to a plain email with encryption. Or maybe even forward it encrypted.

Did we remove that intentionally, or did it get broken by some Gmail DOM change?

**Comment by tomholub** [comment]
Now I see it again. Maybe it's flaky.

<img width="620" alt="image" src="https://user-images.githubusercontent.com/6306961/144429804-e18737bc-367f-42fe-8d0e-98707eb51535.png">

**Comment by limonte** [comment]
Encrypted reply to plain message is there and works for me per screenshot above as expected always. I would need steps to reproduce the situation when the secure reply button is missing for plain message.

Encrypted forward to plain message was never implemented AFAIK.

**Comment by tomholub** [comment]
All good, I'll reopen once I see it again.
