### ISSUE TITLE
Re-fetching signed-only message from API doesn't refresh the fetched text

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#4164]
To be implemented after PR #4144 and possibly refactor the decrypt-render-signature-... module interaction

**Comment by rrrooommmaaa** [comment]
These modules are calling each other in a complicated manner. Perhaps, a bit of refactoring is in order.

**Comment by tomholub** [comment]
reference https://github.com/FlowCrypt/flowcrypt-browser/pull/4144#issuecomment-994972798
