### ISSUE TITLE
Fix UI for manually importing public keys

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-browser#4168]
![image](https://user-images.githubusercontent.com/2863246/144846991-d393ec41-319b-4cbe-a44a-b9d4d40bd6ea.png)

The expanded version looks a little weird

![image](https://user-images.githubusercontent.com/2863246/144847168-f171efa0-d19f-44b3-9939-0fa2b0d38ac2.png)

**version 8.2.0 on November 16, 2021**

**Comment by limonte** [comment]
Caused by #4110

In this case, the orange warning shouldn't be shown.
