### ISSUE TITLE
"missing keys to verify this message" status should be red color

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4198]
> * "missing keys to verify this message" status should be red color.

This needs to be filed separately as currently I think it's gray.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/3884#issuecomment-995873321_

**Comment by rrrooommmaaa** [comment]
![image](https://user-images.githubusercontent.com/23335944/146509990-ddb72713-c0df-458f-afcc-00ff2011eb68.png)
@tomholub do you mean to have this border red?

**Comment by tomholub** [comment]
Sorry - I think this doesn't need any action at the moment. Thanks for the screenshot.

Instead we'll be updating the rendering of signatures, as here https://github.com/FlowCrypt/flowcrypt-browser/issues/4201 and then re-evaluate the borders after that.
