### ISSUE TITLE
update signature+encryption rendering to use badges

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4201]
Instead of how we currently render signatures, I'd like to do something more similar to this (FlowCrypt iOS app)

![image](https://user-images.githubusercontent.com/6306961/146417516-1851e670-b02d-44e4-95d5-beeea08ea21f.png)

Badge styles can be reused from backup screen (there is also a red color background style)

![image](https://user-images.githubusercontent.com/6306961/146417832-1cc61118-65fd-4cd0-8d1b-13411f505c34.png)

There will be one encryption and one signing badge, and the states are:

signing:
 - `signed` (green, only when matching and successful)
 - `not signed` (red)
 - `could not verify signature: unknown public key` (red)
 - `error verifying signature: ...` (red)
 - `verifying signature...` (gray)

encryption:
 - `encrypted` (green, if decrypted succesfully)
 - `decrypt error: key mismatch` (red) for `key_mismatch`
 - `decrypt error: security hazard` (red) - for `bad_mdc` and `no_mdc`
 - `decrypt error: ...` (red) - other decrypt errors similarly
 - `not encrypted` (red)

After this, we'll have to examine the screenshots of what all of these situations look like, and consider what does that mean for the color of the border of the whole message. That would be in another issue.

**Comment by tomholub** [comment]
That means we no longer print the name of the signer, as it's naturally the sender, if verified correctly.

**Comment by tomholub** [comment]
That means we can throw away the custom cursive font which is included in the source as a ttf or similar.

**Comment by rrrooommmaaa** [comment]
> signing:
- signed (green, only when matching and successful)
- not signed (red)
- could not verify signature: unknown public key (red)
- error verifying signature: ... (red)
- verifying signature... (gray)

Please confirm whether I need to reword these 3 cases to conform to the mentioned patterns
- [] Could not load sender's pubkey due to an error.
- [] Could not look up sender's pubkey due to network error, click to retry.
- [] signature does not match

**Comment by tomholub** [comment]
`signature does not match` should be called `bad signature`

`Could not load sender's pubkey due to an error.` let's do simply `error verifying signature: ${error}`

`Could not look up sender's pubkey due to network error, click to retry.` let's do `error verifying signature: offline, click to retry`

**Comment by rrrooommmaaa** [comment]
@tomholub do we still retain this intermediate screen for MDC errors
![image](https://user-images.githubusercontent.com/23335944/146644396-fb6f1528-1495-4d6e-8d6b-a672044bf3b2.png)
prior to showing this?
![image](https://user-images.githubusercontent.com/23335944/146644485-4e00c689-59de-4448-a9d3-f4f40349f847.png)
Should I remove the header "Security threat!..." when displaying the badges?

**Comment by tomholub** [comment]
I'd keep the "security threat" beginning. Never enough of those, in a situation like this that should not normally happen.
