### ISSUE TITLE
Rendered encrypted messages don't fit vertically and have vertical scrollbar

### ISSUE THREAD

**Issue by limonte** [FlowCrypt/flowcrypt-browser#4219]
Probably caused by new badges?

![CleanShot 2021-12-28 at 10 58 41](https://user-images.githubusercontent.com/6059356/147548533-567227e7-e42b-4e6c-9bfe-3d790c25879d.gif)

(Latest Chrome on macOS)

**Comment by rrrooommmaaa** [comment]
duplicate of #4243
