### ISSUE TITLE
don't save alias to contacts during setup if chosen not to sumit it to attester

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4236]
Description:
The browser extension throws an error when trying to save an IDN email into the contacts. This prevents the user from creating and importing their private key even when they choose not to use the email alias at all (unchecked).

They could have ended up removing the email alias from their Gmail account but I think it was not a good/practical option for them.

Consider the following js snippet:
```javascript
function isEmailValid(email) {
    if (email.indexOf(' ') !== -1) {
      return false;
    }
    email = email.replace(/\:8001$/, '');
    return /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/i.test(email);
  }
var email = "demo@åwesomedomain.com"
var email2 = "åwesome@awesomedomain.com"
console.log(isEmailValid(email)) // false
console.log(isEmailValid(email2)) // true
  ```
Screenshot:
![1](https://user-images.githubusercontent.com/46025304/148154497-5ba4902b-3e7e-44bc-be31-241e487b04b2.png)

Reference: https://mail.google.com/mail/u/1/#inbox/FMfcgzGmtFJRDCbGVwrvFQXDZXlQczDv

Thanks,
Mart Gil

**Comment by martgil** [comment]
I have explored how IDN email is processed with the attester, it turns out that an IDN email is also being validated in `POST /attester/pub/` endpoint.

The endpoint `POST /attester/initial/legacy_submit`, on the other hand, accepts an IDN email without any problem. However, the email is not searchable through the compose message box even though the email is already in the Attester.

In my option, we have another option to save only the emails that are "checked" in the contacts instead of saving all the aliases in the contacts. That way, they wouldn't need to remove their cherry-picked email aliases away from their Google Account when they decided to use the FlowCrypt extension without having the ability to read encrypted messages on a specific email alias.

Thanks,
Mart Gil

**Comment by tomholub** [comment]
If they choose not to submit the aliased email, we should not be saving it into contacts, either.

**Comment by tomholub** [comment]
Also that email should not be in the created pgp key uids (I think already isn't, please double check).

**Comment by tomholub** [comment]
> The endpoint POST /attester/initial/legacy_submit, on the other hand, accepts an IDN email without any problem. However, the email is not searchable through the compose message box even though the email is already in the Attester.

I think we are not using this endpoint anymore, as of recently.
