### ISSUE TITLE
[User suggestion] Possibility of supporting "+" Gmail notation

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4237]
Description from the original email:
> I was sending an email to a gmail account that was using plus notation and flowcrypt didn't pick up that the encryption keys would be the same for that email address.  Is it possible to add this functionality.
> \+ Notation sends emails appended with a plus before the domain name to the same inbox.
eg emails send to all email below will go to the same account:
test@gmail.com
test+123@gmail.com
test+thisisatest@gmail.com
test+usefulfilter@gmail.com
test+yougetthepoint@gmail.com

Reference: https://mail.google.com/mail/u/1/#inbox/FMfcgzGmtNWwPjtndSlPDHjdtvDrPVbW

Thanks,
Mart Gil

**Comment by martgil** [comment]
sir @tomholub  Is it possible for us to add this improvement in the future? Thanks!

**Comment by tomholub** [comment]
No plans at the moment to add support for `+` to be treated as the same email account at the moment. It is not a very frequently used feature, and it's not clear if treating it as the same email account would be more correct than the current behavior (although I understand it would allow some usecases that are currently not supported).
