### ISSUE TITLE
Compose message box UI bug: updating recipients

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-browser#4241]
It may relates to the "password-protected message" feature. Please look at the attached video. Updating recipients sometimes can have unexpected results (some recipients can have PGP but shoudn't, and vice versa). To reproduce just need to play around different recipients. Also the updating process looks frozen(Infinite progress)

https://user-images.githubusercontent.com/2863246/148768108-a84a37e2-d80c-4b6b-b1b0-ac53de1680d7.mp4

**Comment by tomholub** [comment]
@DenBond7 the video doesn't play for me on a mac, unsure if it does play on other devices?

**Comment by DenBond7** [comment]
@tomholub Have you tried to download it?

**Comment by DenBond7** [comment]
I've sent the video via email. Please try to open it.

**Comment by tomholub** [comment]
I was able to view the issue on mac using VLC media player. Thank you for the video. Forwarding to @sosnovsky

**Comment by ioanmo226** [comment]
I think this issue is already fixed?

**Comment by tomholub** [comment]
@DenBond7  please later try again

**Comment by DenBond7** [comment]
@tomholub I have version 8.4.0 on November 18, 2022. It still has this issue. I can reproduce it.

**Comment by ioanmo226** [comment]
@DenBond7 could you share new video with new version?

**Comment by DenBond7** [comment]
> could you share new video with new version?

yup. Here is

https://user-images.githubusercontent.com/2863246/209138209-3493a6d5-005d-4e73-a583-f64b7e78875c.mp4
