### ISSUE TITLE
sometimes "encrypted" badges are colored red.

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#4253]
To reproduce: pass phrase should not be entered.
Thus, "decrypt error" red badge is displayed.
After entering pass phrase and successful decryption, the badge has now (at least) two classes: "red_label green_label". Red one overrides the green one.
![image](https://user-images.githubusercontent.com/23335944/149624993-68d846eb-ecac-4dea-81a2-ef458276aa52.png)
Perhaps, we need a separate placeholder for intermediate errors? ("decrypt error" and "parse error") or make sure the whole iframe is reloaded?

**Comment by rrrooommmaaa** [comment]
@tomholub Should we fix it in the 8.2.2 release?

**Comment by tomholub** [comment]
ah! If you can fix it today, I'll hold off releasing our enterprise customer & will send them a release this evening with the fix.

If not, I'd release what we have (I made a commitment to make a release today) and then we'll give them a fixed version soon after.

**Comment by rrrooommmaaa** [comment]
Yes, I would go with a separate div for `decrypt error/parse error` approach, what do you think?

**Comment by tomholub** [comment]
I'm unsure - will let you choose the approach, as long as it fixes the ux issue. Thanks!
