### ISSUE TITLE
send MessageID to FES for easier threading of conversations on Gmail

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4269]
Roman - on FES we allowed two methods to supply message ID (the mime email header).

Option 1: pre-generate message id before constructing mime / uploading the message to Gmail, and include that in FES /upload call

Option 2: let Gmail generate message id (as it does now) and then retrieve it & send that to FES in another API request

Option 1 is preferred if it can be made to work (if Gmail respects message id constructed by us when we're sending the message) as it requires fewer API calls.

Pre-generate option:
- create a valid Message-ID - these should include the angled brackets.
- Send it along in the MessageUploadRequest class:
```kotlin
data class MessageUploadRequest(
   val associateReplyToken: String,
   val expiration: Instant?,
   val from: String,
   val to: List<String>,
   val cc: List<String> = emptyList(),
   val bcc: List<String> = emptyList(),
   val emailGatewayMessageId: String? = null
)
```

Separate API request option:
- after sending the email retrieve the Message-ID.
- Send it to the new POST
/api/$VERSION_CLIENT/message/{externalId}/gateway endpoint.
Authorization is required and the class is:
```kotlin
data class MessageGatewayUpdateRequest(
   val emailGatewayMessageId: String,
)
```

**Comment by tomholub** [comment]
related https://github.com/FlowCrypt/flowcrypt-enterprise-on-prem/pull/2365

and https://www.jwz.org/doc/mid.html

Please test the option 1, and see if Gmail accepts it & it stays the same. If yes, we can use that option.

**Comment by rrrooommmaaa** [comment]
Unfortunately Gmail overwrites `Message-ID` and don't even keep the original value in `X-Google-Original-Message-ID` as it used to do, so we need to proceed to Option 2.
I am a bit baffled by this `externalId` in /api/$VERSION_CLIENT/message/{externalId}/gateway endpoint.
Looks like neither NewReplyToken nor messageUpload return it.

**Comment by tomholub** [comment]
Indeed, it's not returned separately. Please implement it as if `externalId` was returned from `messageUpload` in `MessageUploadResponse` alongside `url`. Then I'll have that change done on FES.
