### ISSUE TITLE
message password security

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#428]
```diff
- check that the password is not included in the hint..
+ check that the password is not included in the intro and subject
add a strength bar, but don't enforce
```

**Comment by tomholub** [comment]
- [ ] also check that this password is different than all known users passphrases!
- [ ] strength bar to have minimum requirement about 1/10th of pass phrase min entropy

**Comment by schmorrison** [comment]
@tomholub  I am curious if there is a security concern in checking that the password is different than all known passwords. Feels like that is something we should not check, if there is a password collision then our users probably aren't using challenging passwords.

**Comment by tomholub** [comment]
The passwords are not auto generated, they are user generated.

Same password means that the user thinks they should be entering their pass phrase, when actually they should be entering a completely different password that they can share with others (pass phrases are not meant to be shared).

**Comment by schmorrison** [comment]
Ok, I misunderstood. I really need to remember the difference between `password` and `passphrase`

**Comment by tomholub** [comment]
The way we are using the words, pass phrase protects a key, while a password may be used to encrypt a message.

**Comment by schmorrison** [comment]
Understood.

Then when you wrote ```also check that this password is different than all known users passphrases!``` you mean check that the password entered is not the same as the passphrase for any of the current users keys.

**Comment by tomholub** [comment]
Correct. I guess the most reliable way to check that would be to try to decrypt each key with the password (after some delay so that we don't keep computing it as the user is typing).

The good news is that we only have to check it against the keys if it surpasses whatever minimum strength we require when creating pass phrases.

**Comment by michael-volynets** [comment]
+15m for test fixing
