### ISSUE TITLE
fes user can backup private key 

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4315]
@tomholub 

We recently restrict the download availability of private key for fes user. However, when the user navigates to FlowCrypt settings > additional > experimental > Back up account information into a file, the user can download the private key even though they are under of no_prv_backup rule.

On the orgrule description on https://flowcrypt.com/docs/business/org-rules.html - it says:
```
NO_PRV_BACKUP - Do not allow automatic or user-generated key backup except to an internal EKM if available. 
Manual export of password-protected private key is still allowed.
```

I need some advice what's best for it. thanks!

**Comment by tomholub** [comment]
I'll be removing this functionality shortly, thank you for the report.
