### ISSUE TITLE
frozen setup screen when EKM not reachable?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4322]
Customer report. Will have to see this in action to be able to debug it.

Normally, any network error should result in a modal on this page, after a 30 second timeout at the latest.

----------

![image](https://user-images.githubusercontent.com/6306961/157087269-a289689e-8e09-4974-a123-c0f01fd184bd.png)

**Comment by martgil** [comment]
Hello sir @tomholub, I remembered someone reported something similar to this - with the help of the user sending the network log, I'm able to spot that EKM for their org is not reachable. This results in login failure to any of the users trying to set up the extension for the first time.

**Comment by martgil** [comment]
By configuring a proxy to pointing to a non-working http server, i think we are able to replicate the problem: <img width="1267" alt="Screen Shot 2022-03-09 at 3 21 29 PM" src="https://user-images.githubusercontent.com/46025304/157392343-a30114b1-bd58-4091-a79a-08a1c7ffd132.png">

I can also quickly identify that the request to pull private keys is not wrapped in a try & catch so networks errors are happening in the background silently.
```typescript
public getPrivateKeys = async (idToken: string): Promise<LoadPrvRes> => {
    return await this.request('GET', '/keys/private', undefined, idToken) as LoadPrvRes;
  };
```

**Comment by tomholub** [comment]
fixed finally in https://github.com/FlowCrypt/flowcrypt-browser/pull/4334 and then there is a followup in https://github.com/FlowCrypt/flowcrypt-browser/issues/4335
