### ISSUE TITLE
 check if hovering above the new button will produce a "Secure Compose" title

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4323]
@martgil please check if hovering above the new button will produce a "Secure Compose" title

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4318#issuecomment-1061512415_

**Comment by martgil** [comment]
Hello, sir @tomholub - if you're referring to the `title` HTML attribute, I don't see the "Secure Compose" title when hovering to it - the same goes for the original one. 

<video src=https://user-images.githubusercontent.com/46025304/157195580-b7260b57-5fda-4f62-9550-d0d4b465fd00.mov>

**Comment by tomholub** [comment]
Gmail uses something similar to a title, but with their own styles. Please add ` data-tooltip="Secure Reply" aria-label="Secure Reply"` to the html.
