### ISSUE TITLE
secure compose now broken in original gmail view

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4328]
@martgil you need to test carefully. The update to the secure compose button has broken existing design of the button on previous version on gmail.

![image](https://user-images.githubusercontent.com/6306961/157238854-095e69cb-ce8a-4014-a304-96bc7d7483bc.png)

Please fix it back by testing both versions, and making sure your changes don't affect the old version.

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/157239038-195d28e9-61d4-47a8-a3d2-1187ff557954.png)

**Comment by martgil** [comment]
@tomholub - it seems I can't replicate it on my end. I'm now at v8.2.6 (master), i'll take a look:

<img width="248" alt="Screen Shot 2022-03-08 at 8 41 11 PM" src="https://user-images.githubusercontent.com/46025304/157240290-5d076e6b-8999-42ff-8550-8ca14214acae.png">
<img width="68" alt="Screen Shot 2022-03-08 at 9 00 57 AM" src="https://user-images.githubusercontent.com/46025304/157240298-4b1b813b-6b1b-4354-a5a3-b39cf5844c28.png">
