### ISSUE TITLE
PGP message cannot be decrypted if the key usage flags was set to 'sign-data'

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4341]
Hello @tomholub,

A concern user reach out to us about the decrypt error happening when FlowCrypt extension. The message however can be decrypt using gpg but returns an info message says "gpg: used key is not marked for encryption use.".

I've investigated this issue and found out that if the message was encrypt using a key with usage flags 'sign-data' then the app will throw 'session decrypt error' causing the message remains unreadable.

I've informed the respondent to send us encrypted messages (human and compatibility emails):

the message decrypts successfully on 'compatibility' account but fails on 'human' account (with sign-data flags).

I've make a simple dump to gain more info and they seem to be the cause of issue:

human:
```Key has potential validity: good
Key has fingerprint: 6BF1 6EE1 ECE7 A66C 4B66  36DF 0C9C 2E6A 4D27 3C6F
Checking to see if key is OpenPGPv4: V4
Checking the strength of your primary asymmetric key: RSA 4096
Checking user-ID- and user-attribute-related items:
  Human at FlowCrypt <human@flowcrypt.com>:
------ major difference -----
    Self-sig hash algorithms: [SHA-256]
    Preferred hash algorithms: [SHA-256, SHA-512, SHA-1]
    Key expiration times: []
    Key usage flags: [[sign-data, certify-keys]]
------end major difference -----
Checking subkeys:
  one of the subkeys is encryption-capable: True
  fpr: 1A0F 9B7F 5E48 F4DD 7B8D  108E 305F 81A9 AED1 2035
    version: v4
    timestamp: 20171102-175919
    algo/size: RSA 4096
    binding sig hash algorithms: [SHA-256]
    usage flags: [[encrypt-storage, encrypt-communications]]
    embedded cross-cert: False
    cross-cert hash algorithms: [SHA-256]
```

compatibility:
```Key has potential validity: good
Key has fingerprint: E8F0 517B A6D7 DAB6 081C  96E4 ADAC 279C 9509 3207
Checking to see if key is OpenPGPv4: V4
Checking the strength of your primary asymmetric key: RSA 4096
Checking user-ID- and user-attribute-related items:
Checking subkeys:
  one of the subkeys is encryption-capable: True
  fpr: F9CE DAA4 BE95 A007 4343  E069 4B5A 2FFC E62D 9501
    version: v4
    timestamp: 20171102-232518
    algo/size: RSA 4096
    binding sig hash algorithms: [SHA-256]
    usage flags: [[encrypt-storage, encrypt-communications]]
    embedded cross-cert: False
    cross-cert hash algorithms: [SHA-256]
```
    
Finally, there seem to be a solution to through https://github.com/openpgpjs/openpgpjs/discussions/1352 by using a specified config which happened to work but still checking it out.

reference: https://mail.google.com/mail/u/6/#inbox/FMfcgzGmvLWRpTQgmjkXXCqSJDvmLgbV

**Comment by tomholub** [comment]
Such message is not OpenPGP compliant, and we will not be adding compatibility to decrypt it.

Any pgp software that decrypt such message is buggy, including gnupg.

**Comment by martgil** [comment]
Thanks for looking into this. I understand the technical aspect of this issue after participating in the said thread above and the maintainer tell me that message should be encrypted to a public key with an 'encrypt' flag. 

 Closing this issue in the meantime. thanks again!

**Comment by fluxxion82** [comment]
@tomholub I'm a little confused - is it the message that isn't OpenPGP compliant or the keys? I've checked the keys used for encrypting the message and they're marked as encryption keys according bouncycastle pgp v1.70 (still not sure how to detect the sign only flag..i get the encryption key with the key id). Moreover, I tested with 3 other pgp tools to decrypt similar messages and all them were able to decrypt the messages. So you're saying that all of these tools are buggy??

**Comment by tomholub** [comment]
Are these 3 other tools all based on gnupg? (a lot of pgp tools are) Or more diverse?

You can use pgpdump to see structure of keys easily. Commonly, there will be a sign-only private key, and encryption-only subkey. On such key, messages should be encrypted for the subkey. If for example it was encrypted for the primary key (wrongly), than the receiving implementation must not decrypt it, because it's a sign-only key packet it was encrypted for.

See the pubkey at https://attester.flowcrypt.com/pub/flowcrypt.compatibility@gmail.com

You can paste it here https://www.lirnberger.com/tools/pgpdump/

Result:

```
pgpdump <ASCII data>

New: Public Key Packet(tag 6)(525 bytes)
	Ver 4 - new
	Public key creation time - Fri Nov  3 00:25:18 CET 2017
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA n(4096 bits) - ...
	RSA e(17 bits) - ...
New: User ID Packet(tag 13)(59 bytes)
	User ID - FlowCrypt Compatibility <flowcrypt.compatibility@gmail.com>
New: Signature Packet(tag 2)(565 bytes)
	Ver 4 - new
	Sig type - Generic certification of a User ID and Public Key packet(0x10).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA256(hash 8)
	Hashed Sub: signature creation time(sub 2)(4 bytes)
		Time - Fri Nov  3 00:25:23 CET 2017
	Hashed Sub: preferred symmetric algorithms(sub 11)(5 bytes)
		Sym alg - AES with 256-bit key(sym 9)
		Sym alg - AES with 128-bit key(sym 7)
		Sym alg - AES with 192-bit key(sym 8)
		Sym alg - CAST5(sym 3)
		Sym alg - Triple-DES(sym 2)
	Hashed Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0xADAC279C95093207
	Hashed Sub: preferred hash algorithms(sub 21)(3 bytes)
		Hash alg - SHA256(hash 8)
		Hash alg - SHA512(hash 10)
		Hash alg - SHA1(hash 2)
	Hashed Sub: preferred compression algorithms(sub 22)(2 bytes)
		Comp alg - ZLIB <RFC1950>(comp 2)
		Comp alg - ZIP <RFC1951>(comp 1)
	Hashed Sub: primary User ID(sub 25)(1 bytes)
		Primary - Yes
	Hashed Sub: key flags(sub 27)(1 bytes)
		Flag - This key may be used to certify other keys
		Flag - This key may be used to sign data
	Hashed Sub: features(sub 30)(1 bytes)
		Flag - Modification detection (packets 18 and 19)
	Hash left 2 bytes - ce e6 
	RSA m^d mod n(4095 bits) - ...
		-> PKCS-1
New: Public Subkey Packet(tag 14)(525 bytes)
	Ver 4 - new
	Public key creation time - Fri Nov  3 00:25:18 CET 2017
	Pub alg - RSA Encrypt or Sign(pub 1)
	RSA n(4096 bits) - ...
	RSA e(17 bits) - ...
New: Signature Packet(tag 2)(543 bytes)
	Ver 4 - new
	Sig type - Subkey Binding Signature(0x18).
	Pub alg - RSA Encrypt or Sign(pub 1)
	Hash alg - SHA256(hash 8)
	Hashed Sub: signature creation time(sub 2)(4 bytes)
		Time - Fri Nov  3 00:25:24 CET 2017
	Hashed Sub: issuer key ID(sub 16)(8 bytes)
		Key ID - 0xADAC279C95093207
	Hashed Sub: key flags(sub 27)(1 bytes)
		Flag - This key may be used to encrypt communications
		Flag - This key may be used to encrypt storage
	Hash left 2 bytes - b9 b8 
	RSA m^d mod n(4094 bits) - ...
		-> PKCS-1
```

Notice the interesting parts, for primary key:

```
	Hashed Sub: key flags(sub 27)(1 bytes)
		Flag - This key may be used to certify other keys
		Flag - This key may be used to sign data
```

Subkey:

```
	Hashed Sub: key flags(sub 27)(1 bytes)
		Flag - This key may be used to encrypt communications
		Flag - This key may be used to encrypt storage
```

If an implementation encrypts for such primary key, it's wrong. If then another implementation decrypts it with the above information, it's also wrong.

**Comment by fluxxion82** [comment]
Ok, interesting. I'm not sure what these tools are based on. One of the programs I've been using to test this stuff is my own, and I'm using the java bouncycastle library. When I encrypt something, I check that the key is an encryption key, via `isEncryptionKey`. I checked the documentation for this call and there's a note in the docs saying "subpackets should also be considered when present for determining the preferred use of the key". I had assumed that the check would be doing what's necessary to check if the key can be used for encryption but I guess not. I added the flag checks and flow crypt is able to decrypt the messages my app is generating.
I'm kind of concerned that my Gpg tools is decrypting the messages. If anyone was sticking to the openpgp specs, I would have though it was them. I think I'm going to write to them and let them know.
Thanks for explaining it a bit more.

**Comment by tomholub** [comment]
My guess is gnupg knows about this but did it anyway. But worth a try.

I don't recommend using BC directly, the library makes it real hard to do things properly.

Try https://github.com/pgpainless/pgpainless instead. It's based on BC but doesn't let you shoot yourself in the foot so easily (we support and use this library ourselves).
