### ISSUE TITLE
signed message occasionally throws an error 'Message digest did not match'

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4342]
Description:

A user reported an issue where a signed message occasionally throws an error 'Message digest did not match'. I asked the responded to send a couple of signed messages and those worked well without any issue.

I looked closer into the signed message that throws 'Message digest did not match' by opening/sending it again with myself and it works well (needs modifying signerEmail not to trigger the missing pubkey error checks as its a different error with a different root cause).

I'm having trouble spotting the problem for this one as it works after moving opening it in my inbox but it shouldn't be the case. 

will try to move the .eml file to my inbox to dig into this issue.

**Comment by martgil** [comment]
I loaded the .eml file into my inbox and the error 'Message digest did not match' occurs - when I just resend the signed message to myself (and edit the signerEmail), it works.

**Comment by martgil** [comment]
The message is also recognized when viewing it in the FlowCrypt inbox extension page but fails to recognize when the message is viewed in the Gmail for web inbox. - I have copied the message in the 'compatibility' account "Re: ....FlowCrypt feedback".

**Comment by martgil** [comment]
Related issue(s): 
https://mail.google.com/mail/u/6/#inbox/FMfcgzGpFWTMqVGCqljSGkdwwdFGVsNt

**Comment by martgil** [comment]
As of now, I can't find/create relevant test email to replicate the issue due to its complexity. However, we have a conversation through email support that has this problem which can be use to test manually.

Email thread that contains the error itself: https://mail.google.com/mail/u/6/#inbox/FMfcgzGpFWTMqVGCqljSGkdwwdFGVsNt

**Comment by martgil** [comment]
This is a very tricky bug. I import the message into our compatibility account and that produces the correct output. It has the subject of "False positive message digest not match" while it is the signed message on https://mail.google.com/mail/u/6/#inbox/FMfcgzGpFWTMqVGCqljSGkdwwdFGVsNt

Does the signed message don't want it to be in a thread?

**Comment by tomholub** [comment]
Please ask the user to send a sample directly to flowcrypt.compatibility@gmail.com

From there, we can produce a test case for it.

**Comment by martgil** [comment]
Thank you, sir! will do

**Comment by tomholub** [comment]
Before you do anything else at all, look into making a Draft PR for as I asked in the "URI filtering" email. I don't want to see anything else until you address that.

**Comment by martgil** [comment]
Thanks, @fluxxion82 for sending us the test signed message. 

The test message for this one is right here (compatibility test account): https://mail.google.com/mail/u/5/#inbox/WhctKKXXFsMTlBxJfdScBtSdHKkGVJtjwLfPtGbfMsvzKkQfgtwfbVNTqCpbfpMKbMWzJLq

**Comment by rrrooommmaaa** [comment]
There is an extra new line (0x0A) appears in the beginning of the cleartext message
![image](https://user-images.githubusercontent.com/23335944/218255716-0e93ee1c-d7b0-4f90-89fd-5f8f9b0b0647.png)

**Comment by rrrooommmaaa** [comment]
Indeed, the `text/html` section of the e-mail goes to rendering and this part:
`innerHtml`=`<div dir=3D"auto">Hash: SHA512</div><div dir=3D"auto"><br></div><div dir=
=3D"auto">this is a test for flowcrypt issue 4342</div>`
gets converted to this:
`innerText`=`Hash: SHA512\n\n\nthis is a test for flowcrypt issue 4342\n`

We shouldn't be using HTML to Text conversion for cleartext messages, we should extract cleartext from `text/plain` section of the email.

**Comment by rrrooommmaaa** [comment]
> But if we are downloading the message from API already? For sure need to use the text/plain portion.

For cleartext signed messages -- we don't

**Comment by tomholub** [comment]
We used to, but only if they fail verification. I thought we still do.

**Comment by tomholub** [comment]
It's the `forcePullMsgFromApi`, passed into `initialize` as `true` sometimes, eg here:

```ts
      if (this.view.signature && !verifyRes.isErrFatal && this.view.decryptModule.canAndShouldFetchFromApi()) {
        // Sometimes the signed content is slightly modified when parsed from DOM,
        // so the message should be re-fetched straight from API to make sure we get the original signed data and verify again
        this.view.signature.parsedSignature = undefined; // force to re-parse
        await this.view.decryptModule.initialize(verificationPubs, true);
        return;
      }

```

If that error handler were to be adjusted, the problem would fix itself, I think. (if the problem comes from HTML DOM parsing)

**Comment by tomholub** [comment]
yes
