### ISSUE TITLE
Emails labeled as 'promotions' not shown in Gmail for web but shown in primary inbox of FlowCrypt inbox (web page)

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4360]
@tomholub just sharing what I've spotted on the browser extension.

On Gmail for web, the promotions are not shown in the primary inbox of a user. For example, in our support email, the 'promotions' emails are separated into the 'promotions' tab of Gmail.

For another example, take a look at the following URL below:
https://mail.google.com/mail/u/6/#search/label%3Apromotions

and the promotions tab of gmail and it will show the same emails as its indication.

On the FlowCrypt web page (inbox) its not the case so emails that are labeled as 'promotions' are mixed up with user's primary emails.

In my opinion, it would be best to separate the 'promotions' label by default to make it more organize (mimic gmail behavior) so that users can focus more to their primary emails.

**Comment by tomholub** [comment]
Thanks for the report. The FlowCrypt Inbox is supposed to only be a backup mechanism. I don't want to make it too complicated.
