### ISSUE TITLE
inspect [check-for-email] github action 

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4374]
> There were 1 email addresses found in the above comment. Please:
> 
>     1. Click `three dots` -> `edit` to remove the email addresses.
> 
>     2. Click `edited` in the comment header, and click on the previous revision of the comment.
> 
>     3. When viewing the old revision with an email in it, click `options` -> `delete this revision from history`.

@martgil this one seems wrong - since it's on .test domain. Can you take a look?

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4372#issuecomment-1091596269_

**Comment by martgil** [comment]
@tomholub - I think I see the problem here. 

We can notice that the excepted domains are starting with an '@' char which is not following of a domain format so logically thinking the @test.com will pass while @demo.test.com will trigger the prompt.
<img width="1440" alt="Screen Shot 2022-04-07 at 7 56 15 PM" src="https://user-images.githubusercontent.com/46025304/162193260-4bdb17c8-9a46-4e41-a085-0923e79aad8b.png">

I'll try it here:
demo@test.com
demo@hello.test.com

**Comment by martgil** [comment]
demo.@test.com test@flowcrypt.com

**Comment by martgil** [comment]
Demo:

hello@.@test
demo@hello.test

**Comment by martgil** [comment]
@tomholub I found the problem. I looks like v19 working more appropriately unlike the v20. I'll push a PR now and it should work fine.

**Comment by tomholub** [comment]
:+1:
