### ISSUE TITLE
"show original message" functionality shows JSON representation of the mime message

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4386]
Description:
A concerned user reported to us that the "show original message" functionality that is usually shown when a decrypt error occurs shows a JSON representation of a raw mime message that confuses the user.

I wasn't able to replicate the issue for the time being so I'm taking down some notes so anyone would be aware of it and can provide more information if anyone encountered the said issue. Likewise, I'll provide more info whenever I have.

Reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGmvpBZtPqzLZGdBHFjQkGvHDNs

**Comment by tomholub** [comment]
you can inspect the see original implementation

**Comment by tomholub** [comment]
<img width="563" alt="image" src="https://user-images.githubusercontent.com/6306961/162818105-9545e974-191f-4efd-ae9e-880bd3841c27.png">

<img width="854" alt="image" src="https://user-images.githubusercontent.com/6306961/162818146-1fc97dd3-2dc0-424a-84df-a98a8bb14142.png">

Saw this in inbox earlier. It was a signed message that somehow failed validating due to format.

**Comment by martgil** [comment]
thanks @tomholub - this is helpful. I can now confirm this happens on email with detached signature (badly formatted signature). 

Does showing the plain text in replacement of JSON data the appropriate way to solve this? 

For example, this is currently how its done with the invalid signed message (inline)
![image](https://user-images.githubusercontent.com/46025304/162868682-534904b4-e00a-48eb-939f-c3e09396c22a.png)

**Comment by martgil** [comment]
ok this is unbelievable - the broken signed message I generated earlier suddenly started showing non-json output after reinstalling the browser extension. 

do the recently pushed updates sometimes needs reinstallation? most of the concerns related to signed message issues were resolved just by reinstalling the browser extension. 

![image](https://user-images.githubusercontent.com/46025304/162870656-3e64e9cd-60a2-47eb-bb80-dd15c0dea03c.png)

**Comment by tomholub** [comment]
Just inspect the code of that functionality. If there is a JSON stringification, you'll see it.

**Comment by tomholub** [comment]
sure, the plain text would be better in this case

**Comment by martgil** [comment]
@tomholub - thanks for the other hint - the (string) json message shown is actually an error message in json format. To fix the issue, the (string) json message had to be parse to extract the plain text message.

PR is now ready for review https://github.com/FlowCrypt/flowcrypt-browser/pull/4394
