### ISSUE TITLE
add more information to Settings -> My Keys similar to Android

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4407]
@tomholub I've added a few UI changes to see the key status. Please look at them. If it looks good I will add a few tests and then this issue will be completed.

![image](https://user-images.githubusercontent.com/2863246/164253226-95ac0127-7cd2-421e-8666-2eab197a4d03.png)
![image](https://user-images.githubusercontent.com/2863246/164253592-2b7f6f65-82c9-44a8-96c8-6fb8ba405f06.png)
![image](https://user-images.githubusercontent.com/2863246/164253744-c2cae948-504e-4a9f-940f-f54988d71815.png)
![image](https://user-images.githubusercontent.com/2863246/164253841-e71d5fbd-4b5b-4920-b5df-877f7c2f4e32.png)

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/1741#issuecomment-1104002848_

**Comment by tomholub** [comment]
In particular:
 - in list of keys, should add status (valid / expired / revoked) next to each key
 - when clicking on key details, should show `status`, `key creation`, `key expiration` values

**Comment by IvanPizhenko** [comment]
@tomholub and/or @rrrooommmaaa Where exactly this should be added?

**Comment by tomholub** [comment]
The functionality and structure of the available options/settings are more or less equivalent across platforms. Here we are talking about displaying our own keys, there is only one such place on each platform.

On Android and iOS this is `Menu` -> `Settings` -> `Keys` (this is a list of keys page) -> (tap any key) -> key details page

On browser extension this is `Settings` -> `Additional Settings` (shows list of keys on the bottom) -> (click any key) -> key details page

The list of keys, and the key details page, is what needs editing as per https://github.com/FlowCrypt/flowcrypt-browser/issues/4407#issuecomment-1104472903
