### ISSUE TITLE
[Discussion]Question: How to conveniently update expired private key

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4408]
Scenario:
The user had already expired the key (usable).

As far as I know, we currently have a quite long process to update the key. 

For the non-enterprise users (current behavior):
A key is already updated through gpg > Perform a reset (uninstall the extension) > skip backup recovery process > load the key with updated expiry date > key ready to use.

(suggested) For the non-enterprise users (ideal behavior):
A key is already updated through gpg > (a pop-up notice tells that a key is expired) > the key can be updated without the account reset process (uninstallation). I'm not sure how feasible it is but there would be a button that says 'update expired key' which when clicked will open a file upload dialog box and select the update key > overwrite the matched key with the updated one > key ready to use.

For the enterprise users (current behavior):
the same process as for non-enterprise users.

(suggested) For the enterprise users (ideal behavior):
(a pop-up noticed tells that one of the keys is expired) > there would be a button that says 'update expired key' > fetch the updated key from the ekm server > overwrite the matched key with the updated one > key ready to use.

Reference: https://mail.google.com/mail/u/6/#inbox/FMfcgzGpFWQsgmTkjsDwZDvcdjhcHbzm

**Comment by tomholub** [comment]
See the "update" button

<img width="676" alt="image" src="https://user-images.githubusercontent.com/6306961/164413246-8e0fd4c1-36ab-42a4-ad0d-644d9112fdda.png">

**Comment by tomholub** [comment]
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/6306961/164413349-495e3a5a-d483-4d77-946e-ad022c63c53e.png">
