### ISSUE TITLE
change google api domains to their more specific subdomain alternatives

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4417]
I was talking about the "URI filtering" email.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4416#issuecomment-1110740390_

**Comment by martgil** [comment]
I have gathered all of the alternative URI's and here are those:
```
- https://oauth2.googleapis.com/token
- https://oauth2.googleapis.com/tokeninfo
- https://gmail.googleapis.com/gmail/v1/users/me/settings/sendAs
* https://contacts.googleapis.com/m8/feeds/contacts/default/thin
- https://gmail.googleapis.com/gmail/v1/users/me/messages
- https://gmail.googleapis.com/gmail/v1/users/me/drafts
- https://gmail.googleapis.com/upload/gmail/v1/users/me/messages/send
- https://gmail.googleapis.com/gmail/v1/users/me/threads
- https://gmail.googleapis.com/gmail/v1/users/me/messages/*
- https://gmail.googleapis.com/gmail/v1/users/me/messages/*/attachments/*
- https://gmail.googleapis.com/gmail/v1/users/me/drafts/*
- https://gmail.googleapis.com/gmail/v1/users/me/threads/*
- https://gmail.googleapis.com/gmail/v1/users/me/labels
(people API)
* https://people.googleapis.com/v1/people:searchContacts
* https://people.googleapis.com/v1/otherContacts:search
```
Legends:
(--) : possibly ok
(*) : needs further checking

**Comment by martgil** [comment]
@tomholub are they interested in using Google API alternatives in making HTTP requests? 

I can see that after I changed the `www.googleapis.com` to these values, the domain `www.googleapis.com` was still the one fulfilling the necessary requests.

**Comment by tomholub** [comment]
> * https://contacts.googleapis.com/m8/feeds/contacts/default/thin

I don't think we use this API anymore.

**Comment by tomholub** [comment]
> I can see that after I changed the www.googleapis.com to these values, the domain www.googleapis.com was still the one fulfilling the necessary requests.

that means that you haven’t actually made the necessary change

**Comment by martgil** [comment]
> I don't think we use this API anymore.

thank you, I will exclude them from the current list.
