### ISSUE TITLE
Doesn't generate .xpi file for Firefox

### ISSUE THREAD

**Issue by OliverOffing** [FlowCrypt/flowcrypt-browser#4436]
I was able to build the project with `npm build` but it won't generate any `xpi` files. It seems Firefox requires a single file as opposed to a directory (i.e. `./build/firefox-consumer`). Help?

**Comment by tomholub** [comment]
For testing, you can get it running with `npm run_script run_firefox` or `run_firefox_windows` so you don't need the xpi file.

**Comment by OliverOffing** [comment]
I'd like the xpi file so that I can build myself FlowCrypt and use it on my day-to-day browser.

**Comment by OliverOffing** [comment]
In case anyone else comes looking. In order to build a valid `.xpi` file and load it into firefox, you'll need to follow these steps:

1. You'll need the [Developer Edition](https://www.mozilla.org/en-US/firefox/developer/) of Firefox in order to install unverified extensions. 
    - This is a bit silly. Although the extension isn't signed by some external key I built the extension myself so it's more than verified IMO.
    - NB: You can use your existing profile with the `firefox -P` option.
1. Go to `about:config` and set `xpinstall.signatures.required` to `false`
1. Clone this repo
1. `npm install`
1. `npm build`
1. `cd build/firefox-consumer && npx web-ext build`
1. Now go to `about:addons` and install the extension from the file generated inside the `web-ext-artifacts` directory

Hope this helps.
