### ISSUE TITLE
[User feedback] browser extension not accepting ed448

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4445]
Description:
A user informed us that the browser extension isn't accepting ed448 (probably a key encryption type?).

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGpFqdCjkHjqDsSZRGrvxqrKQCV

**Comment by tomholub** [comment]
Can they produce a key sample with it?

**Comment by martgil** [comment]
I will try to request a sample key from the user. I'll update you shortly.

**Comment by martgil** [comment]
Hello, sir, @tomholub 

The respondent gratefully generates sample keys for us. I also asked for his permission if it is okay to share the sample keys here, to which he agrees.

Here are the sample keys:
[flowcrypt private.ppk.txt](https://github.com/FlowCrypt/flowcrypt-browser/files/8706056/flowcrypt.private.ppk.txt)
[flowcrypt public.txt](https://github.com/FlowCrypt/flowcrypt-browser/files/8706057/flowcrypt.public.txt)

He also added that he tried various key/certificate conversion but with no avail:
> converted this into various formats, binary (base, base64) and ascii (pkcs7a, pkcs7b, pkcs12) forms, cers, ders, pfxs

**Comment by tomholub** [comment]
That is not an OpenPGP private key. He should use OpenPGP compatible software to generate keys.
