### ISSUE TITLE
FlowCrypt extension can't picked up idToken on kiwi browser after a successful OAuth authorization flow

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4466]
Description:
Kiwi Browser is a chromium-based web browser for Android with chrome extension support. 
After installing the FlowCrypt extension and successfully passing the OAuth login flow. 

The state of the browser extension remains still even though the Oauth consent page says that the authorization process is successful - "Authorization has been granted successfully. Please switch to your application."

Video demostration:
<video src=https://user-images.githubusercontent.com/46025304/170222545-74f8c796-ca20-4153-bcbc-70a14aabc832.mp4>

Any thoughts or feedback to be shared will be highly appreciated. If there's anything I could help with, please let me know.

Thank you very much!

Reference: https://mail.google.com/mail/u/2/#inbox/FMfcgzGpFzssDHCbCsgtdbWsdkkxWmZC

**Comment by martgil** [comment]
I have requested the user for the extensions that are previously worked well on the kiwi browser that has interactions with the OAuth consent screen and luckily, there are numbers of extensions we can look for as a reference just in case we consider supporting the Kiwi browser.

- Microsoft Autofill 
- Microsoft Office extension 
- OneNote Web Clipper
- Adobe Acrobat
- Adobe CreativeCloud
- Amazon Assistant
- Honey
- Todoist

**Comment by tomholub** [comment]
I'd recommend the user tries the FlowCrypt Android App instead.

Even if they can set up the extension, I don't think it will work on mobile Gmail interface on the web, as it looks completely different.
