### ISSUE TITLE
implement allow_attester_search_only_for_domains client configuration

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4476]
Regex would probably be the most flexible but also complicated.

Let's go with what Roman suggests.

> What about adding `allow_attester_search_only_for_domains` option?
> 
> If it's set then app will ignore `disallow_attester_search_for_domains` option and search only in listed domains.

Plus add an appropriate test.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-ios/issues/1668#issuecomment-1146221302_

**Comment by tomholub** [comment]
Wiki will help you a lot to get started. Particularly for tests https://github.com/FlowCrypt/flowcrypt-browser/wiki

To create test, you'll have to add your updated client configuration here https://github.com/FlowCrypt/flowcrypt-browser/blob/d3ee8a3b09b32687c0ee8096a322667932772329/test/source/mock/backend/backend-data.ts#L148 - use user on some unique domains like `user@allow-attester-some-domains.flowcrypt.test`. The domain would come here with your desired org rules to test

Then, use that user to write a test which will get that particular client configuration. (browser extension tests all use mocked apis, even for Gmail apis, so you can use any user email you want). Here is a similar test https://github.com/FlowCrypt/flowcrypt-browser/blob/d3ee8a3b09b32687c0ee8096a322667932772329/test/source/tests/setup.ts#L487 so you'd want to copy that and write a new test.

**Comment by tomholub** [comment]
@ioanmo226 please do this one next while it's fresh in your mind

**Comment by ioanmo226** [comment]
ok
