### ISSUE TITLE
test-secrets.json should not contain keys section

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4478]
It should be moved to code instead, or a separate json file that gets checked into repo

No reason to put these in the secrets file

**Comment by ioanmo226** [comment]
I also think it's good idea to add test-secrets-sample.json (which is not git-ignored and only shows structure).
Something like
```
{
  "ci_admin_token": "",
  "ci_dev_account": "",
  "data_encryption_password": "",
...
}
```
I didn't have any idea how test-secrets.json look like and even developers won't know about structure if they've been away for long time.

**Comment by tomholub** [comment]
I guess we could do that also
