### ISSUE TITLE
no-explicit-any warnings - prefer unknown

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4490]
> It seems we have delayed after-effects after this merge. #4284 https://flowcrypt.semaphoreci.com/jobs/47dbcb8e-5bc4-437a-9812-e70699e7d855

They are all warnings, except for 

```
   148:4   error    Missing semicolon                         @typescript-eslint/semi 00:09 
```

In either case, we should try to address these warnings - I'll file an issue.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4484#issuecomment-1152617605_

**Comment by tomholub** [comment]
@martgil you can take 5 of these warnings and convert `any` to `unknown` in the code, and make a PR.

If the reviewer is happy with the result, then you could try to address the rest, gradually.

**Comment by ioanmo226** [comment]
I also don't prefer `unknown`.
I prefer to define types as possible as we can. For real unknown types, we may define `unknown`.

**Comment by ioanmo226** [comment]
@tomholub What do you think?

**Comment by tomholub** [comment]
I agree in general. But it may be a lot of work that I may not want to immediately block developer time for :-)

I'd do two steps - in first step, convert all to `unknown` (Mart, who is not a developer, could still do this) and then in the PR review we'll highlight the areas where we really need more proper types, and focus on that in another PR.

`unknown` is not too bad btw. `any` means anything goes, anything is correct. `unknown` means the compiler doesn't know the type and you have to test the value to determine what type it is, in order to use it. It's a pretty safe type when handled appropriately.

I think a lot of the `any` will be thrown errors (today declared as `any`) where `unknown`.

Most of the `any` situations will probably come from missing types on libraries. So we'll have to write `<library>.d.ts` files for them which may not be trivial, for some of them. But it could later be filed as a separate issue eg `add types for library X` that will solve 50 any/unknowns at once.

**Comment by ioanmo226** [comment]
OK, Got it

**Comment by rrrooommmaaa** [comment]
I still see a lot of warnings.

**Comment by ioanmo226** [comment]
Yeah, there are still tons of warnings
