### ISSUE TITLE
"switch to encrypted reply" no longer works 

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4496]
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/6306961/174572325-5d9e8421-6170-44ca-8a7f-a677e2565e54.png">

To reproduce, in my case:
 - receive several encrypted messages in a thread
 - pick the one in the middle
 - click "reply all" using standard gmail interface
 - then see above banner
 - clicking `Switch to encrypted reply` doesn't work

Actually, the reason this happened is because I didn't see any "encrypted reply" option on the message itself. It seems that it's missing on encrypted messages that have many recipients:

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/6306961/174573073-3d327b21-ac38-43c0-90f6-e3092fc3c112.png">

but it's present and functioning on encrypted messages with just me as a recipient:

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/6306961/174573174-b43eb93d-a353-40a7-bb91-5ae1d3f7c4f8.png">

So that needs to be addressed as well.

**Comment by tomholub** [comment]
Please later see if you can reproduce this, as you recently looked into something similar.

**Comment by ioanmo226** [comment]
Just checked and reproduced this issue.
But not sure what should be done when user clicks `Switch to encrypted reply` as we already have view with 3 buttons at the bottom(`secure reply to all`, `secure reply`, `secure forward`).
I think this issue can also be ignored if we implement [this issue ](https://github.com/FlowCrypt/flowcrypt-browser/issues/4630)?

**Comment by tomholub** [comment]
Maybe you didn't reproduce the same thing that I encountered earlier. In my case, whatever I did, I couldn't get the secure reply box to render. If you already saw the secure reply to all, secure reply, secure forward buttons, then you had different behavior then me. In some situations, I could not get these three to appear at all.

**Comment by ioanmo226** [comment]
I think I encountered same thing.
When you open thread (with encrypted emails). you see secure reply box at the bottom of thread. Right.
And the problem is you click email(in the middle) and click `reply all` and then click `switch to encrypted reply`. and it has no behavior.

What I mean is if we display secure reply box below the email(in the middle) we will end up having 2 secure reply boxes and that doesn't seem to be good

**Comment by tomholub** [comment]
Ok. It is indeed the same thing.

I think it's ok to have more than one secure reply box - one in the middle, and one on the bottom. Doesn't bother me, anyway :-) and I think it mimics what Gmail would do as well in that situation? Or is Gmail somehow more clever?

**Comment by ioanmo226** [comment]
Gmail is more clever and same behavior as #4630.
it displays reply box just under email. I think we should also replace standard reply box with secure reply box once user clicks `switch to encrypted reply` (like mentioned in #4630 )

**Comment by tomholub** [comment]
Ok. I'll let you handle this in a way that you find most appropriate.

**Comment by tomholub** [comment]
One thing is though, Gmail also has a way for me to switch to "reply all" or "forward" after the reply box is already open. That's why they don't need the extra step, and that's why they don't need so many buttons. So I suppose we may need to do that first?

**Comment by tomholub** [comment]
Would be good on Android and iOS too, tbh. Convenient

**Comment by ioanmo226** [comment]
I agree
> So I suppose we may need to do that first?
