### ISSUE TITLE
reply sometimes showing [object Object] instead of recipients

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4497]
tested on 8.3.2, firefox. Seems we have some unsafe/unwanted conversions to string.

![image](https://user-images.githubusercontent.com/6306961/174614928-974a6500-878b-4757-b33c-3715ace0f60a.png)

**Comment by rrrooommmaaa** [comment]
This appears to be solved by PR #4284.
This is how the reply is rendered after sending now (related test: 'user2@standardsubdomainfes.test:8001 - PWD encrypted message with FES - Reply rendering').
![image](https://user-images.githubusercontent.com/23335944/178140271-6003ce78-e0db-4e34-a825-d161bd4d419c.png)
