### ISSUE TITLE
update client configuration each time settings page is refreshed or gmail content script loaded

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4510]
.

**Comment by tomholub** [comment]
currently only updating client configuration following google authentication. We should additionally do it in asynchronously each time settings page is loaded, and in asynchronously each time content scripts are loaded.

**Comment by rrrooommmaaa** [comment]
Is this priority over #4596, @tomholub ?

**Comment by tomholub** [comment]
yes, this one is more important at the moment. Thanks for asking
