### ISSUE TITLE
[Feature suggestion] add templates to encrypted emails

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4538]
We received a feature suggestion to add templates to encrypted emails. Though we don't have the suggested feature yet, users might use the email templates feature from Gmail in the meantime (currently not available for the mobile apps). 

Reference: https://mail.google.com/mail/u/6/#inbox/FMfcgzGpGwhzgShgTTxGctwtwZShwbzh

**Comment by tomholub** [comment]
We could potentially look into this sometime 2024 or later. For now, unfortunately not.

**Comment by martgil** [comment]
Ok, sir - I understand. Thank you!
