### ISSUE TITLE
Consider using tailwindcss

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4542]
Currently, we have so many hardcoded styles in cryptup.css.
With help of tailwindcss, we may eliminate all those styles and we won't need to define custom css classes to define styles.

Ping: @tomholub

**Comment by tomholub** [comment]
That would be quite a rewrite. I'm generally against - frameworks come and go, and their popularity changes over time too. For example, I think we still have some pages that use Bootstrap and it makes sense when the whole team know the framework, but what ended up happening was a 50% effort that is neither here or there. Now the guy who knew bootstrap is gone and it's just another legacy thing we have 🤷 on one or two pages.

On the other hand, I'd be in favor of trying to clean up our css files. Eg use some tool to see which ids/classes are unused and trim it down. And remove bootsrap where it's still used :-)

**Comment by ioanmo226** [comment]
Ok, got it

**Comment by ioanmo226** [comment]
By the way, @tomholub 
I'm curious, why we put all styles in cryptup.css file instead of add styles per html files and only add common styles in cryptup.css file

**Comment by tomholub** [comment]
I just didn't think of splitting it, but it sounds like an improvement. Feel free to take it on.
