### ISSUE TITLE
Browser extension is experiencing problems with Brave Browser v1.41.96

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4552]
Looks like the same issue was re-introduced again on Brave Browser v1.41.96 (latest version)  - https://github.com/FlowCrypt/flowcrypt-browser/issues/4472

The message was all readable if they are viewed through the web extension pages. The error message says "Could not load message due to network error. retry"
![image](https://user-images.githubusercontent.com/46025304/179928793-4f7ad1ce-41bd-487f-a196-e6a7c8b6680b.png)

Steps to reproduce
- pre-requisite:
Flowcrypt browser extension installed on brave browser (latest version)

1. open an encrypted message and the error "Could not load message due to network error. retry" will appear.
2. (optional) messages are readable through web extension pages (click on the FlowCrypt browser extension icon  -> Encrypted Inbox -> open an encrypted email -> encrypted message is readable)

<details><summary>stack traces:</summary>

```
[callerStack]
    at chrome-extension://mimchhddcelobciniokjnakmkcbdggof/js/common/browser/browser-msg.js:289:124
    at new Promise (<anonymous>)
    at BrowserMsg.sendAwait (chrome-extension://mimchhddcelobciniokjnakmkcbdggof/js/common/browser/browser-msg.js:287:22)
    at Object.pgpMsgDecrypt (chrome-extension://mimchhddcelobciniokjnakmkcbdggof/js/common/browser/browser-msg.js:41:47)
    at decrypt (chrome-extension://mimchhddcelobciniokjnakmkcbdggof/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.js:76:67)
    at PgpBlockViewDecryptModule.decryptAndRender (chrome-extension://mimchhddcelobciniokjnakmkcbdggof/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.js:82:42)
    at async PgpBlockViewDecryptModule.initialize (chrome-extension://mimchhddcelobciniokjnakmkcbdggof/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.js:35:25)
    at async PgpBlockView.render (chrome-extension://mimchhddcelobciniokjnakmkcbdggof/chrome/elements/pgp_block.js:46:21)

url: chrome-extension://mimchhddcelobciniokjnakmkcbdggof/chrome/elements/pgp_block.htm?frameId=frame_dPIRWiVQYn&message=-----BEGIN%20PGP%20MESSAGE-----%0AVersion%3A%20FlowCrypt%20Email%20Encryption%208.3.2%0AComment%3A%20Seamlessly%20send%20and%20receive%20encrypted%20email%0A%0AwcBMA7ABwoqBKaWeAQgAgW8oyR3VvdKA2h5NmYChMdMdwK37TnWjRO3OQGSj%0AARwaULYzdMfbqcpChiVLaN9pRUI7MJ41vvXf3wEe1iBy9DrH85C7Y2PrCJyi%0ARRRNVHKf2nD3ClfAkUK4T2G43qxn9DkW1s0BGP2Z%2BdwiXItnFF2ZihOBj7c7%0AsIY85eYpNkPZPoUNRDVqx8ma1LTkj2URG1KK5Yuqs6BbAwSlJdyQeFFsKLoF%0AQPDitwGiA6nx6sJRQPteQuGxDu64pWAo5UPTV30A1EtnAngR3jXmCGkUh0T8%0AVE8whC9t%2BugRCU%2Bss75rzdZWt4H7bZZXxuOsBg%2Fq55DfzbYmkJ9ZvvWSiiOO%0AScHATANxBa6MDR4LLQEIAJCo3DGFqWeGHRTpIBfWo8%2FVeSSnIMcyW17WmfRe%0A8c2RiEMkTezS2Ur22p%2FwfHZxrUaUMFQFOyUHH67BLeGuFk%2B824qOuIl1dYZi%0A7fbZs99Q6CMs%2BMvGKuUGXDdr%2BiqUZdQxyHAjJ9Nl0eeiK4Ag42N2S6bTxAl7%0AcRZIvEKeKJ%2BHlg94EPdInS8ahlrOf%2BzGGFYd%2BD%2FT8rLp%2BcaBFoKx8B6XVs67%0AtDNH8r4xavj5BhwmQi4Elcj545OMWc4uHYBRAHJUFFJT7wx0YCNOcLuiyMnx%0AQEU9AegWR3%2BelFfYTXwnpvwaCGAjVEgva2ZorCneR5QMPZ1vC7LS%2FLqIQMQO%0AXeLBwEwDsAHCioEppZ4BB%2F9tgccDm8IhxnHYGmSdz9%2Bby5i4rc6R4ZghsDjE%0A3cqWB2uPkf79tb2i%2FjUAODUL1Z3HO7NA5sMavIPKTBTi3eHHevO%2FKdG5g9BR%0AAmEMlMroRfKaIIlvuolzVvzoChg6xTN%2BHLl37rvgKb%2BsUu3R0kMzkr86ewmV%0Aw1EBtKmSH32sNW7T1HgqynXDzLpKld9V2GjpZd5bZLJl2kWDxmB2pxoPwh5Q%0ABomWRyoC5Itr1lklCdwBdWiSJwWJcARyGEpcOdi854ghCa5ALrXjSXMadTCs%0A3nv6U%2BNSSCrTIcy5NUcA7hQx74XxLPHEdQB%2FhkNz5PfbqrKkLMtpk6ga8q3S%0A7yNc0sDCAU2msF8CQ6xfm6WffY48eOS0ilr5pDzUtdgUVwD33b%2FBMu0%2BAfdU%0AAM5JztIfWYyei4JVfbtoio41dYwlLs%2B40O8X1RbflYP2KR0myVfWpt9YVDkt%0AcJoIdCf7IDaC12RSU9PleMpjXsaP98TQe%2BtuvLv112d4Ro4JJoMbPmuZlhp1%0A5bPerhGLuLEuHXiWy3mMzsQ79gLmhJaK5U1WbAGnwMs5l6kdbjMbH75Ucmd1%0AA6rcdI5rXJLKlP6VZn1YSi2e0c8VeFcBToCF%2B4wmLLdXVOTH9DUw8Kuy%2BMsI%0AW7lE3aFpQ1ZJlhlN2EVo78UhcgGFIcZ3pe4G914wPLlFMeaJOkyOKrduvZ0w%0A3d21NJ2bPyBvtfTMYwx3iof8yYJjboCORmthfjAVVqQl22%2FH5Kbj%2FZIkuP1l%0ASpPQ78PxiqQ5t%2BN7sdg55GJgdQF%2FpelO66sv93xHQhcezoiVNMTS0yXshpva%0Adclz0R8ZTj0xpHq1LS556x5CEK%2BjyHKPtsugzoJTn9Y%3D%0A%3DwoDK%0A-----END%20PGP%20MESSAGE-----&msgId=1821604bd58a3a7b&senderEmail=twosince85%40gmail.com&isOutgoing=___cu_true___&acctEmail=user@email.test&parentTabId=31%3A0

[/callerStack]

[responderStack]
    at XMLHttpRequest.errHandler (chrome-extension://mimchhddcelobciniokjnakmkcbdggof/js/common/api/shared/api.js:34:110)

url: chrome-extension://mimchhddcelobciniokjnakmkcbdggof/js/background_page/background_page.htm


provided ajax call stack:
    at XMLHttpRequest.errHandler (chrome-extension://mimchhddcelobciniokjnakmkcbdggof/js/common/api/shared/api.js:34:110)

url: chrome-extension://mimchhddcelobciniokjnakmkcbdggof/js/background_page/background_page.htm

    at <async> download (/extension/js/common/api/shared/api.ts:37:27)
    at <async> objUrlConsume (/extension/js/common/browser/browser.ts:20:32)
    at <async> replaceObjUrlWithBuf (/extension/js/common/browser/browser-msg.ts:455:40)
[/responderStack]

    at <async> sendAwait (/extension/js/common/browser/browser-msg.ts:370:29)
    at <async> decrypt (/extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts:75:22)
    at <async> decryptAndRender (/extension/chrome/elements/pgp_block_modules/pgp-block-decrypt-module.ts:72:29)
    ```
    
</details>

user complains:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGpGwsMgrDkbvzGnNxsGVCTSFtB
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGpGdmqTvRlGdXPBfXmkGTsJlrT
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGpGwlRstKtkZSssQrXdjKjqrpl

**Comment by martgil** [comment]
Users with the same problem:

https://mail.google.com/mail/u/2/#inbox/FMfcgzGpHHWjPZKRmmLSmQkhrndjjLKk
https://mail.google.com/mail/u/2/#search/brave/FMfcgzGpGwlRstKtkZSssQrXdjKjqrpl
https://mail.google.com/mail/u/2/#search/brave/FMfcgzGpGdmqTvRlGdXPBfXmkGTsJlrT
https://mail.google.com/mail/u/2/#search/brave/FMfcgzGpGwsMgrDkbvzGnNxsGVCTSFtB

**Comment by martgil** [comment]
Additionally, the error message disappears if the URL being framed (pgp_block.htm) is accessed directly or read the message from the encrypted inbox. I read the error message and it tells about error GET-ting blob://chrome-extension... but can't find the root cause. I feel like the error exists only when viewing on the mail.google.com?

**Comment by martgil** [comment]
@rrrooommmaaa Good afternoon, sir! What do you think about this issue? Some users found that some browser extensions were also affected/started to work improperly with Brave's recent update.

**Comment by rrrooommmaaa** [comment]
I guess Brave shields consider `mail.google.com` and Flowcrypt's extension settings pages as different sites, thus blocking the former (web content script) from re-using credentials received from the latter.
We can probably circumvent this by delegating this call to the background page, but I'm not sure if this solution is preferred.
![image](https://user-images.githubusercontent.com/23335944/182828129-9a317f5b-5651-4bce-815e-643604e437e2.png)
We can probably solve this with Brave Shields option "Allow Google login for extensions", or
file an issue in https://github.com/brave/brave-browser repo so that the extension automatically receives the necessary privileges since the `gmail` site is mentioned in the extension's manifest.
![image](https://user-images.githubusercontent.com/23335944/182828763-24ccdc8c-8fca-4736-b25c-e53869fc20d3.png)

**Comment by martgil** [comment]
sir @rrrooommmaaa I have filed an issue in the Brave browser repo about the potential bug -  https://github.com/brave/brave-browser/issues/24459.

**Comment by martgil** [comment]
I received user feedback stating that the browser extension doesn't work with containers (such as the multi-account container by firefox). I look at the issue, and they share similar error message when using Brave Browser with cross-cookie blocked through Brave shields. Just sharing it here - maybe it might help.

It contains the following error message (extracted from pgp-block-error-module.ts -> ApiErr.isNetErr(e)):
> Error: BrowserMsg(pgpMsgDecrypt) (no status text): -1 when GET-ing blob:moz-extension://889c1ed4-37a0-4803-8189-558015b71615/96ff591e-a3d9-4e94-a0fc-44b1b7857c12 (no body):  -> (no standard err msg)

From email: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqPpcmvCkNTQGBqHLdpzjWbhpl

**Comment by rrrooommmaaa** [comment]
Right, I reviewed the call stack once again and it turns out that I was wrong about the idea that the problem is with the gmail token.
Actually, the error happens in the background page when trying to restore parameters from objUrls: `replaceObjUrlWithBuf` calling `objUrlConsume` calling `Api.download`.
The parameter was previously packed by the outer page with `replaceBufWithObjUrlInplace` calling `objUrlCreate` calling [window.URL.createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) -- this call happens when sending a large buffer to the background.
So actually this mechanism is broken by Brave Shields.
As for our particular case, I guess, the data passed as objUrl is probably the encrypted message (need to double-check that), and if the frame fails to retrieve it, we can add some fallback code that will try to load this message from Gmail.

**Comment by sosnovsky** [comment]
Seems to work well in the latest Brave releases, also haven't received any user feedback about this issue, can be closed for now.
