### ISSUE TITLE
Ways to check the PGP key version?

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4592]
Hello,

I just want to ask if anyone knows to dump the OpenPGP key version. We received a concern informing us that the keys generated by the extension are in V3 format (deprecated) and can't be uploaded to a server that requires v4.

To investigate the issue, I ran `gpg -vv my_pubkey.asc`, and the output shows packet version 4. Alex asks the same question a couple of years ago - https://superuser.com/questions/1584221/how-can-i-tell-what-version-of-pgp-a-public-key-uses. Also, in the same post, he shares that the packet version might not be the PGP key version.

Any feedback or suggestion is always welcome and appreciated. Thank you!

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqPpjXMsfbNxPmQWWmnfZLGQbg

**Comment by martgil** [comment]
Thanks for your response, sir!

<details><summary>user's public key: </summary>

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: FlowCrypt [BUILD_REPLACEABLE_VERSION] Gmail Encryption
Comment: Seamlessly send and receive encrypted email

xjMEYvHMHhYJKwYBBAHaRw8BAQdArybfYTvC1Nad10LBw/ls1NL7FooTtaGR
zQLLil0AwAbNKFBhdWwgV2lsbGlhbXMgPGNvb0Bmb3JlY2xvc3VyZXBlZGlh
Lm9yZz7CjwQQFgoAIAUCYvHMHgYLCQcIAwIEFQgKAgQWAgEAAhkBAhsDAh4B
ACEJEBORnl9u257qFiEEXx3pvB7qL6WiCn30E5GeX27bnurZegEA3EZGZUFD
iwKRcBB0xRa/i2tiS8VUfquAEnJBOctTlqkA/RUlg4uVXXUCDWAuBkcviEPZ
dTHtx48EK5ajSXD65bMCzjgEYvHMHhIKKwYBBAGXVQEFAQEHQACnRnHcsCPY
7nT0XX+aMTVeGNbOrzRK7NoQxEd2jqYNAwEIB8J4BBgWCAAJBQJi8cweAhsM
ACEJEBORnl9u257qFiEEXx3pvB7qL6WiCn30E5GeX27bnurkhwD/dtnJugAy
5tzZHks2tMm/B9iOw2LOGuWGIdngpadqXYwA/jXM3Vpt3TTOvMgemUIk3Swu
8YHGIj/SqdHc9/3wJpEC
=3dhE
-----END PGP PUBLIC KEY BLOCK-----
```

</details>


keyserver(PGP Global Directory): https://keyserver.pgp.com/vkd/GetWelcomeScreen.event

I've also asked the same question from OpenPGP.js's Q&A section and they say that the keyserver probably doesn't support ECC keys since they are very old. - https://github.com/openpgpjs/openpgpjs/discussions/1552

**Comment by tomholub** [comment]
I agree with that assessment. ECC keys are modern and keyserver.pgp.com most likely doesn't support them, wrongly claiming they are v3 keys.
