### ISSUE TITLE
Fix semaphoreci ui test

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4593]
Sometimes semaphoreci ui test fails with timeout issue.
Need to be investigated.
https://flowcrypt.semaphoreci.com/jobs/cdbf4d6b-e900-494c-9481-c595677f9481

**Comment by rrrooommmaaa** [comment]
I have also seen periodic failures of this test `user4@standardsubdomainfes.test:8001 - PWD encrypted message with FES web portal - some sends fail with BadRequest error` -- maybe related.

**Comment by ioanmo226** [comment]
Right
