### ISSUE TITLE
Export test result to semaphoreci

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4605]
I think we should implement `export test result to semaphoreci` feature like we did in iOS app.
Currently for browser extension, it's hard to find failed tests in semaphoreci if it fails.
I need to scroll up & down to check failed tests.
Here's reference.

https://docs.semaphoreci.com/essentials/test-summary/

cc: @tomholub

**Comment by tomholub** [comment]
yup

**Comment by ioanmo226** [comment]
I thought again and I think we don't need this one.

We already publish our own debug html format and that seems more meaningful (like below one)

https://storage.googleapis.com/p8ejr437e40a1hc10jpmsp5q2wfx83/artifacts/jobs/c7e05eba-f39a-485d-a90a-3bfe23c70594/debugHtmlAttachment-0.html?Expires=1675414967&GoogleAccessId=artifacthub%40semaphore2-prod-artifacts.iam.gserviceaccount.com&Signature=QpbzLshnYXQ0Er2YviJF7je%2BNq%2FSWknmp19b%2BcbZR2lnkAs3dJ0H8NeM0bT96XYAhkE5Nq6l9Daqc22z0ZK6hHeAr2rifSoES5nfykcB5E9kYGDvnWEab4SH1qy%2FXFVodUHjpEptjnh5FRrmuUuqvA2N4yAnCnmBzFncizz0d0JIPLXHyt7OzmwK%2BABe2ymyNBDqJ12RfS9fsb0hWvCYNg9QHRP1C%2F8JNi6KOXQqB0HV7g1seRQhqxxlayaupjRC0bBA%2BlEmp3fdVDnaEF%2FOay2ZIccA3RpjzL6Uomi3N3T5TgNDTrcP%2B8ZGMJgC%2BQWmdgEvMVebImfGEfIEk%2Bv5vg%3D%3D&response-content-disposition=inline&response-content-type=text/html;%20charset=utf-8

@tomholub What do you think?

**Comment by sosnovsky** [comment]
I think it's still will be useful to have test results integrated to Semaphore UI, as it makes debugging failing tests easier (for example it would help me in my previous task with test mock api updates)

**Comment by ioanmo226** [comment]
Ok
