### ISSUE TITLE
stop using initialLegacySubmit

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4609]
should first do #4610 and #4607

we're removing method `initialLegacySubmit` as follows:

## in `keyserver.ts` `submitPublicKeyHandler`

 you can instead use `submitPrimaryEmailPubkey` with id_token if this is a primary email that is being updated, or `replacePubkey` for aliases.

## rename client configuration 

`useLegacyAttesterSubmit` to `setupEnsureImportedPrvMatchLdapPub` and rename `USE_LEGACY_ATTESTER_SUBMIT` to `SETUP_ENSURE_IMPORTED_PRV_MATCH_LDAP_PUB`

##  in `setup.ts` `submitPubkeys`, on top

instead of `initialLegacySubmit` use `Attester.doLookupLdap` without specifying server. 
 - If there is no result, show warning modal `Your organization requires public keys to be present on company LDAP server, but no public key was found. Please ask your internal help desk.`
 - If you did get back a public key,  compare the received public keys primary fingerprints to the primary fingerprint of the private key that the extension is being set up with. If at least one primary fingerprint of the prvs matches at least one privmary fingerprint of the received pubkeys, do nothing else. If there is no intersection, show a warning modal with `Imported private key with ids {prv.map(prv => prv.id).join(', ')} does not match public keys on company LDAP server with ids {pubs.map(pub => pub.id).join(', ')}. Please ask your help desk.` 

## in `setup.ts` `submitPubkeys`, for aliases

where aliases are being submitted on the bottom, use `replacePubkey`

**Comment by ioanmo226** [comment]
@tomholub 
This doesn't make sense to me. I wonder why we need to show warning modal instead of error message with retry button like below.
If we show warning modal, does this mean user can continue setup and can use app normally? (I suppose we should not let user finish setup  & do not allow to use app) in this case.
>  there is no result, show warning modal `Your organization requires..`

![image](https://user-images.githubusercontent.com/77344191/191329905-4cc1d3f1-e528-4f7e-b4dc-074ccb5b7ce2.png)

**Comment by tomholub** [comment]
I made a mistake in issue definition. Yes, that should be a hard stop with a retry, not something user can click away.
