### ISSUE TITLE
More careful reading keys from backup

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#4619]
I don't like the idea of concatenating (possibly broken) keys before parsing (reading) them here:
https://github.com/FlowCrypt/flowcrypt-browser/blob/d0fb456b707a0c3ba3f9e8fe1f1d96d0dd1cc3fb/extension/js/common/api/email-provider/gmail/gmail.ts#L350
Need to rewrite this part more carefully (and test the edge cases)

**Comment by tomholub** [comment]
I'll close this as I think it won't make a big difference
