### ISSUE TITLE
responding with plain message is not possible when using triple dot

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4621]
### This works:

1) open encrypted message
2) click default gmail reply icon above

![image](https://user-images.githubusercontent.com/6306961/185987560-a6dacea7-7f7e-4ed2-aebc-426786a7416a.png)

3) I can write a plain reply, and also get a handy warning

![image](https://user-images.githubusercontent.com/6306961/185987845-959555e9-803b-4e28-b4ff-c9c8d95b0a8d.png)

### this doesn't work

1) open encrypted message
2) click more -> reply (plain)

![image](https://user-images.githubusercontent.com/6306961/185987743-bd13c145-c912-4929-9634-1fb7853265c1.png)

3) gmail reply box shows
4) it gets replaced by encrypted reply box

------------------

The second case should work same as the first one. I'm unsure why is there any difference.

**Comment by tomholub** [comment]
@ioanmo226 after current issue please have a look. Thanks!

**Comment by ioanmo226** [comment]
@tomholub In master branch, when I click `switch to encrypted reply`, it replaces reply view with view(with 3 buttons)
Is this correct behavior?
I think it should replace with secure reply box.

![chrome-capture-2022-7-23 (2)](https://user-images.githubusercontent.com/77344191/186183833-291596ce-ffc6-4fc7-a081-93581d24589f.gif)

**Comment by tomholub** [comment]
Alternative options would be to not care and always choose "reply" for that red banner, or give two options right in that red banner. In either case, I think better left for another issue.

**Comment by ioanmo226** [comment]
But bad thing is that after user clicks `switch to encrypted reply`, gmail reply button (both `default gmail reply icon above` and `more -> reply`) button doesn't work at all.
> It's not the worst - at least it still gives the user a chance to choose "reply" or "forward"

I agree
>  I think better left for another issue.
