### ISSUE TITLE
BrowserMsg pgpHashChallengeAnswer can be removed

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4626]
this method

```ts
  public static sha256UtfStr = async (string: string) => {
    return opgp.util.Uint8Array_to_hex(await opgp.crypto.hash.digest(opgp.enums.hash.sha256, Buf.fromUtfStr(string)));
  };
```

can be updated to use `window.crypto.subtle.digest('SHA-256', ...));` instead of `hash.sha256`, and `Buf.toHexStr` instead of `Uint8Array_to_hex`.

Then all `BrowserMsg` parts related to `pgpHashChallengeAnswer` can be removed, and instead of making this call through background page, code cal just call `PgpHash.challengeAnswer` directly. Which will no longer have `opgp` dependency.

**Comment by ioanmo226** [comment]
@tomholub 
Hmmm.... I don't see any `pgpHashChallengeAnswer` calls.
I can only see `pgpHashChallengeAnswer` listeners but can't see any triggers in project.
Could you confirm if it has been removed or what?

**Comment by tomholub** [comment]
these listeners can be removed. 

does nothing call these listeners?

**Comment by ioanmo226** [comment]
I couldn't find any.

**Comment by tomholub** [comment]
You're right. Just remove the listeners then 👍
