### ISSUE TITLE
Re-enter recipient issue

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4628]
Here are steps to reproduce

1. Enter invalid recipient (something like aaa)
2. Delete it by pressing backspace(pressing backspace twice works fine)
3. Enter valid recipient
4. You will see `Re-enter recipient` button even though all recipients are valid

![chrome-capture-2022-7-23](https://user-images.githubusercontent.com/77344191/186078540-0e0fbe47-62a8-41b5-b042-bd3b076bc1cf.gif)

**Comment by tomholub** [comment]
Thanks! That's an annoying bug
