### ISSUE TITLE
[important] Setting up browser extension cannot be finished if the option to backup private key is selected

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4650]
Description:
We received feedback from a few users that they are unable to proceed after creating a new key. I have confirmed this problem when creating a new key and it occurs when I'm about to submit the key on the attester with https://flowcrypt.com/attester/pub/email@example.com

Steps to reproduce:

1. install FlowCrypt extension on your browser 
2. signin with Gmail and create a new key 
3. make sure the option to create a private key backup (keyserver) is checked 
4. click on save and the following screen occurs (email and token have been redacted):

![image](https://user-images.githubusercontent.com/46025304/187138354-312e1a87-2c21-4cbb-9775-4e959771c3c8.png)

The current workaround so far is to uncheck the option to save a backup on user inbox

references: 
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQJhCdgwCRZqxkGSxhxmSjWXr
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQJhCddgzKpXdczKnhtzWPvKk
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQJkTNtXlpljClkjVfRfWFmpq
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQJkTrBtdkLpXrxlfNbfPfdfl

**Comment by martgil** [comment]
The corresponding error says "Error happened: TypeError: MimeBuilder is not a constructor" when trying to create a backup private key.

Additionally, I noticed that this happens (1) when the option to backup the private key is selected (2) backing up private key like the one on the screenshot
<img width="1440" alt="Screen Shot 2022-08-29 at 5 13 09 PM" src="https://user-images.githubusercontent.com/46025304/187167257-4432e537-02a7-48db-9f82-76bc06b9db31.png">

Backing up private key from FlowCrypt settings -> Dashboard -> backup -> backup my keys -> backup as email works very well.

**Comment by martgil** [comment]
@tomholub just making you aware in the meantime.

**Comment by tomholub** [comment]
I'll take a look, thank you for alerting me

**Comment by tomholub** [comment]
submitted an update, will take a few days to be reviewed by Google, unfortunately

**Comment by martgil** [comment]
Thank you for the hotfix, sir. I have also checked this from the master branch and this fixed the issue. Thanks again!

**Comment by tomholub** [comment]
> > make sure the option to create a private key backup (keyserver) is checked
> 
> there isn't any such option, could you take screenshot of what you meant?

@martgil for clarity - could you please confirm about the above?

**Comment by martgil** [comment]
Sorry, I was referring to the option where users could uncheck the option of saving the backup private key onto their inbox which is `checked` by default.

**Comment by tomholub** [comment]
Got it
