### ISSUE TITLE
Visual glitch opening passphrase dialog

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#4681]
I noticed that the default `<h1>` text "Enter FlowCrypt pass phrase to read encrypted email" is visible for a second,
and then gets replaced with a correct text based on query arguments.
https://github.com/FlowCrypt/flowcrypt-browser/blob/754e0b6d7a453b7ca0fd12672fa806b7d32298e7/extension/chrome/elements/passphrase.htm#L21

(I saw this effect with `update_key` tests, perhaps, the same effect happens for all the other cases)
https://github.com/FlowCrypt/flowcrypt-browser/blob/754e0b6d7a453b7ca0fd12672fa806b7d32298e7/extension/chrome/elements/passphrase.ts#L79

I think it'd be good to display the correct text at once.

**Comment by tomholub** [comment]
Yes, the text could start out empty, and be filled to its desired value instead of how the value is prefilled now.
