### ISSUE TITLE
OAuth signin shows a warning about using unsupported oauth flows

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4685]
Description:
Precaution info from google was shown telling that the browser extension should stop using the unsupported OAuth flow and suggests migrating to a supported one.

<img width="569" alt="Screen Shot 2022-09-14 at 9 47 26 AM" src="https://user-images.githubusercontent.com/46025304/190040508-f48338e4-dab7-451b-947f-c76de865381c.png">

Steps to reproduce:
1. Install the latest version of FlowCrypt browser extension at https://flowcrypt.com
2. Try to sign into the app and observe the Oauth signing-in window.

Link to the migration guide: https://developers.google.com/identity/protocols/oauth2/resources/oob-migration

References:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQSSSJkbnPhnxmhTWnmhXPsWW
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQSSScNvpZVnsjthQcbswngCQ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQSSSljDtZLgDrJVnBzkZLlbb

**Comment by martgil** [comment]
@tomholub just bringing this to your attention. Thanks!

**Comment by ioanmo226** [comment]
@martgil This is already addressed in https://github.com/FlowCrypt/flowcrypt-browser/issues/2649 and will be fixed after we release new version. Thanks.

**Comment by martgil** [comment]
@ioanmo226 oh - thanks for informing me :). Also, I have a quick question. I'm honestly not aware of whether the client_secret's value should be exposed or not. Though I found a few on some other apps. Was gitguardian's detection about being private info a false positive?

**Comment by ioanmo226** [comment]
> Per https://stackoverflow.com/questions/7274554/why-google-native-oauth2-flow-require-client-secret it's not considered a secret for client apps, since that's impossible. So you can add it to code.
> 
> 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



https://github.com/FlowCrypt/flowcrypt-browser/issues/2649#issuecomment-1232088815

**Comment by martgil** [comment]
@ioanmo226 Thank you for answering my question :)

**Comment by ioanmo226** [comment]
@tomholub I think it would be better to deploy this OOB migration ASAP?

**Comment by tomholub** [comment]
Agree, I'll have a look at #4594 and see if I can get it resolved, hopefully today, possibly tomorrow.

**Comment by ioanmo226** [comment]
@tomholub I think we can close this issue?

**Comment by tomholub** [comment]
yup

**Comment by tomholub** [comment]
I'll be releasing the second update today
