### ISSUE TITLE
Drop backend uuid mechanism

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4686]
Current mechnism on backend is to send id_token along with uuid, and next time only use email+uuid when sending requests

I would instead like all authenticated requests to flowcrypt.com/api to use id_token, like we do with requests to EnterpriseServer (FES)

I'm not entirely sure if the backend code supports this yet, we'll find out

This means we are dropping support for `uuid` tokens completely, and can also remove storage code for them. But we don't necessarily need to do a migration to remove them from storage, since their support will be removed from backend too, and they'll become useless in either case.

**Comment by tomholub** [comment]
wip on backend https://github.com/FlowCrypt/flowcrypt-backend/pull/456

**Comment by tomholub** [comment]
Backend is ready and can accept id_token as authentication on all requests now. Setting for a future milestone.

**Comment by tomholub** [comment]
Also should drop `uuid` mechanism from iOS and Android, and use id_token there too.

**Comment by ioanmo226** [comment]
@tomholub Does this mean we need to remove this functionality and remove test assigned to this one?

![image](https://user-images.githubusercontent.com/77344191/195029290-a564c970-9cd7-448a-9590-1d7bd97b1bc0.png)

**Comment by tomholub** [comment]
Yes, these two buttons can be removed.

But the tests may need to be adjusted to use `Wipe Google access token` and `Wipe Google refresh token` instead, to also prompt authentication form. It depends on exactly what the tests are doing.

**Comment by ioanmo226** [comment]
This is already covered by those tests
1. `test re-auth after updating chrome extension`
2. `mail.google.com - success notif after setup, click hides it, does not re-appear + offers to reauth`

Do we still need to add separate test for this?
> But the tests may need to be adjusted to use Wipe Google access token and Wipe Google refresh token instead

**Comment by ioanmo226** [comment]
Ok, got it
