### ISSUE TITLE
Move live tests to mock test 

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4698]
Several live test can be moved to mock test.
Ex: `mail.google.com - setup prompt notif + hides when close clicked + reappears + setup link opens settings`, `mail.google.com/chat`

**Comment by ioanmo226** [comment]
@tomholub How about we make `gmail-mock.ts` in `test/source/tests` for mocked gmail test and run seperate instance in semaphoreci?
Or you prefer to put mocked gmail tests in `setup.ts` or somewhere like that?

**Comment by tomholub** [comment]
I'd keep putting them into existing categories / instances.

If one instance overgrows the other ones and takes much longer to run, that would be the time to consider splitting it, I think.
