### ISSUE TITLE
replies@flowcrypt.com oddity when replying to web portal message from browser extension

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4701]
To reproduce:
 - from enterprise account, email to someone with a web-portal message
 - reply back from web portal
 - reply from browser extension back to it

Actual: immediately after sending the reply, recipient will be rendered as `replies@flowcrypt.com`

Expected: it should render the actual emails that the reply was just sent to

@martgil please see if you can reproduce this, also on iOS and Android. If you notice this issue also on iOS and Android, please file appropriate issues there.

Implementation / fix will be done by others after the repro.

**Comment by martgil** [comment]
@tomholub I reproduced the issue you describe on the browser extension. Initially, the email address was set to the correct recipient but after a split seconds, the recipient address changed to replies@flowcrypt.com.

I also try to reproduce it on Android and iOS

**Comment by martgil** [comment]
the

**Comment by tomholub** [comment]
could you share a video of it?

**Comment by martgil** [comment]
Here it is:
https://user-images.githubusercontent.com/46025304/191687613-d532f4ff-cd22-47bc-8e4e-1dd8b1ad09a0.mov

**Comment by tomholub** [comment]
Ok, that is wrong
