### ISSUE TITLE
change test/welcome to welcome-message

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4710]
Also `attester/test/welcome` should become `attester/welcome-message` and it should include `Bearer id_token` auth header (not enforced yet but will eventually enforce)

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-android/issues/1984#issuecomment-1255197555_

**Comment by ioanmo226** [comment]
I can't find `attester/initial/welcome` endpoint but can find  `test/welcome`.
Is this correct?

**Comment by tomholub** [comment]
Yes, my typo.
