### ISSUE TITLE
Question: Why feedback sent by the extension not encrypted?

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4712]
@tomholub I assume it may be because of the ease of accessibility of the email. 

Other than that, will/should we consider encrypting feedback we receive from the extension? Options like 
using ECP https://flowcrypt.com/me/tom are readily available or sending encrypted email directly to our support email will do.

**Comment by tomholub** [comment]
A lot of times, people write us feedback because something is broken. There is a possibility that they could send you encrypted feedback, then we'd reply (which would be encrypted) which they wouldn't be able to read.
