### ISSUE TITLE
supposed encrypted + signed draft message becomes encrypted only when sending the email

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4727]
When composing a secure message that is encrypted + signed, I noticed that when the message is saved as a draft message, the draft message only became encrypted but not signed and this is unnoticed when the draft was sent using Gmail and not the dedicated `Encrypt, sign and send` button of the extension.

Steps to reproduce:
1. Compose an encrypted + signed secure message and wait till the message was saved automatically as a draft message.
2. Close the secure compose window and navigate to Drafts
3. Open the draft message (but do not open the message further using the extension)
4. Send the message (you can send the message to yourself for testing purposes)
5. Noticed that the message is encrypted but not signed though the draft message should be encrypted + signed. Also, as far as I know, we don't consider sending unsigned encrypted messages anymore. (Only, plain, signed, encrypted + signed)

**Comment by martgil** [comment]
@tomholub I'm unsure if it needs an improvement but if not, feel free to close the issue. Thank you!

**Comment by tomholub** [comment]
yes, this is expected behavior. At the moment, I don't intend to change it - it would be inconvenient, implementation wise and UX wise, to sign each saved draft.
