### ISSUE TITLE
[Feature suggestion] Scheduled email sending 

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4728]
A user shows some interest in scheduled email sending using FlowCrypt. 

We don't have that feature yet, so as a workaround, users can utilize Gmail's scheduled email sending feature, however, #4727 may bother them.

Here is how they can send a secure scheduled email:
1. Compose a draft message using FlowCrypt's secure compose. 
2. Close the secure compose window
3. Open the draft message (do not open the draft message further using the FlowCrypt extension)
4. From Gmail's native compose window, click the dropdown arrow beside the `send` button and choose `Schedule send`
5. Choose an appropriate date & time and set the schedule.

Reference: https://mail.google.com/mail/u/6/#inbox/FMfcgzGqQmSFCwFcXCdnKnvlBBZktsGg

**Comment by martgil** [comment]
@tomholub I can't see any issue related to it and I can't recall filing a related issue either, so I decided to write it here. Do you foresee the suggested feature being part of the extension somewhere in the future?

**Comment by tomholub** [comment]
Hello, thanks for asking - no plans at the moment for scheduled emails.
