### ISSUE TITLE
Oddity when replying to a multiple-recipient encrypted message 

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#4737]
When pressing "Secure Reply" button on this message https://mail.google.com/mail/u/0/#inbox/FMfcgzGqQvvQQTzfBdzFCTbrWRWjFJnL,
I can only see one of the recipients in `To:` field (the last one in the original message's `To:` list) -- glitch 1.
When I clicking on the recipient, the `To:` field control is loaded with the original message's sender email address in its place -- glitch 2.
When I trying to delete the recipient by clicking on the `x`, I'm getting this (glitch 3):
![image](https://user-images.githubusercontent.com/23335944/195918776-c283aabf-b5eb-4671-b5b8-633081d12c60.png)

And on clicking "Encrypt, Sign and Send" button, the reply is sent to the last recipient of the original message's `To:` list.

Expected behaviour (if "Secure Reply" means replying to the original sender only): The original sender's email address should appear in `To:` list.
Question: Should I be able to add more "To:", "Cc:" or "Bcc:" recipients or remove the original sender from the list?
Anyhow, there shouldn't be the "unexpected error" popup on trying to delete the original sender.

**Comment by tomholub** [comment]
> if "Secure Reply" means replying to the original sender only

I'm not entirely sure anymore if it means reply one or all. In either case, this ambiguity will be removed with https://github.com/FlowCrypt/flowcrypt-browser/issues/4496 - you could click reply first, which renders a box, and then you can still toggle if this means reply all/reply/forward which will rework the recipients.

>  Question: Should I be able to add more "To:", "Cc:" or "Bcc:" recipients or remove the original sender from the list?

Yes - Gmail allows it, we should too.

This could be looked into either separately, or as a part of #4496 which I hope will be soon.

----------

On which mailbox was that? The `0` signifies the first logged in user, doesn't make it clear which one.

**Comment by rrrooommmaaa** [comment]
> On which mailbox was that? The `0` signifies the first logged in user, doesn't make it clear which one.

This message was in my own personal mailbox. This is the message from you sent to multiple recipients.

**Comment by Sarisura** [comment]
G kTelefonumdan gönderildi-------- Orijinal mesaj --------Gönderici: Roman ***@***.***>Tarih: 15 Eki 2022 Cmt 10:11Al: FlowCrypt/flowcrypt-browser ***@***.***>Cc: Subscribed ***@***.***>Konu: Re: [FlowCrypt/flowcrypt-browser] Oddity when replying to a multiple-recipient encrypted message  (Issue #4737)

On which mailbox was that? The 0 signifies the first logged in user, doesn't make it clear which one.

This message was in my own personal mailbox. This is the message from you sent to multiple recipients.
