### ISSUE TITLE
Cover `accountUpdate` with tests

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#4738]
Looks like `accountUpdate` is only used when updating `default_message_expire`? It'd be good to have a unit test for this.

_Originally posted by @rrrooommmaaa in https://github.com/FlowCrypt/flowcrypt-browser/pull/4733#discussion_r996416677_

**Comment by tomholub** [comment]
following https://github.com/FlowCrypt/flowcrypt-browser/issues/4890 it will no longer be used, and the ui to modify expiration will be removed.
