### ISSUE TITLE
Chrome-based Opera Browser don't work with FlowCrypt extension

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4743]
I assume Opera browser (chrome-based) is not directly supported by FlowCrypt. Hence, a user kindly tried to install it on an opera browser and reported to us that it doesn't work right after the sign process gets stucked showing the /robots.txt from google.com.

![image](https://user-images.githubusercontent.com/46025304/196611027-44f957db-a2d0-410e-b5f5-329c57974c7f.png)

I just cared to share this here just in case we are interested in supporting wide range of web browser in the future.

**Comment by martgil** [comment]
Overall Interested users:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRQGRMMZPlfZqHgvHMNSWzFDs
https://mail.google.com/mail/u/human@flowcrypt.com/#archive/FMfcgzGqQwDMRwfKhJNhbPFsJplCPVrN

**Comment by martgil** [comment]
I've investigated this issue and it happens that, the `www.google.com/robots.txt` was unable to replace by the FlowCrypt extension and the user stucks into the robots.txt page.

As a temporary solution, they could inspect element the robots.txt page as the last step of authentication then paste the onliner javascript redirect code into the console.

`const redirUrl = 'chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/oauth2.htm';location.href = redirUrl+location.search;window.close()`

**Comment by martgil** [comment]
**UPDATE:**

User wouldn't need to perform pasting javascript code above. They just need to enable the option to "Allow access to page results" that can be enabled in Opera Extension settings placed on the bottom-left corner of the Opera browser -> choose Extension.

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/113dc54b-80e5-4408-a198-a948b0bf169a)

**Comment by martgil** [comment]
Hi @sosnovsky, cc: @tomholub,

Just making you aware of this solution, in case you bump into it in the future.

**Comment by sosnovsky** [comment]
Hi @martgil, thanks for finding working solution!

I think it'll be useful to add it to our Downloads page at https://flowcrypt.com/download
Let's remove `Brave extension` link from this page, and instead add new section `Other browsers` with text like this:

> Other browsers
>
> FlowCrypt extension can be used in Brave and Opera browsers by installing it from [Chrome extension webstore](https://chrome.google.com/webstore/detail/cryptup-encrypt-gmail-wit/bnjglocicdkmhmoohhfkfkbbkejdhdgc).
> For Opera browser you should also enable "Allow access to search page results" option in FlowCrypt extension settings.

**Comment by martgil** [comment]
Thanks for your suggestion @sosnovsky I'll be updating the FlowCrypt Downloads page. Thanks!
