### ISSUE TITLE
remote images cannot be loaded from the extension

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4759]
We allow loading remote images when a user clicks the "show remote image":
<img width="366" alt="image" src="https://user-images.githubusercontent.com/46025304/197954200-9ef4e5e5-81ac-458c-be6c-8fa46c7e49dd.png">

However, this produces a broken image because our CSP for the browser extension is strictly set only to data:,blob:, or https://*.googleusercontent.com - https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/manifest.json#L95

<img width="910" alt="Screen Shot 2022-10-26 at 2 28 16 PM" src="https://user-images.githubusercontent.com/46025304/197955047-ba8a97ad-1703-474b-bdc2-fd46284db67f.png">

<img width="830" alt="Screen Shot 2022-10-26 at 2 28 02 PM" src="https://user-images.githubusercontent.com/46025304/197954516-9c5978bd-89b3-4022-9a96-740153c4212e.png">

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRGdFDHLvCpGmwBhQnPtcbtdG

**Comment by ioanmo226** [comment]
@tomholub Not sure how we can fix this issue.
I thin we can't add wildcard as it might allow attackers to attack.

**Comment by martgil** [comment]
Sure @ioanmo226 I can generate this email for you in a sec.

**Comment by tomholub** [comment]
In which case, it's less urgent, moving milestone.

**Comment by ioanmo226** [comment]
@martgil @tomholub 
For above case/email, we currently show `aaaa [show image(remote)](button)`.
Maybe we can
1. Show `aaaa [Remote images are blocked due to security](plain text)`?  (Tell me which message I have to show in square brackets)
2. show `Remote images are blocked due to security` message when user clicks `show image(remote)` button?

I prefer 1st option though.
Let me know your thoughts.

> I think we should, as a part of this issue, make it clearer to the user that remote images are disabled for security.

**Comment by tomholub** [comment]
1st option is better, suggested text is good.

Always better to show to user the problem before they take the action.

If we made the user take an action and then display the error afterwards, it makes the user feel stupid and/or frustrated.

**Comment by ioanmo226** [comment]
I totally agree

**Comment by martgil** [comment]
Hello @ioanmo226 - sorry, I didn't inform you about the sample email I sent on your email

you may search for this email subject - test message for flowcrypt-browser/issues/4759. 

For the test, I'll send another one for the compatibility account.

To generate such message, you will need to have the FlowCrypt extension installed on a Firefox browser. there we support Rich text document where you can edit the contenteditable div aka the secure compose window's dom and place it there the custom img element with src pointing to some server where our CSP disallows.

**Comment by ioanmo226** [comment]
Thank you @martgil

**Comment by martgil** [comment]
Thank you, too - here is the test email for the compatibility account: https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/FMfcgzGrbbtFbjKfkckqcwqQBJlVGPld

**Comment by martgil** [comment]
> I prefer 1st option though.
Let me know your thoughts.

I would opt for the first option, it seems to follow the traditional inline warning.

**Comment by kubadoki** [comment]
Was not sure where to post this - but on IOS Mobile Flowcrypt App there is no button for "Show Remote Images" - it just says in text "Remote content blocked for your privacy" and I cant find any settings to allow loading of remote images (which in case of some email I am getting is essential to approve security requests (they come as image with link and flowcrypt mobile does not load neither the image nor the link - while in gmail on desktop it loads images and links fine)

**Comment by sosnovsky** [comment]
@kubadoki thanks for your feedback! I filed an issue for this case in iOS app repository - https://github.com/FlowCrypt/flowcrypt-ios/issues/2414

**Comment by kubadoki** [comment]
> @kubadoki thanks for your feedback! I filed an issue for this case in iOS app repository - [FlowCrypt/flowcrypt-ios#2414](https://github.com/FlowCrypt/flowcrypt-ios/issues/2414)

Awesome thanks so much!!
