### ISSUE TITLE
customer deployment requests

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4769]
- [x] implement **31st October to 4th November** - #4703 
 - [x] #4846
 - [x] #4771

**Comment by ioanmo226** [comment]
Could you explain more about `missing images on signed messages` issue?

**Comment by tomholub** [comment]
Thanks for reminding me, I'll check with customer again, and then possibly assign to @sosnovsky

**Comment by ioanmo226** [comment]
Does this issue still need to be open?
Perhaps we can close this issue?

**Comment by tomholub** [comment]
yup
