### ISSUE TITLE
pressing enter in passphrase dialogs -> click ok|next btn

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#477]
Find all pass phrase inputs by searching for `Ui.passphraseToggle`

**Comment by mondo989** [comment]
@tomholub  Still advocating for 'CMD+Return' to send an email (similar to gmail) 
(Not really a big deal)

**Comment by tomholub** [comment]
We have one for that one too #183

**Comment by tomholub** [comment]
More details in #770

**Comment by tomholub** [comment]
I will still be testing before closing this

**Comment by tomholub** [comment]
Works well, thanks!
