### ISSUE TITLE
better ux for disabled password messages: December/January

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4771]
I'd like to add a client configuration flag `DISABLE_FLOWCRYPT_HOSTED_PASSWORD_MESSAGES`.

When present, and recipients are missing a public key, and the user is using flowcrypt.com/api (not FES), it will not give the user option to enter a message password, as if that functionality didn't exist.

need to then check:
 - that the wording / user instructions in that situation still make sense
 - that what happens after clicking the send button (even though missing pubkey makes sense)

in neither case should it be prompting the user to add any password, just focus on public keys

(standard behavior is to prompt for public keys OR a password)

**Comment by ioanmo226** [comment]
@tomholub I have a question.
Let's say I entered two recipients (recipient1 which has pub key and recipient 2 which doesn't have pubkey)
In this case, What should we should to user when user clicks send button?
I'm thinking of 3 options.
1. Show user `Public key for ${recipient names} are missing. Please add their public keys` error modal.
2. Send plain message to all recipients (whether or not they have public key or not)
3. Send plain message to recipients who don't have public key and encrypted message to recipients who have public key)

I think we need to remove this block from compose ui though when DISABLE_FLOWCRYPT_HOSTED_PASSWORD_MESSAGES is present.
![image](https://user-images.githubusercontent.com/77344191/205635373-9cb7f30d-8650-4810-a72d-ce5a415860cd.png)

**Comment by tomholub** [comment]
option 1

yes, you'll want to remove the password text

**Comment by ioanmo226** [comment]
This means user can't send message (both encrypted/plain message) when there are recipient(s) who don't have pubkeys?

> option 1

**Comment by tomholub** [comment]
if the sender had chosen a plain message, it would have never asked for public keys or password to begin with, already now. so that usecase is covered.

**Comment by ioanmo226** [comment]
Yeah, 
I meant i think we need to inform user that they can send plain message when recipient keys are missing.
Like show this error modal
`Public key for ${recipient names} are missing. Please add their public keys or send them plain messages by chaning below send option`

**Comment by ioanmo226** [comment]
When I first used extension, I didn't know I could send plain message (by changing send button option).

**Comment by tomholub** [comment]
it's possibly disabled on enterprise version, or in some other circumstances. but when enabled, and selected, user is not asked for keys.

**Comment by ioanmo226** [comment]
You mean you don't agree to inform user they can also send plain message (when error occurs when recipient pub keys are missing)
Please provide me text for error modal message though

**Comment by tomholub** [comment]
i think there is no point informing them they can send a plain message. they could use standard gmail for that, and you would have to only inform them whenever plain messages are enabled, which is a hassle. 

for the modal, you already suggested it above, i have nothing against it.
