### ISSUE TITLE
Key import issue

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4782]
![image](https://user-images.githubusercontent.com/77344191/200562577-b2b3c9f3-4d04-40ad-93a3-a60ae8856b3f.png)

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRQJkGxhDhWksnJrlwpzgKTsx

**Comment by ioanmo226** [comment]
@martgil I guess you received this message. Could you share human email link here for further reference?

**Comment by martgil** [comment]
Hello @ioanmo226 yes - no problem. By the way, have you already received the private key from the customer?

**Comment by ioanmo226** [comment]
Yes.

**Comment by ioanmo226** [comment]
Not sure this task priority though. Can you confirm @martgil?

**Comment by martgil** [comment]
Usually, @tomholub sets a dedicated prioritization for these. If you have the private key and passphrase, I can take over this so you can focus on your tasks in the meantime. You may share the credentials via email and I'll try to analyze the key first.

**Comment by ioanmo226** [comment]
Thank you.
Just sent email. Let me know if it works.

**Comment by tomholub** [comment]
priority high. it's an important customer

i suspect Roman will have to take a look. i think he is the only one who may have a chance to actually fix it, or be able to clearly see what is wrong compared to similar keys the extension can normally fix

**Comment by martgil** [comment]
@tomholub I take the first step to import the key with `gpg` - that fixes the format of the key and allows me to import/use the key with the FlowCrypt extension.

However, I'm now getting a "missing private key parameters" -- which is caused by keys exported via gpg's "--export-secret-subkeys" flag or the secret key is missing.

```
(1) Primary keys found: 1  
(2) ----- Testing key 0 -----  
(3) PK 0 > Key type: openpgp  
(4) PK 0 > Is Private?: [-] true  
(5) PK 0 > User id 0: User <redacted@domain.tld>  
(6) PK 0 > User id 1: redacted@domain.tld <redacted@domain.tld>  
(7) PK 0 > Primary User: User <redacted@domain.tld>  
(8) PK 0 > Fingerprint: redacted  
(9) PK 0 > Subkeys: [-] 1  
(10) PK 0 > Primary key algo: [-] rsa_encrypt_sign  
(11) PK 0 > Usage flags: [-] [sign_data, certify_keys]  
(12) PK 0 > key decrypt: [-] success  
(13) PK 0 > isFullyDecrypted: [-] true  
(14) PK 0 > isFullyEncrypted: [-] false  
(15) PK 0 > Primary key verify: [-] valid  
(16) PK 0 > Primary key creation?: [-] 1667901929 or 2022-11-08T10:05:29.000Z  
(17) PK 0 > Primary key expiration?: [-] 1730973929 or 2024-11-07T10:05:29.000Z  
(18) PK 0 > Encrypt/Decrypt test: Encryption with key was successful:   
(19) PK 0 > Encrypt/Decrypt test: Decryption with key succeeded:   
(20) PK 0 > Sign/Verify test: [-] Exception: Error: Missing private key parameters  
(21) PK 0 > SK 0 > LongId: [-] EE36283F1BBB32B3  
(22) PK 0 > SK 0 > Created: [-] 1667901932 or 2022-11-08T10:05:32.000Z  
(23) PK 0 > SK 0 > Algo: [-] rsa_encrypt_sign  
(24) PK 0 > SK 0 > Usage flags: [-] [encrypt_communication, encrypt_storage]  
(25) PK 0 > SK 0 > Verify: [-] OK  
(26) PK 0 > SK 0 > Subkey tag: [-] 7  
(27) PK 0 > SK 0 > Subkey getBitSize: [-] 4096  
(28) PK 0 > SK 0 > Subkey decrypted: [-] true  
(29) PK 0 > SK 0 > Binding signature length: [-] 1  
(30) PK 0 > SK 0 > SIG 0 > Key flags: [-] 12,0,0,0  
(31) PK 0 > SK 0 > SIG 0 > Tag: [-] 2  
(32) PK 0 > SK 0 > SIG 0 > Version: [-] 4  
(33) PK 0 > SK 0 > SIG 0 > Public key algorithm: [-] 1  
(34) PK 0 > SK 0 > SIG 0 > Sig creation time: [-] 1667901936 or 2022-11-08T10:05:36.000Z  
(35) PK 0 > SK 0 > SIG 0 > Sig expiration time: [-] 1667901932 + 63115200 seconds, which is: 1731017132 or 2024-11-07T22:05:32.000Z  
(36) PK 0 > SK 0 > SIG 0 > Verified: [-] true  
(37) PK 0 > expiration: [-] 1730973929000  
(38) PK 0 > internal dateBeforeExpiration: [-] undefined  
(39) PK 0 > internal usableForEncryptionButExpired: [-] false  
(40) PK 0 > internal usableForSigningButExpired: [-] false  
```

Reference:
https://www.reddit.com/r/ProtonMail/comments/f4ru2o/missing_private_key_parameters_when_importing_gpg/

**Comment by tomholub** [comment]
@rrrooommmaaa  please take a look

ioan please forward the sample to him

**Comment by rrrooommmaaa** [comment]
I noticed that it was a freshly-created key.
This behavior may be possible if the key `created` field is in future.
So if we create a key on one computer and immediately send it to another computer, and we have a messy time zone setup on one or both of them, we may get UTC key creation time in future.
I managed to reproduce this situation by setting my local machine's time to November 7-- it leads to an exception in OpenPGP's `verifyPrimaryKey` called by `getEncryptionKey` etc. The exception says `Primary key is expired` and the only way to circumvent this is the way we circumvent the expired key situation, but in this case, we need to pass the date parameter to be LATER than the key's `created` field and its signatures (they usually hold a timestamp a bit later than the key's).
How should we react on this issue? Should we diagnose and display an error saying something like "You're trying to import a key with a signature UTC timestamp set in future"?

**Comment by tomholub** [comment]
@ioanmo226 @martgil if you have tried to import the key originally and got error, could you try to import the same unmodified key now and see if you still got error?

It seems Roman imported it successfully now, that would confirm a likely time issue.

**Comment by martgil** [comment]
@tomholub I imported the unmodified key and it works on my setup as well.

**Comment by ioanmo226** [comment]
I got below screen when trying to import in setup screen and after i select expiration & import, it works fine.
![image](https://user-images.githubusercontent.com/77344191/201079108-fef3bda6-833b-47de-ad68-4e68a68d69e8.png)

**Comment by tomholub** [comment]
The issue appears resolved, with most likely culprit being the time difference between the server that created the key, and the client that attempted to import it.

**Comment by tomholub** [comment]
We should continue in #4556 to make this fully functional for the customer.
