### ISSUE TITLE
releases 8.3.9 + 8.4.0 + 8.4.1

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4784]
8.3.9

 - [ ] release and test firefox (can skip)
 - [x] consumer release
 - [x] enterprise release + email
 - [x] email about consumer release

8.4.0

 - [ ] release and test firefox
 - [x] release commit
 - [x] pull on server
 - [x] npm install
 - [x] build on server
 - [x] upload consumer to s3
 - [x] upload enterprise to s3
 - [x] consumer release
 - [ ] enterprise release + email (can skip)
 - [x] email about consumer release

8.4.1

 - [x] npm install
 - [x] pull on server
 - [x] build on server
 - [x] release commit
 - [x] release and test firefox
 - [ ] upload consumer to s3
 - [x] upload enterprise to s3
 - [x] consumer release
 - [x] enterprise release + email (can skip)
 - [x] email about consumer release

**Comment by martgil** [comment]
Good morning @tomholub!  Users that are highly dependent on using PW-protected messages get affected by https://github.com/FlowCrypt/flowcrypt-browser/issues/4792. 

Do you have an estimated date when we can release our next update for the browser extension? 

Thank you!

**Comment by tomholub** [comment]
today

**Comment by tomholub** [comment]
but google may take a day or two to verify

**Comment by martgil** [comment]
I'm relieved user wouldn't have to wait too long. Thank you!

**Comment by tomholub** [comment]
released

**Comment by martgil** [comment]
Thank you so much!
