### ISSUE TITLE
Google Login Advanced protection issue

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4788]
User reported this issue.
Waiting for more details.

![image](https://user-images.githubusercontent.com/77344191/200999890-cda43fc8-b3c7-45e5-a013-411156326855.png)

**Comment by martgil** [comment]
@ioanmo226 Looks like we're not applying our apps to GAP at least not this year. 

References:

https://github.com/FlowCrypt/flowcrypt-browser/issues/1325
https://github.com/FlowCrypt/flowcrypt-android/issues/2041
