### ISSUE TITLE
Account reconnection pops-up when sending a password-protected messages

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4792]
Users cannot send a password-protected message as the account reconnection pops up every time the send button was clicked.

Steps to reproduce:
1. Compose a pw-protected message
2. Send the pw-protected message
3. Account reconnection message will pop up -- try to reconnect the account the refresh the webpage
4. repeat step 1 & 2 and the account reconnection message will appear again preventing the user from sending the pw-message.

Screenshot:
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/46025304/201815922-e6286369-ae3b-468b-b625-2f367eeaff59.png">

Reference: 
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZfCdPtdKFTbMWkkrtqctmJB
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZgLpSTPjSWsdNBfkVNbFBkC
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZjcnFHfBwGNKvMgznTbDbzh
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThfFwlRtBWnPxjgwGtNnD
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZjcdjsFWLMXvsktCbbWfkTq
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTqwFLQmngvRvzmQSJDtTr
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTqrhnNlNPxsrQLgzPrpss
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTqpQgpGPTHLwvKkBRQkDw
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThfGjjvFmZQKFMLdSLcQc
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThXXwcSkGkbHSfKDWPTlc
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTFVbFHqVgFZrgfkDxQHQZ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTNqpLZqSpNWkJtkfrsXWQ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTXDKgtnmwBxFxmVRVJsGZ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTXHjJGvfgJVrcrNMSkXNs
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhTXJpSpspRWgKhPnxblgkC
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZgLVZXWzjSGxZVWCXmRTMxJ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThQmNLnBBfjGBMxcRdVzq
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThRsPgHFpLpMbjWXgHrpm
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThVKgMksXVPkBJbPFStMV
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThcwGLWpVbMhgrZBJDvSJ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZhThWQhfthVjwgglQfWVCJG

**Comment by martgil** [comment]
Hi, sir @ioanmo226 - after pulling https://github.com/FlowCrypt/flowcrypt-browser/pull/4793 to my master branch, the problem still persists where I'm repeatedly asked to reconnect my account when sending a pwd message. Maybe I'm missing something here?

**Comment by ioanmo226** [comment]
@martgil Could you share reproduce steps? Maybe video would be even better.
I might not understand problem correctly.
I thought problem was this.
https://github.com/FlowCrypt/flowcrypt-browser/pull/4793#discussion_r1023929580

**Comment by martgil** [comment]
Here is the short video clip highlighting the issue:

https://user-images.githubusercontent.com/46025304/202358569-9418eb31-fff6-41f0-ace2-9f33de61cb75.mov

You may try to reconnect your account, refresh the webpage and notice it would repeatedly asks to connect your account.

**Comment by ioanmo226** [comment]
did you try to click `OK` button in `Please login with flowcrypt to continue` modal?
What happens after that? (I couldn't see that in video)

**Comment by ioanmo226** [comment]
Plus how/why do you get that `login with flowcrypt to continue` popup?
Did you remove google access/refresh token in experimental page? Or something else?

**Comment by martgil** [comment]
> did you try to click OK button in Please login with flowcrypt to continue modal?

Yes, I clicked the 'OK' button and the 'Reconnect Account' -- both of these triggers the Google Account login. I can complete the account reconnection but it just keeps asking. I have sent another video from your email.

> Plus how/why did you get that login with flowcrypt to continue popup?

Honestly, I'm not sure. I didn't remove my google access/refresh token. In my observation, It just only appears when sending a password-protected message.

**Comment by ioanmo226** [comment]
@martgil Thanks for your video(I received it and checked)
I now have a correct understanding of this issue.
When I tried with enterprise build(with my flowcrypt account) it works fine, but when I try with consumer build I see above error.

Can you confirm if this happens only in consumer build?
After that I'll fix it.

**Comment by martgil** [comment]
You're welcome, sir!

> When I tried with enterprise build(with my flowcrypt account) it works fine, but when I try with consumer build I see above error.

Yes, I can confirm it is working fine with enterprise build when using our corporate account. 

Although the issue still exists on the enterprise build when using a regular Gmail account. 

Maybe because the flow for sending a PW-protected message is different for an FES user rather than a free-to-use consumer? In short, it's not about the build type but if they're an FES user or not?

**Comment by ioanmo226** [comment]
Yeah, correct

**Comment by ioanmo226** [comment]
@martgil Just fixed above issue and I'm implementing live test now.
Do you know any test email which can be used to compose password-protected message? (which means which doesn't have pub key setup)

**Comment by ioanmo226** [comment]
@martgil Any new problems?

**Comment by martgil** [comment]
Nothing - just misclicked the button 😅.
