### ISSUE TITLE
api/message/upload called twice?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4801]
ok
> Let's rename it to getEmailFromIdTokenOrThrow as throwIf... doesn't suppose a return value

What do you mean called twice? was this api called twice somewhere?
> I noticed that the API endpoint of /api/message/upload is called twice successfully.

_Originally posted by @ioanmo226 in https://github.com/FlowCrypt/flowcrypt-browser/pull/4799#discussion_r1025566791_

**Comment by rrrooommmaaa** [comment]
A possible scenario:
1) PWD-encrypted message gets successfully uploaded, we have `UploadedMessageData`
2) sending message(s) to `gmail` fails (for whatever reason), but auto-retried (e.g. after reconnecting the account)
3) If possible, PWD-encrypted message shouldn't be re-uploaded, provided the inputs are the same (the sender, the recipients, the text etc.) -- which is probably true for auto-resends.
4) sending message(s) to `gmail` using either previous `UploadedMessageData` or the previously built messages -- but the point of concern here is the situation when the user "reconnected" to another gmail account if that's possible.

**Comment by ioanmo226** [comment]
https://github.com/FlowCrypt/flowcrypt-browser/pull/4799#discussion_r1034341064

**Comment by ioanmo226** [comment]
@rrrooommmaaa Please check above comment

**Comment by rrrooommmaaa** [comment]
> If we want to change like above way, we need to change compose send infra and need to change several tens of lines of codes and might make code messy.

If this makes code messy, then it's not worth it.
I was thinking about possible refactoring without increasing the overall code complexity.

**Comment by ioanmo226** [comment]
@rrrooommmaaa I think we can close this issue?

**Comment by rrrooommmaaa** [comment]
Why not just label it "not any time soon" or whatever label there is for that purpose?

**Comment by ioanmo226** [comment]
As I mentioned I think we need to re-call /message/upload after google re-auth(or similar event) because id_token is changed?
> Moreover, I think it's fine to call /message/upload twice because id_token will change after google re-auth(or something like that) and backend might need to return different data than previous one.

**Comment by rrrooommmaaa** [comment]
Do you mean the sender e-mail have changed?

**Comment by ioanmo226** [comment]
`/message/upload` will be called twice in below situation.
When google auth expired(we can simulate this by resetting access and refresh token in experiemental page) and user tries to send password protected message backend returns success result but sending gmail fails(our gmail mock also returns error) (unauthroized error).
We now show user `Please login with flowcrypt to continue` popup to let user re-auth.
After google re-auth, extension automatically tries to send message again and therefore `/message/upload` is called twice.

**Comment by tomholub** [comment]
Well noted also. Doesn't bother me too much at this point, filing for later.

**Comment by tomholub** [comment]
Actually, I'll close this. Worst case, in edge case, user has to wait a bit longer, and there will be one more message uploaded that will not be linked or used anywhere. It's not a problem.
