### ISSUE TITLE
Wrong oauth CSRF token 

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4803]
User reported below.

> I cannot log in to my Crypt Flow account and receive the following error:
> 
> Could not log in:
> Wrong oauth CSRF token. Please try again.
> 
> Can you assist in helping me reconnect Crypt Flow with my google account?
> 

Reference:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqRZjfMLxNqxBsfmMfrMwmTMxB

**Comment by ioanmo226** [comment]
Waiting more details from user.
@tomholub Could you adjust priority for this task?

**Comment by tomholub** [comment]
Is it affecting more people?

It should work if they close everything and try from the start again.

**Comment by ioanmo226** [comment]
I dunno, I'm even not sure how this issue could happen

**Comment by tomholub** [comment]
Probably a back button during setup or things like that.

**Comment by martgil** [comment]
Pardon me for interrupting your conversation.

> Is it affecting more people?

I received only one complaint so far. Probably it happens due to calling the OAuth window multiple times when a user tries to log back in from issue https://github.com/FlowCrypt/flowcrypt-browser/issues/4792.

**Comment by tomholub** [comment]
in that case, can advise user to retry on new version, then observe

**Comment by sosnovsky** [comment]
Looks like a single case, probably was fixed with https://github.com/FlowCrypt/flowcrypt-browser/issues/4792
