### ISSUE TITLE
Password messages' attachment can't be track from the senders perspective

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4812]
Description:
When a user sends a password-protected message with an attachment, sends it, and views the shipped email, the attached file(s) are not visible so the sender won't be able to track/review which attachments are already sent.

sender's perspective:
<img width="976" alt="image" src="https://user-images.githubusercontent.com/46025304/203885287-4b071a22-844a-4b83-b0fb-a2be9468d1d4.png">

receiver's perspective:
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/46025304/203885319-d898b3ef-64c3-42c1-977d-8fdfdf93ba71.png">

Reference:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGrbHsJsSXFvHchFWSGNwbGfbSJ

**Comment by ioanmo226** [comment]
Possible duplicate of this issue
https://github.com/FlowCrypt/flowcrypt-browser/issues/4702

**Comment by martgil** [comment]
Ah yes, it seems like. I'll try the replicate the issue using the #4773 branch to see if it fixes cases for the non-enterprise users.

**Comment by martgil** [comment]
yep duplicate of #4702 - it fixes case for non-fes users.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/46025304/203903263-5c93b2e7-3ba2-4557-bc83-e131bf8ff8b4.png">
