### ISSUE TITLE
app crashes when pasting a 1kB of pass phrase

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4835]
normally, the input fields such as password, text, etc are capable of accepting 1kB of text without suffering with performance -- however, the case is different when an event that does a complex process is bound to it.

During my testing when creating a new key and pasting a large character in the first pass phrase field, the function  `evalPasswordStrength` is bind into it to test the passphrase strength. In this phase,  the application starts to slow down or crash -- this happens quite similarly to ReDoS (Regex DoS). It only happens during setup since it's the only place where the passphrase strength is tested.

@tomholub @rrrooommmaaa I have some ideas of lowering the `maxlength` value to around 256 (tested and it didn't crash).

**Comment by tomholub** [comment]
256 is reasonable
