### ISSUE TITLE
promotional tiles for chrome web store + twitter

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#484]
here: https://chrome.google.com/webstore/category/apps
Small tile - 440x280
Large tile - 920x680
Marquee - 1400x560

and here: https://twitter.com/TryCryptUp - the background

**Comment by mondo989** [comment]
Oh cool, forgot you had a twitter for CryptUp.

**Comment by mondo989** [comment]
Figured this would be a fairly valuable, low hanging fruit. 

Do we have any taglines / quotes / ideas that we may want to have on the Twitter banner page?
And for the Chrome Webstore, I plan to pull some inspiration from pages like this...

![Uploading Screen Shot 2017-02-19 at 12.58.14 PM.png…]()

**Comment by tomholub** [comment]
The screen didn't upload

**Comment by mondo989** [comment]
<img width="837" alt="screen shot 2017-02-19 at 12 58 14 pm" src="https://cloud.githubusercontent.com/assets/3431871/23105742/861db154-f6a9-11e6-8957-01031cbda78b.png">


Just a point of reference, my wifi is in the dumps until tomorrow afternoon. (Tethering)

**Comment by tomholub** [comment]
I'm not sure that there needs to be any text in terms of the twitter account. You can design the background in a way that has a lot of space to add texts if needed/wanted.

I was thinking of some background that is somehow security-related and sends a message of "this is not just an abandoned twitter account made in 5 minutes". It doesn't need to send any other messages yet, I guess :)

Just see the pic - something like that for the twitter account, but doesn't even need text. If it should have text, then I'll come up with some

Let me observe some twitter accounts

Of course, promo tiles on web store will have to show what cryptup does

**Comment by tomholub** [comment]
When I google images for "privacy" or "security", all the images have locks or eyes in them, and they all look creepy, and I don't like any of them.

I'll try to look around more.

**Comment by tomholub** [comment]
Maybe an image with a very bad weather, storm etc and then on the bottom a bubble with a laptop in it where a sun is shining and nice green grass.

**Comment by mondo989** [comment]
I'll take a stab at it

**Comment by tomholub** [comment]
Here's a collage of what I mean but animated and a bit more thought through would be better :D

![image](https://cloud.githubusercontent.com/assets/6306961/23106623/0e703194-f6a5-11e6-8470-c4d41bfe2c48.png)

**Comment by tomholub** [comment]
We can maybe first try to make some sketches (super low res) to agree on a general idea

**Comment by mondo989** [comment]
Yeah that seems a bit intense, and there are a lot of things going on. 
I think a problem with this is, we might want to convey it in a certain way, but users may interpret this in many different ways, so maybe if we simplified it a bit?

(Hahaha, I do like the background photo, as I think I know where it came from lol. )

**Comment by mondo989** [comment]
Here's what I was thinking for the play store Marquee.

We may want to update the copy, it uses elements of the brand and a simple message. 
![playstore marquee 1400 x 560](https://cloud.githubusercontent.com/assets/3431871/23106883/e0746a5c-f6b9-11e6-895c-8c993e0d980d.png)

**Comment by tomholub** [comment]
Not bad at all for the marquee

The more I look at the logo font, the more I think it needs an update. But
the Marquee is great

For now we could just use this concept on Twitter as well

Also, the green part of the icon on a green background doesn't really stand
out, so we'd need to do something about that too.

--
Tom James Holub <http://holub.me/>

**Comment by tomholub** [comment]
Just testing

![image](https://cloud.githubusercontent.com/assets/6306961/23106932/bb9c3b5c-f6a9-11e6-8326-366e13f568a6.png)

**Comment by mondo989** [comment]
Cool. 

Yeah something short and sweet, which just conveys the brand (logo) and a simple message. 
Then when the users visit the playstore, they say woooow lol (Very good reviews).

As for the green standing out more, I can give it more of a shadow...

**Comment by mondo989** [comment]
Yeah, I think if we change it to black here, we will have to do it everywhere. 
As it will be a bit awkward if the branding changes midway.

I can play around with the background color a bit more and/or the drop shadow.

**Comment by tomholub** [comment]
Yeah see if changing the background will help.

It's also OK if brands have different versions of the logo for different settings, eg a gray-scale verstion, version for light background and version for dark background, as long as it still feels like the same brand in the end.

Ignore the colors below, just testing the font

![image](https://cloud.githubusercontent.com/assets/6306961/23106985/813c398e-f6aa-11e6-9a8c-f1e1cedac644.png)

**Comment by tomholub** [comment]
Eg Coke is still Coke either way

![image](https://cloud.githubusercontent.com/assets/6306961/23107024/e7cf019a-f6aa-11e6-93d1-807084cfcca8.png)

But of course, keeping it consisted would be better if we can

How about a black background with gray grid? And original white+green logo

**Comment by mondo989** [comment]
I agree, and know exactly what you mean.  (i.e. Print/Web/etc.)

In a potential use case, if I am a first time user of the platform, it may raise trust issues if the branding changes mid way through, and since there is a decent amount of trust going into permissions/emails, I think it's worth the hassle to keep try and keep it the same, until the whole logo brand identity is finalized. (Just my 2 cents)

**Comment by mondo989** [comment]
Let me try the black background.
<img width="722" alt="screen shot 2017-02-19 at 4 06 43 pm" src="https://cloud.githubusercontent.com/assets/3431871/23107149/78ba3e38-f6bd-11e6-9bca-3d906d4fdc3f.png">

**Comment by mondo989** [comment]
<img width="720" alt="screen shot 2017-02-19 at 4 06 55 pm" src="https://cloud.githubusercontent.com/assets/3431871/23107152/8aa471cc-f6bd-11e6-92e8-009555b2ef95.png">

With a little more drop shadow

**Comment by tomholub** [comment]
Black looks awesome

**Comment by tomholub** [comment]
I think we have a winner

**Comment by mondo989** [comment]
If you like the black more, let me put a little more effort into polishing it a bit...

**Comment by mondo989** [comment]
![playstore black marquee 1400 x 560](https://cloud.githubusercontent.com/assets/3431871/23107228/dccddeba-f6be-11e6-9358-9b1813f917d0.png)

Has a tad bit of a gradient that gets lighter around the logo.
Also played with the lock's opacity to not be as intense

**Comment by mondo989** [comment]
And all black

![playstore black-all marquee 1400 x 560](https://cloud.githubusercontent.com/assets/3431871/23107268/73be3676-f6bf-11e6-9eb0-c55b190e9b9c.png)

**Comment by tomholub** [comment]
I think I like the all black one the most

**Comment by tomholub** [comment]
Something really needs to be done to the font so it actually reads "crypt"

Example

![image](https://cloud.githubusercontent.com/assets/6306961/23107312/b072f86e-f6af-11e6-9396-8d84c063fa9a.png)

Later we can make a SVG of the logo ince it's finalized

**Comment by tomholub** [comment]
I think for now it should read "Easiest Gmail Encryption"

Once it supports Outlook and Yahoo, we can say "Easiest Email Encryption"

**Comment by mondo989** [comment]
Ok let me make these updates and post them here. 

"The Easiest Gmail Encryption for Chrome" 

Correct?

**Comment by tomholub** [comment]
I would probably remove Chrome, because they are already on the Chrome app store. Just "The Easiest Gmail Encryption"

Or without "The" would also do

**Comment by tomholub** [comment]
Some visual feedback when it's on the web store

![image](https://cloud.githubusercontent.com/assets/6306961/23107349/a4b8defc-f6b0-11e6-850f-9f83086deb15.png)

**Comment by mondo989** [comment]
Ok that's cool. 
(IMO the black just feels kind of dark, and evil lol) 

And for Twitter, I'm assuming we want to add the "for Chrome" back?
Since there is no context, like being at the app store.

**Comment by mondo989** [comment]
![playstore black marquee 1400 x 560](https://cloud.githubusercontent.com/assets/3431871/23107393/4f50ca4e-f6c2-11e6-86b2-3d5b98a56232.png)

**Comment by mondo989** [comment]
![twitter black cover 1500 x 500](https://cloud.githubusercontent.com/assets/3431871/23107405/7c0b17a6-f6c2-11e6-8792-61b5a32c9ba9.png)

**Comment by mondo989** [comment]
![playstore black marquee 1400 x 560](https://cloud.githubusercontent.com/assets/3431871/23107419/a6cf93cc-f6c2-11e6-85c2-8fa2f27dbe56.png)
Larger copy since only 3 words...

**Comment by tomholub** [comment]
I like it all

Maybe we can try some lighter Grey, since it's so.. dark :)

**Comment by tomholub** [comment]
you can see the twitter up
https://twitter.com/TryCryptUp

**Comment by mondo989** [comment]
Not bad, I feel like having the logo twice isn't the best...
I do like the UP, as it's being used in a few different places.

I wonder if we were to play around with a super simple 'explainer,' (for lack of better words
<img width="1002" alt="screen shot 2017-02-19 at 5 31 12 pm" src="https://cloud.githubusercontent.com/assets/3431871/23107789/4dc9c85e-f6c9-11e6-9cca-7a10340bc34f.png">
)

**Comment by tomholub** [comment]
I agree. Maybe just add black and white logos of chrome and Gmail to the left of the envelope, instead of the lock

**Comment by tomholub** [comment]
Just ideas. These but inverted

![image](https://cloud.githubusercontent.com/assets/6306961/23107847/7ab7c538-f6b9-11e6-87d6-c427e45c6877.png)
![image](https://cloud.githubusercontent.com/assets/6306961/23107854/9289922c-f6b9-11e6-9f73-88132555320d.png)

Then put a white lock into green circle on top of the email message

![image](https://cloud.githubusercontent.com/assets/6306961/23107862/ab1ba438-f6b9-11e6-81af-30bdf005c296.png)

**Comment by mondo989** [comment]
Hmm I like that idea...

**Comment by mondo989** [comment]
@tomholub  Looks like we've taken care of this in another repo.
Reopen if we need anything.

**Comment by tomholub** [comment]
That logo looked horrible! :)
