### ISSUE TITLE
Offer users to reconnect when id_token expires

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4844]
The following error occurs when a JWT token has expired when requesting for `api/account/get`. 

<img src=https://user-images.githubusercontent.com/46025304/208585324-da2e68e1-66f0-414b-aa6a-46d94be7af85.png width=55%>

I think one way to address this is by going to FlowCrypt settings -> resetting the account -> sign back in to refresh the id_token needed by the backend (not user friendly). 

The customer wonders if there's something we can do to simplify it. 

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGrbbxhKWXXkjFGnRLcMxlLkRQc

**Comment by martgil** [comment]
@tomholub just sharing it with you. thank you!

**Comment by tomholub** [comment]
hello, could you please describe user action steps leading up to this error?

**Comment by martgil** [comment]
Based on their initial description, it occurs when refreshing the browser - I think it is only the aftermath. I'll check it with them.

**Comment by tomholub** [comment]
it's not so interesting to know when the id token expires, it does every hour. my point is that die most user actions that follow that, we already have a refresh mechanism in place. 

so i want to know what steps did the user take directly prior to the error showing, and where exactly it showed. were they just opening an email? clicking secure compose? clicking send? in settings? etc

**Comment by martgil** [comment]
yes, sir. I have asked them the steps they have taken so that we can possibly replicate the issue.

**Comment by martgil** [comment]
@tomholub they have responded back to our question. 

> If I remember correctly it showed up when I was starting a new message. When I restarted the browser the error went away though.

> A user just reported this. He said all he did was refresh his normal inbox and it popped up. It went away whenever he started to secure compose.

I'll take a look if can replicate this by setting up a browser extension just before the id_token expires. I think that's the closest one -- since in the bug description the user is still able to use the FlowCrypt app. I think it's the backend's id_token that is expired and not the access token used by the extension.

**Comment by tomholub** [comment]
There is no id token stored on the backend. It's the browser extension's id token that is expired. In most actions, we offer to reconnect, but apparently in one particular action we don't.

**Comment by tomholub** [comment]
Link to email conversation in my inbox https://mail.google.com/mail/u/0/#inbox/FMfcgzGrbcCBKdDwgmPvszKTvSdMgLrS

> Ok another user (B) just reported the same issue. She said all she was doing was refreshing the page. I just tried to open a new chrome tab and go to [gmail.com](http://gmail.com/) and it happened to me just now. Every time you refresh it keeps showing up.
> 1. I thought if I click the "enter passphrase" or whatever the message is at the bottom of the screen it would fix it, but when I clicked it nothing happened (no prompt to enter the passphrase like it normally does).
> 2. refreshed again, same story.
> 3. Then when we do a normal compose, refresh still there.
> 4. BUT when we do a secure compose, we can send an email, refresh and no error message anymore.

> [tom] in most situations, when renewing the id token automatically is not possible, the user will be presented with a prompt to re-connect in whichever context they are at that moment. It seems like there is some context in which they don't. We'll address it.

**Comment by tomholub** [comment]
Even if we cannot reproduce it, this is enough information to attempt a fix.
