### ISSUE TITLE
cannot build flowcrypt-browser on a mac easily?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4848]
@ioanmo226 did you have any problem with that?

i remember our build script needed a recent version of bash, which macs don't have. Is this something you had to work around, or did it work right away?

In case there indeed is any problem, I'm filing this for @sosnovsky to either document or improve.

**Comment by ioanmo226** [comment]
Well, When I first tried to setup browser extension, I had trouble with setting up bash v4.
But I followed documentation and it was straightforward.

![image](https://user-images.githubusercontent.com/77344191/208839415-16af411e-493f-4702-8da1-661b00e5c511.png)

PS: I'm currently using mac though

**Comment by tomholub** [comment]
thanks, looks sufficient
