### ISSUE TITLE
Recognise links and make them clickable

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#4849]
Currently users can't click links in rendered emails. We should recognise links when rendering email message and make them clickable

**Comment by tomholub** [comment]
maybe on browser it already works?

**Comment by sosnovsky** [comment]
doesn't work for me on firefox

**Comment by sosnovsky** [comment]
just checked chrome - links not clickable there too

**Comment by tomholub** [comment]
ok. used to be. i mildly recall, there may have been some problem with the dependency and maybe we took it off. 

could see if it could be implemented as part of dompurify, that would be easiest

**Comment by ioanmo226** [comment]
I think we have to find links and replace them with `a` tag using regex.
Let me know your thoughts

**Comment by sosnovsky** [comment]
> I think we have to find links and replace them with `a` tag using regex.
> Let me know your thoughts

Yes, you can try this way, but we should also check that it's not existing link like `<a href="...">some link text</a>`
Maybe `dompurify` has some helper functions for this, like Tom proposed above, should be worth to check too

**Comment by ioanmo226** [comment]
Yeah, I think so

**Comment by ioanmo226** [comment]
As I checked, DOMPurify doesn't support such feature.
But [linkify](https://github.com/Hypercontext/linkifyjs/) does. Do you want me to use `linkify` or develop my own solution?

**Comment by sosnovsky** [comment]
`linkify` looks good, let's use it
