### ISSUE TITLE
Extension doesn't recognize draft saved from iOS app

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4868]
When I created draft in iOS app and opened draft in browser extension, it doesn't show `Open Draft`(which will open secure compose view with decrypted content)

![image](https://user-images.githubusercontent.com/77344191/210952997-26424c57-cf13-4576-9791-7caff4af1294.png)

**Comment by ioanmo226** [comment]
@tomholub I believe this issue requires your attention.
The browser extension is unable to determine the draftId when a user opens a draft by clicking on the image provided.
![image](https://user-images.githubusercontent.com/77344191/212098263-dc0f1750-8a80-4891-9103-a12dd5c1962b.png)

As a result, the browser extension is prepending "flowcrypt:link:draft_compose:{draftId}" to the draft and using regex to extract the draft id from the text.
This results in the draft appearing as follows:

```
flowcrypt:link:draft_compose:{draftId}
-----BEGIN PGP MESSAGE
...
-----END PGP MESSAGE
```

However, when saving a draft from iOS, we are only saving the PGP blocks as we have full control over the Gmail API. I recommend fixing or implementing this issue on the iOS side by adding the prefix "flowcrypt:link:draft_compose:{draftId}" when saving a draft, so that the browser extension can understand and parse it correctly.

Please let me know your thoughts on this matter.

**Comment by tomholub** [comment]
I would prefer that we find a way to not need this "tag" anymore on browser extension. Was never happy with it.

@sosnovsky may have some idea

**Comment by sosnovsky** [comment]
@ioanmo226 I checked markup of gmail page and it seems we can fetch draft id from html:

```html
<span data-thread-id="#thread-f:1754843898727782240" data-legacy-thread-id="185a753a73ee5760" data-legacy-last-message-id="185a7542f4cf13a3" data-standalone-draft-id="#msg-a:r-2512441704796820331" data-legacy-standalone-draft-id="185a7542f4cf13a3">Test draft</span>
```

Then we can use this id for `Open draft` link in [replaceComposeDraftLinks](https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/content_scripts/webmail/gmail-element-replacer.ts#L294)

And for detecting FlowCrypt drafts we can use regex matching `-----BEGIN PGP MESSAGE----- Version: FlowCrypt...` instead of current `flowcrypt:link:draft_compose:`

What do you think, will it work this way?

**Comment by ioanmo226** [comment]
Sounds good. 👍 
Yeah it seems to work well.
Let me implement that way and get rid of those `tags`
