### ISSUE TITLE
message password no longer coloring in green?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4872]
it used to color green when it matched the input requirements. now it stays red

![image](https://user-images.githubusercontent.com/6306961/211148828-26759a5e-8d1b-4fd6-8480-560c372b5f4d.png)

**Comment by tomholub** [comment]
That way it would indicate that the password is fine. At that point, no need to show the tooltip either. (but need to show it later again if password is modified to be non-compliant)

**Comment by tomholub** [comment]
@ioanmo226 tomorrow please have a look at this

**Comment by ioanmo226** [comment]
OK
