### ISSUE TITLE
review app performance without workers on OpenPGP.js 5

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4903]
We'll merge and try it without background workers first. If performance is acceptable, we'll leave it. Else we'll have to implement our own background workers in another PR. They were removed from OpenPGP.js v5 and left for app to implement when needed.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/pull/4725#discussion_r1085536372_

**Comment by tomholub** [comment]
To test this, have a conversation of 50 short messages encrypted for rsa4096. 50 is the maximum size in Gmail I think before it makes a new thread visually, so that's the maximum that would be loaded at once.

Open the conversation so that all iframes start loading/decrypting at once. Time how long it takes for the last one to finish decrypting. This way, compare the OpenPGP.js v4 version to current master. Let's see if the difference is significant, I suspect the new implementation will be slower, possibly half as slow (assuming you have a multi-core device).

**Comment by rrrooommmaaa** [comment]
I assume I can do this on a mock Gmail page?

**Comment by tomholub** [comment]
would also work

**Comment by rrrooommmaaa** [comment]
or I can just create a single message with 50 inline blocks?
Each block is opened in its own frame anyway.

**Comment by tomholub** [comment]
yes

**Comment by rrrooommmaaa** [comment]
> Let's see if the difference is significant, I suspect the new implementation will be slower, possibly half as slow (assuming you have a multi-core device).

Actually, the other way around, the new implementation is significantly faster. Here are the measurements:
77881730548e38897e823732e4655874b1003e27 1 core: 56 seconds, 4 cores: 35 seconds
HEAD  1 core: 35 seconds, 4 cores: 15 seconds

I submitted the code in this PR #4968 (elapsed time is measured between `start = new Date{}` and `stop = new Date{}`

**Comment by tomholub** [comment]
For sure an improvement. Clearly, multi-threading is being well utilized.

Did you intend to possibly merge that? If yes, we could consider reducing it to 10 messages, with appropriate time limit. If not, then it has served well as a demonstration.

Oh - could alternatively merge it in with `.skip`, as it is useful.

**Comment by rrrooommmaaa** [comment]
> Oh - could alternatively merge it in with `.skip`, as it is useful.

Good point! Done that.
