### ISSUE TITLE
switch to forward is missing files

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4922]
1) click encrypted reply to a particular email
2) switch reply to forward using the dropdown on top right
3) I'm forwarding now but it's missing the attachments from previous email

**Comment by ioanmo226** [comment]
I can't reproduce.
When I switch from reply to forward, previous attachment still remains in forward.
@tomholub Could you share reproduce steps?

**Comment by tomholub** [comment]
I have an email with attachment received, and I click "secure reply" below

![image](https://user-images.githubusercontent.com/6306961/216591624-e2e08b1a-8d65-411e-b81e-1a8ac03a6c29.png)

then I see this

![image](https://user-images.githubusercontent.com/6306961/216591712-7a9a2fa9-48d2-4d10-bf02-813e3e36b8f4.png)

but I realize I wanted to forward, so I switch to forward on top left

![image](https://user-images.githubusercontent.com/6306961/216591822-880126c4-4b35-48da-949a-a94086c90c8a.png)

but as you can see there is no attachment showing in the message I'm about to forward

**Comment by ioanmo226** [comment]
Aha, I got your point.
Let me check & fix
