### ISSUE TITLE
trouble building the extension

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4940]
@rrrooommmaaa I tried to build extension with `npm run build` from `master` branch, but it fails with error after this merge
```
+ mkdir -p ./build/generic-extension-wip/lib/streams
+ cp node_modules/@openpgp/web-stream-tools/lib/node-conversions.js node_modules/@openpgp/web-stream-tools/lib/reader.js node_modules/@openpgp/web-stream-tools/lib/streams.js node_modules/@openpgp/web-stream-tools/lib/util.js node_modules/@openpgp/web-stream-tools/lib/writer.js ./build/generic-extension-wip/lib/streams
+ sed -i -E 's/'\''\.\/(streams|util|writer|reader|node-conversions)'\''/'\''\.\/\1\.js'\''/g' ./build/generic-extension-wip/lib/streams/node-conversions.js ./build/generic-extension-wip/lib/streams/reader.js ./build/generic-extension-wip/lib/streams/streams.js ./build/generic-extension-wip/lib/streams/util.js ./build/generic-extension-wip/lib/streams/writer.js
sed: 1: "s/'\.\/(streams|util|wr ...": \1 not defined in the RE
```

Should I change something to make it work?

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-browser/issues/4725#issuecomment-1420527461_

**Comment by tomholub** [comment]
Sorry @sosnovsky , I jumped you here and merged it too early - will leave it to you next time.

You could try deleting node_modules, ensuring to use same npm version as on the CI, then trying again.

**Comment by sosnovsky** [comment]
I found an issue - it happens only on mac, as it needs to have extension for backup of original files for `sed` command.
It happened for me in [config-mock-build.sh](https://github.com/FlowCrypt/flowcrypt-browser/blob/master/scripts/config-mock-build.sh#L5) too
