### ISSUE TITLE
client configuration to allow remote CSP images to be automatically expanded when sent from desired domains

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4956]
This will be after #4950

I'd like a new client configuration called `allow_remote_content_from_users_on_domains: []` that is processed similarly as `allow_attester_search_only_for_domains` (list of domains). It's optional. When not present or has empty list, the behavior is as before (user has to click on remote image to display it).

When present, let's say `allow_remote_content_from_users_on_domains: ["first.com", "second.com"]` then if I receive an email from user on either `first.com` or `second.com`, remote images in the email should be expanded automatically.

**Comment by ioanmo226** [comment]
@tomholub Can I work on this one after #4950?

**Comment by tomholub** [comment]
I think this issue is to be closed, because https://github.com/FlowCrypt/flowcrypt-browser/issues/4950 already expands them automatically for all recipients?

**Comment by ioanmo226** [comment]
Yeah. it displays all images automatically.

**Comment by tomholub** [comment]
Good - so this one is irrelevant now. I'll go check your other issues now and ensure they are in correct order in milestones.

**Comment by ioanmo226** [comment]
I'm curious about one thing though.
We have `1st priority` milestone and current working version milestone (let's say 8.4.0).
Which one has higher priority?

**Comment by tomholub** [comment]
versioned milestones are always above First/Second/Third, which the nearest version the highest priority.

I know it's not the most fortunate naming, maybe you have some idea how to rename the first/second/third.

**Comment by ioanmo226** [comment]
Aha, got it
