### ISSUE TITLE
Add signature in secure compose windows

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4959]
Mail Subject: Signature missing in FC compose

The UX with regards to Gmail footer/signature should be the same as when composing with Gmail, that is, already show when new compose box is rendered (but don't show if this is a reply box, while still ensuring that it gets added appropriately for replies, and that it behaves well when sending out from a Draft too, whether new or reply, after this change).

**Comment by tomholub** [comment]
@ioanmo226 this one would be the next - thank you

**Comment by ioanmo226** [comment]
ok

**Comment by sosnovsky** [comment]
Here we need to have the same behavior as Gmail - signature should be visible in compose window too

**Comment by ioanmo226** [comment]
ok

**Comment by ioanmo226** [comment]
@sosnovsky We have triple dot button and when we click this button, signature will be shown.
I think this one seems more reasonable(User can see signature if he wants to)?
Do you still want to display signature without clicking `triple dot` button and hide `triple button`?

![image](https://user-images.githubusercontent.com/77344191/220877093-57b271e3-0bb1-476b-8620-77b746fff3c1.png)

![image](https://user-images.githubusercontent.com/77344191/220877044-89fcbedb-df97-4739-ad01-140f44d5f0d7.png)

**Comment by sosnovsky** [comment]
> Do you still want to display the signature without the user clicking on the triple-dot button and hide the button itself?

Yes, it was request from customer, as he thought signature wasn't added to his message.
That's why we decided to copy original Gmail behavior, so it'll be more clear for users.
