### ISSUE TITLE
a more gracious way to reset pass phrase when using EKM

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4975]
Currently, when an EKM user forgets their pass phrase, we instruct them to reset (often reinstall) the extension which is excessive.

Instead, when EKM is in use, the browser extension should respond with a prompt to set a new pass phrase. Which can be easily fulfilled, because the decrypted keys can be fetched from EKM and stored locally.

**Comment by ioanmo226** [comment]
@tomholub Could you give me some more details on how to reset a password? I'm curious if the user needs to reconnect their Google account during the process.

If the user doesn't have to reconnect their Google account, setting a passphrase may not be useful because anyone (not just the author) trying to reset the password could potentially see encrypted emails.

**Comment by tomholub** [comment]
I guess it would indeed be appropriate to force the user to go through Google reconnection in the process.

Following that, a call to EKM would be made like during setup, where private keys are retrieved, and the user is asked for a new pass phrase to use for these retrieved keys. Again, just like during setup. You could possibly reuse the setup screen for this, but you wouldn't have to. I'm unsure which would be cleaner, but I imagine _not_ reusing the setup screen would be cleaner. 

> If the user doesn't have to reconnect their Google account, setting a passphrase may not be useful because anyone (not just the author) trying to reset the password could potentially see encrypted emails.

The call to EKM is authenticated either way, it does require id_token. That id_token can be either a fresh one following a re-authentication with Google, or it can be one that is retrieved from browser extension storage, assuming it's fresh, or one that gets retrieved from Google API without re-authentication with Google, assuming the one in storage was not fresh.

From the perspective of the EKM, none of this makes any difference, as long as a valid id_token is sent.

That being said, it does make sense to require the user to go through the re-authentication in the UI if they want to reset their pass phrase.

**Comment by ioanmo226** [comment]
Ok, got it

**Comment by tomholub** [comment]
so we're dropping this then, per customer feedback.
