### ISSUE TITLE
backup option that emails encrypted backup to a designated mailbox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#4978]
with this option client configuration:

```
"prv_backup_to_designated_mailbox": "(armored public key here)"
```

User will be presented with a screen that we already have as in "used pgp before?" with options to import or create a key.

When importing, they have an option to import from a file or by pasting as usual.

When generating, after the user sets their pass phrase (the regular backup step), without asking the user anything regarding which backup to use, the key will be:

1) decrypted, so it doesn't use any pass phrase + armored
2) email will be composed, to: `<primary uid of the prv_backup_to_designated_mailbox pubkey>` , subject: `FlowCrypt OpenPGP Private Key backup for user ${userEmail} with id ${primaryFingerprint}`, the text should have: `Please keep this email and attachment in the mailbox for safekeeping. It will be needed if the user ever needs to set up FlowCrypt again or forgets their pass phrase. Without this, the user won't be able to read their emails. See https://flowcrypt.com/docs/technical/enterprise/configuration/backup-to-designated-mailbox.html#recovery` and then the attachment will be the private key
3) This whole email will be encrypted with the public key in `prv_backup_to_designated_mailbox`
4) the email will be sent to the primary uid email contained in `prv_backup_to_designated_mailbox` public key

The priority is as follows, which should be documented when adding this new option to https://flowcrypt.com/docs/technical/enterprise/configuration/client-configuration.html#client-configuration-rules : 
 - if both `prv_backup_to_designated_mailbox` and `key_manager_url` is set, `prv_backup_to_designated_mailbox` will be ignored
 - if both `prv_backup_to_designated_mailbox` and `NO_PRV_BACKUP` is set, `prv_backup_to_designated_mailbox` takes precedence 
 - if both `PRV_AUTOIMPORT_OR_AUTOGEN` and `prv_backup_to_designated_mailbox` are set, client will show error

**Comment by tomholub** [comment]
Recovery process that should then be documented in docs / private key management, should be:

> 
> Assuming this has to happen remotely, I think easier option would be to send it password-encrypted through the web portal, which would be as follows:
>  - helpdesk decrypts/downloads the unprotected private key
>  - helpdesk uses FlowCrypt to send an email while ignoring the previous public key of the user they are helping, as follows: assuming "user@example.com" needs the key, they send to "user+key@example.com". FlowCrypt will then offer to send the email password-encrypted. Strong password should be used here (16 characters). The body of the email or "intro" (unencrypted) should also contain either instructions on how to recover or link to docs provided by us (general) or yourself (if you want more specific instructions).
>  - helpdesk texts the user an SMS with the password
>  - user receives the email with the link, which takes him to web portal, and he enters password which allows to download the private key
>  - user reinstalls the browser extension
>  - during setup, user imports the private key they received, and chooses a new pass phrase when prompted

**Comment by tomholub** [comment]
I'll make a separate issue so that Vahram can document the `prv_backup_to_designated_mailbox` property in client configuration and on the new page https://flowcrypt.com/docs/technical/enterprise/configuration/backup-to-designated-mailbox.html

The draw of this setup is that the customer doesn't need to run any Enterprise Server or EKM. They can have a very simple SaaS setup where we run everything for them, and they still have automatic backup like this. The downside is that when users forget their pass phrase, they have to involve the admin to give them the key backup to recover from. The upside is fast and easy setup.

**Comment by martgil** [comment]
@tomholub Just a quick question for "if both PRV_AUTOIMPORT_OR_AUTOGEN and prv_backup_to_designated_mailbox are set, client will show error".

PRV_AUTOIMPORT_OR_AUTOGEN flag is not usable without the key_manager_url property. Is it correct to return an existing error message: "Wrong org rules config: using PRV_AUTOIMPORT_OR_AUTOGEN without key_manager_url"? Because the `prv_backup_to_designated_mailbox` was already ignored when the FES user uses a key manager.

**Comment by tomholub** [comment]
in that case, existing error will do

**Comment by martgil** [comment]
noted, thank you.
