### ISSUE TITLE
re-enable viewing remote images in signed/encrypted messages still not working as expected.

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#4983]
Showing remote images still don't work well yet.

**Comment by ioanmo226** [comment]
@sosnovsky As I checked carefully, image is not displayed because image server is returning CORS error.
I think this issue should be fixed in customer side?

> Access to fetch at 'https://go.[clientserver].com/rs/222-DNK-376/images/[logo_name].png' from origin 'chrome-extension://mkefadjohdmonnjbidopnmjlepdomjmi' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by ioanmo226** [comment]
Also what error message do I have to show?

**Comment by ioanmo226** [comment]
Will it fix CORS issue? I don't think it would solve cors issue

**Comment by sosnovsky** [comment]
Checking it now..

**Comment by sosnovsky** [comment]
> Will it fix CORS issue? I don't think it would solve cors issue

Yeah, seems like CORS issue will occur for all possible data fetches.
Then for now let's show error `Can't load remote image` and link below `Open image in new tab`

> Or maybe we can use background script to fetch resource?

Did you try this method?

**Comment by ioanmo226** [comment]
Not yet. I'll try and i think this might work.
I have current in-progress [issue](https://github.com/FlowCrypt/flowcrypt-browser/issues/4962).
I'm gonna have a look at this issue after current issue.
Or do you wanna me to have a look at this one first?

**Comment by tomholub** [comment]
> could it be that the cors error is the result of extension’s csp? maybe another approach to rendering could work around the problem. 

I suspect adjusting csp would fix the CORS issue. @rrrooommmaaa may know

**Comment by sosnovsky** [comment]
> I suspect adjusting csp would fix the CORS issue. @rrrooommmaaa may know

I think CSP won't affect this issue, as this issue is on other server side - it doesn't allow external servers to fetch images.
We had similar issue with attachments stored on s3 - https://github.com/FlowCrypt/flowcrypt-browser/issues/3026.

**Comment by tomholub** [comment]
Sure, it's missing CORS headers returned from the server. But in some contexts, extensions can still access such content. One such way is if we allow the extension to run access `*` (all websites) in manifest. Not that I want to do that. But there may be other ways still, for extensions.

**Comment by ioanmo226** [comment]
Even when using a background script, the CORS error still persists.
@sosnovsky, would you like me to proceed with showing the error message and the image link below?

**Comment by sosnovsky** [comment]
Yes, let's show error message `Remote server blocked image loading` for CORS error, and `Failed to load image` for other errors 
And add link to image below - `<a href="IMAGE_URL">Open image in new tab</a>`

**Comment by ioanmo226** [comment]
Regarding this error UI test, what image url should I use which returns cors error?

**Comment by tomholub** [comment]
if your code has a generic handler for any possible error, then it wouldn't need to be cors in particular. could just be any unreachable url?

**Comment by ioanmo226** [comment]
Sounds good!

**Comment by ioanmo226** [comment]
I have better suggestion.
We can bypass this CORS issue using 3rd party url (something like https://allorigins.win/) or make our server api and use that api to fetch image resource.

Let me know your thought.

`https://api.allorigins.win/get?url=${imageUrl}`

**Comment by tomholub** [comment]
There's a very large privacy problem with that, whether we do it ourselves, or use a 3rd party tool (worse).

Unless the customer runs the software.

At that point, a less nuclear solution would be to give the extension permission to access content on all websites. Then it won't be affected by CORS (but we're not doing that now. We could consider it on manifest v3 if it allows incremental permissions, where user would enable it afterwards).

**Comment by ioanmo226** [comment]
Ok, got it.
Then let me continue to implement in previous suggested solution
