### ISSUE TITLE
user question: signed message is in encrypted format

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#4988]
from: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGrcrnlbTTzpBVtlRwhVwdwcTlV

Description: the user in the inquiry wonders why the signed message is encrypted.

I investigate the said concern and send a signed-only message to my test account. Seeing the original message shows the `-----BEGIN PGP MESSAGE -----` ascii armored signed message. The message is encrypted and signed - and not the typical cleartext signed message `-----BEGIN PGP SIGNED MESSAGE-----`.

@tomholub Is it the signed message we actually expected?

Sample test message: https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/FMfcgzGrcrrDxTmmjPSppVCPhxbKmWxD

**Comment by patrickallaert** [comment]
I think I am facing the same issue.
I only wanted to sign a message, not encrypt it.
This is what has been seen on the mailing list: https://externals.io/message/119661

This is what I can see in my "Sent items":
![image](https://user-images.githubusercontent.com/195277/222724656-3520376f-940e-4a42-9a81-abe088b43991.png)

**Comment by Braveheart53** [comment]
For an example, see the following images:

Initial Message Prior to sending
![image](https://user-images.githubusercontent.com/30416052/222726396-064f67e9-e9ad-4877-a3e8-44594d013a3f.png)

Showing selection of no encryption:
![image](https://user-images.githubusercontent.com/30416052/222726545-30943e6e-d527-4187-810b-8279a888aa1c.png)

Message as seen in sent folder:
![image](https://user-images.githubusercontent.com/30416052/222726778-c0e5300f-113b-425b-ad6d-53215483b49f.png)

Message Original as seen in sent folder:
![image](https://user-images.githubusercontent.com/30416052/222726946-d3013570-518e-4a8b-aec4-09338932a482.png)

Message as seen by recipient:
![image](https://user-images.githubusercontent.com/30416052/222727185-a4af0f02-75ee-42d2-8aa0-32640c46018d.png)

**Comment by tomholub** [comment]
my guess is that the message is indeed signed only, but also armoured. so it has an appearance of an encrypted message. likely result of openpgp v5 update. @rrrooommmaaa  could you do a hotfix for this, temporarily postpone other work?
