### ISSUE TITLE
load remote images directly in img tags, allow it in CSP, add warning around remote images

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#5001]
We should stick to `<img src=>` tags. Remove the csp restriction as I've just done, and all of the images will work, regardless of CORS.

It seems to me to be the only sane way to support this functionality.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/4999#issuecomment-1458392763_

**Comment by tomholub** [comment]
I'd like something similar, like you have done for the error handling:

![image](https://user-images.githubusercontent.com/6306961/223477352-6792c391-50ec-4bde-8311-bec4856b2fe2.png)

Except that instead of `Failed to load image` there would be the `Authenticity of this remote image cannot be verified.` and below that, there would be the actual image.

**Comment by ioanmo226** [comment]
@sosnovsky I think we can release 8.4.4 as all tasks are completed if everything is okay?

**Comment by sosnovsky** [comment]
Yes, everything looks good, can do new release
