### ISSUE TITLE
Failed to import keys with image data

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5026]
Description: The FlowCrypt browser extension raises an error when importing a key with image data. Image data are stored in key users' attributes. 

The error shown is `TypeError: Cannot read properties of null (reading 'userID')` because the image data's userID is indeed null while the software is trying to read it.

![image](https://user-images.githubusercontent.com/46025304/226313510-97757447-93ea-409b-9175-d9f2b04158a3.png)

sample public key with image data can be found at https://flowcrypt.com/attester/pub/A62F3CDFECC0926C

output from gpg:
```
pub  rsa4096/A62F3CDFECC0926C
     created: 2016-06-15  expires: never       usage: SC  
     trust: unknown       validity: unknown
sub  rsa2048/D14BB2C566698205
     created: 2016-06-15  expires: 2024-06-13  usage: SE  
sub  rsa2048/2D2EA188B5988036
     created: 2016-06-15  expires: 2024-06-13  usage: SA  
[ unknown] (1). User <user@example.com>
[ unknown] (2)  User <user@example.com>
[ revoked] (3)  User <user@example.com>
[ revoked] (4)  User <user@example.com>
[ unknown] (5)  [jpeg image of size 5473]
[ revoked] (6)  User <user@example.com>
```

Notice the 5th item from the users list. It is an image added via `addphoto` command by gpg and utilized by software like GPG Keychain for Mac - https://superuser.com/questions/336894/how-can-i-add-my-picture-to-my-public-key-using-gnupg

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGslbKpfTcJlrrsQzJnWJzgHQzn

**Comment by martgil** [comment]
To replicate the issue:

1. Try encrypting a message using [A62F3CDFECC0926C](https://flowcrypt.com/attester/pub/A62F3CDFECC0926C).
2. An error `TypeError: Cannot read properties of null (reading 'userID')` will occur in the background which we can check through the javascript console.
3. The sender nor the owner won't be able to encrypt emails using the said public key.

**Comment by tomholub** [comment]
We used to just strip out all image packets (they can be used for abuse and can bloat keys quite a bit).

So we could look into stripping them again, which maybe could address the problem.

Does the same problem happen when loading/using the public key with OpenPGP.js only, outside of our extension? If yes, then it could be a problem with the library.

**Comment by martgil** [comment]
> Does the same problem happen when loading/using the public key with OpenPGP.js only, outside of our extension? If yes, then it could be a problem with the library.

Reading the public key with OpenPGP.js works without any issues. It's just our extension reads every `userID` property where in this case, the `userID` is null but with image data in users' `attributes` properties. I think we solve the issue by stripping the image packets or adjusting the checks when reading userID.

**Comment by tomholub** [comment]
I see. I don't know what exactly the solution should be, but indeed it's a bug in our software that we should fix, so that such keys are generally usable.

**Comment by martgil** [comment]
I investigate the issue further and found out that the issue is within OpenPGP.js `verifyAllUsers()`. I will raise this concern with OpenPGP.js regarding their support of keys with image data.

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/46025304/234199748-ef312889-85ec-4b6f-96ff-57a4e690410d.png">

**Comment by martgil** [comment]
Here it is https://github.com/openpgpjs/openpgpjs/issues/1636.
