### ISSUE TITLE
Email from ECP with valid inline-image not rendering correctly

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5031]
Description: The browser extension fails to show the preview of an inline-image attachment sent using the Encrypted Contact Page (ECP).

Screenshot:
(image attachment preview)
<img width="769" alt="image" src="https://user-images.githubusercontent.com/46025304/226814543-b25f3b46-db70-4258-984c-a2cdf071baf7.png">
(downloaded image)
<img width="385" alt="image" src="https://user-images.githubusercontent.com/46025304/226814695-c5db5610-5d6c-40fe-bfbb-ec78a7091657.png">

Sample email with image attachment:
https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/FMfcgzGslkdwstMkdNkdxgcbqrKhMSvd

**Comment by tomholub** [comment]
Does it work correctly when displaying in Thunderbird for example?

**Comment by martgil** [comment]
No - it's a custom inline attachment that we're rendering into the extension.

![image](https://user-images.githubusercontent.com/46025304/227135921-8d328a18-ece1-4df3-aed8-a95c9470154e.png)

**Comment by tomholub** [comment]
This should be fixed by https://github.com/FlowCrypt/flowcrypt-web/issues/183

It's still possible to download them, right? Just the previous is a problem? I think I'll close this here, and later we need to address the linked issue.

**Comment by martgil** [comment]
Yes, users can decrypt and download the message - it's just they can't see the preview of a supported file attachment.
