### ISSUE TITLE
Incorrect modification detection when saving drafts

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#5037]
The failing use case that I saw:
1) open a new secure compose window
2) quickly type/paste something into the body before the first `draftSave()` is activated (`SAVE_DRAFT_FREQUENCY = 3000` ms)
3) the draft will not be saved

This causes some tests to periodically fail (e.g. `mail.google.com - saving and rendering compose drafts when offline`) and generally bad UX.

Reason: `ComposeDraftModule.hasBodyChanged()` relies on `lastDraftBody` property which is initialized as `undefined`
and it ignores the first updates (returns false)

**Comment by tomholub** [comment]
Good observation, than you for detailing it here. This could indeed be improved.

**Comment by rrrooommmaaa** [comment]
@ioanmo226 Please remove the pauses in tests marked like this: `await Util.sleep(5); // until #5037 is fixed`
The tests should be able to work without this now.

**Comment by rrrooommmaaa** [comment]
Why? #5069 isn't related to compose windows. Maybe it only affects some decryption-related code there

**Comment by rrrooommmaaa** [comment]
Ok, this can wait
