### ISSUE TITLE
Enable 'Update branch` button for PRs

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5060]
In other repositories we have button for merging latest commits from `master` branch to PR, which is quite convenient:

<img width="600" alt="Screenshot 2023-04-04 at 21 33 21" src="https://user-images.githubusercontent.com/1062093/229886054-a2d0d588-683b-4f81-824c-63c203254126.png">

Seems like it's disabled here, can be enabled in `Repository settings` -> `Pull Requests` -> `Always suggest updating pull request branches`
https://github.blog/changelog/2022-02-03-more-ways-to-keep-your-pull-request-branch-up-to-date/#always-have-the-option-to-update

**Comment by tomholub** [comment]
updated
