### ISSUE TITLE
Password-protected message won't work if keys.openpgp.org is not reachable

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5070]
Description: The password-protected message composer doesn't work if keys.openpgp.org is not reachable. That makes the password messages feature unusable. The affected use cases are with those systems where keys.openpgp.org is configured not to be reachable.

![image](https://user-images.githubusercontent.com/46025304/230295443-504535db-aad9-4f1e-8211-75d3d7d70d7d.png)

Steps to reproduce:
1. compose a password-protected message with FlowCrypt secure compose for `unknown.user@example.com`.
2. Let every HTTP requests go through except for `https://keys.openpgp.org/vks/v1/by-email/unknown.user@example.com` (drop the request).
3. You'll get the following screen above - with no error message. 

Alternatively, you can temporarily disconnect your internet connection so you'll get the above error. Everything else is is unreachable but it should let rendering password message and only then when sending the password protected message, a network error will appear since reaching keys.openpgp.org is only an optional process.

![image](https://user-images.githubusercontent.com/46025304/230294071-a42d9e30-4d4f-4dcc-a78b-dd005290232d.png)

Expected behavior: Let the password message UI load even when keys.openpgp.org is not reachable. 

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGsltMtPXCTntcsdfBHXHjmsKlf

**Comment by tomholub** [comment]
given that the customer has a firewall that is blocking these requests, they should communicate to their firewall administrator and allow requests to keys.openpgp.org.

I think this behaves as expected.

**Comment by tomholub** [comment]
Since they were able to use FlowCrypt previously, it seems like they already must have earlier allowed at least some other domains to make it work, so we are suggesting they add one more to ensure it continues working going forward.
