### ISSUE TITLE
Message parsing fails with error 'TypeError: imageSrc is null'

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5079]
Customer reported issue with parsing email, it fails with `imageSrc is null` error, seems to be related to [replaceInlineImageCIDs](https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/chrome/elements/pgp_block_modules/pgp-block-render-module.ts#L337)

I sent you original email so you can reproduce it.

@ioanmo226 please check this one, probably should be a small fix

**Comment by ioanmo226** [comment]
Ok.
