### ISSUE TITLE
Rewrite mocks to use new `ConfigurationProvider`

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#5099]
`Attester` and `keysOpenPgp` is already migrated.
Below needs to be migrated.

- [x] #5101
- [x] #5102
- [x] #5105
- [x] #5142
- [x] #5118

**Comment by sosnovsky** [comment]
Let's implement https://github.com/FlowCrypt/flowcrypt-browser/issues/5098 first and then you can choose any service from this list

**Comment by ioanmo226** [comment]
Ok

**Comment by sosnovsky** [comment]
Great job, it was a big improvement for our tests structure 👍
