### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by vahram-papazyan** [FlowCrypt/flowcrypt-browser#5119]
Grammar, stylistic and content improvements

**Comment by tomholub** [comment]
This issue is missing a description, can you be more specific? Is it small format issues and stuff, or something bigger missing?

**Comment by vahram-papazyan** [comment]
> This issue is missing a description, can you be more specific? Is it small format issues and stuff, or something bigger?

I added a description.

**Comment by vahram-papazyan** [comment]
Seems like I don't have rights to contribute to the project

SSH
```
ERROR: Permission to FlowCrypt/flowcrypt-browser.git denied to vahram-papazyan.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

HTTPS 

```
remote: Permission to FlowCrypt/flowcrypt-browser.git denied to vahram-papazyan.
fatal: unable to access 'https://github.com/FlowCrypt/flowcrypt-browser.git/': The requested URL returned error: 403
```

**Comment by tomholub** [comment]
@DenBond7

**Comment by DenBond7** [comment]
@vahram-papazyan I've updated Collaborators. Please try.

**Comment by vahram-papazyan** [comment]
Is there a valid link for Live tests? The current one isn't working
