### ISSUE TITLE
`Enable Google Contact search` is shown even after granting permissions

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5123]
Customer reported that `Enable Google Contact search` button appears even when contact permissions are granted.
And after clicking on it contacts search still returns only FlowCrypt contacts, but not contacts from Google.

I reproduced this issue too - just try to enter contact name which doesn't exist (to have empty search results) and then click `Enable Google Contact search`

It seems this bug appeared in the latest 8.4.6 release.
Also should add test for this issue, so it won't reappear in the future.

**Comment by sosnovsky** [comment]
Let's work on this one first, as it's a customer-facing issue

**Comment by sosnovsky** [comment]
@ioanmo226 `Enable Google Contact search` button still appears after restarting Chrome

**Comment by ioanmo226** [comment]
I also reproduced it after restarting Chrome. Let me investigate this issue next week
