### ISSUE TITLE
Error during importing Public keys from a file

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-browser#5146]
I'm working on https://github.com/FlowCrypt/flowcrypt-android/issues/1692. After trying to import the provided file with public keys I saw the following
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/2863246/ebb8263b-a73b-4ffc-9a4c-b00bd13ed7ec)

This file contains a lot of public keys. Maybe we have to allow importing `good` keys and show a warning for `bad` keys.
@sosnovsky I will send you the file.

**Comment by sosnovsky** [comment]
> This file contains a lot of public keys. Maybe we have to allow importing good keys and show a warning for bad keys.
@sosnovsky I will send you the file.

Usually it works the way you described - valid keys are imported, and for invalid ones we show warning (https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/chrome/settings/modules/contacts.ts#L111).

Maybe currently all keys are invalid in provided file, as it's more than 1 year old and keys can expire since then.

@DenBond7 were you able to import any key from this file on Android?

**Comment by sosnovsky** [comment]
> Yes, for example for this file [pub_keys_5_good_1_unsupported.txt](https://github.com/FlowCrypt/flowcrypt-browser/files/11441700/pub_keys_5_good_1_unsupported.txt)

Yeah, current UI isn't very informative, I'll file separate issue for it, thanks for reporting!

**Comment by ioanmo226** [comment]
Please send me key file you are testing

**Comment by DenBond7** [comment]
> Please send me key file you are testing

I've sent ))

**Comment by sosnovsky** [comment]
@ioanmo226 during my check I found that issue probably happens at [getSortedUserids](https://github.com/FlowCrypt/flowcrypt-browser/blob/34c64e18e46e877b846ac49e1e31471f2a6d55a9/extension/js/common/core/crypto/pgp/openpgp-key.ts#L535)

**Comment by ioanmo226** [comment]
From my research, this error happens at below line (OpenPGP `verifyAllUsers` function returns error for current key)and I can see that Mart already reported issue at OpenPGP.
@sosnovsky Let me know what you want me to do here.

https://github.com/FlowCrypt/flowcrypt-browser/blob/951cf0ffebcf66c32a3bcc2c71b25c1ba2bb90a7/extension/js/common/core/crypto/pgp/openpgp-key.ts#L543
https://github.com/openpgpjs/openpgpjs/pull/1637

**Comment by sosnovsky** [comment]
> @sosnovsky I think we should wait for next OpenPGP release and just update OpenPGP version.

Agree 👍 Then nothing needs to be done here for now, just re-check that issue is fixed with the next openpgp release.
Thanks for checking!
