### ISSUE TITLE
Improve UI for contact keys import error

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5147]
Currently error for invalid key looks like this:

<img src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/2a40073d-6b02-4e11-8026-8f112c07a161" width="600">

To reproduce:
- go to `Contacts` -> `import public keys`
- try to import pub keys from [pub_keys_5_good_1_unsupported.txt](https://github.com/FlowCrypt/flowcrypt-browser/files/11442064/pub_keys_5_good_1_unsupported.txt)

To do:
- align error message with inputs
- add 'view key` button

Updated design:
<img width="429" alt="Screenshot 2023-05-10 at 16 18 14" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/0a352fe8-844b-4c7b-819b-f06ce00f1520">

**Comment by sosnovsky** [comment]
> What should happen when a user clicks the View Key button? Should it display another swal modal window showing the key contents, or should it simply show the key content below the View Key button, similar to when we click the Details button in the full (non-compact) view?

Let's show key content below, so it'll be consistent with full view.

> Additionally, I couldn't find a use case for the pgp_pubkey.htm?compact=___cu_false___... to enable the non-compact view. Are there any specific circumstances or scenarios where the user can access this non-compact view, other than manually modifying the compact URL parameter from ___cu_true___ to ___cu_false___?

I think it's used when someone sends you message with attached public key (by clicking pubkey icon in the bottom right corner)

**Comment by ioanmo226** [comment]
@sosnovsky How about we display like this?
Show email address too when showing `This OpenPGP key is not usable` label. (Actually `input` element with `disabled` attribute so that it matches other elements/pubkeys.)

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/9ddb9813-e47e-4ad4-84bb-32c2b1816181)

**Comment by ioanmo226** [comment]
Or maybe show `This OpenPGP key is not usable` label at top and then `user_email` input disabled field at the bottom?

**Comment by ioanmo226** [comment]
Well, we just don't show input attribute (which contains email) then?
just show `this openpgp key is not usable` label and `View key` button?

**Comment by sosnovsky** [comment]
> Well, we just don't show input attribute (which contains email) then?
> just show `this openpgp key is not usable` label and `View key` button?

Sounds good, and `this openpgp key is not usable` will be aligned with `View Key` button
