### ISSUE TITLE
`mail.google.com - pubkey gets rendered with new signed and encrypted Thunderbird signature` live test fails

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#5157]

**Comment by sosnovsky** [comment]
Seems like it started failing after my fix for parsing inline signatures - https://github.com/FlowCrypt/flowcrypt-browser/commit/94d91a672cc3b3ffd5f392d8572f0af043d6e6d4

**Comment by ioanmo226** [comment]
I guess so.

**Comment by sosnovsky** [comment]
Probably should just change `not signed` to `signed` in test, I'll check it
