### ISSUE TITLE
Gmelius rendering issue compatibility issue when using FlowCrypt simultaneously

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5159]
Description: A Gmelius user reported that the software failed to render when using FlowCrypt simultaneously. I investigated the issue and found that Gmelius and FlowCrypt both tried to access the same element. Gmelius complained about not having the expected element because the FlowCrypt extension had taken over the slot for that element.

### Steps to reproduce the issue:

1. Install Gmelius and configure it for your Gmail account.
2. Go to Gmail and notice a new section:
<img width="276" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/542ce4fb-ba2a-419c-9636-8940ee4adfef">
3. Install FlowCrypt and configure it for your Gmail account.
4. Go back to Gmail, refresh the page, and notice that the new section is gone and an error on Web Console appears where it js complains about a problem in accessing an element.

One solution is to use another element container to inject the FlowCrypt secure compose button without compromising the UI itself. However, we may find the solution I have proposed to be inadequate in terms of its placement in the HTML structure.

I will publish a PR regarding this to visualize it.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGsmhTPdszCbbJjXhGNWqcZFfTg

**Comment by martgil** [comment]
@sosnovsky I would love to hear your feedback on this one (not urgent). thank you!

**Comment by tomholub** [comment]
I'm not too keen on changing this, as it may cause other trouble and we would be getting no benefits for the risk we're taking. The user could consider using FlowCrypt and the other extension in two separate browser profiles.

**Comment by sosnovsky** [comment]
> I'm not too keen on changing this, as it may cause other trouble and we would be getting no benefits for the risk we're taking. The user could consider using FlowCrypt and the other extension in two separate browser profiles.

I tried to install Gmelius extension and it worked well for me along with FlowCrypt (https://github.com/FlowCrypt/flowcrypt-browser/pull/5160#issuecomment-1553262416), not sure why it fails for other user

**Comment by martgil** [comment]
Thanks for checking this issue. I must add that it only happens when using Gmail with UI for Chat and Meet turned on. This will trigger the error.

<img width="938" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/62573870-b37c-4733-9227-e9fc9badbc5a">

<img width="353" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/bfaf2f56-4d22-4ca1-988a-4c695ef3c7ef">

> I'm not too keen on changing this, as it may cause other trouble and we would be getting no benefits for the risk we're taking. The user could consider using FlowCrypt and the other extension in two separate browser profiles.

Understood. Thank you to @sosnovsky for checking the issue. That definitely helps and it must be an acceptable workaround to use a different Gmail UI that allows the user to use FlowCrypt and Gmelius simultaneously.

I'll be closing this and the draft PR. thank you very much!
