### ISSUE TITLE
Draft is saved even without opening 'compose' box

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5184]
1) open some thread
2) wait for 10 seconds
3) go to Drafts folder - you have draft saved for this thread (even when you just read message and didn't click `Reply` button)

Probably caused by changes in https://github.com/FlowCrypt/flowcrypt-browser/commit/68bae118781a3133b1f7a3faaee9c7f7862f7e17

**Comment by ioanmo226** [comment]
Great, you've found it before we release the new version.
I've just pushed a new fix. Thank you!
