### ISSUE TITLE
Failing properly parse signed message

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5185]
FlowCrypt fails to parse signature from `signature.asc` in signed-only message.

<img width="376" alt="Screenshot 2023-05-25 at 13 16 00" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/204c855b-29a7-4552-8ff5-2876d78877c1">

@ioanmo226 I'll send you .eml file of problematic email message

**Comment by ioanmo226** [comment]
Let me chek

**Comment by sosnovsky** [comment]
Yes, it shows such random characters when opened from plain Gmail UI, but if you click on 3-dot button and select `Show original` then `signature.asc` attachment will have usual `-----BEGIN PGP SIGNATURE-----...` content

**Comment by sosnovsky** [comment]
Yeah, something is wrong with message structure, I'll ask what mail client did they use for sending this message and did there were same issues with another emails.

**Comment by sosnovsky** [comment]
No, any updates on this issue

**Comment by ioanmo226** [comment]
@sosnovsky I changed this task milestone to `cannot reproduce` as we can't reproduce this issue.

**Comment by sosnovsky** [comment]
no feedback from customer, closing this issue
