### ISSUE TITLE
8.4.8 release

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5200]
> @sosnovsky, I noticed that all the tasks in the 8.4.8 milestone have been completed. Should we consider releasing this version? Or is there something specific you are waiting for?

No, I think everything is ready for 8.4.8 release, it's already includes a lot of fixes.
Tom usually creates new builds and releases them.

@tomholub should we release new 8.4.8 version?

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-browser/issues/5150#issuecomment-1568362240_

**Comment by tomholub** [comment]
I forgot about this, will do a release now.

**Comment by tomholub** [comment]
done firefox, still todo:
 - release chrome
 - enterprise chrome

**Comment by tomholub** [comment]
@sosnovsky could you please help me compose release notes and put them in milestone description? Please skip items that are internal refactoring, only user-facing updates.

**Comment by sosnovsky** [comment]
@tomholub done, added changelog to https://github.com/FlowCrypt/flowcrypt-browser/milestone/474

**Comment by tomholub** [comment]
excellent, thank you
