### ISSUE TITLE
[Feature suggestion] fetch and load public key to key compatibility checker page 

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5211]
Description: The OpenPGP key compatibility check page is super helpful for evaluating users' public keys. We use it quite often to have an overview of the available user public key in the attester.

I feel that adding an input field that accepts user email and a button for loading the public key above the ASCII armored key textarea would make it even more useful and versatile. This would improve repetitive tasks such as looking up a user's public key from the attester, copying the public key, and pasting it into the key compatibility checker.

(kindly ignore the error message) 
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/bbe21426-fb9a-4450-a25f-3df7bbe7d2bd)

**Comment by sosnovsky** [comment]
Sounds useful, there we can add label `Search for public key on FlowCrypt Attester` + email input + `Search` button.
On successful search public key should be inserted to public key input.
