### ISSUE TITLE
The "attach public key to email" not working

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5220]
Description: The "attach public key to outgoing email" is not working as expected.

Steps to reproduce:

1. Open the FlowCrypt secure compose message box.
2. Click the public key certificate icon -- you will see the "attaching public key" message afterward.
3. Add a recipient, email subject, email body and hit the "send" button.
4. Open the sent email and notice that the email doesn't include any public key.

Affected sending options: plain text messages - on `master` -- plain and signed on chrome web store version.

**Comment by sosnovsky** [comment]
@margil which browser and extension version do you use?

I tried to send message with attached public key and it worked well for me on both - Chrome and Firefox.

**Comment by martgil** [comment]
I'm using Chrome extension and FlowCrypt extension 8.4.7 - Correction: the public key won't be attached to emails if the message type is plain or signed.

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/92dc995d-f31a-45d1-b5f3-8c759109a752)

**Comment by sosnovsky** [comment]
> I'm using Chrome extension and FlowCrypt extension 8.4.7 - Correction: the public key won't be attached to emails if the message type is plain or signed.

Can you please try it on the build from `master` branch? On my side it reproduces only for plain messages, while signed messages contain attached pub keys

**Comment by martgil** [comment]
On the `master` branch, public keys are not getting attached. Signed and encrypted + signed messages can contain attached pub keys.

**Comment by martgil** [comment]
Got it! That makes sense to me now.
