### ISSUE TITLE
Update Flowcrypt Browser Extension Screenshots in Chrome Web Store

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#5228]
The screenshots on our Flowcrypt browser extension page in the Chrome Web Store are outdated  and need a makeover to match the snazzy new design.

cc: @sosnovsky, @tomholub 

Updated screenshots - https://drive.google.com/drive/folders/1Z_45H1zJn73CrhJl3o_EWXoiyIpfg9U-?usp=sharing

Updated description:
```
🟢 A simple end-to-end encryption to secure your emails and attachments on Google, including G Suite, Business, and Enterprise using OpenPGP.

🟢 FlowCrypt lets you use PGP encryption by generating a private and public key. It uses the recipient’s public key to encrypt the email, and only the recipient’s private key can decrypt the message and reveal its content.

🟢 Adds a Secure Compose button to Gmail, allowing you to send private PGP-encrypted emails when you choose to.

🟢 We update the extension regularly (see the "Updated" field to the right).

FlowCrypt allows you to:
 ✔ Set up the extension in just a few clicks.
 ✔ Generate private keys using the ECC and RSA (up to 4096-bit) algorithms.
 ✔ Use FlowCrypt’s own Attester public key server.
 ✔ Send and receive encrypted emails and attachments (up to 25MB, with previewing functionality) to anyone.
 ✔ Send and receive encrypted emails directly or through Encrypted Contact Page.
 ✔ Send password-protected emails to the recipient who doesn’t have any OpenPGP software (as well as receive such emails).
 ✔ Sign encrypted emails to let your recipients verify that the message is from you and that the content hasn’t been modified.

🌐 Website: https://flowcrypt.com/
📁 Source code: https://github.com/FlowCrypt/
📚 Documentation: https://flowcrypt.com/docs/
🧠 Knowledge Base: https://flowcrypt.com/blog/questions/
📱 Android & iOS apps: https://flowcrypt.com/download

📩 Looking forward to your feedback! Please email us at human@flowcrypt.com.
```

**Comment by sosnovsky** [comment]
Yeah, and probably screenshot files can have larger resolution, as currently they're blurry (or maybe chrome web store automatically compresses them)

**Comment by sosnovsky** [comment]
Then updated screenshots can be also used for Mozilla web store in https://github.com/FlowCrypt/flowcrypt-browser/issues/2859

**Comment by tomholub** [comment]
@vahram-papazyan could later prepare new screenshots that, once you two are happy with them, I'll upload to the web store. I'm unsubscribing until then, please assign me once ready. Thanks!

**Comment by vahram-papazyan** [comment]
I was trying to search for the flowcrypt extension but it doesn't find it. Decided to let you know.
 
![store](https://github.com/FlowCrypt/flowcrypt-browser/assets/22081012/b5a5665f-04e3-4b13-bbeb-7bb40c4e5b9d)

**Comment by vahram-papazyan** [comment]
@sosnovsky 
> Maybe it was some temporary issue, can you try to search it again?

Still the same
![store](https://github.com/FlowCrypt/flowcrypt-browser/assets/22081012/1eac13ed-8afe-4839-9fbd-95759bd26566)

I use Chromium, by the way, not Chrome. Here I don't have the featured option:

![store](https://github.com/FlowCrypt/flowcrypt-browser/assets/22081012/a2006996-968c-462e-9eb3-06a8a9b770e1)

The same in Brawe.

**Comment by sosnovsky** [comment]
I tried to search `flowcrypt` in Brave and it shows FlowCrypt extension in results too:

<img width="800" alt="Screenshot 2023-09-13 at 21 26 35" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/6727ae06-5d74-4ed2-98a5-1a19676bb290">

Does extension page load for you at https://chrome.google.com/webstore/detail/flowcrypt-encrypt-gmail-w/bnjglocicdkmhmoohhfkfkbbkejdhdgc ?

**Comment by vahram-papazyan** [comment]
> Does extension page load for you at https://chrome.google.com/webstore/detail/flowcrypt-encrypt-gmail-w/bnjglocicdkmhmoohhfkfkbbkejdhdgc ?

Yes, when I google "chrome web store flowcrypt" the first result is this link and it's working.

**Comment by vahram-papazyan** [comment]
@sosnovsky Did you save the background image you used for the existing screenshots?

**Comment by sosnovsky** [comment]
No, I don't have background from old screenshots. You can use solid green color as background for now, and I'll try to recreate the old one

**Comment by vahram-papazyan** [comment]
> No, I don't have background from old screenshots. You can use solid green color as background for now, and I'll try to recreate the old one

I have already created some samples with AI tools. 

![1](https://github.com/FlowCrypt/flowcrypt-browser/assets/22081012/140c2ad8-294b-44ec-a199-4dab766f6981)
![2](https://github.com/FlowCrypt/flowcrypt-browser/assets/22081012/eb3c7ea7-ad5c-410d-a83d-1c06bbe84ea3)
![3](https://github.com/FlowCrypt/flowcrypt-browser/assets/22081012/deaa461f-dba2-4d62-a0ae-2952d519c02a)
![4](https://github.com/FlowCrypt/flowcrypt-browser/assets/22081012/98d7d177-8937-4ba0-a699-4d55ad3002da)

What do you think? I like 1 and 3.

**Comment by sosnovsky** [comment]
It'll be nice to have lock icon pattern on the background, like on current screenshots, to highlight security of encrypted messages

**Comment by sosnovsky** [comment]
@vahram-papazyan I sent you invite to Figma project with screenshot template, let's use it for creating new screenshots - you can edit text and insert real screenshots there. Then you just need to export result images and we'll use them for replacing screenshots on Chrome Web Store

**Comment by vahram-papazyan** [comment]
> @vahram-papazyan I sent you invite to Figma project with screenshot template, let's use it for creating new screenshots - you can edit text and insert real screenshots there. Then you just need to export result images and we'll use them for replacing screenshots on Chrome Web Store

Okay, thank you.

**Comment by vahram-papazyan** [comment]
Drafts

![1](https://github.com/FlowCrypt/flowcrypt-browser/assets/22081012/287e0dcf-11e3-4c43-982e-76d5d4c4350f)

**Comment by sosnovsky** [comment]
Looks nice 👍

**Comment by vahram-papazyan** [comment]
@sosnovsky I think we can also update the description text. Something like this (not a final version)

```
A simple end-to-end encryption to secure your emails and attachments on Google, including G Suite, Business and Enterprise using OpenPGP.

FlowCrypt lets you use PGP encryption by generating a private and public key. It uses the recipient’s public key to encrypt the email and only the recipient’s private key can decrypt the message and reveal its content.

Adds a Secure Compose button to Gmail. This way, you can send private PGP encrypted emails when you choose to:
 - Sets up in a few clicks
 - Generate private keys using the ECC and RSA (up to 4096-bit) algorithms.
 - Use FlowCrypt’s own Attester public key server
 - Send and receive encrypted emails and attachments (up to 25MB, with previewing functionality) to anyone
 - Send and receive encrypted emails directly or through Encrypted Contact Page
 - Compose password-protected emails to send encrypted emails to the recipient who doesn’t have any OpenPGP software.
 - Sign encrypted emails to let your recipients verify that the message is from you and that the content hasn’t been modified 

Website: https://flowcrypt.com/
Source code: https://github.com/FlowCrypt/
Documentation: https://flowcrypt.com/docs/
Knowledge Base: https://flowcrypt.com/blog/questions/
Android & iOS mobile apps: https://flowcrypt.com/download

Looking forward to your feedback! Email us at human@flowcrypt.com - we are improving the plugin on a weekly basis (see the "Updated" field to the right).
```

**Comment by sosnovsky** [comment]
> I think we can also update the description text. Something like this (not a final version)

Good idea, let's update it too

**Comment by vahram-papazyan** [comment]
@sosnovsky Done. Both the screenshots and text are ready.

**Comment by sosnovsky** [comment]
Well done 👍
Let's just change `We update the extension weekly` to `We update the extension regularly` in description text

**Comment by vahram-papazyan** [comment]
> Well done 👍 Let's just change `We update the extension weekly` to `We update the extension regularly` in description text

Done

**Comment by sosnovsky** [comment]
Done ✅

**Comment by sosnovsky** [comment]
> @sosnovsky Will it require some time to see the updates? I still see the old version

Yes, I submitted new release 8.5.3 with new text and screenshots to chrome web store review, they should be updated after release is approved, probably today or tomorrow.

**Comment by sosnovsky** [comment]
@vahram-papazyan the latest build was approved, now chrome web store page shows updated information - https://chromewebstore.google.com/detail/flowcrypt-encrypt-gmail-w/bnjglocicdkmhmoohhfkfkbbkejdhdgc
