### ISSUE TITLE
Is initial screen really necessary?

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#5235]
As the title suggests, is the initial screen below necessary? Why do we display the initial screen (settings/initial.htm) instead of directly showing setup screen(settings/index.htm) after the user installs the extension?

I have always considered it unnecessary to have to click the `Flowcrypt` extension icon in the extensions list by clicking the extensions button.

Is there a specific reason why we need to show this initial screen after the user installs the extension?

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/9abf2966-7ecc-4eea-a0f5-4ccdcbbb3079)

cc: @tomholub  @sosnovsky

**Comment by tomholub** [comment]
to train the user. without it, they may never learn there even is a flowcrypt extension button to click. they may never find the settings again, should they need it.

**Comment by ioanmo226** [comment]
I see
