### ISSUE TITLE
Improve README 

### ISSUE THREAD

**Issue by vahram-papazyan** [FlowCrypt/flowcrypt-browser#5237]
- Fix projet title
- Add icons

**Comment by vahram-papazyan** [comment]
@sosnovsky The project title here includes "Encrypt Gmail with OpenPGP" while the iOS and Android repos include "Encrypt email with PGP". Can we change OpenPGP to PGP here, or PGP to OpenPGP in mobile app repos?

**Comment by sosnovsky** [comment]
let's use `Encrypt email with PGP`, so it'll be the same as title on chrome extension page - https://chrome.google.com/webstore/detail/flowcrypt-encrypt-gmail-w/bnjglocicdkmhmoohhfkfkbbkejdhdgc
