### ISSUE TITLE
click on reply fist -> click add to contacts later -> gray should refresh

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#524]

**Comment by tomholub** [comment]
1) receive a public key from a person who does not have public key recorded on Attester
2) click reply, to find that their email shows in gray
3) click "SAVE CONTACT" in the rendered public key above (in their original message)
4) notice the recipient stays gray. It would be great if it could turn green.

I don't know what's a good way to do this, maybe a broadcast browser message using `BrowserMsg` that the reply box could be listening to, and when received, check contacts storage for all recipients currently marked as gray, and re-render the recipients if new pubkey found.

**Comment by michael-volynets** [comment]
@tomholub I can't understand what this code does:
```
        const element = $(this.factory.btnReply()).insertBefore($(lastReplyBtn).children().last());
        if (isEncrypted) {
          element.click(Ui.event.prevent('double', Catch.try(this.setReplyBoxEditable)));
        } else {
          element.click(Ui.event.prevent('double', Catch.try(() => this.replaceStandardReplyBox(true, true)))); // xss-safe-factory
        }
```

I see when the message isn't encrypted but there is a public key file, the reply button (in the top-right corner) doesn't work. 

If I replace the whole `if...else` statement with
```
          element.click(Ui.event.prevent('double', Catch.try(this.setReplyBoxEditable)));
```
everything works well on encrypted and non encrypted messages.

**Comment by tomholub** [comment]
Thanks for asking! The main difference seems to be that it's using `this.replaceStandardReplyBox(true, true)` where the second `true` is `force` (which default to `false`). Which is used here:
```js
const doReplace = Boolean(convoRootEl.find('iframe.pgp_block').filter(':visible').length || (convoRootEl.is(':visible') && force));
```
Without `force` set as true, it would not replace the standard gmail reply box if the conversation has no encrypted elements in it yet (normal plain conversation).

So that would be something for you to double check:
1) open standard plain conversation
2) click encrypted reply
3) if all is good, you can replace it with your version

If you do replace it, please link in the PR to this comment so that I know to test it very thoroughly myself.

**Comment by tomholub** [comment]
Works very well. This will help usability a lot, especially for new users who need to write to someone who uses non-FlowCrypt software.
