### ISSUE TITLE
Different sender name is displayed for encrypted emails sent by the extension

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5254]
Description: We received a bug report in which the receiver of an encrypted message sent using FlowCrypt sees a sender name that is different from what it should be.

For example, I send an encrypted email from my test account to my corporate account. The profile name of the test account is "Test Account", which was formerly known as "Mart Robles".

When the receiver opens the email, they see that the sender name is set to the former name instead of the current one.

![Screenshot 2023-06-26 at 1 34 39 PM](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/87c3cc39-923a-4882-8f40-097ad1d7a96a)

![Screenshot 2023-06-26 at 1 35 07 PM](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/4d780e4d-620a-44c8-95a2-a138acd0594d)

The reporting user also shares a test email which confirms the following issue: https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/FMfcgzGsnLGRgMHPqpKsCBjgJGTDMqSB

They also added that the problem does not occur when sending an original email sent by Gmail, which I have also confirmed.

Reference:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGsnLCzRmkRSSxcGFVqLrKhMSGd

**Comment by ioanmo226** [comment]
@sosnovsky You want me to have a look at this task too before moving on iOS?

**Comment by sosnovsky** [comment]
@ioanmo226 please work on this one too before switching to iOS. To reproduce - change name in your Google account and try to send email with FlowCrypt, message `From` field will use your old name

**Comment by ioanmo226** [comment]
We tried to get `from` value from saved `sendAs` in `Storage`. That's why `sender name` might be deprecated.
Maybe we should call `refreshSendAs` in `getEmailWithOptionalName` for the first time when it's called?

https://github.com/FlowCrypt/flowcrypt-browser/blob/b4765bf1a1cb9915b6653f5ef112b8c691c7ac29/extension/chrome/elements/compose-modules/compose-input-module.ts#L79

https://github.com/FlowCrypt/flowcrypt-browser/blob/4a236411a2e954b08212b13ad580a02e340de9b7/extension/chrome/elements/compose-modules/compose-storage-module.ts#L189

**Comment by sosnovsky** [comment]
I think we already perform `refreshSendAs` when opening compose box - https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/chrome/elements/compose-modules/compose-sender-module.ts#L26, but updates are not applied to sender name

**Comment by ioanmo226** [comment]
Hmmm... You are right. I thought `refreshSendAs` was not called, but it was actually indeed called.

However, the problem is that the Gmail `users/me/settings/sendAs` API returns an outdated `displayName` (even though I changed my Google account name to my full name).

I suppose there isn't much we can do for now?

https://github.com/FlowCrypt/flowcrypt-browser/blob/a5f53bc6d23d9ba3b415563c1b048d4e631fa26c/extension/js/common/api/email-provider/gmail/gmail.ts#L311

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/1b470527-aeec-4292-bc6c-4b60ad9741fe)

**Comment by sosnovsky** [comment]
Interesting, I checked my response for `/settings/sendAs` and it has empty `displayName`, but `from` field still uses my old name. It seems we fetch sender name somewhere else, maybe it's possible to get current name of Google account there

**Comment by ioanmo226** [comment]
Well, we first try to get name value from email and then try to get `name` from storage `sendAs` value (which was `displayName` field in `settings/sendAs` api)
If those are all empty, then we try to get name from public key for that email.

In either way, I think we won't be able to get updated sender name I guess.

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/62a802fd-78a5-40f6-b70d-2a0fb31b0f72)

**Comment by sosnovsky** [comment]
I re-checked Gmail API and found that `GET /settings/sendAs` response always has `displayName = ''` for first object, it's populated only for next objects (`sendAs[1]`, `sendAs[2]`, `sendAs[3]` etc, but not `sendAs[0]`)

Also checked `/tokeninfo` endpoint - it returns `idToken` which initially included user's `displayName`, but after I changed name for my Google Account - `displayName` disappeared from `idToken`, which is strange. But maybe user needs to re-authenticate extension to get another token with correct name, I didn't test it as it's still not convenient for users.

And finally there is https://www.googleapis.com/oauth2/v2/userinfo endpoint which always returns current Google Account name. So I think we should use it somewhere along with `refreshSendAs`, to fetch current user name.

What do you think?

**Comment by ioanmo226** [comment]
AFAIK, customer enterprise environments use gmail, oauth2, people subdomain of googleapis.com and didn't allow wildcard googleapis.com domain?
Currently trying to find oauth2.googleapis api which will return correct user name.

**Comment by ioanmo226** [comment]
I just found this api `https://people.googleapis.com/v1/people/me?personFields=names` and it's returning data what we are expecting.
What do you think?

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/72fb9167-db1a-463b-8d9a-781531b49880)

**Comment by sosnovsky** [comment]
> I just found this api `https://people.googleapis.com/v1/people/me?personFields=names` and it's returning data what we are expecting.
> 
> What do you think?
> 
> 
> 
> ![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/72fb9167-db1a-463b-8d9a-781531b49880)
> 
> 

Looks good, let's use it
