### ISSUE TITLE
The attachment in the encrypted MIME message is not recognizable by the FlowCrypt extension.

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5258]
> I have noticed an unrelated problem. It seems that the attachment in an encrypted MIME message is not recognized by the FlowCrypt browser extension.

Sample encrypted mime message: https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/FMfcgzGsnLNMcnLqxmcDmbBfNbZbnJfr

_Originally posted by @martgil in https://github.com/FlowCrypt/flowcrypt-browser/issues/5248#issuecomment-1608901026_

**Comment by sosnovsky** [comment]
@martgil how this message was sent - from FlowCrypt browser extension using `Include your public key`?

**Comment by martgil** [comment]
The message was crafted and sent like this:

1. On Gmail,  compose an email with an attachment (eg. public key attachment) and send it to yourself.
2. Open the email and view the MIME message by clicking the see more options icon indicated by 3-dots -> Show original.
3. Copy the entire MIME message.
4. Paste the MIME message on FlowCrypt secure compose, make sure sending options was "Encrypt, sign and send" and send the email to yourself once again.
5. Open the encrypted email and noticed that the attachment is missing.

For example, here is the original message that was encrypted in the sample email above: https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/QgrcJHsNhMkClrLTFKPTBgRVnPRrbRBGZxv

**Comment by sosnovsky** [comment]
@martgil I checked MIME content of original message (by clicking `Show original`) and it doesn't contain attachment body, only id, which is used Gmail downloads attachment content. So copying this mime won't copy attachment data, only message text, that's why encrypted message doesn't contain attachment.

**Comment by martgil** [comment]
Thank you very much. it is just okay? Or could we use the Gmail API to retrieve/render the attachment based on the attachment id included on the mime message?

**Comment by sosnovsky** [comment]
> Thank you very much. it is just okay?

Yes, I think it's expected behavior, as only text content was copied from MIME content.

> Or could we use the Gmail API to retrieve/render the attachment based on the attachment id included on the mime message?

For retrieving attachment we need message id and attachment id, so if we copy just attachment id from MIME of message X then it won't work for another message Y.
