### ISSUE TITLE
Leading tab is dropped when sending a message

### ISSUE THREAD

**Issue by rrrooommmaaa** [FlowCrypt/flowcrypt-browser#5268]
We have a failing test `compose - leading tabs` now, probably after #5226 was merged?
the text `\tline 1\n\t\tline 2` loses its initial tab and becomes `line 1\n\t\tline 2`. This happens on sending -- the encrypted message is missing the tab, so re-rendering of the sent message is correct.

**Comment by sosnovsky** [comment]
Yes, and also `test_patterns` has following error:
```
unchecked xss in extension/js/common/platform/xss.ts:186: 00:01
      pre.innerHTML = pre.innerHTML.replace(/\n/g, br); 00:01
patterns.ts: Found 1 unhandled patterns, exiting
```

**Comment by sosnovsky** [comment]
> We have a failing test compose - leading tabs now, probably after https://github.com/FlowCrypt/flowcrypt-browser/pull/5226 was merged?
the text \tline 1\n\t\tline 2 loses its initial tab and becomes line 1\n\t\tline 2. This happens on sending -- the encrypted message is missing the tab, so re-rendering of the sent message is correct.

#5226 should be applied only to `<pre>` tags, need to check if this change caused initial tab deletion
