### ISSUE TITLE
maximum width of online images to be the full width of the frame?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#5278]
When I enter an image that is super wide, say 2000px, it will make the encrypted iframe scrollable horizontally, which makes text hard to read.

Most email clients also do this, but I think it's nonsense. I think the image size when rendered should be capped at 100% of available space, meaning it should get shrunk, so that whole image and text remains normally visible without scrolling horizontally.

**Comment by martgil** [comment]
test email - https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/FMfcgzGtvsWtTVQzSlPrkVBTPdWVKvSJ
