### ISSUE TITLE
404 when calling client-configuration?domain=flowcrypt.dev during tests on PROD?

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#5296]
title: Error
message: failed to log into google in newGoogleAcctAuthPromptThenAlertOrForward
url: chrome-extension://iolmfhiemifblfacllafaecfngheoabl/chrome/settings/index.htm?account_email=ci.tests
line: 377
column: 15
environment: chrome:ex:fork
build type: consumer 

This actually happens in our CI. Please can you check which test causes this? It's weird that it calls PROD FES, maybe it's a live gmail test?

If this is a mock test, we should fix that, it should not be calling live services.

If it is a live test, we'll decide what to do with it once we see the test.

```
Error: failed to log into google in newGoogleAcctAuthPromptThenAlertOrForward
at Catch.nameAndDetailsAsException (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:377:15)
at Catch.report (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:103:34)
at Settings.newGoogleAcctAuthPromptThenAlertOrForward (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/settings.js:390:27)
at async SettingsView.<anonymous> (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/chrome/settings/index.js:198:28)


details:
[typeof:object:[object Object]] {"result":"Error","error":"Grant successful but error accessing fc account: Error: Not Found: 404 when GET-ing https://flowcrypt.com/shared-tenant-fes/api/v1/client-configuration?domain=flowcrypt.dev (no body): -> Missing client configuration for domain flowcrypt.dev","acctEmail":"ci.tests."}

### Catch.reportErr calling stack ###
# at Catch.formatExceptionForReport (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:273:90)
# at Catch.onErrorInternalHandler (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:81:29)
# at Catch.reportErr (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:97:18)
# at Catch.report (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/platform/catch.js:103:18)
# at Settings.newGoogleAcctAuthPromptThenAlertOrForward (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/js/common/settings.js:390:27)
# at async SettingsView.<anonymous> (chrome-extension://iolmfhiemifblfacllafaecfngheoabl/chrome/settings/index.js:198:28)
#
# url: chrome-extension://iolmfhiemifblfacllafaecfngheoabl/chrome/settings/index.htm?account_email=ci.tests.gmail@flowcrypt.dev
#
######################
```

**Comment by martgil** [comment]
I think I have found the issue. It is from the mock test used when the test is specified for live Gmail test. It is present in `BrowserRecipe.setUpCommonAcct()`. I will gather more information.

https://github.com/FlowCrypt/flowcrypt-browser/blob/605a8fd2795d74a9c3459edabd6a3098640f9c0c/test/source/tests/tooling/browser-recipe.ts#L96C64-L96C64

**Comment by martgil** [comment]
@sosnovsky Some other tests are failing too often than what it used to be before. Could it be because of this one?

**Comment by sosnovsky** [comment]
I think it depends on test - I noticed that `automatic update of key found on key manager` fails often, but it's quite big and locally passes for me on each run, so I haven't found exact reason for it fail. There was another test which fails when running with puppeteer v21.1.1, after changing puppeteer version back to v21.1.0 - it passes.

Which tests are failing for you?

**Comment by martgil** [comment]
Yeah, I noticed that too -- there are like 3 of these tests that are just taking turns to appear though sometimes they are like two of these. I can't point it out exactly but I can barely remember those failing error contains terms like `passphrase`, and `key manager`... I'll update my comments later after this -- I have also tried checking those failing errors locally and those are passing on my machine as well. Thank you very much for checking this.

**Comment by sosnovsky** [comment]
Also currently debug information for failed tests on Semaphore doesn't contain detailed information about fail reason and screenshots - https://github.com/FlowCrypt/flowcrypt-browser/issues/5396. Fixing this issue will be helpful for better understanding of test failures

**Comment by martgil** [comment]
For example in PR 5381, this happens. There will be at least one test that would fail.

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/678bcc9b-620e-4cae-a545-fc588875bf96)

It the test passes when tested locally: 
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/4a2f218c-e9d2-4537-9fac-4f23039cde36)

**Comment by sosnovsky** [comment]
Looks like something wrong with test results parsing - if you go to https://flowcrypt.semaphoreci.com/jobs/b0bd8ede-4690-4a2a-bf8e-40ca5349545a, there this test passed successfully, and fail happened in another one:

<img width="800" alt="Screenshot 2023-09-05 at 13 00 06" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/a904e372-6c1f-43ce-8819-f9e8f993a4a1">

**Comment by martgil** [comment]
OH - that is true, in fact, there's no failing test ever mentioned at https://flowcrypt.semaphoreci.com/jobs/b0bd8ede-4690-4a2a-bf8e-40ca5349545a

**Comment by sosnovsky** [comment]
In the latest builds mentioned issue didn't occur, maybe was fixed on FES side.
