### ISSUE TITLE
Re-enable BrowserMsg.addPgpListeners() if needed

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5304]
We have a couple comments saying `// BrowserMsg.addPgpListeners(); // todo - re-allow when https://github.com/FlowCrypt/flowcrypt-browser/issues/2560 fixed`:
- https://github.com/FlowCrypt/flowcrypt-browser/blob/c5e719146092df0b90b4418792ff5fac45872142/extension/chrome/settings/inbox/inbox.ts#L107
- https://github.com/FlowCrypt/flowcrypt-browser/blob/c5e719146092df0b90b4418792ff5fac45872142/extension/js/content_scripts/webmail/webmail.ts#L153

https://github.com/FlowCrypt/flowcrypt-browser/issues/2560 is closed, so we can re-enable this code, if it's still needed after reworking decryption process.

**Comment by rrrooommmaaa** [comment]
All Pgp/X.509 operations and the related cryptographic libraries will be completely removed from the `background` page in one of following PR for task #1509 
So all the cryptographic handlers will be placed in webmail and inbox pages, so we can uncomment or remove this line.
So far a couple of handlers remain in `background`.

**Comment by sosnovsky** [comment]
Then we can just remove these lines, as everything works without these listeners, so it'll be less to remove from background page in the future.
