### ISSUE TITLE
Unable to send password messages if the contact name retrieved from contacts.google.com includes emoji

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5308]
Error message:
```
--------- BUG REPORT ----------

[name]
composer: send: bad request (errMsg: Bad recipient)

[stack]
    at BrowserExtension.prepareBugReport (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/browser/browser-extension.js:8:44)
    at ComposeErrModule.handleSendErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-err-module.js:115:61)
    at async ComposeSendBtnModule.extractProcessSendMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-send-btn-module.js:117:21)

url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?frameId=frame_FyyyfGeQfc&acctEmail=[SCRUBBED]&parentTabId=241918943%3A0


[error]
{
  "status": 400,
  "url": "https://flowcrypt.com/shared-tenant-fes/api/v1/message",
  "responseText": "{\"code\":400,\"message\":\"Bad recipient\",\"details\":\"Invalid RFC 5322 mailbox User Name⭐️ Real Name <user@corp.test>\"}",
  "statusText": "Bad Request",
  "resMsg": "Bad recipient",
  "resDetails": "Invalid RFC 5322 mailbox User Name⭐️ Real Name <user@corp.test>"
}

[details]
{}
```
Steps to reproduce:
1. Create a contact at contacts.google.com and name it `Example ⭐️ Name`, fill in the email address field and save.
2. Use FlowCrypt's secure compose and compose a password protected message for `Example ⭐️ Name`. Click enable google contact search and grant the required permission.
3. Finish composing the secure email, set a password, and send the email and you'll get the following error:
<img width="581" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/08d4a40c-ce00-4a0f-bdab-6682eb642a17">
4. Click 'ok' and you'll get the following stack trace above when you are about to report the issue.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGtwDDWqBNzHzXpZhWdNvJlBXNs

**Comment by tomholub** [comment]
I think it would be acceptable to strip out the emoji

**Comment by tomholub** [comment]
But if you fix the emoji case, doesn't it automatically fix all UTF situations? In that case just one test would be enough.

I don't like apostrophes in emails, I'm quite ok to not support them :laughing: ... I think they are ridiculous

**Comment by sosnovsky** [comment]
> But if you fix the emoji case, doesn't it automatically fix all UTF situations?

In https://github.com/FlowCrypt/flowcrypt-browser/pull/5321 we just strip all utf-8 symbols which are emojis, so other utf-8 symbols are still left in the recipient name. To make it work for all cases we'll need to strip all utf-8 symbols, but then it can lead to unexpected behavior for users - Mart mentioned recipient with Chinese characters in the name, stripping these characters will lead to broken name.

I think it'll be better to add support for all these utf-8 symbols, maybe it needs just changing of our validation rules, as I tried to send FES message with emoji in subject field and it worked well, error appears only when emoji is in recipient name.

**Comment by sosnovsky** [comment]
@martgil can you please share failing examples for this cases over email:
- case where the email address in mailbox format User Name <user@corp.test> contains bullet points
- mailbox format emails containing an apostrophe (') 
- a mailbox with a Chinese contact name.

thanks!

**Comment by martgil** [comment]
Hello @sosnovsky, thanks - I have shared the contact name examples over email.
