### ISSUE TITLE
bad CC returned on pasted email in cc field when sending a password messages

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5309]
Description: The FlowCrypt secure compose is unable to send email on a certain email address that is copy and pasted into the CC field.

Stack trace:
```
--------- BUG REPORT ----------

[name]
composer: send: bad request (errMsg: Bad CC recipient)

[stack]
    at BrowserExtension.prepareBugReport (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/js/common/browser/browser-extension.js:8:44)
    at ComposeErrModule.handleSendErr (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-err-module.js:115:61)
    at async ComposeSendBtnModule.extractProcessSendMsg (chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose-modules/compose-send-btn-module.js:117:21)

url: chrome-extension://bnjglocicdkmhmoohhfkfkbbkejdhdgc/chrome/elements/compose.htm?frameId=frame_oDNWAIndcy&acctEmail=[SCRUBBED]&parentTabId=1779525868%3A0


[error]
{
  "status": 400,
  "url": "https://flowcrypt.com/shared-tenant-fes/api/v1/message",
  "responseText": "{\"code\":400,\"message\":\"Bad CC recipient\",\"details\":\"Invalid RFC 5322 mailbox ​User NAME <test@example.com>\"}",
  "statusText": "Bad Request",
  "resMsg": "Bad CC recipient",
  "resDetails": "Invalid RFC 5322 mailbox ​User NAME <test@example.com>"
}

[details]
{}
```

### Steps to reproduce:

Sample email address that would trigger the error: `​Test ADDDRE <f.test@example.com>`

1. Use the FlowCrypt secure compose and compose a password-protected message.
2. In the `To` field, put `user1@example.com`. For the `CC` field, copy the above email address payload and paste it directly into the `CC` field. The FlowCrypt browser extension will parse the email address from it and render it to the extension page successfully.
3. Provide an email body and a password and send the email.
4. Notice you'll get an error message. click 'ok' and you'll be taken to the bug report submission page where the error description is described as the above.

Reference [reported by a user under customer domain]: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGtwDCPsZMXDWZcJkDGLmqxDtsr

**Comment by martgil** [comment]
The email address above has a zero width space character E2 80 8B HEX UTF-8 bytes - https://www.cogsci.ed.ac.uk/~richard/utf-8.cgi?input=342+200+213&mode=obytes. And probably even more zero-width space chars can trigger the error. Gmail does allow sending emails to email addresses such as the one with spaces. The only problem right now is that space chars are not well-defined yet.

**Comment by sosnovsky** [comment]
Similar to https://github.com/FlowCrypt/flowcrypt-browser/issues/5308

**Comment by martgil** [comment]
@sosnovsky this is partially part of #5308 and they somehow shared on test present in #5321 . Should I move it to enterprise-server repo?

**Comment by sosnovsky** [comment]
Ah, we already have similar issue on `enterprise-server` repo, fix should be included in the next release - https://github.com/FlowCrypt/enterprise-server/pull/5332

So this issue can be closed
