### ISSUE TITLE
add skeleton of `ConfiguredIdpOAuth` class

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#5318]
- [x] a new class called `ConfiguredIdpOAuth` that inherits from `OAuth`. It should contain new method called `newAuthPopupForEnterpriseServerAuthenticationIfNeeded`
- [x] The method checks the storage for `authentication` and decides if a custom IdP is used or not. If custom IdP is not used, it just returns `Promise<void>`.
- [x] else it shows a warning modal `Custom IdP is configured on this domain, but it is not supported on browser extension yet. Authentication with Enterprise Server will continue using Google IdP until implemented in a future update.`
- [x] this new method should be called in `newGoogleAcctAuthPromptThenAlertOrForward`, right under `await GlobalStore.acctEmailsAdd(response.acctEmail);` inside the success case
- [x] update the test from earlier issue #5317 to also expect this modal

**Comment by tomholub** [comment]
@martgil this is now ready to work on

**Comment by martgil** [comment]
Thanks, @tomholub! I'll start working on this as soon as I finish all my tasks for milestone 8.5.1.
