### ISSUE TITLE
Drafts don't save attachments

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#534]
Having CryptUp save drafts is awesome. 

Although I noticed that it did not save the attachment.

**Comment by tomholub** [comment]
Ha. Didn't think of that.

**Comment by tomholub** [comment]
Contributor: 
 - when saving draft, also upload attachments (unless the attachment did not change).
 - When removing an attachment, also remove it from the gmail draft.
 - When adding attachment, trigger a new draft save.
 - When loading msg from draft, also load attachments.

This is a prerequisite to #1211

**Comment by michael-volynets** [comment]
Hello @tomholub, 

Is there a way to convert Att to a file? I save 'Att's in a draft but I can't turn it back to the 'File'

**Comment by michael-volynets** [comment]
I've resolved the issue with the file.

**Comment by tomholub** [comment]
Sorry for responding slowly. I'm not really sure which `File` you meant. If it's something to pass to Ajax, you may want to look at what the `Api.s3` api call does.

**Comment by tomholub** [comment]
I'm marking it as not actionable, the code complication is not quite worth it. Maybe later.

**Comment by tomholub** [comment]
related PR run into issues, may be lacking Gmail API
