### ISSUE TITLE
CI secrets not found

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5343]
Tests on CI are failing with error `Secret flowcrypt-browser-ci-secrets not found`

https://flowcrypt.semaphoreci.com/workflows/2e68c0af-e286-41bb-9e15-81f2230019f0

**Comment by sosnovsky** [comment]
@tomholub I checked Semaphore secrets settings, and there is no `flowcrypt-browser-ci-secrets` item there, do we have any backup of these secrets?

**Comment by tomholub** [comment]
Yes I think I screwed them up when updating. I will have to take a look tonight. I don't think we have a backup, but they get created with a shell script, which maybe broke so I have to check it.

**Comment by tomholub** [comment]
I pushed them all back, from my local copies, and fixed the scripts. And added the needed secrets to the deploy server. Hopefully these secrets I pushed are up to date.

**Comment by tomholub** [comment]
I re-run it, it's not immediately failing anymore. If it still gives you trouble, let me know, same for iOS. cc @ioanmo226
