### ISSUE TITLE
Attachment blocks are duplicated when filename contains non-alphanumeric symbols

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5345]
<img width="320" alt="Screenshot 2023-08-03 at 13 38 50" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/110b9a4d-18a6-4eee-bcf6-8560c9738afd">

Gmail replaces emoji in filename with `<img>` and it makes our regex for filename in [processAttachments](https://github.com/FlowCrypt/flowcrypt-browser/blob/8daed5fbe9008d246b0301b4f7952137eef1777e/extension/js/content_scripts/webmail/gmail-element-replacer.ts#L434) to fail.

Possible solution - remove emojis from filename in regex and ignore `<img>` tags, then regex should work

**Comment by ioanmo226** [comment]
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/a0f9338e-6e1b-4ac3-a20b-1e635ae2724d)

**Comment by ioanmo226** [comment]
This one too.

**Comment by sosnovsky** [comment]
Probably because of `!` symbol
