### ISSUE TITLE
Error: composer: send: bad request (errMsg: Missing recipient)

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5350]
### Description: 
The following error occurs when sending a password-protected message and specifying the sender only in either `cc` or `bcc`. 

### Stack trace:
```
--------- BUG REPORT ----------

[name]
composer: send: bad request (errMsg: Missing recipient)

[stack]
    at BrowserExtension.prepareBugReport (chrome-extension://mimchhddcelobciniokjnakmkcbdggof/js/common/browser/browser-extension.js:8:44)
    at ComposeErrModule.handleSendErr (chrome-extension://mimchhddcelobciniokjnakmkcbdggof/chrome/elements/compose-modules/compose-err-module.js:115:61)
    at async ComposeSendBtnModule.extractProcessSendMsg (chrome-extension://mimchhddcelobciniokjnakmkcbdggof/chrome/elements/compose-modules/compose-send-btn-module.js:117:21)

url: chrome-extension://mimchhddcelobciniokjnakmkcbdggof/chrome/elements/compose.htm?frameId=frame_bRfSCOIBlu&acctEmail=[SCRUBBED]&parentTabId=276893792%3A0


[error]
{
  "status": 400,
  "url": "https://flowcrypt.com/shared-tenant-fes/api/v1/message",
  "responseText": "{\"code\":400,\"message\":\"Missing recipient\",\"details\":\"For more details, see FlowCrypt External Service logs.\"}",
  "statusText": "Bad Request",
  "resMsg": "Missing recipient",
  "resDetails": "For more details, see FlowCrypt External Service logs."
}

[details]
{}
```

### Expected Behavior:
The password protected message should be sent regardless of the recipient fields like sending regular email with Gmail or encrypted email with the FlowCrypt browser extension. Or, if the `To` recipient field is required, we could add a check and inform the user by showing an informational message through a modal.

Reference: 
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGtwWDKpWNlwlzmQxGwhBwPfdGb

**Comment by sosnovsky** [comment]
Here it should be better to have the same behavior as Gmail (and our encrypted messages) - allow to have only CC or BCC set. It should be fixed on FES side, I filed an issue there - https://github.com/FlowCrypt/enterprise-server/issues/5181
