### ISSUE TITLE
Possible Layout update for the user's current plan. 

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#536]
The current logo has the subscription plan immediately to it's right.
It makes the logo feel a bit cluttered and less memorable. 

I would like to propose that we move it to the centered at the bottom of the page.
Also putting Terms and Privacy below that. 

Let me know what you think.

<img width="806" alt="screen shot 2017-02-26 at 2 05 00 am" src="https://cloud.githubusercontent.com/assets/3431871/23338178/322ee4ee-fbc9-11e6-9ec6-36c2b36018be.png">

**Comment by tomholub** [comment]
Maybe on top of the email address would be the best place. That way account info is together. Or to the left of it, or below it

**Comment by tomholub** [comment]
dated
