### ISSUE TITLE
Long clipped encrypted message isn't decrypted

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5370]
I received encrypted message which was clipped and didn't end with `----END PGP MESSAGE----`:

<img width="400" alt="Screenshot 2023-08-18 at 12 40 24" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/da936a82-5ec8-427c-9b86-fbca6b0499ac">

After clicking `3-dots` button:

<img width="400" alt="Screenshot 2023-08-18 at 12 42 04" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/ec6784cb-6614-481e-82e9-f8dd32b042f7">

FlowCrypt didn't detect that it's encrypted message and didn't try to decrypt it.

**Comment by tomholub** [comment]
This used to work, like there was code specifically to handle this situation. It would fetch the message from Gmail API in these circumstances.

Also problem on Chrome?

**Comment by sosnovsky** [comment]
Yes, it happens on both - Chrome and Firefox.

Maybe it's some edge case when only last line is clipped, I'll look into code which should handle such situations, can be a small fix

**Comment by tomholub** [comment]
Hahaha that would be quite lucky to hit that exact length. Plausible.
