### ISSUE TITLE
Debug html attachments on Semaphore not contain screenshots

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5396]
Previously debug html attachments had screenshots and information about reason for test failure, but currently they have only mock API logs (example - https://flowcrypt.semaphoreci.com/jobs/0be03fb0-c584-4943-b6d5-4164e2a94ce3/artifacts)

Issue probably appeared after updating to Puppeteer 21.0.0, as `testFailSingleAttemptDebugHtml` fails with error `Error: Requesting main frame too early!`. It works well in Puppeteer 20.9.0

**Comment by tomholub** [comment]
Related issue, the debug files are not getting uploaded to Semaphore at all. I'll try to address that in #5748
