### ISSUE TITLE
Sending password-protected message without recipients in "To" field returns reportable error message

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5399]
Description: A reportable error message occurs when sending a password-protected message without specifying any recipients in the "To" fields and the "Bcc" and/or "cc" the one that is populated. Users might get confused about such an error that is caused by simply not having a recipient in the "To" fields.

There are two key points that could ideally need to be updated to improve the described scenario above.

1. ) The particular error above should be handled differently in a way that it wouldn't be reportable -- eg. replaced by a simple modal stating that the "to" field is required.
2.) Let the user send password messages without any recipients being specified in the "To" field, just like how the extension behaves when writing PGP-encrypted messages. (still need point number 1 to be implemented together with this one) 

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGtwzjdChsRnXlKJwTMjpQlbxWN

**Comment by sosnovsky** [comment]
We have an issue in `enterprise-server` repo for allowing password-protected messages without `To` recipient - https://github.com/FlowCrypt/enterprise-server/issues/5181

> (still need point number 1 to be implemented together with this one)

I think it's not needed, as there won't be any error when sending message without `To` recipient.

**Comment by martgil** [comment]
The error occur exactly when sending a password protected message in either in "bcc" or "cc" and the error only triggered when proceeding to send the password message if it doesn't have a recipient in the "To" field.

**Comment by martgil** [comment]
Can I close this one now since it won't exists when https://github.com/FlowCrypt/enterprise-server/issues/5181 gets implemented?

**Comment by sosnovsky** [comment]
Yes, this one can be closed
