### ISSUE TITLE
Non-encrypted HTML page tries to render by the extension as encrypted results to unreadable regular emails

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5422]
Description: The FlowCrypt browser extension tries to render an HTML email as encrypted message which results to the following error message: "Problem extracting armored message". The email turns into a what seems to be a PNG file based on its chunked contents displayed after clicking the "show original message".

<img width="1008" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/5339b267-077d-42ed-a6a7-dfbeae7aa37d">

Test email shared by the user:
https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/FMfcgzGtxKSjkJdCkwlFDhfgdPdWRXnH

Affected users:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGtwztzFgmFHWJxmltxxtSztfTm
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGtwzspsmJwqdjqXbtKZPQVmtdF

**Comment by martgil** [comment]
Additional information: This happens because of a file name 'noname' that contains an image data. The extension treat this as an encryptedMsg type so that it returns the following error with the error message contains a PNG meta data.

**Comment by martgil** [comment]
There is this case where the 'noname' file with the content type of 'application/octet-stream' but with a bytes of png and indeed was a png file when opening it. they were using using this image as an cid image embedded in a regular emails.

**Comment by tomholub** [comment]
closing this issue in this milestone to reflect the work already done in merged PR.

Filed a new issue #5450 for remaining work, in next milestone.
