### ISSUE TITLE
Release 8.5.1

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5434]
roma:
 - [x] release notes in milestone

tom:
 - [x] release firefox
 - [x] test firefox
 - [x] release chrome consumer
 - [x] release chrome enterprise
 - [x] notify customers
 - [x] share chrome enterprise with customers

**Comment by sosnovsky** [comment]
@tomholub I think we can publish a new 8.5.1 release of browser extension, it's already includes many improvements and fixes for issues reported by customers and users.

I added release notes to milestone description.

**Comment by sosnovsky** [comment]
Also Vahram prepared new screenshots and updated description for Chrome web store:
- screenshots - https://drive.google.com/drive/folders/1Z_45H1zJn73CrhJl3o_EWXoiyIpfg9U-?usp=sharing
- description:
```
🟢 A simple end-to-end encryption to secure your emails and attachments on Google, including G Suite, Business, and Enterprise using OpenPGP.

🟢 FlowCrypt lets you use PGP encryption by generating a private and public key. It uses the recipient’s public key to encrypt the email, and only the recipient’s private key can decrypt the message and reveal its content.

🟢 Adds a Secure Compose button to Gmail, allowing you to send private PGP-encrypted emails when you choose to.

🟢 We update the extension regularly (see the "Updated" field to the right).

FlowCrypt allows you to:
 ✔ Set up the extension in just a few clicks.
 ✔ Generate private keys using the ECC and RSA (up to 4096-bit) algorithms.
 ✔ Use FlowCrypt’s own Attester public key server.
 ✔ Send and receive encrypted emails and attachments (up to 25MB, with previewing functionality) to anyone.
 ✔ Send and receive encrypted emails directly or through Encrypted Contact Page.
 ✔ Send password-protected emails to the recipient who doesn’t have any OpenPGP software (as well as receive such emails).
 ✔ Sign encrypted emails to let your recipients verify that the message is from you and that the content hasn’t been modified.

🌐 Website: https://flowcrypt.com/
📁 Source code: https://github.com/FlowCrypt/
📚 Documentation: https://flowcrypt.com/docs/
🧠 Knowledge Base: https://flowcrypt.com/blog/questions/
📱 Android & iOS apps: https://flowcrypt.com/download

📩 Looking forward to your feedback! Please email us at human@flowcrypt.com.
```

**Comment by ioanmo226** [comment]
It seems screenshot (of gmail page browser extension) is distorted to me.
Maybe tried to import small screenshots and tried aspect ratio is not same to original one?

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/46c2b49f-ec7b-4989-b7ce-d1135a89ce53)

**Comment by sosnovsky** [comment]
> It seems screenshot (of gmail page browser extension) is distorted to me. Maybe tried to import small screenshots and aspect ratio is not same to original one?

@vahram-papazyan did you resize screenshots after pasting or it's their original aspect ratio?

**Comment by vahram-papazyan** [comment]
I increased the text font-size because otherwise it's blurry and difficult to read.

**Comment by sosnovsky** [comment]
Chrome web store decreases quality of uploaded screenshots (like on our current page - https://chromewebstore.google.com/detail/flowcrypt-encrypt-gmail-w/bnjglocicdkmhmoohhfkfkbbkejdhdgc?hl=en), so probably it won't be noticeable, we can leave it as is for now

**Comment by tomholub** [comment]
I'll start working on the release now.
