### ISSUE TITLE
FES reply with attachment is not decrypted

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5458]
Customer reported an issue when FES reply to password-protected message isn't decrypted by browser extension, when reply contains attached file with size between 500 and 800kb

Example message is in `flowcrypt.compatibility` account with subject `FES message for #5458`

**Comment by ioanmo226** [comment]
Hey @sosnovsky, I attempted to send a reply to an FES encrypted message that had a 600kb attachment. Everything looks good on my end.
However, the `FES message for #5458` isn't decrypting.
How'd you create that message?

**Comment by sosnovsky** [comment]
It was created with the previous version of FES `2023-11`, but in the latest `2023-12` release we updated FES to send messages in PGP/MIME format (https://github.com/FlowCrypt/enterprise-server/pull/5129) which fixed this issue.

Message in `FES message for #5458` is still a valid encrypted message, but for some reason it's not detected as encrypted one. For this case when message content is clipped, browser extension is expected to fetch full message data from Gmail API  ([msgGetFull](https://github.com/FlowCrypt/flowcrypt-browser/blob/5b7cf403bc6fde52e9ded596777a110148f0ca4f/extension/js/common/downloader.ts#L53)), but it's not triggered for mentioned message

**Comment by ioanmo226** [comment]
Yeah, I checked it and `messages/{msgId}?format=full` api returns below response. (Notice {body: {size: 0}} )
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/3ddeafbf-bf0b-4a98-8bcd-68732be25140)

**Comment by ioanmo226** [comment]
Maybe need to fetch attachment data and proceed I think.
Will check deeply though.
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/cd090d99-a1ac-4073-83e9-438f29aae718)

**Comment by sosnovsky** [comment]
It happens because after some message size (that's why this issue is caused by attachments of specific size) Gmail puts all message content into body attachment. This case is also handled by browser extension, but for some reason it fails for this message

**Comment by ioanmo226** [comment]
I checked and below api returns 200 status code after 3-5 seconds. (That's why it's treated as plain text). 
But to get actual response, it takes about 100-200 seconds. Not sure why this api takes so long.
Maybe need to fix `attachmentGetChunk` function to get actual response data? (But even though we fix it, we have to fix it to show loading spinner while this api is loading. people might think it's stuck/not working)
What do you suggest in this case.

https://www.googleapis.com/gmail/v1/users/me/messages/{msgId}/attachments/{attachmentId}

**Comment by sosnovsky** [comment]
Our goal here is to make encrypted message to be detected as encrypted and rendered appropriately.
As currently user won't be able to read message text, because it's detected as plain text.

Showing spinner is ok, but we should check why it takes so long to fetch message data here - for other messages it's much quicker.

> Should we look into optimizing the attachmentGetChunk function to speed it up? 

Do we use `attachmentGetChunk` here? As we also have [fetchAttachment](https://github.com/FlowCrypt/flowcrypt-browser/blob/5b7cf403bc6fde52e9ded596777a110148f0ca4f/extension/js/common/api/email-provider/gmail/gmail.ts#L258) method, maybe it'll be faster

**Comment by ioanmo226** [comment]
It's not because of our implementation.
But messages/{msgId}/attachments/{attachmentId} api takes so long. It's google's problem I think

**Comment by ioanmo226** [comment]
@sosnovsky I sent you fetch code which will execute call to above api.
Run that code and it will take over 150 seconds to fetch data (even though final data is about 1.5mb or so)

**Comment by sosnovsky** [comment]
`fetch` code failed for me with CORS error. But I tried to perform `this.messageRenderer.gmail.attachmentGet` in `replaceArmoredBlocks` and message attachment was downloaded in a couple seconds.

I added code below before this line - https://github.com/FlowCrypt/flowcrypt-browser/blob/5b7cf403bc6fde52e9ded596777a110148f0ca4f/extension/js/content_scripts/webmail/gmail-element-replacer.ts#L168

```ts
const att = await this.messageRenderer.gmail.attachmentGet(
  '18b39cba715705cf',
  'ANGjdJ_39gxMSuHyMrzCNBPhG0PuxCH1web9tYiWMysHXvVADpZvHjFPQ-Zm9fXMzcjrEcnK8bRLDdUAzHUADzsRuUUuDxh5_FiRUc8lORnSk14CB56jXlethhBwAeXrk7V4OZOv2vfGAZ7rpH9pHg8thTBVWDvQjLFFQRH8GcmmLRwJbY2jr_wjyXTcsMZ-IEJXyv0TOlN8BpFmWIqxYiFr_4fl1ozObb30_sSULJb0QvUSM5Z-dibNRLjoANF_ywRLwQ0Dw7w90WU2Vya_oR3frxtJtilyU8Ca30evoxgpRW3EbmklQv4J7fVdoNrLcio6gHgObGGZ6jNSx7gVSu7Ws0aE7w9vJSoUMqdz2diZPNOZ8vF_5v6bo0KGoC0'
);
console.log(att.data.toUtfStr());
```

So Gmail API works fast, issue should be somewhere on our side

**Comment by ioanmo226** [comment]
Strange....
With above code, it fetches in a few seconds.
I wonder why simple `fetch` call take so long time (more than 100 seconds). To avoid CORS error you might try in our extension dev console

**Comment by ioanmo226** [comment]
Anyway, let me investigate and fix our logic.

**Comment by sosnovsky** [comment]
> I wonder why simple fetch call take so long time (more than 100 seconds). 

I noticed some issues with `fetch` too while working on https://github.com/FlowCrypt/flowcrypt-browser/pull/5372, especially on firefox, as it's implementation differs in chrome and firefox

**Comment by sosnovsky** [comment]
fixed in https://github.com/FlowCrypt/flowcrypt-browser/pull/5518
