### ISSUE TITLE
'noname' attachment not hidden in password-protected message

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5459]
After merging https://github.com/FlowCrypt/flowcrypt-browser/pull/5445 `noname` attachments are not hidden in password-protected messages and `2 attachments` label is visible, but it should be hidden too.

Need also to add ui test checking that `noname` attachment and this label is hidden in password-protected messages.

before
<img width="320" alt="Screenshot 2023-10-17 at 08 20 52" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/5d383b5a-e0d5-4dfb-ba84-a8bb93832336">

after 
<img width="320" alt="Screenshot 2023-10-17 at 09 42 31" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/9d0dd6ef-1a61-4e2a-96e1-f0cbc5beea6b">

**Comment by martgil** [comment]
I'll fix this now. 

(For me) Test email to use:

https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#search/noname/FMfcgxwDrRShslZMMFjPWpzwTJxjhJfr

**Comment by martgil** [comment]
Hello @sosnovsky, Could we treat the 'noname' as an attachment type 'hidden'?

**Comment by sosnovsky** [comment]
You mean to hide all `noname` attachments? But I think we initially had an issue when some non-PGP `noname` attachments weren't rendered correctly, as they had another content, not related to encryption. So some `noname` attachments should still be rendered

**Comment by martgil** [comment]
Yes, for all `noname` attachments. Ok, I get it now. So I'll just hide those `noname` attachments for password messages and leave them as is for PGP encrypted messages. Is it correct?

**Comment by sosnovsky** [comment]
For PGP-encrypted messages it should be hidden in some cases too, as some `noname` files can include PGP-signatures (which should be parsed and attachment hidden), also PGP/MIME messages sometimes include `noname` file with PGP/MIME version identification (they're hidden now, which is correct behavior)

So hiding behavior should depend on `noname` attachment content, not message type (password-protected or PGP-encrypted)
