### ISSUE TITLE
Incorrect label with attachments count

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5460]
When message has attached public key and other attachment, UI shows `2 Attachments` label, while it should be `1 Attachment` as public key attachment isn't shown:

<img width="400" alt="Screenshot 2023-10-18 at 22 59 36" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/8077e6c3-016c-4a12-bf8a-27e2c3d94537">

For example you can check `PDF attached` thread in `flowcrypt.compatibility` account

**Comment by martgil** [comment]
@sosnovsky In the discussion on https://github.com/FlowCrypt/flowcrypt-browser/issues/5459, it has been decided to hide the label completely, irrespective of the number. Can we hide the label completely, as reverting the previous change seems to be functioning effectively and would require less effort. 

If you agree on this, it would be part of https://github.com/FlowCrypt/flowcrypt-browser/pull/5472 PR as it was really a small change -- i'll just reference this GH issue on the commit if thats ok with you?

**Comment by sosnovsky** [comment]
> @sosnovsky In the discussion on https://github.com/FlowCrypt/flowcrypt-browser/issues/5459, it has been decided to hide the label completely, irrespective of the number. Can we hide the label completely, as reverting the previous change seems to be functioning effectively and would require less effort.

I checked our discussion there, but didn't find any comment about hiding attachments count label. There we discussed only hiding some `noname` attachments, but attachments count label should be visible.

**Comment by martgil** [comment]
Sorry, I mean the initial description in the GH issue. So, I'm little bit confused as to whether hide it or not:

> After merging https://github.com/FlowCrypt/flowcrypt-browser/pull/5445 noname attachments are not hidden in password-protected messages and 2 attachments label is visible, but it should be hidden too.

It could be superseded by #5460 -- do you want me to display this label for both pgp encrypted and password protected message?

**Comment by sosnovsky** [comment]
> Sorry, I mean the initial description in the GH issue. So, I'm little bit confused as to whether hide it or not:

Ah, there I meant that `2 attachments` label should be hidden when there is no rendered attachments.

> It could be superseded by https://github.com/FlowCrypt/flowcrypt-browser/issues/5460 -- do you want me to display this label for both pgp encrypted and password protected message?

Yes, attachments count label should be visible for any message when there is at least 1 visible attachment.

In this task description there is a message with 2 attachments, but one of them is public key attachment which is not rendered. So attachments count label should be visible and have text `1 Attachment`.

In https://github.com/FlowCrypt/flowcrypt-browser/issues/5459 message has 2 attachments, but both of them are hidden, so attachments count label should be hidden too.

**Comment by martgil** [comment]
Oh, okay. But in the current code, we only show the label if there are two or more renderable attachments. I just to confirm you would like it to be changed as suggested.

**Comment by sosnovsky** [comment]
> Oh, okay. But in the current code, we only show the label if there are two or more renderable attachments. I just to confirm you would like it to be changed as suggested.

Comment there says `Aligned with Gmail, the label is shown only if there are 2 or more attachments`, but currently Gmail shows label even when there is only 1 attachment. So let's remove `nRenderedAttachments >= 2` check and show this label when there is at least 1 renderable attachment, to align with Gmail behavior
