### ISSUE TITLE
Secure reply/Secure forward disappears from Gmail

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5494]
### Description
When receiving an encrypted email reply, the option to reply/forward securely has disappeared. 

<img width="50%" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/9c4f4fda-f31a-4aea-9102-a9d41a56e60b">

### Steps to reproduce

1. User 1 sends flowcrypt encrypted email to User 2.
2. User 2 received the encrypted email and responded to it.
3. User 1 receives the encrypted reply but has no option to reply/forward the email securely (encrypted).
4. From User 2's view, the option to reply/forward encrypted is rendered in Gmail correctly.

Reference:
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGwHpShPkWdxBZFXMBHZtTxNdvW
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGwHpRXzjZFRnMhWmZkMLQKtfsq

**Comment by sosnovsky** [comment]
I've just noticed such issue too, currently trying to find what's happened with these buttons.
@martgil can you please also check it on your side, so we'll try to find solution faster, thanks.

**Comment by martgil** [comment]
Yes, Roma -- I'm a bit surprised for this issue because as far as I know, we haven't pushed any updates on chrome store or firefox build.

**Comment by sosnovsky** [comment]
Yes, probably something changed in Gmail markup, which led to this issue, but I haven't found yet.

**Comment by sosnovsky** [comment]
@martgil I think I found issue - class name for convo root element has changed, so [getConvoRootEl](https://github.com/FlowCrypt/flowcrypt-browser/blob/cd30be23119e4bfddd303e8e31abb966e8cd0ac6/extension/js/content_scripts/webmail/gmail-element-replacer.ts#L581) fails to find it. Fixed by adding `div.Bk` to classes list
