### ISSUE TITLE
Uncollapsible drop-down menu when expanding contact key details.

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5513]
### Description

When collapsing a drop-down menu container for viewing contact key details from the contacts list, clicking the header of the collapsible menu won't return it to the uncollapsed state.

<img width="65%" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/af8aa5e5-b2e1-4263-8faa-b7f9c0b7d503">

### Expected Behavior

It should return to the uncollapsed state when clicking on the header.

### Steps to reproduce

1. Open FlowCrypt settings and navigate to `Additional Settings` -> `Contacts`.
2. Collapse at least one contact details.
3. Try to uncollapse the menu and notice that it wouldn't work.

**Comment by sosnovsky** [comment]
fixed in https://github.com/FlowCrypt/flowcrypt-browser/pull/5538
