### ISSUE TITLE
Update the "use custom keyserver" button link on the "Contacts and their Public Keys" page and capitalize buttons

### ISSUE THREAD

**Issue by vahram-papazyan** [FlowCrypt/flowcrypt-browser#5524]
close #5524

**Comment by sosnovsky** [comment]
> sosnovsky Can you please help me to solve this issue?
> 
> I've updated the link and committed my changes but faced this issue

Try to run `npm install` and then commit again, it should work


> And there is a problem with installing the extension on Brave: [recording](https://drive.google.com/file/d/1iHk_e9ib4_JXF7Mc3QchF3MBYvB_su1p/view?usp=sharing)

Seems like it happens in all browsers, as extension can't fetch client configuration, I filed an issue for backend, thanks for noticing!

**Comment by sosnovsky** [comment]
> And there is a problem with installing the extension on Brave: [recording]> (https://drive.google.com/file/d/1iHk_e9ib4_JXF7Mc3QchF3MBYvB_su1p/view?usp=sharing)
>
> It shows this error window after the process:

@vahram-papazyan issue is fixed, it should work well now
