### ISSUE TITLE
Broken blog post links in FlowCrypt Settings basic view

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5526]
### Description

The following code below results in a broken links rendered in FlowCrypt extension index page:

https://github.com/FlowCrypt/flowcrypt-browser/blob/749c1029486775668ac61b19d3c7843098405b63/extension/chrome/settings/index.ts#L333

### Screenshot

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/8de0394c-bab3-4337-a609-c3cc86c0dbc2)

Reference: 
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGwHxxDHkfGXcrtjQwRXQwTtfdM

**Comment by martgil** [comment]
Upon reviewing the issue, nothing needs to be changed here; the modification should occur in the website repository.

**Comment by sosnovsky** [comment]
@martgil it looks like we have incorrect generated urls here too, as they start from duplicated `https://flowcrypt.com`, so `href` attribute should be `href="${Xss.escape(post.url)}"`

**Comment by martgil** [comment]
You're right -- sorry for the confusion. I'll fix it too.
