### ISSUE TITLE
Update PGP/MIME message format according to standards

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5537]
> Yeah, looks like we should update code for PGP/MIME message composing in browser extension 
> But maybe it will be a simple fix for Android, as I opened the same message on iOS and it was rendered there (maybe no name for image causes problem on Android):

Yes, I can add a fix. But this will be a non-standard way, and it will significantly complicate the code.

The current browser realization doesn't follow the standard. Let me add more details here

The browser extension generates the following:

```
------sinikael-?=_1-16998840995020.4112130840361884
Content-Type: application/pgp-encrypted; name=
Content-Description: PGP/MIME version identification
Content-Disposition: attachment
X-Attachment-Id: f_mxDfixWgPOEcEygnCeJiNRdWbtvpqe@flowcrypt
Content-Id: <f_mxDfixWgPOEcEygnCeJiNRdWbtvpqe@flowcrypt>
Content-Transfer-Encoding: 7bit

Version: 1
```

Based on https://proton.me/support/pgp-mime-pgp-inline it should be something like this one:

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/513957d3-fb97-442f-9ec3-e53b528f13a1)

Also, based on https://datatracker.ietf.org/doc/html/rfc3156#autoid-4

```
The multipart/encrypted MIME body MUST consist of exactly two body
   parts, the first with content type "application/pgp-encrypted".  This
   body contains the control information.  A message complying with this
   standard MUST contain a "Version: 1" field in this body.  Since the
   OpenPGP packet format contains all other information necessary for
   decrypting, NO OTHER INFORMATION IS REQUIRED HERE.
```

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/c978678d-e295-4c37-912c-bd6bfda75695)

All of that means we have to generate the following:

```
------sinikael-?=_1-16998840995020.4112130840361884
Content-Type: application/pgp-encrypted
Content-Description: PGP/MIME version identification
Content-Transfer-Encoding: 7bit

Version: 1
```
###########################################################

For now, on my side **name=** is a problem. JavaMail recognizes it as an error. If a parameter is present it should have a value(or `quoted-string` for the empty value like `name=""`). More details can be found [here](https://datatracker.ietf.org/doc/html/rfc2045#section-5.1)

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/83ff6301-430a-4f69-b472-f5280dd2afe6)

###########################################################
> I tried to send similar message from protonmail and it's rendered in Android app.

It is not `PGP/MIME` encrypted message. It's `PGP/Inline`

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/e929cee0-5ac3-46b1-b089-c1b239514a24)

Like 

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/2448a174-92ee-4082-944d-029fd7164e90)

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/2527#issuecomment-1862745204_

**Comment by DenBond7** [comment]
I've created an example from Proton(please look at `flowcrypt.compatibility -> Proton PGP/MIME encrypted with an attachment`)
