### ISSUE TITLE
Secure reply issues when composing signed message

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5599]
### Description

When replying to a signed message, pressing enter creates a new line above the current line the user is writing wherein it should create a new line below the current line. Aside from this, pressing backspace does nothing making any typos undeletable.

This only happens on messages composed in a signed message and composing encrypted + signed is not affected.

Reference: 
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRdxBwtHmFKSTKPNLSQSsnqKm
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRfBSrqRfqcSwksGTzqkVdMhQ
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxSRMQMmRDKjttmnsQMWRQGDGb

**Comment by martgil** [comment]
I noticed just now that when trying to send a blank signed message, there was this unhandled error message that occurred.

<img width="549" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/8ff5f090-9edf-4cc1-9590-d503bd2dd2c1">

**Comment by sosnovsky** [comment]
> I noticed just now that when trying to send a blank signed message, there was this unhandled error message that occurred.

Oh, please fix it when working on the initial issue

**Comment by martgil** [comment]
Yes, i will cover it as well.
