### ISSUE TITLE
A user public key was automatically attached when using "Secure Reply" on a non-encrypted email

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5609]
Steps to reproduce:

1. On Gmail, open a regular email (but preferably an HTML email).
2. Click the FlowCrypt's "Secure Reply" button on the top-right corner for the email. 
3. Once again, click on the "Secure Reply" button.
4. You will have the encrypt+signed message type option... Aside from this, the include public key button is in blue, which indicates that the public key will be included.

Users seem to prefer to include their public key at their discretion.

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/eb9aa9b6-44b7-4166-8bb9-1d0e276190d5)

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRfFtxbXfhgjhGpbhLrmmxpTl

**Comment by sosnovsky** [comment]
Hi @martgil, I tried to reproduce and I don't have public key attached by default (icon stays gray).
Were you able to reproduce described behavior?

**Comment by martgil** [comment]
Hello @sosnovsky Yes, I was able to replicate the issue as the screenshot above came from me. I'll take a short screencast to demonstrate the issue here shortly.
