### ISSUE TITLE
Error "TypeError: Failed to execute fetch..." occurs on several users

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5612]
### Description

There are several users who are experiencing errors related to `fetch()` where the error says `Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'Window': The provided ReadableStream is locked.`.

One user, experienced it when accessing the FlowCrypt Settings (during setup)

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/05e6deec-a4c2-4690-9fe1-9579b80db56c)

And this one below happens on a couple of users trying to send a secure email (encrypted + signed):

<img src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/4eb0aa55-8d1d-45c0-8795-63feb315898b" width="55%">

We started receiving reports related to this a few weeks ago, so I wonder if that would be something related to https://github.com/FlowCrypt/flowcrypt-browser/pull/5372.

I personally encountered this one but only limited to test that I accidentally bump into. Everything works for me when I'm using FlowCrypt on a daily use.

References:

https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRfFtxPNTGxQBmtcGVqrcZrxK
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRdzKDmBnXRjCkxVqqbQSFVCS
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRfFwgjWJCjlxlhRjNFpTQDGh
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRndgGHWpZMQTkxnnBPKZQqjz
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRfDnLXBxrdjGFfDQtjkpwhXq
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRnfpHlHbqrbcPcvhStwwQlCR
https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGxRxBGrQpRQHFTCKnkdftvfBSM

**Comment by martgil** [comment]
@sosnovsky just sharing this with you so that I can hear your advice. Thank you!

**Comment by martgil** [comment]
Your welcome. thank you too. This issue has been in my head for quite a while now since i only have fragments of unhelpful information but just written the report clear when i think i have the sufficient data to write it on.

**Comment by sosnovsky** [comment]
@martgil I checked provided screenshots and noticed a couple error codes for failed `gmail/v1/users/me/messages/send?uploadType=multipart` requests - `ERR_DNS_NO_MATCHING_SUPPORTED_ALPN` and `ERR_H2_OR_QUIC_REQUIRED`.

These codes mean that there were issue with establishing http/2 connection (which is used for handling message upload progress). It can happen when user uses some antivirus software which monitors HTTPS traffic and disables http/2. Turning off such monitoring should fix the issue. Here some examples of similar issues:
- https://stackoverflow.com/a/66086626/3091318
- https://stackoverflow.com/a/41128943/3091318

I'll work on temporary disabling this http/2 requirement, so extension will work even with enabled antivirus https monitoring, but as a temporary solution you can let them know about this possible fix.

**Comment by martgil** [comment]
Hi @sosnovsky, can I share a custom build that includes the fix for this issue with the affected users (non-customers)?

**Comment by sosnovsky** [comment]
Hi @martgil, you can share this build with a couple users to check if their issue is fixed, so we can release it to chrome web store later today

**Comment by martgil** [comment]
Thanks, Roma, that is. I'll pack the master branch build and distribute it. I'll let you know of any feedback shortly so that we can decide later.

**Comment by sosnovsky** [comment]
Hi @martgil, did you receive any feedback from users?

**Comment by martgil** [comment]
Hello @sosnovsky I havent heard an update from them yet, but they are responsive to emails so we should have their feedback soon.

**Comment by martgil** [comment]
Hello @sosnovsky, I received positive feedback confirming that the particular fix is working and allows them to continue sending the composed secure email.

**Comment by sosnovsky** [comment]
Great, thanks for update! Will try to prepare a new release today or tomorrow

**Comment by martgil** [comment]
I understood. thank you!

**Comment by sosnovsky** [comment]
Hi @martgil, I submitted new build to chrome web store, so it should be published soon

**Comment by martgil** [comment]
Thanks, @sosnovsky! I'll keep checking for its arrival on the Chrome Store and keep the users mentioned in the links informed.
