### ISSUE TITLE
email signature does not change when switching between different "send mail as identities"

### ISSUE THREAD

**Issue by pi-2007** [FlowCrypt/flowcrypt-browser#5615]
Hello,

we are using latest 8.5.3 on Firefox and we have some Gmail accounts with multiple "Identities" which use their own email signature (under Settings -> Account -> "Send mail as" we have multiple email addresses and they are configured to each use a specific email signature).

Switching between different "from" addresses in the normal Gmail composer updates the email signature in the email body. 

However, this is not happening when using secure compose: I can switch the "from" address, but the signature will stay the same (see screenshot)
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/70692117/ecd8eb13-99e1-436b-95d0-c40c70e33f79)

 I found https://github.com/FlowCrypt/flowcrypt-browser/issues/61 but I'm not sure if this is the same issue ?

kind regards,

**Comment by sosnovsky** [comment]
Hi @pi-2007, thanks for the report! Footer should be updated when switching between different `from` addresses, I'll add this issue to our next milestone
