### ISSUE TITLE
email body is hidden for some messages which are signed, not encrypted, with public key, with attachments

### ISSUE THREAD

**Issue by pi-2007** [FlowCrypt/flowcrypt-browser#5639]
Dear Flowcrypt,

We are using latest v8.5.3 with Firefox and we found emails which do not display correctly in flowcrypt (the body of the email is not shown), they display correctly without flowcrypt by clicking "See original" in the top right corner. 

I'm not sure whether it has to do that both emails are signed but not encrypted, that both are sent with a public key attached, or that both have an attachment. Maybe it is the formatting of the email itself (the GPG signature is created by Protonmail, but it is a newsletter). I've tried adding the public key to my contacts whether this makes any difference, and it does not.

Also sometimes the "See original" button in the top right corner is missing, although I see the "secure reply" buttons at the bottom of the email. To get it back, I need to reopen the email and then (sometimes) it works.

I found this https://github.com/FlowCrypt/flowcrypt-browser/issues/1690 which describes very similar symptoms: it briefly shows the email body, but then "hides" it.

I can only post 2 screenshots here:

1) view when simply opening the email which is then shown "with" flowcrypt:
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/70692117/1c4ceb42-ad6d-4cc5-a550-becda1334f3e)

2) view when clicking "Show original" which opens the email without flowcrypt:
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/70692117/cf37bf12-4933-406b-97f0-f8b2bbae0b04)

I'm more than happy to share the eml file with the developers. Please let me know how I can send you the file.

**Comment by sosnovsky** [comment]
Hello @pi-2007, sorry for the late response - do you have similar issue in the latest 8.5.4 release?
If it still occurs - please send .eml file to the flowcrypt.compatibility@gmail.com, we'll check it to provide a fix.
Thanks for your report!

**Comment by sosnovsky** [comment]
Closing, as there is no response from reporter.

**Comment by pi-2007** [comment]
Dear Flowcrypt,

thank you. Back then, we were waiting for the release of 8.5.5 which seemed almost ready to test with the most recent version. However, I see now that the Firefox extension is still 8.5.4 (https://flowcrypt.com/download) while for Chrome the version is 8.5.7.

Will there be no new versions for Firefox?

kind regards

**Comment by sosnovsky** [comment]
Upcoming 8.5.8 release will be available for Firefox - we migrated to Manifest V3 in 8.5.5 release which caused some blocking issues in Firefox. So we didn't publish previous updates for Firefox.
Now fix is ready and will be included in the next release
