### ISSUE TITLE
Live test is broken

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#5652]

**Comment by sosnovsky** [comment]
@ioanmo226 I've worked on this issue in https://github.com/FlowCrypt/flowcrypt-browser/pull/5654 (forgot to create PR initially), live test seems to be fixed there

**Comment by ioanmo226** [comment]
Ohhh. I see
Thank  you for your info

**Comment by ioanmo226** [comment]
Let me close my PR
