### ISSUE TITLE
Fix failing OSSAR static analysis reporting

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5681]
From Roma:

> By the way, we have also some automated scanning configured in flowcrypt-browser repo, can also check opened issues at https://github.com/FlowCrypt/flowcrypt-browser/security/code-scanning and find why ESLint fails there.

Reference: https://github.com/FlowCrypt/flowcrypt-security/issues/277

**Comment by martgil** [comment]
Hello @sosnovsky, I believe I have already found the root cause of this issue. The GitHub action [OSSAR](https://github.com/github/ossar-action)  is still using 'node 16', from which [ESLint's requirements doesn't support](https://eslint.org/docs/latest/use/getting-started).

OSSAR action file:
https://github.com/github/ossar-action/blob/fae13e456b9973657a670eef6bccc3a4c2b5153d/action.yml#L16

**Comment by sosnovsky** [comment]
Hello @martgil, thanks for your investigation, hope they'll get it merged soon!

**Comment by martgil** [comment]
I noticed that there's something wrong going on only for push event's where checking out the repo doesn't seems so well and marked as not finished if we take a look at the GitHub action overview.

Consider the following example:

https://github.com/FlowCrypt/flowcrypt-browser/actions/runs/9095908805/job/25036158252 - its from the master branch.

But in general most PRs should experience such issue, where OSSAR with "push" event tags does have the same issues where tags "OSSAR / OSSAR-Scan (pull_request)" finishes correctly.

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/828292d0-bf74-4208-8c59-ef5c34af9755)

There's no way we can review the logs for that step.

**Comment by martgil** [comment]
Noticed that in every PR the scan "OSSAR / OSSAR-Scan (pull_request)" in every push so from this stand point. I'd like to raise my suggestion of removing the push requirement since its present in every pull request. And there would be no reason to run OSSAR's when pushed on the master branch.

**Comment by martgil** [comment]
Hello @sosnovsky I had to re-open this GitHub issue since the error on the `Security` tab didn't disappears. Meanwhile, I have completely tried to create the same OSSAR GitHub action on a test organization that I created to verify this and while both has the same similar OSSAR configuration, the error only appears on the FlowCrypt browser extension report. So I think a maintainance should have done on the repo's Settings under code scanning, specially it would help if we could have remove other define workflows where file's didn't exists in `.github/workflows` within the FlowCrypt browser extension's report - https://github.com/FlowCrypt/flowcrypt-browser/security/code-scanning/tools/CodeQL/status

I have invited you the test organization that i made to cross this - https://github.com/An-Example-Org/sample-ossar/security.

**Comment by martgil** [comment]
Another option to try could be re-initializing the OSSAR Github Action - since it works very well with against my test repo under the test organization.

**Comment by sosnovsky** [comment]
It seems `eslint` fails with some errors when running in OSSAR Action 
<img width="400" alt="Screenshot 2024-05-22 at 16 21 14" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/d8cda2a0-7599-43ff-ba86-46f7773547ed">

Maybe it happens because OSSAR Action uses outdated `eslint 7.32.0`, while our project is configured to work with eslint v8. I also re-checked OSSAR and we need only eslint from this action, as other tools there are for checking Python and C code. So it'll should be simpler to use just ESLint action - https://github.com/FlowCrypt/flowcrypt-browser/new/master?filename=.github%2Fworkflows%2Feslint.yml&workflow_template=code-scanning%2Feslint

**Comment by martgil** [comment]
Thanks @sosnovsky, I understand. I'll be more efficient by using ESLint action instead of OSSAR for a well-defined project like ours. I'll check it out.
