### ISSUE TITLE
FlowCrypt extension no longer detects backup for recovery

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5683]
Description:

I noticed that after generating a new key pair for my Gmail account, the extension no longer offers key recovery, even though there's actually a FlowCrypt backup within my account's inbox. I happened to notice this randomly when reviewing the manifest V3 pull request, but the issue exists in the Chrome Store version.

I'm using Brave browser: 1.64.122 Chromium: 123.0.6312.122 (Official Build) (arm64)

**Comment by martgil** [comment]
Hi @sosnovsky, I've tested this in my Firefox browser and it also happens not to detect any of my backups.

**Comment by sosnovsky** [comment]
Hi @martgil, what is subject name for your FlowCrypt backup message? I tested it and backup search works well for me, code for search query haven't changed for a long time (https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/js/common/core/const.ts#L34), so it's strange that it stopped working for you.

You can also look for request https://www.googleapis.com/gmail/v1/users/me/messages?q=from%3YOUR_EMAIL%20to%3A3YOUR_EMAIL%20(subject%3A%22Your%20FlowCrypt%20Backup%22%20OR%20subject%3A%20%22Your%20CryptUp%20Backup%22%20OR%20subject%3A%20%22All%20you%20need%20to%20know%20about%20CryptUP%20(contains%20a%20backup)%22%20OR%20subject%3A%20%22CryptUP%20Account%20Backup%22)%20-is%3Aspam%20-is%3Atrash&includeSpamTrash=true in the Network tab, to check if it's performed and finds any backups

**Comment by martgil** [comment]
@sosnovsky That Gmail API call we're never called upon checking the logs. I'll be sharing a short video over email.

**Comment by martgil** [comment]
I do notice that the term "Trash" has now been transitioned to "Bin" in Gmail so perhaps we should start looking into it as there maybe some changes made somewhere in Gmail.

**Comment by martgil** [comment]
Confirmed, they have changed it from the flag from 'trash' to 'bin':

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/64724168-89e5-48f0-91cd-f099d16933b5)
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/3b937507-4c5e-4662-8dc7-237d5a981957)

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/18a3dd77-f149-4e9c-80e6-a47e6775bc8b)
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/b2dc3f72-5c8a-4b56-abe6-7b412823eb48)

@sosnovsky please confirm -- mobile apps should then be updated after this.

**Comment by sosnovsky** [comment]
For me it's still `Trash`, maybe it depends on selected UI language (I have `English (US)`)

<img width="238" alt="Screenshot 2024-04-19 at 11 51 25" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/05e9995f-9958-4d6f-8c68-98a4e7e925ed">

And backup was successfully detected after you've added `-is:bin` to backup search query?

**Comment by martgil** [comment]
Hello @roma, this is interesting, on my other account it also shows Trash while the other says Bin.

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/4215d935-ee35-4ed2-9739-c289e19287d8)
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/609df423-35f9-4ebd-9e6b-5c069dddb0f2)

 > And backup was successfully detected after you've added -is:bin to backup search query?
 
 Yes, it does work for my other account with "Bin" pretty well.

**Comment by martgil** [comment]
It's in the "Inbox" directly.

**Comment by sosnovsky** [comment]
Then probably backup issue is caused by some other bug - `-is:trash` or `-is:bin` should just remove from search results messages from `Trash` or `Bin` folder. But in your case backup search query wasn't even performed, I think if now you'll change `-is:bin` back to `-is:trash` - backup detection will continue working.

https://github.com/FlowCrypt/flowcrypt-browser/blob/master/extension/chrome/settings/setup/setup-render.ts#L49 - maybe `this.view.storage!.setup_done` wasn't set in your case.

Also if you'll be able to reproduce original issue, can you please try to reload page and check if backup search query will be executed after reload?

**Comment by martgil** [comment]
Yeah, it works now without the -bin flag. Strange, this has happened to me more than once on my PC and Mac, I swear, but now it works completely fine.

I apologize for any inconvenience I have caused.

**Comment by sosnovsky** [comment]
Probably it can happen for users in some circumstances too, so let's monitor it - if you'll notice this issue again, please reopen this issue and will try to find why it happens
