### ISSUE TITLE
Improve the "Add a public key to email address" page texts and UI

### ISSUE THREAD

**Issue by vahram-papazyan** [FlowCrypt/flowcrypt-browser#5695]
Currently the page looks like this:

![add-pubkey](https://github.com/FlowCrypt/flowcrypt-browser/assets/22081012/cfb838c6-8e9f-42cd-a801-eac14ef9d45f)

I suggest:

- Remove overflow
- Use green for texts and "OK" button
- Add hover similar to the browser's setting section buttons

**Comment by sosnovsky** [comment]
> Remove overflow

👍

> Use green for texts and "OK" button

Current color highlights that it can be dangerous to manually import public keys, let's continue using it.
But `OK` button can be renamed to `Import`

> Add hover similar to the browser's setting section buttons

We don't use hover for buttons in other places, so let don't add hover here too.

**Comment by sosnovsky** [comment]
> My bad, should write "active" effect, not hover, like this:

Ah, this effect can be added there 👍

> Maybe we could use a danger icon in that case?

There are no icons on other buttons in FlowCrypt extension, so it'll look different from them, let's leave only text for consistency.
