### ISSUE TITLE
Text improvements of the Secure Compose window

### ISSUE THREAD

**Issue by vahram-papazyan** [FlowCrypt/flowcrypt-browser#5698]

**Comment by sosnovsky** [comment]
> @sosnovsky When we click on "for 90 days" it redirects to the Security section where there is nothing related to this topic. should we remove that anchor?

Security section includes some settings for password-protected messages, so let's leave this link as is.
Maybe in the future there will be more settings related for password-protected messages

**Comment by sosnovsky** [comment]
> Okay, I'd also attach the [Send Encrypted Emails to Users Who Don't Use Encryption](https://flowcrypt.com/docs/getting-started/send-and-receive/send/send-password-protected-emails.html) link where is says "Or send email password-protected", like this:

Sounds good, let's add it 👍

> Can i add that link directly in href attribute? i see all other anchors don't have direct links on this page inside href

Yeah, I think it should work well from `href` attribute
