### ISSUE TITLE
Public key-encrypted message named after "noname" didn't recognized as encrypted message based on its content

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5726]
### Description

We received a report send to `flowcrypt compatibility` account about a Public key-encrypted message attachment named after "noname" and another "noname" file where it contains `Version: 1`. The application used the [Canary Mail](https://canarymail.io/blog/pgp-encryption/).

The issue produces a seemingly blank page:

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/08a78092-bb5a-4e84-abb2-03078a75c2b1)

The `noname` file attachment content:

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/9a00d5a9-f06b-4b75-b1da-60cc23265b09)

Reference: https://mail.google.com/mail/u/flowcrypt.compatibility@gmail.com/#inbox/FMfcgzGxTFXMFnDNbgknpqvXKtSmMgSK

**Comment by sosnovsky** [comment]
`application/octet-stream` is a default mime type for unknown files, so for cases when we don't have any file type set - `application/octet-stream` is used

**Comment by martgil** [comment]
Thanks, Roma - that is right, I knew it later on right after. I'll have more information to add here when needed.
