### ISSUE TITLE
auto scroll down when selecting long text in secure compose

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#573]

**Comment by tomholub** [comment]
try to do what the title describes (msg that spans a few pages) and if you don't see any obvious problem, close

**Comment by schmorrison** [comment]
From within gmail when the `div#pgp_block` element exceeds the window height, highlighting with the mouse does not scroll the screen when the mouse reaches the window bottom. `Ctrl+A` after clicking on the text within `div#pgp_block` works fine to highlight all of the text, at least in chrome.

Tried a few things with CSS but cannot get a simple fix to sort it out. Possibly an event handler of some sort when the mouse reaches the edge of the window, while it is highlighting text, then the window can be moved automatically.

I suspect it has something to do with the the parent div of the iframe not knowing that the text is being highlighted. Highlighting text outside of the `div#pgp_block` element will allow the window to move when the mouse reaches the bottom of the screen.

**Comment by tomholub** [comment]
Thanks for looking into it. If you think you can fix it relatively easily, then try, else we can leave this for later.

**Comment by tomholub** [comment]
This may come pre-packaged in whatever solution we end up using for rich-text formatting: #668 so I'm closing this for now.
