### ISSUE TITLE
Error when trying to send empty signed-only message

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5730]
> I noticed just now that when trying to send a blank signed message, there was this unhandled error message that occurred.

<img width="549" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/8ff5f090-9edf-4cc1-9590-d503bd2dd2c1">

_Originally posted by @martgil in https://github.com/FlowCrypt/flowcrypt-browser/issues/5599#issuecomment-1940538245_

**Comment by martgil** [comment]
Hi @sosnovsky - this bug no longer exists as of this moment. But before, it exists when sending a signed email without an email body and title and the error above occurs.

Let's close this one.

**Comment by sosnovsky** [comment]
Hmm, this issue still occurs for me in `master` branch

**Comment by martgil** [comment]
I've checked it on my end as well. Could you share the steps you took to reproduce it? Perhaps it differs from the way we tested it.

**Comment by martgil** [comment]
For example, here's how I tested it based on my recollection:

[Screencast from 2024-05-23 20-04-28.webm](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/7887a115-208c-4e4f-932f-7fc3029c085e)

**Comment by sosnovsky** [comment]
Try to remove your signature from message input and you'll get mentioned error

**Comment by martgil** [comment]
Thanks  - I can replicate the issue now. Will proceed into fixing this.
