### ISSUE TITLE
"see original" functionality isn't working

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5733]
1. Open encrypted thread
2. Click `See original` button
3. Popup with original message opens, but FlowCrypt decrypts original message again, so there is no ability to check original message content

@ioanmo226 seems like it was caused by changes in the manifest v3 migration, it worked well in the previous release.
Please check this one after finishing your current task, thanks

**Comment by ioanmo226** [comment]
Hmmm... I couldn't reproduce issue.
When I click `see original` it correctly shows encrypted content.
Could you try to reproduce and let me know the reproduce steps?

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/3be3126a-fa44-4789-8a0a-4a754cbbf673)

**Comment by ioanmo226** [comment]
We also have ui test `settings - inbox - show original`

**Comment by martgil** [comment]
Hi @ioanmo226 - sorry for the interuption. I think what Roma's referring to is the "see original" button in Gmail. Where it returns another FlowCrypt-rendered solo email thread instead of just returning the original message.

**Comment by ioanmo226** [comment]
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/5f8f522c-34bc-4928-afd7-f668f2884b71)

This one also works fine though

**Comment by martgil** [comment]
I mean the green "see original" button on the right-side of every FlowCrypt-recognizable emails.

**Comment by ioanmo226** [comment]
Aha, I see
Yeah, I can reproduce this issue too
Thank you

**Comment by martgil** [comment]
No worries - thanks!

**Comment by sosnovsky** [comment]
Yeah, I've missed to note that it happens in Gmail UI, not in our encrypted inbox. @martgil thanks for explanation!
