### ISSUE TITLE
Group similar error reports

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5736]
There are many error reports which are sent in [doSendErrorToSharedTenantFes](https://github.com/FlowCrypt/flowcrypt-browser/blob/d4c6c45fadccc244e3de726427533c3c4dec6345/extension/js/common/platform/catch.ts#L313) with similar message like `429 when GET-ing https://www.googleapis.com/gmail/v1/users/me/threads/18fa6109b0f0d121 (no body)`, which has the only difference - thread id.

For such cases we should just replace such parameters with `THREAD_ID`, so similar reports will be grouped on our backend.

**Comment by sosnovsky** [comment]
the same happens for different extension ids, as example:
- `chrome-extension://mimchhddcelobciniokjnakmkcbdggof/chrome/elements/compose.htm`
- `chrome-extension://pjohdcpiapjhagmakkjpgjmodmgfmkkd/chrome/elements/compose.htm`

here we can replace extension ids with `EXTENSION_ID`

**Comment by sosnovsky** [comment]
Hi @ioanmo226, can you please work on this one before https://github.com/FlowCrypt/flowcrypt-browser/pull/5749, so it can be included in the 8.5.6 release to better distinguish client error reports. Thanks!

**Comment by ioanmo226** [comment]
Let me confirm
Do I have to replace those EXTENSION_ID and THREAD_ID in `url` field or `trace` field?
Or both?
![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/77344191/b32f612b-f3d5-441b-a083-571c84c00e1d)

**Comment by sosnovsky** [comment]
They should be changed in `url` and `message` fields, here is screenshot from error reports dashboard:

<img width="400" alt="Screenshot 2024-05-31 at 11 45 00" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/1062093/34cf5cb0-6ca7-4f9a-8fb1-9bfecdef20ae">

Currently I noticed 3 paths which should be replaced (maybe in the future there will be another ones):
- `https://www.googleapis.com/gmail/v1/users/me/threads/18fa6109b0f0d121` -> `https://www.googleapis.com/gmail/v1/users/me/threads/THREAD_ID`
- `https://www.googleapis.com/gmail/v1/users/me/messages/16deefad688886d1` -> `https://www.googleapis.com/gmail/v1/users/me/messages/MESSAGE_ID`
- `chrome-extension://mimchhddcelobciniokjnakmkcbdggof/chrome/elements/compose.htm` -> `chrome-extension://EXTENSION_ID/chrome/elements/compose.htm` (here I think we can just replace all `chrome-extension://some_extension_id_aksdnasoinfas/...` occurrences with `chrome-extension://EXTENSION_ID/...`
