### ISSUE TITLE
Pressing "Enter" twice in beginning/endings of quoted text required before a newline actually rendered 

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5740]
Description:

It was reported to us that it requires them to press the "Enter" on their keyboard twice before a newline to render. Upon further investigation, the issue exists when interacting onto the beginning or endings of the quoted text. To be specific, its on the the line where the "On <date>, <email> wrote:" starts or at the last occuring line of the quoted text "> some quoted text...".

Steps to reproduce:

1. Open Gmail with FlowCrypt browser extension set up.
2. Open any FlowCrypt-renderable emails (encrypted+signed or signed) in your inbox.
3. Click on "Secure Reply".
4. Click onto the "..." icon button on the bottom part of the Secure reply box to see the quoted email text.
5. On the section "On <date>, <email> wrote:" or at the last occuring line of the quoted text "> some quoted text...", try to press <kbd>Enter</kbd> and you'll not be getting an expected newline. It will require you to press <kbd>Enter</kbd> twice for a newline to be inserted.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/QgrcJHsbjBtCThLpRmNDcjlkLmVBPrQHhVB

**Comment by sosnovsky** [comment]
Maybe something related to https://github.com/FlowCrypt/flowcrypt-browser/issues/5599 ?

**Comment by martgil** [comment]
I checked it and its not related to it but its about how we process quoted email in the blockquote - [separateQuotedContentAndRenderText()](https://github.com/FlowCrypt/flowcrypt-browser/blob/d4c6c45fadccc244e3de726427533c3c4dec6345/extension/chrome/elements/pgp_block_modules/pgp-block-quote-module.ts#L12)
