### ISSUE TITLE
Don't report "400 when POST-ing https://flowcrypt.com/attester/welcome-message" error 

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5741]
We already have code for skipping this error - https://github.com/FlowCrypt/flowcrypt-browser/pull/5284, but these errors are reported again after manifest v3:
```
Bad Request: 400 when POST-ing https://flowcrypt.com/attester/welcome-message string: email,pubkey -> This key does not appear valid(Error: Could not find valid self-signature in key b4a63b803788e67e)
```

Maybe error text has changed and it's different from value in `IGNORE_ERR_MSG` array.

**Comment by martgil** [comment]
Upon checking, the error message we are checking is way too vast and so some other issue's that occurs on the `/attester/welcome-message` may still reports other issues.

![image](https://github.com/FlowCrypt/flowcrypt-browser/assets/46025304/0d021630-fc89-425d-aa0e-19440f4259a3)

So I think a way to solve this is to adjust the matching pattern regardless of the error text next to `Bad Request: 400 when POST-ing https://flowcrypt.com/attester/welcome-message string: email,pubkey ->`.
