### ISSUE TITLE
vscode - errors in content script

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#5746]
I can build it without errors, but the IDE is not happy. Are you seeing the same, or is it just me?

<img width="1251" alt="image" src="https://github.com/FlowCrypt/flowcrypt-browser/assets/6306961/2e4b2fce-f6e2-469e-a481-71b1cc73b996">

**Comment by sosnovsky** [comment]
Same for me - VS Code showing errors, but builds without any issues. Looks like some updates are needed for types in `Bm` - https://github.com/FlowCrypt/flowcrypt-browser/blob/dd2cdb80151bf7f7c69a51d75f2e936a905e7984/extension/js/common/browser/browser-msg.ts#L112

**Comment by tomholub** [comment]
From what I recall, when it builds fine but vscode is unhappy with specifically content script types, it's because vscode is set up with the rest of the browser extension code environment in mind, content scripts being code for a bit of a separate environment which confuses it.

I guess one possibility would be to have a separate code-workspace  file that is tailored for the content scripts only. Which is inconvenient. Or perhaps some other project settings.

But of course, if it can be managed to fix this just by updating types, then we could just do that.
