### ISSUE TITLE
refactor content scripts to make it easier to implement Thunderbird support

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#5747]
> One thing I noticed is that the `content_scripts/webmail` folder already on master is quite disorganised and not so easy to work on to add Thunderbird (or any other webmail) support. I country try and refactor it a little bit myself, and that could make it easier for you.

_Originally posted by @tomholub in https://github.com/FlowCrypt/flowcrypt-browser/issues/5690#issuecomment-2135257325_

**Comment by sosnovsky** [comment]
> Additionally, there used to be automatic code style changes on save (for example ordering of private/public methods). Was it disabled, does it work for anyone else?

private/public members ordering were auto-fixable in TSLint, but it needs to be manually fixed in ESLint.
Other common code styles issues are still automatically fixed on save.

**Comment by tomholub** [comment]
Got it 👌
