### ISSUE TITLE
[URGENT] FlowCrypt browser extension signin is blocked

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5790]
Description: Google block sign in flow on FlowCrypt browser extension and shows an error message the following error message:
```
This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access.
```

Steps to reproduce:

1.) Install FlowCrypt browser extension on https://flowcrypt.com/download.
2.) Try to login with your Google account and you'll get the following screen with error message from Google Login page:

![image](https://github.com/user-attachments/assets/85695c24-98b2-4c3b-becd-9c1c895f3e1a)

**Comment by martgil** [comment]
cc: @sosnovsky - This affects new users but also old user when the moment they will have to reconnect their account. This makes the extension completely unusable. Enterprise users might've notice this soon.

I'm looking into a fix for this one but I can't guarantee an exact timeline as the information  from error message is pretty limited.

**Comment by martgil** [comment]
Upon investigation, this is the result of Google's preparation in their upcoming transition on how less secure apps to be treated and attached an advice on how those deemed less secure apps should be configured to become secure:

https://support.google.com/accounts/answer/6010255#more-secure-apps-how

**Comment by martgil** [comment]
I performed additional checks against the following assets:

FlowCrypt web, android and ios apps - all of its user sign in with Google works fine.

**Comment by sosnovsky** [comment]
@martgil thanks for letting know, checking it

**Comment by sosnovsky** [comment]
For now, if we'll get any support requests about this issue - please advise to use iOS or Android app, until we'll resolve this issue, thanks!

**Comment by sosnovsky** [comment]
@martgil I found reason for this issue - we need to perform re-verification of used authorization scopes for Google APIs, I'll submit all needed data for verification, hope it'll be solved soon.

**Comment by martgil** [comment]
Thank you Roma for taking an immediate action on this.

**Comment by tomholub** [comment]
Google didn't warn us ahead of this action whatsoever.

**Comment by martgil** [comment]
@tomholub @sosnovsky I checked this once again and I was able to logged in with my Google Account.

**Comment by sosnovsky** [comment]
> @tomholub @sosnovsky I checked this once again and I was able to logged in with my Google Account.

For me it works for flowcrypt demo gmail account, but doesn't work for my own gmail test account.
Currently waiting for google review team response

**Comment by martgil** [comment]
Got it - thank you!

**Comment by martgil** [comment]
Hi @sosnovsky - Does Google share any relevant information about their re-verification process?

**Comment by sosnovsky** [comment]
Hi @martgil, unfortunately it's not so quick as expected - we've passed first stage of verification which is done by Google, but now they request us to perform verification by 3rd-party partner.
I'll ask if it's possible to re-enable our app while we're in the process of verification.

**Comment by martgil** [comment]
Hello @sosnovsky, thank you so much for the quick update. I fully understand. Hopefully, they will allow lifting the app blocking by this week.

**Comment by sosnovsky** [comment]
Hello @martgil, we've successfully passed security review by Google's security partner, they sent verification confirmation to Google. Hope it'll be resolved in the beginning of the next week, will keep you updated.

**Comment by martgil** [comment]
Hi Roma, good morning! Thank you for the update - it is good news. I look forward to the next update. I'm always here when you need some help.

**Comment by sosnovsky** [comment]
Hi @martgil, FlowCrypt browser extension was successfully re-verified by Google ✅

**Comment by martgil** [comment]
Hello @sosnovsky, thank you. I can confirm that as well when logging into my account. I'm in the process of informing all the previously affected users about this.
