### ISSUE TITLE
missing key management features?

### ISSUE THREAD

**Issue by kamaradski** [FlowCrypt/flowcrypt-browser#5803]
Unless i'm overlooking something, I miss some basic features to manage my pgp key in the browser tool.

- Option to rotate my key (flowcrypt to generate the new key for me) (maybe keep the old key around for decryption purposes only?)
- Option to add a secondary key in another format and where Flowcrypt can generate the new key for me
- Option to manage backups. as users loose the passphrase (or rotate their key) there might be a cleanup need

Usecase:

1) generic adaption: I love PGP email and consider it a missing core feature of email in general. I work for a smaller company and in order for me to convince other people (especially less technical) to use PGP is very hard as long as it remains hard to work with it. So i think it is important that Flowcrypt can generate the keys in all cases.

2) secondary key: Someone in Sales is working with a very big partner that started to enforce the use of PGP with RSA2048 keys, while we internally use more modern Ed25519 keys. So now i should ask this completely non-technical Sales person to "install gnu-cli, use the terminal to generate a new key, and add it to flowcrypt manually?". As you can imagine this won't fly.

3) key rotation: a) Basically i'm just a fan of rotating keys instead of working 10 years with the same one. This should be fine as long as the new public key is published correctly and one keeps the old key available to decrypt older emails. b) And then there is always this one user that forgets their Passphrase and no longer can use the old key. Currently i instruct such users to de-install Flowcrypt, and re-install so they can use the UI to generate a new key even though this causes the old key to be stuck in the backup.

4) manage backups: for the case-b outlined in usecase 3 where a user forgets their passphrase, but also in general when one decides to rotate the key for whatever reason i think one should be able to select the key to keep in backup or not. Personally i had the case where i previously installed and uninstalled Flowcrypt for my work account, and when i re-installed it a few years later i wanted to start with a new key, the old one is still in my backup even though i will never use it anymore.

**Comment by sosnovsky** [comment]
Closing this one, further development process will be in https://github.com/FlowCrypt/flowcrypt-browser/issues/5811
