### ISSUE TITLE
Sending feedback to /shared-tenant-fes/api/v1/account/feedback should be encrypted by a reciever's public key

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5807]
Current Behavior: Feedback going to `api.feedback.form.email.address.to` is PGP-encrypted.

Expected Behaviour: It should be encrypted by the client app first before the message is passed to `/shared-tenant-fes/api/v1/account/feedback`.

Screenshot:

![image](https://github.com/user-attachments/assets/f8ee6d29-545d-4cc2-9bc1-9e6ba6ebd71e)

**Comment by martgil** [comment]
Hi @sosnovsky - Just a quick questions - is it possible to obtain the `api.feedback.form.email.address.to` from public api (authenticated)? or at least a way for obtaining the appropriate public key to which we will encrypt the message before passing to `/shared-tenant-fes/api/v1/account/feedback`.

Reference: https://flowcrypt.com/docs/technical/enterprise/configuration/feedback-form.html#properties-file-section-feedback-form

**Comment by sosnovsky** [comment]
Hi @martgil, currently there it's not possible to obtain `api.feedback.form.email.address.to` value from client app. It's used only on backend when sending feedback message.

> Current Behavior: Feedback going to api.feedback.form.email.address.to is PGP-encrypted.

Is it correct? It seems message is sent non-encrypted, that's why we receive `invalid PGP message` error.

**Comment by sosnovsky** [comment]
I checked FES code and looks like originally we didn't expect feedback message to be encrypted, it was just a plain text. But during some migration we've added this additional check, which is not needed and should be removed.

**Comment by martgil** [comment]
Thanks @sosnovsky - That means, there's nothing to update here but on the private repo. I'll be working on that now.

**Comment by sosnovsky** [comment]
similar issue - https://github.com/FlowCrypt/flowcrypt-browser/issues/4712
