### ISSUE TITLE
[Feature Suggestion] Ability to generate keys within the extension

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5811]
Description: The ability to generate keys within the FlowCrypt browser extension can be useful in cases where a user needs to generate a new key for themselves or others.

Ideally, this feature could include additional checkboxes asking whether the key that is about to be generated should be stored and added to the user's key list or not. This would allow users to choose between storing the key for future use or simply generating it for immediate distribution (i.e., generate and forget). Users should also be able to select key types and algorithms during the generation process.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzQVzFNhdqCqRtGmqlQspMRKxHxD

**Comment by martgil** [comment]
@sosnovsky - Could you please check the validity and priority of this issue? Thanks!

**Comment by sosnovsky** [comment]
This one should be a convenient addition to extension functionality, there are already several similar issues and seems like many users asked for such functionality:
- https://github.com/FlowCrypt/flowcrypt-browser/issues/2865
- https://github.com/FlowCrypt/flowcrypt-browser/issues/5190
- https://github.com/FlowCrypt/flowcrypt-browser/issues/942

We can start with adding `Generate key` option to `Add private key` modal

<img width="800" alt="Screenshot 2024-08-26 at 13 06 34" src="https://github.com/user-attachments/assets/004ac574-4d74-4a8c-89bf-1dcb69e26c6a">

**Comment by sosnovsky** [comment]
@ioanmo226 let's make this functionality quite simple. It should look like `Paste armored key directly` option, but instead of textview there should be 2 options:
- `ECC Curve25519 (modern, faster)`
- `RSA 4096 (for compatibility with legacy software)`

<img width="600" alt="Screenshot 2024-08-28 at 12 42 10" src="https://github.com/user-attachments/assets/72367bcd-4c1b-4cb4-b4b9-71de89574cbb">

I think this should be enough for most users, as RSA2048 and RSA3072 are slower and less secure than ECC keys.

**Comment by ioanmo226** [comment]
Okay, Got it

**Comment by ioanmo226** [comment]
@sosnovsky How about below Mart's comment?
I think we should also consider this feature?

> Ideally, this feature could include additional checkboxes asking whether the key that is about to be generated should be stored and added to the user's key list or not. This would allow users to choose between storing the key for future use or simply generating it for immediate distribution (i.e., generate and forget).

**Comment by ioanmo226** [comment]
What about the passphrase? Should we allow users to choose a passphrase for their generated keys, or do we have to generate unprotected private keys

**Comment by sosnovsky** [comment]
> @sosnovsky How about below Mart's comment? I think we should also consider this feature?
> 
> > Ideally, this feature could include additional checkboxes asking whether the key that is about to be generated should be stored and added to the user's key list or not. This would allow users to choose between storing the key for future use or simply generating it for immediate distribution (i.e., generate and forget).

I think it'll be quite rare case when users will want to just generate key but not use it.
For this purpose they can generate new key, then go to their keys list, download public/private keys and then just remove this key. Should be quite straightforward and won't require any UI changes. What do you think?

> What about the passphrase? Should we allow users to choose a passphrase for their generated keys, or do we have to generate unprotected private keys

Yes, they should set passphrase when generating key and `remember the pass phrase after closing the browser` checkbox should be visible too (like on screenshot in https://github.com/FlowCrypt/flowcrypt-browser/issues/5811#issuecomment-2314853848)

**Comment by ioanmo226** [comment]
I agree
> Should be quite straightforward and won't require any UI changes. What do you think?

Sounds good
> Yes, they should set passphrase when generating key and remember the pass phrase after closing the browser checkbox should be visible too (like on screenshot in https://github.com/FlowCrypt/flowcrypt-browser/issues/5811#issuecomment-2314853848)

**Comment by ioanmo226** [comment]
I think we should clone the key generation logic from the setup process.
Alternatively, we could display the screen below in an iframe when the user clicks the Generate key button (making sure to update the page title and text as needed). Also, I think we should show the backup key view after the user has generated a key.

![image](https://github.com/user-attachments/assets/b8eb691d-9ade-443c-8d73-a8282d6b5022)

![image](https://github.com/user-attachments/assets/55a30700-8165-43c4-99cb-882f919046ae)

**Comment by ioanmo226** [comment]
Let me know your thoughts

**Comment by sosnovsky** [comment]
> I think we should clone the key generation logic from the setup process. Alternatively, we could display the screen below in an iframe when the user clicks the Generate key button (making sure to update the page title and text as needed). Also, I think we should show the backup key view after the user has generated a key.

Great idea! Yes, let's reuse UI from key generation in setup process and show backup options after that.

**Comment by ioanmo226** [comment]
@sosnovsky I think we can safely close those issues now?

> This one should be a convenient addition to extension functionality, there are already several similar issues and seems like many users asked for such functionality:
> 
> * [option to generate another key #2865](https://github.com/FlowCrypt/flowcrypt-browser/issues/2865)
> * [[Feature Suggestion] Ability to set/update key expiration #5190](https://github.com/FlowCrypt/flowcrypt-browser/issues/5190)
> * [renew / change key expiration #942](https://github.com/FlowCrypt/flowcrypt-browser/issues/942)
> 
> We can start with adding `Generate key` option to `Add private key` modal
> 
> <img alt="Screenshot 2024-08-26 at 13 06 34" width="800" src="https://private-user-images.githubusercontent.com/1062093/361397517-004ac574-4d74-4a8c-89bf-1dcb69e26c6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0OTA2MzcsIm5iZiI6MTcyNjQ5MDMzNywicGF0aCI6Ii8xMDYyMDkzLzM2MTM5NzUxNy0wMDRhYzU3NC00ZDc0LTRhOGMtODliZi0xZGNiNjllMjZjNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTZUMTIzODU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTI0YzAyNzRjZmVhMDBlZTMwMGZlMmQxYmUwMzY5ZDI1MDlmMDEwMzgyODk5ZWNiYTcxODEzNmEzN2EwOGNjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ypJS8zEK3Jl6qNXbou_PHaZsSPVbI8wWTLIGUNqcS0g">

**Comment by sosnovsky** [comment]
I closed https://github.com/FlowCrypt/flowcrypt-browser/issues/2865, but 2 other issues are related to changing key expiration. This functionality is a bit different - maybe we'll add it in the future

**Comment by ioanmo226** [comment]
Aha, I see
