### ISSUE TITLE
[Feature Suggestion] Ability to manage any backups from Gmail

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5812]
Description: The ability to delete FlowCrypt backups directly from the FlowCrypt settings is also a useful addition suggested by users. A possible implementation could be a subsection within the "Backup" menu that lists existing key backups, with each listed key identifiable by its fingerprint and having a directly accessible "delete backup" button.

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzQVzFNhdqCqRtGmqlQspMRKxHxD

**Comment by martgil** [comment]
Hi @sosnovsky - Could you please check the validity and priority of this issue? Thanks!

**Comment by sosnovsky** [comment]
Hi @martgil, sorry for delayed response!

As for me, there is no need to implement such functionality directly into FlowCrypt extension - it can lead to accidental backup deletion.
Currently users can search their Gmail for `flowcrypt backup` to find all stored backups and delete those that are not needed. However, it should be a quite rare case, as usually there is no issue with old backups stored on Gmail.

**Comment by martgil** [comment]
Hello @sosnovsky - Sorry for the delayed reply. I understand your perspective on this issue and that accidental backup deletions can happen. I have already informed the user via email.
