### ISSUE TITLE
Fix 'typescript-eslint/no-deprecated' errors

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5822]
`typescript-eslint` added new rule `no-deprecated`, it'll be useful for finding and updating all usages of deprecated methods in our code.

It found around 160 deprecation errors - https://flowcrypt.semaphoreci.com/jobs/4d93845e-1561-4254-a759-2ff804ade7c9

**Comment by ioanmo226** [comment]
For reference

> A real-world example of this is in the @types/chrome package, which provides typing for browser-specific APIs exposed by Chrome for use in Chrome Apps and Chrome Extensions. There are a bunch of specific APIs that are deprecated, such as:

https://github.com/typescript-eslint/typescript-eslint/issues/9902#issue-2493189703
