### ISSUE TITLE
cannot sign a message if primaryKey missing and using subkey: key not decrypted

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#583]
> Regarding signing of messages, I get an error saying "Private key is not decrypted". Is this maybe a problem because of a missing primary key and a extra subkey for signing messages.

**Comment by tomholub** [comment]
another case: support https://mail.google.com/mail/u/1/#inbox/15b4a0e2fbf06dee

cannot sign atttest + cannot sign emails / encrypted key / accepts pass phrase but says "Private key is not decrypted"

**Comment by arsham** [comment]
I'm using gnupg 2.2.1 on linux. I have a sub key pairs (SE: RSA2048) and I get this error when I click the sign key. I have tried generating a few keys (with fresh master key), I still receive this error.
Extra info: I have tried this with mailvelope and it cannot be decrypted with that extension too. 
Signing and decrypting files in terminal is fine.

**Comment by tomholub** [comment]
looks like something we need to fix in OpenPGP.js. Can you please create a bogus private key for me that is showing this behavior. If you could paste:

1) misbehaving private key (and pass phrase if any or keep without pass phrase)
2) a message signed with the key in terminal

That will help me debug it.

**Comment by arsham** [comment]
Hi,
I have [made the keys](https://www.dropbox.com/s/xcwt3drqaazbi55/keys.tar.gz?dl=0) and put the steps taken in the message.txt file. The pass phrase is **1**. The gnupg folder is included in case you need to dig into the keyring. 

BTW, I love your plugin. It has been improved since last time I tried it about a year ago. Well done!

**Comment by tomholub** [comment]
[keys.tar.gz](https://github.com/FlowCrypt/flowcrypt-browser/files/1395134/keys.tar.gz)

I'm saving them here so that I can still find it when I get time to debug it. Thanks!

**Comment by arsham** [comment]
Just a quick feedback: I just imported my keys into firefox and it signs the message just fine. The problem seems to be related to google chrome.

**Comment by tomholub** [comment]
That's weird. It still doesn't work in Chrome, but does in Firefox?

**Comment by arsham** [comment]
Correct. I just tried with chromium (Arch Linux OS), got the same issue.

**Comment by dpnova** [comment]
I'm seeing this too. Ubuntu 17.10 and chrome. Just a subkey in my flowcrypt config.

**Comment by tomholub** [comment]
Subkey-only key exported from GPG, is that correct @dpnova ?

**Comment by ppmotskula** [comment]
Same behaviour here. Ubuntu 17.10, Chromium, separate signing subkey. Decryption works, signing doesn't.

**Comment by tomholub** [comment]
@ppmotskula Is that also a subkey-only key or some other structure?

**Comment by ppmotskula** [comment]
It's a subkey-only key.

**Comment by tomholub** [comment]
ref https://github.com/openpgpjs/openpgpjs/issues/251

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#sent/16128e119ace56ed

**Comment by tomholub** [comment]
This should now be solved. Please try and report success or failure back, thanks!
