### ISSUE TITLE
Incorrect newlines when composing reply message

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5838]
- go to `flowcrypt.compatibility` inbox
- open `#5466 unencrypted reply` thread
- expand first message
- click `secure reply` on first message toolbar
- type "Hello<kbd>Enter</kbd>World"
- you'll get
```
World
Hello
```

@martgil you already fixed same issue in https://github.com/FlowCrypt/flowcrypt-browser/pull/5729, maybe similar fix will work here too.

**Comment by martgil** [comment]
Sorry for the late reply. I'll check it again manually and prepare a PR for this issue really soon.
