### ISSUE TITLE
Thunderbird (master branch) complains about messageDisplayScript undefined due to possible change of manifest version

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-browser#5848]
Description:

There's an error message saying that the usage of `messageDisplayScript` is undefined.

![image](https://github.com/user-attachments/assets/ae69e1fd-14c3-4f77-88ec-bf49956192b2)

Upon checking, the Thunderbird 91 or older only supports messageDisplayScript for already opened pages https://webextension-api.thunderbird.net/en/91/messageDisplayScripts.html and so it does not work for Thunderbird client version128 ESR version or latest. 

![image](https://github.com/user-attachments/assets/590f3c2a-04da-4671-be3b-f6a6acc57be9)

So from the latest documentation available at https://webextension-api.thunderbird.net/en/128-esr-mv2/messageDisplayScripts.html, it is suggested to use [executeScript](https://webextension-api.thunderbird.net/en/128-esr-mv2/tabs.html#tabs-executescript) for maximum compatibility possible.

![image](https://github.com/user-attachments/assets/f35ff10c-c293-4b62-97af-8eba94253d29)

**Comment by martgil** [comment]
Taking a closer look of this issue, it seemed to have caused by the last changes related to change of manifest file that affects FlowCrypt for Thunderbird port.

**Comment by martgil** [comment]
I'll prepare to migrate the existing code to manifest v3 as some parts of the build is still using manifest v2.

For me: https://webextension-api.thunderbird.net/en/beta-mv3/changes/128.html

**Comment by martgil** [comment]
Another blocking issue is that the typescript typing for Thunderbird API we're using is still for Thunderbird version 127 ESR and not for major update 128 (beta) for version 3 - https://www.npmjs.com/package/@types/firefox-webext-browser

**Comment by martgil** [comment]
Users can still use the current build for Thunderbird ESR version < 128 until the current build gets migrated to version 3 and the MailExtension API usages across the codebase.

**Comment by sosnovsky** [comment]
Probably we can continue using manifest v2 for thunderbird until typescript typing will be updated?

**Comment by martgil** [comment]
Yes @sosnovsky, I've tested it and the latest version of Thunderbird works well with manifest v2 extensions. Would you be okay with that if we continue using manifest v2 for the Thunderbird port? While the rest (chrome and firefox) builds uses v3.

**Comment by sosnovsky** [comment]
No issue with manifest v2 for thunderbird, as it's probably doesn't affect extension functionality and I'm not sure if we currently have any thunderbird users. So let's stick with it for now.
