### ISSUE TITLE
Display warning for incorrect PGP checksum

### ISSUE THREAD

**Issue by ioanmo226** [FlowCrypt/flowcrypt-browser#5868]
Got it, then let's stick with the newest spec and update test to expect decrypted message text.

By the way, is there any possibility to find if message has incorrect checksum?
Then we at least be able to show some warning about checksum issue

_Originally posted by @sosnovsky in https://github.com/FlowCrypt/flowcrypt-browser/issues/5866#issuecomment-2493073744_

**Comment by ioanmo226** [comment]
Maybe the warning message should be like below?

> Warning: Checksum mismatch detected. This indicates the message may have been altered or corrupted during transmission. Decryption may still succeed, but verify the message source and integrity if possible.

**Comment by sosnovsky** [comment]
Sounds good 👍 Let's use it

**Comment by ioanmo226** [comment]
@sosnovsky  This is the only remaining task assigned to me in the current milestone. (Other assigned tasks are in a later milestone or awaiting reproduction.)
Could you please review and assign new tasks?
