### ISSUE TITLE
Password-protected messages compliance

### ISSUE THREAD

**Issue by sosnovsky** [FlowCrypt/flowcrypt-browser#5878]
To ensure password-protected messages comply with security rules, client apps must check the subjects of composed password-protected email messages for specified strings. If any configured terms are found, the application should display an error message indicating that the password encryption method is incompatible with the composed message.

Client configuration will have 2 new optional properties (subject check should be performed only if both properties are set):
- `disallow_password_messages_for_terms` (_string[]_) - specifies an array of strings to check against the subject of the composed password-protected message. If any string in this array is found in the subject, an error alert must be displayed.
- `disallow_password_messages_error_text` (_string_) - defines the text to be displayed in the error alert.

related https://github.com/FlowCrypt/flowcrypt-ios/issues/2644

**Comment by ioanmo226** [comment]
Okay, Sure
