### ISSUE TITLE
minimize 'secure compose' window

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#612]
<img width="661" alt="screen shot 2017-03-13 at 3 08 57 pm" src="https://cloud.githubusercontent.com/assets/3431871/23884700/89126c40-082b-11e7-8a68-5106824e4519.png">

**Comment by tomholub** [comment]
yeah it can get annoying right

**Comment by mondo989** [comment]
*Shakes fist angrily*

**Comment by tomholub** [comment]
very actionable! Add a minimize icon (actually you can just use a bold underscore white letter...) and make it do something somewhat similar to gmail

**Comment by qialex** [comment]
I'll try to implement it

**Comment by schmorrison** [comment]
@qialex , any luck on putting this together? Ill take a crack at it if you haven't had a chance yet, but I don't want to work on something that is almost feature complete.

Best regards.

**Comment by tomholub** [comment]
It's free, you can take it.

**Comment by schmorrison** [comment]
I thought this was a simple event listener on a button that changed the CSS. But looking into it, it seems like the iframe has a height set (for good reason), so the scope of an event listener inside the iframe won't work as far as I can tell.

It looks more like the event listener will need to send a BrowserMsg like the secure compose button, or the close page button. I am not really sure how this mechanism works, or how to register a BrowserMsg handler.

I think I will need some further explanation before I dive into this one.

**Comment by tomholub** [comment]
Correct, you will have to mimic the close button. There is a `setCss` BrowserMsg that you can reuse - pgp_block.ts uses this. On minimize, you send this browser message to the parent tab (Gmail content script) which will set css of the iframe to be smaller. To undo, you'll do the opposite.

You will also have to change the css of the iframe body internally. I think a good way to do that would be to use `@media max-height` kind of css rule in the stylesheet. In the rule it could say that if the body of the compose box has a low height (eg equal or less than whatever the height of the minimized frame), than all elements marked as `.hide_when_minimized` would not be displayed. That way css does the work for you and you don't have to manually hide/show them in the JS. You'll then only have to change the height using the `setCss` query, and change the minimize / maximize button similar to what Gmail does.

I recommend to use the UTF8 minimize character: `🗕` (white)

**Comment by tomholub** [comment]
Edited msg above
