### ISSUE TITLE
GPG key public import and external keyserver support is broken

### ISSUE THREAD

**Issue by zaolin** [FlowCrypt/flowcrypt-browser#656]
Hey,

I tried to import normal ascii armored gpg public keys but it wasn't possible.
Same goes for publishing my key to a gpg keyserver which is synced with other
gpg keyserver

You may want to fix that.

**Comment by tomholub** [comment]
@zaolin Was this in CryptUp Settings -> Additional Settings -> Contacts -> bulk import?

Can you post the pubkey here please? Alternatively, send it to my email: tom@cryptup.org

**Comment by tomholub** [comment]
Closed, missing clarification. Feel free to comment & I'll re-open.
