### ISSUE TITLE
spell checking not working on some chrome versions

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#662]
<img width="577" alt="screen shot 2017-03-26 at 3 59 28 pm" src="https://cloud.githubusercontent.com/assets/3431871/24336029/48d2b8c6-123d-11e7-9695-c0f02dd5b8b6.png">

**Comment by tomholub** [comment]
Ha. I'll look into this one day :)

**Comment by mondo989** [comment]
Surely not mission critical, but just wanted to make note.

**Comment by tomholub** [comment]
Got two more reports. Turns out this is a Chrome bug on some versions.

Works: 
 - SRWare Iron 56.0.2950.0 (Official Build) custom (64-bit)

Does not work:
 - Google Chrome 57.0.2987.133 (Official Build) (64-bit)
