### ISSUE TITLE
non-ascii characters in file names

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#665]
eg Cyrillic

**Comment by tomholub** [comment]
Test how well we support non-ascii characters in filenames. For this you can test it in the following directions:
1) FlowCrypt -> FlowCrypt
2) FlowCrypt -> Enigmail + Thunderbird
3) Enigmail + Thunderbird -> FlowCrypt

We're interested to see that there are no issues displaying the filename and that the retains the same name after downloaded.

If you don't encounter any issues, please comment and close the issue.

If you encounter an issue, please document the issue here and see if you can fix it.

**Comment by michael-volynets** [comment]
I can confirm that:
1. FlowCrypt -> FlowCrypt - works good
2. FlowCrypt -> Enigmail + Thunderbird - works good
3. Enigmail + Thunderbird -> FlowCrypt - works good

Everything works well on all the variants.

**Comment by tomholub** [comment]
Great, when you have a result like that (nothing to fix), you can also close the issue along with the comment. Thanks for testing it!
