### ISSUE TITLE
save non-matching emails to localdb when searching contacts

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#709]
only the "found/matching" ones get saved locally, but other emails are encountered while searching contacts. all should be saved locally, making it easier to search next time

**Comment by michael-volynets** [comment]
I just tested it and it seems to be already resolved. We already save all emails that Google Contacts API and when searching for contacts in Inbox.

Or I may not know what other email addresses can be encountered while searching. I went through the code but didn't find anything.

**Comment by tomholub** [comment]
I think this was referring to searching contacts without Google Contacts API (see the date the issue was opened). Look at `Google.gmail.searchContacts` which is using methods like `apiGmailLoopThroughEmailsToCompileContacts`. My understanding of this issue is that this method looks through various email messages to find email addresses that (at least partly) match the search query. These then get returned, and saved to Contacts.

It would make sense to save to contacts ALL email addresses that were parsed out of these emails (only in `to:` header), regardless if they matched the current search query or not.

Of course, the actual results of the search for a particular query should remain unchanged. This is about also saving email addresses that we encounter (which the user has sent emails to before) that don't match the current query.

**Comment by tomholub** [comment]
Un-assigning for now

**Comment by tomholub** [comment]
Closing without a fix
