### ISSUE TITLE
pop out/maximize secure compose window

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#714]
This will involve adding a maximize icon to the left of close icon in our Secure Compose window. Behavior similar to what Gmail does.

You can use maximize or minimize icons from https://feathericons.com/ - please choose style that you think fits better.

![image](https://user-images.githubusercontent.com/6306961/55668388-3d94b400-5859-11e9-9f09-38862814ed32.png)

--------------------------

Functionality similar to Gmail: when I click on it, it window will get maximized from small:

![image](https://user-images.githubusercontent.com/6306961/55578967-a7e90f80-5706-11e9-8ff0-fdae892d584c.png)

to big (make sure to also lift it a bit from the bottom, like Gmail does):

![image](https://user-images.githubusercontent.com/6306961/55578972-acadc380-5706-11e9-9e5a-9c7aa67f5a8f.png)

And back to normal size if I click on it again.

**Comment by tomholub** [comment]
https://mail.google.com/mail/u/1/#inbox/15cef8079148cf42

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/163016d3c86314d7

**Comment by michabbb** [comment]
it´s only css, so please don´t wait too long with that... thanks !

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/163730a1a78123df

**Comment by tomholub** [comment]
reserving this as a screening issue

**Comment by tomholub** [comment]
Lyova is taking it

**Comment by tomholub** [comment]
Available again.

**Comment by michael-volynets** [comment]
@tomholub do you know how I can add class to the element out of iFrame?
e.g. here 
![image](https://user-images.githubusercontent.com/49104848/57875304-48107900-781b-11e9-968e-7523306f5aae.png)

I was trying to use BrowserMsg.send (I created some new methods such as add_class and remove_class)
but, I don't know why, its behavior is very weird. Sometimes it works, sometimes it doesn't.

I need to add the class synchronously.
Maybe you know some way to do it.
Thanks

**Comment by tomholub** [comment]
> I was trying to use BrowserMsg.send (I created some new methods such as add_class and remove_class)

That is probably what you have to do, I don't know of any other way

> but, I don't know why, its behavior is very weird. Sometimes it works, sometimes it doesn't.

One thing to remember is that while your iframe content will refresh right away, the content script code will not. You have to trigger an extension update for content scripts to update ( in chrome://extensions click the refresh button).

That should make your content scripts start using the new code. Maybe that was your issue. If not, share the code and I'll take a look.

> I need to add the class synchronously.

All of these calls will always be processed asynchronously, there's not much we can do about that, but it should not be a problem - hopefully.

**Comment by tomholub** [comment]
You may also be able to use the `set_css` call. With that you can set any css you want on any frame. That way you don't have to create another call to set classes - less code to maintain in the future.

**Comment by michael-volynets** [comment]
yes, I tried to use set_css also but it works asynchronously and doesn't return a promise to await it.
I need synchronously function because just after I added/removed styles I need to call `resizeInputTo` function

So, I created the same function but in `BrowserMsg.send.bg.await` and started it synchronously but `resizeInputTo` still didn't work, then I tried to call `resizeInputTo` function in `setTimeout` and it worked but worked sometimes and its behavior was weird.

**Comment by tomholub** [comment]
I think we had a miscommunication when it comes to terminology. Anything that does not happen in current event loop cycle is considered asynchronous (including awaited promises, although they "look" more synchronous).

But now I better understand what you're trying to do.

You could avoid the problem by listening for frame resize events. Notice how reply frame will resize itself when you stretch the window it is in. The inner iframe learns about it through a DOM event and will fire `resizeInputTo` automatically (I think). You can just allow that code to run on new message iframes too, and then you don't have to await that (asynchronous) background call.

**Comment by tomholub** [comment]
This took me a while to find, it happens here:
```js

**Comment by tomholub** [comment]
You could maybe rename it to `resizeComposeBox`, then add an `else` to deal with logic that concerns new messages.
```js
  resizeReplyBox = (addExtra: number = 0) => {
    if (this.urlParams.isReplyBox) {
      this.S.cached('input_text').css('max-width', (this.S.cached('body').width()! - 20) + 'px'); // body should always be present
      let minHeight = 0;
      let currentHeight = 0;
      if (this.S.cached('compose_table').is(':visible')) {
        currentHeight = this.S.cached('compose_table').outerHeight() || 0;
        minHeight = 260;
      } else if (this.S.cached('reply_msg_successful').is(':visible')) {
        currentHeight = this.S.cached('reply_msg_successful').outerHeight() || 0;
      } else {
        currentHeight = this.S.cached('prompt').outerHeight() || 0;
      }
      if (currentHeight !== this.lastReplyBoxTableHeight && Math.abs(currentHeight - this.lastReplyBoxTableHeight) > 2) { // more then two pixel difference compared to last time
        this.lastReplyBoxTableHeight = currentHeight;
        BrowserMsg.send.setCss(this.urlParams.parentTabId, { selector: `iframe#${this.urlParams.frameId}`, css: { height: `${(Math.max(minHeight, currentHeight) + addExtra)}px` } });
      }
    }
  }
```

**Comment by michael-volynets** [comment]
@tomholub here is a video of what I'm talking about: https://drive.google.com/file/d/1DPNSWvhJXtjXCtO2Or7Mnt8cGLHGmGlI/view?usp=sharing

In the video, you can see that sometimes the header icons hide after I minimize composer, it happens because the input width is more than the composer width (in the video you can see).

I don't exactly understand why this happens because I call `resizeInputTo` after I changed the CSS,
here is the code:
```
    if (!this.isMaximized) {
      await BrowserMsg.send.bg.await.addClass(this.urlParams.parentTabId, { class: this.FULL_WINDOW_CLASS, selector: 'div#new_message' });
      this.S.cached('compose_table').addClass(this.FULL_WINDOW_CLASS);
    } else {
      await BrowserMsg.send.bg.await.removeClass(this.urlParams.parentTabId, { class: this.FULL_WINDOW_CLASS, selector: 'div#new_message' });
      this.S.cached('compose_table').removeClass(this.FULL_WINDOW_CLASS);
    }
    this.resizeInputTo();
    this.isMaximized = !this.isMaximized;
```
But it works every time when I'm debugging exactly the same code or when I put `resizeInputTo` into `setTimeOut` function with 100ms timeout.

Also, I've changed `resizeInputTo` function to this:
```
  private resizeInputTo = () => { // below both present in template
    this.S.cached('input_to').css('width', 'unset;'); // Need to reset width because it affects parent elements
    this.S.cached('input_to').css('width', (Math.max(150, this.S.cached('input_to').parent().width()! - this.S.cached('input_to').siblings('.recipients').width()! - 50)) + 'px');
  }
```

I added this line of code ` this.S.cached('input_to').css('width', 'unset;'); ` 
I need to to it because when I minimize the composer window the width of input is very long and it affects on the perent elements.

I was investigating it but I haven't found any solution yet.

Have you had such situations before?

**Comment by tomholub** [comment]
I had to request access to the video, please approve

**Comment by tomholub** [comment]
Most likely it just takes some time before the change of size of the outer iframe is reflected from the perspective of the inside of the iframe.

Is there somewhere where I can see the code? You can make a PR and indicate that it's not ready to be merged yet.

**Comment by tomholub** [comment]
I found the branch, no need to make a PR

**Comment by tomholub** [comment]
My question would be, if you take this code out of the `if(isReplyBox)` branch, and change the iframe size, does `resizeReplyBox` not get executed?

```js
$(window).resize(Ui.event.prevent('veryslowspree', () => this.resizeReplyBox()));
```

`resizeReplyBox` should be getting executed when iframe size changes. Then, you can put your after-resize logic there, and it will reliably work without having to put `setTimeout` delays.

**Comment by tomholub** [comment]
So you would have

```js
  resizeReplyBox = (addExtra: number = 0) => {
    if (this.urlParams.isReplyBox) {
       ...
    } else {
      this.resizeInputTo();
    }
  }
```

Of course, after that, you may as well rename it from `resizeReplyBox` to `resizeComposeBox`.

Does this make it work?

**Comment by michael-volynets** [comment]
Yes, Thanks Tom!
but when I use `Ui.event.prevent('veryslowspree' the `resize` event works with some delay so I removed it and it works perfectly. Thanks

**Comment by tomholub** [comment]
The delay is intentional. Else slower computers will melt trying to process so many resize events (eg when resizing windows by hand). It should be barely noticeable though
