### ISSUE TITLE
When clicking 'Enter Passphrase' to open message, Passphrase input should be 'in focus' by default. 

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#769]
<img width="853" alt="screen shot 2017-05-14 at 11 32 25 am" src="https://cloud.githubusercontent.com/assets/3431871/26035387/31978f56-3899-11e7-9dee-6ef50c97f252.png">

Not too major, but saves me an extra click. 
As it is my intent to enter a passphrase.

**Comment by tomholub** [comment]
Absolutely
