### ISSUE TITLE
Enter Passphrase -> pressing return should confirm dialog (eg click ok)

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#770]
<img width="555" alt="screen shot 2017-05-14 at 11 37 12 am" src="https://cloud.githubusercontent.com/assets/3431871/26035423/c7dbe7a0-3899-11e7-8100-1dda76a6fc64.png">

Minor, but makes the experience easier.

**Comment by tomholub** [comment]
Yup, part of #477. This is one of the more important ones because it happens often

**Comment by tomholub** [comment]
Susmita reserved this

**Comment by tomholub** [comment]
Reproduce: to be presented with this dialog, check "require pass phrase" in FlowCrypt Settings -> Security, then after each try, restart the browser to make it forget the pass phrase again.

**Comment by tomholub** [comment]
I'm closing this as the other issue covers it.
