### ISSUE TITLE
When selecting all 'CMD+A' and pasting 'CMD+V' over selected content. Pasted content is 'appended' as opposed to 'overriding' selected content. 

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#771]
<img width="555" alt="screen shot 2017-05-14 at 12 06 17 pm" src="https://cloud.githubusercontent.com/assets/3431871/26035657/c4ffe3d4-389d-11e7-9121-c9b3ff94c57b.png">

**Comment by tomholub** [comment]
yeah this can get annoying

**Comment by tomholub** [comment]
will be fixed by #1861
