### ISSUE TITLE
Updating when a user clicks on "Settings" / "Send Secure Email" 

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#779]
<img width="1129" alt="a-draft" src="https://cloud.githubusercontent.com/assets/3431871/26535163/bfe869a0-43f8-11e7-99a6-c4f862c04f0e.png">

**Comment by mondo989** [comment]
Added another update here. The styling is now a bit better than previously. 

<img width="429" alt="screen shot 2018-10-18 at 2 01 47 am" src="https://user-images.githubusercontent.com/3431871/47143391-df0f5580-d279-11e8-8210-c46c825e7a43.png">

**Comment by tomholub** [comment]
A little bit of nostalgia seeing the old logo :) I'll close this, we can continue on the PR page
