### ISSUE TITLE
forward a standard message in encrypted form

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#787]
https://mail.google.com/mail/u/1/#inbox/15c5a05351928bba

**Comment by mondo989** [comment]
This would be sweet! 
Does the link you included just reference an email?

**Comment by tomholub** [comment]
Yeah I just keep a track of people who wanted this, so that I can email them back when it's done

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/1614d850fbcea367

**Comment by hopelab** [comment]
I am surprised there are such few folks who need this feature.  Our organization forwards a lot - for example, medical newsletters, emails from other folks with PGP keys, etc..  It would be great to get this feature added. Thank you!

**Comment by tomholub** [comment]
It could be under the three dots

![image](https://user-images.githubusercontent.com/6306961/65760210-10400900-e10c-11e9-9775-f65d7818b6a3.png)

**Comment by tomholub** [comment]
This would be relatively easy to implement, but it will only work on the very last message.

Implementing it for previous messages would not yet be easy at all.

**Comment by tomholub** [comment]
Marking it as actionable, will get potentially assigned to someone to implement.

**Comment by tomholub** [comment]
@hopelab This seems to be mostly working by now, due to other changes. You can click the green secure reply near the last message:
![image](https://user-images.githubusercontent.com/6306961/68017132-e7241280-fc8d-11e9-80d6-6e386892da50.png)

Once clicked, just remove the recipient in the reply box and put any recipient. It will act just like forwarding.

Thanks to https://github.com/FlowCrypt/flowcrypt-browser/issues/920 which is in works, you'll soon be able to do this with any non-encrypted message, not just the last.

I'll close this for now, please let me know if that will work for you.
