### ISSUE TITLE
add names to outgoing email, from: and to:

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#791]
Action steps:
1) When composing email, we load contacts from the database, along with their pubkey.
    - If the contact has a `.name` property that is truthy, then outgoing email headers should contain the name, for example: `To: Recipient name <their@email.com>`
    - If not truthy, continue doing what was done until now, eg: `To: their@email.com`.
2) Do same thing with the `From: ` header. Use `full_name` from local storage (but only if truthy - same thing applies - it may not be set, in which case continue to use previous behavior).

Related to #147, but this one is about mime headers. Users who want this: 
https://mail.google.com/mail/u/1/#inbox/15c6201c3bf60782
https://mail.google.com/mail/u/0/#inbox/FMfcgxvzLFDKgdhLrNKqmKlrJngWwBKj

**Comment by tomholub** [comment]
Radek will take a shot

**Comment by tomholub** [comment]
Hints:
- `extractProcessSendMsg` will probably have to be updated
  - In particular, `collectAllAvailablePublicKeys` should probably be renamed to `loadContacts` and just return `Contact[]` or something similar.

Which means that the signatures of almost all methods in `composers.ts` will have to change, and it's not obvious what's the best way to approach it. Maybe this is not an appropriate issue for a new contributor.

**Comment by tomholub** [comment]
@michael-volynets this is relatively involved, so you should ask when unsure

**Comment by michael-volynets** [comment]
> If the contact has a .name property that is truthy, then outgoing email headers should contain the name, for example: To: Recipient name <their@email.com>
If not truthy, continue doing what was done until now, eg: To: their@email.com.

Maybe I don't understand exactly but what do you mean by `truthy?
How can I check if the contact is truthy or not?

**Comment by michael-volynets** [comment]
Do you want me to add some RegEx to check if the name is correct?

**Comment by tomholub** [comment]
Checking for truthiness means you check if something evaluates to `true`.
```js
if(contact.name) {   // contact.name is truthy
  to = `${contact.name} <${contact.email}>`;
} else {
  to = contact.email;
}
```

**Comment by michael-volynets** [comment]
oh, okay, got it
I will remember that :)
