### ISSUE TITLE
UPGRADE button - didn't know/forgot it was an upgrade button

### ISSUE THREAD

**Issue by mondo989** [FlowCrypt/flowcrypt-browser#793]
<img width="529" alt="screen shot 2017-06-02 at 7 21 31 pm" src="https://cloud.githubusercontent.com/assets/3431871/26748099/bd2c1a12-47c8-11e7-916f-b15805b3c184.png">

I wonder if we can make the button a bit more compelling?
The upgrade button is competing with other content.

**Comment by tomholub** [comment]
I don't really expect people to click it there. It's mostly there for my
debugging out for someone who's really looking to find it.

I hope people would rather upgrade as a result of some action they need to
do. Eg I need to send a larger file -> need to upgrade.

I feel like making this button would feel unnecessarily pushy, and nobody
would use it much anyway.

**Comment by mondo989** [comment]
Ok, that's good to know.  
Although, if you aren't expecting people to click it there, and it's for debugging mainly, do we need to keep it there for the user? (I understand the value of it in regards to debugging.)

**Comment by mondo989** [comment]
**(Kind of thinking out loud)**
Instead of having the UPGRADE spelled out as a gray button, I wonder if we could use an icon? 

Or, somewhat like you already have it, but we get the user familiar with the meaning/terms: 
"Basic" / "Advanced" or
"Lite / Premium"

When trying to send an email with attachments, we can say something like.
"To send encrypted attachments, you will need the Advanced version."

(Showing the Basic vs Advanced checkmarks)

**Comment by tomholub** [comment]
can you show an example of that? Unable to visualize :)

**Comment by tomholub** [comment]
Marking as actionable, only to take a look to confirm upgrade button is still gray, and make it green to make it more visible like other buttons. If already green, close without code change.

**Comment by mondo989** [comment]
I've been noticing the 'Actionable,' on a few, might be some 'low hanging fruit' for me? :)

**Comment by tomholub** [comment]
We have onboarded two TypeScript devs and this was mostly for them, but you definitely could, if any of those are purely html/css issues :) This particular one can be closed, I have since noticed it's green.
