### ISSUE TITLE
pubkey import form should accept just the fingerprint

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#802]
Eg people may try to paste one of the following:

PGP: 62BF F048 0077 1341 FEB3 B75C 76DC B628 6C3A 87CA
62BF F048 0077 1341 FEB3 B75C 76DC B628 6C3A 87CA
PGP: 62BF F048 0077 1341 FEB3 B75C 76DC B628 6C3A 87CA
0x76dcb6286c3a87ca
0x62BFF04800771341FEB3B75C76DCB6286C3A87CA
76dcb6286c3a87ca
76DCB6286C3A87CA
0x76DCB6286C3A87CA

etc

show a few examples of what should be put in there

This especially affects people new to encryption, because other people just put fingerprints in their emails

**Comment by tomholub** [comment]
- For this use the lookup api eg `GET https://flowcrypt.com/attester/lookup/ADAC279C95093207`
- make sure to convert it to standard format eg 76DCB6286C3A87CA before getting `https://flowcrypt.com/attester/lookup/..` - although this API accepts all sorts of weird and spaced formats, soon it won't.

**Comment by tomholub** [comment]
The form in question is at FlowCrypt Settings -> Additional Settings -> Contacts -> import.

**Comment by tomholub** [comment]
claimed

**Comment by tomholub** [comment]
Available as an interview issue again because the solution above was rejected.

Please don't make the same mistake as the attempt above, which made unnecessary changes too deeply in the internals of the codebase without checking if it breaks any functionality.

The solution to this issue should be relatively simple and contained mostly within the contacts screen. You should be quite certain that what you do does not affect functionality elsewhere in the software.

**Comment by michael-volynets** [comment]
@tomholub Where can I get fingerprints to test it out?

**Comment by tomholub** [comment]
You can fing fingerprints in FlowCrypt Settings -> Additional Settings -> Contacts, where you click to view a public key and it will show fingerprint.

![image](https://user-images.githubusercontent.com/6306961/57703236-30849500-764f-11e9-99d5-38538251e420.png)

`0x76dcb6286c3a87ca` is a longid. On this case, it was created by lowercasing the fingerprint, trimming to last 16 characters, then prefixing `0x`.

As you can see I have listed many different formats of fingerprints and longids, because different software and different people format it differently.

Also please use a different endpoint: `https://flowcrypt.com/attester/pub/ADAC279C95093207` which accepts a properly formatted longid. `Attester.lookupLongid(longid);`

**Comment by tomholub** [comment]
All the examples I gave above refer to the same longid: `76DCB6286C3A87CA`

Api response: https://flowcrypt.com/attester/pub/76DCB6286C3A87CA

So in order to be able to accept all these formats, you will have to normalize them to become a standard formatted longid (16 characters). Here is some python code that does that, you can do something similar in JS:

```py
	def __normalize_longid(self, longid:str) -> str:
		longid = ''.join([c for c in longid.strip() if c not in ' :-'])
		if longid[0:2] == '0x':
			longid = longid[2:]
		longid = longid.upper()
		if len(longid) >= 16:
			longid = longid[-16:]
			if re.match('[A-F0-9]{16}', longid):
				return longid

```
Then you can use the normalized longid to request a pubkey from the api.

Let me know if this helps.

**Comment by michael-volynets** [comment]
Yes, it helps me, Thanks!

Maybe would be better to replace this textarea with input? Because we need to enter only 1-line

**Comment by tomholub** [comment]
The main usecase will remain to enter a public key. That's what most users do.

But some users unknowingly only enter a fingerprint or a longid instead of the whole key. So I would still leave the textbox large to accommodate pasted public keys, and add functionality to also be able to handle longids and fingerprints (by pulling the actual key from our server, based on the key id).

**Comment by michael-volynets** [comment]
Got it, thanks

**Comment by tomholub** [comment]
todo for me - I still want to update the wording and move `normalizeLongId`, so I'm not closing this yet

**Comment by michael-volynets** [comment]
> todo for me - I still want to update the wording and move `normalizeLongId`, so I'm not closing this yet

I can do it if you want

Just tell me how I should update wording and where can I move  `normalizeLongId`

**Comment by tomholub** [comment]
It's ok, I'm at it. Often times I'm not sure exactly how I want to update it until I see it in the ui. For example, I have already re-written it 3 times in the last 5 minutes, simply because once I see it, I have more ideas on how to improve it.

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/57791383-356b4680-772c-11e9-8529-54811667d934.png)
