### ISSUE TITLE
signed messages verification missing pubkey ui

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#811]
- attested keys should load automatically if not present, if the email is attasted for the same key as the one that signed the email
 - if not attested but same key, offer a button
 - if attested or not attested and it's a different key, show the mismatch & offer custom import

**Comment by tomholub** [comment]
should offer to download key https://mail.google.com/mail/u/1/#inbox/15ce838fc14f9c04

**Comment by mbwmbw1337** [comment]
When will this be released? Seeing the issue still.

**Comment by tomholub** [comment]
It's now available on Firefox. I'll go ahead and make it available on new Chrome installations. That means if you uninstall & reinstall a few hours from now, you'll get the update. Over the course of the next week, we'll slowly increase the rollout until it reaches everyone.

Version `6.8.8`

**Comment by mbwmbw1337** [comment]
> It's now available on Firefox. I'll go ahead and make it available on new Chrome installations. That means if you uninstall & reinstall a few hours from now, you'll get the update. Over the next week, we'll slowly increase the chrome rollout until it reaches everyone.
> 
> Version `6.8.8`

Thank you. I'll validate in a few hours. Surprisingly I had this pop up on a few emails recently and was about to submit a bug when I found your issue already opened. Thank you for resolving so quickly!

**Comment by tomholub** [comment]
For what it's worth, it's an issue from 2017

¯\_(ツ)_/¯
