### ISSUE TITLE
allow to change attestation w/o original key

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#815]

**Comment by warwickmm** [comment]
This feature would be nice to have.  I originally tested the extension by doing the following:

1.  For testing purposes, I allowed FlowCrypt to generate a keypair.  I then received the attestation email and was able to encrypt/decrypt emails.
2.  I then uninstalled FlowCrypt and reinstalled it as I now wanted to use my existing keypair.
3.  I pasted in my private key when prompted, and am able to successfully encrypt/decrypt emails as expected.

However, when I now go into Settings->Attestor, I see the message:

"Wrong public key recorded. Your incoming email may be unreadable when encrypted."

**Comment by tomholub** [comment]
does it show the `request re-attestation` button? If you still have the auto-generated key and pass phrase, you can use that to submit your new key instead

**Comment by warwickmm** [comment]
Unfortunately, I don't have the original auto-generated key anymore.  No
worries...I can understand why we wouldn't want to allow for key changes
without proper authentication.  For now, I can exchange my public key to
others the old fashioned way.

**Comment by JetseBrouwer** [comment]
This would be a very usefull function! I did the exact same thing as @warwickmm did. I don't have the original passphrase anymore (I simply forgot it) so now my record is the public key of an orphaned key-pair, and i can't change it.

**Comment by tomholub** [comment]
Endpoint ready for this: https://flowcrypt.com/attester/update-public-keys

(if someone ends up here due to a google search, you can use the link above manually to replace your public key records)

**Comment by Juanlu001** [comment]
Worked like a charm! Thanks a lot <3

**Comment by tomholub** [comment]
#1661
