### ISSUE TITLE
display attachments in browser if image, pdf or text

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#85]

**Comment by mondo989** [comment]
Are we thinking showing different icons for each one?

**Comment by mondo989** [comment]
Also, can you trim the file name a bit (if it reaches a certain amount of characters), and I can place the icons to the left of it.

<img width="566" alt="screen shot 2016-03-22 at 6 41 44 pm" src="https://cloud.githubusercontent.com/assets/3431871/13971371/bfb7f206-f05d-11e5-9100-f0d1b02fe30d.png">

It would look something like this. (but icons cleaner)
<img width="762" alt="screen shot 2016-03-22 at 6 49 58 pm" src="https://cloud.githubusercontent.com/assets/3431871/13971526/e6574212-f05e-11e5-90bd-a367c9e23b56.png">

**Comment by mondo989** [comment]
The icons are crappy screenshots, I would use SVG's it would appear much better.

**Comment by tomholub** [comment]
I actually meant that if you click on attachment you receive, you would see the actual image in the browser (instead of downloading it). So it will be kind of like a lightbox with that image, and a download button. similar for pdf and text.

These icons, for now, I'd put them on the receiving side, also on the left of the text

pdf
image
text
word + similar
excel + similar
unknown

maybe best just find a library of them, because there might be more coming later (too much work). 

Putting it on the receiving side would be a bit harder

**Comment by mondo989** [comment]
Ah, got ya. Way different then lol.
The lightbox would be a cool idea.

Unless you know of a different/alternative one, The icons I would use would probably come from  flaticon.com.

**Comment by tomholub** [comment]
yes something like that, that's what I thought!

**Comment by mondo989** [comment]
Ok so here are two options.

<img width="1107" alt="screen shot 2016-03-23 at 1 56 10 pm" src="https://cloud.githubusercontent.com/assets/3431871/14000722/b8bcab2a-f0ff-11e5-820f-031c73f0b8d0.png">
<img width="946" alt="screen shot 2016-03-23 at 2 00 42 pm" src="https://cloud.githubusercontent.com/assets/3431871/14000723/b8bdbb00-f0ff-11e5-9136-dec88934d913.png">

**Comment by tomholub** [comment]
Would something like this work? In order to make the icon the most readable (I was thinking, unless we modify the icons, the "PNG" on the left would end up being too small to read).

Optionally, we could later add CryptUP logo somewhere to signify "ecnrytpion".

![image](https://cloud.githubusercontent.com/assets/6306961/14009768/2e089252-f1ca-11e5-9ad5-97920b4983ad.png)

I kind of like these two packs 
http://www.flaticon.com/packs/file-formats-styled
http://www.flaticon.com/packs/file-formats-icons

Because both tend to show by imaging what is the content (eg PNG shows image icon, etc).

**Comment by tomholub** [comment]
By the way if you prefer your second version over my first, then use that one, I think both will work well.

**Comment by mondo989** [comment]
You know I kind of like yours better.

**Comment by tomholub** [comment]
the hover is very nicely done! overall it's nice, I'll make issue for myself to finish this

**Comment by tomholub** [comment]
looks good, can you just put all of the icons on git with original names, and if I can recognize the attachment filename to be the same as the icon name, I can use the icon automatically without having to specify one by one

for the ones you uploaded, I already connected them one by one

**Comment by mondo989** [comment]
Added the rest of the files in folder, there are a few.

**Comment by mondo989** [comment]
I believe we've completed this a while back

**Comment by tomholub** [comment]
actually the original issue was about displaying the contents of attachment in browser, which I haven't done so I'll keep it open for now

**Comment by tomholub** [comment]
like, to actually show the image in a lightbox

**Comment by mondo989** [comment]
Got ya.

**Comment by tomholub** [comment]
We could consider this.. with a modal :)

For now only images and text. Do you think this is realistic?

**Comment by tomholub** [comment]
The actual display may involve the inner frame making a call to the content script, which would have to create an overlay frame.. and display it there. It won't be that easy, unless we implement it as a window popup, which may be much simpler... needs some thought.

**Comment by limonte** [comment]
The oldest (4 yo!) issue is resolved! :tada: :tada: :tada:
