### ISSUE TITLE
quote previous message / reply

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#873]
#1621

https://mail.google.com/mail/u/1/#inbox/15d12319eadac1f4
relies on #92

**Comment by tomholub** [comment]
https://mail.google.com/mail/u/1/#sent/15f07b45ccf9ca34

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/1606516537801891

**Comment by tomholub** [comment]
@michael-volynets You can do similar thing that we do for replies, with a little more standard intro line:

- Html content should be converted to text before being included in the quoted part
- hen quoted with `On 2019-02-20 at 19:48 someone@hello.com wrote:`
- and `>` on each line below

**Comment by tomholub** [comment]
Also, you should probably reuse the UX from quoted messages (`pgp_block`) on the bottom of the reply window as well, to mimic what Gmail is doing:

![image](https://user-images.githubusercontent.com/6306961/60113600-a9ecc880-9761-11e9-84ec-1a8148e84361.png)

Clicking it will make it go away, and then I see the quoted content which I can remove or edit if I want.

**Comment by michael-volynets** [comment]
just to make sure,
If I correctly understood, I need to add 3 dots to the bottom of the reply box and after clicking on it, it should show previous message (with header line you wrote and ) that can be edited? (Like Gmail does)

**Comment by michael-volynets** [comment]
@tomholub I should let you know that this issue will take more time than I expected.
Because I need to handle replied messages along with drafts. 
For Example, if I clicked reply button then the draft shouldn't be saved immediately, it should be saved only when I clicked on those 3 dots or typed something, and it should be saved along with the quoted replied message in the end. 
Then when I opened a draft again, I need to check if there is a replied part, if yes - I need to hide it and show 3 dots.
There also can be a case, when I have a draft but there isn't replied part (I just removed it), in this case, I don't need to show 3 dots.
Or when the replied message has no text (e.g. it has attachments only)
I hope you understood what I mean.

I tested how Gmail does it. and basically, I understand what I should do that.

This really interesting task, thanks for assigning :)

**Comment by michael-volynets** [comment]
But I think there is another easier way, is to do this similar to forwarding messages (without hiding). 
When the user clicks reply then the replyed message is immediately appended in quoted text with header line to the reply window. (without 3 dots).

This way will be easier and faster but without hiding replied content. 
I think the first way (with hiding) is better for UX but it can take much more time than without hiding.
I don't know if this's worth it. What do you think about it?

**Comment by tomholub** [comment]
> just to make sure,
> If I correctly understood, I need to add 3 dots to the bottom of the reply box and after clicking on it, it should show previous message (with header line you wrote) that can be edited? (Like Gmail does)

This sounds correct

**Comment by tomholub** [comment]
> For Example, if I clicked reply button then the draft shouldn't be saved immediately, it should be saved only when I clicked on those 3 dots or typed something

Didn't think about this. Yes, sounds correct.

> and it should be saved along with the quoted replied message in the end.

correct

> Then when I opened a draft again, I need to check if there is a replied part, if yes - I need to hide it and show 3 dots.

correct

> There also can be a case, when I have a draft but there isn't replied part (I just removed it)

The logic for all of these is the same. You parse the message with the same logic that you used in `pgp_block.ts` (you can move the logic to a common file). You just run it through the parser, and it spits out two parts. You render the first, you check if quote exists, and you render that or not.

> Or when the replied message has no text (e.g. it has attachments only)
> I hope you understood what I mean.

We don't store attachments in drafts yet anyway

> I tested how Gmail does it. and basically, I understand what I have to do.

That's often a good idea :)

**Comment by tomholub** [comment]
> But I think there is another easier way, is to do this similar to forwarding messages (without hiding).
> When the user clicks reply then the replyed message is immediately appended in quoted text with header line to the reply window. (without 3 dots).
> 
> This way will be easier and faster but without hiding replied content.
> I think the first way (with hiding) is better for UX but it can take much more time than without hiding.
> I don't know if this's worth it. What do you think about it?

It would be easier, and I really like that you proposed a simpler solution, because 90% of the time I'd be super happy to go the simple route. I hope I hear about more "simple fixes" in the future :)

In this particular case, I'd just find the quoted text disturbing. I already see the text above. Now I see it below. As a user, I feel like removing it just because it blocks my view. I feel like it would have a negative effect on the user. I have no way to back that feeling, other than imagining that I'd be annoyed by it.

You can start out with the simpler version, have it reviewed, and then slowly add complexity from there. But I think I would not merge it until it starts out hidden.

**Comment by michael-volynets** [comment]
Okay, great! 
Thanks!

**Comment by michael-volynets** [comment]
Is there a method to find out whether a string is encryptedMessage or not?
I found a `Mime.process`, it returns the object with `MsgBlock` property and `MsgBlock` has a `type` property through which I can know the message is encrypted or not. But perhaps there is a function that returns  just 'true' or 'false'

**Comment by michael-volynets** [comment]
Also, I pushed some code to the branch (https://github.com/FlowCrypt/flowcrypt-browser/tree/issue-873-quote-previous-reply) for review. Please review it because I think there will be much more code when I've finished whole the task and it can be harder to review.

Now it appends the previous message to reply box.

**Comment by tomholub** [comment]
> rough which I can know the message is encrypted or not. But perhaps there is a function that returns just 'true' or 'false'
> 
> If not, can I create a function that just checks if the string includes `-----BEGIN PGP MESSAGE-----`, if it does then I can try to decode it.

For the purposes of parsing our own drafts, you can look for `-----BEGIN PGP MESSAGE-----`.

**Comment by tomholub** [comment]
Sorry, just realized you're not pulling drafts but previous emails.

I understand your goal is to grab the message content, either plain or decrypted, to add to the quote. It's more complicated than you'd thought, because there is 1000 different formats a message can be in depending on the software that sent it (I probably spent a year adding compatibility to most of these).

The message can be binary, it can be encrypted inside attachment, directly in body, can be armored, etc, so just checking for string presence won't do it.

I'll write it up.

**Comment by tomholub** [comment]
I made a PR with comments: https://github.com/FlowCrypt/flowcrypt-browser/pull/1791#pullrequestreview-256724420
