### ISSUE TITLE
offer to search contacts with Google api

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#879]
#1621

ref https://mail.google.com/mail/u/0/#inbox/160add19970fd443

**Comment by tomholub** [comment]
On enterprise builds, this permission should be included during setup.

**Comment by tomholub** [comment]
Currently, we search contacts on our local database + based on sent email.

Searching based on sent email is good because we don't have to ask for another permission (contacts). But it's also bad because the results are imperfect. Often times, users are not able to find the contacts they are looking for, and they are writing me about this all the time.

Google has some APIs for this:
https://developers.google.com/contacts/v3/ - the older XML version
https://developers.google.com/people - similar JSON API

Scope:
https://www.googleapis.com/auth/contacts.readonly - it looks like it's not a restricted scope

The functionality should be as follows, depending if user has added the contacts oauth scope or not (which will NOT be added by default during setup for consumer builds, so that we don't scare users):

#### Default behavior (when app does not have contacts read scope enabled)

1) search in local contacts like today
2) search in sent gmail like today
3) render results
4) on the bottom rendered results, show `Enable Google Contact Search` (clickable)

When user clicks it, `authPopup` will show up where there should also be contacts permission included. User should go through the popup, similar to when we handle `authPopupNeeded`, except this time there should also be the contacts permission.

Once done, the app should be able to check if we have contacts permission from storage (similar to canReadEmails or whatever we called the email read permission).

If there is this permission, it will behave like described below.

#### Google contact search enabled - behavior

1) search in local contacts like today
2) search contacts from Google API
3) render results

**Comment by michael-volynets** [comment]
Okay, everything described pretty well, Thanks,

I've got one question below:

When I search for contacts from Google API and there are some contacts that have PGP installed I think it would be great to render them with green lock and etc.. So maybe when I fetch  contacts from Gmail  then I need to find out which of them have PGP installed through our Attester and then I add all of the fetched contacts into Local DB.

What do you think about it?

**Comment by tomholub** [comment]
That sounds like a good idea. Let's add that in a separate PR, to make it easier for me to review.

**Comment by michael-volynets** [comment]
So, in the PR for this issue, I just load contacts and doesn't matter whether they have PGP or not, I will render them with gray color, yes?

**Comment by tomholub** [comment]
Yes, just like we do today. But remember that we are rendering results from from the DB as well (always search local db first).

The ones from local db may show as green, with contacts from the external api, which will for now always show as gray EXCEPT when we already have that contact in the db and it's known to have a public key - then it will be green.

**Comment by tomholub** [comment]
I edited the comment above for clarity

**Comment by michael-volynets** [comment]
Okay, got it, looks really interesting 

Thanks,
