### ISSUE TITLE
Error when replying in Inbox if "sign and send" is chosen

### ISSUE THREAD

**Issue by RamonBeast** [FlowCrypt/flowcrypt-browser#910]
I'm noticing an odd behavior in Inbox: if a message is received and the sender signed it (without encrypting) the reply button automatically sets the reply to "Encrypt and Send". It is thus necessary to click on the pen button in order to just sign, but upon sending two things happen:

1) The following box appears (and nothing happens if the browser is restarted)

![image](https://user-images.githubusercontent.com/10730701/30123033-f0160236-9330-11e7-8011-73d7510bfd6f.png)

2) The toolbar buttons in the lower right hand side stop working

**Comment by tomholub** [comment]
deprecating inbox following google's move.. sorry
