### ISSUE TITLE
reply type based on message type: sign -> sign, encrypt -> encrypt

### ISSUE THREAD

**Issue by RamonBeast** [FlowCrypt/flowcrypt-browser#911]
When replying to a signed message, by default the "encrypt and send" option is selected, in any case it's not possible (at least in Inbox, correct me if I'm wrong) to reply without signature to a signed message, the outcome is that if a message is addressed to multiple people and only one signs it, everyone using cryptup is forced to add his signature too. I think that this pattern is not entirely correct, I would like to propose a new one:

1) If the message is encrypted the reply button could show the following options in order: reply encrypted, sign and send, reply in clear (this last option can be omitted if too dangerous)

2) If the message is signed: sign and send, reply encrypted, reply in clear (in this case the last option doesn't present any danger)

3) If the message is in clear: no action is taken since cryptup doesn't activate

I think this pattern might work better than the current one, in any case I believe that it should be possible for the user to without signature to a signed message.

**Comment by tomholub** [comment]
I agree, we'll improve it. Thanks for your input.

**Comment by RamonBeast** [comment]
Thank you Tom for your amazing work and always swift response.

**Comment by tomholub** [comment]
I don't know what's a good way to implement this. @michael-volynets you can take a look, maybe you'll have an idea.

**Comment by tomholub** [comment]
However, I only want to implement a simplified version:

If last incoming message was signed, by default when rendering reply box, click the "sign" button for the user. If last incoming message was encrypted, leave as is (default encrypted).
