### ISSUE TITLE
hide quoted responses

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#92]
#1621

Today we don't quote previous responses because Gmail shows a conversation anyway, so we only need to render one message at a time, without any quoted text.

This however becomes a problem when someone is added to a convo half-way, because they have no context (no previous messages), only the latest reply.

I would be good to start quoting the previous message, which is tracked in #873. But before we do that, we have to have a mechanism to hide such quoted content when rendering a message. Eg:

```
this is my reply

> some other
> quoted text
>
> > gets very
> > 
> > > messy
> > > like that
```
Should become:
```
this is my reply

[...]
```

1) only lines at the bottom of the email are eligible to hide (starting with `> `)
2) should be replaced similar to what Gmail does, with a `...` button. The button color should probably use standard FlowCrypt green bg, with white text
3) clicking it will show the whole quoted text, including the `> ` on each line
4) Remember to resize the iframe after showing the quoted part

This work will likely be done somewhere in `elements/pgp_block.ts`

**Comment by tomholub** [comment]
https://mail.google.com/mail/u/1/#inbox/15d12319eadac1f4

**Comment by tomholub** [comment]
1) only lines at the bottom of the email are eligible to hide (starting with `> `)
2) should be replaced similar to what Gmail does, with a `...` button. The button color should probably use standard FlowCrypt green bg, with white text
3) clicking it will show the whole quoted text, including the `> ` on each line
4) Remember to resize the iframe after showing the quoted part
5) Ideally test your solution on large messages, messages with `<img src="base64, ...">` that contain a 1MB image and stuff like that. It should not make my browser cry.

This work will likely be done somewhere in `elements/pgp_block.ts`

**Comment by tomholub** [comment]
Additionally (outside of scope for this PR) we should test the solution on large messages, messages with `<img src="base64, ...">` that contain a 1MB image and stuff like that, else we risk bricking people's browsers on a slow regex or whatnot.

**Comment by tomholub** [comment]
forgot to note, claimed

**Comment by tomholub** [comment]
Available for interviews again.

**Comment by michael-volynets** [comment]
I finished this issue but I have a question,

> Additionally (outside of scope for this PR) we should test the solution on large messages, messages with base64 that contain a 1MB image and stuff like that, else we risk bricking people's browsers on a slow regex or whatnot.

How can I test it? Because I haven't found the way to add the base64 image to the encrypted message

I also made a pull request only for Code-review. **Don't merge it** before I haven't checked the solution on large messages.

**Comment by tomholub** [comment]
Try this one (compatibility account)
https://mail.google.com/mail/u/2/#label/fix%2Fwip

I'm not sure it's a base64 image, but it's a larger message either way. Take a look (and let me know).

**Comment by tomholub** [comment]
This one is also a PGP/MIME (+ html), which could possibly use slightly different mechanism code path than a textual email.

For HTML messages, I would suggest using `Xss.htmlSanitizeAndStripAllTags` for the html case. Using this, you can convert the previous html message into a textual content that you can treat as if the original message was just text.
