### ISSUE TITLE
Reply in conversation to not last element

### ISSUE THREAD

**Issue by axkibe** [FlowCrypt/flowcrypt-browser#920]
Am I doing something wrong or is it missing. I cannot reply to a conversation that is not the last message. In "original" view, I have a reply button on every message, but in crypt-view I only can reply to the last message of conversation.

**Comment by tomholub** [comment]
For now, that's indeed a limitation. The thing is, CryptUp doesn't really quote the message contents anyway, so in a conversation, even if you were allowed to reply to a middle message, the recipient would probably not see a difference (as long as they are using conversation view).

Once we start quoting messages, then it will make sense to allow this.

**Comment by axkibe** [comment]
Well I had to copy/paste the email adresses by hand, since the last reply I got was a personal reply to a conversation that included a bunch of people.

I don't know if each just quoting or other email headers involved, my reply that should go to the group should have nothing to do with the personal reply I received.

PS: This is also something that didn't work, dragging the emails into the new composition field. Or to copy/paste the email boxes, I had to expant them and manually copy/paste each email address.

**Comment by tomholub** [comment]
There are email headers involved, at this moment we're always referring to the last message in conversation as you'd expect.

**Comment by tomholub** [comment]
depends on https://github.com/FlowCrypt/flowcrypt-browser/issues/873 which in turns depends on https://github.com/FlowCrypt/flowcrypt-browser/issues/92

**Comment by tomholub** [comment]
Marking actionable, third priority - the blocking issues have been fixed.

Have to re-work the logic to know which exact message we are replying to, instead of always assuming it's the last message in conversation.
