### ISSUE TITLE
PGP/Mime - detached signatures

### ISSUE THREAD

**Issue by axkibe** [FlowCrypt/flowcrypt-browser#921]
I recently got a complaint that one receiver of my signed message (signed only not encrypted) was confused by all the Mumbo Jumbo.

So I guess FlowCrypt uses Inline PGP as default? Can I change this somewhere to do PGP/MIME instead?

**Comment by tomholub** [comment]
We're planning detached signatures. I don't see an issue for it on github though, so I'll keep this open.

**Comment by spudlyo** [comment]
Howdy, another user here would like to see a PGP/MIME option, as well as the ability to encrypt + sign.

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/163c9ff17887f205

**Comment by tomholub** [comment]
One more request: Outlook seems to be able to verify PGP mail from https://mailfence.com/en/ but not from FlowCrypt. Maybe Mailfence uses PGP/MIME.

https://mail.google.com/mail/u/0/#inbox/FMfcgxvzLXJjkgkQPlLdNPjpXTKrZFdF

**Comment by hoclun-rigsep** [comment]
This issue should be considered critical. The project is about promoting an open standard, but it doesn't interact in compliant way with other MUAs.

**Comment by tomholub** [comment]
This has been implemented - but it requires you to switch it manually. See this screenshot:

![image](https://user-images.githubusercontent.com/6306961/83646946-d7fa9f80-a5a3-11ea-8594-ba63245a8655.png)

**Comment by hoclun-rigsep** [comment]
I appreciate the work of implementing this.

It's not I who would have to switch though; it's my normie correspondents, whom I've been steering to FlowCrypt. Is there a plan for making this the default?

**Comment by tomholub** [comment]
Yes, we definitely want to make this the default. There were some problems with Gmail modifying message format in transit, which affected encrypted messages. I believe it didn't affect signed ones. This issue is a bit more involved due to these external factors then it seems, but the goal is to eventually make it the default.

**Comment by hoclun-rigsep** [comment]
Great. This is important work and you have my thanks. I'll encourage my correspondents to activate the option and report any difficulties.

**Comment by seisvelas** [comment]
In Firefox this appears as expected:

![Screenshot_2020-08-17_19-27-26](https://user-images.githubusercontent.com/44826516/92788645-bf064500-f36f-11ea-9453-e8c02247570a.png)

However, when I do the same thing with Chrome, it doesn't appear:

![Screenshot_2020-09-10_14-14-48](https://user-images.githubusercontent.com/44826516/92788953-02f94a00-f370-11ea-8c78-2e1fcccedfbf.png)

Is there something additional that needs to be done for the option to appear in Chrome?

Ref: https://mail.google.com/mail/u/1/#inbox/FMfcgxwJXLmlLTrbmXgLNrDCBnHmRLCM
