### ISSUE TITLE
rename to FlowCrypt

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#922]
- [x] name of plugin
- [x] folder path
- [x] gmail notification
- [x] send welcome message from human@flowcrypt.com
- [x] submit pubkey for human@flowcrypt.com
- [x] add send-from address human@flowcrypt.com
- [x] rename "developer contact"
- [x] rename oauth app on google
- [x] rename stripe cc note

**Comment by tomholub** [comment]
rename "developer contact"

**Comment by tomholub** [comment]
raname oauth app on google

**Comment by tomholub** [comment]
It will only allow us to do a redirect of https://github.com/CryptUp -> https://github.com/FlowCrypt if FlowCrypt was empty, but we have been using FlowCrypt for a while for our Android app.

Individual repos get redirected. Go to https://github.com/CryptUp/cryptup-browser/ and see yourself.

**Comment by Jogai** [comment]
Yeah, I checked. But at first I got really anxious since this could lead to serious problems. Its not unprecedented: http://chrispederick.com/blog/web-developer-for-chrome-compromised/

**Comment by tomholub** [comment]
They would have to take over our extension as well as github account. We have 2FA on both.

**Comment by tomholub** [comment]
Thanks for feedback, hopefully we don't need to rename it a second tome :)
cheers
