### ISSUE TITLE
test and fix? compatibility with Canary Mail

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#936]
https://mail.google.com/mail/u/1/#inbox/15ea347abf34c4a8

```
Error: Error decrypting message: Compression algorithm BZip2 [BZ2] is not implemented.
```

**Comment by ismail** [comment]
Any news on this?

**Comment by tomholub** [comment]
I'm hoping we will land a fix in 1-2 months.

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/1638807c0e381bfb

**Comment by tomholub** [comment]
there is probably a broken sample in flowcrypt.compatibilty to work with

**Comment by tomholub** [comment]
Please find a canary test email in `flowcrypt.compatibility` account - I believe this should be fixed in OpenPGP.js v4.

**Comment by tomholub** [comment]
Decrypting Canary Email works well
