### ISSUE TITLE
new message draft will not display when missing pass phrase

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#938]
0) set session only pass phrase in FlowCrypt Setting-> Security -> Require pass phrase to open email
1) new message -> draft -> close
2) restart browser
3) open draft - empty

**Comment by tomholub** [comment]
please try to repro / else fix or close

**Comment by michael-volynets** [comment]
When I'm on step 3 I see the button to open modal window to enter the passphrase.
We can close this issue.

But actually, I think would be better if the passphrase modal window shows immediately when you have opened the draft (without clicking on the button to open that modal window). 
How do you think?

**Comment by tomholub** [comment]
It's a good idea and I considered it before. But I'm afraid users will complain. Imagine you are using your `next` and `previous` button in gmail:
![image](https://user-images.githubusercontent.com/6306961/56147057-0465ed80-5f97-11e9-9c5d-e07ca728d75c.png)
You click next, next, next, then boom! Cannot click next anymore, because you are presented with a modal.

At the very least we would have to add functionality to close the modal when you hit Escape and also when you click away from it. But even then, I'm not 100% sure I won't get angry emails :)

One of the many complaints we get is that the software is too invasive / interfering with people's workflow.

**Comment by tomholub** [comment]
Another solution may be to replace the message with the pass phrase modal. But in that case, what if someone sends an email that looks like the modal? Maybe someone clicks on it, it takes them to another website that looks like gmail and they enter their pass phrase. Now that would be a vulnerability, so that's why I'm making the prompt distinctively pop up, which cannot be replicated inside malicious html email.
