### ISSUE TITLE
"this is my pubkey" email template hijacks other open tabs

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-browser#946]
I found one bug. 
How to reproduce: 

1. Need to open two (or more) different tubs in Chrome for different accounts.
2. I have a message in Account#1

![image](https://user-images.githubusercontent.com/2863246/32484081-4ca4f592-c3a7-11e7-97d8-bd8b752b4307.png)
3. I have a message in Account#2
![image](https://user-images.githubusercontent.com/2863246/32484223-b436485a-c3a7-11e7-8b6a-837b929e4c30.png)
4. When I clicked on the button "I don't have any other key" I received next results on both tabs (different accounts: Account#1 and  Account#2).

![image](https://user-images.githubusercontent.com/2863246/32484368-31a28c04-c3a8-11e7-9610-807610b29b9f.png)

###############################################################################

![image](https://user-images.githubusercontent.com/2863246/32484387-43d3f2a0-c3a8-11e7-9f4d-b59f752e2a7e.png)

**Comment by tomholub** [comment]
Haha that's a good one. Thanks!

**Comment by tomholub** [comment]
This may be a bit tricky, you may want to consult how to alleviate this with @tomholub. Maybe you have an idea in mind, please discuss before you invest too much time in it

**Comment by michael-volynets** [comment]
Hi @tomholub 

Seems like that the issue isn't actionable now, I tried to reproduce the same way but I can't see this result.

Here I've attached the video how I was reproducing this. Can you please check if I was reproducing it correctly or not.

https://drive.google.com/file/d/1W1-6QTAJKlxqBD2FHsb5lo_elP3LmURi/view?ts=5d02639b

Also, I see the attachments in the reply composer are shown in the bottom incorrectly. I will create another issue to fix it.

**Comment by tomholub** [comment]
Looks good, thanks for testing! Must have gotten fixed as a side effect of some other development.
