### ISSUE TITLE
Chrome: "secure reply" breaks position of search bar

### ISSUE THREAD

**Issue by sebastianbauer** [FlowCrypt/flowcrypt-browser#968]
Using Chrome, clicking the "secure reply" button breaks the position of the search bar. Clicking twice will move the bar even further. See screenshot.

![flowcryptgmail](https://user-images.githubusercontent.com/1159817/33527432-3ce3581a-d851-11e7-9f6e-1dbcd8c36131.png)

**Comment by tomholub** [comment]
1) Could you make a video? I can't quite visualize how would that happen. 
2) Which version of chrome are you running?

**Comment by sebastianbauer** [comment]
Seems to work not on the first time clicking the reply button. Also seems you must wait the reply dialog loaded completely and close it.

![flowcryptgmail](https://user-images.githubusercontent.com/1159817/33528897-faa4d3da-d868-11e7-9346-fa1c63c15316.gif)

**Comment by tomholub** [comment]
Interesting! On my device it will also jump up, but barely a pixel or two. If I continue the cycle 10-20 times, it will produce a similar result to what is happening on the screen shot. I'll look into it.

**Comment by tomholub** [comment]
Can't reproduce this anymore.
