### ISSUE TITLE
Facebook encrypted messages improperly display Cyrillic and Chinese

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#981]
@DenBond7 can you please create a Facebook account registered for email flowcrypt.compatibility@gmail.com 
 - please make sure it's registered in Russian or Ukrainian language
 - please set up that it will send PGP encrypted notification in Facebook settings
 - see if the received messages are readable in FlowCrypt Browser
 - check on android too

Russian and Chinese speaking users were reporting issues with facebook specifically:

![flowcrypt](https://user-images.githubusercontent.com/6306961/34641187-386fb346-f33b-11e7-8766-42d1e80d7534.png)

This will allow me to debug it. Thanks!

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#inbox/160c9d4228eacc61

**Comment by DenBond7** [comment]
I have received the next result:
![image](https://user-images.githubusercontent.com/2863246/34663526-f80f60b4-f45f-11e7-981d-e0dd6fd3d08f.png)

**Comment by tomholub** [comment]
Can you also try Russian instead of Ukrainian? In case. Not sure why it
didn't work for some.

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/34665022-7448aa3a-f467-11e7-8f28-b8df125f7e4e.png)

**Comment by tomholub** [comment]
Looks ok. Thanks!

This is on Windows, right? Widows 10?

Is your system language English, Russian or Ukrainian?


On Jan 8, 2018 10:31, "Den" <notifications@github.com> wrote:

[image: image]
<https://user-images.githubusercontent.com/2863246/34665022-7448aa3a-f467-11e7-8f28-b8df125f7e4e.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FlowCrypt/flowcrypt-browser/issues/981#issuecomment-355917982>,
or mute the thread

**Comment by DenBond7** [comment]
> This is on Windows, right? Widows 10?

Widows 7, x64

> Is your system language English, Russian or Ukrainian?

Russian

**Comment by tomholub** [comment]
closed as #1008, thanks for help! Facebook started sending garbled messages after a while, so I was able to fix it.
