### ISSUE TITLE
FlowCrypt vulnerable to ClickJacking via iFrame loading

### ISSUE THREAD

**Issue by justinamcafee** [FlowCrypt/flowcrypt-browser#987]
While attempting to create an embedded secure contact page for my clients ( http://www.justinmcafee.com/p/blog-page.html ) I realized that iframe were enabled under the flowcrypt website. 

Current ClickJacking techniques could be easily employed against users who might embed the FlowCrypt secure contact page. ( https://mteor.github.io/0x1_ClickJacking/ )

Solution: You can use the X-Frame-Options Header or the directive frame-ancestors from the Content-Security-Policy HTTP Header to deny rendering your service in an iframe or even scope which domains do you allow to frame your service. ( https://www.owasp.org/index.php/Clickjacking_Defense_Cheat_Sheet ) 

Alternatively, block iframes AND provide an "Embed this Page" code block on the secure contact page, to incentivize against iframe usage.

**Comment by tomholub** [comment]
We could disallow iframe usage, but I don't see how that provides any security benefits.

If the attacker can render an iframe on their webpage, they may as well render a complete mock-up of our encrypted page that interacts the same way. How would that be any different? It's their page, they have control over it, it doesn't make any difference if our iframe can or cannot be placed there.

Please let me know if I'm understanding this wrong.
