### ISSUE TITLE
button to export email content as pdf (print/for printing)

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#992]
ref https://mail.google.com/mail/u/0/#inbox/1616a7dd632ac39d

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/0/#sent/161e88fef23ce300

**Comment by seisvelas** [comment]
Another user requesting this: https://mail.google.com/mail/u/1/#inbox/FMfcgxwJXVGtMNTQCFZRlsKxZDcQKGbX

**Comment by tomholub** [comment]
If it's purely for aprint button, I imagine we don't need to convert to PDF first. I imagine we could just invoke browser print functionality to print out the contents of the frame as is, maybe with some added header (from, to, subject). That means the browser would be printing the html of the frame, not a version that we converted to PDF.

It may be simpler that way, if it works. But either way, this functionality would be for year 2021 or maybe even 2022.

**Comment by seisvelas** [comment]
Ref: https://mail.google.com/mail/u/1/#inbox/FMfcgxwJXpSDFdgsQVJVpwTbgtHXDhhN

**Comment by tomholub** [comment]
An important customer showed their interest in this. Please have a look. The easiest would be to place the print button inside of the green secure frame, I suppose, so you don't need to communicate between frames to print it.

**Comment by ioanmo226** [comment]
I see. By the way, I can't access above emails

**Comment by tomholub** [comment]
In this case, they just contain emails like "hello, it would be nice to have a print functionality". thanks for checking

**Comment by tomholub** [comment]
Our customer reported it as follows:

> Browser extension printing issue.
> If you try to print an encrypted email message, then the browser will
> pop up a new windows and display the unencrypted message.

I don't think we can easily/reliably prevent that, but giving the user another print button may help.

**Comment by ioanmo226** [comment]
![captures_chrome-capture-2022-7-10](https://user-images.githubusercontent.com/77344191/183921735-9c061897-1d2f-42fd-bbbf-64fdbbb5d0b8.png)

**Comment by tomholub** [comment]
I suppose, at least that would be the easiest first implementation. In top right corner. Then we could refine it some other time.
