### ISSUE TITLE
investigate missing gmail message id

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-browser#996]
```
acarrel-certificat-cabincetcarrel.asc
acarrel-certificat-inovalex.asc
Clef publique Vincent Baudouin Inovalex.asc
```

maybe investigate any small .asc file?

ref https://mail.google.com/mail/u/0/#sent/16157c5612b54ba2

**Comment by tomholub** [comment]
This may now work properly, but needs to be tested.

Repro: create three files with the names above, and put an armored pubkey into each. Just plain text files. Send them to flowcrypt.compatibility@gmail.com attached in standard non-encrypted email, one per email.

See if FlowCrypt picks up on the files and renders the import pubkey UI.

If all rendered well, please close. If some are ignored, consult @tomholub on how to proceed.

**Comment by michael-volynets** [comment]
In general, it renders well but sometimes I see "Unknown Message Id" error or there isn't attachment block in the message.
I tried to investigate that but I haven't found the reason for that behavior. 
See the attachments:
![image](https://user-images.githubusercontent.com/49104848/56213256-5cb6f100-6064-11e9-93b4-1ebadfed9ecc.png)

**Comment by tomholub** [comment]
Normally, the content script will try to figure out which Gmail message id are you viewing. Based on that, it can pull the message attachments from the Gmail API, investigate the attachments, and determine if they should be treated as public keys, or an encrypted message, encrypted attachment, plain attachment, ...

It's not always needed to check the API. But sometimes it is. If I send you a file named `something.asc`, it's hard to say if it's just a plain text file, pubkey, encrypted file or a message.

We parse message ID from the dom (google provides it in Gmail dom). Looks like in some situations it will fail, which would be definitely good to investigate!

**Comment by michael-volynets** [comment]
Do you know why there is this comment?
`  private determineMsgId = (innerMsgEl: HTMLElement | JQueryEl) => { // todo - test and use data-message-id with Gmail API once available
    return $(innerMsgEl).parents(this.sel.msgOuter).attr('data-legacy-message-id') || '';
  }`

Sometimes It cannot find data "data-legacy-message-id" but there is always ''data-message-id".
Can I replace them? (data-legacy-message-id -> data-message-id)

**Comment by tomholub** [comment]
Gmail is moving away from the legacy id format and into the new id format since last year.

The problem was, last time I checked, the Gmail API was still returning the old (legacy) format, so I couldn't make the switch without side effects.

Example api response:\
https://www.googleapis.com/gmail/v1/users/me/messages/16a260bfcfb264cf?format=full
```
{
 "id": "16a260bfcfb264cf",
 "threadId": "16a260bfcfb264cf",
 "labelIds": [
  "IMPORTANT",
  "CATEGORY_PERSONAL",
  "Label_15",
  "INBOX"
 ],
 "snippet": "test",
 "historyId": "837965",
 "internalDate": "1555416469000",
 "payload": {
  ...
  }
```

The thread id is the old format.

So I was waiting to switch to new ones when the API starts returning new formats, which it never did.

Even if I pull the message using the new format:
https://www.googleapis.com/gmail/v1/users/me/messages/msg-f:1630972392001135823?format=full
It still shows old style ids in the response!
```
{
 "id": "16a260bfcfb264cf",
 "threadId": "16a260bfcfb264cf",
 ...
}
```

So I thought maybe they will not switch to new id format after all.

But now it seems like they are deprecating the old format (standard deprecation practice - they only remove it in a small percentage of page loads first).

You can try to start using the new message ids when parsing DOM. See if it causes any trouble. If not, then we can switch to look for the new ones.
